### ISSUE TITLE
是否有PAC失效了？

### ISSUE THREAD

**Issue by IRISlMaple** [Alvin9999/new-pac#10]
一直在用PAC (pac1.nagro.net)，对我来说效果也是最好的。
今天好像连接不上服务器了，请问下是否真的失效了？
是否还会启用呢？
谢谢。
再来就是感谢作者的无私奉献~！^_^~~~

**Comment by Alvin9999** [comment]
PAC (pac1.nagro.net)这个节点目前确实已经失效，你可以切换成其它地址来使用，或者下载新的PAC版，有新的节点。同时，建议你也可以试试goagent版和goproxy版，这是我主要推荐的。

**Comment by IRISlMaple** [comment]
非常感谢~！

2016-10-12 8:50 GMT+08:00 自由上网 <notifications@github.com>:

**Comment by IRISlMaple** [comment]
主要也是因为GOAGENT和GOPROXY的速度不理想~~~

2016-10-12 8:50 GMT+08:00 自由上网 <notifications@github.com>:
