### ISSUE TITLE
集合版更新动态

### ISSUE THREAD

**Issue by Alvin9999** [Alvin9999/new-pac#1001]
目前除trojan-go以外的工具都已恢复，请运行ip更文件来同步。如果多款工具更新ip后还是无法使用，多半是被系统默认自带的防火墙和杀毒软件干扰了，可以关闭它们再试试看。

**Comment by yDan** [comment]
Astar vpn 已经挂掉了。还能恢复吗？

**Comment by Amoour** [comment]
为啥我一个都用不了呢？

**Comment by Alvin9999** [comment]
> 为啥我一个都用不了呢？

关闭系统自带防火墙和杀毒软件，重新更新ip，可以优先尝试goflyway、ssr、ss、ss-kcptun、etgo   很多人在用了

**Comment by JaniceZD** [comment]
现在还是不行哦  更新了ip和关闭杀毒软件也不行

**Comment by Alvin9999** [comment]
> 现在还是不行哦 更新了ip和关闭杀毒软件也不行

优先尝试下ssr、ss

**Comment by yy0535** [comment]
为啥我一个都用不了呢？都非常慢还卡

**Comment by Alvin9999** [comment]
> 为啥我一个都用不了呢？都非常慢还卡

试试SSR

**Comment by wushen789** [comment]
基本上所有的都显示这个：WARNING: cannot verify gitlab.com's certificate, issued by '/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA':
  Unable to locally verify the issuer's authority.

**Comment by Alvin9999** [comment]
> 基本上所有的都显示这个：WARNING: cannot verify gitlab.com's certificate, issued by '/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA':
> Unable to locally verify the issuer's authority.

用ip2来更新看看

**Comment by wushen789** [comment]
ip2    WARNING: cannot verify cdn.jsdelivr.net's certificate, issued by '/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA':
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 200 OK

**Comment by yy0535** [comment]
> > 为啥我一个都用不了呢？都非常慢还卡
> 
> 试试SSR

一个都打不开，我刚刚试过了都不行，SSR也不行

**Comment by Alvin9999** [comment]
嗯，SSR又被封锁了。这两天封锁很严重。可以试试goflway和v2ray，每个都有4个ip。

**Comment by Alvin9999** [comment]
北京时间2020年10月26日23点14分：这两天封锁特别严重，有的工具更新后很快又被封了，但仍然会继续更新。可以优先尝试Goflyway、v2ray、Etgo、SS、SSR等工具。

**Comment by hunanker** [comment]
谢谢您的实时动态通知，最近确实封的厉害，一直稳定的astar今天都挂了，现在又恢复了，万分感谢。

**Comment by Alvin9999** [comment]
北京时间2020年10月27日6点00分：可以优先尝试Etgo、v2ray、SS、SSR工具。

**Comment by Alvin9999** [comment]
> 谢谢您的实时动态通知，最近确实封的厉害，一直稳定的astar今天都挂了，现在又恢复了，万分感谢。

好

**Comment by Alvin9999** [comment]
北京时间2020年10月27日7点47分：可以优先尝试Etgo、v2ray、Brook、SSR工具。

**Comment by jap33** [comment]
v2 ip1.2.3无法使用

**Comment by Alvin9999** [comment]
北京时间2020年10月27日16点53分：可以优先尝试集合版SSR、v2ray工具，或Astar版

**Comment by Alvin9999** [comment]
北京时间2020年10月27日19点50分：更新4个v2ray地址

**Comment by yDan** [comment]
这种那么强烈的封锁一般会延续多长时间的？国庆节都没有封锁那么厉害，这几天是什么节日，为什么封锁那么猛烈

**Comment by yDan** [comment]
这种那么强烈的封锁一般会延续多长时间的？国庆节都没有封锁那么厉害，这几天是什么节日，为什么封锁那么猛烈

**Comment by Alvin9999** [comment]
> 这种那么强烈的封锁一般会延续多长时间的？国庆节都没有封锁那么厉害，这几天是什么节日，为什么封锁那么猛烈

开会。持续多久不是很清楚。

**Comment by Alvin9999** [comment]
北京时间2020年10月28日7点03分：可以优先尝试集合版v2ray、SSR、SS工具，或Astar版。

**Comment by yDan** [comment]
astar 也挂掉了。

**Comment by Alvin9999** [comment]
> astar 也挂掉了。

嗯，封锁很严重。可以试试集合版v2ray、SSR、SS，应该都能用了。

**Comment by Alvin9999** [comment]
北京时间2020年10月28日13点02分：可以优先尝试集合版SSR、v2ray、SS工具。

**Comment by Alvin9999** [comment]
北京时间2020年10月28日19点20分：可以优先尝试集合版的SSR、v2ray、SS、trojan-go工具，也可以尝试Astar版、FreeGate版、SkyZip版。Astar版有点不稳定，优先尝试新加坡、加拿大节点。

**Comment by jap33** [comment]
v2 1 .2不行。trojan可以。

**Comment by Alvin9999** [comment]
> v2 1 .2不行。trojan秒挂。

推测是不同地区使用效果不同。有的人觉得v2ray ip1和ip2很快。

**Comment by Alvin9999** [comment]
> v2 1 .2不行。trojan秒挂。

试下v2ray  ip3，刚更新了下

**Comment by Alvin9999** [comment]
> v2 1 .2不行。trojan秒挂。

v2ray ip1已更新

**Comment by Alvin9999** [comment]
北京时间2020年10月29日6点50分：可以优先尝试集合版的SSR、v2ray、SS工具，也可以尝试Astar版、FreeGate版、SkyZip版。Astar版有点不稳定，优先尝试新加坡、加拿大节点。

**Comment by yDan** [comment]
Asatar用不了

**Comment by Alvin9999** [comment]
> Asatar用不了

封锁严重，用不了就换其它工具。

**Comment by Alvin9999** [comment]
北京时间2020年10月30日11点04分：可以优先尝试集合版的SSR、v2ray、SS、Goflyway（ip1、ip2、ip3、ip4）、Brook工具，也可以尝试FreeGate版。

**Comment by Alvin9999** [comment]
北京时间2020年10月31日8点10分：集合版大多数工具已恢复。

**Comment by jap33** [comment]
![2020_07_25_09_22_29](https://user-images.githubusercontent.com/15140842/98612509-44d24c80-232f-11eb-822a-14602ae815ed.gif)

**Comment by jap33** [comment]
![2020_07_25_09_25_37](https://user-images.githubusercontent.com/15140842/98612779-d477fb00-232f-11eb-88c1-d7412d059767.gif)

**Comment by ali99188** [comment]
反馈一下：
2020年11月18日更新的chrome87高内核版浏览器，有一个问题：不能使用ctrl+w键关闭标签页，我用其它绿色版都没有此问题，能不能修复一下？谢谢！

**Comment by ali99188** [comment]
我说的其它绿色版，是指别的网站下载的最新chrome87绿色版。

**Comment by ali99188** [comment]
另外这个clash翻墙很快，但是有一个问题，就是会泄露自己的DNS，不知道这个能不能修复一下，如果不能，可能是软件设计的问题，那这样用也可以，毕竟多了一款翻墙软件，但是使用者必须知道：它虽然很好用，但是有这个风险。

**Comment by Alvin9999** [comment]
@ali99188  用鼠标点击关闭一下标签页也花不了多少时间吧。clash泄露DNS指的是什么？你是怎么测试的？

**Comment by Alvin9999** [comment]
@ali99188 使用clash时，如果你想测试clash的ip，要用一个被墙的ip测试网站来测试才行，因为clash是自动代理网站，国内网站不走代理，所以用国内ip测试网站测试出来的ip是自己的本地ip。

**Comment by Alvin9999** [comment]
比如这个[国外ip地址查询](https://allinfa.com/check-online-ip-address.html)
