### ISSUE TITLE
是否可以自动化地感知当前免费账号已经更换

### ISSUE THREAD

**Issue by MuYunyun** [Alvin9999/new-pac#1004]
### 背景

关于 [ss免费账号](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7) 中的账号最近可能半天就更新一次, 请问楼主大大是否有邮件或电报群或者其它啥方式, 能让我们自动化地感知到当前某某账号已经失效了。

**Comment by Alvin9999** [comment]
这是个好主意，但是目前没有这个计划。
