### ISSUE TITLE
v2ray安卓客户端无法fq

### ISSUE THREAD

**Issue by badongdyc** [Alvin9999/new-pac#1008]
我用v2ray安卓客户端连接集合版里的v2ray服务器，电脑可以正常fq，安卓却不行，请问是什么原因呢

**Comment by Alvin9999** [comment]
可能是没有配置好的缘故，好好检查下

**Comment by badongdyc** [comment]
我看了配置跟电脑一模一样的。。

**Comment by Alvin9999** [comment]
电脑和手机是同一网络吗

**Comment by badongdyc** [comment]
是的

**Comment by Alvin9999** [comment]
理论上不应该。同一网络、同一节点信息应该是都可以，或者都不可以才对哦。推测是手机环境，比如手机有没有安装杀毒软件之类的。这个得你自己来排查才行。

**Comment by badongdyc** [comment]
就是啊，所以我很纳闷。。手机也没安装杀毒软件啊。唉，我看集合版里面v2ray速度挺快的，我就想拿到手机上用，结果给我闹这出

**Comment by Alvin9999** [comment]
手机填写节点信息的界面截图看一下，帮你检查下

**Comment by badongdyc** [comment]
![Screenshot_2020-10-28-11-09-27-475_com v2ray ang](https://user-images.githubusercontent.com/17975624/97386184-430b9080-190e-11eb-9b77-541459184449.png)

**Comment by Alvin9999** [comment]
最后一个跳过证书验证选空或者true。这个false的意思是不跳过证书验证，实际上没有验证，应该是这个问题。你试试看。

**Comment by badongdyc** [comment]
试了，还是不行。

**Comment by Alvin9999** [comment]
那就不知道了

**Comment by badongdyc** [comment]
好吧。感谢回复

**Comment by bannedbook** [comment]
用这个 [安卓vpn](https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6#v2vpn)
