### ISSUE TITLE
最近是有什么事件么，vultur申请了几个vps都连不上

### ISSUE THREAD

**Issue by wufan-bit** [Alvin9999/new-pac#1009]
昨天弄了一个今天就挂了，现在申请了几个vps xshell也连不上了

**Comment by Alvin9999** [comment]
如果ping不通，那么多半就是ip被墙了。近期封锁严重，应该时开到了被墙ip。先开新服务器，再删旧服务器，可以保证ip不是重复的。

**Comment by wufan-bit** [comment]
> 如果ping不通，那么多半就是ip被墙了。近期封锁严重，应该时开到了被墙ip。先开新服务器，再删旧服务器，可以保证ip不是重复的。

经常出现这样的情况，用了一段时间无法访问外放了，可以Ping通，去站长之家测ip国内也是通的，但是端口国内国外除了22都是关闭的，这是什么原因？

**Comment by 6923403** [comment]
> 如果ping不通，那么多半就是ip被墙了。近期封锁严重，应该时开到了被墙ip。先开新服务器，再删旧服务器，可以保证ip不是重复的。

好像前天开始   一天端口得换个2-3次 最近力度大了？
