### ISSUE TITLE
要不要把SSR换成SS试试？

### ISSUE THREAD

**Issue by senRsl** [Alvin9999/new-pac#101]
感觉这几天都封出规律来了。

我记得以前研究SS跟SSR的时候，SSR好像是有特征的，可以根据特征来拦截。反而母版的SS没有。

**Comment by Alvin9999** [comment]
什么意思？SSR不好用吗？你说的问题我也在考虑，主要是考虑到安全，才换的SSR账号。

**Comment by senRsl** [comment]
不是不好用，是我以前研究ss跟ssr的时候，记得好像ssr是有特征可查，可以根据特征被屏蔽的。我记得之前看ss作者说的也有这么回事，刚翻了下，找不到了。。。。这几天看服务器挂的太快才提个issues，要不要试试。。。。

技术上来说，这俩现在来说各有利弊吧。。。。。

**Comment by Alvin9999** [comment]
最近使用人数有点多。。。。如果是被封掉，ip会用不了，但ip没事，只要重新换端口就没问题。

之前网上有报道，广东那边使用ss账号被检测出来了，之后我才换用了SSR帐号。

**Comment by senRsl** [comment]
好吧，现在技术更新太快，我也不知道了。。。。。。。。

最后
谢谢楼主为新中国的伟大复兴做出的努力！

**Comment by Alvin9999** [comment]
不客气，谢谢你善意的建议
