### ISSUE TITLE
v2ray+ws+tls，Xshell可以连服务器，但是不能上网

### ISSUE THREAD

**Issue by UselessRage** [Alvin9999/new-pac#1010]
前两天还可以，今天就不行了，换了好几个端口也没用

**Comment by Alvin9999** [comment]
这个模式换端口不行，你换个传输方式看看

**Comment by UselessRage** [comment]
请问哪一种传输方式比较好呢，我之前看说ws+tls最安全结果用了一两天就用不了了

**Comment by Alvin9999** [comment]
> 请问哪一种传输方式比较好呢，我之前看说ws+tls最安全结果用了一两天就用不了了

最近是因为封锁加重导致的。可以试试看tcp。
