### ISSUE TITLE
ssr 全部默认   搭建好。只能用一天好好的，第二天就又超时了？？？

### ISSUE THREAD

**Issue by xiaoer371** [Alvin9999/new-pac#1012]
如题，  各位大佬什么情况？

**Comment by xiaoer371** [comment]
vultr的服务器，日本站。   但是搭建的V2ray 每天都很正常。  ssr 是手机上用的，就只用一天，第二天又超时，重新安装又正常，之后第二天又不超时了。

**Comment by Alvin9999** [comment]
最近封锁特别严重，端口被封的厉害，如果ip没有被墙多半是端口被封了，换端口

**Comment by xiaoer371** [comment]
@Alvin9999 问题是重新安装 还是这个端口， 就又能用啦？？？  感觉不是端口问题吧？

**Comment by Alvin9999** [comment]
> @Alvin9999 问题是重新安装 还是这个端口， 就又能用啦？？？ 感觉不是端口问题吧？

如果是同一个端口就不是这个问题。

**Comment by Devinwon** [comment]
我的也是超时，ssh可连，IP可达，ssr换了几次端口还是不行，

**Comment by Alvin9999** [comment]
推荐 加密方式：salsa20  协议：auth_aes128_sha1 混淆： http_post

**Comment by Alvin9999** [comment]
使用ssr脚本的时候先安装 4. 安装 libsodium(chacha20)

**Comment by Devinwon** [comment]
谢谢，我尝试下

**Comment by xiaoer371** [comment]
@Alvin9999 好的  我试一下，感谢

**Comment by Devinwon** [comment]
可以啦，谢谢

**Comment by Alvin9999** [comment]
> 可以啦，谢谢

OK

**Comment by Alvin9999** [comment]
@xiaoer371 @Devinwon 顺便提醒下，vultr韩国速度不错，bbrplus提速效果最好

**Comment by xiaoer371** [comment]
@Alvin9999 用了一上午，现在ip被封了，  得重新整一个了。  为什么搞个外贸的，都老封！！！ 心累😢
