### ISSUE TITLE
反馈一个问题：每次点击“9.Etgo翻墙.cmd”，都会触发windows defender

### ISSUE THREAD

**Issue by ali99188** [Alvin9999/new-pac#1013]
我是用windows10系统，好一段时间以来，每次更新“谷歌翻墙浏览器86高内核版”，点击“9.Etgo翻墙.cmd”，都会触发windows defender检测这个文件有威胁，位置在：Etgo\Eagle_Tunnel_Go\publish\config\hosts\neo.hosts，可能里面有些被阻止的链接被windows defender视为敏感，请处理一下，或者在文件说明的地方写一个提示，不然不知道的人会以为有病毒。
另外感谢Alvin9999对此网站的维护和更新，我这里几年时间里，几乎只能靠这个软件翻墙，对你们致以无比的敬意和感恩！还有你们新增的V2free机场，very very good！这样方便的机场真是越多越好！谢谢！

**Comment by Alvin9999** [comment]
好的，谢谢反馈和支持

**Comment by badongdyc** [comment]
V2free机场 是什么？

**Comment by Alvin9999** [comment]
@badongdyc 
[v2ray机场](https://github.com/Alvin9999/new-pac/wiki/V2free%E6%9C%BA%E5%9C%BA)

**Comment by ali99188** [comment]
反馈一下：2020年11月3日更新的高核版还是这个情况。另外，点击“8.SS-Kcptun翻墙.cmd”会出现一个错误提示，不能用，我不知道在别的电脑上面会不会也这样。其它的都很好，特别是新增的clash翻墙感觉很快。谢谢！

**Comment by ali99188** [comment]
还有一个反馈：国外的高速节点都能上去，除了俄罗斯的速度最快外，国内的几个节点，我这几天天天翻墙，没有一次上去过，另外国内节点会不会暴露使用者的IP？

**Comment by ali99188** [comment]
我上面提到的节点，是“V2free机场”里面的节点，忘了写了。这个机场很方便，谢谢！

**Comment by Alvin9999** [comment]
8.SS-Kcptun翻墙.cmd 是什么错误提示呢？

不会。

更新一下最新的节点，然后试试看。

**Comment by ali99188** [comment]
![捕获](https://user-images.githubusercontent.com/73689818/98884124-5308a000-24ca-11eb-9646-6f9041989a8f.PNG)
![捕获2](https://user-images.githubusercontent.com/73689818/98884131-5734bd80-24ca-11eb-931d-54e2c7a321f2.PNG)

**Comment by ali99188** [comment]
我是windows10 2016_ltsb系统。
9.Etgo翻墙初次打开时，windows defender还是会提示发现恶意软件，是“neo.hosts”文件，不知道里面哪个微软的链接被它视为“恶意”了。

**Comment by ali99188** [comment]
我试了一下，还搞不清楚是因为哪个链接，是不是与软件系统激活的哪个相关网站被屏蔽有关？

**Comment by Alvin9999** [comment]
有没有安装NET Framework 4.0？

**Comment by Alvin9999** [comment]
etgo那个允许一下就好了，小众工具就会这样。

**Comment by ali99188** [comment]
我查看了一下“windows功能”，我这里安装有.net3.5和4.6。我刚才用5.SS翻墙，用“2、ip2更新”也出现了跟上面一样的提示，相同的电脑配置和软件，以前这个SS翻墙都没有错误提示，我想可能是Shadowsocks软件的问题，也可能是我电脑有这个问题，如果别人没出现，请忽视。

**Comment by ali99188** [comment]
确实是这个SS软件，我在电脑中打开我以前保存的SS软件，没有这个提示，可以正常打开。

**Comment by Alvin9999** [comment]
目前没有其他人反馈这个问题，我也不知道是什么原因，可能是最新版不兼容某些系统的原因。再观察看看其他人的反馈。可能会再下次更新时换上旧版。

**Comment by ali99188** [comment]
好的。
