### ISSUE TITLE
退出软件（翻墙）之后。使用自己电脑的浏览器打开网页很慢

### ISSUE THREAD

**Issue by caojinlong-827** [Alvin9999/new-pac#1019]
使用完软件之后，退出软件。然后使用自己安装的浏览器，火狐、Google、或者搜狗高速浏览器打开网页，无论是什么网页（比如百度）、，都会变得很卡，打开很慢，超时。求大佬帮忙解决

**Comment by Alvin9999** [comment]
打开IE浏览器-internet选择-连接-局域网设置，看看有没有什么代理被选上了，如果有就去掉它。

**Comment by Alvin9999** [comment]
理论上翻墙软件只是便携式的，没安装应该不会影响其它浏览器的，所以这个问题有点怪。

**Comment by caojinlong-827** [comment]
我也很纳闷呀，但是确实是有这种情况。我在笔记本上又搭建了个xp的虚拟机，使用完软件。也是发现有这样的问题。即使是重置网络，也还是有打开网页缓慢的问题。连打开百度首页也很慢。您有好的建议或者方法吗？

**Comment by Alvin9999** [comment]
现在情况如何？

**Comment by caojinlong-827** [comment]
> 现在情况如何？

还是老样子，找了很多解决方式，也不起任何作用

**Comment by Alvin9999** [comment]
电脑有没有国产安全卫士或者杀毒软件？

**Comment by caojinlong-827** [comment]
有的，有电脑管家，诊断修复了一下网络，还是老样子。我在笔记本上搭建了个xp的虚拟机，试着使用了一下软件。也是发现有这样的问题。

**Comment by Alvin9999** [comment]
不推荐用腾讯的电脑管家，这个跟网络防火墙有千丝万缕的关系。

**Comment by Alvin9999** [comment]
腾讯、360产品都有问题。

**Comment by caojinlong-827** [comment]
好的，已经退了。估计我得重装系统，才会解决这个问题了

**Comment by caojinlong-827** [comment]
对了，电脑的微信客户端，点开公众号的链接，也会变慢

**Comment by Alvin9999** [comment]
退出国产卫士和杀毒软件，并禁用开机启动，然后重启下电脑再试试看。如果还不行的话，那这个问题确实有点怪怪的。

**Comment by caojinlong-827** [comment]
好的，谢谢哈

**Comment by AnyWAT** [comment]
> 退出国产卫士和杀毒软件，并禁用开机启动

仅仅退出并禁用开机启动或许还不够，也许有隐藏的服务一直运行。
要么卸载，要么 Autoruns 禁用相应的服务。

**Comment by AnyWAT** [comment]
https://twitter.com/Poohskikill/status/1603414685503868928

![FkB5EznaEAAKFPu](https://user-images.githubusercontent.com/37962734/208097378-2bc4d52a-c9c3-48a2-be21-095b38f28c90.jpg)

**Comment by Alvin9999** [comment]
> https://twitter.com/Poohskikill/status/1603414685503868928
> 
> ![FkB5EznaEAAKFPu](https://user-images.githubusercontent.com/37962734/208097378-2bc4d52a-c9c3-48a2-be21-095b38f28c90.jpg)

问了客服，推荐的机场没用这个面板。
