### ISSUE TITLE
请问一下专家：V2free机场提供的节点，可不可以作为Tor的前置代理？

### ISSUE THREAD

**Issue by ali99188** [Alvin9999/new-pac#1020]
我暂时还没有成功，因为v2rayn不能直接代理除了普通浏览器以外的软件，我准备用proxycap转换一下，还在试验当中。不知道这些节点能不能使用？谢谢！

**Comment by Alvin9999** [comment]
需要借助第三方工具，理论上是可以的

**Comment by ali99188** [comment]
好的，谢谢！

**Comment by fqnews** [comment]
tor 设置为 同时使用 obfs4 网桥 和 socks5 v2ray代理 127.0.0.1 10808
就可以了
