### ISSUE TITLE
无法登陆国内网站

### ISSUE THREAD

**Issue by jacknnnbauer** [Alvin9999/new-pac#103]
我使用的是ss高内核版本。
上国外网站速度很快。但是无法上国内网站。比如百度，京东等等。
系统代理我选择的是全局代理模式。
但是我把它切换为PAC模式好像也不顶用。
请问，如何解决？

**Comment by Alvin9999** [comment]
为了节省服务器流量，对服务器进行了禁用国内网站的限制。如果是访问没有被封的网站，可以用普通浏览器。
