### ISSUE TITLE
clash翻墙IP地址与DNS不符

### ISSUE THREAD

**Issue by Wilson2003** [Alvin9999/new-pac#1031]
clash翻墙IP地址与DNS不符，如何设置？或者后续版本能否解决这个问题？

“你的 DNS 服务器所在的国家不同于你的 IP 地址所在的国家。通常情况下，这表明你试图隐藏自己的位置。”

**Comment by Alvin9999** [comment]
哪个网站弹出的这样的提示？

**Comment by Alvin9999** [comment]
多截图点图片

**Comment by Wilson2003** [comment]
https://whoer.net/zh#

**Comment by Alvin9999** [comment]
好的，收到

**Comment by Alvin9999** [comment]
试试这个[ip检测地址](https://dnschecker.org/ip-location.php)

**Comment by Alvin9999** [comment]
因为clash是自动代理，如果你发的这个网站的dns检测是启用了自动检测，用了国内的dns检测，那么就会出现这个结果。因为clash打开国内网站都走本地代理，不走国外代理。

**Comment by bannedbook** [comment]
https://thesafety.us/dns-leak

**Comment by Alvin9999** [comment]
不是问题。PAC自动代理的工具都是这样，这是为了节省服务器流量以及提高打开国内网站的体验。

**Comment by Alvin9999** [comment]
@Wilson2003  你用这个DNS检测网站来检测：https://thesafety.us/dns-leak
