### ISSUE TITLE
不能用了。

### ISSUE THREAD

**Issue by a120476536** [Alvin9999/new-pac#1034]
楼主大佬，求更新。ss不管用了。

**Comment by Alvin9999** [comment]
哪个ss呢？

**Comment by Alvin9999** [comment]
目前4个节点都是正常的哦

**Comment by Alvin9999** [comment]
目前4个节点都是正常的哦

**Comment by jinyumarine** [comment]
ss不能用，ssr德国不能用，仅剩另一个ssr

**Comment by jinyumarine** [comment]
> 目前4个节点都是正常的哦

ss两个基本上不能用，偶见连接上，但是龟速，SSR德国不能用，现在只剩西雅图正常

**Comment by Alvin9999** [comment]
你用的什么客户端？

**Comment by jinyumarine** [comment]
> 你用的什么客户端？

SS,SSR都安装了，SS即使能连接，也是很不稳定，并且龟速，但是基本上是没下行网速的，SSR也只能西雅图正常使用

**Comment by Alvin9999** [comment]
节点很多人在用，速度720p，可能是你的网络环境问题。你可以用西雅图节点，或者也可以考虑根据教程搭建自己的SS/SSR节点。

**Comment by Alvin9999** [comment]
刚刚更新了下德国和瑞士节点，可以再试试看。

**Comment by Alvin9999** [comment]
刚刚更新了下德国和瑞士节点，可以再试试看。
