### ISSUE TITLE
推荐一个YouTube视频平台rumble.com

### ISSUE THREAD

**Issue by wahello** [Alvin9999/new-pac#1038]
推荐一个YouTube视频平台[rumble.com](https://rumble.com/)

**Comment by Alvin9999** [comment]
这个网站跟YouTube是什么关系？试了一些关键词都搜不到视频。

**Comment by wahello** [comment]
现在YouTube开始要删视频了.
播主也要过去啊 [这里](https://nordvpn.com/blog/youtube-alternatives/) https://nordvpn.com/blog/youtube-alternatives/ 有很多可以替代的平台,大家不要在一家吊吧
