### ISSUE TITLE
v2rayN 一直闪退 打不开

### ISSUE THREAD

**Issue by jiachen-xu95** [Alvin9999/new-pac#1039]

**Comment by Alvin9999** [comment]
有没有下载内核

**Comment by jiachen-xu95** [comment]
> 有没有下载内核
感谢大佬提醒，目前已经可以了

**Comment by jiachen-xu95** [comment]
> 有没有下载内核

v2rayN代理设置选哪个好呢 目前看油管视频只能维持360p

**Comment by Alvin9999** [comment]
免费节点用的人多，速度不快。如果追求速度，可以考虑根据教程自己搭建v2ray节点，或者考虑付费v2ray。

**Comment by jiachen-xu95** [comment]
> 免费节点用的人多，速度不快。如果追求速度，可以考虑根据教程自己搭建v2ray节点，或者考虑付费v2ray。

为什么我连接了我买的美国服务节点 日志显示还是德国呢

**Comment by Alvin9999** [comment]
> > 免费节点用的人多，速度不快。如果追求速度，可以考虑根据教程自己搭建v2ray节点，或者考虑付费v2ray。
> 
> 为什么我连接了我买的美国服务节点 日志显示还是德国呢

可以用这个网站来查询ip，比较准，https://www.ipip.net/ip.html

**Comment by jiachen-xu95** [comment]
> > > 免费节点用的人多，速度不快。如果追求速度，可以考虑根据教程自己搭建v2ray节点，或者考虑付费v2ray。
> > 
> > 
> > 为什么我连接了我买的美国服务节点 日志显示还是德国呢
> 
> 可以用这个网站来查询ip，比较准，https://www.ipip.net/ip.html

![image](https://user-images.githubusercontent.com/42468123/101275132-454eed80-37de-11eb-9fcb-41685ac2c24a.png)
连接显示这个信息 可是这不是我的节点信息，ip也更新过了

**Comment by Alvin9999** [comment]
你用的是我的节点噢

**Comment by Alvin9999** [comment]
这个节点是德国节点。你在哪里购买的节点？购买节点后要导入到软件中。

**Comment by jiachen-xu95** [comment]
> 这个节点是德国节点。你在哪里购买的节点？购买节点后要导入到软件中。

根据你说的教程 我在https://my.vultr.com/这里买的。
1.用ProxySu配置好了 启动v2ray.exe 
2.启动内核中的翻墙

整体的流程有什么问题吗?

**Comment by jiachen-xu95** [comment]
> 这个节点是德国节点。你在哪里购买的节点？购买节点后要导入到软件中。

切换任何节点 都是这个德国节点 我不太懂这些怎么弄

**Comment by Alvin9999** [comment]
明白了。你用ProxySu搭建完成后，有个vmess地址，把它复制下来，然后右键“v2rayN”图标，选择“从剪切板批量导入url”，如下图
![111](https://user-images.githubusercontent.com/12132898/101276857-dcba3d80-37ea-11eb-9eaa-b1083d4174af.jpg)

**Comment by Alvin9999** [comment]
如果忘记了vmes地址，在文件夹中有url的txt文档。一键搭建ProxySu教程中有提到文件夹，可以看下教程中的图片。

**Comment by jiachen-xu95** [comment]
> 如果忘记了vmes地址，在文件夹中有url的txt文档。一键搭建ProxySu教程中有提到文件夹，可以看下教程中的图片。

非常感谢 希望在一键ProxySu教程的最后附上这部操作 谢谢

**Comment by Alvin9999** [comment]
好的

**Comment by Alvin9999** [comment]
提醒一下，vultr韩国、日本服务器比美国服务器要快一些
