### ISSUE TITLE
有人能教教我用shadowrocket吗？已经按教程输入，但无法科学上网

### ISSUE THREAD

**Issue by png0957** [Alvin9999/new-pac#104]

**Comment by Alvin9999** [comment]
4个账号是否都已测试？

**Comment by Alvin9999** [comment]
2017年8月15日晚：据测试和反馈，shadowrocket有不稳定的表现在。推荐使用Potatso Lite，这个软件在app商店里可以直接搜索，目前售价6元。Potatso Lite使用方法可以参考shadowrocket的使用方法。
