### ISSUE TITLE
SS账号貌似挂了

### ISSUE THREAD

**Issue by jinyumarine** [Alvin9999/new-pac#1042]
SS账号貌似挂了
没下行流量了
麻烦请检查
谢谢

**Comment by Alvin9999** [comment]
检查了，2个SSR节点和1个SS节点都是正常的，顺便重启了下，你再试试看。

**Comment by jinyumarine** [comment]
我发觉账号老是抽风，时好时不好，过一阵又好了，用着用着又抽风了

**Comment by Alvin9999** [comment]
这可能是用的人太多的缘故。如果某个账号不好用，试试另外2个。还有一个方法就是自己根据教程搭建账号，这肯定会稳定很多，而且速度也会很快。免费账号用的人太多，所以进行了限速250kb/s。

**Comment by Alvin9999** [comment]
你是具体用的哪个账号抽风呢？

**Comment by jinyumarine** [comment]
比较不抽风的只有西雅图账号，SS账号特别明显

**Comment by Alvin9999** [comment]
今天再观察看看

**Comment by Alvin9999** [comment]
新增了2个韩国帐号
