### ISSUE TITLE
错误503该如何解决？

### ISSUE THREAD

**Issue by leekbillow** [Alvin9999/new-pac#1043]
v2ray前几天上不去了报错503，想着升级下脚本提示已停用，导到[那边](https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this)（那里不适合小白，门槛太高）去了，那里教程不太详细迁移出了各种毛病，最后还是找回[这里](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)，通通卸载然后安装。
但是重装后仍然提示503，请问应该如何解决呢？

**Comment by leekbillow** [comment]
更换了端口，不报503了，速度变成0了……

**Comment by Alvin9999** [comment]
可以重装写vps系统，然后再安装。

**Comment by leekbillow** [comment]
> 可以重装下vps系统，然后再安装。

找到原因了，因为我想把旧配置json给新脚本用所以出了毛病
<s>我是傻逼</s>

**Comment by Alvin9999** [comment]
好的
