### ISSUE TITLE
想从国外翻到国内，但是在国内云服务器上安装后一直无法连接

### ISSUE THREAD

**Issue by SENAmylove** [Alvin9999/new-pac#1046]
您好，我现在身处国外，但是想用SSR翻到国内。我在腾讯云上安装好SSR之后（centos7.6），电脑和手机的客户端连接到服务器都无法正常上网（百度打不开），手机端测试连接显示 Unable to resolve host "www.google.com":No address associated with hostname 。我是个新手，尝试了很多次没法解决，请问有什么办法吗？

**Comment by Alvin9999** [comment]
把vps防火墙关闭一下

**Comment by WCBBearing** [comment]
国外到国内还需要翻墙吗？
