### ISSUE TITLE
SSR模式下Google打不开了？

### ISSUE THREAD

**Issue by Motorcure** [Alvin9999/new-pac#1047]
其它网站都正常，就Google打不开了，貌似昨天还是正常的，这是什么情况？

**Comment by WCBBearing** [comment]
ip 地址又被封了吧

**Comment by Motorcure** [comment]
> ip 地址又被封了吧

都已经翻墙成功了啊。。。

**Comment by WCBBearing** [comment]
能连接不代表有流量啊

**Comment by Motorcure** [comment]
> 能连接不代表有流量啊

其它需要翻墙的网站都能正常访问的

**Comment by WCBBearing** [comment]
youtube  facebook 能打开？

**Comment by Motorcure** [comment]
> youtube facebook 能打开？

当然啊。。。不看issue内容的吗？？？

**Comment by WCBBearing** [comment]
能打开 youtube 和 facebook 打不开google 这种情况还真不常见，应该不是什么问题，重新登录下试试

**Comment by Alvin9999** [comment]
试试这个https://www.google.com.hk

**Comment by Motorcure** [comment]
> 试试这个https://www.google.com.hk

目前就是用这个应付下，但是这个是带安全搜索的和谐版。。。

**Comment by Alvin9999** [comment]
你是自己搭建的ssr账号，还是用的我分享的免费账号呢？

**Comment by Motorcure** [comment]
> 你是自己搭建的ssr账号，还是用的我分享的免费账号呢？

是分享的帐号，现在又可以了，真是太奇怪了。。。
