### ISSUE TITLE
为什么当我访问www.dlsite.com时会被重定向至www.kernel.org

### ISSUE THREAD

**Issue by yuijker** [Alvin9999/new-pac#1049]
当我试图访问www.dlsite.com时，页面会被重定向至www.kernel.org。

**Comment by Alvin9999** [comment]
用的什么？

**Comment by yuijker** [comment]
Brook的ip1，其他的翻墙方案里，你们故意把dlsite.com404我也忍了，唯独Brook的ip1直接把我重定向至Linux kernel的网站，我不问你我问谁。

**Comment by Alvin9999** [comment]
屏蔽了黄色网站。
