### ISSUE TITLE
作者應該用這個項目代替自己手動更新ip

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#105]
如果使用這個基於goa修改的代理就可以免去手動更新ip麻煩了，讓作者的作品更加傻瓜化也給那些小白們提供一個免去了不會折騰的煩惱，雖然gop已經普及這麼多年，但是還有很多人還是不會自己折騰goa的。
https://github.com/out0fmemory/GoAgent-Always-Available

**Comment by Alvin9999** [comment]
这个项目并不完美，全是gws ip，没有gvs ip，某些封锁强的地区会用不了。xxnet论坛有人反馈直接把ip导入进去，还是无法翻墙。

**Comment by Alvin9999** [comment]
现在我的思路是，采用这个项目的gws ip以及自己搜的gvs ip，然后一起更新。

**Comment by caofengzi** [comment]
俺還是贊成用這個做一個集成包，這樣gws ip讓程序自動維護，gvs ip可以用你的批處理讓使用者從自己的ip維護站點下載更新，這樣你只管維護gvs ip了，爾gws ip讓程序自己維護，這樣能夠減輕你的工作負擔。

**Comment by candy2107** [comment]
@caofengzi 
没必要这么做，除非你会写 python 把2个ip文件整合到一起
而且现在有soso版，如果你觉得ip不合适，自己搜就行了

**Comment by caofengzi** [comment]
@candy2107 soso版就是集成了那個自動搜索ip的goagent程序，還有xx-mini精簡版。
