### ISSUE TITLE
请教下 vultr  问题

### ISSUE THREAD

**Issue by xiaoer371** [Alvin9999/new-pac#1052]
从昨天开始梯子断了    之后mac一直连不上   一直报错。

Connection reset by *.*.*.* port 22    不知道怎么解决

**Comment by Alvin9999** [comment]
搭建的什么梯子？如果ip没有被封，试试换个端口。如果连不上vps，那么多半是ip被封了。需要换新服务器，新ip，开好新服务器后，把旧服务器删去即可。

**Comment by xiaoer371** [comment]
开新服务器 也是这样， 东京的服务器。

**Comment by Alvin9999** [comment]
把ip发出来，帮你测试下

**Comment by xiaoer371** [comment]
@Alvin9999    45.76.218.9

**Comment by Alvin9999** [comment]
都没有被墙。你也可以用自己的电脑ping一下
方法：https://jingyan.baidu.com/article/6f2f55a17154fdb5b93e6ca8.html

**Comment by xiaoer371** [comment]
但是连不上是什么原因？   Connection reset by 45.76.218.9 port 22   一直报这个错误~

**Comment by Alvin9999** [comment]
试试其它地区的vps

**Comment by Alvin9999** [comment]
一般晚高峰期丢包都会有点

**Comment by skidoo34** [comment]
从昨天开始遇到同样的问题，vultr换了10个不同地区的节点，丢包率80%以上

**Comment by xiaoer371** [comment]
今天我找到问题原因，  我这边  移动的丢包非常高，就等于上不了网。

**Comment by skidoo34** [comment]
> 今天我找到问题原因，  我这边  移动的丢包非常高，就等于上不了网。
> 
> 我换成电信的丢包就正常了。 @skidoo34    
> 
>  
> 
> 丢包问题节点，要么服务器那边， 要么我们这边的网络。  你试一下看看。

确实，我也是移动的网络 换其他的就好了
