### ISSUE TITLE
vultr账户被锁定求助

### ISSUE THREAD

**Issue by Giagoo** [Alvin9999/new-pac#1053]
早上起来，对方发邮件告诉我，我违反了使用政策，但是我按照教程开了服务器就挂着啥也没干，不知道为啥会被封禁，我回复对方可能封错了。对方发来一封这样的邮件，我要怎么回答才能解封呢？
![image](https://user-images.githubusercontent.com/41316613/105285540-93ce1500-5bef-11eb-9a63-c2fef0769181.png)

**Comment by Giagoo** [comment]
机票DTO-44NYY已由账户团队更新。关于:217.163.30.24

你好,

(关于这个问题，我们需要更多的资料。)

请详细回答以下问题:

*您使用我们的服务的目的是什么?
*你们在VPS上运行哪些软件包?
*是否有任何公司或网站与你的活动有关?(如果是，它们使用什么名称和url进行操作?)
*在这个虐待投诉中的活动与你做过的任何事情相似吗?你知道问题的根源是什么吗?
*如果我们选择取消挂起，您将采取什么措施来确保这种情况不再发生?

——Vultr Trust & Safety

若要更新或查看您的机票进度，请直接回复此邮件或访问:

https://my.vultr.com/support/view_ticket/?TICKETID=DTO-44NYY

感谢您使用Vultr.com

在Twitter上关注我们吧!

https://twitter.com/vultr

**Comment by Alvin9999** [comment]
我看到提到虐待服务器，你是BT下载？

**Comment by Giagoo** [comment]
> 到提到虐待服务器，你是BT下载？

你这么一说我想起来了，我好像还真bt下载过，有什么办法解决吗？我的账户还是没解封

**Comment by Alvin9999** [comment]
BT下载版权资源，服务器会被投诉。这个你可以按照它们的提示逐条解释下，承认错误，下次不会再这样了。

**Comment by Giagoo** [comment]
> BT下载版权资源，服务器会被投诉。这个你可以按照它们的提示逐条解释下，承认错误，下次不会再这样了。

我已经解释了，还是没解封，哎，再等等吧
