### ISSUE TITLE
Fair VPN无法导入Vmess

### ISSUE THREAD

**Issue by YoucanBaby** [Alvin9999/new-pac#1055]
作者大大你好，我自己搭建了V2Ray服务器，有可用的Vmess，但是Fair VPN无法导入Vmess，报错无法导入，请问要如何解决呢？

**Comment by Alvin9999** [comment]
你好，你是怎么导入的呢？报的什么错呢？

**Comment by YoucanBaby** [comment]
> 你好，你是怎么导入的呢？报的什么错呢？

通过vmess导入，配置选择的utp kcp，然后报错，就是error后面跟一长串乱码。最后，我在V2ray上，选择配置的shadowsocks，就能成功导入。

**Comment by Alvin9999** [comment]
是选择的第一个手动添加VPN吗

**Comment by Alvin9999** [comment]
也可以试试扫码导入，扫电脑上v2ranN的节点二维码，这个可以点击v2rayN的最上面第一排的第3个“分享”按钮就有二维码了。

**Comment by fqcdn** [comment]
Fair VPN vmess 不支持 kcp 模式，只支持 tcp/tls/ws 模式
