### ISSUE TITLE
这几天PAC 都不能用了？

### ISSUE THREAD

**Issue by plus888** [Alvin9999/new-pac#106]
好几天PAC 都不能用了？

**Comment by Alvin9999** [comment]
你说的是PAC版浏览器吗? 如果是的话，请使用最新版。目前测试前几个地址都正常。

**Comment by Alvin9999** [comment]
如果你尝试了最新版的所有PAC地址，都不能使用的话，说明你那里的网络环境不适合用PAC版了。那就换其它类型的软件，因为我分享的软件类型很多，每款软件都有可取之处，然而不同的地区封锁强度不同，网络类型不同，所以最好自己测试下。

**Comment by Alvin9999** [comment]
需要提醒的是，不管你用什么软件，都不要用国产杀毒软件，尤其是360，至少翻墙时不要用！国产杀毒软件会起干扰作用！

**Comment by plus888** [comment]
我一个杀毒软件都没有安装
你的前几天都可用 这几天不能用  . 但是 itzmx的pac能用

**Comment by Alvin9999** [comment]
不同的PAC地址采用的服务器位置是不同的，有的是日本，有的是美国。国内网络环境复杂，没法兼顾所有的地区。
