### ISSUE TITLE
代理服务器拒绝连接

### ISSUE THREAD

**Issue by xuyixuyi** [Alvin9999/new-pac#1061]
用ProxySU一键完成后再根据教程"浏览器代理设置成Socks(5) 127.0.0.1 和1080 即可通过v2ray代理上网"
也用v2rayN客户端测试了是有速度的，但是Firefox浏览器设置完成后却提示：代理服务器拒绝连接。
应该怎么处理？谢谢！

**Comment by Alvin9999** [comment]
推测是火狐浏览器代理没有设置好导致的
