### ISSUE TITLE
所有工具貌似都失效了

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#1064]

**Comment by jinyumarine** [comment]
过年去了

**Comment by bannedbook** [comment]
用这个
https://github.com/Alvin9999/new-pac/wiki/V2free%E6%9C%BA%E5%9C%BA

**Comment by Alvin9999** [comment]
部分工具ip失效，但有的工具没问题，比如ssrot ，ssr ip2，ss-kcptun，v2ray ip3都正常

**Comment by Alvin9999** [comment]
可以先用能用的工具，会尽快更换失效工具ip
