### ISSUE TITLE
Goflyway求更新， 谢谢

### ISSUE THREAD

**Issue by JohnWu17** [Alvin9999/new-pac#1067]
几天不能用了，求更新，非常感谢~

**Comment by Alvin9999** [comment]
Goflyway被封的厉害，即使更新很快又被封了，建议这段时间先换用其它工具。

**Comment by JohnWu17** [comment]
> Goflyway被封的厉害，即使更新很快又被封了，建议这段时间先换用其它工具。

好的， 辛苦了，我试试别的，主要用习惯了，见谅~

**Comment by Alvin9999** [comment]
刚更新了Goflyway ip1，可以试试看

**Comment by Alvin9999** [comment]
不用试了，坚持了10多分钟就不行了

**Comment by Alvin9999** [comment]
goflyway 4个ip地址都已更新
