### ISSUE TITLE
最近跟新的这个貌似里面大多数都不能正常工作啊~

### ISSUE THREAD

**Issue by GFconcept** [Alvin9999/new-pac#1070]
最近跟新的这个貌似里面大多数都不能正常工作啊~

**Comment by Alvin9999** [comment]
北京时间2021年2月20日8点48分：最近封锁严重，可以优先尝试clash ip1 ip2，v2ray ip1、ip2、ip3、ip4，ssrot ，ssr ip1 ip2，ss-kcptun ip1 ip2。
