### ISSUE TITLE
今天更新SSR和SS都无法使用了

### ISSUE THREAD

**Issue by jinyumarine** [Alvin9999/new-pac#1072]
有上行，没下行
是否服务器没刷新

**Comment by Alvin9999** [comment]
封锁加重

**Comment by jinyumarine** [comment]
> 封锁加重

怎么解决

**Comment by Alvin9999** [comment]
电脑系统是什么？

**Comment by jinyumarine** [comment]
> 电脑系统是什么？

手机

**Comment by Alvin9999** [comment]
手机的话，可以尝试安卓手机版，这里有很多款，但需要自己来尝试哪款好用，地址：https://github.com/Alvin9999/new-pac/wiki/%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA%E7%89%88

或者考虑付费v2ray机场：https://github.com/Alvin9999/new-pac/wiki/V2free%E6%9C%BA%E5%9C%BA

**Comment by Alvin9999** [comment]
顺便提醒下，这个节点是好的

节点2-德国：89.163.224.142  端口：12345  密码： dongtaiwang.com 123abc   加密方式：rc4  协议：origin 混淆：plain

**Comment by ShanChuangxin** [comment]
> 顺便提醒下，这个节点是好的
> 
> 节点2-德国：89.163.224.142 端口：12345 密码： dongtaiwang.com 123abc 加密方式：rc4 协议：origin 混淆：plain

好像也被墙了

**Comment by Alvin9999** [comment]
89.163.224.142没有被墙

**Comment by jinyumarine** [comment]
> 89.163.224.142没有被墙

嗯，更新了这个能用
是否私信来个账号

**Comment by jinyumarine** [comment]
> 89.163.224.142没有被墙

刚按你的链接试了好几个，没一个能用
都是有上行没下行

**Comment by Alvin9999** [comment]
可以考虑用免费v2ray账号

**Comment by ningyu1** [comment]
🤫👉[科学上网](https://hideu.app/?f=dn613)，嘘一般人我不告诉他。
