### ISSUE TITLE
是不是都不能用了啊？

### ISSUE THREAD

**Issue by GFconcept** [Alvin9999/new-pac#1073]

**Comment by Alvin9999** [comment]
北京时间2021年3月3日9点22分：最近封锁有加重的趋势，有的工具即使更新了又很快被封掉，部分工具正常。可以优先尝试工具clash ip1、ip2，ssr ip1、ip2，ss-kcptun ip1、ip2，v2ray ip1、ip2、ip3、ip4，ssrot。

**Comment by jinyumarine** [comment]
> 北京时间2021年3月3日9点22分：最近封锁有加重的趋势，有的工具即使更新了又很快被封掉，部分工具正常。可以优先尝试工具clash ip1、ip2，ssr ip1、ip2，ss-kcptun ip1、ip2，v2ray ip1、ip2、ip3、ip4，ssrot。

貌似又要更新了
剩西雅图能用
