### ISSUE TITLE
proxy的疑问？

### ISSUE THREAD

**Issue by BlackHole1** [Alvin9999/new-pac#108]
在pac定义了
`var proxy = "PROXY xi.dnsfree.space:80;";`
是什么意思？
打开之后，是中国禁网什么的。

还劫持了360和haosou，到你的360.itzmx.com网站上。网站上说的原因是，为了防止360通风报信。但是请具体到某一个domain上，而不是劫持所有的360.cn网站。

**Comment by Alvin9999** [comment]
这个地址不是我维护的，是别人另外一个项目维护的。

据我的了解，前面那个pac定义是为了保护真实的pac地址的一个“障眼法”，并没有多大的实质作用。

关于所有的360.cn网站，因为360确实口碑很差，尤其是翻墙，所以有人会全部屏蔽此网站并转到开发者想转到的网站上去。
