### ISSUE TITLE
ubuntu下安装报错

### ISSUE THREAD

**Issue by ShanChuangxin** [Alvin9999/new-pac#1080]
![image](https://user-images.githubusercontent.com/26052648/111965916-43acf980-8b3
![QQ图片20210322170915](https://user-images.githubusercontent.com/26052648/111965986-5a535080-8b31-11eb-966f-1abc0e593c18.png)
1-11eb-8fc5-1f03bfe0078e.png)

**Comment by Alvin9999** [comment]
提示正常运行，是否重复安装了？

**Comment by ShanChuangxin** [comment]
> 提示正在运行，是否重复安装了？

没有问题，能正常使用，只是安装的过程和用debian不太一样

**Comment by Alvin9999** [comment]
好
