### ISSUE TITLE
请教：“滚轮”或者“右键+滚轮”切换标签页是如何实现的

### ISSUE THREAD

**Issue by Tandio** [Alvin9999/new-pac#1081]
非常感谢老哥的项目，让我脱离了国产浏览器的泥潭（夸张手法）。
以前一直使用的老哥提供的工具，后来参考老哥的“自建VPN教程”慢慢捣鼓，现在已经能够自己科学上网了。
之后也就没有使用老哥这里下载的chrome浏览器，结果发现chrome官方不能使用滚轮切换标签页，百度谷歌了好几天也没找到较好的实现方式，故来请教下。

**Comment by Tandio** [comment]
谢谢老哥，能方便告知下插件的出处嘛

**Comment by Alvin9999** [comment]
这个必须要用dll注入，也就是必然要用插件程序，就是我的一键翻墙浏览器所用到的插件，不是设置浏览器的，所以你用我分享的浏览器APP里面的文件用到你的浏览器就可以，但前提是便携版。
