### ISSUE TITLE
v2ray免费账号 只剩一个节点好用了....

### ISSUE THREAD

**Issue by syhufo** [Alvin9999/new-pac#1082]
只有最后一个节点好用,其他的提示:
2021/03/26 06:49:33 tcp:127.0.0.1:57835 accepted tcp:alive.github.com:443 [proxy] 
2021/03/26 06:49:33 tcp:127.0.0.1:57836 accepted tcp:www.google.com:443 [proxy] 
2021/03/26 06:49:33 tcp:127.0.0.1:57837 accepted tcp:www.gstatic.com:443 [proxy] 
2021/03/26 06:49:36 tcp:127.0.0.1:57842 accepted tcp:alive.github.com:443 [proxy] 
2021/03/26 06:49:38 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.cloudflare.com/exlffvws): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2021/03/26 06:49:39 tcp:127.0.0.1:57845 accepted tcp:alive.github.com:443 [proxy]

**Comment by Alvin9999** [comment]
已更新

**Comment by syhufo** [comment]
> 已更新

万分感谢!!
