### ISSUE TITLE
V2ray 443端口的ip都失效了....

### ISSUE THREAD

**Issue by syhufo** [Alvin9999/new-pac#1084]
2021/03/30 14:49:13 tcp:127.0.0.1:50376 accepted tcp:alive.github.com:443 [proxy]
2021/03/30 14:49:15 [Warning] [757685222] github.com/v2fly/v2ray-core/v4/app/proxyman/outbound: failed to process outbound traffic > github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound: failed to find an available destination > github.com/v2fly/v2ray-core/v4/common/retry: [github.com/v2fly/v2ray-core/v4/transport/internet/websocket: failed to dial WebSocket > github.com/v2fly/v2ray-core/v4/transport/internet/websocket: failed to dial to (wss://c-us5.ooxc.cc/jj): 429 Too Many Requests > websocket: bad handshake] > github.com/v2fly/v2ray-core/v4/common/retry: all retry attempts failed

只有VLESS的节点还能用,VMESS全部阵亡......

**Comment by Alvin9999** [comment]
已更新。最近VMESS确实被封的厉害，建议优先选择VLESS节点。

**Comment by syhufo** [comment]
> 已更新。最近VMESS确实被封的厉害，建议优先选择VLESS节点。

非常感谢!
