### ISSUE TITLE
谷歌浏览器Ctrl + W关闭当前标签页变成了[关闭后打开新的空白标签页]

### ISSUE THREAD

**Issue by iguoji** [Alvin9999/new-pac#1093]
比如我打开了10个标签页，在原版Chrome或Edge中，我按一次Ctrl + W，就关闭一个标签页

但是现在我打开10个标签页，按一次Ctrl + W，就把当前的标签页变成了启动空白标签页，最终还是10个

**Comment by Alvin9999** [comment]
手动关闭一下吧。

**Comment by iguoji** [comment]
> 手动关闭一下吧。

请问在哪里关闭，我就是没找到

**Comment by Alvin9999** [comment]
鼠标左键点击叉叉

**Comment by Albert1995Einstein** [comment]
> 比如我打开了10个标签页，在原版Chrome或Edge中，我按一次Ctrl+W，关闭一个标签页
> 
> 现在打开10个标签页，但是我按一次Ctrl+W，把当前的标签页变成了启动空白标签，还是最后10个

可以用鼠标中键关闭标签

**Comment by Albert1995Einstein** [comment]
> 

我看有的是通过覆盖version.dll来解决的，这个项目可以吗？
