### ISSUE TITLE
域名问题

### ISSUE THREAD

**Issue by chen510260x** [Alvin9999/new-pac#1095]
https://www.namecheap.com 网站好像更新了，以前通过点击“Advanced DNS”来添加ip，现在不行了，该怎么办

**Comment by chen510260x** [comment]
Domain suspended. Contacts verification needed. |  
原来是这个问题，怎么搞

**Comment by chen510260x** [comment]
解决了，说一两天内激活，当垃圾邮件了。。。。

**Comment by Alvin9999** [comment]
好的
