### ISSUE TITLE
如何设置Chrome+为默认浏览器啊..

### ISSUE THREAD

**Issue by southcentral731** [Alvin9999/new-pac#11]
每次打开网页都新打开一个chrome

**Comment by Alvin9999** [comment]
”每次打开网页都新打开一个chrome“  这句话我没有看明白，可以截图说明吗

**Comment by Alvin9999** [comment]
你可以右键chrome+.exe，选择创建快捷方式，之后把这个快捷方式拖到桌面上，以后翻墙的时候，双击桌面上的这个快捷方式就可以用了，很方便。

**Comment by southcentral731** [comment]
@Alvin9999 就是 我把chrome设置为默认浏览器么 然后比如我从别的软件 比如微信的一个网页链接 用默认浏览器打开 它不会从我已经chrome+打开的那个chrome打开新的网页 而会再次打开一个什么扩展没有的chrome里 也就是并不是chrome+附带的那个chrome里打开

**Comment by Alvin9999** [comment]
嗯，是的。目前没法解决呢，以后会留意的，因为这款浏览器是便携版，并没有安装在电脑上，所以操作起来很难度。我通常的做法是，如果从其它软件打开一个网页，而这个网页是需要翻墙才能打开，那么我会把这个网址复制到翻墙浏览器打开。如果不需要翻墙就能打开，那么就用普通浏览器打开了。
你应该是自己也装了一个普通谷歌浏览器？

**Comment by southcentral731** [comment]
@Alvin9999 并不是我自己装的 就是chrome+捆绑文件夹里的那个原生chrome浏览器打开

**Comment by Alvin9999** [comment]
那你删掉文件夹，重新解压再打开试试，如果没有扩展就不能翻墙

**Comment by southcentral731** [comment]
@Alvin9999 不是..不是这个意思 chrome+打开的chrome是有扩展的 但是通过系统默认浏览器打开网页就会从新的原生态chrome里打开 所以这个时候系统就会有两个chrome 一个是chrome+打开的 一个是原生态的

**Comment by Alvin9999** [comment]
哦！明白了。原生态这就不行了。因为是要先启动一键启动程序chrome+.exe才会同时启动代理软件和浏览器，是这样的。

**Comment by southcentral731** [comment]
@Alvin9999 对啊 所以要想办法把系统默认浏览器能指向chrome+ 而不是chrome浏览器

**Comment by caofengzi** [comment]
其它網站都是調用原版chrome的，無法指定便攜啟動exe。
