### ISSUE TITLE
有goproxy版自动搜谷歌IP的么？

### ISSUE THREAD

**Issue by mymatrix2002** [Alvin9999/new-pac#110]
找了很久现在找到能自动搜谷歌IP的都是以goagent为基础的，现在goagent的作者都开始开发goproxy了，希望社长能出一个goproxy版自动搜谷歌IP的版本。

**Comment by Alvin9999** [comment]
现在没有。GoAgent和GoProxy开发编程语言不同，所以很难做到。未来可能会想到办法。
