### ISSUE TITLE
https://onedrive.live.com/无法访问

### ISSUE THREAD

**Issue by wittyprince** [Alvin9999/new-pac#1103]
ss四个节点 使用ShadowsocksR 均无法访问 https://onedrive.live.com/，OneNote无法同步

**Comment by Alvin9999** [comment]
试试全局代理

**Comment by wittyprince** [comment]
现在浏览器中可以访问https://onedrive.live.com/了，但是"OneNote for windows10" 软件中自动同步还是报错Page has never been synced | E000006B blg5z

**Comment by Alvin9999** [comment]
ss不是vpn，只能代理浏览器。如果想代理其它软件，需要借助第三方工具。

**Comment by wittyprince** [comment]
能不能推荐一下，哪些第三方工具可以？多谢

**Comment by Alvin9999** [comment]
可以试试Proxifier，网上搜一下使用方法

**Comment by wangzhankun** [comment]
请问能够正常访问谷歌网站但是无法访问onedrive.live.com有什么解决方案吗？
![image](https://user-images.githubusercontent.com/35724924/204749608-8b5f4aec-011c-49c2-9ccc-0dae444a9cc2.png)

**Comment by AnyWAT** [comment]
Windows10系统，如果（全局）系统代理不行，代理软件支持 http 和 socks，试试参照 psiphon3 设置系统代理的方案——
http=127.0.0.1:xxxxx;https=127.0.0.1:xxxxx;socks=127.0.0.1:yyyy
来手动设置系统代理。

**Comment by wangzhankun** [comment]
我试了不是系统代理的问题。我这里没有使用onenote客户端访问，是用浏览器也是无法打开onedrive.live.com,但是同一浏览器是可以访问谷歌，YouTube的。

**Comment by wangzhankun** [comment]
是`config`文件中的rules写的有问题，
![image](https://user-images.githubusercontent.com/35724924/204792870-cf11cde0-e84a-4154-8f2b-92f3d723780a.png)

把这一行删除掉就能够正常访问了 onedrive.live.com  了 。

**Comment by AnyWAT** [comment]
试了下，估计你使用的 Clash 规则（不行），改用“全局”就行了。
