### ISSUE TITLE
反华派？做个教程就得了，还搞这些？不去舔你主子？

### ISSUE THREAD

**Issue by Tajang-ctf** [Alvin9999/new-pac#1105]
就这外网翻墙，你发个翻墙教程不就得了，还九评还真相，搞一堆反华内容能干什么？不去舔你主子？阻止了中国的发展吗？搞教程就搞教程，不搞就滚

**Comment by Alvin9999** [comment]
中共不等于中国，更不是中华民族，中华民族有几千年的历史

**Comment by Alvin9999** [comment]
中共是外来政权，中共前身是共产第三国际，在前苏共的支持下赶走合法民国政府，占据中华大陆。中国人是炎黄子孙，继承的是中华传统文化，敬天地讲道德讲礼仪，中共是“马列幽灵兵”，宣扬无神论，毁灭传统文化，战天斗地与人斗，无法无天。

**Comment by Tajang-ctf** [comment]
国民党出卖民族，内战失败逃回台湾，勾结美帝，屠杀华人，你脑子呢




Tajang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 反华派？做个教程就得了，还搞这些？不去舔你主子？ (#1105)





 
中共是外来政权，中共前身是共产第三国际，在前苏共的支持下赶走合法民国政府，占据中华大陆。中国人是炎黄子孙，继承的是中华传统文化，敬天地讲道德讲礼仪，中共是“马列幽灵兵”，宣扬无神论，毁灭传统文化，战天斗地与人斗，无法无天。

**Comment by Tajang-ctf** [comment]
我家就是苏区，你了解历史吗
中央红军战略转移后，蒋介石及其国民党军队在苏区进行了惨无人道的大屠杀。这与蒋介石及其国民党军队大肆鼓吹搞灭绝人性的法西斯统治有很大的关系。深受日本军国主义思想影响大搞独裁政治的蒋介石，在看到英美想将世界经济危机所造成的矛盾引向苏联，通过绥靖政策支持已经法西斯化的德国、日本、意大利的情形，他也想通过这样的方式维护其反动统治。


Tajang
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 反华派？做个教程就得了，还搞这些？不去舔你主子？ (#1105)





 
中共是外来政权，中共前身是共产第三国际，在前苏共的支持下赶走合法民国政府，占据中华大陆。中国人是炎黄子孙，继承的是中华传统文化，敬天地讲道德讲礼仪，中共是“马列幽灵兵”，宣扬无神论，毁灭传统文化，战天斗地与人斗，无法无天。

**Comment by Alvin9999** [comment]
共产党在内战后，和平时期搞各种运动针对中国老百姓，包括三反、五反、肃反、反右、文化大革命、六四屠杀大学生、迫害法轮功、迫害维权律师等，根据《共产主义黑皮书》过去70年，在没有战争、没有外来侵略的和平时期，中共发动过70多次政治运动，导致8000多万中国人非正常死亡，这个数字是第一次世界大战死亡人数的8倍，是二战死亡人数的1.5倍！面对这样一个罪恶累累的政党（且至今毫无任何悔意、更绝不向人民认罪、道歉，并且还在继续屠杀！），那些期望它还能改革从善的人们，简直是在做一个和共产主义同样的美梦。

**Comment by Alvin9999** [comment]
建议您完整看一下《九评共产党》了解一下真实的共产党，兼听则明。

**Comment by Tajang-ctf** [comment]
这样和你说，我在初中就拜读过你方的《伪火》以及九评系列，禁书网，我也浏览很多，那么多年你们还是这些东西，毫无见解。以前我感觉你们的东西很搞笑，现在看来还是很搞笑。几乎接近邪教，你看看如今的国民党混成了什么样，与民进党天天吵架，像极了菜市场。台湾越治理越差，经济也下滑。你还不明白吗？台湾教科书为何不讲抗日战争？难道这不是关乎民族生死存亡的战争？国民党名为国民，却让台湾人民吃有问题的猪肉，它心中真的有国民？


在和你说共产党与国民党的区别，说一个我们这里发生过的事情。日本鬼子来了，村里人都跑到山上躲着，回来发现东西都被抢了。国民党来了，村民跑到山上回来后，东西也被抢了。共产党来了后，村民也跑到山上躲着，但是回来之后，发现东西没被抢，甚至挑好了水劈好了柴，拿的东西留的有押金和字据。第二次共产党来，村民就再也没躲着。为人民服务一直是宗旨。相比国民党，你自己想想好吧。




蒋介石的国民党可以用四个字来概括：混乱、腐败。
事实上，蒋介石一直没能把国民党整合成一个团结一致，纪律严明的组织，与其说他是国民党的领袖，不如说他是国民党各派势力的裁判者。

国民党至今没有想起孙中山先生的遗言，想起它也未曾践行。


Tajang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 反华派？做个教程就得了，还搞这些？不去舔你主子？ (#1105)





 
建议您完整看一下《九评共产党》了解一下真实的共产党，兼听则明。
