### ISSUE TITLE
傻逼法轮功

### ISSUE THREAD

**Issue by 49470488** [Alvin9999/new-pac#1107]
傻逼作者

**Comment by Alvin9999** [comment]
您好，您这样说，是您不太了解真相，建议您看下天安门自焚事件真相——《伪火》[在线观看](http://cn.ntdtv.com/gb/2014/01/07/a24016.html) [本地观看&下载](http://video1.freeair777.club/%E4%BC%AA%E7%81%AB.mp4) 

国内的央视媒体是党的喉舌，党让说啥就是啥。非央视的媒体和网站也是被管控的。所以，老百姓很难知道真相。如果想全面真实的了解共产党，建议您再看下《九评共产党》纪录片。

**Comment by 49470488** [comment]
为什么你会觉得你知道的才是真相，笑死个人了
国外媒体那么多fake news，youtube这么多造假视频，也有脸来diss中国？

自由上网 ***@***.***> 於 2021年6月3日週四 下午10:08寫道：
