### ISSUE TITLE
蓝的灯版本的都没破解完全

### ISSUE THREAD

**Issue by LitterCatZJ** [Alvin9999/new-pac#111]
不知道怎么回事，蓝灯Windows，Linux和安卓版的都只有500m流量，用完就限速20kb了，改了一下mac地址又可以了。拜托作者解决_(:з」∠)_

**Comment by Alvin9999** [comment]
我不会破解。蓝灯破解版为网上找的。但不管怎么说，破解版肯定没有收费版好用。而如果不想付费，免费版为每个月500M流量，超过后会限速至20kb/s，看网页没问题。
