### ISSUE TITLE
小白求助：SS/ShadowsocksR 服务器节点 v2ww付费之后怎么用啊？

### ISSUE THREAD

**Issue by biggiantpigeon** [Alvin9999/new-pac#1112]
https://shadowsockshelp.github.io/Shadowsocks/linux.html
这里面第二步：填写 “Server Address” （为你的节点服务器地址）> 填写”Server Port”（为你的服务端口) > 填写 “Password” （为你的登陆密码)。都要填什么？
v2ww的网站桑什么都没找到。。。

**Comment by Alvin9999** [comment]
那个是v2ray节点，不是ss节点

**Comment by Alvin9999** [comment]
如果用不来v2ray，可以看看教程或者申请退款

**Comment by biggiantpigeon** [comment]
> 如果用不来v2ray，可以看看教程或者申请退款

请问您这里有教程吗?另外我没找到能申请退款的地方..

**Comment by Alvin9999** [comment]
这里https://w1.v2free.net/user/ticket

**Comment by biggiantpigeon** [comment]
![image](https://user-images.githubusercontent.com/80443901/123615929-5756b300-d838-11eb-91fa-9adc9e081a35.png)
做到这一步之前都ok，可以连接上，后面这里“设置全局透明代理即可使用”是该怎么做，有详细说明吗？谢谢

**Comment by Alvin9999** [comment]
可以发工单问一下客服

**Comment by biggiantpigeon** [comment]
不好意思再请问一下，为现在成功了，但是内网的dns都解析不了，是什么问题呢？@Alvin999

**Comment by Alvin9999** [comment]
> 不好意思再请问一下，为现在成功了，但是内网的dns都解析不了，是什么问题呢？@alvin999

截图看看怎么设置的客户端？
