### ISSUE TITLE
clash 节点全都不能用了

### ISSUE THREAD

**Issue by ask7696** [Alvin9999/new-pac#1114]
![图片](https://user-images.githubusercontent.com/52815730/122856764-f3b91b00-d349-11eb-8953-5131d1f18e1e.png)

**Comment by Alvin9999** [comment]
关闭防火墙、杀毒软件和安全卫士后，更新ip再试试看。ip1、ip2、ip3、ip4、ip5、ip6都可以试试看。

**Comment by ask7696** [comment]
全试了还是不行

**Comment by Alvin9999** [comment]
其它工具能用不？

**Comment by ask7696** [comment]
刚刚全部试了下就SSROT可以

**Comment by Alvin9999** [comment]
好的，知道了，可能其它工具不太适合你。不过，clash都不能用的话，还是很奇怪。其它工具也有很多人在使用。
