### ISSUE TITLE
不自焚的轮子不是好轮子

### ISSUE THREAD

**Issue by FisherCloud** [Alvin9999/new-pac#1115]
科学上网请多听多看，要有独立思考意识，不要被洗脑了，特别是那一串推荐频道

**Comment by Alvin9999** [comment]
自焚是假的，建议看下天安门自焚事件真相——《伪火》[在线观看](http://cn.ntdtv.com/gb/2014/01/07/a24016.html) [本地观看&下载](http://video1.freeair777.club/%E4%BC%AA%E7%81%AB.mp4)
