### ISSUE TITLE
自由浏览2.0

### ISSUE THREAD

**Issue by jiangchengyike** [Alvin9999/new-pac#112]
自由浏览2.0安装后无法正常使用，一打开就报bug，然后退出，希望解决。

**Comment by Alvin9999** [comment]
这个软件不是我开发的。

你可以这样尝试下：重启手机，退出手机杀毒软件，安装前需要先对手机进行设置： 打开“菜单键”－设置（settings）－应用程序（Applications），勾选"未知源"（Unknown sources）。 下载apk文件，进行安装。如果 .apk 被保存为zip文件，请将它改回为 .apk。

**Comment by caofengzi** [comment]
自由瀏覽器分ram和x86兩種架構版本。

**Comment by jiangchengyike** [comment]
我去了Google play store下载也是卡退，但是在荣耀平板上可以正常使用，不知道是不是小米手机的问题。

**Comment by Alvin9999** [comment]
@jiangchengyike  有这种可能性。

**Comment by Alvin9999** [comment]
网友反馈，自由浏览具有不安全隐患，所以不建议使用。我已经删掉了自由浏览和自由有声的分享地址。
