### ISSUE TITLE
关于默认网页内容

### ISSUE THREAD

**Issue by pandaQJY** [Alvin9999/new-pac#1124]
为什么默认打开的页面中会有宣传FLG的内容？？？这是你设置的吗？

**Comment by Alvin9999** [comment]
是的，可以了解一下真相。

**Comment by pandaQJY** [comment]
你所谓的真相不过是西方反华势力的颠倒是非，但凡是生长在这片土地上的人都会真真切切的感受到这100年来在党的带领下祖国的日益昌盛。恰恰我认为，你可能没有看到真相，请你看看下面这个视频，看看什么是真的！https://www.bilibili.com/video/BV1zM4y1T7LB?from=search&seid=14666401393864260762

**Comment by killgcd** [comment]
最大的反华势力的魁首在这里：
据赫鲁晓夫——《赫鲁晓夫回忆录》：
在莫斯科，毛亲口对我说：“第三次世界大战应该在中国展开，待我们将美军引入纵深后，请你们苏联向我们投原子弹，一举全歼美军主力。可能因此死亡中国三分之二的人口，但换来一个世界大同还是值得的！”
当时我真替中国人捏把汗，让三亿中国人送死当炮灰这种事也能脱口而出，他和谁商量过？对自已国民实施大屠杀，他就这么的自然而然地说出了口，而且说的轻松异常，仿佛在谈论天气一样，这是人还是魔鬼？！”

**Comment by pandaQJY** [comment]
荒唐！ 毛主席带领中国人民经过革命斗争，赢得了民族独立和人民解放，创建了新中国。仅凭一句无从考证的话就像污蔑主席吗！

**Comment by pandaQJY** [comment]
荒唐！ 毛主席带领中国人民经过革命斗争，赢得了民族独立和人民解放，创建了新中国。仅凭一句无从考证的话就像污蔑主席吗！

**Comment by Alvin9999** [comment]
> 荒唐！ 毛主席带领中国人民经过革命斗争，赢得了民族独立和人民解放，创建了新中国。仅凭一句无从考证的话就想污蔑主席吗！

建议您看一下《九评共产党》，可以全面了解一下共产党的历史。

**Comment by Alvin9999** [comment]
> 荒唐！ 毛主席带领中国人民经过革命斗争，赢得了民族独立和人民解放，创建了新中国。仅凭一句无从考证的话就想污蔑主席吗！

共产党在建立政权后，在和平时期屠杀了很多中国人，包括三反、五反、肃反、文化大革命、六四屠杀大学生、迫害法轮功等各种运动，负有累累血债。

**Comment by pandaQJY** [comment]
“中国人民从来没有欺负、压迫、奴役过其他国家人民，过去没有，现在没有，将来也不会有。同时，中国人民也绝不允许任何外来势力欺负、压迫、奴役我们，谁妄想这样干，必将在14亿多中国人民用血肉筑成的钢铁长城面前碰得头破血流！”

**Comment by pandaQJY** [comment]
法轮功 也配用迫害这个词？你一个搞技术的人居然会和这种反科学的邪教站在一边，书白读了？？？？？
