### ISSUE TITLE
如果是中立的,我会很感谢你.然而并不是.

### ISSUE THREAD

**Issue by wenanlee** [Alvin9999/new-pac#1125]
中国怎么我会用自己的眼睛看.不用你指路.
对了,请把美国黑奴和印第安人种族灭绝也写上,让别人一眼就有对比啊.

**Comment by Alvin9999** [comment]
中国不等于中共（共产党），共产党也代表不了中华名族，中华民族有5000多年的历史，共产党的祖先是马克思，从本质上来说，中共是外来政权。

**Comment by Alvin9999** [comment]
建议您看一下《九评》，全面了解一下共产党的历史，当然纪录片和cctv说的会不一样，兼听则明。

**Comment by wenanlee** [comment]
简直扯淡！
中国共产党代表不了中国，中国政府可以。
美国共和党和民主党也代表不了美国，但美国政府可以。
日本自民党代表不了日本，但日本政府可以。
请问你是反共，还是反中国政府？

共产党是外来的？
对，因为中国传统是封建帝制！
科学思想是不是外来的？
民主思想是不是外来的？
一个不懂得吸收优秀的外来文化，闭门造车，因循守旧的民族早就该消失在历史中。

请不要被洗脑了，最可怕的洗脑不是共产党这种，你天天提心吊胆生怕被洗脑的；而是你压根不觉得自己被洗脑，还以为自己获得了真理。

中国目前还有许多不如人意的地方，也做错过许多事情，没有什么是完美的，如果共产党一路走来伟光正，我反而觉得有问题，但是我们要给她时间。
