### ISSUE TITLE
A bad experience

### ISSUE THREAD

**Issue by reai-0** [Alvin9999/new-pac#1127]
The high kernel version (Freegate) is severely blocked, hope to upgrade it soon😢

**Comment by Alvin9999** [comment]
你好，自由门版本升级更新需要一定的时间。当然，不同的时间段来使用也会有不同的效果，所以可以换个时间段再试试看。在不能正常翻墙的时候，可以考虑更换其它类型的软件，比如无界版本，或者集合版本，集合版推荐clash、v2ray、ssr工具。
