### ISSUE TITLE
能否提供SSR ssr链接？

### ISSUE THREAD

**Issue by t66y-sc** [Alvin9999/new-pac#1129]
首先感谢您提供的ssr免费账号，让我有免费的梯子可以用。

那个，在您每次更新ssr账号信息后，虽然可以手动设置SSR，不过又是SSR设置完后，仍然不起作用，我不知道是我自己设置出错了，还是账号已经被封禁，因此，特别希望您能在更新ssr账号时，同时提供ssr链接！

**Comment by Alvin9999** [comment]
可以，已增加

**Comment by KKsimi** [comment]
V2ray现在很多节点不能用啊
