### ISSUE TITLE
请问如何暂停或者卸载谷歌bbr加速？

### ISSUE THREAD

**Issue by BrooksYang** [Alvin9999/new-pac#113]
装了bbr加速之后，确实很有效果，但服务器本身的下载速度会降低很多，所以想问下有没有暂停或者卸载的方法

**Comment by Alvin9999** [comment]
我也没有暂停以及卸载谷歌bbr加速的代码。如果你用的是vultr的服务器，可以重装系统或者重新建立一个服务器，毕竟vultr是按小时计费的。
