### ISSUE TITLE
小白 请问v2ray服务器搭建不用高阶的话可以正常上网吗

### ISSUE THREAD

**Issue by xiayi91** [Alvin9999/new-pac#1136]
安装了一键脚本（非高阶部分） 根据vmess地址在v2rayN增加了服务器 开启代理后不能上网 
特殊的是我在国外 用的是国内的服务器
麻烦大佬帮忙回答 谢谢了！

**Comment by xiayi91** [comment]
一问问题就解决了 改成tcp就可以正常用了

**Comment by Alvin9999** [comment]
好的
