### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Jason96M** [Alvin9999/new-pac#114]
goagent v.3.2.3 更新证书后还是不能打开外网，使用管理员身份打开会提示找不到文件，文件名不正确，请教高手帮忙解决一下吧，谢谢了

**Comment by Alvin9999** [comment]
我推测你用的是win8或win10系统。你可以按照系统给你的提示，自己手动去启动。只要杀毒软件没有误删，那么文件肯定都在的。

**Comment by Alvin9999** [comment]
使用说明里面有提到分开启动的方法。
