### ISSUE TITLE
SSR账号全部失效了

### ISSUE THREAD

**Issue by xrogzu** [Alvin9999/new-pac#1146]
SSR账号全部失效了

**Comment by bannedbook** [comment]
暂时可到这里看看
https://github.com/bannedbook/fanqiang/wiki/%E5%85%8D%E8%B4%B9ss%E8%B4%A6%E5%8F%B7

**Comment by Alvin9999** [comment]
马上修复

**Comment by Alvin9999** [comment]
已更新
