### ISSUE TITLE
你的免费SS账号被这个网站恶意转载了。

### ISSUE THREAD

**Issue by ToyoDAdoubi** [Alvin9999/new-pac#115]
实际上是我发现这个网站恶意转载我网站的免费SS账号，然后翻了下发现你的也被转载了，就给你提醒一下，下次记得在图片中加入水印，可能会让这些抄袭狗更麻烦一点。
http://i.wuw.red/ssr%E8%8A%82%E7%82%B9/github%E7%AB%99%E7%82%B9ssr%E8%8A%82%E7%82%B9/

**Comment by Alvin9999** [comment]
收到了，谢谢Toyo～

**Comment by Alvin9999** [comment]
你的网站和镜像都打不开了，什么情况呢？

**Comment by starksong** [comment]
今天在G+社群看到公告。
不知道说点什么。。。
期待toyo回归，
签名为生命不息，逗比不止。
永远支持，加油！

**Comment by zionfuo** [comment]
关站了好像

**Comment by wggwcn** [comment]
精品换色网站，微信 1 8 3 88 39 0002 ~~+++++
