### ISSUE TITLE
不懂

### ISSUE THREAD

**Issue by horizon86** [Alvin9999/new-pac#1153]
做梯子就做梯子，为什么夹带反华？

**Comment by Alvin9999** [comment]
中共（共产党）不等于中国，也不代表中华民族。

**Comment by horizon86** [comment]
笑岔了，Github是让你宣传政治的网站？你做梯子非得夹带点个人政治私货，就你在这破坏环境是吧，GitHub就是让你这种东西破坏掉的。垃圾，没见别人发GitHub还带政治立场的。

**Comment by Alvin9999** [comment]
了解真相是每位公民的基本权力。
