### ISSUE TITLE
clash无法翻墙

### ISSUE THREAD

**Issue by badongdyc** [Alvin9999/new-pac#1162]
clash无法翻墙

**Comment by Alvin9999** [comment]
提示的什么？有没有更新ip？

**Comment by badongdyc** [comment]
有更新ip，更新了ip没法访问谷歌，且有1两个无法更新ip

**Comment by Alvin9999** [comment]
截图看看

**Comment by badongdyc** [comment]
![1](https://user-images.githubusercontent.com/17975624/141253698-c83ef5b5-33a7-4e48-a636-0502fa5883ea.png)
就是这样

**Comment by badongdyc** [comment]
有时候更新了ip可用，但是过一段时间又不行了，不是很稳定的样子

**Comment by Alvin9999** [comment]
用的什么日期的版本呢

**Comment by badongdyc** [comment]
Chrome87_64bit_AllNew_2020.12.6 这个版本，以前都还好好的，就最近经常不行， 然后我刚刚下载了最新版，也用clash，刚开始也是不行，然后刚刚试了下又可以了。

**Comment by Alvin9999** [comment]
最近不稳定指的是从什么时候开始的？昨天？前天？

**Comment by badongdyc** [comment]
记不太清了，应该是9号开始的

**Comment by Alvin9999** [comment]
好的，知道了

**Comment by badongdyc** [comment]
好的，麻烦有空看看，现在用的最新版SSR，暂时没什么问题

**Comment by Alvin9999** [comment]
原因应该找到了，剔除了clash中一些不稳定的节点，重新更新ip即可。

**Comment by badongdyc** [comment]
好的，感谢
