### ISSUE TITLE
oracle cloud安装后无速度

### ISSUE THREAD

**Issue by YYJavaGit** [Alvin9999/new-pac#1163]
oraclecoud安全组出入全部放行了 
纯净系统 
dns服务商godaddy
证书ddnspod下载的nginx 
可以ping通 
连上不通
手机电脑都一样
最新发行版
![image](https://user-images.githubusercontent.com/50813117/141409153-e7e8791c-387a-400d-b841-125933ebaacd.png)

**Comment by Alvin9999** [comment]
http://port.ping.pe/
ip:端口
测试下ip对应下端口是否正常

**Comment by YYJavaGit** [comment]
z
