### ISSUE TITLE
这两天vutlr的虚拟机买完重启就都不能访问了？SSR加速器有文件无法下载安装

### ISSUE THREAD

**Issue by vision-qiu** [Alvin9999/new-pac#1166]
`Downloading packages:
linux-firmware-20200421-80.git78c0348.el7_9.noarch.rpm                                                                                                                                                               |  80 MB  00:00:04     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : linux-firmware-20200421-80.git78c0348.el7_9.noarch                                                                                                                                                                       1/2 
  Installing : kernel-3.10.0-327.el7.x86_64                                                                                                                                                                                             2/2 

Broadcast message from systemd-journald@vultr.guest (Mon 2021-11-15 15:46:46 CST):

dracut[5344]: Failed to install module nscsi_transport_sas

Message from syslogd@guest at Nov 15 07:46:46 ...
 dracut:Failed to install module nscsi_transport_sas

Broadcast message from systemd-journald@vultr.guest (Mon 2021-11-15 15:47:03 CST):

dracut[14122]: Failed to install module nscsi_transport_sas

Message from syslogd@guest at Nov 15 07:47:03 ...
`

**Comment by Alvin9999** [comment]
服务器系统选择的什么？

**Comment by vision-qiu** [comment]
centos7，大部分情况都是安装加速器的时候，我提的issue中的那个问题，退出当前加速器安装时，然后重启，重启后就无法访问了

正在 Ping 66.42.98.174 具有 32 字节的数据:
来自 107.191.59.36 的回复: 无法访问目标主机。
来自 107.191.59.36 的回复: 无法访问目标主机。
来自 107.191.59.36 的回复: 无法访问目标主机。
来自 107.191.59.36 的回复: 无法访问目标主机。

貌似加速器的问题

**Comment by Alvin9999** [comment]
因为要修改内核才能部署bbr各种版本的加速，有时候会重启不了，有的机器会遇到，有的不会遇到。试试debain10系统，最近我会这个系统部署bbr plus都没有问题。

**Comment by Alvin9999** [comment]
如果选择debain10，只要运行一下加速脚本，默认会开启bbr原版加速，不用重启。如果想部署其它加速，那么就要先安装对应的内核。

**Comment by vision-qiu** [comment]
debian10，默认的BBR加速器速度太慢了，甚至访问不了google，加速器内核换不了，选择其他内核时，能看到日志中有个别Error，唉，用了四年了，最近问题频频发生，难受😫

**Comment by Alvin9999** [comment]
数字2安装bbrplus内核，多安装2次就可以了

**Comment by Alvin9999** [comment]
弹出的提示选择否
