### ISSUE TITLE
请教一个问题，貌似这种翻墙方式上脸书的速度有点慢？

### ISSUE THREAD

**Issue by roseyue** [Alvin9999/new-pac#117]
感谢大神写的软件让我们翻墙更方便了。
但是翻墙后访问facebook时感觉明显速度没有油管快，facebook搜索框速度特别慢一些。
想请问一下这是什么原因呢？有解决的办法吗？
再次感谢！！！

**Comment by Alvin9999** [comment]
我分享了8种不同翻墙方式的软件，因为不同的地区封锁强度不同，运营商干扰不同等，所以使用效果不会完全相同。你可以试试其它方式，这是目前比较好的方式了。我只能尽可能兼顾大多数用户的需求，全部用户的需求目前一款软件没法实现。
