### ISSUE TITLE
关于免费ssr/ss账号的搭建方式

### ISSUE THREAD

**Issue by ShenCastle** [Alvin9999/new-pac#1170]
如题，想请教下大佬怎么能搭出这样的梯子，我按照自建ssr/ss的教程搭建的梯子从上周二开始一直用不了，试了二十多次了已经（没用高级教程里的内容，因为是deepin系统，windows坏掉了。。）/(ㄒoㄒ)/~~

**Comment by Alvin9999** [comment]
带域名的账号是用的高阶篇方法，SSR+TLS+Caddy+Web
第一个账号是普通的搭建，你可以试试第一个账号的参数设置，需要提醒一下，chacha20加密方法的安装需要先安装数字4的libsodium

**Comment by ShenCastle** [comment]
看上去高阶篇方法是要用Windows的是吧/(ㄒoㄒ)/~~

**Comment by Alvin9999** [comment]
是的噢

**Comment by Alvin9999** [comment]
你也可以不用域名，直接用普通的搭建，参数用这个：
加密方式：none  协议：auth_chain_a 混淆：tls1.2_ticket_auth

**Comment by ShenCastle** [comment]
用您推荐的协议和混淆解决了，感谢！

**Comment by Alvin9999** [comment]
好的
