### ISSUE TITLE
能不能把每次版本更新的地址文件都挂上来，方便选择下载，而不是现在这样，只有最新更新的版本。

### ISSUE THREAD

**Issue by lxok89** [Alvin9999/new-pac#118]
如题所示。

**Comment by Alvin9999** [comment]
直接在页面上就可以查看旧版，如图：
![1](https://user-images.githubusercontent.com/12132898/30278470-020194be-973d-11e7-8507-34d90d80d81a.PNG)
![2](https://user-images.githubusercontent.com/12132898/30278471-020626dc-973d-11e7-8faf-664c22670b1a.PNG)

但有个问题，因为网盘空间有限，现在我用的是百度云盘和巴别鸟云盘，这个两个云盘的免费空间都是有限的，所以我每隔一段时间就会在以前的网盘中删掉一些旧的文件，那么即使你打开旧版的界面，会发现下载失效。

**Comment by Alvin9999** [comment]
如果你能推荐一些好用的网盘，那么兴许会让旧版文件保留的更久一点。推荐的网盘最好符合以下特点：
1.免费
2.在国内没有被墙 
3.下载100M左右的文件不会太慢，且下载速度比较稳定，不要还没有下载完毕就显示下载完了。那么文件是失效的。

**Comment by Alvin9999** [comment]
4.分享的文件的有效期限至少在3个月以上。
