### ISSUE TITLE
CentOS 8 无法正常安装使用

### ISSUE THREAD

**Issue by stevelyc** [Alvin9999/new-pac#1180]
安装最后的日志
![安装报错](https://user-images.githubusercontent.com/7158530/143600911-65688c38-ca59-4492-81ce-db3e968a8a8a.png)
使用时的报错
![使用报错](https://user-images.githubusercontent.com/7158530/143600918-fb31eddb-012b-4354-85fe-0d0d42ccbc42.png)

**Comment by Alvin9999** [comment]
换CentOS7或者Debain10

**Comment by stevelyc** [comment]
西八，那我重新编译一个吧，还有其他服务跑着，不能说换就换
