### ISSUE TITLE
备用网址打不开了

### ISSUE THREAD

**Issue by weiter0** [Alvin9999/new-pac#1181]
这个备用网址：[https://hub.fastgit.org/Alvin9999/new-pac/wiki/ss免费账号](https://hub.fastgit.org/Alvin9999/new-pac/wiki/ss免费账号)
打不开了。我这在没墙翻的时候GitHub和另一个备用网址都经常没法直接打开，就用hub那个备用链接，结果现在打不开了。
![image](https://user-images.githubusercontent.com/88627186/143664389-b3870202-4d27-4813-a686-54140f52967b.png)

**Comment by Alvin9999** [comment]
再试试看

**Comment by weiter0** [comment]
这个备用网址又打不开啦～
挂梯子显示这样：
![IMG_20220126_013048](https://user-images.githubusercontent.com/88627186/151028410-8e8b7125-2452-43ec-ba24-e022571c05dd.jpg)
不挂梯子显示这样：
![IMG_20220126_013225](https://user-images.githubusercontent.com/88627186/151028683-e403608d-e52f-457a-9bf0-39201a60597a.jpg)

**Comment by Alvin9999** [comment]
换个时间段再试试看。
第二个备用网址能打开吗https://tr1.freeair888.club/ss免费账号

**Comment by weiter0** [comment]
tr1那个可以打开～但是需要挂梯子才行。(之前很长时间就是tr1需要挂梯子才能打开，hub可以直接打开，本页面有时需要梯子有时能直接打开)
不挂梯子的样子：
![IMG_20220126_141052](https://user-images.githubusercontent.com/88627186/151112560-ea1346a3-275a-4e97-99d9-16e8e3d1d2bd.jpg)

**Comment by Alvin9999** [comment]
tr1那个前面加https

**Comment by weiter0** [comment]
哦神奇。怪不得我这么久一直打不开这个。谢谢！

**Comment by Alvin9999** [comment]
> 哦神奇。怪不得我这么久一直打不开这个。谢谢！

好的

**Comment by PiPiTaDie** [comment]
选个付费的吧 https://balala.io/auth/register?code=AHNP  一个月就十块钱，有几十个接口包含多个国家，虽然是有流量限制的，但是至今没见过有人一个月把流量用完的
