### ISSUE TITLE
在Windows server 2016下部署v2ary节点出错

### ISSUE THREAD

**Issue by DARPUB** [Alvin9999/new-pac#1187]
你好大神，
我不懂Linux，所以我准备在Windows Server上部署节点。我在网上搜索了很多，绝大部分讲的是Linux环境下部署。后来我按https://www.zhuguodong.com/?id=383上的教程操作。
我下载的是最新的服务端和客户端，https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0 下的windows 64位（不知道是不是下错了）
双击 "wv2ray.exe" 时，并没有弹出教程中的窗口，但系统后台进程里有这个程序。防火墙开了，客户端可以ping通，但无法通过“服务器真连接延迟测试”，主要报“基础连接已关闭”之类的。
请问v2ary能在windows server下部署节点吗，是那样操作的吗？我这里出现的问题大概是什么原因造成的，请大佬指教。感激不尽！

**Comment by Alvin9999** [comment]
你好，我也没有在vps服务器是windows的系统选择下部署过v2ray。有2个建议给你，供你选择。
1、你可以用一键搭建科学上网工具ProxySU，用自己的windows系统电脑就可以了，只需要输入vps服务器的ip和密码，然后选择自己想部署的代理工具的参数就可以一键部署，[教程及下载地址](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91%E5%B7%A5%E5%85%B7ProxySU)。
2、我分享的各种自建服务器教程虽然是操作linux系统的vps，但很详细，按照步骤一步步来应该是没有问题的，部署代码也是一键式的，比如[自建v2ray服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by Alvin9999** [comment]
OK

**Comment by DARPUB** [comment]
我刚才试过了，猛然发现，这个工具是给Linux系统部署代理节点，对吧。
我现在的情况是，有一台windows server 2016的美国vps，想在这系统上面弄个代理节点，这样我在中国的客户端就用自己的节点上外网了，不用天天找不稳定的免费节点。您能推荐个这样的代理部署工具吗？如果有的话。谢谢！

**Comment by Alvin9999** [comment]
你还是用这个方法https://www.zhuguodong.com/?id=383
下载32位软件，然后设置好后，服务器的时间和本低电脑的时间不超过90秒

**Comment by Alvin9999** [comment]
另外，服务端和客户端不要弄错了，你的vps用服务端软件，自己本低电脑用客户端软件

**Comment by Alvin9999** [comment]
检查端口是否正常网站：http://port.ping.pe/1.1.1.1:443
ip:端口，如果全是绿色表明端口是通的，如果是红色，表明没有通。

**Comment by DARPUB** [comment]
端口OK.
客户端与服务端没问题
防火墙全禁用，或全通行
就是无法连接
折腾大半天
弃了
怀疑不支持windows server2016，或vps上游禁止。
