### ISSUE TITLE
大家别用这个了 真的太差了

### ISSUE THREAD

**Issue by JohnGreenn** [Alvin9999/new-pac#1188]
我也用了好几个月了 涨价就不说了 今天花了二个小时 换了各种服务器 和加密方式 根本不行 已经弃坑了

**Comment by JohnGreenn** [comment]
而且速度也不快啊延迟250+ 一般维持在300+

**Comment by Alvin9999** [comment]
目前推荐的SSR参数设置为以下，有利于突破网络封锁，参数如下：

1、加密方式：none 协议：origin 混淆：tls1.2_ticket_auth

2、加密方式：none 协议：auth_chain_a 混淆：tls1.2_ticket_auth

3、高阶篇的SSR+TLS+Caddy
