### ISSUE TITLE
为何每次使用chrome版本的，第二次就不能使用

### ISSUE THREAD

**Issue by arsenal1447** [Alvin9999/new-pac#119]
每次第一次可以使用，第二次再打开的时候，扩展就全部不可使用了，这是为啥啊，使用的是这个包 Chrome61_GA_2017.9.6.7z，使用了好几个日期的版本都是这样，而且黑窗口没有数据在跑
![https://s1.ax1x.com/2017/09/12/nK2kV.png]()

**Comment by zxx1988328** [comment]
每次解压一次可以使用，第二天再使用的时候，全部的扩展就不可使用了

**Comment by Alvin9999** [comment]
黑窗口没有数据的话，表明程序被干扰了，多半是杀毒软件的锅，尤其是国产杀毒软件，比如360，腾讯管家，金山卫生等，所以建议把杀毒软件退出来再翻墙。如果插哦那个件被杀毒软件默默的删了，那么也会导致扩展不可用。
