### ISSUE TITLE
最近什么情况？公用账号+fg+无界全都阵亡了？

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#1193]
clash、v2ray、SSR所有的更新IP更新全都是一连串的failed: Bad file descriptor. v2ray似乎是“假死”了，能连上但完全打不开任何网页。fg现在隔三岔五提示“目前封锁严重，还需要5-10分钟继续搜索”，无界卡在“正在连接服务器 ...”上好几十分钟了。难道是从某个日子开始Q的火力突然变猛了？？？

**Comment by bannedbook** [comment]
V2free 机场 不错，比较坚挺

**Comment by Alvin9999** [comment]
都正常。排除一下防火墙、国产杀毒软件、安全卫士的干扰后，重新解压再更新ip。

**Comment by Alvin9999** [comment]
你这是ip没有更新成功
