### ISSUE TITLE
这是不准备维护了嘛

### ISSUE THREAD

**Issue by 2363878987** [Alvin9999/new-pac#1195]

**Comment by Alvin9999** [comment]
都正常的呀

**Comment by Alvin9999** [comment]
你是遇到了什么问题呢

**Comment by 2363878987** [comment]
并没有遇到问题，只是觉得现在的节点普遍质量不如以前高了。我一直用clash，感觉大佬可以把节点单独放一个文件。我们自己更新就完事了。

**Comment by Alvin9999** [comment]
clash有的是网络免费节点，用的人可能就会变慢。。。

**Comment by Alvin9999** [comment]
ip1~ip6都可以试试看，实在不太适合自己的网络环境，可以考虑换工具

**Comment by 2363878987** [comment]
好的 ， 感谢大佬回复。还有一个问题是关于clash节点选择这个部分，能否做到先测速再选择速度最快的节点。现在的规则 select-tet 应该是 选择延迟最低的节点并倒序选择的吧。

**Comment by Alvin9999** [comment]
当然也考虑自己搭建翻墙服务器，主页里面有教程，自己搭建的话就是独享带宽了，如果不想搭建，也可以考虑那个推荐的付费v2fee服务。

**Comment by Alvin9999** [comment]
> 好的 ， 感谢大佬回复。还有一个问题是关于clash节点选择这个部分，能否做到先测速再选择速度最快的节点。现在的规则 select-tet 应该是 选择延迟最低的节点并倒序选择的吧。

目前就是按照最低延迟来选择的，没办法做到速度选择，你可以到clash的开发者github上提建议。

**Comment by 2363878987** [comment]
> > 好的 ， 感谢大佬回复。还有一个问题是关于clash节点选择这个部分，能否做到先测速再选择速度最快的节点。现在的规则 select-tet 应该是 选择延迟最低的节点并倒序选择的吧。
> 
> 目前就是按照最低延迟来选择的，没办法做到速度选择，你可以到clash的开发者github上提建议。

好的。❤（づ￣3￣）づ╭❤～
