### ISSUE TITLE
近期ssh攻击频繁

### ISSUE THREAD

**Issue by tao329** [Alvin9999/new-pac#1196]
![image](https://user-images.githubusercontent.com/68785698/150476089-c3ba1484-797b-42a5-b0b9-1170d024bf20.png)
尝试了 http://antivirus.neu.edu.cn/scan/ssh.php， 但效果并不显著， 此类攻击对服务器有影响吗？ Alvin有何建议？

**Comment by Alvin9999** [comment]
使用这个命令查看ip连接数
netstat -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n

把链接数特别大的ip屏蔽了
iptables -I INPUT -s IP -j DROP

**Comment by birdofprey** [comment]
you have use sshguard https://sshguard.net/
