### ISSUE TITLE
召唤大法

### ISSUE THREAD

**Issue by Gdname** [Alvin9999/new-pac#12]
@Alvin9999 本来使用goagent这个的谷歌翻墙的，然后我觉得有点麻烦，然后就去谷歌官网下载了一个谷歌浏览器，然后把goagent里面的SwitchyOmega的PAC5搬到了我下载的谷歌浏览器，然后发现在我的新的谷歌浏览器SwitchyOmega设置里面点击   立即更新情景模式都可以更新IP，不用原来的goagent的还要进IP这个文件夹进行更新，直接在插件里面点一下，就更新好了，不过把这个goagent里面的PAC5搬到了新下载的谷歌浏览器后速度变慢了，720P有点压力，要暂停缓冲一会。

诶，图片上传不了，给度娘盘把，我上面说了一堆废话，说白了就是想问一问goagent里面的PAC5搬到了新下载的谷歌浏览器后速度变慢了
http://pan.baidu.com/s/1o8TNRYU

**Comment by Alvin9999** [comment]
你好，goagent版利用的是谷歌ip，并不是pac里面的ip，这是两种不同的方式。你在情景模式下更新的pac5里的ip只是pac ip，并不是谷歌ip哦！所以速度慢。说白了，你用的是pac代理方式，而不是goagent代理，没有用到谷歌ip。单纯的把扩展弄过去，是不行的。

**Comment by Alvin9999** [comment]
如果你想方便使用goagent版，可以右键那个chrome+.exe程序，选择快件快捷方式，之后把这个快捷方式拖到桌面上去，然后以后点击桌面这个快捷方式就能翻墙了，很方便，我自己就是用快捷方式的。

**Comment by Alvin9999** [comment]
issues上传图片在这里
![1](https://cloud.githubusercontent.com/assets/12132898/19405788/55f3caf4-92ae-11e6-9ad6-41058664e45e.PNG)

**Comment by Gdname** [comment]
怪不得，我把PAC和goagent的各移植了一个，发现那个速度居然慢到家了= =，还有还有，上传图片上传不上去 = =

**Comment by Gdname** [comment]
那个GFW大杀器是软件还是浏览器？？

**Comment by Alvin9999** [comment]
是软件配合浏览器使用

**Comment by Alvin9999** [comment]
上传图片时，选择图片并加载好后是一个地址，类似于这样：![Uploading IMG_2415    然后发送出去就能显示了
