### ISSUE TITLE
域名访问问题

### ISSUE THREAD

**Issue by s1mple-child** [Alvin9999/new-pac#1202]
问题：
之前自申请了一个域名，并且搭建了trojan，使用了很长时间了，一直没有问题，但是前几天小火箭连接超时，无法使用。
- 使用 http 方式可以访问该域名
- 使用 https 方式访问失败
- ping 域名可以返回成功信息

**Comment by Alvin9999** [comment]
试试端口被封了没有？
http://port.ping.pe/ip:端口

**Comment by Alvin9999** [comment]
如果端口被封，那么需要换个ip

**Comment by s1mple-child** [comment]
> 如果端口没有被封，可以换个二级域名重新来搭建看看

我猜是端口被封了，因为我换了一个二级域名也是一样的问题
有几个小问题，麻烦你解答下：

- 像这种端口被封的问题，如果访问 https 的 443 端口被封了是否可以通过修改端口的方式‘复活’它？（如果不行的话我就只能新建节点了，用了一年多还挺不舍得换的 :cry: ）
- 另外域名使用ipv6被墙的几率会比ipv4低吗？因为我看 v2ray 的脚本里示例用的是ipv6
- v2ray trojan wireguard 这三个如果搭的话首选是哪个？请问有没有一些可以参考的对比的 blog？

谢谢 :handshake:

**Comment by Alvin9999** [comment]
1、一般ws+tls端口是443，如果是搭建其它传输方式，可以换非443端口。
2、如果你的网络能使用ipv6，可以试试看，具体情况要试了才知道
3、v2ray trojan wireguard 这三个如果搭的话哪个最好？不同的网络环境，不同的封锁强度不好说，具体还是以自己测试为准。除了这3个，ssr+tls+caddy的方法目前也还比较稳定，我分享的免费ssr帐号用了很长一段时间，目前也还在用。还有ss的aes-256-gcm加密方式也还不错。

**Comment by Alvin9999** [comment]
一般只要是端口不一样，一个vps可以搭建多款工具，所以你可以搭建不同的工具，然后让端口不一样就可以了。只要ip没被墙，以及各个工具的端口没封，你可以切换来使用。

**Comment by s1mple-child** [comment]
> 一般只要是端口不一样，一个vps可以搭建多款工具，所以你可以搭建不同的工具，然后让端口不一样就可以了。只要ip没被墙，以及各个工具的端口没封，你可以切换来使用。

我先搭了一套 ssr+tls+caddy 先用着，已经搭好了，但是那个新版本的 ProxySU 不支持搭建 SSR，并且在解析 ipv6 的域名时有点问题，所以先用的 ipv4 的域名先用着吧。
谢谢你！ you saved my day! :handshake: :+1:
