### ISSUE TITLE
pac 不能使用，pac5脚本最新版，后面少了一大截

### ISSUE THREAD

**Issue by bpshou** [Alvin9999/new-pac#1203]
将pac配置到SwitchyOmega中，不能正确访问谷歌，将 proxy 更换为自己搭建的v2ray依然不可以。

新版本中的pac5少了一大截，后面没有提交全

**Comment by Alvin9999** [comment]
谢谢反馈。如果是翻墙，推荐用免费翻墙浏览器、免费ssr账号、免费v2ray账号或者v2rayN客户端配合自己搭建的v2ray账号。
此pac只是用来记录用，非实用。
