### ISSUE TITLE
SSR启动的时候,反馈信息SSR服务订阅更新失败

### ISSUE THREAD

**Issue by CandyKIng1991** [Alvin9999/new-pac#1210]
* 可以翻墙
* 点击不报其他错误
* 就是一直显示SSR服务订阅更新失败

* 希望得到你们的帮助,万分感谢

**Comment by Alvin9999** [comment]
不用订阅，直接填写账号信息看看

**Comment by CandyKIng1991** [comment]
> 不用订阅，直接填写账号信息看看

这个就是靠url订阅来的，填了url就会显示订阅的服务器
