### ISSUE TITLE
关于更新chrome版本的问题

### ISSUE THREAD

**Issue by PAKIKNOWLEDGE** [Alvin9999/new-pac#1214]
在更新高内核chrome版本时会丢失我原本chrome的配置，如书签历史等，请问解压时有没有办法通过选择性覆盖来解决此问题？

**Comment by Alvin9999** [comment]
怎么更新的呢

**Comment by Alvin9999** [comment]
书签可以导出后再导入。

**Comment by ioopd** [comment]
> 怎么更新的呢

都8G以上内存了，64bit!

**Comment by AnyWAT** [comment]
> > 怎么更新的呢
> 
> 都8G以上内存了，need 64bit chrome

https://chromeinstaller.herokuapp.com/  7-ZIP （两次）提取文件 .exe、.7z，复制目录 Chrome-bin 或其下全部文件到 chrome 程序下原相同目录及文件。。。
