### ISSUE TITLE
请问如何用ctrl+w关闭chrome的tab？

### ISSUE THREAD

**Issue by retsyo** [Alvin9999/new-pac#1216]
在这里下载的浏览器，<kbd>ctrl</kbd>+<kbd>w</kbd> 不会关闭当前 tab，相反会新开一个 tab
应该在哪里去设置，让<kbd>ctrl</kbd>+<kbd>w</kbd> 能够关闭当前 tab 呢？谢谢啊

**Comment by Alvin9999** [comment]
你好，ctrl+w是关闭当前tab，ctrl+T是关闭当前tab

**Comment by Alvin9999** [comment]
https://support.google.com/chromebook/answer/183101?hl=zh-Hans

**Comment by Albert1995Einstein** [comment]
下载 Autocontrol 的浏览器扩展，自定义就可以了

> 谢谢这里下载的浏览器，ctrl+w不会关闭当前标签，相反会新开一个标签 应该在哪里去设置，让ctrl+w能够关闭当前标签呢？

下载 Autocontrol 的浏览器扩展，自定义就可以了
