### ISSUE TITLE
有没有免费账号订阅地址？

### ISSUE THREAD

**Issue by blackteahamburger** [Alvin9999/new-pac#1217]
每次免费账号更新都得重新导入，很麻烦。

**Comment by Alvin9999** [comment]
没有，避免被滥用。

**Comment by Pawdroid** [comment]
有的，这个仓库提供免费节点订阅地址，每天更新高质量节点
<https://github.com/Pawdroid/Free-servers>

**Comment by IceYin0** [comment]
您的来信已收悉，谢谢。 ——以上内容为自动回复。
