### ISSUE TITLE
libssl1.1_1.1.1d-0+deb10u2_amd64.deb不存在

### ISSUE THREAD

**Issue by HailongJson** [Alvin9999/new-pac#1219]
10u2在仓库中已不存在，需要替换tcp.sh脚本中的为
https://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1d-0+deb10u8_amd64.deb
![image](https://user-images.githubusercontent.com/30728105/162618016-7b47af4e-6e55-4e21-83ed-fcc64e07e6c4.png)

**Comment by Alvin9999** [comment]
安装的什么呢

**Comment by HailongJson** [comment]
> 安装的什么呢

v2ray安装 BBR/BBR魔改版内核

**Comment by Alvin9999** [comment]
脚本是别人开发的，可以试试bbrplus加速内核

**Comment by yimingxsy** [comment]
大佬，之后在输入6（使用暴力BBR魔改版加速(不支持部分系统)）之后，代码报错：
![WPUOU1B9XWH3H)E( {$AA~R](https://user-images.githubusercontent.com/124903864/229367007-28aeb145-495c-4ae6-af83-973540d006fe.png)
你知道这个怎么修改吗？
