### ISSUE TITLE
谷歌浏览器61高内核版 无法访问谷歌

### ISSUE THREAD

**Issue by GreatGarlic** [Alvin9999/new-pac#122]

**Comment by Alvin9999** [comment]
61高内核版有很多版本？你具体用的哪一款？

**Comment by GreatGarlic** [comment]
@Alvin9999 谷歌浏览器61高内核版 （2017年9月15日发布新软GoProxy Quic版）第一行这个版本

**Comment by Alvin9999** [comment]
只有谷歌访问不了吗？其它网站是否可以？刷新网页或者重启软件看看，最好是截图，比如打不开网站时网页的画面，以及黑框窗口里面的数据画面。

**Comment by GreatGarlic** [comment]
@Alvin9999 只有谷歌不可以
![qq 20170915102753](https://user-images.githubusercontent.com/9128851/30463812-9697d370-9a00-11e7-9c5f-03fd522edb0c.png)

**Comment by Alvin9999** [comment]
打开这个网址https://www.google.com/ncr

**Comment by GreatGarlic** [comment]
@Alvin9999 好了，我知道了过滤规则没有设定，谢谢
