### ISSUE TITLE
太牛了你这个

### ISSUE THREAD

**Issue by huajie2020** [Alvin9999/new-pac#1220]

**Comment by Alvin9999** [comment]
如果觉得不错，也可以分享给自己的好朋友。

**Comment by huajie2020** [comment]
> 如果觉得不错，也可以分享给自己的好朋友。

谢谢你们无私的动作...前辈们做的很好的表现...我会了我会跟着你的脚步前行...刚刚研究这个东西...还不是很会...但是看到你们的无视让我很有感触...现实社会太残酷

**Comment by Alvin9999** [comment]
好的，慢慢来，刚开始会慢点，多多尝试，有不会的地方可以提出来一起交流交流。

**Comment by huajie2020** [comment]
> 好的，慢慢来，刚开始会慢点，多多尝试，有不会的地方可以提出来一起交流交流。

好的好的没问题...我是完完全全白纸哈哈...我就不烦你了我先学学看好久没碰电脑的东西了...哈哈很高兴认识你...等我比较会了在找你...要不然怕你给我问倒烦哈哈

**Comment by Alvin9999** [comment]
OK
