### ISSUE TITLE
clash翻墙 cmd界面开启后过了一会就自动关闭了

### ISSUE THREAD

**Issue by badongdyc** [Alvin9999/new-pac#1223]
如题，clash翻墙 cmd界面开启后过了一会就自动关闭了，请教一下是什么原因，Chrome95_64bit_AllNew_2021.10.20

**Comment by Alvin9999** [comment]
用最新版。同时，下载后的翻墙浏览器压缩包文件解压时，路径中的文件夹名字不要包含空格字符，不然程序会闪退，无法正常启动。

**Comment by badongdyc** [comment]
没有空格，下载了最新版，没问题了，谢谢
