### ISSUE TITLE
自建v2ray，安卓端代理失败

### ISSUE THREAD

**Issue by shuaizi96** [Alvin9999/new-pac#1227]
查看配置里面复制的链接，导入PC端代理工具之后，网页可以访问外网，同样的链接导入Android App，就怎么都访问不到外网，全局路由、重启都试过了无效

![QQ图片20220426214459](https://user-images.githubusercontent.com/26296170/165314145-df00f843-baeb-4d4d-851f-bc9c86130e8f.jpg)

**Comment by Alvin9999** [comment]
网上搜了一下：https://zhidao.baidu.com/question/1582036976269384180.html

**Comment by Alvin9999** [comment]
如果已经排除了手机杀毒软件的影响，而账号信息填写也是正确的，可以试试改一下v2ray传输方式，比如websocket

**Comment by shuaizi96** [comment]
> 如果已经排除了手机杀毒软件的影响，而账号信息填写也是正确的，可以试试改一下v2ray传输方式，比如websocket

换websocket可以了，多谢大佬！
