### ISSUE TITLE
win10 ins上不了啊啊

### ISSUE THREAD

**Issue by xcmw** [Alvin9999/new-pac#123]
每个版本都是，就卡在ins的加载界面，白屏网页。
其他的都正常，也就上个推特ins偶尔上上汤不热，一下少了三分之一的乐趣……

**Comment by Alvin9999** [comment]
如果用的是与GoAgent、GoProxy相关的版本，可以按照使用说明更新一下ip，然后切换浏览器为全局代理，再打开看看。
SSR、GoGo、萤火虫版也尝试了吗？
