### ISSUE TITLE
SSR配置好之后，IP属地似乎无法更改

### ISSUE THREAD

**Issue by Jazihars** [Alvin9999/new-pac#1230]
您好，非常感谢提供的教程。参照https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B 配置好SSR之后，IP属地似乎无法更改。这是怎么回事？

**Comment by Jazihars** [comment]
我的系统代理模式用的就是全局模式，但是IP属地似乎还是无法更改

**Comment by Jazihars** [comment]
哦，好像解决了。把代理规则设为全局就可以了。

**Comment by zleiwang** [comment]
> OK

https://github.com/nojsja/shadowsocks-electron
这个软件又回来了，ssr能用，可以写到列表里

**Comment by Jazihars** [comment]
> https://github.com/nojsja/shadowsocks-electron 这个软件又回来了，ssr能用，可以写到列表里

@zleiwang 这个是SSR的一个变体吗？是不是就是另一个版本的SSR？

**Comment by zleiwang** [comment]
> > [https://github.com/nojsja/shadowsocks-electron](https://hub.fastgit.xyz/nojsja/shadowsocks-electron) 这个软件又回来了，ssr能用，可以写到列表里
> 
> @zleiwang 这个是什么软件？是不是就是另一个版本的SSR？

是的，界面不一样而已

**Comment by Jazihars** [comment]
好的，非常感谢！我关闭问题了
