### ISSUE TITLE
M1 芯片的 Mac SSR 客户端无法访问外网

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1231]
Intel 芯片的是正常的，希望能加个适配 M1 的 SSR Mac 客户端安装包

**Comment by V-zhangyunxiang** [comment]
> 可以在原开发项目上提建议哦

原项目链接地址是什么呢

**Comment by Alvin9999** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG
