### ISSUE TITLE
请问用这个和原来电脑里的v2ray和clash冲突吗？

### ISSUE THREAD

**Issue by 54github** [Alvin9999/new-pac#1242]
我电脑里已经装了v2ray和clash，和chrome浏览器，只是节点不太好用。请问用这个和原来电脑里的v2ray和clash冲突吗？需要先把原来的卸载吗？

**Comment by Alvin9999** [comment]
不冲突，不同时启动就可以了。

**Comment by 54github** [comment]
谢谢！那这个chorme浏览器登录后可以共享我原来的历史记录和收藏夹以及插件吗？

**Comment by Alvin9999** [comment]
可以试试看。至少书签可以导出后导入。
