### ISSUE TITLE
翻墙就翻墙为什么夹带私货

### ISSUE THREAD

**Issue by shanheluren** [Alvin9999/new-pac#1245]
浏览器导航页一堆反共言论，服了

**Comment by mesutozil1088** [comment]
反共算不上什么私货,世上反共的人多了去了.就准你反美,不准别人反共?
花钱的梯子一大堆,非要来这里干嘛.既然支持ccp建墙,花点钱又有啥?
你翻墙没有报备审批就是在违法,既然挺共就该遵守党国的法律,你该去自首而不是来抱怨.

**Comment by jing5460** [comment]
> 反共算不上什么私货,世上反共的人多了去了.就准你反美,不准别人反共? 花钱的梯子一大堆,非要来这里干嘛.既然支持ccp建墙,花点钱又有啥? 你翻墙没有报备审批就是在违法,既然挺共就该遵守党国的法律,你该去自首而不是来抱怨.

傻不垃圾一个，还能说中文！

**Comment by shanheluren** [comment]
> > 反共算不上什么私货,世上反共的人多了去了.就准你反美,不准别人反共? 花钱的梯子一大堆,非要来这里干嘛.既然支持ccp建墙,花点钱又有啥? 你翻墙没有报备审批就是在违法,既然挺共就该遵守党国的法律,你该去自首而不是来抱怨.
> 
> 傻不垃圾一个，还能说中文！

对呀，世界上为什么会有你这样的蠢货，是不是很气对我无可奈何呢

**Comment by shanheluren** [comment]
> > 反共算不上什么私货,世上反共的人多了去了.就准你反美,不准别人反共? 花钱的梯子一大堆,非要来这里干嘛.既然支持ccp建墙,花点钱又有啥? 你翻墙没有报备审批就是在违法,既然挺共就该遵守党国的法律,你该去自首而不是来抱怨.
> 
> 傻不垃圾一个，还能说中文！

跳梁小丑，爸爸爱你哦😙
