### ISSUE TITLE
买服务器只能通过PayPal,? 我看现在已经不支持支付宝了

### ISSUE THREAD

**Issue by yaojin2070** [Alvin9999/new-pac#1249]
![image](https://user-images.githubusercontent.com/48686959/173181887-23402ae6-e5af-4f64-9911-894bba173df7.png)

**Comment by Alvin9999** [comment]
![pay](https://user-images.githubusercontent.com/12132898/173194045-a5301322-ccd4-4d54-9bb1-d692856fdc0f.png)
看了下，可以的哦
