### ISSUE TITLE
为啥chrome下载不了，firefox不出现下载按钮

### ISSUE THREAD

**Issue by arsenal1447** [Alvin9999/new-pac#125]
chrome版本Chrome61_GP_Quic_2017.9.14，下载youtube的视频总是出现 
![](https://s1.ax1x.com/2017/09/17/KeLss.png)
火狐就不再出现下载的按钮了，大神，就我一个是这种情况吗，而且即使可以下载，也只下载部分视频，播放一小段就没了，不全

**Comment by Alvin9999** [comment]
GoProxy下载功能不完善，超过32M的文件就下载不全，与GoProxy相关的版本都会遇到此问题，比如GoProxy版、GoProxy Quic版
