### ISSUE TITLE
能再挂个脚本部署个网站啥的吗

### ISSUE THREAD

**Issue by yaojin2070** [Alvin9999/new-pac#1251]
服务器一个月500g，感觉我用不完，想用来挂个脚本或者部署个小网站啥的，会不会有影响的

**Comment by Alvin9999** [comment]
端口和代理端口不一样就可以

**Comment by Alvin9999** [comment]
需要提醒的是如果代理ip被墙了，那么网站也就被墙了。

**Comment by yaojin2070** [comment]
> 需要提醒的是如果代理ip被墙了，那么网站也就被墙了。

你回复得真快, 很及时, 太感谢你了, 感谢开源
