### ISSUE TITLE
最新的节点有速度但是连不上外网

### ISSUE THREAD

**Issue by lizhaobomb** [Alvin9999/new-pac#1254]
最新的节点有速度但是连不上外网，只有我自己是这样的吗？

**Comment by Alvin9999** [comment]
哪个节点？

**Comment by lizhaobomb** [comment]
> 

SSR的节点用
<img width="171" alt="image" src="https://user-images.githubusercontent.com/3756281/174782474-dce2879b-e0be-4c97-bd5a-bcc3fa3d5ee0.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/3756281/174782569-8f611bc2-008b-47ed-b7ed-41d6c47ec3fe.png">
速度也有，但是就是连不上外网

**Comment by Alvin9999** [comment]
协议和混淆设置没有

**Comment by lizhaobomb** [comment]
设置了的，以前都好好的，就最近才开始不能访问外网了
![image](https://user-images.githubusercontent.com/3756281/174937149-29ff045b-e856-4a8d-ac50-6b3fe30385f4.png)

> 协议和混淆设置没有

**Comment by Alvin9999** [comment]
多尝试几个国外网站看看

**Comment by lizhaobomb** [comment]
> 

试了好多个，都不行，估计这软件太久不更新了吧，我换clashX了

> 多尝试几个国外网站看看
