### ISSUE TITLE
最近怎么回事。翻墙很不稳定

### ISSUE THREAD

**Issue by badongdyc** [Alvin9999/new-pac#1262]
所有工具都是，刚打开时还可以，能顺利翻墙，但是等个几分钟再去，就不行了，要刷新很多次就又可以了，极其不稳定。。，更新了ip也一样。下载的是[谷歌翻墙浏览器103高内核版](https://github.com/Alvin9999/new-pac/wiki/%E9%AB%98%E5%86%85%E6%A0%B8%E7%89%88)

**Comment by Alvin9999** [comment]
应该是你的网络环境或者电脑环境的问题。比如国产杀毒软件、安全卫士、防火墙干扰。

**Comment by badongdyc** [comment]
应该不是吧，一直这样用的，以前都没有问题，都是最近才出现的问题

**Comment by AnyWAT** [comment]
刚发现，貌似《谷歌翻墙浏览器103高内核版》之 clash 下的 ip_1.bat 与 ip_2.bat 更新后的节点完全一致

**Comment by Alvin9999** [comment]
> 刚发现，貌似《谷歌翻墙浏览器103高内核版》之 clash 下的 ip_1.bat 与 ip_2.bat 更新后的节点完全一致

是的，其它不一样。

**Comment by laiqinghan** [comment]
一直用这个爬数据，挺稳定的(https://xmrth.cc/auth/register?code=eyii)
