### ISSUE TITLE
namecheap 注册账号失败

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1263]
一直提示 SECURITY CHECK Please prove you're a human. 他们也没有在线客服，要提工单

**Comment by V-zhangyunxiang** [comment]
在阿里云申请域名是否可以

**Comment by Alvin9999** [comment]
最好用国外域名服务商。注册的时候可以把广告屏蔽插件管了，如果有这个插件的话。

**Comment by V-zhangyunxiang** [comment]
> 最好用国外域名服务商。注册的时候可以把广告屏蔽插件关了，如果有这个插件的话。

关了还是不行

**Comment by V-zhangyunxiang** [comment]
> > 最好用国外域名服务商。注册的时候可以把广告屏蔽插件关了，如果有这个插件的话。
> 
> 关了还是不行

或者还有没有别的国外服务商

**Comment by Alvin9999** [comment]
https://www.freenom.com/zh/index.html?lang=zh 关于freenom注册方法，网上搜一下“freenom注册教程”即可。

**Comment by V-zhangyunxiang** [comment]
torjan 的客户端下载链接能补充下吗，目前有用 vrayN ，也有用 torjan 原生客户端的，Windwos、Mac、Android、iOS 麻烦都补上推荐的客户端链接

**Comment by gpchn** [comment]
路人，+1

**Comment by FY1043031060** [comment]
一样的问题。 暂时没找到解决办法
