### ISSUE TITLE
Torjan 客户端链接补充

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1264]
Torjan 方式的客户端不知道从哪下载，希望补全 Windows、Mac、Android、iOS 的下载地址

**Comment by Alvin9999** [comment]
trojan项目地址：https://github.com/trojan-gfw/trojan/releases/tag/v1.16.0

**Comment by Alvin9999** [comment]
iOS可以用shadowsocket（非大陆ID下载）

**Comment by V-zhangyunxiang** [comment]
torjan 脚本没有类似 SSR 脚本的 bash ssr.sh 的快捷管理命令吗，比如想查看当前绑定的域名，修改绑定的域名，等等功能

**Comment by Alvin9999** [comment]
没有哦
