### ISSUE TITLE
YouTube 高清视频下载

### ISSUE THREAD

**Issue by yezine** [Alvin9999/new-pac#1268]
YouTube 高清视频下载，支持搜索，海量视频，完全免费，全程无需科学：https://tools.liu.app/youtube

**Comment by stayfoolish777** [comment]
> YouTube 高清视频下载，支持搜索，海量视频，完全免费，全程无需科学：https://tools.liu.app/youtube

来个p的下载，你懂的

**Comment by yezige** [comment]
> > YouTube 高清视频下载，支持搜索，海量视频，完全免费，全程无需科学：https://tools.liu.app/youtube
> 
> 来个p的下载，你懂的

来个q的下载，你懂的

**Comment by meliu88** [comment]
好像不能用了
