### ISSUE TITLE
请问，facebook登录不了，ins也打不开

### ISSUE THREAD

**Issue by qazwsx543** [Alvin9999/new-pac#127]
GoAgent高内核最新版，win8.1系统
很久之前也遇到facebook无法登陆的情况，把36的内核升到53就好了
这两天又登不行了，然后下了高内核的最新版也不行……
哦对了还有一个问题是这版的chrome很多应该是左键单击的左键单击没反应，要右键单击才行

**Comment by Alvin9999** [comment]
谢谢反馈。争取以后改进。

**Comment by qazwsx543** [comment]
好的，谢谢您。
我更新了ip之后Facebook可以用了，ins还是打不开，http error503

**Comment by Alvin9999** [comment]
推测是ins屏蔽了谷歌ip所致。GoAgent、GoProxy以及与之相关的版本用的是谷歌ip。你可以换其它版本试试看。
