### ISSUE TITLE
请教一下华为云香港服务器可以搭建SSR服务吗

### ISSUE THREAD

**Issue by epiao55** [Alvin9999/new-pac#1270]
服务器本身可以直接ping通海外，搭建完SSR后，我本地还是ping不通海外站点，请教一下是服务器的问题吗，必须用国外的厂商吗

**Comment by Alvin9999** [comment]
关闭服务器防火墙。混淆推荐用tls1.2_ticket_auth。
当然，不推荐用国内服务商。
