### ISSUE TITLE
win10家庭版系统，打开谷歌高内核版插件崩溃，无法上网

### ISSUE THREAD

**Issue by shanechiang85** [Alvin9999/new-pac#1272]
安装了谷歌103高内核版，管理员运行任意一个翻墙软件，打开的chrome浏览器均显示崩溃，之前版本，在系统代理中设置127.0.0.1，端口8080可以解决，更新后，无法上网，使用netstat查端口情况，将所有监听端口占用软件杀掉后依然不行，哪里出了问题？

**Comment by Alvin9999** [comment]
试试关闭防火墙，然后重新解压后再试试看

**Comment by shanechiang85** [comment]
没有用
