### ISSUE TITLE
请问用v2ray搭建非常不稳定怎么办

### ISSUE THREAD

**Issue by ziyewqg324** [Alvin9999/new-pac#1276]
买了个域名，用的websocket+TLS+Web协议，机房选的是new jersey的，但是浏览油管或者小蓝鸟几分钟就会断开，然后过几分钟又恢复，v2Ray的控制台显示的信息是这样的：
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://"我自己买的域名"/ray):  > dial tcp "我的vps
": i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://"我自己买的域名"/ray):  > dial tcp  "我的vps
": operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://"我自己买的域名"/ray):  > dial tcp: lookup "我自己买的域名": operation was canceled] > common/retry: all retry attempts failed

**Comment by Alvin9999** [comment]
bbr plus部署一下看看

**Comment by ziyewqg324** [comment]
> 

thanks
