### ISSUE TITLE
求助：Telegram 注册收不到验证码怎么回事？

### ISSUE THREAD

**Issue by wn0112** [Alvin9999/new-pac#1277]
* iPhone
* Google Voice 号码
* 已科学上网，能打开google, youtube, fb等

现象：
app 上注册，输入号码，点发送后，转圈后提示 让我检查网络连接

Telegram app 是 科学上网后下载的，从youtube 官网上也下过，结果一样。

**Comment by Alvin9999** [comment]
google搜索了一下，可以参考下其他人的解决方法，有可能是科学上网的ip问题。
[Telegram 注册收不到google voice验证码怎么回事？](https://www.google.com/search?q=Telegram+%E6%B3%A8%E5%86%8C%E6%94%B6%E4%B8%8D%E5%88%B0google+voice%E9%AA%8C%E8%AF%81%E7%A0%81%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F&ei=nDkHY5XaOqmekPIP1Pms6Ac&ved=0ahUKEwiVmO32z-H5AhUpD0QIHdQ8C30Q4dUDCA4&uact=5&oq=Telegram+%E6%B3%A8%E5%86%8C%E6%94%B6%E4%B8%8D%E5%88%B0google+voice%E9%AA%8C%E8%AF%81%E7%A0%81%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEKIEMgcIABAeEKIEMgUIABCiBDIHCAAQHhCiBDoHCAAQRxCwA0oECEEYAEoECEYYAFDkBFiDKGCQKWgBcAF4AIABxgKIAY8fkgEGMi0xMi4ymAEAoAEByAEKwAEB&sclient=gws-wiz)

**Comment by wn0112** [comment]
> 

这个项目连接的科学上网 IP 都不行吗？ 我在这里下载的Chrome ，目录里面的 SSR, v2ray, clash等 方式好像都不行

**Comment by Alvin9999** [comment]
不清楚，没有研究过注册Telegram，只是说有可能是ip的原因，需要你自己研究下。

**Comment by Alvin9999** [comment]
刚刚尝试弄了一下，可以试试现在能不能上telegram
