### ISSUE TITLE
google无法关闭安全搜索

### ISSUE THREAD

**Issue by SHINGO945** [Alvin9999/new-pac#1280]
请问在使用最新的[谷歌翻墙浏览器105高内核版]时，显示google安全搜索无法关闭，原因是“您无权更改安全搜索设置。安全搜索已被设备或您浏览内容时使用的网络锁定”；此外，部分网站无法访问，两三周之前还没有这个问题。
我不清楚以上2个问题是否有关联，烦请解答，谢谢！

**Comment by Alvin9999** [comment]
屏蔽了色情网站。

**Comment by zxrzxc728** [comment]
这就很难受啊，谁天天光看政治新闻啊。是个人也没这么枯燥吧。求9月3号 之前版本，手欠9月3号更新了，安全搜索关不掉了。
