### ISSUE TITLE
谷歌翻墙浏览器105高内核版 无法更新v2rayN的订阅地址

### ISSUE THREAD

**Issue by nmaooo** [Alvin9999/new-pac#1281]
复制并粘贴到v2ray客户端再更新订阅即可刷出节点，会不定期的更新

https://raw.githubusercontent.com/fggfffgbg/https-aishangyou.tube-/master/README.md

https://jiang.netlify.com

https://bujidao.cf/api/user/account/subscribe/4e2a59218aabb9bdaa32c78de894bbe7?type=shadowrocket&ip=0&flow=0

https://github.com/ImLaoD/sub/raw/master/v2ray_ssrshare.com

https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub

https://youlianboshi.netlify.com/

**Comment by Alvin9999** [comment]
无法更新地址有可能是国内网络无法正常连接导致。
