### ISSUE TITLE
打开某些网址显示此网站无法提供安全连接

### ISSUE THREAD

**Issue by KasuganoSakura** [Alvin9999/new-pac#1283]
请问如何解决这个问题 有时能打开 不稳定 

![QQ截图20220909172603](https://user-images.githubusercontent.com/113174765/189318829-b17e146f-e7a6-421d-b7f8-f6c787f7d312.jpg)
![QQ截图20220909172824](https://user-images.githubusercontent.com/113174765/189318841-50a08fe8-8889-4e39-80d5-709b10864b32.jpg)

**Comment by Alvin9999** [comment]
屏蔽了色情网站。非色情网站如果打不开，可以尝试更新ip或者更换工具。

**Comment by Alvin9999** [comment]
或者刷新几次网页。

**Comment by KasuganoSakura** [comment]
> 如果非教育网站打不开，可以尝试更新ip或者更换工具。

以前都不屏蔽的 后期是加了新的屏蔽规则吗？

**Comment by Alvin9999** [comment]
是的。服务器屏蔽了这些色情网站。
