### ISSUE TITLE
按照脚本进行了部署，但是V2ray依然无法自动启动

### ISSUE THREAD

**Issue by yocus** [Alvin9999/new-pac#1286]
starting v2ray...
v2ray start fail !

完全按照教程进行的操作，但是重试了很多次都不能启动V2ray，重启VPS，date时区也对，没有进行升级，也没有安装加速。也执行了教程中说的三条命令，但依然是不启动。确定操作是完全对照教程的，非常困惑。

root@NewJersey:~# sed -i "s/v2ray -config/v2ray run -config/g" /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
sed: can't read /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf: No such file or directory
root@NewJersey:~# 
root@NewJersey:~# systemctl daemon-reload
root@NewJersey:~# 
root@NewJersey:~# systemctl restart v2ray

**Comment by yocus** [comment]
确定问题是存在的，https://github.com/Jrohy/multi-v2ray/issues/608 这里也有网友反馈，因为我一直是用Alvin9999的教程，一直都很好用，而且对新手极度友好，所以也看到了一个比较简单可行的方案：直接使用管理命令update到指定版本，比如：
v2ray update v4.45.2


以上，希望遇到同样问题的朋友可以恢复自由上网~ 最后感谢Alvin9999

**Comment by Alvin9999** [comment]
OK
