### ISSUE TITLE
大佬wireguard 教程不对

### ISSUE THREAD

**Issue by fgcd8964** [Alvin9999/new-pac#1287]
大佬今天一下午时间在不停的自建wireguard，下载配置文件命令在xshell 7 里面不存在“yum -y install lrzsz”
换了不下30多个IP，xshell都可以连上，可是ping都可以拼通，部分掉包，依然无法爬过深墙。
是不是wireguard配置被墙需要像v2ray ss ssr用那个魔改加速呢？
折腾快8彻底崩溃，都快不想配置，极度怀疑自己电脑安错软件导致不能过墙，用大佬的集合版轻松过去
我需要下载英语和日语教学才买VPS，不想占用大佬这些工具流量
大佬邮箱是多少呢？记得以前和你发过邮件的

**Comment by Alvin9999** [comment]
部署完成后，重启下vps看看，输入reboot  
如果实在不行，也不排除你所在地区不适合这种方式。那么可以换其它工具，比如搭建ssr，这个也比较稳定，用教程推荐的参数来搭建，抗封锁性要强很多。

邮箱kebi2014@gmail.com

**Comment by Alvin9999** [comment]
WireGuard VPN服务器搭建教程已更新。
