### ISSUE TITLE
新工具hysteria自建教程已发布

### ISSUE THREAD

**Issue by Alvin9999** [Alvin9999/new-pac#1289]
[自建hysteria服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAhysteria%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by fgcd8964** [comment]
大佬 这速度太牛B了

**Comment by fgcd8964** [comment]
用大佬的工具都可以上網，但是自己和大佬搭建的不知道麼問題就是不能下載達100kb,懷疑還是vps太爛，還是想個辦法申請搬瓦工，或是亞馬遜，甲骨文，遠離牆內有毒訊息
天天躲避核酸檢測人員，昨天差點被人害得抓了，一直說我不做核酸，不被抓住我是不會妥協，幾天前在推特看到有個偷渡的推文，沒細看，我這人沒多少錢，只能靠偷渡遠離糞坑


自由上网 ***@***.***> 於 2022年9月20日 週二 19:09 寫道：
