### ISSUE TITLE
twitter无法转发 twitter网页内视频无法加载

### ISSUE THREAD

**Issue by hyehye2323** [Alvin9999/new-pac#129]
是内核较低的问题吗

**Comment by Alvin9999** [comment]
不一定。不知道你具体用的哪款软件，给你如下建议：
如果按照使用说明能做的都做了，还不是不行的话，且自己特别想玩twitter，可以换其它的版本试试看。

**Comment by hyehye2323** [comment]
GoAgent版 已经是53内核

**Comment by Alvin9999** [comment]
刚刚在云端做了一次改动，你运行一下ip更新文件来同步云端的设置，然后再试试看
