### ISSUE TITLE
9月3号后的版本google安全搜索关不掉了

### ISSUE THREAD

**Issue by zxrzxc728** [Alvin9999/new-pac#1290]
不能这样搞啊老大，不然不就违背了网站所为的“自由”二字嘛，谁天天光看政治新闻，不乏味吗？FQ用谷歌最大的意义不就是因为它自由嘛，你这么一搞逼着开VPN去了又要，如果有人有这方面需求，您可以出两个版本嘛，各取所需啊，你这直接一刀切，多难受。。。

**Comment by AnyWAT** [comment]
貌似不是“9月3号后的版本”浏览器的事，而是代理服务器的事？

**Comment by zxrzxc728** [comment]
> 貌似不是“9月3号后的版本”浏览器的事，而是代理服务器的事？

那怎么办啊大佬，我貌似就是9月3号更新之后就这样了，你们咋解决的啊

**Comment by Alvin9999** [comment]
服务器屏蔽了色情内容，非浏览器设置问题。

**Comment by Alvin9999** [comment]
不好意思，色情对人的精气神不好，所以屏蔽了。

**Comment by zxrzxc728** [comment]
> 不好意思，色情对人的精气神不好，所以屏蔽了。

是永久禁止了吗？

**Comment by zxrzxc728** [comment]
> 不好意思，色情对人的精气神不好，所以屏蔽了。

说实话这起不到很大效果的，只能让人变得很头痛，像推特还有收藏的很多色网也都还是能上的，只是锁了google让人变得很是别扭和麻烦啊大佬，希望能慎重啊，就像国内不让FQ，不还是有办法F嘛。三思啊大佬

**Comment by AnyWAT** [comment]
> 那怎么办啊大佬，我貌似就是9月3号更新之后就这样了，你们咋解决的啊

用其他代理呀，如：迷雾通

**Comment by AnyWAT** [comment]
> 服务器屏蔽了色情内容，非浏览器设置问题。

不仅如此，貌似还定时重连，刷个推都常常不爽：图片加载不正常、评论显示不全，得刷新或更换。。。

**Comment by Alvin9999** [comment]
> > 服务器屏蔽了色情内容，非浏览器设置问题。
> 
> 不仅如此，貌似还定时重（断）连，刷个推都常常不爽：图片加载不正常、评论显示不全，得刷新或更换。。。

现在用的人很多了，服务器负载大，如果不定时重启服务那么速度会越来越慢。看看之后能不能找到更好的解决方法。

**Comment by zxrzxc728** [comment]
> 迷雾通

谢谢啊，我去试试

**Comment by zxrzxc728** [comment]
> > > 服务器屏蔽了色情内容，非浏览器设置问题。
> > 
> > 
> > 不仅如此，貌似还定时重（断）连，刷个推都常常不爽：图片加载不正常、评论显示不全，得刷新或更换。。。
> 
> 现在用的人很多了，服务器负载大，如果不定时重启服务那么速度会越来越慢。看看之后能不能找到更好的解决方法。

慢点都理解，但阉割了真没办法用了
