### ISSUE TITLE
搭建完成后能知道有多少人在使用这个梯子吗

### ISSUE THREAD

**Issue by Nullres** [Alvin9999/new-pac#1293]
搭建完成后能知道有多少人在使用这个梯子吗，或者能不能查询使用这个梯子的人的浏览记录

**Comment by Alvin9999** [comment]
搭建完成后，只有你自己知道密码这些，没有其它人使用。
如果你分享账号给别人，搭建ssr工具的话可以查看到使用人数，不能查询浏览记录。

**Comment by Nullres** [comment]
> 

感谢dalao

**Comment by Alvin9999** [comment]
好的
