### ISSUE TITLE
用代理腳本的話Chrome無法使用

### ISSUE THREAD

**Issue by Mazakanull** [Alvin9999/new-pac#1294]
如果從app文件夾裏的chrome.exe能正常打開瀏覽器可以正常使用，但使用作者編的翻墻腳本打開的就所有擴展崩潰，包括設置在內的所有標籤頁都打不開。
請問這個怎麽解決呢

**Comment by Alvin9999** [comment]
解压路径中的文件夹名字不要包含空格字符
