### ISSUE TITLE
问一下哪里能下载chrome浏览器的免安装版本，也就是便携版！

### ISSUE THREAD

**Issue by maidiweide** [Alvin9999/new-pac#13]
一直用您发布的翻墙，先说声谢谢。然后我想问一下哪里能下载比较靠谱的chrome浏览器的免安装版本，也就是便携版，最好是50以上的版本。就像您发布的翻墙，下载后解压就能打开的！万分感谢！

**Comment by Alvin9999** [comment]
谷歌浏览器便携版制作方法可以参考这个http://www.zdfans.com/2055.html

**Comment by maidiweide** [comment]
好的，谢谢啦

**Comment by caofengzi** [comment]
@maidiweide 此網站下載的便攜版比zd23那個做的好。http://portableapps.com/apps/internet/google_chrome_portable
