### ISSUE TITLE
关于在国内其他浏览器上安装youtube下载插件

### ISSUE THREAD

**Issue by shemengjia** [Alvin9999/new-pac#130]
@Alvin9999 [大大你好，小的想在国内例如QQ，搜狗浏览器上安装youtube720P下载插件，恳请大大能发我下拓展程序么，如果不是的话怎么弄啊求教，小的感激不尽！！！！可以的话发我邮箱吧，1752924104@qq.com

**Comment by Alvin9999** [comment]
我也没有哦～

**Comment by pgz123** [comment]
@ @Alvin9999 大大中秋节快乐，感谢付出
