### ISSUE TITLE
Trojan 安装过程一直提示 https 证书没有申请成功

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1300]
![image](https://user-images.githubusercontent.com/22291811/194292715-c5bcfdd2-80a4-4944-bb2d-17514387588e.png)

**Comment by V-zhangyunxiang** [comment]
我的域名绑定过一个 IP ，这次我想换个新 IP 绑定这个域名。IP 已经更新到域名服务商了，也解析成功了

**Comment by Alvin9999** [comment]
换个二级域名试试

**Comment by luichooy** [comment]
> 我的域名绑定过一个 IP ，这次我想换个新 IP 绑定这个域名。IP 已经更新到域名服务商了，也解析成功了

请问你解决了吗 遇到同样的问题

**Comment by V-zhangyunxiang** [comment]
> > 我的域名绑定过一个 IP ，这次我想换个新 IP 绑定这个域名。IP 已经更新到域名服务商了，也解析成功了
> 
> 请问你解决了吗 遇到同样的问题

这个脚本第 3 个选项有个修复证书，执行下，再跑一边安装 Trojan，我这里就好了

**Comment by KwaBEF** [comment]
解决了嘛，这个证书不知道怎么一直弄不了

**Comment by Alvin9999** [comment]
如果是centos系统，需要先关闭vps服务器的防火墙

**Comment by KwaBEF** [comment]
解决了，gen更换个二级域名之后选择脚本里的修复证书就可以了

自由上网 ***@***.***> 于2023年11月23日周四 14:14写道：

**Comment by Alvin9999** [comment]
用这个脚本可以一键搭建trojan，无需域名
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B
