### ISSUE TITLE
idm怎么用不了

### ISSUE THREAD

**Issue by Blake-Jiang** [Alvin9999/new-pac#1304]
如何使用idm拓展程序？

**Comment by AnyWAT** [comment]
在任何正在播放的 youtube 视频地址栏中 youtube.com 之间插入 pi 成 youtubepi.com 再打开，即可转至视频下载页面，按网页提示或可成功（非断点续传地）下载视频。
如果仍然无法正常下载，可在浏览器下载内容 chrome://downloads 内复制该视频下载链接，用支持断点续传但无法从 youtube 获得下载地址的 FDM 来正常下载视频。
