### ISSUE TITLE
最近节点质量好差。。

### ISSUE THREAD

**Issue by gongmengen** [Alvin9999/new-pac#1309]
最近节点经常连接超时啊（即使拉到了连接也很不稳定），没办法像之前一样愉快的YouTube了呢/(ㄒoㄒ)/~~
有什么好办法嘛？
或者推荐一下便宜好用的VPN？

**Comment by Alvin9999** [comment]
可以试试这个
https://github.com/Alvin9999/new-pac/wiki/V2free%E6%9C%BA%E5%9C%BA

**Comment by dolphinsboy** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4864391/199213887-f811a56c-9731-45b1-8d24-9c8bf3532be3.png">
