### ISSUE TITLE
为什么鼠标左键点不了？

### ISSUE THREAD

**Issue by edendon** [Alvin9999/new-pac#131]
不知道为什么我的电脑上右键弹出的菜单、收藏夹等点鼠标左键没有用，要点鼠标右键才是相当于是确定。解压以后直接运行的，都是默认的设置还有插件

**Comment by Alvin9999** [comment]
我猜测你是win10系统。这个是高内核便携版兼容性的问题，在某些系统上才会出现这个问题。如果影响了使用，可以换低内核版，然后按照低内核版的《内核升级方法》升级到53内核。

同类的低内核版和高内核版仅仅是浏览器内核不同，翻墙方式都是一样的。

如果不想换低内核的版本，那么目前先凑合用一下哈。争取下次改进。
