### ISSUE TITLE
clash彻底挂了

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#1310]
error: 198.41.212.122:443 connect error: dial tcp4 198.41.212.122:443: i/o timeout 十一以后开始就这样了，6个ip全都不顶用了。

**Comment by Alvin9999** [comment]
那可能是你所在地的网络封锁比较厉害，从服务器带宽和资源消耗看，clash目前使用人数还是挺多的。建议你换其它工具来使用。
