### ISSUE TITLE
您好为什么最新版本的显示下载油管视频错误。。求看我

### ISSUE THREAD

**Issue by Alexmorgan1** [Alvin9999/new-pac#132]
我是用您的 谷歌浏览器61高内核版 （2017年9月15日发布新软GoProxy Quic版，更新SSR版；2017年9月6日升级所有版本浏览器内核为61）这个版本，十分的好用，就是有个问题，下载的时候显示 "失败-服务器出现问题"，或者"没有找到文件"等字眼.，，，
在前几个月里，我用的是17年1月2号的一个版本，之前没问题，前几天发现不能上了，加载不出来，还好找到了文件里的更新地址，于是下载了最新版。结果想下载没法下载，我证书也安装了该弄的都弄了就是没办法。一切正常就是下载没法下载，首先我测试了视频源是没问题了，所有视频点击下载都不可以。我的电脑是惠普的64位，win7系统，固态180g接下来我会附上图片给您更好的了解是哪里出了问题，我试过重装3遍，下载过后几个版本，谷歌浏览器低内核GoProxy Quic版（2017年9月15日发布新软）
谷歌浏览器低内核GoAgent版（2017年8月19日更新版本，提供XP系统打开YouTube出现乱码的解决方法）谷歌浏览器低内核GoAgent soso版（2017年8月19日更新版本，提供XP系统打开YouTube出现乱码的解决方法）谷歌浏览器低内核GoProxy版（2017年9月2日更新版本）结果要么出现同第一个版本无法下载视频的问题就是加载不出来，或者是下载得了一两个后又不行了，我是个某视频站上的无偿搬运工，想搬运些有趣的视频给大家看，可是当今无法下载视频真的难倒我了，希望您有空可以恢复我一下，我也不知道您能不能看见我发的，谢谢您了。

**Comment by Alexmorgan1** [comment]
- 

@Alvin9999

**Comment by Alexmorgan1** [comment]
@

**Comment by Alexmorgan1** [comment]
@Alvin9999 麻烦您看看

**Comment by Alexmorgan1** [comment]
图片发不了，，咋办

**Comment by Alvin9999** [comment]
邮件已回复。
