### ISSUE TITLE
Windows11，一直没问题，这几天突然出现了闪退

### ISSUE THREAD

**Issue by peigd** [Alvin9999/new-pac#1326]
解压路径中没有中文或空格，解压到D盘一级、二级目录都尝试了，但还是闪退，也偶尔出现9009的错误代码，崩溃ing
![image](https://user-images.githubusercontent.com/47517242/205081054-fe9b93ae-240f-475a-973f-98caf23828a3.png)
![image](https://user-images.githubusercontent.com/47517242/205081317-7550ff9e-f62e-4a7f-bc57-532bb0bf16b0.png)

**Comment by AnyWAT** [comment]
自己安装 Clash for Windows，Chrome 原版或能自动更新的便携版 MyChrome，利用大佬提供的 ip_Update 资源武装 Clash，随时更新节点配置，拥有免折腾收藏栏的自己专属的浏览器，除了偶尔节点不行，也不见啥闪退。

**Comment by Alvin9999** [comment]
每款工具都是闪退吗？

**Comment by Alvin9999** [comment]
@peigd

**Comment by Alvin9999** [comment]
换到C盘或者其它硬盘，再重新解压看看

**Comment by peigd** [comment]
是的

**Comment by peigd** [comment]
@Alvin9999

**Comment by Alvin9999** [comment]
@peigd  没有其他人反应这个问题。你试试最新版。

**Comment by beginner2012** [comment]
我这也有这问题，所有的打开都闪退

**Comment by Alvin9999** [comment]
> 我这也有这问题，所有的打开
换个解压路径，重新解压。
