### ISSUE TITLE
那个hysteria的acme证书功能有问题，貌似只能用自签证书wechat.com

### ISSUE THREAD

**Issue by mebest100** [Alvin9999/new-pac#1327]
那个hysteria的安装，你用了它内置的acme签发证书吗，我这边好像不行，客户端启动会报错：
error:lookup xxx域名 on 114.114.115.115:53: Post "https://223.5.5.5/dns-query": x509: certificate is valid for 223.5.5.5, 223.6.6.6, not 223.5.5.5] Failed to initialize client
貌似只能用它自签的证书wechat.com,  它那个acme的证书功能是不是有问题？

**Comment by Alvin9999** [comment]
可以提问脚本的开发项目：https://github.com/emptysuns/Hi_Hysteria
如果自己域名实在不行，用自签也可以。

**Comment by mebest100** [comment]
这个我找到原因了，不是域名也不是证书的原因，应该是脚本生成客户端的json配置有问题，把config.json下面的配置删除就好了
"resolver": "https://223.5.5.5/dns-query"

**Comment by Alvin9999** [comment]
OK
