### ISSUE TITLE
无法访问pornhub，如何解决？

### ISSUE THREAD

**Issue by Hazerink** [Alvin9999/new-pac#1328]
![image](https://user-images.githubusercontent.com/119715349/205418534-998354f5-44e8-4045-83d5-f346b27daec1.png)
app中的所有代理都不能访问pornhub，其他大部分网站都能访问，请问是app禁止了这个网站的访问，还是我自己这里设置有问题？怎么解决呢？

**Comment by Alvin9999** [comment]
屏蔽了色情网站。
