### ISSUE TITLE
帮忙看眼，v2ray的vmess网速显示-1ms

### ISSUE THREAD

**Issue by wanglun7** [Alvin9999/new-pac#1334]
mac电脑，v2ray客户端，vmess导入，最近的两个账号貌似都用不了了哎
能否帮忙排查一下，需要我提供什么信息

另，之前的免费账号是没问题的，非常感谢这里提供的账号，Thanks
<img width="648" alt="WX20221215-192930@2x" src="https://user-images.githubusercontent.com/23076830/207848414-1591e6c7-ff60-4cbd-a8a5-60209a11b864.png">

**Comment by wh9007** [comment]
你好 能帮忙发一个v2ray的安装包吗
我这里无法打开网页

获取 Outlook<https://aka.ms/o0ukef>
________________________________
发件人: 汪仑 ***@***.***>
发送时间: Thursday, December 15, 2022 7:31:53 PM
收件人: Alvin9999/new-pac ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Alvin9999/new-pac] 帮忙看眼，v2ray的vmess网速显示-1ms (Issue #1334)


mac电脑，v2ray客户端，vmess导入，最近的两个账号貌似都用不了了哎
能否帮忙排查一下，需要我提供什么信息

另，之前的免费账号是没问题的，非常感谢这里提供的账号，Thanks
***@***.***<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F23076830%2F207848414-1591e6c7-ff60-4cbd-a8a5-60209a11b864.png&data=05%7C01%7C%7Cc33f5632cbb645e746f008dade8ff7c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638067007156631499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bT1MzahB%2Be%2Fc%2BhDQPE9fXW4kzoXnCahJ0yWF51sXlFs%3D&reserved=0>

―

**Comment by Alvin9999** [comment]
@wanglun7 提供一下打开网页时，网页的提示界面。

**Comment by Alvin9999** [comment]
@wh9007 什么系统？

**Comment by wanglun7** [comment]
> @wanglun7 v2ray账号已更新，更换了ip，可以用最新的账号试试看。

谢谢你，已经恢复正常
