### ISSUE TITLE
所有版本的浏览器都无法翻墙，请问是暂时性问题么

### ISSUE THREAD

**Issue by RussellFu** [Alvin9999/new-pac#134]
![360 20171005133744816](https://user-images.githubusercontent.com/29419217/31212330-6b7fd5fc-a9d2-11e7-9d3e-e96a0ab39516.jpg)
![360 20171005133756003](https://user-images.githubusercontent.com/29419217/31212329-6b7f28c8-a9d2-11e7-8672-4de710046118.jpg)
因为前两天还在正常用，应该不是失效吧？

**Comment by Alvin9999** [comment]
你的图片显示的goproxy不是正常启动后的状态。请下载最新版，下载最新版后，先按照《使用说明（必看）》运行ip更新文件，将ip更新到最新的云端配置，然后再使用。

软件下载地址：https://github.com/Alvin9999/new-pac/wiki

**Comment by Alvin9999** [comment]
正常启动并打开网站，黑框里面要有数据滚动才算正常。如图：
![2](https://user-images.githubusercontent.com/12132898/31229917-d76dd13c-aa14-11e7-945e-d2d78f431cea.PNG)

**Comment by RussellFu** [comment]
现在已经恢复了，辛苦你了，多谢！
