### ISSUE TITLE
SSR vpn网速变慢怎么办?

### ISSUE THREAD

**Issue by DamonDay** [Alvin9999/new-pac#1346]
想过重启server, 但是担心重启之后又要一堆配置

**Comment by Alvin9999** [comment]
搭建bbr加速没有？
重启后不用再次搭建。

**Comment by DamonDay** [comment]
> 搭建bbr加速没有？ 重启后不用再次搭建。

当前状态: 已安装 BBRplus 加速内核 , BBRplus启动成功
-- 重启了, 显示已启用加速

**Comment by Alvin9999** [comment]
服务器位置是什么？

**Comment by DamonDay** [comment]
> 服务器位置是什么？

新泽西

**Comment by Alvin9999** [comment]
可以考虑换成洛杉矶
