### ISSUE TITLE
自购证书邻到期更新证书问题

### ISSUE THREAD

**Issue by s1mple-child** [Alvin9999/new-pac#1350]
hi，我自己购买了一个域名，然后证书临近到期了，然后我在托管域名的站点renew了一年，我想了解下如果我更新了域名后对应域名的服务器会自动更新吗？还是需要什么办法来手动更新？

**Comment by Alvin9999** [comment]
这个不是很清楚，如果到时候不可用，可以考虑重新搭建。

**Comment by s1mple-child** [comment]
> 这个不是很清楚，如果到时候不可用，可以考虑重新搭建。

OK，之前看服务器里没有更新，可能需要重新部署
