### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by VeganBirdie** [Alvin9999/new-pac#1352]
https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAWireGuard-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B
最后生成的配置文件，address都是10.77.0.2，但是vultr本身是不带的,到setting开启pvc以后分配的地址不唯一。
当然不论是手动修改地址前\后，使用wireguard官方客户端连接都"握手失败"。
https://www.linode.com/docs/guides/centos-wireguard-installation-and-configuration/
已解决：这个'private address' 不是那个‘private address',UDP被墙需要加上套件。。。

照着这个教程来搭建服务端：
“Start WireGuard with [wg-quick](https://manpages.debian.org/unstable/wireguard-tools/wg-quick.8.en.html) script. This is a convenient wrapper for many of WireGuard’s common functions.”
sudo wg-quick up wg0
就出错显示不支持此操作，device wg0 not found, 难道vultr服务器本身限制不能使用wireguard?
已解决：搜索后发现问题所在，服务器自带版本较老，需要补充kernel headers或者装新内核（5.1以上自带headers），不然wireguard无法识别。
不过很奇怪，一键包搭的有出站没入站，手动搭的出站都没有。头好晕呐。又不能用google找资料，好吃力，好费时间。

**Comment by Alvin9999** [comment]
WireGuard VPN服务器搭建教程已更新。
