### ISSUE TITLE
有没有办法把默认打开的浏览器改成其它的？比如Edge

### ISSUE THREAD

**Issue by xux7943** [Alvin9999/new-pac#1358]
因为包括Edge在内的都是chrome内核的了，但因为使用习惯上的问题，我想很多人想知道怎么把默认打开的chrome浏览器换成本机正在使用的，谢谢~

**Comment by AnyWAT** [comment]
没弄清大佬提供的是免安装的绿色浏览器，与楼主“本机正在使用的”Edge 是两类。。。
如想“替换”，只有楼主自己动手：提取绿色浏览器中的代理，系统自带的Edge 加装代理扩展。貌似除了自己，其他人无法代劳。

**Comment by xux7943** [comment]
抱歉提出这么小白的问题，可能我描述的不太清楚，因为大佬直接给打开绿色chrome就能使用代理，我想在打开大佬代理（例如CLASH.cmd）时自动打开的是Edge或者是Maxthon浏览器，这样就不用再在浏览器内配置代理设置了……
现在我是打开CLASH.cmd后又得在系统浏览器里设置代理http端口的方法~

**Comment by AnyWAT** [comment]
> 例如CLASH.cmd

尝试编辑 CLASH.cmd 的倒数二、三行？

**Comment by xux7943** [comment]
> 

感谢楼主耐心回复，此方案可行，原谅我对官方配置的不了解（习惯性不敢动官方配置文件:P）
