### ISSUE TITLE
GoAgent soso版好像挂了。。。电信和移动的网络都不行

### ISSUE THREAD

**Issue by Explore911** [Alvin9999/new-pac#136]
两个一键启动的都不能搜Ip了，无法上网

**Comment by Alvin9999** [comment]
近期GoAgent soso版确实不好用，我在等待合适的时机再更新。在此之前请更换其它版本，比如GoProxy Quic版、GoProxy版、SSR版等，使用这些版本前，请按照《使用说明（必看）》更新ip到最新的配置，然后再使用。

这个长假封锁明显加重，能够搜到的可用ip很少，可能跟马上的开会有关，根据以往经验，收假后或者开完会后，封锁会减轻。

**Comment by decemer** [comment]
@Alvin9999 我自己部署的GoProxy Quic版最近也不稳定了，我在cn canton，电信，goagent已经0/0了
any other good way to pass？
还有就是为什么lantern 一直不怕block
read udp: HandshakeTimeout: Crypto handshake did not complete in time.

**Comment by Alvin9999** [comment]
@decemer 可以尝试部署SSR，SSR协议至少现在表现很好

**Comment by decemer** [comment]
@Alvin9999 那个日本的服务器今天貌似上不了了，是关了吗20171010
