### ISSUE TITLE
求助，下午装了个硬盘，其余什么都没干，晚上开机就不行了

### ISSUE THREAD

**Issue by hutao01-miku** [Alvin9999/new-pac#1366]
今天晚上为啥都不能用了，软件显示能连上但网页全都打不开，并且在连上的状态下自己的浏览器也没有网了，可能就我一个这样？

**Comment by Alvin9999** [comment]
重新下载后解压。

**Comment by AnyWAT** [comment]
> 今天晚上为啥都不能用了，软件显示能连上但网页全都打不开，并且在连上的状态下自己的浏览器也没有网了

那又怎么来的这里？
那又如何重新下载？
试试：重置网络？

**Comment by hutao01-miku** [comment]
> > 今天晚上为啥都不能用了，软件显示能连上但网页全都打不开，并且在连上的状态下自己的浏览器也没有网了
> 
> 那又怎么来的这里？ 那又如何重新下载？ （最多）不是重新解压即可？ 试试：重置网络？
用插件Fast能直接进github，原因找到了，谢谢。
