### ISSUE TITLE
V2ray梯子已断

### ISSUE THREAD

**Issue by AlonsoZeng** [Alvin9999/new-pac#1372]
其他可以连接，但V2ray这几天断了

**Comment by Alvin9999** [comment]
哪个账号？免费v2ray账号还是集合版里面的账号？

**Comment by AlonsoZeng** [comment]
> 哪个账号？免费v2ray账号还是集合版里面的账号？

Chrome90_64bit_AllNew_2021.4.17

**Comment by Alvin9999** [comment]
可以用最新版了
