### ISSUE TITLE
一个关于更新的问题.

### ISSUE THREAD

**Issue by shicong0013** [Alvin9999/new-pac#138]
之前好像在  SSR软件下载及更新地址   下面有推荐过一个购买别人建好的ssr的网站，现在好像没有，能否再告知下，谢谢

**Comment by Alvin9999** [comment]
现在不推荐付费ssr网站了，因为不确定是否长期靠谱，所以如果你有这方面的需求，可以自己网上搜索。我是建议自己学习搭建ssr，增加一项技能。

**Comment by shicong0013** [comment]
主要是那个付费网站上有一些别的分享，最近突然想看看，但是之前没保存现在找不到了，所以想问下你 @Alvin9999

**Comment by Alvin9999** [comment]
噢，明白了。时间过去很久了，我已经记不清具体是哪个网站，你还记得网站名字或者与之相关的信息吗？

**Comment by shicong0013** [comment]
不记得了...唯一的印象就是页面背景都是些挺好看的照片

**Comment by Alvin9999** [comment]
这就有点尴尬了。。。

**Comment by shicong0013** [comment]
尴尬了....可惜了那个网站做的还挺好看的，既然找不到就算了，谢谢了
