### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by LZlzLzzlzl** [Alvin9999/new-pac#1380]
下载那个谷歌浏览器高内核版后再随便用里面的一个客户端程序，就只能用那个程序自动打开的谷歌浏览器翻墙吗，其他浏览器都不行对吗

**Comment by AnyWAT** [comment]
参考：https://github.com/Alvin9999/new-pac/issues/1358

**Comment by LZlzLzzlzl** [comment]
谢谢，所以要自己动手对吧
