### ISSUE TITLE
使用了这VPN是否会对登录某些网站有限制？

### ISSUE THREAD

**Issue by Toffei-Z** [Alvin9999/new-pac#1381]

**Comment by Alvin9999** [comment]
屏蔽了色情网站，其它没有限制。

**Comment by Toffei-Z** [comment]
> 屏蔽了色情网站，其它没有限制。

哎，干得好。
那还是自己搭个梯子。

**Comment by Toffei-Z** [comment]
> 屏蔽了色情网站，其它没有限制。

另外有没有可能用EDGE上网？

**Comment by AnyWAT** [comment]
参考：https://github.com/Alvin9999/new-pac/issues/1358
