### ISSUE TITLE
一键搭建连不上

### ISSUE THREAD

**Issue by ljsdlfjk** [Alvin9999/new-pac#1382]
一键搭建提示成功 在pc上用客户端连不上

![1679318261468](https://user-images.githubusercontent.com/26861505/226353185-4bde66a6-bcb6-4143-8a1e-99d8e9fbacc4.png)

**Comment by ljsdlfjk** [comment]
请问这个工具怎么看有没正常连上服务器？

**Comment by Alvin9999** [comment]
换个websocket协议。
