### ISSUE TITLE
new bing 会被强制跳转回来.请问这个有解决办法吗

### ISSUE THREAD

**Issue by GUNDAM-OO** [Alvin9999/new-pac#1387]
new bing 会被强制跳转回来.请问这个有解决办法吗  @Alvin9999

**Comment by Alvin9999** [comment]
什么意思？

**Comment by GUNDAM-OO** [comment]
> 什么意思？

使用clash上网,谷歌等正常访问,但是访问[https://www.bing.com/new]这个地址的时候会,跳转回[https://cn.bing.com/]
