### ISSUE TITLE
下载后，提示文件存在危险，因此Chrome已将其拦截

### ISSUE THREAD

**Issue by mingoodgood** [Alvin9999/new-pac#1390]
使用Chrome下载无论是高内核还是低内核版，下载后都提示文件存在危险，因此Chrome已将其拦截。请问是怎么回事？

**Comment by mingoodgood** [comment]
我刚刚换了一个高版本的Chrome浏览器下载，就没有这个危险提示了。

**Comment by Alvin9999** [comment]
好的，软件本身没有问题。
