### ISSUE TITLE
ssr 和v2ray 失效

### ISSUE THREAD

**Issue by newyorkthink** [Alvin9999/new-pac#1395]

**Comment by Alvin9999** [comment]
免费ssr账号和v2ray账号？还是翻墙浏览器？

**Comment by newyorkthink** [comment]
> 免费ssr账号和v2ray账号？还是翻墙浏览器？

免费的ssr账号 和 v2ray
特别是ssr账号

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/229333457-426640a3-3da0-442a-bc34-3b878d0bf3e5.png)
这是 ssr 免费账号，一直无法连接

**Comment by Alvin9999** [comment]
账号没有问题哦

**Comment by Alvin9999** [comment]
浏览器代理设置HTTP

**Comment by newyorkthink** [comment]
卧槽，我看了下，我端口设置错了，gg。
现在没事了
