### ISSUE TITLE
召唤大法1

### ISSUE THREAD

**Issue by Gdname** [Alvin9999/new-pac#14]
@Alvin9999  PAC版本的是不是不能用了。。

![1](https://cloud.githubusercontent.com/assets/22128065/19569317/e59a5484-9727-11e6-8e0f-f11570b5dbe2.PNG)

**Comment by Gdname** [comment]
切换了多个都不行了= =看来要启动备用了

**Comment by Alvin9999** [comment]
第一，你的PAC版有点老了，已经更新了PAC版，可以下载新的PAC版。
第二，启动备用是很明智的选择。
