### ISSUE TITLE
有没有单独的goproxy下载

### ISSUE THREAD

**Issue by zdf0145** [Alvin9999/new-pac#140]
这个和社长那个差别大吗？

**Comment by Alvin9999** [comment]
这个版本比较低，从某个版本开始社长取消了对goagent appid的支持，要用新的服务端来部署，所以从那个时候我就没有再继续下载新的goproxy了。

但我觉得现在的版本够用了。这是项目删掉前的最后一班[r1623](https://github.com/goproxy0/goproxy/releases)
