### ISSUE TITLE
请问如何保留上个版本浏览器的设置

### ISSUE THREAD

**Issue by EllenShi** [Alvin9999/new-pac#1406]
我想保留上个版本浏览器的设置（比如启动页、浏览器设置等等），请问应该如何操作呢？

**Comment by CoderHaay** [comment]
把data文件copy到新的版本里面，覆盖就行了

**Comment by EllenShi** [comment]
> 把data文件copy到新的版本里面，覆盖就行了

好的，非常感谢！
