### ISSUE TITLE
VPS 一直在 重启中...

### ISSUE THREAD

**Issue by tomiaa12** [Alvin9999/new-pac#1408]
![image](https://user-images.githubusercontent.com/34568691/232957463-7bf2560a-79f9-495c-9d65-677b0241aaf2.png)
等了很久一直是这样,
tcp.sh也是显示启动失败
![image](https://user-images.githubusercontent.com/34568691/232957545-a34056db-3cc6-4a29-b276-c4b67a5028dd.png)

**Comment by Alvin9999** [comment]
建议部署bbr plus
