### ISSUE TITLE
今天免费的翻墙软件全挂了

### ISSUE THREAD

**Issue by cndkc** [Alvin9999/new-pac#141]
无界、赛风、自由门。封锁厉害啊。

**Comment by cndkc** [comment]
刚才试了下无界，又可以了。最近抽风厉害，两边的技术人员斗智斗勇啊。

**Comment by decemer** [comment]
不知道哪里有网络知识教程
，现在感觉这个很重要啊

**Comment by decemer** [comment]
不知道哪里有网络知识教程
，现在感觉这个很重要啊

**Comment by Alvin9999** [comment]
@cndkc  最近封锁是很厉害，能翻出去就很不错了。我看你喜欢用小巧的软件，但也推荐你使用其它的，比如GoProxy Quic版、SSR版等。

**Comment by Alvin9999** [comment]
@decemer 可以看这个[自建SSR服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) 适合初学者

**Comment by Alvin9999** [comment]
@decemer  [v2ray用户手册](https://www.v2ray.com/) 另外一种翻墙方式，但不是很容易上手，也可以看一下

**Comment by cndkc** [comment]
@Alvin9999 谢谢大大，正在换用其他软件中。

**Comment by Myoko** [comment]
付费的SSR并没有挂

**Comment by wuhualu185086661** [comment]
真的吗?我花钱在91vpn上买的帐号今天挂了,悲剧.  @Myoko

**Comment by wuhualu185086661** [comment]
@Myoko 真的吗?我花钱在91vpn上买的帐号今天挂了,悲剧.

**Comment by Alvin9999** [comment]
@wuhualu185086661  vpn和ssr是不同的软件，采用的加密方式是不一样的

**Comment by wuhualu185086661** [comment]
@Alvin9999 我按照这个链接的方法自建ss服务器的教程部署了一遍，两个方法都试过了，还是不行，请问是不是哪个端口没有开启？完全按照步骤来的。

**Comment by Alvin9999** [comment]
@wuhualu185086661  是不是部署的ssr协议，然后用的ssr客户端？浏览器代理是否设置了127.0.0.1和1080端口？

**Comment by Myoko** [comment]
@wuhualu185086661 如果你买的是宣传厉害的！你懂的 有时候难免的，我用的是没宣传的就我们几个熟人知道！而且屏蔽了百度 百度根本搜索不到任何记录 所以更安全一些。

**Comment by wuhualu185086661** [comment]
@Myoko 宣传厉害的？也就是不能选那个教程上说的美国硅谷（Silicon Valley）、美国达拉斯(Dallas)这种热门吗？服务器位置要选哪里比较好呢？

**Comment by wuhualu185086661** [comment]
@Alvin9999 我从三年前开始翻墙，这些基本设置还是比较熟了，加上检查了好几遍，也重启了好几次，还是不行。要不我把我买的服务器帐号密码给你，你试试？如果能弄好，免费借你用一个月，如何？

**Comment by Alvin9999** [comment]
@wuhualu185086661  原来你有经验噢，我以为你是新手，所以才那样问你。我的免费ssr账号有3个，你试试能不能用，如果能用，说明你那里的地区可以用ssr协议。推测是你的账号问题，但是我也不知道你的账号是什么问题，所以给你的建议是：删掉服务器，重新换个地区的服务器来部署。

**Comment by wuhualu185086661** [comment]
@Alvin9999 能否加个QQ详细聊呢？2190105685

**Comment by Alvin9999** [comment]
@wuhualu185086661  我不加qq，希望理解。为了你的隐私，我把你的qq回复也删了。

**Comment by wuhualu185086661** [comment]
@Alvin9999 换了个服务器，后来就就解决了。谢谢了啊，不过有个小问题是你的linux软件好像出bug了，老是说无法绑定1080端口，windows软件是好的，可以用。如果我用shadows官方的linux软件会不会好点？

**Comment by Myoko** [comment]
@wuhualu185086661  就是大家都知道的！知道的人越多的越容易挂！在特殊时期
