### ISSUE TITLE
自建ssr服务器, windows可连, ios失败

### ISSUE THREAD

**Issue by lyzsk** [Alvin9999/new-pac#1411]
服务器配置成了, windows环境用了三天没问题, 但是ios环境一直连不上, 端口用的非常规的33333, 理论上不冲突?

配置如下:

```
default port: 33333
default cipher: aes-256-cfb
default protocol: auth_shal_v4
default obfs: plain
```

ios手机端用的ShadowRocket APP, 配置和windows端用的一样的, 

新增配置:

```
TCP Fast Open -> Off
UDP Relay -> On
```

想请教下原因或者其他解决方案?

**Comment by lyzsk** [comment]
截图如下: windows环境下测试可连, 无丢包, ios环境timeout

![ios_1](https://user-images.githubusercontent.com/88008847/233530830-713fe3ad-813c-4b08-86ec-b00de35bd3c2.jpg)
![ios_2](https://user-images.githubusercontent.com/88008847/233530839-195a125d-bb5a-45fc-81ca-39efa551179e.jpg)
![windows_1](https://user-images.githubusercontent.com/88008847/233530845-6a9a50c7-7cd7-4825-bd5c-701961aea6a7.jpg)

**Comment by Alvin9999** [comment]
iOS没有看到可以填写协议auth_shal_v4的地方？

**Comment by Alvin9999** [comment]
如果你服务器设置了这个参数，但客户端没有填是用不了的。

**Comment by lyzsk** [comment]
> 如果你服务器设置了这个参数，但客户端没有填是用不了的。

IOS OBF那一行点进去就能看到 auth_shal_v4(protocol) plain(obf), 配置是和服务端一致的

**Comment by lyzsk** [comment]
> 如果你服务器设置了这个参数，但客户端没有填是用不了的。

总之就是windows端能连, ios端配置一致不能连, 端口也是一致的, 打开的:

```
root@vultr:~# netstat -ntulp | grep 33333
tcp6       0      0 :::33333                :::*                    LISTEN      55930/python        
udp6       0      0 :::33333                :::*                                55930/python
```

**Comment by lyzsk** [comment]
> 如果你服务器设置了这个参数，但客户端没有填是用不了的。

然后windows cmd 查端口也是打开的:

```
telnet ip 33333
```

然后跳转空白页(证明端口打开), 真的不知道什么原理会导致一个os能用一个os不能用....大佬求教

**Comment by Alvin9999** [comment]
是很奇怪，是同一个网络吗

**Comment by lyzsk** [comment]
> 是很奇怪，是同一个网络吗

是的，同一个路由器转发的wifi, ios端移动5g也试过了

**Comment by Alvin9999** [comment]
你在服务器里面把账号的混淆设置成tls1.2_ticket_auth，然后客户端改成这个后，再试试看

**Comment by lyzsk** [comment]
> 你在服务器里面把账号的混淆设置成tls1.2_ticket_auth，然后客户端改成这个后，再试试看

我试过前面issue提到的：

1、加密方式：none 协议：origin 混淆：tls1.2_ticket_auth

2、加密方式：none 协议：auth_chain_a 混淆：tls1.2_ticket_auth

都没成功……

**Comment by Alvin9999** [comment]
试一下我分享的免费ssr账号

**Comment by lyzsk** [comment]
> 试一下我分享的免费ssr账号

我自己又尝试了下解决了，先kill掉可以ping通的进程监听端口的pid，然后重新配置脚本在原端口，wifi下速度正常，不过移动5G网络时快时慢，有的时候图都加载不出来

**Comment by Alvin9999** [comment]
OK
