### ISSUE TITLE
 Unable to locally verify the issuer's authority.

### ISSUE THREAD

**Issue by zjsuperman1987** [Alvin9999/new-pac#1413]

**Comment by Alvin9999** [comment]
什么意思？遇到了什么问题？

**Comment by zjsuperman1987** [comment]
最近登录不了&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
什么意思？遇到了什么问题？

**Comment by zjsuperman1987** [comment]
报本地认证 错误 老大 着两周才开始的， 咋整？&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
什么意思？遇到了什么问题？

**Comment by Alvin9999** [comment]
说清楚一点。用的什么软件？什么账号？

**Comment by zjsuperman1987** [comment]
所有的都报这个错误。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月22日(星期六) 晚上11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac]  Unable to locally verify the issuer's authority. (Issue #1413)





 
说清楚一点。用的什么软件？什么账号？

**Comment by zjsuperman1987** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月22日(星期六) 晚上11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac]  Unable to locally verify the issuer's authority. (Issue #1413)





 
说清楚一点。用的什么软件？什么账号？

**Comment by Alvin9999** [comment]
说清楚一点。用的什么软件？

**Comment by Alvin9999** [comment]
截图看一下

**Comment by zjsuperman1987** [comment]
你是指截那个图， 我已经给你截图2张发过来了。 现在问题就是上不了了， 然后呢，以前遇到这中情况 ip_1.bat 更新一下就能上， 现在更新 就报 认证错误。 gitlab 。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
截图看一下

**Comment by zjsuperman1987** [comment]
我一直用的ShadowsocksR.exe 这个。 其他的最近试了试也报同样的错误






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac]  Unable to locally verify the issuer's authority. (Issue #1413)





 
截图看一下

**Comment by Alvin9999** [comment]
图片没有收到。请用最新版。最近封锁加重，尤其是SSR、SS被封的厉害。
北京时间2023年4月18日-21日：最近封锁加重，部分工具被封的厉害，可以优先选择clash、Xray、hysteria、singbox、naiveproxy工具。会持续更新。

**Comment by zjsuperman1987** [comment]
clash 这个怎么使用啊？&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
图片没有收到。请用最新版。最近封锁加重，尤其是SSR、SS被封的厉害。
 北京时间2023年4月18日-21日：最近封锁加重，部分工具被封的厉害，可以优先选择clash、Xray、hysteria、singbox、naiveproxy工具。会持续更新。

**Comment by zjsuperman1987** [comment]
点击.exe就可以了吗？ 然后打开浏览器就行了嘛？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
图片没有收到。请用最新版。最近封锁加重，尤其是SSR、SS被封的厉害。
 北京时间2023年4月18日-21日：最近封锁加重，部分工具被封的厉害，可以优先选择clash、Xray、hysteria、singbox、naiveproxy工具。会持续更新。

**Comment by zjsuperman1987** [comment]
你说的clash我试了都不行呢，是使用方法有问题吗？&nbsp;
可以优先选择clash、Xray、hysteria、singbox、naiveproxy工具。会持续更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac]  Unable to locally verify the issuer's authority. (Issue #1413)





 
图片没有收到。请用最新版。最近封锁加重，尤其是SSR、SS被封的厉害。
 北京时间2023年4月18日-21日：最近封锁加重，部分工具被封的厉害，可以优先选择clash、Xray、hysteria、singbox、naiveproxy工具。会持续更新。

**Comment by Alvin9999** [comment]
用最新版。

**Comment by zjsuperman1987** [comment]
4月9日更新版本的， 我看已经是最新版本了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac]  Unable to locally verify the issuer's authority. (Issue #1413)





 
Closed #1413 as completed.

**Comment by Alvin9999** [comment]
4月24日

**Comment by zjsuperman1987** [comment]
OK 一会我试一下， 谢了， 辛苦了 大早上的， 打扰你了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
4月24日

**Comment by Alvin9999** [comment]
看不到你发的图片，你用电脑登录gihtub，然后发图片

**Comment by zjsuperman1987** [comment]
好的， 谢谢， 这会可以上了， 太感谢你了， 真的很棒！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 晚上11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Alvin9999/new-pac]  Unable to locally verify the issuer&#39;s authority. (Issue #1413)





 
看不到你发的图片，你用电脑登录gihtub，然后发图片
