### ISSUE TITLE
爬墙的梯子都倒了

### ISSUE THREAD

**Issue by ck8918** [Alvin9999/new-pac#142]

**Comment by Alvin9999** [comment]
如果你使用的GoAgent版、GoProxy版，请按照使用说明运行ip更新文件来同步到最新的云端配置。

如果更新ip后还是无法使用，建议换用GoProxy Quic版或SSR版，这两款抗封锁很强。在使用这两款时，和上面两款一样，需要运行ip更新文件来更新ip。

ps：近期我会经常在云端更新ip，以帮助大家应对这种困难时期。

**Comment by Alvin9999** [comment]
软件下载地址：https://github.com/Alvin9999/new-pac/wiki

**Comment by cndkc** [comment]
@Alvin9999 谢谢大大，辛苦了。
