### ISSUE TITLE
目前GoProxy Quci可以用但是google上不去

### ISSUE THREAD

**Issue by qcj912** [Alvin9999/new-pac#143]
只是google上不去，推特和YouTube之类的都可以。
使用说明里也没有解决方法，所以要怎么做呢？

**Comment by Alvin9999** [comment]
你好，这个测试时，google可以访问。那么有可能是兼容性或地区性的问题。你可以尝试按照使用说明运行ip更新文件来尝试着解决。如果还不能解决，且自己很喜欢上google，很急，那么请使用[谷歌镜像](https://github.com/Alvin9999/new-pac/wiki/%E8%B0%B7%E6%AD%8C%E9%95%9C%E5%83%8F) 来访问谷歌搜索和谷歌学术。

**Comment by caofengzi** [comment]
部分地區tls lls加密協議基本上是不能用了，今天用這個測試了一下good ip才1個，gfw這次升級差不多所有代理程序不同程度都受到了干擾。

**Comment by decemer** [comment]
@caofengzi 说明他技术能穿透 破译了吗

**Comment by Alvin9999** [comment]
目前tls仍可用，只是有干扰，所以解决方法是放入更多的ip，以量来弥补。放入的ip至少曾出现过连接成功，出现连接成功的概率越大越好。
