### ISSUE TITLE
刚购买的vsp服务器 一直登录不上

### ISSUE THREAD

**Issue by weekendyy** [Alvin9999/new-pac#1432]
新建很多服务器了 ，还是登录不上去，发现第一次添加防火墙的规则然22端口同行之后，第一次可以登录  断开一次之后就都不行了，我怎么回事，求解答

**Comment by weekendyy** [comment]
连接都是报这个错误  kex_exchange_identification: read: Connection reset by peer
Connection reset by 149.28.199.160 port 22

**Comment by Alvin9999** [comment]
现在好了没
