### ISSUE TITLE
还没用，服务器ip被封了的原因？

### ISSUE THREAD

**Issue by nanyang24** [Alvin9999/new-pac#144]
在使用了[自建ss服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)中服务器安装ssr的方法，瞬间服务器的ip被封了，是什么原因。。。？

**Comment by Alvin9999** [comment]
是还没搭建就被封了吗?还是在搭建的过程中呢？

**Comment by nanyang24** [comment]
@Alvin9999 准确的 时间点 应该是服务端搭建完成后，在客户端ShadowsocksX-NG-R8上配置好账号之后，发现连接不上ip了，求解答。。

**Comment by Alvin9999** [comment]
你这种情况很特别，还没开始用就不行了。我之前分享的免费的ssr账号之一是被用了一段时间才被封ip的。你的问题的具体原因我也不知道，推测是GFW在封其它ip的时候顺便把你的ip也一起封了，也就是它可能封的是ip段，刚好你的ip在ip段上，这是我的推测。

解决方法是:删掉服务器，重新换个地区的服务器来部署。vultr是折算成小时来计算的，所以金钱上几乎不会有损失，就是自己要辛苦一点。在目前这段翻墙艰难时期，只好这样了。

**Comment by Alvin9999** [comment]
顺便问问，你用的哪个地区的服务器呢？

**Comment by nanyang24** [comment]
@Alvin9999 
嗯嗯，我用的是digitalocean的旧金山节点。
我测试下我的ip号+-1之后都可以ping痛，估计是精确定位封我的ip了。。
就是在好奇为什么还没开始用就封了呢，前几天用ss是一段时间后才被封ip，才转来ssr的，难道是我的加密方式有问题吗，这次用的是chacha20

**Comment by Alvin9999** [comment]
噢！有可能，用aes-256-cfb试试看

**Comment by Alvin9999** [comment]
协议：auth_sha1_v4  混淆：tls1.2_ticket_auth

**Comment by nanyang24** [comment]
@Alvin9999 
行，那我换个服务器试一下，协议和混淆就是这样设置的
还以为chacha20比aes-256-cfb优秀呢 😄

**Comment by nanyang24** [comment]
@Alvin9999 
成功了！采用aes-256-cfb。
虽然不知道能坚持多久……😆
另外想请问ssr在最近严打期间可以顶住吗？?

**Comment by Alvin9999** [comment]
没问题的，我搭建了多个，只是偶尔有个别的用不了，换一下ip就又能用了

**Comment by pygmalion666** [comment]
666

**Comment by pnp200** [comment]
@nanyang24,
车祸现场，同样的教程，当天晚上部署好搭上梯子，第二天就被封ip。
[关于 0124 毫无根据且不负责任的猜想](https://toutyrater.github.io/#2018-01-28)

**Comment by Alvin9999** [comment]
@pnp200  混淆不要设置TLS看看，我的教程推荐也是不要选TLS。
