### ISSUE TITLE
安卓vpn一个都连不上

### ISSUE THREAD

**Issue by snningcn** [Alvin9999/new-pac#1441]
老大，我在广东的，你发的那些手机安卓的，我一个都连不上，还有什么好介绍的吗

**Comment by snningcn** [comment]
老大我说错了，是订阅地址不行，有没有好点的地址介绍

**Comment by Alvin9999** [comment]
可以用[ssr、ss](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)账号。
