### ISSUE TITLE
无法翻墙

### ISSUE THREAD

**Issue by weixia1** [Alvin9999/new-pac#1446]
你好，按照教程->，https://shadowsockshelp.github.io/Shadowsocks/linux.html 
"获取 Shadowsocks 账号信息" 买了一个账号，
通过“Clash for Windows” 方式登录账号，但最后还是无法fanqiang。
![QQ截图20230525142919](https://github.com/Alvin9999/new-pac/assets/10680088/f1f90821-a7a9-46d2-b679-f0bc72937806)

帮忙看下什么原因。

我的需求是，C++编译某些程序，需要连外网下载，然后需要搭建一个梯子翻墙，谢谢。

**Comment by Alvin9999** [comment]
你好，如果你是买的账号，请找客服。

**Comment by Alvin9999** [comment]
如果你想搭建账号，主页有搭建教程，比如可以搭建ssr、ss、v2ray等账号。

**Comment by Alvin9999** [comment]
[自建SS/SSR服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2022年9月29日更新）

[自建hysteria服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAhysteria%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2022年9月29日发布）

[自建v2ray服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2023年5月4日更新）

[自建brook服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2023年3月23日更新）

[自建trojan服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAtrojan%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2022年9月29日更新）

[自建WireGuard VPN服务器服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAWireGuard-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2023年5月14日更新安装脚本和安卓版下载地址）

**Comment by Alvin9999** [comment]
付费账号的话，推荐这个https://github.com/Alvin9999/new-pac/wiki/V2free%E6%9C%BA%E5%9C%BA
