### ISSUE TITLE
蓝灯失效了吗？

### ISSUE THREAD

**Issue by Jason4774** [Alvin9999/new-pac#145]
蓝灯失效了吗？

**Comment by Alvin9999** [comment]
失效了。官网说正在修复。

**Comment by Jason4774** [comment]
@Alvin9999你之前用的蓝灯应该是ilanyu的lantern999可能由于版本更新导致之前版本里面的所有服务器失效了，请问你有社长最新的goproxyr1624吗？谢谢

**Comment by Jason4774** [comment]
:smile:

**Comment by Alvin9999** [comment]
是的。999一去不复返了。
[r1623](https://github.com/goproxy0/goproxy/releases)
