### ISSUE TITLE
443端口开不了

### ISSUE THREAD

**Issue by newyorkthink** [Alvin9999/new-pac#1453]

**Comment by newyorkthink** [comment]
![image](https://github.com/Alvin9999/new-pac/assets/87791643/b1c23134-329d-4f5a-971f-ba09c4472d50)

**Comment by newyorkthink** [comment]
教程不完整

**Comment by Alvin9999** [comment]
哪个教程？

**Comment by Alvin9999** [comment]
你的服务器系统是什么? 用的哪个教程的哪个脚本？

**Comment by newyorkthink** [comment]
就是那个v2ray 8和一脚本，os是debian

**Comment by Alvin9999** [comment]
用过，没什么问题。要不你用CentOS7系统试试看
