### ISSUE TITLE
v2ray安卓版在google play上下载不了

### ISSUE THREAD

**Issue by Bluezzznb** [Alvin9999/new-pac#1458]
请问一下，安卓版v2ray在google play上下载东西一直显示正在连接wlan，重启应用，重启手机，重连wifi都没用这是为啥呀

**Comment by Alvin9999** [comment]
v2ray账号是否有效？

**Comment by Bluezzznb** [comment]
> v2ray账号是否有效？

有效，可以正常访问网页等，但就是google play里下载不了应用，很奇怪

**Comment by Alvin9999** [comment]
确实奇怪。
