### ISSUE TITLE
SSR翻墙Ubuntu可以连上，但是无法使用1080端口做代理

### ISSUE THREAD

**Issue by wuhualu185086661** [Alvin9999/new-pac#146]
一步一步按照SSR翻墙方法，买了服务器，装好SSR以后，发现ubuntu16.04链接上以后，设置127.0.0.1:1080仍然无法翻墙。具体描述如下：
看log估计已经连上了，但是把chrome设置127.0.0.1:1080后，仍然无法翻墙，是不是还有哪里要设置一下？
ssr config命令后，控制台打印：
___________________________________________________________________________________
IPv6 support
stopped
IPv6 support
2017-10-12 15:51:51 INFO util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
当前 IP：45.76.172.148 来自：美国 Vultr
___________________________________________________________________________________
看样子连上了，但是设置代理后，仍然无法访问google。
PS:同样的SSR客户端配置，在windws可以，在ubuntu16.04失败了，因为我用的双系统。
使用netstat -apn | grep 1080 命令查看端口1080的使用情况，控制台打印：
___________________________________________________________________________________
tcp 0 0 127.0.0.1:1080 0.0.0.0:* LISTEN 6397/python
udp 0 0 127.0.0.1:1080 0.0.0.0:* 6397/python
___________________________________________________________________________________
说明1080端口被监听了。

**Comment by Alvin9999** [comment]
linux我是转载的别人的方法，如果不好用，你可以换其[linux的ssr客户端](https://github.com/erguotou520/electron-ssr/releases)  期待你的反馈，如果后者好用，那我把前面那个方法撤销。

**Comment by Alvin9999** [comment]
我对linux确实不熟悉，不好意思哈

**Comment by stormwrath** [comment]
@wuhualu185086661 楼主你的问题解决了吗?我也遇到了和你一样的情况，windows可以上但Ubuntu16.04却始终连不上
