### ISSUE TITLE
大佬，用AWS免费服务器搭建V2Ray，一开始10M/S，现在0.1M/S,如何优化呀

### ISSUE THREAD

**Issue by DrugHua** [Alvin9999/new-pac#1461]
我现在传输协议就是ws，没有买域名，有用BBRPLUS内核加速
现在网速慢的谷歌都难打开，应该如何优化呀

**Comment by Alvin9999** [comment]
可能是免费的资源用的人多，高峰期平均分摊到每个人的带宽比较小的缘故。如果是这个原因，没办法解决。
