### ISSUE TITLE
能够提供普通的谷歌的镜像

### ISSUE THREAD

**Issue by ted-dev-42** [Alvin9999/new-pac#1463]
首先感谢作者的无私奉献。 目前谷歌镜像分类下只有一个谷歌学术，能否提供一些普通的谷歌的镜像，万分感谢。

**Comment by Alvin9999** [comment]
试试这个
https://free9.freeku6.xyz/62

**Comment by ted-dev-42** [comment]
> 

昨天还可以，今天就 502 Bad Gateway

**Comment by ted-dev-42** [comment]
> 试试这个 https://gg.freeku11.xyz/62

昨天还可以，今天就 502 Bad Gateway

**Comment by bannedbook** [comment]
现在谁还用这个
翻墙不香吗，想看啥看啥

**Comment by ted-dev-42** [comment]
> 现在谁还用这个 翻墙不香吗，想看啥看啥

公司电脑上有监控，用不了翻墙软件

**Comment by ted-dev-42** [comment]
> > 试试这个 https://gg.freeku11.xyz/62
> 
> 昨天还可以，今天就 502 Bad Gateway

刚试了下，又可以了

**Comment by bannedbook** [comment]
绕过监控就好了吧，这么多翻墙软件，它还能都给监控住

**Comment by Alvin9999** [comment]
遇到“502 Bad Gateway”这种情况，刷新一下网页
