### ISSUE TITLE
换了N个协议，现在用着VLESS GRPC，虽然会断，但是没断的的那么快

### ISSUE THREAD

**Issue by YASIN0905** [Alvin9999/new-pac#1465]
换了N个协议，现在用着VLESS GRPC，虽然会断，但是没断的的那么快

_Originally posted by @chen510260x in https://github.com/Alvin9999/new-pac/issues/1404#issuecomment-1509731558_

**Comment by Alvin9999** [comment]
试试最新的reality协议
