### ISSUE TITLE
您好 感谢您的分享！请问有自建Clash服务器的相关教程吗

### ISSUE THREAD

**Issue by Enignna** [Alvin9999/new-pac#1467]

**Comment by Alvin9999** [comment]
clash只是一款工具，可以用ssr、v2ray、ss等账号。搭建好账号后，你需要把账号导入到clash客户端中。搭建教程主页里面有，至于clash工具如何使用，可以网上搜索一下。

**Comment by Enignna** [comment]
好的 谢谢您啦
