### ISSUE TITLE
可以不可以快点更新呀

### ISSUE THREAD

**Issue by bibinbing** [Alvin9999/new-pac#1468]

**Comment by Alvin9999** [comment]
更新什么呢？

**Comment by bibinbing** [comment]
谷歌内核更新上次是6月8号，现在都差不多一个月了，啥时候更新呀，老哥。

**Comment by Alvin9999** [comment]
现在就是最新的版本哦，有能更新的时候再更新。目前所有的工具都是正常的。

**Comment by bibinbing** [comment]
对了，CloundFearID是什么呀？还有就是这些IP有些很卡，一般哪个工具比较稳定点呢？

**Comment by Alvin9999** [comment]
不同的地区，不同的宽带运营商，网络封锁可能不一样，哪款工具好不好用需要自己来测试。
