### ISSUE TITLE
链接不上服务器

### ISSUE THREAD

**Issue by tl123987** [Alvin9999/new-pac#1469]
![image](https://github.com/Alvin9999/new-pac/assets/65206700/300529b1-f8e4-4830-9c41-de254a71d190)

可是单独打开却可以连接上

**Comment by daxiaoma** [comment]
me to

**Comment by Alvin9999** [comment]
用的哪款版本？

**Comment by tl123987** [comment]
最多工具的，SSR无界109，突然不行了

**Comment by Alvin9999** [comment]
暂时用其它工具，修复需要时间。

**Comment by Alvin9999** [comment]
已修复。

**Comment by tl123987** [comment]
thanks
