### ISSUE TITLE
GoProxy Quci无法下载youtube视频，说未发现文件。

### ISSUE THREAD

**Issue by LeeChen2000** [Alvin9999/new-pac#147]

**Comment by Alvin9999** [comment]
谷歌浏览器的GoProxy Quic版下载的视频大小超过32M就会出现上述问题，目前没法解决。但是火狐浏览器的GoProxy Quic版下载YouTube视频就没有此问题，你可以用火狐浏览器的GoProxy Quic版来下载。

**Comment by LeeChen2000** [comment]
好的，谢谢。
