### ISSUE TITLE
大佬们我的ssr账号在win上能用，在os x上500是啥问题？

### ISSUE THREAD

**Issue by MadZXR** [Alvin9999/new-pac#148]
在我的mac上用的shadowsocks-ng-r8
弹
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file connection-timeout or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).

**Comment by Alvin9999** [comment]
在win系统上能用，说明ssr账号没问题。
你好好查看mac上的配置，比如账号信息，浏览器代理设置等。客户端一定要用ssr客户端。

**Comment by MadZXR** [comment]
是前天突然开始弹500的，之前用着都正常，开的全局，ssr账号是扫码的，telegram也不能用了……平时带出门的都是mac，现在好烦躁•﹏•

**Comment by Alvin9999** [comment]
改下ssr端口、密码、协议、混淆再试试看。

**Comment by MadZXR** [comment]
好的，我试试
