### ISSUE TITLE
所有国内网站都上不去

### ISSUE THREAD

**Issue by dove12412** [Alvin9999/new-pac#1483]
无论使用什么方法，重新代理，改DNS，修复工具。
用的是高内核集合版， 不开代理的情况下所有国内网站都不能上，提示建立安全连接失败，而且代理更新提示获取ip失败，但是挂入代理以后可以正常使用，可以正常玩游戏，qq可以聊天但不能发图片，微信无法使用内置浏览器，怀疑是DNS被篡改，但用了能查到的所有修复方法均无效

**Comment by Alvin9999** [comment]
高内核版是便携版，不会对电脑有什么设置。
你看下ie浏览器的代理设置，有的话，关闭它。
具体操作：
https://jingyan.baidu.com/article/647f0115e555bf7f2148a8be.html
