### ISSUE TITLE
ProxySU 搭建的VLESS 和 VMess 443  客户端是  v2rayN

### ISSUE THREAD

**Issue by canislupuslee** [Alvin9999/new-pac#1486]
提示是
2023/08/02 11:38:55 [Warning] [595996027] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/7G3R8R):  > read tcp 192.168.0.104:63188->xxxx:443: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/7G3R8R):  > read tcp 192.168.0.104:63189->xxxx:443: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/7G3R8R):  > read tcp 192.168.0.104:63190->xxxx:443: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/7G3R8R):  > read tcp 192.168.0.104:63191->xxxx:443: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/7G3R8R):  > read tcp 192.168.0.104:64003->xxxx:443: wsarecv: An existing connection was forcibly closed by the remote host.] > common/retry: all retry attempts failed

**Comment by canislupuslee** [comment]
https://tcp.ping.pe/ip:443 正常 服务器是腾讯云的 硅谷服务器 系统是 Debian 11.1  求帮助 大佬

**Comment by Alvin9999** [comment]
用最新的ProxySU版试试
