### ISSUE TITLE
RSS如何订阅被墙的网站

### ISSUE THREAD

**Issue by DrTourist** [Alvin9999/new-pac#1487]
根据网上的一些教程在qb里设置了代理链接：

![QQ截图20230806100344](https://github.com/Alvin9999/new-pac/assets/93828299/b38f21d3-272b-4f1f-aca0-eadc0d3d68c4)

但仍然无法更新rss订阅。

**Comment by Alvin9999** [comment]
不了解这个软件。代理服务器类型HTTP换成SOCKS5，试试
