### ISSUE TITLE
不支持xp

### ISSUE THREAD

**Issue by jdfq** [Alvin9999/new-pac#149]
低内核版的ssr账号更新程序“IP”也不支持xp

**Comment by Alvin9999** [comment]
两个ip更新文件都用不了吗？提示什么，截图看一下。

**Comment by jdfq** [comment]
好像说certutil既不是命令也不是什么。可能还有中文路径的兼容性问题

**Comment by Alvin9999** [comment]
测试没有问题，这种更新ip方式持续了1年多了。你把压缩包放在没有中文的路径下，然后重新解压再试试看。

**Comment by jdfq** [comment]
路径：D:\Firefox52_ss_2017.7.14.7z\ss_Update
运行结果：

--2017-10-18 11:28:40--  https://coding.net/u/Alvin9999/p/ip/git/raw/master/ssco
nfig.txt
Resolving coding.net (coding.net)... 120.132.63.152, 120.132.63.88, 123.59.94.10
1, ...
Connecting to coding.net (coding.net)|120.132.63.152|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'ssconfig.txt'

    [ <=>                                   ] 5,254       --.-K/s   in 0s

2017-10-18 11:28:40 (61.0 MB/s) - 'ssconfig.txt' saved [5254]

找不到 D:\Firefox52_ss_2017.7.14.7z\Proxy\SS\gui-config.json_backup
系统找不到指定的文件。
'certutil' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的文件。
找不到 D:\Firefox52_ss_2017.7.14.7z\ss_Update\gui-config.json

已更新SS配置文件,请按任意键退出,并重启MyFirefox.exe程序.

**Comment by Alvin9999** [comment]
请下载新版的火狐SSR版软件

**Comment by jdfq** [comment]
好吧，信你一回

**Comment by jdfq** [comment]
其他网盘都下不了。百度网盘下载的，解压报数据错误。两个ip更新文件运行都这样：

'wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'certutil' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的文件。
找不到 E:\BaiduYunDownload\Firefox52_2017.10.12\Firefox52_SSR_2017.10.12\ss_Upda
te\ssconfig.txt
找不到 E:\BaiduYunDownload\Firefox52_2017.10.12\Firefox52_SSR_2017.10.12\ss_Upda
te\gui-config.json

已更新SS配置文件,请按任意键退出,并重启MyFirefox.exe程序.

**Comment by jdfq** [comment]
不能只给代理程序吗？浏览器我已经有了。下载好难。

**Comment by jdfq** [comment]
下载这个：https://github.com/Alvin9999/new-pac/wiki/SSR%E7%89%88
运行ip文件：

--2017-10-18 17:26:32--  https://raw.githubusercontent.com/Alvin9999/pac2/master
/ssconfig.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.72.13
3
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.72.1
33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5176 (5.1K) [text/plain]
Saving to: 'ssconfig.txt'

100%[======================================>] 5,176       --.-K/s   in 0.009s

2017-10-18 17:26:33 (544 KB/s) - 'ssconfig.txt' saved [5176/5176]

'certutil' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的文件。
找不到 E:\BaiduYunDownload\Chrome53_SSR_v2017.10.12\ss_Update\gui-config.json

已更新SS配置文件,请按任意键退出,并重启MyFirefox.exe程序.

**Comment by Alvin9999** [comment]
之所以做成一键翻墙包是为了方便用户。下载出错，可以用7z解压软件来解压。压缩包的格式是7z。

你给的信息提示系统找不到gui-config.json这个文件，你根据提示的目录，去看下是否有？如果没有，那么多半是解压没有完全，或者被杀毒软件删了（如果你开了杀毒软件的话）。这个文件上传时肯定在压缩包里面。

正常更新界面如下：
![default](https://user-images.githubusercontent.com/12132898/31713671-925278f6-b431-11e7-9263-bdea66474b46.PNG)

**Comment by jdfq** [comment]
有这个文件。我就是7zip。win7下正常运行。

**Comment by jdfq** [comment]
别人说xp不支持此命令：certutil

**Comment by Alvin9999** [comment]
哦哦，谢谢反馈哈。我研究下。

**Comment by jdfq** [comment]
这里附上了我的xp更新程序，虽然不值一提：https://drive.google.com/open?id=0B_h0u1qjA5FfYmhmZC01SGRGYnM

**Comment by Alvin9999** [comment]
@jdfq 大佬你好，我计划近期更新ssr版，主要是要兼容XP系统。但是我没有xp系统，用虚拟机测试了下，发现你提供的方法更新不行，可能是我的操作方式不对。请你帮忙优化下教程和使用方法，最好能够让电脑小白看得懂，越简单越好。

**Comment by Alvin9999** [comment]
@jdfq  问题已经解决了，和你说下。
