### ISSUE TITLE
iOS上很慢

### ISSUE THREAD

**Issue by daweiq** [Alvin9999/new-pac#1498]
使用相同的VMESS服务器，在PC上使用v2rayN 链接很快；但是在iOS上使用V2box、oneClick facebook很慢，Youtube都打不开，啥原因？

**Comment by Alvin9999** [comment]
电脑和手机是否是同一个网络？

**Comment by daweiq** [comment]
是的，同一个Wifi

**Comment by daweiq** [comment]
是V2Box配置问题，修改正确的security 和 headtype配置后，可以正常工作了，谢谢！
