### ISSUE TITLE
qq能上，浏览器不能上网

### ISSUE THREAD

**Issue by Finn199587** [Alvin9999/new-pac#15]
后来把之前下的代理浏览器卸载了，就能上了。这是什么回事？用之前的谷歌代理浏览器上，可以上谷歌，但是其他的网站打不开。。。

**Comment by Alvin9999** [comment]
你用的什么版本呢？压缩包的名称是什么？我分享的浏览器不用安装，解压后打开使用呢。
浏览器不能上网的话，试试打开IE浏览器——工具——internet选项——连接——局域网设置，把为LAN使用代理的勾去掉即可
