### ISSUE TITLE
请教一下，页面打不开是怎么回事？

### ISSUE THREAD

**Issue by zzz45** [Alvin9999/new-pac#150]
"type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: NetworkIdleTimeout: No recent network activity."
}

**Comment by Alvin9999** [comment]
提示没有网络活动。如果你电脑有安装杀毒软件，请退出杀毒软件，然后重新解压，之后按照使用说明更新一下ip，再打开看看。

**Comment by zzz45** [comment]
你好，是这样的，我电脑没有装杀毒软件，前面大概有近一个小时的时间一直无法连接，期间我将压缩包重新解压依然没有效果，然后刚刚我再次刷新的时候短暂的恢复正常了，然后又失效了。是我自己的网络不稳定吗？

**Comment by Alvin9999** [comment]
你是用的GoProxy Quic版吗？

**Comment by Alvin9999** [comment]
有可能是你的网络环境不稳定，也有可能是你那里的网络环境不适合用你正在用的版本。如果你用的GoProxy Quic版，你可以换GoAgent版、GoProxy版、SSR版等其它。可以按照我给你的推荐顺序来尝试使用。

**Comment by zzz45** [comment]
是的，目前这个网站我也比较卡，要多次刷新才能成功

**Comment by zzz45** [comment]
我目前打不开下载页面，可能是我目前网络有问题，我明天再尝试看看，谢谢大佬。

**Comment by zzz45** [comment]
我昨天开始用的，今晚之前一直很流畅。

**Comment by Alvin9999** [comment]
嗯，如果下载有困难和我说。

**Comment by zzz45** [comment]
依次尝试到GoProxy版后可用，再次感谢。

**Comment by Alvin9999** [comment]
OK。SSR版建议也下载了，作为备用。

**Comment by zzz45** [comment]
好的，已下载。
