### ISSUE TITLE
windows11系统不能正常使用，其他系统正常，这是怎么回事？

### ISSUE THREAD

**Issue by qinxiamms** [Alvin9999/new-pac#1506]
windows11连接正常，服务器也有响应，Windows11自带防火墙和安全策略造成的连接问题，自带防火墙也关闭了，安全策略不会改动设置，怎么办？

**Comment by qinxiamms** [comment]
只有在windows11系统，6种工具都不能正常使用，这和Windows11的防火墙的安全策略有关，怎么破解？

**Comment by qinxiamms** [comment]
防火墙全都禁用了以后，还是不能用

**Comment by Alvin9999** [comment]
浏览器提示的什么内容？

**Comment by qinxiamms** [comment]
显示未连接，检测里面说防火墙和安全策略有限制

**Comment by Alvin9999** [comment]
你这个新系统有没有用杀毒软件、安全卫士？

**Comment by qinxiamms** [comment]
我没装任何杀毒软件，连自带的Defender的所有功能都关闭了，只是最近几次系统更新以后就不能用了，换成win10 win8 win7系统都能正常使用，甚至今年4月份的工具都能用

**Comment by Alvin9999** [comment]
那就奇怪了，翻墙工具都可以正常启动吗？
