### ISSUE TITLE
求助一下大佬，ssr最好的加密方式、协议和混淆是什么

### ISSUE THREAD

**Issue by liwenjie119** [Alvin9999/new-pac#151]
最近据说ss已经可以被检测出来，ssr还能用，想问问最好的加密方式、协议和混淆是什么。目前我用none加密，auth_chain_b协议和tls1.2_ticket_auth混淆

**Comment by Alvin9999** [comment]
没有最好之分吧，或者我不知道。我的理解是ssr比ss好，因为多了协议和混淆。
