### ISSUE TITLE
关于一键搭建的过程中，显示申请证书失败！！！

### ISSUE THREAD

**Issue by fglgit** [Alvin9999/new-pac#1513]

**Comment by fglgit** [comment]
在proxysu搭建到安装显示申请证书失败

**Comment by Alvin9999** [comment]
试试最新版。不行的话，建议用https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B 末尾的搭建脚本。
