### ISSUE TITLE
请教: Chrome61_GP_Quic_2017.9.14 版 浏览器 在切换标签页时特别卡怎么解决？

### ISSUE THREAD

**Issue by GPSGH** [Alvin9999/new-pac#152]
不仅是标签页切换卡
在打开网页时也比较卡 ，明显迟钝

**Comment by GPSGH** [comment]
问题2：浏览器可以使用，但是太卡了，，，

跟原先现在的chrome反应速度 完全比不了 有没有解决办法呢

**Comment by Alvin9999** [comment]
测试没有问题，很流畅，可能是你的电脑环境问题。建议翻墙时少开一些其它程序，这样可能会好点，或者你可以试下低内核的版本。

**Comment by GPSGH** [comment]
哦哦  好 我多试试几个
