### ISSUE TITLE
建议美国节点使用naiveproxy

### ISSUE THREAD

**Issue by gdlwolf** [Alvin9999/new-pac#1521]
经过长时间使用，发现在国内（联通）使用hysteria2和clash.meta（发现也是hy2）持续一段时间后就访问不了啦。稳定性相对于naiveproxy差不少。不知道是不是hy2被运行商限制UDP。因为需要使用美国节点，所以希望将美国节点添加naiveproxy。谢谢。

**Comment by Alvin9999** [comment]
国内不同的地区使用效果可能会有差异。naiveproxy ip2是美国节点。

**Comment by gdlxxuu** [comment]
感谢
