### ISSUE TITLE
求助Google搜索问题

### ISSUE THREAD

**Issue by lxhei1831** [Alvin9999/new-pac#1526]
求助用的是谷歌客户端，用的clash链接，不论改地区改语言都显示处于安全搜索中，会过滤信息，谷歌会直接显示处于安全搜索不显示内容

**Comment by Alvin9999** [comment]
服务器屏蔽了色情内容，浏览器无法修改。

**Comment by hzhhzh801** [comment]
> 服务器屏蔽了色情内容，浏览器无法修改。

墙外有墙
