### ISSUE TITLE
clash.meta用不了

### ISSUE THREAD

**Issue by only-jay0118** [Alvin9999/new-pac#1533]
所有东西都是从这里下的，但是只有clash.meat用不了
![A$CLZ7RC4M1J~3JGJMQVTW](https://github.com/Alvin9999/new-pac/assets/149688870/c08f27b3-a8c4-4e71-8356-475aadeee60d)
如图 挂了5分钟也没反应

**Comment by Alvin9999** [comment]
工具没问题，多半是你的电脑环境问题。你可以把电脑国产杀毒软件、安全卫士、防火墙关闭后，删掉文件夹，重新解压，更新ip。

**Comment by only-jay0118** [comment]
> 工具没问题，多半是你的电脑环境问题。你可以把电脑国产杀毒软件、安全卫士、防火墙关闭后，删掉文件夹，重新解压，更新ip。
我下的所有版本clash都不行，防火墙已关，杀毒软件是微软自带的

**Comment by Alvin9999** [comment]
实在用不了就用其它工具。目前很多人使用clash.meta工具。
