### ISSUE TITLE
Xray.cmd 更新所有ip也还是无法翻墙

### ISSUE THREAD

**Issue by phhh-xh** [Alvin9999/new-pac#1536]
你好，请教一下，（防火墙已关闭，无杀毒软件）前两天还是可以正常使用，今天使用Xray.cmd 更新所有ip也还是无法翻墙，是需要怎么操作啊，重新下载高内核集合版本吗

**Comment by phhh-xh** [comment]
使用的是chrome118集合2023.10.18版本

**Comment by Alvin9999** [comment]
嗯，下载最新版。

**Comment by Alvin9999** [comment]
嗯，下载最新版。

**Comment by phhh-xh** [comment]
好的感谢
