### ISSUE TITLE
浏览器菜单选项单击鼠标左键打不开

### ISSUE THREAD

**Issue by ekingling** [Alvin9999/new-pac#154]
浏览器菜单选项、收藏夹地址、鼠标右键菜单等等，用鼠标左键怎么点都打不开，现在只能移动光标到选项然后回车键打开，试了GA、GP、SS等好几个版本都是同样问题

**Comment by Alvin9999** [comment]
问几个问题
1.你用的是谷歌高内核便携版？
2.你的操作系统是win10 64位系统？
3.可以翻墙，但是操作上不同于常规操作？试过鼠标右键没有？

**Comment by Alvin9999** [comment]
这个问题应该是系统兼容性问题，且高内核版在有的系统上会遇到，主要影响的是浏览器操作体验，不影响翻墙。如果很在乎浏览器操作，可以换谷歌浏览器低内核版或火狐浏览器。

谷歌高内核版浏览器主要是在win7系统上开发和测试的，关于兼容性问题争取以后改进。

**Comment by Alvin9999** [comment]
刚思考了下，这可能是高内核版采用的谷歌浏览器32位，而win7以上的64位电脑操作系统与32位的谷歌浏览器不是很兼容导致的。

下一步考虑发布64位的高内核版来解决此问题。之前只发布32位的主要是图方便，因为通常来说64和32位的电脑操作系统都能用32位的软件。

**Comment by ekingling** [comment]
用的高内核版，系统win7 32位专业版，翻墙没问题，就是浏览体验差了点
找时间我试试看低内核版有没有这个问题

**Comment by Alvin9999** [comment]
有空帮忙测试下高内核版的修改方法.打开GreenChrome.ini这个文件。双击打开。
如下图：
![1](https://user-images.githubusercontent.com/12132898/31764024-98da8274-b4f2-11e7-881e-011b3bd2984e.PNG)

![2](https://user-images.githubusercontent.com/12132898/31764025-990e61c0-b4f2-11e7-84fd-161ecb110975.PNG)

这里面的设置就是针对高内核版的谷歌浏览器，数字1代表启动，数字0代表取消。你帮忙把与鼠标相关的数字1改成0。然后保存文件，接着打开浏览器看看是否能正常。我也是win7 32位系统，但是你所的问题没法重现，只能求助你帮忙了。


下面这个便携化的数字1不要改，其它的应该都没有问题。
![3](https://user-images.githubusercontent.com/12132898/31764027-998e223e-b4f2-11e7-8d16-07adc5aac8b7.PNG)

十分感谢！
