### ISSUE TITLE
Japan vps ChatGPT unavailable

### ISSUE THREAD

**Issue by s1mple-child** [Alvin9999/new-pac#1542]
首先感谢大佬提供的方案，使用大佬提供的教程搭建的环境一直很好用（首先感谢您的辛苦付出 ❤️ ）

之前 ChatGPT 大火那会我使用的该环境还可以正常访问，但是自从 ChatGPT 使用独立的 app，然后迭代了好几个版本之后就无法使用了，每次 log in 就会提示「You may be connected to a disallowed ISP」，我使用 vps 是位于 japan。 主要是想请教下，无法登录是因为本身地域限制不支持还是因为其他原因导致的？

感谢您的解答。如果其他人也有知道的也烦请解答下，感谢 ❤️

**Comment by Alvin9999** [comment]
可以参考这篇文章看看
https://p3terx.com/archives/cloudflare-warp-configuration-script.html

**Comment by s1mple-child** [comment]
> 可以参考这篇文章看看 https://p3terx.com/archives/cloudflare-warp-configuration-script.html

感谢大佬提供的参考方法，我进去看了一下。然后结合我自己的情况，我觉得是不是vps上使用哪个方式做的代理需要用哪一种方式执行。比如我用的是 ssr+tls+caddy，是不是我需要使用 socks5 那套方案部署？

**Comment by Alvin9999** [comment]
> > 可以参考这篇文章看看 https://p3terx.com/archives/cloudflare-warp-configuration-script.html
> 
> 感谢大佬提供的参考方法，我进去看了一下。然后结合我自己的情况，我觉得是不是vps上使用哪个方式做的代理需要用哪一种方式执行。比如我用的是 ssr+tls+caddy，是不是我需要使用 socks5 那套方案部署？

需要自己摸索哦，没有尝试过。

**Comment by s1mple-child** [comment]
> > > 可以参考这篇文章看看 https://p3terx.com/archives/cloudflare-warp-configuration-script.html
> > 
> > 
> > 感谢大佬提供的参考方法，我进去看了一下。然后结合我自己的情况，我觉得是不是vps上使用哪个方式做的代理需要用哪一种方式执行。比如我用的是 ssr+tls+caddy，是不是我需要使用 socks5 那套方案部署？
> 
> 需要自己摸索哦，没有尝试过。

好的，感谢大佬哈，现在我还有一个 alternative，暂时用着也影响不大。 👍
