### ISSUE TITLE
你好，能否提供更多地域的节点？

### ISSUE THREAD

**Issue by gdlwolf** [Alvin9999/new-pac#1549]
你好，能否提供更多地域的节点？现在的节点几乎都是美国，个别为台湾节点。能否增加日本，新加坡，韩国，或者几个欧洲节点？比如想用https://www.ciciai.com/，目前发现使用美国，台湾节点都会提示国家地区不支持，使用日本节点才能正常访问。

介于此种情况，希望能增加几个不同地区的节点，应对各种不同服务针对不同地区的封锁。

优化建议：将ip1更新，ip2更新、ip3更新这种命名更改为IP1_USA更新，IP2_TAIWAN更新，IP3_JAPAN更新，诸如此类。

**Comment by Alvin9999** [comment]
你好，目前没有这个打算。

**Comment by Alvin9999** [comment]
你可以根据教程自己搭建不同地区的节点。
