### ISSUE TITLE
按照步骤部署完成之后，启动不起来，已经试过三个命令，指定版本也试了，求解答

### ISSUE THREAD

**Issue by zhengxishuai** [Alvin9999/new-pac#1555]
[root@localhost systemd]# systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: start-limit) since Wed 2023-12-27 12:41:01 CST; 15min ago
  Process: 18677 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json (code=exited, status=1/FAILURE)
 Main PID: 18677 (code=exited, status=1/FAILURE)

Dec 27 12:41:01 localhost.localdomain systemd[1]: v2ray.service: main process exited, code=exited, status=1/FAILURE
Dec 27 12:41:01 localhost.localdomain v2ray[18677]: Failed to start: main/commands: failed to load config: [/usr/loc...
Dec 27 12:41:01 localhost.localdomain systemd[1]: Unit v2ray.service entered failed state.
Dec 27 12:41:01 localhost.localdomain systemd[1]: v2ray.service failed.
Dec 27 12:41:01 localhost.localdomain systemd[1]: v2ray.service holdoff time over, scheduling restart.
Dec 27 12:41:01 localhost.localdomain systemd[1]: Stopped V2Ray Service.
Dec 27 12:41:01 localhost.localdomain systemd[1]: start request repeated too quickly for v2ray.service
Dec 27 12:41:01 localhost.localdomain systemd[1]: Failed to start V2Ray Service.
Dec 27 12:41:01 localhost.localdomain systemd[1]: Unit v2ray.service entered failed state.
Dec 27 12:41:01 localhost.localdomain systemd[1]: v2ray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
![image](https://github.com/Alvin9999/new-pac/assets/131222902/341b293a-96d8-4ee9-b203-047bb11ca49c)

**Comment by Alvin9999** [comment]
vps系统选择的什么？
