### ISSUE TITLE
询问一下，按照教程配置了v2ray服务器，导入到v2rayN客户端后，延迟是200ms左右，速度在10M/S左右，不管是自动配置系统代理还是pac模式，始终无法访问外网，端口是开放的，ip也是没有被墙的，请问有人知道这是什么原因吗?

### ISSUE THREAD

**Issue by OnlyLoveD** [Alvin9999/new-pac#1559]

**Comment by Alvin9999** [comment]
访问外网时，网页报错提示截图一下

**Comment by Alvin9999** [comment]
测试有延迟和速度，账号应该没问题。多半是浏览器和客户端没有建立连接，你可以试试把浏览器代理设置了，socks5 127.0.0.1 端口和客户端v2rayN一致，一般是1080。这个在v2rayN客户端的“设置”——“参数设置”里面能看到具体的端口号。

**Comment by OnlyLoveD** [comment]
不好意思，可能是我没有描述清楚，我在访问youtube的时候，可以跳转到youtube，但是显示的是无网络连接，麻烦问一下，这个情况该怎么解决的呢？谢谢你，麻烦了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 晚上11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 询问一下，按照教程配置了v2ray服务器，导入到v2rayN客户端后，延迟是200ms左右，速度在10M/S左右，不管是自动配置系统代理还是pac模式，始终无法访问外网，端口是开放的，ip也是没有被墙的，请问有人知道这是什么原因吗? (Issue #1559)





 
测试有延迟和速度，账号应该没问题。多半是浏览器和客户端没有建立连接，你可以试试把浏览器代理设置了，socks5 127.0.0.1 端口和客户端v2rayN一致，一般是1080。这个在v2rayN客户端的“设置”——“参数设置”里面能看到具体的端口号。

**Comment by Alvin9999** [comment]
浏览器代理设置一下

**Comment by OnlyLoveD** [comment]
修改了浏览器代理，访问youtube还是一样的显示无网络连接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 询问一下，按照教程配置了v2ray服务器，导入到v2rayN客户端后，延迟是200ms左右，速度在10M/S左右，不管是自动配置系统代理还是pac模式，始终无法访问外网，端口是开放的，ip也是没有被墙的，请问有人知道这是什么原因吗? (Issue #1559)





 
浏览器代理设置一下

**Comment by Alvin9999** [comment]
只有访问youtube才这样，还是所有的网站都一样？

**Comment by OnlyLoveD** [comment]
访问外网网站都一样，github.com，google.com也会显示响应时间过长

**Comment by OnlyLoveD** [comment]
都是正常的，successful
![image](https://github.com/Alvin9999/new-pac/assets/35253076/a7f38d75-4852-4665-a2b2-d14c4fb1b716)

**Comment by Alvin9999** [comment]
校准一下电脑网络时间。

**Comment by Alvin9999** [comment]
电脑安全卫士、防火墙、杀毒软件关闭。

**Comment by OnlyLoveD** [comment]
还是一样的，这些操作我都已经做过了

**Comment by Alvin9999** [comment]
你试一下免费v2ray账号能不能用？https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by Alvin9999** [comment]
如果不能用，那还是你的电脑环境或者客户端没设置对，如果能用，那么可能还是你搭建的账号有问题。

**Comment by OnlyLoveD** [comment]
![image](https://github.com/Alvin9999/new-pac/assets/35253076/fb1e0107-c748-414a-a519-a6bd24f06168)
你好，我复制了你的这个链接到v2ray客户端，然后需要去更新订阅，就出现了上述错误，这么晚了还在因为这个问题打扰你，不好意思，您早点休息，明天我再问你吧

**Comment by Alvin9999** [comment]
那个vmess不是订阅链接，url导入到客户端。

**Comment by Alvin9999** [comment]
点击链接进去才能看到账号

**Comment by OnlyLoveD** [comment]
作者大大，你好，我早上用了你给我的url,确实可以访问，然后我就将vps重置系统，照着你的v2ray自建服务器教程重新做了一遍，自建服务器过程中和你教程中的界面出现的情况是一样的，然后创建完成后，也将443端口放行了，传输方式也设置为websocket类型，并且检查端口国内网络是正常的，也按照教程上将浏览器代理设置为了本地
![image](https://github.com/Alvin9999/new-pac/assets/35253076/3a3774c2-8472-4c30-a286-c46ff7b036fb)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/8a80f41e-97a5-4931-8945-f4f35642997a)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/091019bb-b57e-4781-a816-31718aa47fdb)

**Comment by Alvin9999** [comment]
1、代理协议HTTP改为socks5
2、把kcp wechat-video改为tcp或者websocket

**Comment by OnlyLoveD** [comment]
作者你好，代理协议改为socks5和传输方式也设置为websocket类型，但是Youtube还是会显示无网络连接，但是我测试了端口国内网络是访问成功的，本地电脑的防火墙和电脑管家也都关闭的

**Comment by Alvin9999** [comment]
截图看一下浏览器代理设置以及服务器账号信息

**Comment by OnlyLoveD** [comment]
![image](https://github.com/Alvin9999/new-pac/assets/35253076/9d153438-9856-4f0e-8b76-33dabb3002d4)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/b4dac27d-750a-4b33-9f47-15bff791b748)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/26c43418-7f3d-405a-8fdf-4094f510b20d)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/71103c81-2ed7-4dc6-8b20-c67c86d54461)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/6790d5f5-8648-4a80-9c75-b30d3302105d)
作者你好，对照了教程好几次了，而且也确实把能测试的都测试了，实在不知道问题出在哪里了

**Comment by OnlyLoveD** [comment]
![image](https://github.com/Alvin9999/new-pac/assets/35253076/9d153438-9856-4f0e-8b76-33dabb3002d4)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/b4dac27d-750a-4b33-9f47-15bff791b748)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/26c43418-7f3d-405a-8fdf-4094f510b20d)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/71103c81-2ed7-4dc6-8b20-c67c86d54461)
![image](https://github.com/Alvin9999/new-pac/assets/35253076/6790d5f5-8648-4a80-9c75-b30d3302105d)
作者你好，对照了教程好几次了，而且也确实把能测试的都测试了，实在不知道问题出在哪里了

**Comment by Alvin9999** [comment]
我看你的v2rayN信息里面开启了TLS，你搭建的时候有开启TLS吗？

**Comment by OnlyLoveD** [comment]
有开启，给了域名的

**Comment by Alvin9999** [comment]
你把脚本卸载了，用教程中的末尾脚本重新搭建看看。

**Comment by OnlyLoveD** [comment]
行，好的，谢谢了，另外想问一下，还有哪些地方可能会出问题呢？会不会是有些小问题没注意到，我确实是按照教程来搭的，而且搭建的过程中，出现的界面都是和教程中是一样的

**Comment by Alvin9999** [comment]
现在可以了吗
