### ISSUE TITLE
自动部署出现HTTP ERROR 502

### ISSUE THREAD

**Issue by paopaohei** [Alvin9999/new-pac#156]

**Comment by Alvin9999** [comment]
什么意思？上传appid还是部署ssr？

**Comment by paopaohei** [comment]
上传appid

**Comment by Alvin9999** [comment]
部署时有没有开启GoProxy版，GoProxy版是否能正常翻墙？

**Comment by paopaohei** [comment]
开启过了，弹出来Google账号登陆的页面，点击允许后出现这种情况

**Comment by Alvin9999** [comment]
这就奇怪了，只能多试试看了

**Comment by paopaohei** [comment]
我用的是你的goproxy，正式的客户端现在找不到，会不会是这个原因？纯小白智商捉急

**Comment by Alvin9999** [comment]
是的，就用我的goproxy版。所以说，问题很奇怪啊。goproxy版可以正常打开国外网站，对吧？

你上传时有没有关闭杀毒软件？

**Comment by paopaohei** [comment]
嗯，可以正常打开，不知道什么情况。根本就没装杀毒软件

**Comment by Alvin9999** [comment]
把完整的黑框里面的错误信息截图发一下

**Comment by paopaohei** [comment]
![](https://i.imgur.com/QWwK10o.png)

**Comment by Alvin9999** [comment]
嗯，这一步没问题，然后呢

**Comment by paopaohei** [comment]
然后就是弹出来Google账号登陆的页面，点击允许后，网页跳转成为HTTP ERROR 502
