### ISSUE TITLE
科学上网-翻墙、免费翻墙、免费科学上网、VPN、一键翻墙浏览器，vps一键搭建翻墙服务器脚本/教程，免费shadowsocks/ss/ssr/v2ray/goflyway账号/节点，免费自由上网、fanqiang、翻墙梯子，电脑、手机、iOS、安卓、windows、Mac、Linux、路由器翻墙

### ISSUE THREAD

**Issue by asd-124** [Alvin9999/new-pac#1560]
请问有教程吗？秘密是多上？大佬照顾下小白

**Comment by Alvin9999** [comment]
有教程，电脑下载这个，下载后解压。
https://github.com/Alvin9999/new-pac/wiki/%E9%AB%98%E5%86%85%E6%A0%B8%E7%89%88/145f7428c34155fa88521dc3e6f185a34a46d113

**Comment by Alvin9999** [comment]
根据自己的电脑系统选择对应的版本
