### ISSUE TITLE
你好！我请教个问题！实在是不知道怎么弄了

### ISSUE THREAD

**Issue by oneole** [Alvin9999/new-pac#1563]
请问这个怎么处理。。
![image](https://github.com/Alvin9999/new-pac/assets/43529206/6dca4052-591b-45c6-a22f-b9df6df5cb43)

**Comment by oneole** [comment]
#1313 我试试解决一下

**Comment by Alvin9999** [comment]
系统不要选择CentOS8，脚本不支持这个系统，推荐Debain11、CentOS7

**Comment by oneole** [comment]
> 提醒一下，服务器系统不要选择CentOS8，脚本不支持这个系统，推荐Debain11、CentOS7

好的谢谢！

**Comment by oneole** [comment]
你好！用Debian10.2直接就搞定了 谢谢！

**Comment by fullhopeus** [comment]
我个人觉得ss-go好用一些。至少不用配置python。

**Comment by oneole** [comment]
> 我个人觉得ss-go好用一些。至少不用配置python。

好的 我一会试一下
