### ISSUE TITLE
有病毒?

### ISSUE THREAD

**Issue by muskapple914** [Alvin9999/new-pac#1569]
我有沙盒检测，报告有异常行为,获取按键，隐藏文件?

**Comment by muskapple914** [comment]
<img width="962" alt="Snipaste_2024-01-29_22-14-53" src="https://github.com/Alvin9999/new-pac/assets/103991613/25138272-06b4-4d98-bf44-f740c957c724">

**Comment by Alvin9999** [comment]
软件没有病毒。

**Comment by Alvin9999** [comment]
如果实在不放心，可以不用的。
