### ISSUE TITLE
超时了怎么处理啊，打不开google

### ISSUE THREAD

**Issue by ifu12345678** [Alvin9999/new-pac#157]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp 221.144.116.97:443: i/o timeout"
}

**Comment by Alvin9999** [comment]
按照使用说明运行ip更新文件来更新一下ip

**Comment by ifu12345678** [comment]
按照你写的方法搭ssh使用自建了appid，更新了ip，但很不稳定啊，一直抽

**Comment by Alvin9999** [comment]
你说的ssr吧？
你用的是GoProxy版还是GoProxy Quic版？

**Comment by ifu12345678** [comment]
GoProxy版

**Comment by Alvin9999** [comment]
如果刷新网页以及重启goproxy，且软件运行了3～5分钟，都不流畅的话，建议换其它版本。
