### ISSUE TITLE
【 一键翻墙浏览器】收藏夹问题

### ISSUE THREAD

**Issue by hslkw** [Alvin9999/new-pac#1573]
您好，我是用过【 一键翻墙浏览器】中Xray，不经意在浏览器收藏夹发现一些xx大法的收藏网址。
请问这是作者不经意放进去，还是因需投放 “广告”、或是个人原因放进去的。
用起来确实挺方便的，这点得感谢无私奉献。
但是我一点都不想和这些东西沾边，请告知以便选择去留。
谢谢！

**Comment by Alvin9999** [comment]
我就是修炼大法的，在国内很多人是被宣传蒙蔽的，所以这也是一种让人们了解真相的一种方式。大法没有强制，你想看就看，不想看就不看。但一些真相视频，还是建议你能够了解一下，当然这都是自愿的。

**Comment by hslkw** [comment]
既为水中鱼，就应该安静的生活在水底，跃出来，或许是龙门，或许是渔网油锅。
成年人，有时候没必要去分清好与坏，重要的是你有没有选择的权力，以及能不能承担选择的后果。
麻烦把这条issue删一下吧，谢谢
