### ISSUE TITLE
shadowsocks服务器配置域名后仍然不能从国内访问

### ISSUE THREAD

**Issue by HaoLi97** [Alvin9999/new-pac#1576]
如题，我已经按照这篇文章的描述在digitalocean的vps上部署了shadowsocks，

https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B

过年这两周都没法访问原来的vps梯子，所以按照文章里的购买配置域名的方法试图规避GFW封锁，但还是没法从国内访问，请问还有别的方法吗？谢谢了。

**Comment by Alvin9999** [comment]
端口是否是通的。检测方法：https://tcp.ping.pe/ip:端口

**Comment by Alvin9999** [comment]
如果ip没被封，换端口应该就可以了。
除了ssr，还可以用v2ray、hysteria等。

**Comment by HaoLi97** [comment]
从国外的环境ping是通的，从国内的就不行

**Comment by HaoLi97** [comment]
好的，我试试，谢谢
