### ISSUE TITLE
这两天是不是封SS？之前部署的突然不行了

### ISSUE THREAD

**Issue by ssshooter** [Alvin9999/new-pac#158]
什么错都没有报，总之就是突然不行了，有类似的情况吗？

**Comment by Alvin9999** [comment]
ssr仍然很好用。

你先ping一下自己的服务器ip或者用xshell软件连接一下，若不能ping通或xshell连接不上，那么就是ip被墙了，建议删掉服务器，重新开一个新的服务器，就是新的ip了。

如果你的ip没被墙，但还是用不了，那么请部署ssr账号，ssr账号相比ss账号更抗封锁，因为多了协议和混淆。

**Comment by ssshooter** [comment]
@Alvin9999 😢 我用aws的重开了好几个全都ping不通

**Comment by Alvin9999** [comment]
我推荐的[vultr](http://www.vultr.com/?ref=7048874)表现不错，硅谷、达拉斯表现很好，我每次开都是好的ip。运气好的话，能开日本的，延迟很低。

**Comment by ssshooter** [comment]
好的，我试试 😭
