### ISSUE TITLE
goflyway免费账号用不了,望更新

### ISSUE THREAD

**Issue by hikaruian** [Alvin9999/new-pac#1581]

**Comment by Alvin9999** [comment]
账号正常，很多人正在使用。

**Comment by hikaruian** [comment]
请教大佬，使用goflyway访问google.com报下面的错误是怎么回事
proxyconnect tcp: dial tcp 45.130.147.174:443: connect: connection refused

**Comment by hikaruian** [comment]
用的是以下命令行，麻烦大佬帮忙看下～
goflyway -up="45.130.147.174:443" -k="ntdtv.com" -l=":8100"

**Comment by Alvin9999** [comment]
你的账号是不对的

**Comment by Alvin9999** [comment]
IP：109.104.152.136

端口：12345

密码：dongtaiwang.com

客户端协议：HTTP

**Comment by hikaruian** [comment]
可以了，感谢大佬
