### ISSUE TITLE
"谷歌翻墙浏览器"是否考虑改用Supermium

### ISSUE THREAD

**Issue by GTEMYee** [Alvin9999/new-pac#1582]
如题
github.com/win32ss/supermium

**Comment by Alvin9999** [comment]
目前没有计划改用Supermium。

**Comment by Alvin9999** [comment]
大概了解了下，支持的系统更多，尤其是老系统。不过有的人测评该软件还是有一些问题，比如https://www.youtube.com/watch?v=Mj5mMEs9yUM

没有更多时间和精力来测试软件的问题，并且目前Supermium好像是不能制作便携版。

**Comment by GTEMYee** [comment]
> 大概了解了下，这个软件的功能还是挺强大，支持的系统更多，尤其是老系统，比如xp、win7、vista。不过有的人测评该软件还是有一些问题，比如https://www.youtube.com/watch?v=Mj5mMEs9yUM
> 
> 没有更多时间和精力以及不同的系统来测试软件的问题。观望一下。

我看到您说不能制作便携版
其实在 chrome.exe 后面加命令行参数 "--user-data-dir=.\UserData\" 也可能同样达到便携版的效果
比如 chrome.exe --user-data-dir=.\UserData\

**Comment by Alvin9999** [comment]
收到

**Comment by Alvin9999** [comment]
已发布。
