### ISSUE TITLE
关于ip地址问题咨询

### ISSUE THREAD

**Issue by sjm787801858** [Alvin9999/new-pac#1589]
我的电脑里面在玩一个游戏，不能在同一个ip地址上面操作同一个账号，一个是翻墙的谷歌浏览器，一个是没有翻墙的浏览器，请问这样挂同一个账号，是否会被检测到在同一个IP地址呢

**Comment by Alvin9999** [comment]
一般是不同的地址，可以用浏览器打开搜索网页查询ip地址来验证
