### ISSUE TITLE
Linux系统翻墙方法中的无界浏览怎么使用？

### ISSUE THREAD

**Issue by LiuQhahah** [Alvin9999/new-pac#159]
谢谢！！

**Comment by Alvin9999** [comment]
你好，这个无界浏览linux版是我直接从无界浏览网站上搬过来的，具体方法还得自己研究哦

**Comment by LiuDong2016** [comment]
使用方法 ：
1、chmod 777 ul
2、ul -L 127.0.0.1:1080
//我是刘栋，有什么需要我的地方可以联系我

**Comment by Alvin9999** [comment]
@LiuDong2016 谢谢分享哈
