### ISSUE TITLE
我Azure虚拟机执行 ssr脚本（ToyoDAdoubi的），但是一直启动失败，提示找不到python

### ISSUE THREAD

**Issue by lunat1cccc** [Alvin9999/new-pac#1594]
不知道是脚本老了还是什么别的原因，看日志也说是找不到python。现在都是python3了，但是脚本中的写法是不是过时了。

**Comment by Alvin9999** [comment]
可能是系统与脚本不兼容，不要用最新的系统，推荐debian11，centos7等
