### ISSUE TITLE
用了后，英雄联盟都打不开，提示服务器未响应，可能遇到一个网络问题

### ISSUE THREAD

**Issue by xiaovjianai** [Alvin9999/new-pac#16]
怎么恢复过来啊？？？？？？？？？？

**Comment by xiaovjianai** [comment]
![image](https://cloud.githubusercontent.com/assets/19337296/19836453/fb994f5e-9edb-11e6-958b-6e76d9789f06.png)

**Comment by Alvin9999** [comment]
不管你采用何种翻墙手段翻墙，假如出现退出翻墙软件后，IE浏览器无法上网，可以通过此方法解决：依次打开IE浏览器——工具——internet选项——连接——局域网设置，把此页面的所有“勾”都去掉，确定即可。

**Comment by xiaovjianai** [comment]
还是不行呢。。

**Comment by Alvin9999** [comment]
那就奇怪了嘛！你用的什么版本的翻墙浏览器啊

**Comment by theratlesnake** [comment]
你遇到的这个问题和翻墙软件无关，是IE的问题，我也遇到过，清理IE，或者重置一下就可以了，以前我玩英雄联盟就经常遇到这问题。
