### ISSUE TITLE
v2ray 按教程跑完脚本不生效

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1600]
把控制台的 vmess url 复制导入到了客户端，还是不行。
![image](https://github.com/Alvin9999/new-pac/assets/22291811/dd0d2e98-0b89-44a8-9d3c-abbaa2a38275)

**Comment by Alvin9999** [comment]
用这个搭建
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B
