### ISSUE TITLE
为什么谷歌浏览器内核/quick 版经常过一段时间就无法代理，但下载最新的包却可以!那命令行更新ip的意义何在 

### ISSUE THREAD

**Issue by zhugunzi** [Alvin9999/new-pac#1601]
为什么谷歌浏览器内核/quick 版经常过一段时间就无法代理，但下载最新的包却可以!那命令行更新ip的意义何在

**Comment by Alvin9999** [comment]
封锁等原因，旧版可能会无法使用。一般情况下更新ip可使用，但特殊情况除外。所以在某些时候更新ip还是有其意义的。
