### ISSUE TITLE
多个协议节点的一键安装脚本是否能做到伪装

### ISSUE THREAD

**Issue by juhuon** [Alvin9999/new-pac#1602]
看网上说流量什么的需要做伪装，最好上cdn，不然容易被封。想问问一键安装脚本是否自动配置了伪装？
![批注 2024-04-16 093038](https://github.com/Alvin9999/new-pac/assets/130397609/2ef364c2-11a0-4d7b-a29c-a672733180fa)

**Comment by Alvin9999** [comment]
这个脚本有多个节点，自动生成的带域名的节点是采用了伪装模式，自动配置了cf的cdn
