### ISSUE TITLE
IP更新后出来的cmd窗口闪退

### ISSUE THREAD

**Issue by luocan03** [Alvin9999/new-pac#1606]
有没有大佬知道IP更新后本来需要弹出来的cmd窗口闪一下就消失了，然后就用不了是怎么回事呀

**Comment by Alvin9999** [comment]
浏览器解压的路径是什么？

**Comment by luocan03** [comment]
> 浏览器解压的路径是什么？

E:\Chrome109_AllNew_2023.4.24\Chrome109_AllNew_2023.4.24\Chrome109_AllNew_2023.4.24
就是偶尔会出现选择完ip更新后，空格或者回车启动程序本来有个cmd窗口的会闪一下就没了，只会打开一个浏览器。之前也出现过，但是偶尔等个一两天就没有这个问题了

**Comment by Alvin9999** [comment]
你用最新版。然后把压缩包放在C盘一级目录，然后解压看看。

**Comment by luocan03** [comment]
> 你用最新版。然后把压缩包放在C盘一级目录，然后解压看看
现在可以了，感谢大佬

**Comment by Alvin9999** [comment]
我看你用的是Chrom109版本，你的电脑是win7系统吗？

**Comment by luocan03** [comment]
> 我看你用的是Chrom109版本，你的电脑是win7系统吗？

win11

**Comment by Alvin9999** [comment]
win11系统可以用chrome124高版本。

**Comment by zz-GuoYF** [comment]
> win11系统可以用chrome124高版本。

D:\Software\Chrome123_AllNew_2024.3.21
这是我的路径，win11系统，有相同的问题

**Comment by Alvin9999** [comment]
> > win11系统可以用chrome124高版本。
> 
> D:\Software\Chrome123_AllNew_2024.3.21 这是我的路径，win11系统，有相同的问题

关闭国产杀毒软件、安全卫士。如果还不行，可以放在C盘一级目录后再试试看。

**Comment by zz-GuoYF** [comment]
> > > win11系统可以用chrome124高版本。
> > 
> > 
> > D:\Software\Chrome123_AllNew_2024.3.21 这是我的路径，win11系统，有相同的问题
> 
> 关闭国产杀毒软件、安全卫士。如果还不行，可以放在C盘一级目录后再试试看。
我用的是火绒，退出后不行，放在C盘一级目录也不行C:\Chrome123_AllNew_2024.3.21；
目前只有一个cmd是能够正常使用的1.clash.meta翻墙，就是这个，无论火绒是否退出，无论放在C盘还是D盘都可以

**Comment by Alvin9999** [comment]
@zz-GuoYF  是很奇怪，因为要是闪退，应该都会闪退，而你clash.meta可以用。
你试试Chrome124版本。

**Comment by zz-GuoYF** [comment]
@Alvin9999 现在一个能正常用，就先用这个吧，用新版本又得重新重新输一遍账号和密码，等我升级版本了，再来回复一下

**Comment by zz-GuoYF** [comment]
更新到124版本了，还是同样的问题，clash.meta翻墙.cmd可以正常运行，其他的几个都闪退
用cmd运行2.Xray翻墙.cmd后正常弹出更新ip的cmd窗口，在选择数字更新完ip后，chrome浏览器正常打开，但是cmd窗口闪退

我用git bash执行了一下2.Xray翻墙.cmd, 提示信息如下
![image](https://github.com/Alvin9999/new-pac/assets/65477849/4c32b3cb-cfe7-41b2-bb28-a9d9d9695fe2)

**Comment by zz-GuoYF** [comment]
楼上的回复有用
