### ISSUE TITLE
多节点搭建，出节点信息

### ISSUE THREAD

**Issue by vicorn** [Alvin9999/new-pac#1610]
![image](https://github.com/Alvin9999/new-pac/assets/30787425/e43f2c9c-2500-4653-b9e2-f1833175db7a)

这一步之后一直卡在这，怎么没有后面那两个配置信息界面啊？

**Comment by Alvin9999** [comment]
第7和第8个步骤，你按回车键没有？看着没有信息。
你可以重新搭建看看。

**Comment by vicorn** [comment]
> 第7和第8个步骤，你按回车键没有？看着没有信息。 你可以重新搭建看看。
重新搭建几次了都是这样，然后重装了下系统再重搭，又提示xray没开启，输入y回车也没用，可是上面不是提示开启了吗？

![image](https://github.com/Alvin9999/new-pac/assets/30787425/8374bd16-c22c-4927-8525-99c1608fc39f)

**Comment by vicorn** [comment]
> 服务器系统选择的什么？
![image](https://github.com/Alvin9999/new-pac/assets/30787425/9b064afd-0060-447a-a1d8-20aa4bbed881)

debian11，会不会配置太低了，1核1G的vps。账号密码发你邮箱了，帮忙看下哦，大佬。
