### ISSUE TITLE
为什么我续费VPS服务器后显示延迟负一并且无法使用

### ISSUE THREAD

**Issue by DeductedSum8676** [Alvin9999/new-pac#1611]
用的V2ray的方法，托了一天没交钱，交上钱后加速不起作用，厂商是hostwinds

**Comment by Alvin9999** [comment]
你问一下你的厂商客服，是不是服务器被暂停了。

**Comment by Alvin9999** [comment]
你也可以自己ping一下你的服务器ip，如果能ping通，那么服务器应该就是正常的。
而v2ray账号不能用，那可能是端口被封了，可以换一下端口试试。

**Comment by DeductedSum8676** [comment]
问过服务器厂商了，应该没问题，他美国人用翻译跟我说话，我也听不懂他具体想表达什么

**Comment by DeductedSum8676** [comment]
ping过了，没问题，我去看看端口怎么搞

**Comment by DeductedSum8676** [comment]
哪里有换端口的教程，我去ping过了

**Comment by Alvin9999** [comment]
还可以用这个脚本，一键搭建多个节点
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B
