### ISSUE TITLE
我是第一次接触，应该安装那个？

### ISSUE THREAD

**Issue by beifen886** [Alvin9999/new-pac#1616]
我是第一次接触，应该安装那个？

我应该选择 ssr 还是 ss 还是其它的？

**Comment by Alvin9999** [comment]
可以选择一键翻墙浏览器，可以电脑系统，选择对应的版本
https://github.com/Alvin9999/new-pac/wiki/%E9%AB%98%E5%86%85%E6%A0%B8%E7%89%88/

**Comment by beifen886** [comment]
@Alvin9999 我是想自己搭建，Linux 操作我会。

**Comment by Alvin9999** [comment]
可以选择ssr，用ssr客户端
