### ISSUE TITLE
我买了vulrt的vps，搭建了ssr的梯子，但是在ip111.cn里测试，从国外访问发现ip还是本地的。 我们公司的ip测试结果就是正常的

### ISSUE THREAD

**Issue by menkaiyuan** [Alvin9999/new-pac#1617]
我搭建的ip：
![微信图片_20240515163144](https://github.com/Alvin9999/new-pac/assets/34207201/94fdf997-18c8-4a32-ac49-81d3cde717f7)
   
我们公司的优质的梯子测试结果：
![QQ截图20240515163203](https://github.com/Alvin9999/new-pac/assets/34207201/a2705710-4415-4fd9-b5bc-771323b6c959)

**Comment by menkaiyuan** [comment]
求大神解惑，我主要用来做tiktok帐号注册的

**Comment by menkaiyuan** [comment]
我本地是config模式，

**Comment by Alvin9999** [comment]
你可以用这个被墙的网址来测试ip的归属地
https://allinfa.com/tool/ip2/ip.php
