### ISSUE TITLE
@Alvin9999可以发一个批量获取谷歌ip的工具吗？

### ISSUE THREAD

**Issue by A6066** [Alvin9999/new-pac#162]
你发的那个表 300一下只有几个ip可用

**Comment by Alvin9999** [comment]
只要有1个有效的谷歌ip，GoAgent版、GoProxy版、GoProxy Quic版就可以正常使用。

近期国内的网络环境能够搜到的ip很少，这属于正常现象。我发布的搜ip教程，只针对GoAgent版和GoProxy版。GoProxy Quic版的搜ip教程有点不一样，后期会发布。

**Comment by A6066** [comment]
知道了 3Q

**Comment by A6066** [comment]
知道了  3q
