### ISSUE TITLE
求助大佬! 突然用不了了, 是控制台里面出现了warning导致的吗?

### ISSUE THREAD

**Issue by deihaohaohun** [Alvin9999/new-pac#1621]
![image](https://github.com/Alvin9999/new-pac/assets/32506456/13016dc2-bcd8-411d-bebe-b5b1a160146a)
突然用不了了, 上午还用的好好的, 又试了几次发现控制台里面多了一些警告, 是这个原因吗?该如何解决呢?

顺便咨询一个问题, 下面的这些配置为什么在手机上用就可以成功翻出来, 到了电脑上面就不好使了呢?
![image](https://github.com/Alvin9999/new-pac/assets/32506456/e3dab983-a83b-4b46-ab83-e563d58f82dc)

**Comment by Alvin9999** [comment]
那个提示是正常的。

**Comment by Alvin9999** [comment]
如果你是购买的节点，你需要咨询你购买的网站的客服。
