### ISSUE TITLE
大佬 已经都按步骤来了但是连不上网

### ISSUE THREAD

**Issue by tang5846** [Alvin9999/new-pac#1622]
求教
![111](https://github.com/Alvin9999/new-pac/assets/96603333/c6c76e61-dc7c-4243-a620-03fe221acff5)

**Comment by tang5846** [comment]
配置是导入的这一串
![222](https://github.com/Alvin9999/new-pac/assets/96603333/cf160dfb-7248-483d-94db-2297f0284af1)

**Comment by Alvin9999** [comment]
你用这个脚本来搭建，可以一次搭建多个节点
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B

**Comment by Alvin9999** [comment]
使用时电脑的杀毒软件、防火墙要退出来，避免干扰翻墙上网。

**Comment by tang5846** [comment]
大佬我防火墙杀毒软件也退了 也按着那个脚本重新部署了还是那样
![333](https://github.com/Alvin9999/new-pac/assets/96603333/249701d6-e701-42d0-b745-0d230395be20)

**Comment by tang5846** [comment]
> 测试有速度，怎么就用不了呢？奇怪。浏览器网页打不开时的错误提示是什么？

说是响应时间过长

**Comment by Alvin9999** [comment]
打开google.com呢

**Comment by tang5846** [comment]
![444](https://github.com/Alvin9999/new-pac/assets/96603333/6c67f050-3f2b-4500-9d91-b3ef4389271e)
是这样的

**Comment by Alvin9999** [comment]
把电脑的时间校准一下。

**Comment by tang5846** [comment]
> 把电脑的时间校准一下。校正了还是不行...害

**Comment by tang5846** [comment]
> 把电脑的时间校准一下。

用这个的话可以用拨号连接嘛，还是必须是wifi什么的

**Comment by Alvin9999** [comment]
应该是可以的。
你把v2rayN软件设置成全局代理看看。

**Comment by Alvin9999** [comment]
你试试这个免费v2ray账号
https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
这个账号很多人在用，如果你还是不能用，应该是你的电脑环境或者设置问题。

**Comment by Alvin9999** [comment]
教程更新了。

**Comment by Alvin9999** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B
