### ISSUE TITLE
多协议节点搭建后端口连不上

### ISSUE THREAD

**Issue by SorataKasugano** [Alvin9999/new-pac#1623]
Debian 10 x64
按 https://github.com/Alvin9999/new-pac/blob/master/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B.md 这个执行的，批量导入之后：
![image](https://github.com/Alvin9999/new-pac/assets/19202656/dc0d6fcb-c507-4f43-abb3-912e06c9aa91)
第一个测试用的站点正常，剩下六个站点都连不上，用tcp.ping.pe测试也都是连接失败：
![image](https://github.com/Alvin9999/new-pac/assets/19202656/f0fa2941-986f-417d-9b21-032e5e6ae3ce)
查看vps端口和进程状态是这样：
![image](https://github.com/Alvin9999/new-pac/assets/19202656/c59c0f35-ad6e-4b5d-83d8-1ed6bd6e0d45)
请问是哪里出了问题？

**Comment by SorataKasugano** [comment]
补充第三步的bbr加速启用和卸载都是连不上

**Comment by Alvin9999** [comment]
你重新弄一台服务器，不要开启ipv6，搭建试试

**Comment by SorataKasugano** [comment]
重新弄了一台，没开ipv6：
Connecting to 45.76.175.238:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Linux vultr 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
/usr/bin/xauth:  file /root/.Xauthority does not exist
root@vultr:~# bash <(wget -qO- https://raw.githubusercontent.com/fscarmen/argox/main/argox.sh)

 Language:
 1. English (default) 
 2. 简体中文 

 Choose: 2

 所有依赖已存在，不需要额外安装 
======================================================================================================================

 脚本版本:1.6.5 (2024.05.20)
 功能新增:1. 添加 Github 加速 CDN; 2. 去掉订阅模板2
 系统信息:
	 当前操作系统:Debian GNU/Linux 12 (bookworm)
	 内核:6.1.0-21-amd64
	 处理器架构:amd64
	 虚拟化:microsoft 
	 IPv4: 45.76.175.238  美国  The Constant Company 
	 IPv6:      
	 Argo: 未安装	 	 	 
	 Xray: 未安装	 		  

======================================================================================================================

 1.  安装 ArgoX 脚本 (argo + xray) 
 2.  升级内核、安装BBR、DD脚本 (argox -b) 
 3.  安装 Sing-box 协议全家桶脚本 [https://github.com/fscarmen/sing-box] 
 4.  安装 sba 脚本 (argo + sing-box) [https://github.com/fscarmen/sba] 
 0.  退出 

 请选择: 1

 (1/8) 输出订阅二维码和 https 服务，需要安装依赖 nginx
 如不需要，请输入 [n]，默认安装: 

 (2/8) 请输入 VPS IP (默认为: 45.76.175.238): 

 (3/8) 请输入 Argo 域名 (如果没有，可以跳过以使用 Argo 临时域名): 

 (4/8) 请输入 Reality 的端口号 (默认为 27195): 

 1. cn.azhz.eu.org 
 2. acjp.cloudflarest.link 
 3. xn--b6gac.eu.org 
 4. dash.cloudflare.com 
 5. skk.moe 
 6. visa.com 

 (5/8) 请选择或者填入优选域名，默认为 cn.azhz.eu.org: 

 (6/8) 请输入 Xray UUID (默认为 283a2513-e34b-4f3f-b70e-b2899c6e50ea): 

 (7/8) 请输入 Xray WS 路径 (默认为 argox): 

 (8/8) 请输入节点名称 (默认为 vultr): 
Created symlink /etc/systemd/system/multi-user.target.wants/argo.service → /etc/systemd/system/argo.service.

 Argo 开启 成功 

Created symlink /etc/systemd/system/multi-user.target.wants/xray.service → /etc/systemd/system/xray.service.

 Xray 开启 成功 

*******************************************
┌────────────────┐  ┌────────────────┐
│                │  │                │
│     V2rayN     │  │    NekoBox     │
│                │  │                │
└────────────────┘  └────────────────┘
----------------------------
vless://283a2513-e34b-4f3f-b70e-b2899c6e50ea@45.76.175.238:27195?encryption=none&flow=xtls-rprx-vision&security=reality&sni=addons.mozilla.org&fp=chrome&pbk=t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA&type=tcp&headerType=none#vultr reality-vision

vless://283a2513-e34b-4f3f-b70e-b2899c6e50ea@45.76.175.238:27195?security=reality&sni=addons.mozilla.org&fp=chrome&pbk=t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA&type=grpc&serviceName=grpc&encryption=none#vultr reality-grpc

vless://283a2513-e34b-4f3f-b70e-b2899c6e50ea@cn.azhz.eu.org:443?encryption=none&security=tls&sni=navy-changing-niagara-accessibility.trycloudflare.com&type=ws&host=navy-changing-niagara-accessibility.trycloudflare.com&path=%2Fargox-vl%3Fed%3D2048#vultr-Vl

vmess://eyAidiI6ICIyIiwgInBzIjogInZ1bHRyLVZtIiwgImFkZCI6ICJjbi5hemh6LmV1Lm9yZyIsICJwb3J0IjogIjQ0MyIsICJpZCI6ICIyODNhMjUxMy1lMzRiLTRmM2YtYjcwZS1iMjg5OWM2ZTUwZWEiLCAiYWlkIjogIjAiLCAic2N5IjogIm5vbmUiLCAibmV0IjogIndzIiwgInR5cGUiOiAibm9uZSIsICJob3N0IjogIm5hdnktY2hhbmdpbmctbmlhZ2FyYS1hY2Nlc3NpYmlsaXR5LnRyeWNsb3VkZmxhcmUuY29tIiwgInBhdGgiOiAiL2FyZ294LXZtP2VkPTIwNDgiLCAidGxzIjogInRscyIsICJzbmkiOiAibmF2eS1jaGFuZ2luZy1uaWFnYXJhLWFjY2Vzc2liaWxpdHkudHJ5Y2xvdWRmbGFyZS5jb20iLCAiYWxwbiI6ICIiIH0=

trojan://283a2513-e34b-4f3f-b70e-b2899c6e50ea@cn.azhz.eu.org:443?security=tls&sni=navy-changing-niagara-accessibility.trycloudflare.com&type=ws&host=navy-changing-niagara-accessibility.trycloudflare.com&path=/argox-tr?ed%3D2048#vultr-Tr

ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToyODNhMjUxMy1lMzRiLTRmM2YtYjcwZS1iMjg5OWM2ZTUwZWE=@cn.azhz.eu.org:443#vultr-Sh
由于该软件导出的链接不全，请自行处理如下: 传输协议: WS , 伪装域名: navy-changing-niagara-accessibility.trycloudflare.com , 路径: /argox-sh?ed=2048 , 传输层安全: tls , sni: navy-changing-niagara-accessibility.trycloudflare.com

*******************************************
┌────────────────┐
│                │
│  Shadowrocket  │
│                │
└────────────────┘
----------------------------

vless://YXV0bzoyODNhMjUxMy1lMzRiLTRmM2YtYjcwZS1iMjg5OWM2ZTUwZWFANDUuNzYuMTc1LjIzODoyNzE5NQ==?remarks=vultr%20reality-vision&obfs=none&tls=1&peer=addons.mozilla.org&xtls=2&pbk=t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA

vless://YXV0bzoyODNhMjUxMy1lMzRiLTRmM2YtYjcwZS1iMjg5OWM2ZTUwZWFANDUuNzYuMTc1LjIzODoyNzE5NQ==?remarks=vultr%20reality-grpc&path=grpc&obfs=grpc&tls=1&peer=addons.mozilla.org&pbk=t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA

vless://283a2513-e34b-4f3f-b70e-b2899c6e50ea@cn.azhz.eu.org:443?encryption=none&security=tls&type=ws&host=navy-changing-niagara-accessibility.trycloudflare.com&path=/argox-vl?ed=2048&sni=navy-changing-niagara-accessibility.trycloudflare.com#vultr-Vl

vmess://bm9uZToyODNhMjUxMy1lMzRiLTRmM2YtYjcwZS1iMjg5OWM2ZTUwZWFAY24uYXpoei5ldS5vcmc6NDQz?remarks=vultr-Vm&obfsParam=navy-changing-niagara-accessibility.trycloudflare.com&path=/argox-vm?ed=2048&obfs=websocket&tls=1&peer=navy-changing-niagara-accessibility.trycloudflare.com&alterId=0

trojan://283a2513-e34b-4f3f-b70e-b2899c6e50ea@cn.azhz.eu.org:443?peer=navy-changing-niagara-accessibility.trycloudflare.com&plugin=obfs-local;obfs=websocket;obfs-host=navy-changing-niagara-accessibility.trycloudflare.com;obfs-uri=/argox-tr?ed=2048#vultr-Tr

*******************************************
┌────────────────┐
│                │
│   Clash Meta   │
│                │
└────────────────┘
----------------------------

  - {name: "vultr reality-vision", type: vless, server: 45.76.175.238, port: 27195, uuid: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, network: tcp, udp: true, tls: true, servername: addons.mozilla.org, flow: xtls-rprx-vision, client-fingerprint: chrome, reality-opts: {public-key: t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA, short-id: ""} }

  - {name: "vultr reality-grpc", type: vless, server: 45.76.175.238, port: 27195, uuid: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, network: grpc, udp: true, tls: true, servername: addons.mozilla.org, flow: , client-fingerprint: chrome, reality-opts: {public-key: t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA, short-id: ""}, grpc-opts: {grpc-service-name: "grpc"} }

  - {name: "vultr-Vl", type: vless, server: cn.azhz.eu.org, port: 443, uuid: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, udp: true, tls: true, servername: navy-changing-niagara-accessibility.trycloudflare.com, skip-cert-verify: false, network: ws, ws-opts: {path: "/argox-vl", headers: {Host: navy-changing-niagara-accessibility.trycloudflare.com}, "max_early_data":2408, "early_data_header_name":"Sec-WebSocket-Protocol"} }

  - {name: "vultr-Vm", type: vmess, server: cn.azhz.eu.org, port: 443, uuid: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, udp: true, alterId: 0, cipher: none, tls: true, servername: navy-changing-niagara-accessibility.trycloudflare.com, skip-cert-verify: true, network: ws, ws-opts: {path: "/argox-vm", headers: {Host: navy-changing-niagara-accessibility.trycloudflare.com}, "max_early_data":2408, "early_data_header_name":"Sec-WebSocket-Protocol"}}

  - {name: "vultr-Tr", type: trojan, server: cn.azhz.eu.org, port: 443, password: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, udp: true, tls: true, servername: navy-changing-niagara-accessibility.trycloudflare.com, sni: navy-changing-niagara-accessibility.trycloudflare.com, skip-cert-verify: false, network: ws, ws-opts: { path: "/argox-tr", headers: {Host: navy-changing-niagara-accessibility.trycloudflare.com}, "max_early_data":2408, "early_data_header_name":"Sec-WebSocket-Protocol" } }

  - {name: "vultr-Sh", type: ss, server: cn.azhz.eu.org, port: 443, cipher: chacha20-ietf-poly1305, password: 283a2513-e34b-4f3f-b70e-b2899c6e50ea, udp: true, plugin: v2ray-plugin, plugin-opts: { mode: websocket, host: navy-changing-niagara-accessibility.trycloudflare.com, path: "/argox-sh", tls: true, servername: navy-changing-niagara-accessibility.trycloudflare.com, skip-cert-verify: false, mux: false } }

*******************************************
┌────────────────┐
│                │
│    Sing-box    │
│                │
└────────────────┘
----------------------------

{
  "outbounds": [
    {
      "type": "vless",
      "tag": "vultr reality-vision",
      "server": "45.76.175.238",
      "server_port": 27195,
      "uuid": "283a2513-e34b-4f3f-b70e-b2899c6e50ea",
      "flow": "xtls-rprx-vision",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "addons.mozilla.org",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA",
          "short_id": ""
        }
      }
    },
    {
      "type": "vless",
      "tag": "vultr reality-grpc",
      "server": "45.76.175.238",
      "server_port": 27195,
      "uuid": "283a2513-e34b-4f3f-b70e-b2899c6e50ea",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "server_name": "addons.mozilla.org",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "t_EJFRVuwcnriK44upPpNxer8PxHWSL5AuHCcLIWokA",
          "short_id": ""
        }
      },
      "transport": {
        "type": "grpc",
        "service_name": "grpc"
      }
    },
    {
      "type": "vless",
      "tag": "vultr-Vl",
      "server": "cn.azhz.eu.org",
      "server_port": 443,
      "uuid": "283a2513-e34b-4f3f-b70e-b2899c6e50ea",
      "tls": {
        "enabled": true,
        "server_name": "navy-changing-niagara-accessibility.trycloudflare.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "/argox-vl",
        "headers": {
          "Host": "navy-changing-niagara-accessibility.trycloudflare.com"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    },
    {
      "type": "vmess",
      "tag": "vultr-Vm",
      "server": "cn.azhz.eu.org",
      "server_port": 443,
      "uuid": "283a2513-e34b-4f3f-b70e-b2899c6e50ea",
      "tls": {
        "enabled": true,
        "server_name": "navy-changing-niagara-accessibility.trycloudflare.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "/argox-vm",
        "headers": {
          "Host": "navy-changing-niagara-accessibility.trycloudflare.com"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    },
    {
      "type": "trojan",
      "tag": "vultr-Tr",
      "server": "cn.azhz.eu.org",
      "server_port": 443,
      "password": "283a2513-e34b-4f3f-b70e-b2899c6e50ea",
      "tls": {
        "enabled": true,
        "server_name": "navy-changing-niagara-accessibility.trycloudflare.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "transport": {
        "type": "ws",
        "path": "/argox-tr",
        "headers": {
          "Host": "navy-changing-niagara-accessibility.trycloudflare.com"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    }
  ]
}

 完整模板可参照:
 https://t.me/ztvps/67
 https://github.com/chika0801/sing-box-examples/tree/main/Tun


*******************************************

Index:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/

QR code:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/qr

V2rayN / Nekoray 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/base64

Clash 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/clash

sing-box for pc 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/sing-box-pc

sing-box for cellphone 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/sing-box-phone

Shadowrocket 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/shadowrocket

*******************************************

 自适应 Clash / V2rayN / NekoBox / ShadowRocket / SFI / SFA / SFM 客户端:
模版:
https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/auto

 订阅 QRcode:
模版:
https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://navy-changing-niagara-accessibility.trycloudflare.com/283a2513-e34b-4f3f-b70e-b2899c6e50ea/auto

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀ ▄ ▀▀▄ ▄▀ ▄▀▄▀▀▀▀  ██ ▄▄▄▄▄ █
█ █   █ █▀ █▄▀▄▀▀▄██▄▀█▀▄█▀█▀ █ █   █ █
█ █▄▄▄█ █▀█▀██▀  ▀▀▀██▄ ▄ ▀ ▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█▄▀▄█▄█▄█▄▀ ▀ ▀▄█▄█▄█▄▄▄▄▄▄▄█
█   ▄ ▀▄  ▄▄██▄█▄ █▄▀▄  █▀▄▀ ▄▄█ ▀▄█▄▀█
██ ▄▄█▄▄▀▀█▄▀█▄▀▄▄▄▄▀▄▀▄ █▄▄▄▀▄▄▀▄▀▄▀▄█
█ ▀ ▀▀ ▄▄  ██▀▄█▄█▄▄██ ▄▀ █ ▄█ ▄▄█▀▄▄ █
██ █ █▄▄▀▄▄▀▀▄ ▀▄▀   ▄▀▄▀█▄ ▄ ▄▄▀▄▀  ▄█
█▀▀▀▄▄▄▄▀█▄▀▀███  ██▀█▀▄█▄▄▀ ▄▀▀█▀ ▄▄ █
█▀▄█▀ █▄█▀▄    ▀██▄▀▀▄█▄▀█▄ ▄▀▄▄▀▄▄  ▄█
█▀▀██▄ ▄█  ██▀█▀▄▀██▀  ▄▀▄▄▀▄ ▄█▄▄▀▄▄ █
█▄ ████▄█▄█▄▀▄ ▀▄▀▄▄ █▀▄   ▄▄▀▄▄▀▄▄ ███
█ █▀▄█▀▄██▄▀███▀▄▄▄▄█  ▀█▀█▀ ▄ ▄ ▀█▄ ▄█
█ ██▀▀▀▄▄ ▄▄▀▄▄▄▄▄▄▄ ▀▀  █▄▄▄▀█▄█▄▄ ▄▄█
█▄█▄█▄▄▄█▀▄▀█ ▄▀▄▀█▀▀ ▀██▄▄█▄ ▄▄▄ ▄▄▄ █
█ ▄▄▄▄▄ █▄▀█▀▀▄▀▄▀▄▀ ▀▀▄▀█ ▄  █▄█  ▄▄▄█
█ █   █ █ ▄ ██▄▄ ▀▄ ▀▄  █▀█▀▀  ▄ ▄██▀▀█
█ █▄▄▄█ █  ▄▀▀▄▄▄▄  ▀▀██ ▄ ▄▀▀  ▀ █▄▀▄█
█▄▄▄▄▄▄▄█▄▄████▄▄▄█████▄█▄█▄█▄██▄█▄▄▄▄█


*******************************************

 临时隧道域名可以从以下网站获取: http://45.76.175.238:3333/quicktunnel 


 脚本当天运行次数: 75，累计运行次数: 197183 


 创建快捷 [ argox ] 指令成功! 


root@vultr:~#

**Comment by SorataKasugano** [comment]
![image](https://github.com/Alvin9999/new-pac/assets/19202656/c1175b87-49b3-4875-9810-01db1c7ca6a7)

**Comment by Alvin9999** [comment]
确实你的端口没有通，应该是没成功。
你把脚本卸载了，用这个脚本来安装试试
bash <(curl -Ls https://gitlab.com/rwkgyg/sing-box-yg/raw/main/sb.sh)

**Comment by SorataKasugano** [comment]
可以了，感谢

**Comment by Alvin9999** [comment]
教程更新了，你可以看下【可选操作】那一部分，可以多一个自动套cf cdn的节点。

**Comment by SorataKasugano** [comment]
OK，看到了
