### ISSUE TITLE
Hysteria2服务器这几天连不上

### ISSUE THREAD

**Issue by quan9364** [Alvin9999/new-pac#1624]
104.192.224.140:40391这个服务器前两天开始连不上了，请大佬维护下哦，谢谢

**Comment by Alvin9999** [comment]
已更新。

**Comment by quan9364** [comment]
Thanks, it worksJackySent from my iPhoneOn May 26, 2024, at 09:58, 自由上网 ***@***.***> wrote:﻿
已更新。
