### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by guoxiaojiewsry** [Alvin9999/new-pac#1625]
Chrome125_warp-plus_2024.5.29
这个真的很棒，能上国内的网站了。

**Comment by Alvin9999** [comment]
好的

**Comment by LOONG-ZY** [comment]
> 好的
您好大佬，为什么使用自由上网谷歌浏览器不能访问chatgpt

**Comment by Alvin9999** [comment]
@LOONG-ZY 有的工具，有的ip可以，这个需要你自己尝试
