### ISSUE TITLE
关于提供的谷歌翻墙浏览器高内核版问题

### ISSUE THREAD

**Issue by IceSnowWolf** [Alvin9999/new-pac#1626]
虽然提供了免费浏览器的上网方式，但还是对于实现的思路有点好奇。可以请教一下吗
1.这种方式还是需要有人在国外购买Vps服务器，只不过是把Vps服务器提供出来免费使用。另外，还是需要在购买的Vps服务器上进行类似以下操作：
```
- 第一步：购买VPS服务器
- 第二步：一键部署VPS服务器
- 第三步：一键加速VPS服务器
```
2.执行脚本之后（例:2.Xray翻墙.cmd）,脚本执行以下操作：
- 执行Xray目录下的xray.exe。（※这一步是在本地创建代理吗，不想创建本地代理，通过浏览器直接访问Vps服务器应该怎么操作）
- 启动chrome浏览器

**Comment by IceSnowWolf** [comment]
非常感谢，这些资料都看过了。
有xray.exe的源码或者如何实现的相关资料吗，对于这部分具体咋实现的本地代理，不太清楚。

**Comment by bannedbook** [comment]
浏览器直接访问Vps服务器 ，这个行不通，不可能的

xray.exe的源码
https://github.com/XTLS/Xray-core

**Comment by IceSnowWolf** [comment]
**需求：代理窗口后台运行**
因为不想要代理窗口一直保持在任务栏
**版本**
谷歌高内核Quick版（额外确认点：这个版本的代理工具是用的clash.meta吗，源码地址是：https://github.com/clash-verge-rev/clash-verge-rev.git吗，因为看他俩的配置文件是一样的）
**问题**
因为看过V2Ray提供了后台运行版本的exe执行文件，想知道Quick.exe怎么后台执行，或者怎么编译后台执行文件

**Comment by IceSnowWolf** [comment]
**需求：代理窗口后台运行**
因为不想要代理窗口一直保持在任务栏
**版本**
谷歌高内核Quick版（额外确认点：这个版本的代理工具是用的clash.meta吗，源码地址是：https://github.com/clash-verge-rev/clash-verge-rev.git吗，因为看他俩的配置文件是一样的）
**问题**
因为看过V2Ray提供了后台运行版本的exe执行文件，想知道Quick.exe怎么后台执行，或者怎么编译后台执行文件
