### ISSUE TITLE
请问V2RAY脚本tls自动申请的证书在哪？

### ISSUE THREAD

**Issue by qun-qq** [Alvin9999/new-pac#1627]
保存的具体位置

**Comment by Alvin9999** [comment]
参考这个：
https://github.com/Jrohy/multi-v2ray/issues/104

**Comment by qun-qq** [comment]
> 参考这个： [Jrohy/multi-v2ray#104](https://github.com/Jrohy/multi-v2ray/issues/104)

感谢 :)

**Comment by Nezambaloc** [comment]
v2rayN/v2rayN/Handler/CoreConfig/CoreConfigV2ray.cs
