### ISSUE TITLE
用家里wifi连不上，但是用是手机热点可以是为什么

### ISSUE THREAD

**Issue by applepies000** [Alvin9999/new-pac#1628]
wifi办的是移动家的,用的vultr服务器套的SSR+TLS+CADDY，用手机热点就可以正常上网，最近才出现这个情况，是移动屏蔽了么？

**Comment by Alvin9999** [comment]
有可能。你可以在原来的vps服务器上再搭建几个其它的翻墙服务，一般来说，只要端口不同就可以共存。比如v2ray、hysteria等，可以用这个[一键搭建多个协议节点教程](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)

**Comment by skyformat99** [comment]
> 有可能。你可以在原来的vps服务器上再搭建几个其它的翻墙服务，一般来说，只要端口不同就可以共存。比如v2ray、hysteria等，可以用这个[一键搭建多个协议节点教程](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)

可以出个万能的exe吗？ 自动获取地址，自动选择协议

**Comment by skyformat99** [comment]
> > 有可能。你可以在原来的vps服务器上再搭建几个其它的翻墙服务，一般来说，只要端口不同就可以共存。比如v2ray、hysteria等，可以用这个[一键搭建多个协议节点教程](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)
> 
> 可以出个万能的exe吗？ 自动获取地址，自动选择协议
