### ISSUE TITLE
Mac 显示有网速  但是连不上

### ISSUE THREAD

**Issue by zpzzz** [Alvin9999/new-pac#1629]
Mac系统试了前两种方法都不行的,提供的地址用软件测速显示的是有.但是谷歌都连不上去.是什么原因?
<img width="194" alt="截屏2024-06-11 14 06 57" src="https://github.com/Alvin9999/new-pac/assets/13012495/bdbca86a-cf66-45db-a93f-623401e440f5">

**Comment by Alvin9999** [comment]
看一下你的账号信息是填写的什么？

**Comment by zpzzz** [comment]
是这个吗?连接网站的话是秒失败的.哪里的原因?

**Comment by zpzzz** [comment]
图片也传不上去了.提示  (网址)  意外终止了连接

**Comment by zpzzz** [comment]
<img width="328" alt="截屏2024-06-12 11 54 19" src="https://github.com/Alvin9999/new-pac/assets/13012495/3ab78ab4-e656-46f6-b79e-84f28a682649">
账号是没问题的吧?   图片开了vpn都传不上去...
<img width="755" alt="截屏2024-06-12 11 55 33" src="https://github.com/Alvin9999/new-pac/assets/13012495/8c2ba644-71e2-4f22-8f91-61c81bb1796e">

**Comment by Alvin9999** [comment]
账号没问题。你试试全局代理，或者浏览器代理那里设置成HTTP 127.0.0.1 1080

**Comment by zpzzz** [comment]
全局模式也不行.浏览器代理在哪里设置?

**Comment by Alvin9999** [comment]
可以网上搜一下Mac浏览器代理设置。
如果还不行的话，试试v2ray免费账号。

**Comment by zpzzz** [comment]
v2ray已经试了,不行.
这样改了也不行
<img width="503" alt="截屏2024-06-12 13 31 31" src="https://github.com/Alvin9999/new-pac/assets/13012495/e9b4fa0d-01a2-4b29-8725-ef44347fb1c8">

**Comment by Alvin9999** [comment]
电脑关闭所有安全卫士、杀毒软件、防火墙后试试

**Comment by Alvin9999** [comment]
账号是没有问题的，因为有很多人正在使用。
