### ISSUE TITLE
能全局翻墙吗？

### ISSUE THREAD

**Issue by xinjianzhanghao** [Alvin9999/new-pac#1631]
请问用您的1.clash.meta翻墙.cmd可以全局翻墙吗？或用您所提供的动态网地址有可以全局翻墙得的方式吗？我没有可以用的服务器。

**Comment by xinjianzhanghao** [comment]
我之前使用warp和warp+的，现在连不上了，不知道为啥

**Comment by xinjianzhanghao** [comment]
还有您的Chrome按下 `Ctrl+w` 应该关闭界面，不是回到主页。

**Comment by Alvin9999** [comment]
> 请问用您的1.clash.meta翻墙.cmd可以全局翻墙吗？或用您所提供的动态网地址有可以全局翻墙得的方式吗？我没有可以用的服务器。

翻墙浏览器没法全局代理，不是VPN。

**Comment by Alvin9999** [comment]
warp的翻墙原理是wireguard协议，你如果要用全局代理，可以根据教程自己搭建服务器，[自建WireGuard VPN服务器服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAWireGuard-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by xinjianzhanghao** [comment]
> warp的翻墙原理是wireguard协议，你如果要用全局代理，可以根据教程自己搭建服务器，[自建WireGuard VPN服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAWireGuard-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

如果不自建代理，就没有办法让别的浏览器共享翻墙环境，是这样吗？有没有通过设置代理的方式就可以全局？
