### ISSUE TITLE
登录google账号后无法访问外网

### ISSUE THREAD

**Issue by haerker** [Alvin9999/new-pac#1634]
重新下载了最新版Chrome126_AllNew，解压路径全英文，使用.clash.meta翻墙，正常没问题，但每次一旦我登录google账号后，外网都进不去了。大佬怎么解决

**Comment by Alvin9999** [comment]
clash.meta提示的是什么？截图看看

**Comment by haerker** [comment]
![111111-06-21_20-45-24](https://github.com/Alvin9999/new-pac/assets/64599799/84b604f5-d3de-4183-a5fc-d2c267790f3b)

**Comment by Alvin9999** [comment]
这个截图看不出clash.meta有什么问题。如果实在用不了，可以换其它工具。

**Comment by Alvin9999** [comment]
关于谷歌学术，推荐用clash.meta ip5、ip6，xray ip1，singbox ip2

**Comment by haerker** [comment]
大佬，当我刚点击后，clash.meta只有两三行正确的日志，然后日志就不动了，
![222222-57-32](https://github.com/Alvin9999/new-pac/assets/64599799/aab68ee2-d547-4a92-bfc4-ce70e7e067ef)
网络也访问不了

**Comment by Alvin9999** [comment]
关闭电脑的所有国产杀毒软件、安全卫士，尤其是360、腾讯管家、金山等软件。

**Comment by Alvin9999** [comment]
现在弄好了吗

**Comment by haerker** [comment]
没有，除了clash其他都用不了，用了clash又不能登录google账号。

**Comment by Alvin9999** [comment]
电脑是什么系统？用的哪款版本？

**Comment by haerker** [comment]
电脑是win11专业版，用的chrome126Allnew最新版。前几天还是正常使用，因为电脑也不关机，昨天谷歌学术突然就用不了，然后重新启动clash，啥都用不了了，最后下载了最新版，啥都能用，登录google账号后还是啥都用不

**Comment by haerker** [comment]
大佬 我明白了，我登录google后开启同步，账号里面的插件冲突了，删除后一切正常，这也解释了上面为什么只有两三条正常log。打扰了 感谢

**Comment by Alvin9999** [comment]
好的，能用就好。
