### ISSUE TITLE
大佬 配置好后服务器无速度不可用 求解答

### ISSUE THREAD

**Issue by Sam-dog** [Alvin9999/new-pac#1635]
![屏幕截图 2024-06-22 232517](https://github.com/Alvin9999/new-pac/assets/110272037/7d294766-8367-46b7-936f-3b235980b2a3)

**Comment by Alvin9999** [comment]
用最新的v2ray账号
https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by Sam-dog** [comment]
远程服务器返回错误（503）服务器不可用
![屏幕截图 2024-06-22 233728](https://github.com/Alvin9999/new-pac/assets/110272037/8e4083da-b40f-4df3-931e-572c28177ba3)

**Comment by Alvin9999** [comment]
你打开这个账号的详细配置，我看一下具体账号是怎么填写的

**Comment by Alvin9999** [comment]
另外你的v2rayN客户端版本有点旧了，可以更新一下

**Comment by Alvin9999** [comment]
现在v2rayN都是2024年的版本，你的是2020年的版本。

**Comment by Sam-dog** [comment]
是这样的
![Uploading 屏幕截图 2024-06-22 234333.png…]()

**Comment by Alvin9999** [comment]
图片看不到

**Comment by Sam-dog** [comment]
![Uploading 屏幕截图 2024-06-22 234333.png…]()

**Comment by Alvin9999** [comment]
仍然看不到

**Comment by Alvin9999** [comment]
你用这个版本
windows v2rayN 6.23客户端 文件名称：v2rayN-With-Core.zip

[下载地址1](https://d2.freessr2.xyz/v2rayN-With-Core.zip) [下载地址2](https://d.dtku35.xyz/v2rayN-With-Core.zip) [下载地址3](https://free.zhujicn2.net/v2rayN-With-Core.zip) [github最新版下载](https://github.com/2dust/v2rayN/releases/latest) (下载带core的文件)

**Comment by Sam-dog** [comment]
连接超时，邮箱发你 








---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月22日 23:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [Alvin9999/new-pac] 大佬 配置好后服务器无速度不可用 求解答 (Issue #1635) |

仍然看不到

**Comment by Sam-dog** [comment]
![屏幕截图 2024-06-22 234333](https://github.com/Alvin9999/new-pac/assets/110272037/4c3343e8-0cab-4939-a275-36b09fa32c52)

**Comment by Alvin9999** [comment]
账号没有问题，可能是你的v2rayN客户端版本太低了。

**Comment by Sam-dog** [comment]
嗯，我更新一下

**Comment by Sam-dog** [comment]
![屏幕截图 2024-06-23 000638](https://github.com/Alvin9999/new-pac/assets/110272037/aacc3cec-e5b0-40e1-88c6-b989852dde6f)
能用了，谢谢大佬

**Comment by Alvin9999** [comment]
好的，能用就好。

**Comment by PandaFiredoge** [comment]
> ![屏幕截图 2024-06-22 232517](https://private-user-images.githubusercontent.com/110272037/341980324-7d294766-8367-46b7-936f-3b235980b2a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTA1MzgsIm5iZiI6MTcxOTQxMDIzOCwicGF0aCI6Ii8xMTAyNzIwMzcvMzQxOTgwMzI0LTdkMjk0NzY2LTgzNjctNDZiNy05MzZmLTNiMjM1OTgwYjJhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMzU3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmM4ZWU5NzcyZjFmNDkwNzQ1YzJiMGM3MWQ0ODUyZmY3YzA5ZDllZGM4MWJkNjgxMGJlOGY0ZDQ4YWMwMzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BxZ3wmBs0KlvDFa5QWj1Y_YNo36VKA1hafKOfJxU6ak)

选中节点之后要敲回车……
