### ISSUE TITLE
谷歌无法访问vimeo，提示ERR_CERT_COMMON_NAME_INVALID。求助求助

### ISSUE THREAD

**Issue by shuuki1234** [Alvin9999/new-pac#1637]

**Comment by Alvin9999** [comment]
用的什么工具？自己搭建的？

**Comment by shuuki1234** [comment]
就直接谷歌访问 vimeo.com提示以上报错（技术小白，就是遇到了这么个问题，不知道咋解决，求助）
![WeChata56be204f25ad38b41280ee938ac566c](https://github.com/Alvin9999/new-pac/assets/173891440/9e280bba-af15-4f21-942f-d4b36a2b0c7e)

**Comment by Alvin9999** [comment]
用的什么翻墙工具？

**Comment by shuuki1234** [comment]
不是第三方工具，是在合法授权的证书下可访问外网

**Comment by Alvin9999** [comment]
你的电脑是什么系统？怎么翻墙的？

**Comment by shuuki1234** [comment]
Mac; 所连接的Wi-Fi就可直接访问谷歌这些

**Comment by Alvin9999** [comment]
有可能是网站本身的限制。

**Comment by shuuki1234** [comment]
那就是只能过段时间再试试看了对吧

**Comment by Alvin9999** [comment]
嗯。为什么你的网络可以直接访问外网？特定网络还是路由器翻墙？

**Comment by shuuki1234** [comment]
应该是属于特定网络

**Comment by Alvin9999** [comment]
喔。也可以试试用翻墙软件来访问，翻墙软件的数据是加密的，相对而言要安全一些。

**Comment by Alvin9999** [comment]
特定网络的话，有可能特定网络本身的源头就屏蔽了你要访问的网站。

**Comment by shuuki1234** [comment]
刚刚又试了一下，突然好了，可以访问了

**Comment by shuuki1234** [comment]
谢谢你的解答：）

**Comment by Alvin9999** [comment]
好的。
