### ISSUE TITLE
请问一下关于2024.7.3新增的YouTube视频下载插件

### ISSUE THREAD

**Issue by whgmqs2024** [Alvin9999/new-pac#1638]
7月3日的更新，我下载了这三个  Chrome126_AllNew_2024.7.3.7z   ，Supermium122_AllNew_2024.7.3.7z   ，Firefox52_AllNew_2024.7.3.7z    ，但是发现只有最后那个在打开youtube网站的视频时有绿色Download按钮，前面两个都没有啊，可以增加进去吗

**Comment by Alvin9999** [comment]
都有。

**Comment by Alvin9999** [comment]
打开视频后要等几秒钟才会显示出来。

**Comment by Alvin9999** [comment]
有人反馈，下载YouTube视频时不要登录自己的YouTube账号，登录账号后无法正常下载。

**Comment by Alvin9999** [comment]
也有其他人反馈这个问题，还在研究中。

**Comment by whgmqs2024** [comment]
我并没有登录我的YouTube账号，打开YouTube视频的时候就只有 Firefox52_AllNew_2024.7.3.7z  出来了绿色Download按钮。

**Comment by Alvin9999** [comment]
目前看是谷歌浏览器屏蔽了下载youtube视频的插件，发布的时候是有安装这个插件的。所以目前只有火狐浏览器是正常的。

**Comment by whgmqs2024** [comment]
反馈一下，北京时间2024.7.10上午10：00的情况：Firefox52_AllNew_2024.7.3.7z   打开youtube网站的视频时，有绿色Download按钮，但是点击后，无法下载视频（前几天试过是可以下载的），有个弹出窗口，提示：An error occurred from remote video site. Please try with other download link.

**Comment by Alvin9999** [comment]
> 反馈一下，北京时间2024.7.10上午10：00的情况：Firefox52_AllNew_2024.7.3.7z 打开youtube网站的视频时，有绿色Download按钮，但是点击后，无法下载视频（前几天试过是可以下载的），有个弹出窗口，提示：An error occurred from remote video site. Please try with other download link.

下载视频时登录youtube或谷歌账号了吗？

**Comment by whgmqs2024** [comment]
没有，一直都没有登录youtube或谷歌账号

**Comment by whgmqs2024** [comment]
我贴个图。一直都没有登录youtube或谷歌账号。绿色Download按钮会出来，但是点了之后，现在下不了视频（前几天可以），firefox 会自动打开一个新窗口，提示 An error occurred from remote video site. Please try with other download link.

![2024-07-10_095719](https://github.com/Alvin9999/new-pac/assets/174496288/ba99792e-ad17-4a71-b4a6-4551e2e60b8f)

**Comment by whgmqs2024** [comment]
> 那这个插件也太不稳定了。考虑放弃它了。

辛苦了

**Comment by Alvin9999** [comment]
用这个在线网址来下载，刚增加了几个地址
https://github.com/Alvin9999/new-pac/wiki/YouTube%E4%B8%8B%E8%BD%BD1080%E6%95%99%E7%A8%8B

**Comment by whgmqs2024** [comment]
> 用这个在线网址来下载，刚增加了几个地址 https://github.com/Alvin9999/new-pac/wiki/YouTube%E4%B8%8B%E8%BD%BD1080%E6%95%99%E7%A8%8B

谢谢，测试了用这些网站下载youtube的视频，清晰度选择1080p及以下就没发现什么问题，但是选择1440p或4K的清晰度就转换很慢或者下载不成功，不过总比下不了要强

**Comment by Alvin9999** [comment]
网站7应该可以下载2k视频

**Comment by whgmqs2024** [comment]
> 网站7应该可以下载2k视频

不行，刚刚测试了两个youtube的视频，一个是最高清晰度1440p，另一个是最高清晰度2160p但是也提供1440p的清晰度，结果是完全一样的，如下图，网址粘贴进去后，蓝色箭头指着的那个地方小方格就从左到右，周而复始，等了半个小时也还是这样，然后试着点红底白字的“开始”也没任何反应

![2024-07-11_225932](https://github.com/Alvin9999/new-pac/assets/174496288/f1a46b65-c20b-4727-b2f3-08901297940c)

**Comment by Alvin9999** [comment]
好
