### ISSUE TITLE
SSR升级后是否需要重新部署？

### ISSUE THREAD

**Issue by canalist** [Alvin9999/new-pac#164]
版主您好，您的教程非常实用，谢谢！

有一个问题：如果SSR升级，比如从现在的4.7.0升到4.8.0，服务端是否一定也做出了修改？如果也做出了修改，是不是就该重新部署呢？如果重新部署，具体怎么操作？

烦请版主赐教。

**Comment by Alvin9999** [comment]
不用

**Comment by canalist** [comment]
感谢回复！虽然不明白为什么服务端不需要手动更新。。。

**Comment by Alvin9999** [comment]
服务端只是相当于中转。只要客户端和服务器之间的通信没问题就可以连接，比如你在部署了SSR 端口、密码、协议、混淆之类的，那么只要客户端填的信息和服务端一致，那么服务端就能识别，只要识别就可以翻墙了。

流程图：自己的网络——SSR客户端——SSR服务端——vps服务器——借助于vps服务器当地网络访问国外网站。

**Comment by Jason-Fly** [comment]
win端c sharp版有4.8版了吗？
