### ISSUE TITLE
chrome崩溃

### ISSUE THREAD

**Issue by benqqsun** [Alvin9999/new-pac#1640]
![屏幕截图 2024-07-07 104534](https://github.com/Alvin9999/new-pac/assets/150105036/7ad6bee2-8008-4563-b7d1-dc538c62e2da)
这个是Chrome126_AllNew_2024.7.3版本的。操作系统是win10。之前的两个版本也是这个情况。
请教大家如何解决。

**Comment by Alvin9999** [comment]
你试试把文件放在C盘一级目录后，再解压试试看。如果还不行，试试superminum版浏览器。

**Comment by Alvin9999** [comment]
如果有国产杀毒软件和安全卫士，请先关闭它们。
