### ISSUE TITLE
佬看看我这啥问题，咋解决，谢谢

### ISSUE THREAD

**Issue by shelter-lin** [Alvin9999/new-pac#1643]
![屏幕截图 2024-07-11 234439](https://github.com/Alvin9999/new-pac/assets/175334865/6d808e9b-b534-4f57-9698-d3815cf308fc)

**Comment by Alvin9999** [comment]
文件要先全部解压出来

**Comment by Alvin9999** [comment]
如果已经全部解压了出来，就要把杀毒软件和安全卫士关闭，然后重新解压。因为提示的是找到不到这个quikc.exe文件
