### ISSUE TITLE
牛逼真的能用

### ISSUE THREAD

**Issue by Pentacle038** [Alvin9999/new-pac#1644]

**Comment by skyformat99** [comment]
比较慢啊

**Comment by Alvin9999** [comment]
> 比较慢啊

用的什么软件？

**Comment by Pentacle038** [comment]
> 比较慢啊

我用的浏览器插件那个，很快

**Comment by Alvin9999** [comment]
可以优选选择hysteria、singbox、naiveproxy、hysteria2、juicity

**Comment by skyformat99** [comment]
> > 比较慢啊
> 
> 我用的浏览器插件那个，很快

哪个插件啊？？

**Comment by Pentacle038** [comment]
> > > 比较慢啊
> > 
> > 
> > 我用的浏览器插件那个，很快
> 
> 哪个插件啊？？

几个线路更新一下ip都能用

**Comment by skyformat99** [comment]
> > > > 比较慢啊
> > > 
> > > 
> > > 我用的浏览器插件那个，很快
> > 
> > 
> > 哪个插件啊？？
> 
> 几个线路更新一下ip都能用

用的哪个啊？  只想用用免费的那些

**Comment by Pentacle038** [comment]
> > > > > 比较慢啊
> > > > 
> > > > 
> > > > 我用的浏览器插件那个，很快
> > > 
> > > 
> > > 哪个插件啊？？
> > 
> > 
> > 几个线路更新一下ip都能用
> 
> 用的哪个啊？ 只想用用免费的那些

谷歌翻墙浏览器高内核版 这个

**Comment by kksfz** [comment]
> > 比较慢啊
> 
> 我用的浏览器插件那个，很快

不过那个谷歌浏览器版本有点低呀，而且首页导航一堆逆天玩意儿啊

**Comment by Alvin9999** [comment]
@kksfz Chrome126版本不低了

**Comment by kksfz** [comment]
@Alvin9999 我超，哥，我开玩笑的，你不会要暗鲨我吧。你的项目很好，导航内容都是小问题，放过我，呜呜呜

**Comment by Alvin9999** [comment]
@kksfz 你很幽默。翻墙出来后可以多看看，多了解了解外面的世界。

**Comment by Pentacle038** [comment]
> @Alvin9999 我超，哥，我开玩笑的，你不会要暗鲨我吧。你的项目很好，导航内容都是小问题，放过我，呜呜呜

什么情况😳😳
