### ISSUE TITLE
hysteria 2 不能用

### ISSUE THREAD

**Issue by quan9364** [Alvin9999/new-pac#1647]
server": "208.87.243.123:41680,40000-50000"

这个又挂了

**Comment by Alvin9999** [comment]
已更新。

**Comment by quan9364** [comment]
108.181.24.39又挂了

**Comment by Alvin9999** [comment]
> 108.181.24.39又挂了

被封了，已更新

**Comment by quan9364** [comment]
![IMG_3155](https://github.com/user-attachments/assets/26925547-f46e-4523-a476-26e6c982ada8)
请问最新的hys2配置obfs部分要如何填在shadowrocket里呀

**Comment by Alvin9999** [comment]
obfuscation那一栏填写混淆密码，目前密码是dongtaiwang.com

**Comment by quan9364** [comment]
搞定了，好人一生平安Sent from my iPhoneOn Jul 22, 2024, at 23:07, 自由上网 ***@***.***> wrote:﻿
obfuscation那一栏填写混淆密码，目前密码是dongtaiwang.com

**Comment by quan9364** [comment]
207.90.239.157:22334这个好像又挂了Sent from my iPhoneOn Jul 23, 2024, at 07:52, quan9361 ***@***.***> wrote:﻿搞定了，好人一生平安Sent from my iPhoneOn Jul 22, 2024, at 23:07, 自由上网 ***@***.***> wrote:﻿
obfuscation那一栏填写混淆密码，目前密码是dongtaiwang.com

**Comment by Alvin9999** [comment]
刚看了，目前正常，没有挂。

**Comment by quan9364** [comment]
大佬，46.17.41.189挂了两天了，麻烦看看。谢谢





--
发自我的网易邮箱手机智能版



在 2024-07-27 23:39:29，"自由上网" ***@***.***> 写道：


刚看了，目前正常，没有挂。

**Comment by Alvin9999** [comment]
> 大佬，46.17.41.189挂了两天了，麻烦看看。谢谢
> […](#)
> -- 发自我的网易邮箱手机智能版 在 2024-07-27 23:39:29，"自由上网" ***@***.***> 写道： 刚看了，目前正常，没有挂。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

已更新。

**Comment by quan9364** [comment]
又挂了JackySent from my iPhoneOn Jan 13, 2025, at 00:27, 自由上网 ***@***.***> wrote:﻿

大佬，46.17.41.189挂了两天了，麻烦看看。谢谢
…
-- 发自我的网易邮箱手机智能版 在 2024-07-27 23:39:29，"自由上网" @.> 写道： 刚看了，目前正常，没有挂。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

已更新。

**Comment by Alvin9999** [comment]
已更新。

**Comment by quan9364** [comment]
大佬这个挂了Sent from my iPhoneOn Jan 28, 2025, at 08:20, 自由上网 ***@***.***> wrote:﻿
已更新。

**Comment by Alvin9999** [comment]
正常的。

**Comment by Alvin9999** [comment]
可能速度有点慢，已更新。

**Comment by quan9364** [comment]
可以用了，谢谢Sent from my iPhoneOn Mar 10, 2025, at 10:51, 自由上网 ***@***.***> wrote:﻿
  可能速度有点慢，已更新。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



Alvin9999 left a comment (Alvin9999/new-pac#1647)
可能速度有点慢，已更新。
