### ISSUE TITLE
求助求助

### ISSUE THREAD

**Issue by Gou-Mang-Prime** [Alvin9999/new-pac#1649]
如题，下载了作者的翻墙火狐浏览器后，使用hysteria翻墙这个程序，但是在脚本运行窗口Ctrl+c后并没有成功关停程序，即使重置网络再重启电脑也仍是翻墙状态，求问大佬该如何正确退出

**Comment by Alvin9999** [comment]
一般点击窗口右上角叉叉就可以啦。
你看下ie浏览器的代理设置，关闭它。
具体操作：
https://jingyan.baidu.com/article/647f0115e555bf7f2148a8be.html
