### ISSUE TITLE
一键翻墙浏览器之外不能用360极速+SS翻墙的问题

### ISSUE THREAD

**Issue by ekingling** [Alvin9999/new-pac#166]
很高兴能遇到一键翻墙浏览器，再次感谢作者~~在此之前我是一直用360极速+SS翻墙的，可是这个月开始新开了个联通账户（之前也是用的联通宽带也没重新布线）后，360极速+SS就一直翻不了墙，可是用这里的一键翻墙浏览器无论哪个版本都能轻松翻墙，况且同个网络下手机WiFi用SS也能翻墙成功啊，到底是什么原因？

**Comment by Alvin9999** [comment]
不要用360的产品，包括360安全卫生、360杀毒软件、360浏览器等。360产品会故意干扰用户翻墙。你的手机能用你的SS账号，说明你的SS账号本身没有问题，那么就是你的电脑的环境问题了。你可以自己做对比试验：你用ss账号+电脑其它浏览器翻墙，如果能成功，那么就是360浏览器的问题。

**Comment by ekingling** [comment]
（先说一点，没换账号之前所有都正常，SS搭配所有浏览器都能轻松翻墙）

我也试了电脑里的IE和115浏览器同样翻不了墙，后台360软件照样开着，同时打开这几个浏览器就只有你提供的一键翻墙可以用，这样看来应该不受360影响的，可现在偏偏电脑上不了手机却能，奇怪了

**Comment by Alvin9999** [comment]
是很奇怪。你用的SSR客户端还是SS客户端，不行的话可以配置一个SSR账号，然后用SSR客户端试试看。另外，不管你表面上看到是否有影响，都不建议翻墙时使用360安全卫生噢。
