### ISSUE TITLE
SSR打不开twitter

### ISSUE THREAD

**Issue by leemz3** [Alvin9999/new-pac#167]
奇怪，就这两天的问题，其他所有网站都能打开，唯独打不开推特，请问是怎么回事呀？SS能打开，但是SSR不能，你们的SSR没有这种问题吗？电信线路

**Comment by Alvin9999** [comment]
twitter可能会对某些代理方式进行限制。比如有的ip段访问量很大，那么twitter网站的防御机制可能会判定为机器人或者攻击，那么会屏蔽这部分ip的访问。

**Comment by chaipoqiang** [comment]
不是哦，手机能上，唯独pc端上不去

**Comment by Alvin9999** [comment]
@chaipoqiang 电脑用的同样的代理方式吗

**Comment by chaipoqiang** [comment]
已解决，谢谢




在2019年12月1日 09:10，自由上网<notifications@github.com> 写道：

@chaipoqiang 电脑用的同样的代理方式吗
