### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by pxyxhy** [Alvin9999/new-pac#1673]
为什么推荐的媒体会有法轮教这些啊？

**Comment by Alvin9999** [comment]
推荐的内容如果不感兴趣可以不看的。从个人角度，是希望大家能够了解一下真相，并非是党媒宣传的那样哦。

**Comment by pxyxhy** [comment]
好的，我或许并不认同你的观点，但我认为你的项目是个很厉害的项目，你本人也很厉害。

**Comment by Alvin9999** [comment]
好的，谢谢你的认可。欢迎分享给自己的好朋友。
