### ISSUE TITLE
使用PROSU安装ssr+tls+caddy时提示域名无法解析到当前VPS

### ISSUE THREAD

**Issue by 1713886391** [Alvin9999/new-pac#1675]
![image](https://github.com/user-attachments/assets/4482e0ec-f30c-4e43-a792-714b9037809b)
但我用的就是域名当主机，且可以登陆进去我也没有使用CDN。请教一下大佬这是什么问题？

**Comment by Alvin9999** [comment]
vps系统换一下试试，比如debian11

**Comment by Alvin9999** [comment]
软件换这个版本2.5.4试试
https://github.com/proxysu/ProxySU/releases/download/v2.5.4/ProxySU-v2.5.4.zip

**Comment by Alvin9999** [comment]
用这个版本https://github.com/proxysu/ProxySU/releases/download/v2.5.7/Release.zip

**Comment by Alvin9999** [comment]
教程已更新
https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91%E5%B7%A5%E5%85%B7ProxySU
