### ISSUE TITLE
大佬 为什么我的clash安装完一开始能用 再过了几天就得重装才能连上

### ISSUE THREAD

**Issue by only-jay0118** [Alvin9999/new-pac#1677]

**Comment by Alvin9999** [comment]
不是很懂哦。clash这款软件原作者没有维护了。

**Comment by only-jay0118** [comment]
大佬 我指的是你的软件中的clash😘

**Comment by only-jay0118** [comment]
大佬 我指的是你的软件中的clash😘

**Comment by Alvin9999** [comment]
软件不需要安装，解压后使用。如果你中途不可用，你可以更新一下ip，如果提示找不到某文件，那么多半是被你的电脑杀毒软件或者安全卫士把clash删除了，这个时候你需要把它加入到白名单，重新解压文件。
