### ISSUE TITLE
如何回退 在《vps解锁ChatGPT、Netflix等网站教程》中所使用的解锁脚本的方案一的操作？运行完之后VPS无法联网

### ISSUE THREAD

**Issue by Valkierja** [Alvin9999/new-pac#1679]
我这边用的不是常规代理方案， 可能导致了某种冲突， 在我运行完题目中所述脚本后，我这边VPS全机都无法出网，查看了一下解锁脚本里面做了混淆，想请教一下如何卸载或者回退解锁脚本中的方案一所作操作，谢谢！

**Comment by Alvin9999** [comment]
1、终止warp-go： kill -15 $(pgrep warp-go)

2、终止wgcf： systemctl stop wg-quick@wgcf

**Comment by Valkierja** [comment]
感谢秒回，已经使用上述命令解决，谢谢！
