### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zjsuperman1987** [Alvin9999/new-pac#1683]
自己搭建好了v2ray, 想请问是否有密码功能， 就是我用二维码 分享给他人后， 需要管理其他人的账号， 并且修改密码， 防止他们再次分享给另一些人。 我应该怎么做， 望回复

**Comment by Alvin9999** [comment]
防止不了。

**Comment by zjsuperman1987** [comment]
> 防止不了。

好滴，非常感谢。

**Comment by zjsuperman1987** [comment]
谢谢，大佬
