### ISSUE TITLE
搭完了挂上后访问国内的网站很慢

### ISSUE THREAD

**Issue by xiaoyiwei199** [Alvin9999/new-pac#1685]
不太清楚是怎么回事，访问外网内容还可以，挂上后电脑端钉钉就会掉线。手机端的话挂上后访问B站或者其他国内APP非常的慢，这个不可以像机场那样有智能判断吗？访问国内域名时不走代理。

**Comment by Alvin9999** [comment]
客户端用的什么软件？浏览器代理如何设置的？
