### ISSUE TITLE
手机端 SSR 连接后，google play 下载不了 app

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#1686]
点击下载，就一直在等待中，是哪里配置的不对吗，访问都没问题

**Comment by Alvin9999** [comment]
不清楚。可以试试ss或者v2ray看看

**Comment by sujieico0** [comment]
是谷歌play自己的bug，你在通知栏提示下载的通知消失的时候，断开vpn，然后继续下载就能安装。

我不确定一定是这个原因，但是我有类似的问题就这么解决了。
