### ISSUE TITLE
翻網真是辛苦...太感謝作者的辛苦

### ISSUE THREAD

**Issue by colachen2017** [Alvin9999/new-pac#169]
請問 高內核 低內核是什麼意思
新手不懂 

再次感謝作者的努力  謝謝

**Comment by Alvin9999** [comment]
高内核版和低内核版都是针对谷歌浏览器来说的，我分享的是谷歌浏览器便携版，便携版的意思是不用安装，直接解压后就能使用。高内核版就是谷歌浏览器版本很高，同理，低内核版就是浏览器版本低一些。

低内核版适合xp、win7、win8、win10系统，高内核版不适合xp系统用，只适合win7、win8、win10系统。两种版本的翻墙方式都是一样的。

**Comment by colachen2017** [comment]
@Alvin9999 
多謝啦 ...我這裡  Chrome61_GP_Quic 能用，62新版反不可以用

**Comment by colachen2017** [comment]
多謝啦， 再請問 為什麼我的Ipv6打不開
是因為 路由器？

**Comment by Alvin9999** [comment]
与路由器关系不大。具有原因我也不清楚，我也是刚接触这个不久。你可以尝试[ip6开启方法（更新过）](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95) 再试试看。

如果ipv6实在没法开启，你还可以换其它类型的软件，我分享的软件挺多的。最近也发布了其它的新软。
