### ISSUE TITLE
fail to install v2ray script

### ISSUE THREAD

**Issue by askdong** [Alvin9999/new-pac#1691]
![image](https://github.com/user-attachments/assets/854e1e39-029d-4cb1-b390-34a26be85692)

**Comment by Alvin9999** [comment]
可能是系统不匹配。可以用[一键搭建多个协议脚本](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)看看。
