### ISSUE TITLE
搭建好端口有监听但是端口不通

### ISSUE THREAD

**Issue by jiaokele** [Alvin9999/new-pac#1693]
防火墙关闭、vps的防火墙放行udp tcp
端口试过默认的443 和其他的都不通。 建立一个udp测试端口是可以通的，唯独这个服务启用的端口内外都不通。
![image](https://github.com/user-attachments/assets/32357042-7851-49f9-a26c-70e62c804257)

**Comment by Alvin9999** [comment]
贴一下你搭建过程的各个参数是怎么选择的

**Comment by jiaokele** [comment]
没事了，只是测试udp端口不通，但是客户端能连=。=

**Comment by Alvin9999** [comment]
好的。
