### ISSUE TITLE
使用vultr自建服务器v2ray新脚本不支持修改加密方式了么，最近新建一个一晚就会被封，请教一下怎么修改加密方式，感谢

### ISSUE THREAD

**Issue by daozun** [Alvin9999/new-pac#1695]

**Comment by Alvin9999** [comment]
之前的脚本在教程中仍然存在，可以修改加密方式
source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh

**Comment by Alvin9999** [comment]
你搭建的什么加密方式？

**Comment by daozun** [comment]
> 你搭建的什么加密方式？

默认的，我看更改配置那里没有修改加密方式的选项，客户端连接是auto

**Comment by Alvin9999** [comment]
v2ray是传输协议为主要，加密方式一般默认即可。

**Comment by Alvin9999** [comment]
比如TCP、Websocket、Mkcp等。
如果你用V2rayN客户端，还可以用[一键搭建多个协议脚本](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)来搭建多个不同协议的节点，其中包括hysteria2，速度要快不少

**Comment by daozun** [comment]
> 比如TCP、Websocket、Mkcp等。 如果你用V2rayN客户端，还可以用[一键搭建多个协议脚本](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B)来搭建多个不同协议的节点，其中包括hysteria2，速度要快不少，还有目前比较流行的vless-reality协议节点。

好的，非常感谢
