### ISSUE TITLE
fair免费的vmess今天好像连不上哇

### ISSUE THREAD

**Issue by zhiiuuu** [Alvin9999/new-pac#1697]
都是fail哇
大神能否看看
![截屏 2024-10-14 11 05 02](https://github.com/user-attachments/assets/8a90034d-cc6f-4f0e-8e51-ffa8105a1257)

**Comment by Alvin9999** [comment]
用最新的节点。

**Comment by Alvin9999** [comment]
苹果手机可以下载一个Streisand（免费）软件，就可以使用节点2（vless-reality协议节点）

**Comment by Alvin9999** [comment]
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogImRvbmd0YWl3YW5nLmNvbVx1ODI4Mlx1NzBCOTEiLA0KICAiYWRkIjogIjIzLjE3MC40MC4xMTYiLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICIwYzdmZTEwMC1mY2NlLTRjNmQtODIwOC1hNTNmNzNlOTNlMTciLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogInd3dy5iaW5nLmNvbSIsDQogICJwYXRoIjogImdpdGh1Yi5jb20vQWx2aW45OTk5IiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiIsDQogICJmcCI6ICIiDQp9

vless://9aca2f38-5ab8-424d-b198-c6c229b6353e@185.22.154.79:11223?encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.yahoo.com&fp=chrome&pbk=px14i0ISua-XFqkVuF7UzoBmDFJTiamW_pihxX6o1U4&sid=43e24701&type=tcp&headerType=none#dongtaiwang.com%E8%8A%82%E7%82%B92
