### ISSUE TITLE
谢谢你的分享！

### ISSUE THREAD

**Issue by tomybluesky** [Alvin9999/new-pac#17]
这里的免费帐号很不错，一直在用，谢谢ALvin9999的辛苦收集与分享！！

**Comment by Alvin9999** [comment]
不客气，好东西一起分享

**Comment by huiyu998** [comment]
谢谢ALvin9999的辛苦收集与分享

**Comment by tomybluesky** [comment]
@Alvin9999 請問"天地行“論壇（tiandixing.org)麼一直打不開了，難道關閉了還是換網址啦,那個論壇裡面有很多有實用的方法。

**Comment by Alvin9999** [comment]
@tomybluesky  可以打开的，我刚刚试了，前面网址要加https   https://tiandixing.org/

**Comment by tomybluesky** [comment]
@Alvin9999 謝謝，可以打開啦
