### ISSUE TITLE
SSR版不能翻墙了，更新了最新版也不行

### ISSUE THREAD

**Issue by windflower57521** [Alvin9999/new-pac#170]
从今天开始的。以前都可以。是我个人的问题，还是服务器的问题

**Comment by jiangchengyike** [comment]
我刚才也发现了同样的问题。

**Comment by redstoneleo** [comment]
我也是

**Comment by jinyumarine** [comment]
已经被墙了

**Comment by jiangchengyike** [comment]
下了其他几个貌似也用不了了

**Comment by Alvin9999** [comment]
待修复

**Comment by Alvin9999** [comment]
云端已更新，按照使用说明更新一下看看

**Comment by jiangchengyike** [comment]
可以了，辛苦作者了。

**Comment by windflower57521** [comment]
更新ip之后 ssr设置还原为初始状态了 服务器地址并没有同步

**Comment by windflower57521** [comment]
你是怎么做到的 用的是ssr版 还是其他

**Comment by windflower57521** [comment]
你是怎么做到的 用的是ssr版 还是其他

**Comment by Alvin9999** [comment]
@windflower57521  你是xp系统吗

**Comment by windflower57521** [comment]
@Alvin9999 是的 电脑有问题 现在用旧电脑 xp系统

**Comment by Alvin9999** [comment]
@windflower57521  你可以把下面的ssr信息直接填入ssr客户端来使用，主要填ip、端口、密码、加密方式、协议和混淆就可以了。会尽快修复ssr更新文件对xp系统的支持。

			"remarks" : "update_2017.10.23",
			"server" : "45.63.92.76",
			"server_port" : 555,
			"server_udp_port" : 0,
			"password" : "ntdtv.com",
			"method" : "aes-256-cfb",
			"protocol" : "auth_sha1_v4",
			"protocolparam" : "",
			"obfs" : "tls1.2_ticket_auth",
			"obfsparam" : "",
			"group" : "alvin9999",
			"enable" : true,
			"udp_over_tcp" : false
		},
		{
			"remarks" : "update_2017.10.23",
			"server" : "45.32.128.38",
			"server_port" : 666,
			"server_udp_port" : 0,
			"password" : "ntdtv.com",
			"method" : "aes-256-cfb",
			"protocol" : "auth_sha1_v4",
			"protocolparam" : "",
			"obfs" : "tls1.2_ticket_auth",
			"obfsparam" : "",
			"group" : "alvin9999",
			"enable" : true,
			"udp_over_tcp" : false
		},
		{
			"remarks" : "update_2017.10.23",
			"server" : "45.77.1.125",
			"server_port" : 777,
			"server_udp_port" : 0,
			"password" : "ntdtv.com",
			"method" : "aes-256-cfb",
			"protocol" : "auth_sha1_v4",
			"protocolparam" : "",
			"obfs" : "tls1.2_ticket_auth",
			"obfsparam" : "",
			"group" : "alvin9999",
			"enable" : true,
			"udp_over_tcp" : false
		},

**Comment by Alvin9999** [comment]
@windflower57521  XP系统运行ssr配置更新文件后不能成功更新，这个问题目前没法解决。我已经手动将配置更新好后发布了SSR新版，有空可以试下。

**Comment by jinyumarine** [comment]
又被墙了

**Comment by ekingling** [comment]
这几天好严重，GP版也是一堆的good_addrs=0

**Comment by jiangchengyike** [comment]
是啊，又被墙了。

**Comment by Jason-Fly** [comment]
请问大家，从哪里更新最新4.8版本？虽然我的现在还能用

**Comment by Alvin9999** [comment]
SSR版暂停更新，忙不过来。建议换其它类型的软件。

**Comment by OnlYet** [comment]
服务器没问题，但是ssr客户端连不上服务器，唉，搞不懂
