### ISSUE TITLE
异常，节点有了但是无法访问

### ISSUE THREAD

**Issue by jixintangen** [Alvin9999/new-pac#1701]
![image](https://github.com/user-attachments/assets/e81c673a-f19e-44b4-a066-59b8aab24336)

**Comment by Alvin9999** [comment]
客户端可以用v2rayN

**Comment by Alvin9999** [comment]
你可以多提供一些信息。比如服务器选择的是什么系统？脚本用的哪个来搭建的？浏览器打不开外网的截图等等

**Comment by Alvin9999** [comment]
你用的是v2ray还是v2rayN，这是两款不同的软件，v2rayN支持的协议更多。

**Comment by jixintangen** [comment]
用的是v2rayN，找到问题了，谢谢！
