### ISSUE TITLE
请问按照教程弄的v2ray，一天挂一个端口怎么回事？

### ISSUE THREAD

**Issue by syzhugh** [Alvin9999/new-pac#1702]
每天都要换一个端口，不太清楚原因

**Comment by Alvin9999** [comment]
换传输协议。
或者用这个[一键搭建多个协议节点教程](https://github.com/Alvin9999/new-pac/wiki/%E4%B8%80%E9%94%AE%E6%90%AD%E5%BB%BA%E5%A4%9A%E4%B8%AA%E5%8D%8F%E8%AE%AE%E8%8A%82%E7%82%B9%E6%95%99%E7%A8%8B) 搭建比较热门的vless realty、hysteria2协议，v2rayN客户端可以用。

**Comment by admin3999** [comment]
帮我推广下啊个我们免费半年现在开放免费不影响你的项目和口碑，不白推给钱哎

**Comment by ihidao** [comment]
V2地话白嫖CF不香么？
