### ISSUE TITLE
两个链接都无效，无法链接服务器

### ISSUE THREAD

**Issue by sparklerl** [Alvin9999/new-pac#1706]
提供的两个链接都无效，无法链接服务器，能不能真心更新个可用的链接呢

**Comment by Alvin9999** [comment]
2个链接？你说的是ssr还是v2ray节点呢？

目前2个ssr和v2ray节点都有很多人在使用。推测是你没有配置正确或者客户端不支持新的v2ray协议等原因。

**Comment by Alvin9999** [comment]
以截图的形式多提供一点图片，便于帮你分析
