### ISSUE TITLE
X账号被冻结怎么办

### ISSUE THREAD

**Issue by Marktobu0258** [Alvin9999/new-pac#1708]

**Comment by Alvin9999** [comment]
google搜看看相关方法。

**Comment by Marktobu0258** [comment]
ok，谢谢大佬。我创的ins号也封了QAQ，太久没用就会封吗

**Comment by Marktobu0258** [comment]
原来如此，谢谢大佬解惑。人机测试通过后又显示系统错误稍后重试有什么解决方法吗？
![Uploading 4b789915-b0ee-4add-8467-1617fb5d3d4b.png…]()

**Comment by Marktobu0258** [comment]
原来如此，
![image](https://github.com/user-attachments/assets/c2782842-a328-4680-b1c5-45ae1bca0e32)

**Comment by Marktobu0258** [comment]
原来如此，谢谢大佬解惑。账号找回时机器人测试通过后又会提示系统错误重新再试有什么解决方法吗？网上说跟设备有关，用iPhon就行，没iPhone是不是就寄了T-T
重试好几次一直是这样
![image](https://github.com/user-attachments/assets/20755110-5a01-41b8-9308-acc2507e14d7)

**Comment by Marktobu0258** [comment]
原来如此，谢谢大佬解惑。账号找回时机器人验证通过后又会显示系统错误请重试有什么解决方法吗？网上说跟设备有关，用iPhone就行，没iPhone是不是就寄了T-T
重试好几次一直是这样
![image](https://github.com/user-attachments/assets/e1b3b490-1780-43f3-916b-b7f828d9b5c6)

**Comment by Alvin9999** [comment]
对这块确实没怎么研究过。。。

**Comment by Marktobu0258** [comment]
好的，多谢

**Comment by Marktobu0258** [comment]
好的，多谢
