### ISSUE TITLE
请问Chromebook也能用什么Goagent或是PAC的方式FQ吗

### ISSUE THREAD

**Issue by huang5307** [Alvin9999/new-pac#171]
请问Chromebook也能用什么Goagent或是PAC的方式FQ吗?
 
我在Windows中用了你的Chrome62_64bit_GP_Quic_2017.10.22觉得很不错，但是我还有一台Chromebook，这当然是更需要FQ的，想想他也是一个Chrome 浏览器啊！能用上述相类似的方法FQ吗？

**Comment by Alvin9999** [comment]
对mac操作系统不熟悉，以后可能会研究下。

**Comment by huang5307** [comment]
use Android version
