### ISSUE TITLE
gogo翻墙可以像GoAgent版最小化托盘吗？

### ISSUE THREAD

**Issue by AKB48kojima** [Alvin9999/new-pac#172]
gogo占任务栏，想和GoAgent版一样放在系统托盘，在设置页面里没有找到最小化托盘，请问可以放在系统托盘上面？可以的话如何设置？

**Comment by Alvin9999** [comment]
近期很忙，这个小问题暂时不考虑，有精力的时候再来琢磨。

**Comment by AKB48kojima** [comment]
好吧，将就着用。
