### ISSUE TITLE
账号异常问题求助

### ISSUE THREAD

**Issue by whxbxs** [Alvin9999/new-pac#1728]
首先感谢作者，用的是Chrome131_AllNew_2024.11.15.7z，clash.meta
前些天刚用上，可以正常使用，于是注册了谷歌账号，youtube和X，
今天刚打开就看到谷歌账号“账号异常”，还要验证
youtube登录被退出，尝试登录就发现出了问题
急眼了，顺手把+86手机号拿去验证谷歌账号了
验证完后谷歌就是正常登录的状态，但youtube还是无法登录，尝试登录，跳转到以下网页
![屏幕截图 2024-12-16 133534](https://github.com/user-attachments/assets/43d73975-60c0-49d7-b579-70e298a1df1d)
多次尝试均如此
去联系申诉了，但要等2工作日
然后又检查了X，账号不出所料的出了问题，好在过个邮箱验证和人机验证就搞定了
奇怪的是，前几天并没有在youtube上做什么事，只是简单的浏览，连赞都没点过
我担心谷歌账号的申述无法通过，以及后续会不会再出现此类问题，所以求助

**Comment by Alvin9999** [comment]
你好，关于账号这块没有多少经验，给不了很好的建议哦。你已经申诉了，只好等结果了。

一般来说，登录账号时，ip不要频繁变化，频繁变化容易被判定为机器人。

**Comment by Alvin9999** [comment]
(ChatGPT答案)

可能的原因
安全原因或账号异常活动

谷歌和YouTube有强大的安全检测系统，如果系统检测到某些异常活动（比如频繁的登录尝试、从不同地区登录、使用不同设备等），可能会认为账号存在安全风险，从而触发验证流程。
尤其是如果你刚刚注册并使用新账号，系统可能会对账号的活跃度进行更严格的监控。
多次登录失败或使用不同的IP地址

如果你在尝试登录时输入密码错误或使用了多个设备登录（尤其是IP地址变化较大），可能会导致账号暂时被锁定或触发验证。
谷歌验证过程中使用的手机号

如果你使用了“+86”手机号验证账号，并且手机号是从不同的地区或国家使用的，也可能导致账号异常。
YouTube账号同步问题

YouTube和谷歌账号是关联的，但有时会出现同步问题，导致即使谷歌账号恢复正常，YouTube仍然无法登录。
第三方账号问题

如果你通过某个第三方服务（例如X）使用谷歌登录，有时也可能导致登录问题，尤其是在这些服务出现变动时。
解决办法和建议
耐心等待申诉结果

既然你已经提交了申诉，首先要做的就是等待谷歌的回复，通常需要1-2个工作日。在此期间，不要频繁尝试登录，这样可能会延长解锁时间。
检查邮件

留意与谷歌或YouTube相关的电子邮件通知，有时谷歌会通过邮件告知你账号恢复的状态，或者提供进一步的解决方案。
使用Google账号恢复页面

如果账号验证时仍有问题，可以尝试使用谷歌账号恢复页面，按照页面提示进行操作。
更改密码

如果账号已经恢复正常，建议更改密码并启用双重身份验证（2FA）以增强安全性。这样可以避免因账号被盗用或未经授权的登录而再次出现问题。
检查账号设置

在你的谷歌账号和YouTube账号设置中，查看是否有安全设置、应用权限或登录历史等。这样可以确认是否有异常登录记录。
暂时避免在多个设备或IP上频繁切换登录

避免在不同设备或网络下频繁登录谷歌和YouTube账号，尤其是如果有多个登录尝试失败的情况。
联系谷歌支持

如果申诉结果不理想，或者你仍然无法登录，可以尝试通过谷歌支持与客服联系，直接向他们说明你的情况。

**Comment by liraosin** [comment]
谷歌最好移动设备注册登录，搞台没入网的安卓机，谷歌自家的最好，有谷歌账户加成，打开谷歌play的客户端注册登录，用墙外邮箱注册，连手机号验证都免了（只要你不换机子登号），ip没限制，网上那些公开的节点随便用，不影响你账户，只要登录保持在谷歌的商店，浏览器可以用系统的谷歌账户授权官方chrome使用网页谷歌，ip也能随便切（不进会被谷歌当成更换其它设备的无痕登录就行），保持谷歌判定你一机一号就行，没换机子可以一直不用短信验证
