### ISSUE TITLE
proxy qc的ip出问题了

### ISSUE THREAD

**Issue by A6066** [Alvin9999/new-pac#173]
with good_addrs=0, bad_addrs=66 （坏的ip有时>100）@Alvin9999

**Comment by ekingling** [comment]
我的GoProxy也是同样问题，昨天开始good_addrs=0，bad_addrs=18，满屏的红黄色代码刷屏

**Comment by k860831** [comment]
proxy agent 都不能用了，所在地区：四川宜宾市 。共产党真是丧心病狂咯，开倒车还踩地板油。20年老网民也没路子了，Alvin9999救我们出来。

**Comment by tianxianbaibao** [comment]
昨晚用新软goagent ipv6版可行

**Comment by 1608637229** [comment]
我这里也挂了，

**Comment by ekingling** [comment]
goagent ipv6版我这里不支持，现在只剩下无界和自由门这两个从来没用过的不知怎样

**Comment by ekingling** [comment]
其实我想说别的帖要搬运的，虽然作者同意了还是低调点吧，私底下分享给你的好友就行了

**Comment by k860831** [comment]
已经证实目前仅ipv6这法能翻出去，但是带宽速度相对 AGENT PROXY要慢些。

**Comment by happier2** [comment]
这里是倒车开的。。。也是没谁了，这是为十九大献礼么。。。

**Comment by A6066** [comment]
@Alvin9999期待你写一个自己换ip的教程

**Comment by dhzjy** [comment]
都不能用呃(⊙﹏⊙) 我的ipv6也开不了

**Comment by Alvin9999** [comment]
目前软件一共有：GoProxy Quic版、GoAgent ipv6版、GoAgent版、GoProxy版、SSR版、GoGo版、萤火虫版、FreeGate版、WuJie版等，近期还会发布新版，请留意主页上的信息。

因为国内不同的地区，封锁强度不同以及网络环境不同，至于哪款软件适合你那里的环境，需要自己一款一款的来测试。需要提醒的是，有的软件会持续更新云端上的配置，这些软件需要按照使用说明文档来运行ip更新文件来同步到云端，测试前需要好好看下文档的说明哦，如果更新ip后还是没法使用，说明这款软件目前并不适合你的网络环境，自己也别灰心，接着尝试下一款软件，尝试过的软件也别删掉，也许过段时间又好用了。

**Comment by scARx** [comment]
试了好几个版本都无法更新IP，无奈

**Comment by 1608637229** [comment]
基本都能用，但是每一个都非常卡，几天前还是youtube 720P无压力。

**Comment by Alvin9999** [comment]
@1608637229   最近会出一个GoProxy ipv6版，速度会得到提升。可以关注下。
