### ISSUE TITLE
关于v2ray经常失效的建议

### ISSUE THREAD

**Issue by ld0714** [Alvin9999/new-pac#1739]
最近v2ray经常失效，能否将新建端口开放出来，使用者一旦发现失效可以主动恢复其端口，避免长时间无法使用还需要博主自己新建端口。

**Comment by Alvin9999** [comment]
你好，谢谢你提出的建议。考虑了一下，这个技术上目前无法实现，目前是手动来更换被墙端口。有空再研究研究。
