### ISSUE TITLE
GoProxy-Quic版，百度网盘解压文件出错

### ISSUE THREAD

**Issue by luck-cheng** [Alvin9999/new-pac#174]
lz，GoProxy-Quic版-10-22的百度网盘下载后解压出错，只有我一个人遇到么

**Comment by Alvin9999** [comment]
先看自己下载的文件大小是否一样，然后用7z解压软件来解压，压缩包的格式是7z，可能是你用的解压软件对7z格式的文件不友好

**Comment by A-DoubleCheng** [comment]
使用的就是7z解压，看来只有我一个遇到这问题，我再重新试试

**Comment by 349205055** [comment]
反正我下载没问题
