### ISSUE TITLE
ipv6版YouTube打开乱码，Google Facebook正常，ipv6已经开启

### ISSUE THREAD

**Issue by liu987** [Alvin9999/new-pac#175]
ipv6版YouTube打开乱码，Google Facebook正常，ipv6已经开启

**Comment by liu987** [comment]
是内核版本低的原因吗

**Comment by Alvin9999** [comment]
对，如果你用的低内核版，请按照内核升级方法升级内核。

**Comment by colachen2017** [comment]
我的ipv6打不開， 是因為用了路由器的原因？

**Comment by he1226** [comment]
现在国内能用ipv6了？不是说只有学校可以用吗？

**Comment by Alvin9999** [comment]
@he1226  根据反馈，目前不仅仅是学校可以用。

**Comment by he1226** [comment]
怎么看我能不能用ipv6？

**Comment by Alvin9999** [comment]
[ipv6开启方法](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95)  里面有详细的介绍

**Comment by abchb99** [comment]
Teredo这种开启ipv6的方法和路由器无关，配置正确都能开启，我是通过2个以上路由器连出去的，一个是自用的100元低端tp路由器，另外的几个路由器不受我控制未知，都能开启ipv6，google good ip很多。
