### ISSUE TITLE
贵州电信联通所有梯子全挂了

### ISSUE THREAD

**Issue by hanweipin** [Alvin9999/new-pac#176]
贵州电信联通所有梯子全挂了，不知道其他地方近况如何？

**Comment by Alvin9999** [comment]
GoProxy Quic版、GoAgent ipv6版、Kelphon版、GoAgent版、GoProxy版、SSR版、GoGo翻墙软件、萤火虫版、FreeGate版、WuJie版 都不能使用吗？

**Comment by hanweipin** [comment]
@Alvin9999 都不能使用了

**Comment by hanweipin** [comment]
@Alvin9999 萤火虫版、FreeGate版、WuJie版 很久以来都不能使用的，GoProxy GoAgent GoGo 等25日挂的，网络服务提供商都不支持IPV6

**Comment by hanweipin** [comment]
@Alvin9999 
目录: D:\misc\fq
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2017/10/24      1:21                GoAgent
d-----       2017/10/23     17:15                GoAgent_ipv6
d-----       2017/10/24      1:30                GoAgent_quic
d-----       2017/10/24      1:26                gogo
d-----       2017/10/24      1:34                goproxy
d-----       2017/10/24      3:39                goproxy - me
d-----       2017/10/25     19:37                klephon
d-----       2017/10/25     11:34                psiphon3
d-----       2017/10/25     13:10                ssr
d-----       2017/10/25     12:26                wujie
d-----       2017/10/25     12:30                ziyoumen

**Comment by A6066** [comment]
V2RAY搜一下，网络快，ytb 24m移动宽带 跑一万多

**Comment by hanweipin** [comment]
@A6066 多谢，我看看去

**Comment by Leroy1245** [comment]
SSR没问题··
