### ISSUE TITLE
校园网 SSR WIN端可用 安卓端却不可用

### ISSUE THREAD

**Issue by Jason-Fly** [Alvin9999/new-pac#179]
本来这周WIN端也不可用，但今天按教程运行ipv6脚本以后就能用了。

我用电脑开热点给手机用，手机开了SSR，检测提示 unable to resolve host

P.S. 自己搭建了Vultr，换了服务器也不行；网络是广东移动 校园网，学校最近进行了网络升级  ：)

**Comment by Jason-Fly** [comment]
求大佬指点

**Comment by Alvin9999** [comment]
如果win端可用，说明账号没问题。账号有问题的话，应该是都无法使用。

unable to resolve host 提示是host的问题，可以排除下。我对安卓手机也不太熟悉。学校进行了网络升级，如果手机和电脑都是用的wife，那么电脑能用，说明也不是网络的问题。

**Comment by Jason-Fly** [comment]
刚才解决了。在服务器端修改了加密方式，就能用了。玄学……
