### ISSUE TITLE
我在wiki上看到了goagent，不知道能不能用= =

### ISSUE THREAD

**Issue by Gdname** [Alvin9999/new-pac#18]
ubuntu的还要装SSR麻烦= =加上我也不用ubuntu
我用archlinux不过我似乎在archlinux的wiki上看到了科学上网的goagent
![default](https://cloud.githubusercontent.com/assets/22128065/20243851/b5f1c250-a9a4-11e6-8ba3-b41113808c50.PNG)

**Comment by Alvin9999** [comment]
试一下就知道了

**Comment by Gdname** [comment]
你去试一试= =，装一个arhclinux要装好久= =，手打命令的我不容易还不能粘贴复制

**Comment by Alvin9999** [comment]
这么麻烦哦，我不用linux系统的

**Comment by Gdname** [comment]
我更新IP的时候，是国内的IP2 出现系统找不到指定的文件，然后翻墙就不能用了，我重新解压了一次，在此更新也是如此的

**Comment by Gdname** [comment]
图片稍后补上

**Comment by Gdname** [comment]
![default](https://cloud.githubusercontent.com/assets/22128065/20856711/184ca5b2-b951-11e6-84e9-70b663be6aad.PNG)
![1](https://cloud.githubusercontent.com/assets/22128065/20856715/26d726e8-b951-11e6-88ec-202165a89071.PNG)

**Comment by Alvin9999** [comment]
用ip-1文件试试

**Comment by Alvin9999** [comment]
我刚试了11.22的版本，没有问题。如图：
![default](https://cloud.githubusercontent.com/assets/12132898/20858244/5bbd140a-b97c-11e6-96a6-2d142bfcb80b.PNG)
