### ISSUE TITLE
按照教程自己整了个服务器，可是执行脚本报错怎么办啊

### ISSUE THREAD

**Issue by zhukongyi** [Alvin9999/new-pac#182]
SSR安装成功了，但是启动不了，查看日志，提示：
```bash
found an error in config.json: Expecting , delimiter: line 4 column 21 (char 72)   
IPv6 support
```
这个怎么处办啊，求助

**Comment by Alvin9999** [comment]
自己解决了吗？

**Comment by zhukongyi** [comment]
是的，已经解决了。
开始的时候手贱，把端口设置成了0417，当时设置通过了，安装完成后却怎么也启动不了。
根据报错，怎么修改ssr目录下的config.json也没有效果，后来通过脚本修改配置，把0417的0去掉就好了。‘
谢谢回贴
