### ISSUE TITLE
我这里的校园打开github都是断断续续的

### ISSUE THREAD

**Issue by 1608637229** [Alvin9999/new-pac#183]
24和25号更是直接打不开所以外网。他们到底在测试些什么。http://www.williamlong.info/archives/5137.html
好像是这篇文章说的，要搞白名单了。我他妈》》》我这里昨天还是稳定的，今天又开始
断断续续。垃圾校园网。

**Comment by Alvin9999** [comment]
嗯，根据反馈，国内个别地区github网站已经被墙了。

白名单的话，也别太悲观。相信总会有办法的。比如这次的GAE ipv4 ip被大量的封，但近期也出来一些新的方法来替代，比如ipv6，quic协议等。
