### ISSUE TITLE
谷歌浏览器低内核GoAgent版

### ISSUE THREAD

**Issue by lizongde** [Alvin9999/new-pac#184]
谷歌浏览器低内核GoAgent版
更新ip之后也不能打开网页（大批黄字）！

**Comment by Alvin9999** [comment]
由于封锁加重的影响，GoAgent版和GoProxy版已无可用谷歌ip，建议在[主页](https://github.com/Alvin9999/new-pac/wiki) 上换其它类型的软件。因为国内网络环境不同、封锁强度不同，所以至于哪款软件适合你那里的网络环境，需要你自己来测试。

**Comment by abchb99** [comment]
开启IPv6，还是有很多谷歌ip可用的。

**Comment by 1608637229** [comment]
现在速度慢了很多，上个星期还是很稳的。自建现在发现很多便宜的套餐都卖光了
