### ISSUE TITLE
不定期分享SSR节点

### ISSUE THREAD

**Issue by leemz3** [Alvin9999/new-pac#185]
alvin9999分享的ssr节点都非常优质，可能使用人数太多的缘故，放出来不久就变得不稳定，流量也用得飞快，我在这里放出别的SSR节点，给各位网友使用，都是网上找的，不一定安全，所以不宜用这些节点进行敏感操作，如果是看youtube、下载之类的，可以用这些节点，复制之后打开SSR客户端用剪贴板批量导入SSR链接：

11月1日 更新：

ssr://MTI4LjE5OS4xNTAuMjMwOjQ0MzphdXRoX3NoYTFfdjQ6Y2hhY2hhMjA6dGxzMS4yX3RpY2tldF9hdXRoOmVucDRlRFF4TXpFLz9vYmZzcGFyYW09ZDNkM0xtSmhhV1IxTG1OdmJRJnJlbWFya3M9UVZZdFUwYw

 
ssr://NDUuMzUuNTIuMTk0OjcyMTphdXRoX2FlczEyOF9zaGExOmNoYWNoYTIwOnRsczEuMl90aWNrZXRfYXV0aDpaRzkxWWk1cGJ5OXpjM3BvWm5ndkttUnZkV0l1WW1sa0wzTnplbWhtZUM4cU56SXgvP3JlbWFya3M9NXB5czZMU201WS0zNXAybDZJZXFPbVJ2ZFdJdWFXOHZjM042YUdaNEwtbVZuT1dEai1XZm4tV1FqVHBrYjNWaUxtSnBaQzl6YzNwb1puZ3Y

**Comment by 906584305** [comment]
非常感谢(｡･ω･｡)ﾉ♡

**Comment by Alvin9999** [comment]
将楼主的某些词语修改了一下，改为“可能使用人数太多的缘故”。管理员权限好大。

**Comment by leitaoxman** [comment]
好人一生平安

**Comment by scott521** [comment]
weavi.com/15479566
这个试试，也还行

**Comment by scott521** [comment]
[https://weavi.com/15479566](https://weavi.com/15479566)
科学上网，可以试试，很不错的
