### ISSUE TITLE
谷歌代理遇到了区域限制

### ISSUE THREAD

**Issue by 906584305** [Alvin9999/new-pac#186]
一些网站必须要求你在他们的国境登入，像这样的情况就只能挂他国的vpn了嘛？

**Comment by Alvin9999** [comment]
是的。除了vpn以外，还可以选择指定他国ip的ssr账号及其它用他国vps服务器搭建的工具。

**Comment by 906584305** [comment]
好吧~谢谢啦(｡･ω･｡)ﾉ♡
