### ISSUE TITLE
我用新版的GP 1624,老是提示链接不私密

### ISSUE THREAD

**Issue by IRISlMaple** [Alvin9999/new-pac#187]
请问到底是什么原因。
证书什么都都重新安装过了。
是证书过期的原因吗？
要怎么处理？
请教一下，谢谢。

**Comment by Alvin9999** [comment]
从某个版本开始，goproxy取消了对原来goagent appid的支持，需要用最新的服务端上传appid。由于我不想放弃goagent，故一直用的是1549

**Comment by IRISlMaple** [comment]
@Alvin9999 所以重新上传就好了吗？最新的服务端在哪里下啊~
