### ISSUE TITLE
下载了最新版（62版本的IPV6）出现如下代码

### ISSUE THREAD

**Issue by frank5** [Alvin9999/new-pac#188]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2607:f8b0:400a:3::f]:443: i/o timeout"
}

**Comment by Alvin9999** [comment]
请问你的电脑系统是否成功开启了ipv6？

**Comment by frank5** [comment]
@Alvin9999 WIN10系统，已经启动了 开启ipv6.bat

**Comment by frank5** [comment]
@Alvin9999 ，哦，现在已经可以了

**Comment by frank5** [comment]
@Alvin9999 就是每次都必须要点击ipv6.bat，才行

**Comment by Alvin9999** [comment]
开启ipv6.bat脚本不是永久性设置，所以电脑重启后翻墙前需要再次运行它。

**Comment by share301** [comment]
按照开启ipv6的方法设置了，但是还是开启不了 我的电脑是32位win7旗舰版

**Comment by share301** [comment]
好多方法都试了 ip helper也是自动开启了

**Comment by Alvin9999** [comment]
如果所有的方法都试过了，但是依然不能成功启动ipv6，那么可能是你的网络环境不适合开启ipv6。建议换其它类型的软件来翻墙。

**Comment by share301** [comment]
之前用chrome goagent都可以用 我是江苏电信 是不是开启不了ipv6

**Comment by share301** [comment]
之前用chrome goagent都可以用 我是江苏电信 是不是开启不了ipv6

**Comment by Alvin9999** [comment]
根据你的描述，你那里开启不了ipv6。你可以换其它的软件。

另外，由于我刚刚在云端更新了GoAgent版ip，你可以更新一下ip再试试看，如果不行，那么只能换其它的软件了。

**Comment by abchb99** [comment]
@share301 安装的可能不是微软原版系统吧，Teredo隧道方式开启ipv6和网络环境无关的，不能开启是系统问题。有些网友制作的精简系统可能不行，重装个原版系统应该能解决。

**Comment by abchb99** [comment]
维基百科
Teredo是一个IPv6转换机制，它可为运行在IPv4互联网但没有IPv6网络原生连接的支持IPv6的主机提供完全的连通性。与其他的类似协议不同，它可以在网络地址转换（NAT）设备（例如家庭路由器）后完成功能。
Teredo使用跨平台隧道协议提供IPv6连通性，将IPv6资料包封装在IPv4用户数据报协议（UDP）数据包内。Teredo路由器将这些数据报在IPv4互联网上传输及通过NAT设备。其他在IPv6网络上的Teredo节点（被称为Teredo中继，英文为Teredo relays）接收数据包，解开它们的封装，以及传递它们。

**Comment by abchb99** [comment]
https://support.microsoft.com/zh-cn/help/929852/how-to-disable-ipv6-or-its-components-in-windows
微软提供了一些禁用或启用 IPv6的工具。

**Comment by Alvin9999** [comment]
@abchb99  你分享的方法非常好。我把这个加在开启ipv6方法里面去。

**Comment by Alvin9999** [comment]
[ipv6开启方法](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95) （2017年11月1日更新，增加微软开启ipv6工具）

@abchb99  上面是ipv6开启方法的教程，已更新。以后如果你有更好的建议，不管是哪方面的，比如方法、措词、排版、细节等，都欢迎提出。

**Comment by share301** [comment]
更新的ip也用不了 都是黄字 还有新更新的微软开启ipv6看不懂 不太会用

**Comment by Alvin9999** [comment]
@share301  建议换其它类型的软件，比如SSR版，v2ray版等。

**Comment by Alvin9999** [comment]
@share301  由于国内网络环境不同、地区不同，封锁强度会不同，所以使用效果会有差别，有的地区几乎所有的软件都能使用，有的只能用几款，因此具体哪款软件适合你的网络环境，需要你自己来尝试。不要纠结于某一款软件，如果已经按照使用说明文档把该更新的都更新了，该排除的因素都排除了，还是不能翻墙的话，此时最好的选择就是换其它类型的软件。

**Comment by abchb99** [comment]
@Alvin9999 好客气。感谢你为网友提供的很好的翻墙工具。关于ipv6开启方法，以我个人的经验可以补充几点，看是否有用：

1、关于测试ipv6是否开启，还需要点击“测试项目”，“不使用域名的 IPv6 测试”为一项成功就肯定可以了。如下图:
![](https://raw.githubusercontent.com/abchb99/file/abchb99-patch-1/v6.jpg)

2、如果“开启ipv6.bat”能测试成功，不用运行微软提供的启用 IPv6的工具。反之可以选择页面上的微软工具“在所有隧道接口上重新启用 IPv6 ”尝试开启IPv6，下载后运行或者直接运行都可以。
![](https://raw.githubusercontent.com/abchb99/file/abchb99-patch-1/v61.jpg)

3、如果ipv6能正常开启，将系统服务“IP Helper”设为“自动”，则重启电脑之后，ipv6应该是正常的，不用再运行“开启ipv6.bat”。

**Comment by Alvin9999** [comment]
@abchb99  收到，感谢。
