### ISSUE TITLE
有没有安卓用来翻墙的APP。能上IG，facebook 和推特！

### ISSUE THREAD

**Issue by maidiweide** [Alvin9999/new-pac#19]
之前用的蓝灯现在不好用了，问一下有没有安卓用来翻墙的APP。能上IG，facebook 和推特！

**Comment by Alvin9999** [comment]
这里有几款，你试试看https://github.com/Alvin9999/new-pac/wiki/%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA%E7%89%88

**Comment by CHN008** [comment]
去 Google Play搜索一下,有很多. Super VPN, One Click VPN 都不错 :face_with_thermometer:

**Comment by qcind** [comment]
How about lantern.
https://github.com/getlantern/forum
