### ISSUE TITLE
没有 mac 版本吗

### ISSUE THREAD

**Issue by macong0420** [Alvin9999/new-pac#190]
没有 mac 版本吗

**Comment by Alvin9999** [comment]
你可以用[MAC](翻墙方法) 有很多种。目前还没有针对MAC制作一键翻墙浏览器。

**Comment by Alvin9999** [comment]
你可以用[MAC翻墙方法](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6) 有很多种。目前还没有针对MAC制作一键翻墙浏览器。
