### ISSUE TITLE
ShadowsocksR启动失败

### ISSUE THREAD

**Issue by JemyZou** [Alvin9999/new-pac#191]
![image](https://user-images.githubusercontent.com/13834392/32209370-eac2651c-be42-11e7-9bbd-522d7877818e.png)
安装完成后显示已安装，但未启动，选10启动显示ShadowsocksR启动失败

**Comment by JemyZou** [comment]
![image](https://user-images.githubusercontent.com/13834392/32210033-68614440-be46-11e7-8c44-848bcd5f3072.png)
logs show that

**Comment by Alvin9999** [comment]
1.是否vps的操作系统选择的是centos 6？

2.如果是centos6系统，那么可以通过快捷管理命令把ShadowsocksR卸载了，然后再装一遍。如果这个脚本试了两次以上还是不行，那么可以选择第一个部署脚本来安装。

3.如果不是centos系统，那么你可以把这个服务器删掉，重新部署一个新的服务器。

**Comment by JemyZou** [comment]
谢谢，卸载后再安装解决了

**Comment by You00** [comment]
centos8安装了卸载再安装还是提示启动失败

**Comment by Alvin9999** [comment]
@You00 脚本不支持CentOS8系统

**Comment by You00** [comment]
@Alvin9999 
CentOS8系统有没有一键安装的呢？

**Comment by Alvin9999** [comment]
@You00 没有CentOS8，因为这个系统是新的，脚本一般都不支持的。建议换系统。

**Comment by You00** [comment]
@Alvin9999 
服务器买来是预装了centos8，然后现在这边是已经把ssr服务装上去了，但是只能在一台电脑上使用，就是我本机电脑连上可以用，但是我手机用Potatso Lite连接不能用，换一台电脑连也不能用，是不是我需要在配置什么呢？

**Comment by Alvin9999** [comment]
@You00 你可以用wife试试看，如果手机用wife可以，那么就说明是移动网络的限制问题。

**Comment by You00** [comment]
@Alvin9999 
wifi也不行，我用移动网络连接我朋友的号也可以用，不知道是什么情况，我在想是不是我搭的有什么问题，如果不用第三方脚本搭建的话，要怎么搭建呢？针对centos 8 的

**Comment by Alvin9999** [comment]
@You00 不会。你可以网上搜搜看。

**Comment by You00** [comment]
@Alvin9999 
好的，thank you

**Comment by julyueluo** [comment]
也遇到这个问题，请问最后解决了吗，是怎么解决的呢

**Comment by Alvin9999** [comment]
@julyueluo 你的vps系统不要选择默认的CentOS8，只能选6或者7

**Comment by julyueluo** [comment]
@Alvin9999  
![图片](https://user-images.githubusercontent.com/29233472/75851391-80be2500-5e24-11ea-957d-5f4594740511.png)
又出现
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(服务器45) at 14:18:42.
这个问题怎么办呢

**Comment by julyueluo** [comment]
重启没问题了

**Comment by HduSy** [comment]
> 1.是否vps的操作系统选择的是centos 6？
> 
> 2.如果是centos6系统，那么可以通过快捷管理命令把ShadowsocksR卸载了，然后再装一遍。如果这个脚本试了两次以上还是不行，那么可以选择第一个部署脚本来安装。
> 
> 3.如果不是centos6系统，那么你可以把这个服务器删掉，重新部署一个新的服务器。

thanks change the Centos version 2 6 then problem solved.

**Comment by 13809634102** [comment]
我的是启动失败后，重新开了一个CenOs7的vps，然后重新操作就好了

**Comment by fxconfig** [comment]
查询日志看到是 module 'collections' has no attribute 'MutableMapping'
修改 class LRUCache(collections.MutableMapping):   为  class LRUCache(collections.abc.MutableMapping):
成功启动，
网上大神提示： python3.10 版本 MutableMapping 放置的位置变为 abc 下面了

**Comment by 761089357** [comment]
OpenCloudOS release 8.8都可以安装，只是需要修改ssr脚本，所有python修改为python3再添加软连接ln -s /usr/bin/python3 /usr/bin/python

**Comment by linxtong** [comment]
> 查询日志看到是 module 'collections' has no attribute 'MutableMapping' 修改 class LRUCache(collections.MutableMapping): 为 class LRUCache(collections.abc.MutableMapping): 成功启动， 网上大神提示： python3.10 版本 MutableMapping 放置的位置变为 abc 下面了

g更改文件  /usr/local/shadowsocksr/shadowsocks/lru_cache.py 的第44行 class LRUCache(collections.MutableMapping):
