### ISSUE TITLE
最近咋回事啊？时断时续的！

### ISSUE THREAD

**Issue by CarberryChai** [Alvin9999/new-pac#198]
这几天，有时候可以上，有时候好长时间连不上，可以ping 通，就是翻不了墙，奇了怪！之前的IP是美国硅谷的，现在把服务删了，重新deploy了新加坡的服务器，还是上不了，服了！😥

**Comment by Alvin9999** [comment]
用这个页面的[免费ssr账号](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7) 试试看。每个账号每天都有上百人使用。你看下你自己能不能用，如果能用的话，你把你的ssr端口、密码、加密方式、协议和混淆设置成和我的账号一样的，再试试看。

**Comment by Alvin9999** [comment]
另外，我分享的搭建ssr教程末尾有常见问题解决方法，你也可以参考下
