### ISSUE TITLE
求助！Chrome62_64bit_GA_ipv6-2017.10.23，无法打开Twitter中的视频与GIF

### ISSUE THREAD

**Issue by Ausf8421** [Alvin9999/new-pac#199]
您好作者！感谢作者长期以来的努力！！遇到一个问题，需要作者帮忙看一下~
版本：Chrome62_64bit_GA_ipv6-2017.10.23
表现：Twitter中的所有视频和GIF图片均无法播放，可以看到带播放按键的预览图，但是点击之后没有任何反应，感觉就是一张图片一样。
搜索之前的帖子似乎有朋友遇到类似的问题，同步过IP，但是没有解决。
请作者帮忙~非常感谢~！！

**Comment by Alvin9999** [comment]
你好，可以换GoProxy ipv6版试试看。目前很忙，没有更多的精力来处理GoAgent版中与twitter有关的问题。
