### ISSUE TITLE
GP的问题，打开所有代理网站出现的

### ISSUE THREAD

**Issue by CZY3434123** [Alvin9999/new-pac#200]
405. That’s an error.

The request method POST is inappropriate for the URL /_gh/. That’s all we know.

**Comment by Alvin9999** [comment]
按照使用说明文档运行ip更新文件，可以将软件的ip更新到最新的云端配置，再试试看，如果还是无法打开代理网站的话，建议换其它类型的软件。

**Comment by CZY3434123** [comment]
嗯嗯，谢谢你啦
