### ISSUE TITLE
这是什么情况呢？请帮忙解决。

### ISSUE THREAD

**Issue by jiangossac** [Alvin9999/new-pac#201]
安装好了之后，好几个版本打开都是出现这样的情况。有以下提示，请大家帮忙，谢谢

{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: NetworkIdleTimeout: No recent network activity."
}

**Comment by Alvin9999** [comment]
你用的应该是GoProxy Quic版，可以按照使用说明文档运行ip更新文件，将ip更新到最新的云端配置。然后再尝试看看。如果更新到最新的云端配置后，还是无法打开国外网站，且自己的电脑也排除了国产杀毒软件的干扰，那么说明GoProxy Quic版目前并不适合你的网络环境。

如果是这样的话，建议换其它类型的软件。

**Comment by jiangossac** [comment]
可能是IPV6开启后没有重启的原因，重启了之后可以用了，谢谢您。

**Comment by jiangossac** [comment]
只是会经常断线~连接不上~
