### ISSUE TITLE
您好，我问一下哪里能下载chrome浏览器的免安装版，纯净无插件的，急用，跪谢！

### ISSUE THREAD

**Issue by maidiweide** [Alvin9999/new-pac#202]
chrome浏览器的免安装版，纯净无插件的，急用，跪谢！

**Comment by Alvin9999** [comment]
[谷歌浏览器](https://api.shuax.com/tools/getchrome)  下载后，把exe后缀名改为zip，然后解压即可。

**Comment by maidiweide** [comment]
好的，我试试，谢谢

**Comment by caofengzi** [comment]
https://api.shuax.com/tools/getchrome
這裡都是離線安裝包而且不用翻牆，下載以後解壓exe文件就能得到一個chrome.7z壓縮包，解壓以後就是免安裝版了。

**Comment by maidiweide** [comment]
免安装版是不是不受其他版本的影响是吧，之前我自己在电脑装过一个chrome浏览器，插件啥的都自己设定好了，但是一旦用了别的版本chrome浏览器，再打开我自己安装的这个chrome的浏览器插件啥的都被破坏掉了，不知道什么原因，后来我自己在网上找了一个便携版的chrome浏览器的压缩文件解压后一直用到现在，最近发现版本有点老了是54的，所以想找一新版chrome浏览器，不需要安装解压就能用的！

**Comment by caofengzi** [comment]
@maidiweide你說的情況應該是安裝版的， 俺上面那個地址都是離線安裝包，下載以後不要點擊安裝，而是右鍵解壓，解壓以後會得到一個chrome.7z壓縮包，在解壓chrome.7z以後就是免安裝版了，然後啟動瀏覽器登錄你的google帳號然後在設置裡面選擇同步內容，以後在用其它版本的chrome設置擴展都不會丟失。
