### ISSUE TITLE
能不能给自己搭建服务器的设置一下限流量

### ISSUE THREAD

**Issue by ruixuedongyang** [Alvin9999/new-pac#203]
每个端口限制一定的流量

**Comment by Alvin9999** [comment]
只能通过限制速度来间接的限制流量。比如：第二个脚本，进入管理界面后，选择数字7，然后有“单线程限速”选项。

**Comment by ruixuedongyang** [comment]
谢谢回复，感谢

2017年11月6日星期一，自由上网 <notifications@github.com> 写道：
