### ISSUE TITLE
翻墙小白，感谢楼主

### ISSUE THREAD

**Issue by gj311241** [Alvin9999/new-pac#204]
纯属电脑小白，按照楼主搭建服务器的方法一步一步的下来，成功了，一台mac和一台win，找不到mac关于ssh好用的app，就是找到了，我也不会设置和使用，建议楼主去写一下关于mac下怎么使用ssh客户端搭建。里面很多知识点有点白痴，有没有这方面的书可以推荐下，谢谢！

**Comment by Alvin9999** [comment]
楼主没有mac，也没用过，教程不好写，所以就不写了噢，网上有很多这方面的教程，用google或百度搜一搜。

你能用windows搭建成功，mac不是什么大问题。mac除了使用ssh客户端连vps以外，还可以搭建一个windows系统的虚拟机，然后用windows系统来连vps。建议你选择前者，先在网上搜mac使用ssh客户端教程。互联网是一个众多资源和信息分享的宝库。
