### ISSUE TITLE
版主去哪里找ipv6的ip段来扫的？用的是什么扫描工具呢？

### ISSUE THREAD

**Issue by yDan** [Alvin9999/new-pac#205]
因为我自己搭建了google 的appid，所以想自己扫描ip

**Comment by Alvin9999** [comment]
[工具](https://github.com/Kisesy/gscan_quic)
[ipv6](https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/good_ipv6.txt)
