### ISSUE TITLE
求个账号

### ISSUE THREAD

**Issue by fongzii** [Alvin9999/new-pac#206]
分享的都不能用，多谢

**Comment by Alvin9999** [comment]
账号没有问题。分享的是SSR账号，请问你是否用的是SSR客户端？

**Comment by zswordsman** [comment]
已经关掉免费的了，mac 除了ssr 有其他的方式吗 谢谢

**Comment by Alvin9999** [comment]
[MAC翻墙方法](MAC翻墙方法（2017年10月29日增加v2ray）)（2017年10月29日增加v2ray）

**Comment by Alvin9999** [comment]
应该很快会重新分享ssr账号，主要是想给大家提个醒，不要下载有版权的电影或视频。
