### ISSUE TITLE
电脑开启ipv6，有时会遇到超时（断开？），如何解决？

### ISSUE THREAD

**Issue by xu378947986** [Alvin9999/new-pac#207]
ipv6有时能正常使用，隔一段时间会出现i/o timeout 不知如何解决呢

**Comment by Alvin9999** [comment]
电脑重启一下，再看看，或者运行两边开启ipv6脚本

**Comment by xu378947986** [comment]
有时候突然就断开 一会儿又可以 不知道怎么回事 断开时候 重启和开脚本都没用啊 群主

**Comment by Alvin9999** [comment]
那估计是那里ipv6不稳定的缘故吧。如果是这样，那么换其它的版本噢
