### ISSUE TITLE
大佬，我照着你这个自建ss服务器的教程还是不能翻墙，原本能上的github都上不了，怎么办？

### ISSUE THREAD

**Issue by OnlYet** [Alvin9999/new-pac#208]

**Comment by OnlYet** [comment]
win10本地cmd能ping通服务器

**Comment by OnlYet** [comment]
ssr客户端日志错误：
在 Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-11-09 16:29:49] [Error] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 119.28.87.227:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

**Comment by OnlYet** [comment]
服务器日志：
2017-11-09 15:20:22 ERROR    tcprelay.py:1097 can not parse header when handling connection from :ffff:18.19.16.188:44430
2017-11-09 15:20:43 WARNING  common.py:238 unsupported addrtype 69, maybe wrong password or encryption method
2017-11-09 15:20:43 WARNING  tcprelay.py:521 Protocol ERROR, TCP ogn data b6dec0d8f4ee9063b2ebe8711e6cb1b55aa4e6060bac5327056895b5a1b0aeec203331e98d4649ebbcf53089c8a3ee56666da61d24c33175d77f8b926cc0f3e2b10a86543b777e3e0c6f8fd4f7157fd16fd9a8354b71e03c04329be3229d525549bf7e388a101e40afd66068c901035aaf5222e56675421cf5f48e46b8696326144cae1ed054b9b20e3857d00774418e758b4303e8dfa3e281d1260daa37947444d72df19ce1558e4fb2dbe8ee1e4abb0487ba24526f8788d3c6e1c8fb2b8aebf2c2493003b6c517649aa5ec9dd0852e98b1bc897c987f5591e3796709f31fc6cb1243261427dd4876fc1a4f10becb7293e6 from ::ffff:18.19.16.188:45549 via port 8989 by UID 8989

**Comment by Alvin9999** [comment]
你好，请贴出服务器部署SSR账号信息、SSR客户端配置信息以及浏览器代理设置截图，我帮你分析一下

**Comment by Alvin9999** [comment]
需要提醒的是：SSR客户端协议和混淆不要忘了填，且配置信息要和服务器配置的信息一模一样。同时，浏览器代理设置成 http 127.0.0.1和1080   如果这些都没有问题，还是不能翻墙的话，那么服务器可以把协议和混淆通通设置成第一个，即协议origin和混淆plain

**Comment by OnlYet** [comment]
![1](https://user-images.githubusercontent.com/19988547/32608595-cb7d02dc-c597-11e7-8c56-ed4052e42299.png)
![2](https://user-images.githubusercontent.com/19988547/32608598-cea5d4ac-c597-11e7-9c5c-2c7ec98cee9b.png)

**Comment by OnlYet** [comment]
![1](https://user-images.githubusercontent.com/19988547/32608671-1725343e-c598-11e7-82ca-7ad12b9f26a3.png)
![2](https://user-images.githubusercontent.com/19988547/32608673-180ae542-c598-11e7-92d3-1edcba6613d7.png)

**Comment by Alvin9999** [comment]
除了尝试上面的方法，你把密码搞复杂点，不要用纯数字，用复杂点的字母

**Comment by OnlYet** [comment]
唉还是没用
![3](https://user-images.githubusercontent.com/19988547/32609221-e135529e-c599-11e7-8010-f4f861a27f79.png)

**Comment by OnlYet** [comment]
目前我用以前公司的ss代理在寝室可以翻墙，但是在公司不能用。自己搭建的这个寝室都不能用。。

**Comment by Alvin9999** [comment]
协议改成origin，混淆改成plain，密码改复杂点，也不行吗？端口改成443看看

**Comment by Alvin9999** [comment]
这个SSR配置是我常用的配置信息，使用效果不错。你也可以尝试下。如下：

端口：443 密码：dongtaiwang.com   
加密方式: AES-256-CFB  SSR协议、混淆(必填）： 协议：auth_sha1_v4   混淆：plain

**Comment by OnlYet** [comment]
还是不行，协议和混淆是否要兼容？ssr客户端pac和代理规则是什么？

**Comment by OnlYet** [comment]
![4](https://user-images.githubusercontent.com/19988547/32610198-f68946de-c59c-11e7-83d2-7dd949622448.png)

不是跟服务器配置有关系吧？

**Comment by Alvin9999** [comment]
代理规则选默认的，不要管它。第一个系统代理，需要选用”全局模式“

**Comment by Alvin9999** [comment]
协议和混淆我经常用的是不兼容

**Comment by Alvin9999** [comment]
代理规则默认的是"全局“ 
系统代理要选”全局模式“才能和浏览器设置的匹配。

**Comment by OnlYet** [comment]
![5](https://user-images.githubusercontent.com/19988547/32610795-c782f68a-c59e-11e7-998f-b235f1db933e.png)

**Comment by Alvin9999** [comment]
你用的ie浏览器翻墙，还是其它的浏览器？

**Comment by OnlYet** [comment]
google呀

**Comment by Alvin9999** [comment]
我看你用的是IE浏览器设置的代理。你用谷歌浏览器上网的话，推荐用SwitchyOmega插件，然后设置代理。

**Comment by OnlYet** [comment]
![image](https://user-images.githubusercontent.com/19988547/32616862-6401c3ba-c5ae-11e7-9b93-f5aaea30a77f.png)
还是不行，有毒

**Comment by Alvin9999** [comment]
![222](https://user-images.githubusercontent.com/12132898/32634959-2deb6296-c5e9-11e7-9eca-c962cdb426f3.PNG)
你是这样设置的吗？除了google以外，其它网站能打开不？

**Comment by Alvin9999** [comment]
![333](https://user-images.githubusercontent.com/12132898/32635017-733054c4-c5e9-11e7-8dbd-6c8c2c4a61a1.PNG)
你试一下我的ssr账号，看看能不能连，判断一下你那里的网络环境怎么样。

**Comment by Alvin9999** [comment]
![444](https://user-images.githubusercontent.com/12132898/32635122-ddf01024-c5e9-11e7-8282-5181034fb82b.PNG)
上面那个是硅谷服务器，这个是洛杉矶服务器，也可以试下

**Comment by OnlYet** [comment]
我试了一下都不行，github在寝室能用，在公司就不能正常用了。然后我用安卓手机试了自己的ssr，然后能翻墙。。难道是我用win10的原因？

**Comment by captain1124** [comment]
win10的你先复制配置信息里的ssr链接，然后打开那个电脑里的ssr，右键右下角的小飞机，然后剪切板批量导入，就可以了

**Comment by captain1124** [comment]
最好调一下pac模式

**Comment by OnlYet** [comment]
并不行。。

**Comment by Alvin9999** [comment]
@OnlYet  如果同样的网络环境，手机能用，电脑用不了，至少说明你搭建的ssr账号是没有问题的。那么问题肯定出在电脑上，比如电脑是否用360安全卫生等国产杀毒软件，防火墙等等之类的。

**Comment by OnlYet** [comment]
老哥有没有win10帮我测试一下，我周末试试别的系统能不能用，公司电脑只有windows defender，我关了

**Comment by Alvin9999** [comment]
没有win10系统

**Comment by OnlYet** [comment]
大佬，我让别人win7用我的ssr可以翻墙，然后我刚才在win7虚拟机试了也可以。这。。真的是win10的问题。。，不知道是防火墙，组策略，服务之类的问题，还是win10就是不支持的？
