### ISSUE TITLE
版主写一下教程，关于如何更改teredo服务器的？

### ISSUE THREAD

**Issue by yDan** [Alvin9999/new-pac#209]
版主写一下教程，关于如何更改teredo服务器的？win10系统的。

**Comment by Alvin9999** [comment]
这里有teredo备用的服务器，你可以试试看
teredo2.remlab.net
teredo-debian.remlab.net
teredo.ginzado.ne.jp
teredo.iks-jena.de
teredo.ngix.ne.kr
teredo.autotrans.consulintel.com
teredo.managemydedi.com

将开启ipv6脚本里面的这行服务器地址“state server=teredo.remlab.net”  替换一下上面的即可

**Comment by Alvin9999** [comment]
先ping一下，如果能ping通才替换

**Comment by yDan** [comment]
@Alvin9999 谢谢版主，我明白了，我这里的网络只有3个能拼通的

**Comment by yDan** [comment]
@Alvin9999 版主，我有个疑问，为什么我找些拼不通的teredo服务器放上去，然后运营开启ipv6脚本，也可以翻墙的，而且速度好像快了不少，你知道什么原因吗？

**Comment by Alvin9999** [comment]
哇唔，这么神奇! 老实说，我也不知道。不过，能用就行哈。

**Comment by Alvin9999** [comment]
请问，默认的服务器，即默认的开启ipv6脚本，你那里用不了吗？如果是，我要更新一下教程了

**Comment by yDan** [comment]
我现在就是用goproxy ipv6 这个版本来翻墙的，不知道用得了还是用不了？反正可以翻墙

**Comment by yDan** [comment]
goproxy里面的ip全是ipv6

**Comment by yDan** [comment]
你也可以更新一下开启ipv6的方法，是不是有更好的方法

**Comment by abchb99** [comment]
有些teredo服务器设置禁止了ping，但是实际上可以用。

**Comment by Alvin9999** [comment]
ok，了解了
