### ISSUE TITLE
为什么我重装WIN10 64位后 打开PAC GOAGENT什么都没有

### ISSUE THREAD

**Issue by hjkzgy110** [Alvin9999/new-pac#21]
右上角没有任何插件，只有一些收藏夹。之前还可以的，突然就不行了。

**Comment by Alvin9999** [comment]
重新解压再打开看看。如果没有插件是翻不了的。

**Comment by hjkzgy110** [comment]
我试过很多次了， 没插件是什么情况 之前还好好的额

**Comment by Alvin9999** [comment]
重新解压还是这样？那这就很奇怪了哦！你把杀毒软件退了，重新下载，再用7z解压软件解压，再打开。

**Comment by hjkzgy110** [comment]
我用的7ZIP   每次打开就是这样 而且我电脑是裸奔的  我现在到别的电脑上去试试

**Comment by hjkzgy110** [comment]
我在舍友的电脑上解压开了 他的就有用 不知道什么情况

**Comment by hjkzgy110** [comment]
算了 麻烦你了 看来我不适合用这个 哈哈

**Comment by Alvin9999** [comment]
windows版的翻墙浏览器，我分享了4款，你可以试试其它的哦～

**Comment by Alvin9999** [comment]
右键“以管理员身份运行”一键启动程序，也可以试试这种方法。

**Comment by marochim** [comment]
我也遇到了同样的问题  请问有没有解决办法？

**Comment by Alvin9999** [comment]
@marochim  首先排除杀毒软件的干扰，可以先退出杀软再解压。其次，排除解压不完整，可以用7z解压软件来解压。
