### ISSUE TITLE
你好，我用的是你提供的ipv6的方式科学，上网的。我想问一下这样安全吗？

### ISSUE THREAD

**Issue by houhouwei** [Alvin9999/new-pac#210]
我用ip111查询自己位置，说是外国普通网站还是本地ip，但是我不想全局ipv6，因为这样的话，国内的网站打开比较慢，，我想问一下这样安全吗？

**Comment by Alvin9999** [comment]
安全。
如果你用的是自动代理模式，那么访问国内网站会自动走本地网络，访问国外网站才会走代理。如果此时，你用一个没有被墙的查ip网站，那么肯定显示的是你本机的ip。你可以用一个被墙的国外网站来查询，因为此时走的是代理，那么会显示代理的国外ip。

如果你用的是全局代理，那么你访问任何查ip的网站，都会显示代理的ip。

**Comment by abchb99** [comment]
如果设置的全局代理，打开国内的网站当然比较慢。可以设自动代理或者换另一个不设代理的浏览器访问国内的网站。如果安全性要求高，最好访问国外、国内的网站分别用两个浏览器分开处理。
