### ISSUE TITLE
苹果手机使用wifi用不了ss

### ISSUE THREAD

**Issue by summyer** [Alvin9999/new-pac#211]
苹果手机移动4g可以翻墙，但是使用wifi就连不上网，这个怎么弄？求帮助

**Comment by Alvin9999** [comment]
应该不是账号的问题，如果是，4g网络和wife都会用不了。推测是不同网络类型封锁强度不同造成的。这种情况的话，你可以增加协议和混淆，或者把端口换成443，80等特殊端口，来尝试着解决，不保证有效果，可以试试看。
