### ISSUE TITLE
访问不了https://www.pinterest.com/，有什么办法可以解决呢，谢谢。

### ISSUE THREAD

**Issue by jiangossac** [Alvin9999/new-pac#212]
因为工作的关系，需要用到https://www.pinterest.com/的素材库，现在这个网站我一直进不去。

**Comment by houhouwei** [comment]
我可以上。。。我用的ipv6方式

**Comment by Alvin9999** [comment]
浏览器地址栏右侧有个圆形的按钮，点击一下可以切换成全局代理

![00000](https://user-images.githubusercontent.com/12132898/32679887-1a2bbd2c-c6a3-11e7-9020-b6e32f892a17.PNG)
