### ISSUE TITLE
为什么会这样。。。怎么变成普通代理了。。。

### ISSUE THREAD

**Issue by houhouwei** [Alvin9999/new-pac#213]
![qq 20171110224943](https://user-images.githubusercontent.com/33490648/32663610-85055098-c669-11e7-8cda-d0bac027a936.png)

求解！

**Comment by Alvin9999** [comment]
用的赛风版吗？如果是，赛风版就是这样设置的，因为赛风没有固定的端口。

**Comment by houhouwei** [comment]
我用的ipv6呀。。。一开机就成这样了。。请问是不是我用了清理软件的问题？

**Comment by Alvin9999** [comment]
有可能噢！你重新解压之前下载的压缩包就是新的了

**Comment by houhouwei** [comment]
@Alvin9999 又变成普通的了。。。好烦，又要重新解压，覆盖

**Comment by Alvin9999** [comment]
@houhouwei  电脑有没有用360安全卫生、360杀毒软件、腾讯管家等国产杀毒软件呢？

**Comment by houhouwei** [comment]
@Alvin9999 没有，，为了用这软件，，我电脑管家都卸载了。。。不知道是不是我用ccleaner或者是dism++清理电脑的问题

**Comment by Alvin9999** [comment]
很有可能噢

**Comment by houhouwei** [comment]
@Alvin9999 有没有好的杀软或者清理软件推荐下，版主

**Comment by Alvin9999** [comment]
你用搜索网站搜国外免费杀毒软件或好用的清理软件就行，应该有不少网友的推荐
