### ISSUE TITLE
群主！！我在使用高内核GoProxy版(64位)浏览器的问题？

### ISSUE THREAD

**Issue by yy0535** [Alvin9999/new-pac#214]
群主！！我在使用高内核GoProxy版(64位)浏览器的问题？就是这个版本浏览器不能再浏览器搜索栏搜索东西，一直不显示内容，只能是在制定谷歌网页里搜索，这样很不方便，如果，我这样，你不明白，你可以下载一个包试试，
在就是Facebook里面不能看视频直播，非常卡，一直转圈圈，再不就是显示视频错误，请你能改正一下，谢谢，看到后，请你紧急回复，谢谢！。

**Comment by Alvin9999** [comment]
1.可以在地址栏输入搜索内容。如图：
![1](https://user-images.githubusercontent.com/12132898/32689385-8fa711a2-c71e-11e7-929c-2c3e884adfb8.PNG)
![2](https://user-images.githubusercontent.com/12132898/32689386-8ffdc5ec-c71e-11e7-9ae7-3f73447f9f17.PNG)

2.facebook的问题目前没法解决。如果特别喜欢看facebook的视频，只能换其它版本。

**Comment by yy0535** [comment]
我在使用高内核GoProxy版自动代理下不能在谷歌搜索栏里搜索，全局可以

**Comment by Alvin9999** [comment]
那就辛苦一下自己在搜索的时候切换一下全局代理喽。你所在地区能用GoProxy版，运气还是不错的，因为有不少地区由于封锁严重，目前还用不了GoProxy版。
