### ISSUE TITLE
最几天延迟有点高啊，卡出翔了！

### ISSUE THREAD

**Issue by gj311241** [Alvin9999/new-pac#215]
如题，自搭口子，日本的，真的卡的要死

**Comment by Alvin9999** [comment]
日本的机子是抢手货，自然用的人超多，用的人多，服务器母机必然会有影响，当然这也与自己的宽带类型有关，不同的宽带类型国际出口线路不一样。所以，建议更换服务器位置，可以选择硅谷等美国地区的服务器。
