### ISSUE TITLE
某一个网络环境下用不了ssr

### ISSUE THREAD

**Issue by bbearb** [Alvin9999/new-pac#217]
按照教程搭建好了ssr，用了几天，今天在公司发现用不了了，但是换一个网络就可以连了。在那个不能用的网络环境下ping IP也可以ping通，现在就是公司的这一个网络连不上，用其他的WiFi都可以连上，请问是怎么回事啊？

**Comment by Alvin9999** [comment]
同样的账号配置，说明至少账号没问题。多半是公司网络防火墙的限制。

你可以尝试更换协议和混淆，比如协议origin、混淆plain，或者其它。可以试试看，不保证能有用。

**Comment by Jason-Fly** [comment]
我也遇到这种问题了。目前我用的是以前的付费账号的配置，aes-128-ctr, auth_aes128_md5, tls1.2_ticket_auth, 再加混淆参数cloudfront.com。不太稳定。请问有什么推荐的协议加密组合吗？

**Comment by Alvin9999** [comment]
@Jason-Fly  推荐混淆用plain。因为混淆不总是有效果，要看各地区的策略，有时候不混淆（plain）让其看起来像随机数据更好。
