### ISSUE TITLE
您好，请问如何更换使用自己的APP ID

### ISSUE THREAD

**Issue by zhualexander** [Alvin9999/new-pac#219]
Chrome62_64bit_GA_ipv6-2017.10.23
出现红字是流量不够么？

感谢您的分享

**Comment by zhualexander** [comment]
忘截图了红字最后好像是  403  错误

**Comment by Alvin9999** [comment]
出现红字不是流量不够的提示，一般来讲红字黄字只要不影响使用，不用管。如果你想换自己的appid，可以参考这个教程里面的替换方法[自建appid教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAappid%E5%92%8C%E6%90%9C%E8%B0%B7%E6%AD%8Cip%E6%95%99%E7%A8%8B%EF%BC%88GoAgent%E7%89%88%E5%92%8CGoProxy%E7%89%88%EF%BC%89)
