### ISSUE TITLE
求偶像指点个学习方向

### ISSUE THREAD

**Issue by captaindeadpoool** [Alvin9999/new-pac#22]
我想学python，目标就是要做一个自己的翻墙软件。
毕竟，随着国家对网络控制的网收得越来越紧，可能日后，真正能说自己是自由人的，是那些有能力不被控制的人，出版和公共的言论自由早就没了，网络空间是最后的阵地。
想求大神给提点一下途径，先学什么，有那些库需要掌握，有什么书可以推荐，有什么教材您觉得合适的，有那些社区可以有很多人交流和解答问题的。

**Comment by Alvin9999** [comment]
python学习路线 https://www.google.co.jp/?gfe_rd=cr&ei=0BlCWIq6Iszo8AeHvaWACg#q=python%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF

现在比较流行的是购买国外的vps服务器（一般几十块钱每个月），然后自己搭建ss或者pac服务器，网上教程一大把的，包括一键安装代码，非常简单和方便。如果你想快速上手搭建自己的翻墙梯子，可以参考我写的这个教程https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%B7%B1%E6%90%AD%E5%BB%BAPAC%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B

**Comment by roseyue** [comment]
大神你好。你发的Python学习路线现在好像失效了。能补发一份吗？感谢~

**Comment by Alvin9999** [comment]
@roseyue 

[自建SS服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （2017年8月30日更新购买vps服务器教程）

[自建PAC服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAPAC%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) (2017年8月30日更新购买vps服务器教程）

**Comment by Alvin9999** [comment]
python学习路线需要翻墙打开，因为是google搜索结果

**Comment by roseyue** [comment]
我是用了你写的翻墙软件翻墙后，粘贴了 https://www.google.co.jp/?gfe_rd=cr&ei=0BlCWIq6Iszo8AeHvaWACg#q=python%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF
这个地址，提示：
无法访问此网站

找不到 www.google.co.jp 的服务器 DNS 地址。
尝试运行 Windows 网络诊断。
DNS_PROBE_FINISHED_NXDOMAIN。

但是我确认是已经翻墙成功了的。因为GOOGLE主页和油管都能连接上。

**Comment by Alvin9999** [comment]
如果你能成功翻出去，可以自己搜python学习方向
