### ISSUE TITLE
麻烦能不能提供一下原版的goproxy？

### ISSUE THREAD

**Issue by YunXuyun** [Alvin9999/new-pac#220]
我更喜欢用原版的goproxy搭配chrome上网

**Comment by Alvin9999** [comment]
[goproxy](https://github.com/goproxy0/goproxy/releases)

**Comment by yDan** [comment]
@Alvin9999 有时候真觉得版主很厉害，goproxy的作者都删除了所有版本的goproxy了，居然你还可以找得到。

**Comment by houhouwei** [comment]
@Alvin9999 请问版主，这个软件能不能集成在路由器里面，或者有没有这样的插件？。。。嘿嘿，你懂得

**Comment by Alvin9999** [comment]
@houhouwei  这个就不会了

**Comment by yunnl** [comment]
@Alvin9999 能否请教一下，群晖里安装哪个版本呢？？

**Comment by Alvin9999** [comment]
@yunnl  “群晖里”是什么意思？

**Comment by yunnl** [comment]
@Alvin9999 群晖NAS啊，一个linux系统，按照网上的教程我看了下似乎是BSD的，但是完全不会装啊

**Comment by Alvin9999** [comment]
@yunnl  喔！我没有用过

**Comment by yunnl** [comment]
@Alvin9999 能不能帮我看一下，太感谢了。https://post.smzdm.com/p/350104/ 这个是VMware，我研究了一整天都没捣鼓明白。: )

**Comment by Alvin9999** [comment]
@yunnl  教程很详细喔，你看自己具体卡在哪一步，然后针对这个问题去网络上搜搜

**Comment by yunnl** [comment]
@Alvin9999 这个是虚拟机安装群晖的，我已经能成功运行了。。。包括ipkg或者opkg的程序包都能成功运行，就是2楼您给的那些goproxy，实在是不知道选择哪个了。。。能请您帮个忙安装一下虚拟机的群晖指导下如何在群晖里安装goproxy么？

**Comment by Alvin9999** [comment]
@yunnl  帮不了你，不是我会这个方法不教你，是因为我也不会。如果是新手，不建议自己弄goproxy，并非装了goproxy就能用，还涉及到很多设置以及ip的问题。

**Comment by yunnl** [comment]
@Alvin9999 好吧~ 谢谢您的回复~ 我看还是找个vm+xp来挂首页的goproxy了~3q~
