### ISSUE TITLE
装完以后显示这个是什么问题？

### ISSUE THREAD

**Issue by bujieshi** [Alvin9999/new-pac#221]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2607:f8b0:4009:35::8]:443: connectex: A socket operation was attempted to an unreachable network."
}

**Comment by Alvin9999** [comment]
你用的应该是GoProxy ipv6版，使用ipv6版需要电脑系统开启ipv6才行，你可以按照使用说明文档来操作。
