### ISSUE TITLE
为什么WhatsApp 发不了图片呢

### ISSUE THREAD

**Issue by Jamesowens11** [Alvin9999/new-pac#223]
您好，请问网页版的WhatsApp， 聊天的时候为什么发不了图片呢，文字可以发送的， 就是图片接收和发送不了， 手机上就可以发的，但是网页版不行的。
还有FACEBOOK 手机登录时候就可以，但是网页版的就不行了。
请问怎么解决呢？

麻烦了，真的感谢

**Comment by Alvin9999** [comment]
你用的啥？

**Comment by Jamesowens11** [comment]
电脑上我下载的是， GoAgent版， 其他网页都是能正常的使用，就是WhatsApp 聊天时候不能发图片，还有facebook 登录不上的呢。
手机上使用的是SSR， 手机完全能正常使用WhatsApp 和Facebook， 就是电脑用的是GoAgent 版，不能正常的使用WhatsApp 和facebook.

**Comment by Alvin9999** [comment]
GoAgent有不完善的地方，可以换GoProxy版试试看

**Comment by Jamesowens11** [comment]
使用了Goproxy, WhatsApp 在电脑上还是发不出去图片的， 文字就可以发出去，不知道什么回事的，因为工作需要在网页端能够正常使用WhatsApp， 希望能提供解决方案，十分感谢

**Comment by Alvin9999** [comment]
GoProxy一共有3款不同的版本，分别是GoProxy版、GoProxy ipv6版和GoProxy Quic版。如果你用的是其中一款，那么你可以试试另外两款软件。如果都不行，可以再尝试其它类型的软件。

国内各个地区网络环境不同，并非完全是软件的原因，因为根据反馈，同样的软件，有的地区能用，有的地区不能用。目前最好的解决方案就是尝试，选择最适合自己网络环境和需求的版本。

**Comment by tandalin** [comment]
@Jamesowens11 遇到相同问题，电脑端速度超慢，不稳定就会重新上传

**Comment by Alvin9999** [comment]
@tandalin  试试其它软件，分享的软件很多。

**Comment by huanghezhen** [comment]
请问 你解决了吗
