### ISSUE TITLE
ipv6无法使用，大量bad_ip,不知如何解决

### ISSUE THREAD

**Issue by xu378947986** [Alvin9999/new-pac#224]
如题，用的服务器是默认的，这几天ipv6都用不了 显示超时，bad_ip很多

**Comment by Alvin9999** [comment]
你先确定下电脑系统是否开启了ipv6，验证方法参考：https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95 需要提醒的是，如果是通过运行开启ipv.bat脚本来开启ipv6的话，由于这种方法不是永久让电脑生效，那么当电脑重启后，ipv6会失效，此时需要再次运行脚本。

目前ipv6这种方法比较稳定。如果你的电脑经过验证确定开启了ipv6，但还是用不了的话，那说明你那里的网络封锁增强了。如果是这种情况，建议换其它类型的软件。除了GoAgent ipv6版和GoProxy ipv6版，其它软件都不需要电脑开启ipv6.

**Comment by xu378947986** [comment]
我尝试了楼主多款软件 还是ipv6速度比较快 但是连接上ipv6后 很容易断开

**Comment by Alvin9999** [comment]
你确定下是自己的电脑ipv6断开了；还是电脑ipv6没有断开，软件断开了。这是两个不同的问题。

**Comment by xu378947986** [comment]
软件没有断开 就是开启ipv6使用一段时间就检测不到ipv6呢

**Comment by Alvin9999** [comment]
你按照上面发给你的教程里面的关于更换开启ipv6.bat服务器的方法，尝试一下

**Comment by Alvin9999** [comment]
如果ipv6版实在用不了，为了能够流畅的翻墙，建议换其它类型的软件

**Comment by YiFenZ** [comment]
INFO - [Nov 25 11:06:33] ssl good_ip=0, bad_ip=983, unknown_ip=23
用了一段时间，最近几天都这样了。早上还是好的 用了30分钟之后，全变bad_ip

**Comment by Alvin9999** [comment]
@YiFenZ  排除杀毒软件的干扰后。你检测下，当bad ip大量出现时，电脑系统的ipv6是否是断开的状态。如果是断开的状态，说明你那里的网络环境ipv6容易被干扰，可以按照这个轿车呢个里面的方法https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95 替换服务器来尝试着解决。
