### ISSUE TITLE
ipv6已经开启了，但打开chrome无法连接

### ISSUE THREAD

**Issue by sundreamm** [Alvin9999/new-pac#225]
打开chrome访问外网时，agent没有数据在加载
agent应用程序名字怎么变成goagnt-uv？

**Comment by Alvin9999** [comment]
GoAgent没有数据在加载，说明软件没有正常运行，多半是被干扰了。请先排除杀毒软件和防火墙的干扰。然后重新解压（复原）再打开软件。

**Comment by sundreamm** [comment]
可以了，感谢！！
