### ISSUE TITLE
蓝灯专业版看视频卡卡卡

### ISSUE THREAD

**Issue by xiaoxin168** [Alvin9999/new-pac#226]
![image](https://user-images.githubusercontent.com/25840040/33227311-5e00bcee-d1db-11e7-8191-c19acebc15f1.png)
专业版账户：cumtbghn@126.com

**Comment by Alvin9999** [comment]
你好，我不是蓝灯客服喔～如果觉得蓝灯不好用，可以用我分享的一键翻墙浏览器：https://github.com/Alvin9999/new-pac/wiki

**Comment by happy1234367** [comment]
蓝灯在流量超过500M后会限速，解决方法是换个MAC
![image](https://user-images.githubusercontent.com/25525577/34066050-24eebbc6-e244-11e7-938a-df6bedc4dca6.png)
