### ISSUE TITLE
ipv6开始问题，曾经开启成功，但是目前一直不行

### ISSUE THREAD

**Issue by almn25** [Alvin9999/new-pac#227]
RT，曾经按教程成功连接了，有些天没上，最近再上就一直检测没开启成功，批处理运行多少次也不好用，发现有错误出现
D:\setup\翻墙>netsh int ipv6 reset 
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

微软的工具也试过了，依然不行，求高手指点，谢谢！

**Comment by Alvin9999** [comment]
重启电脑，关闭杀毒软件，然后按照这个教程https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95 更换服务器看看。如果实在不行，为了能够翻墙上网，也没有必要纠结ipv6，因为我分享的软件类型挺多的，你还可以试试其它的呢。
