### ISSUE TITLE
Chrome62_32bit_GP_ipv6_2017.10.26...無法書籤同步

### ISSUE THREAD

**Issue by colachen2017** [Alvin9999/new-pac#229]
從chrome 設置 --用戶登錄 -- 無法登陸 （其實貌似已經登錄成功，可是最後還是陌生人頭像）
但是從chrome 網頁可以登錄 --登錄後一切正常---但是無法賬戶同步 
不知該怎麼辦

**Comment by colachen2017** [comment]
從網頁上登錄google賬戶 成功，一切都正常 
可是不知道從哪裡同步賬戶 

從chrome 設置中，為啥沒法登錄呢， 或者說是偽登錄成功

**Comment by Alvin9999** [comment]
点击您的帐号头像。
点击“设置”图标 设置。
在“其他人”部分，点击同步。
----------------------------
这是网友搜到的方法，你可以试试看

**Comment by colachen2017** [comment]
to Alvin9999 
就是用這種方法，無法登錄
從網頁登錄google 一切正常 ， 只是無法同步書籤

**Comment by Alvin9999** [comment]
喔，这个我也不太懂，没用过同步功能

**Comment by angelpray** [comment]
![123](https://user-images.githubusercontent.com/17873970/33522177-cf1cb554-d820-11e7-8977-ebf6acfca07c.png)
chrome62_64bit_GP,成功。 @colachen2017 ，如果你单单使用一个版本的chrome登录估计是不行的，前提应该是要在之前就有登录过的，否则你之前的书签如何同步捏？我之前使用过lantern所以成功了……不确定是不是这个原因，有可能。
