### ISSUE TITLE
chrome62_GP

### ISSUE THREAD

**Issue by angelpray** [Alvin9999/new-pac#230]
chrome62_GP，使用google搜索时出现了需要手动验证才能进行，说是检测到了我发出的请求不是本地发出的，是由xxx发出的，然后输入之后还是可以使用的。这貌似不是个好信号。

**Comment by Alvin9999** [comment]
chrome62_GP可用的ip数很少，很多人使用的话会被谷歌判定为ip为机器人，相应的会出现验证。目前没法解决。

**Comment by whhxmwhh** [comment]
感谢楼主。。我在xx-net没遇到您这样热心的。谢谢

**Comment by Alvin9999** [comment]
@whhxmwhh  不客气哈
