### ISSUE TITLE
 楼主有没有什么推荐的ios VPN 苹果商店老是打不开

### ISSUE THREAD

**Issue by xu378947986** [Alvin9999/new-pac#231]
求楼主推荐下VPN免费软件

**Comment by Alvin9999** [comment]
可以用ss客户端，比如openwingy、superwingy、bestwingy、wingy+、greatwingy，选一款，国内app商店可下载。然后配合ss账号就能翻墙。免费ss账号：https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by nxtreaming** [comment]
为啥要安装额外的客户端？直接用内置的VPN就可以。

-----------------------------------------
Productive. Reliable. Fast.

**Comment by Alvin9999** [comment]
@nxtreaming  嗯，如果自己有vpn账号，可以通过苹果手机的设置添加VPN，但如果没有vpn账号，就需要寻找其它解决方法了。

**Comment by Penny1a** [comment]
@Alvin9999 今天试了下openwingy，显示已连接。
但instagram和chrome都无法浏览。
自动模式和全局模式都试过。何解？

**Comment by Alvin9999** [comment]
@Penny1a  
你的账号是否兼容ss客户端？ssr账号放入ss客户端，需要将ssr账号设置为兼容原版（ss客户端），或者把ssr协议设置成origin，混淆设置成plain

**Comment by Penny1a** [comment]
@Alvin9999 是用你提供的免费ss账号。
![_20171214095532](https://user-images.githubusercontent.com/26496110/33971730-043f67e4-e0b5-11e7-82c0-97bba48dd5cf.png)
openwingy没有协议和混淆选项。难道是这个原因？

**Comment by wilsonjuxta** [comment]
@Penny1a

**Comment by Alvin9999** [comment]
@Penny1a  不会。我分享的免费ssr账号兼容ss客户端。刚测试了下账号，连通性没有问题。你检查下密码这些填写正确没有，或者换另外两个免费的账号看看。

**Comment by Penny1a** [comment]
@Alvin9999 换Shadowrocket可用了。

**Comment by hallochina** [comment]
安卓苹果windows全平台支持，在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。

**Comment by hellohongtian** [comment]
为啥我老是收到这种邮件，收件人也没我

在 2018-05-04 16:01:25，"hallochina" <notifications@github.com> 写道：


安卓苹果windows全平台支持，在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。
