### ISSUE TITLE
能否让GoAgent全局代理 更新游戏？

### ISSUE THREAD

**Issue by 1204447095** [Alvin9999/new-pac#234]
RT  游戏更新很慢  如果能挂着代理玩游戏就更好了

**Comment by Alvin9999** [comment]
你好，GoAgent不是vpn，故不能对电脑进行全局代理。

**Comment by happy1234367** [comment]
可以用proxifer汉化版，设置游戏强制走代理的

**Comment by 1204447095** [comment]
用proxifer  无界跟自由门一连就断 赛风就慢   其他软件稳定不好。。。。
