### ISSUE TITLE
IPV6差点不能用吓死我了，说说我今天的遭遇

### ISSUE THREAD

**Issue by nickcarter8317** [Alvin9999/new-pac#236]
就在刚刚，大概凌晨1点左右。
我突然发现IPV6无法手动开启了，无论我使用什么方法，改DNS也好，微软工具也好，改服务器也好。
IPV6连接测试网站通通显示：超时
我一度以为局域网升级了
最后，我重启了一下电脑，发现我国内网站也上不去了，显示找不到服务器
但我QQ能登陆，而且用GOA的IPV4也可以登陆谷歌之类的网站，就国内网站找不到服务器
之后我把DNS改回来，重启还是上不去。
最后我把IPV4的DNS改成8888和114114114114，结果奇迹般的能打开国内网站了
而且IPV6也可以正常开启了。
这是怎么回事？我以前没遇到过。我以前的DNS里都是选择自动获得的。
今天不知道搞什么鬼。
而且我今天才知道IPV4和IPV6无法共存，我能用IPV6的时候IPV4显示0GOODIP，不能用IPV6的时候，IPV4倒是很流畅。

**Comment by Alvin9999** [comment]
推测是自动获得的ipv4 DNS的问题。你可以再做下验证试验或者重启路由器。解决方法就像你做的一样，改成手动的就好。
