### ISSUE TITLE
搬瓦工vps+ssr为啥访问google YouTube 都显示https不安全呢？

### ISSUE THREAD

**Issue by hhrensheng** [Alvin9999/new-pac#237]
请问一下搬瓦工vps+ssr 搭建梯子访问google YouTube 都访问不了呢。先提示https不是安全连接，继续访问之后显示空白页面，只有一个error

**Comment by Alvin9999** [comment]
对搬瓦工的vps不了解，你可以网上搜搜看类似问题的解决方法。
