### ISSUE TITLE
提一个建议-GAE类

### ISSUE THREAD

**Issue by happy1234367** [Alvin9999/new-pac#238]
发现使用internet download manager可以大幅度提高goproxy下载速度（可达4M/S）并突破32M限制，下1G的都行，百度贴吧IDM吧里的破解版
![image](https://user-images.githubusercontent.com/25525577/34075992-90d6b378-e313-11e7-8329-40d2dbf76f19.png)

![image](https://user-images.githubusercontent.com/25525577/34075986-668a6ee8-e313-11e7-9c81-6aa0457a8483.png)

**Comment by happy1234367** [comment]
地址https://idm.party/

**Comment by happy1234367** [comment]
绿色版文件约5M。
是不是可以随chrome+启动呢？

**Comment by Alvin9999** [comment]
谢谢建议。在下一版本更新时会考虑一下，因为不是所有的用户都有下载需求，所以不一定会考虑随软件一起启动，但是可以做一个下载视频的方法提供出来。
