### ISSUE TITLE
可以做一个搜狗浏览器ssr版吗

### ISSUE THREAD

**Issue by jacknnnbauer** [Alvin9999/new-pac#239]
因为搜狗浏览器的反应速度感觉比谷歌要快。
我笔记本打开youtube加载页面速度，搜狗要比谷歌快很多。而且是同样的ssr。
所以建议做个搜狗ssr

**Comment by Alvin9999** [comment]
谢谢你的建议。考虑安全因素，目前不会制作国产浏览器便携版。
