### ISSUE TITLE
连接不到代理服务器的问题，求指教

### ISSUE THREAD

**Issue by Suxia1998** [Alvin9999/new-pac#24]
感谢前辈提供这么棒的一个梯子，但我这好像用不来这一架神梯。。。

点开Mychorm之后出现一个报错

![default](https://cloud.githubusercontent.com/assets/23417547/21088633/f7bf3f9a-c06b-11e6-8a9e-4c36e275d75c.JPG)

然后 打开Google 显示无法连接代理服务器

![default](https://cloud.githubusercontent.com/assets/23417547/21088646/0e88b508-c06c-11e6-9177-0449d82a1e5f.JPG)

电脑上除了您压缩包里的蓝灯和浏览器外  还有之前就下载好在用的蓝灯和chorm浏览器（加上您的，我电脑上有两个蓝灯和两个chorm）

不知道是不是之前的蓝灯和chorm有什么影响？另外网络用的是校园网。   求前辈指教

**Comment by Suxia1998** [comment]
另外  尝试过杀毒软件都退出然后重新解压缩  也按照要求刷新过蓝灯的配置 。都没效果

**Comment by Suxia1998** [comment]
使用的是Goagent版本

**Comment by Alvin9999** [comment]
你好，从你的描述看，你用的是Lantern版，并不是GoAgent版。
国内网络环境负责，有可能是你那里的网络环境不适合用Lantern版，建议你试试GoAgent版 GoProxy版以及PAC版。多尝试下，没有坏处。选择一款最适合你那里网络环境的版本。

**Comment by Alvin9999** [comment]
你好，从你的描述看，你用的是Lantern版，并不是GoAgent版。
国内网络环境复杂，有可能是你那里的网络环境不适合用Lantern版，建议你试试GoAgent版 GoProxy版以及PAC版。多尝试下，没有坏处。选择一款最适合你那里网络环境的版本。

**Comment by Suxia1998** [comment]
嗯  现在用的GOproxy  已成功获得自由 哈哈  谢谢前辈！

**Comment by Alvin9999** [comment]
如果你想确定自己的lantern软件是否会冲突，你可以把你自己的lantern软件卸载了，然后再试试看Lantern版。

好的，知道了，客气啦！
