### ISSUE TITLE
那个版本可以浏览 汤不热 网？

### ISSUE THREAD

**Issue by 125397520** [Alvin9999/new-pac#242]

**Comment by 125397520** [comment]
ssr：是全局代理，整个系统网络都慢了
GoAgent：屏蔽了该网站

**Comment by Alvin9999** [comment]
试试GoProxy ipv6版
![gop](https://user-images.githubusercontent.com/12132898/34319894-25009ad2-e828-11e7-88aa-86e9dc35b3f1.PNG)

**Comment by 125397520** [comment]
登录不了

**Comment by Alvin9999** [comment]
登录不了可能是该网站屏蔽了该代理方式，只能尝试其它不同类型的软件来试试看，具体哪款软件能用需要自己来试。

**Comment by 125397520** [comment]
![qq 20171228200521](https://user-images.githubusercontent.com/34787277/34410359-9eea738c-ec0a-11e7-9ed0-d2495ce70e37.png)

**Comment by 125397520** [comment]
亲测，暂时只有ssr
![qq 20171228201157](https://user-images.githubusercontent.com/34787277/34410438-5e38e28c-ec0b-11e7-8619-8ee2bfc5692f.png)
