### ISSUE TITLE
每次开机的时候浏览器无法连接，QQ等部分软件可以，打开SSR再关闭恢复正常

### ISSUE THREAD

**Issue by CheeseGolem** [Alvin9999/new-pac#243]
是代理的问题吗？
这个可以通过设置什么解决吗

**Comment by Alvin9999** [comment]
依次打开IE浏览器——工具——internet选项——连接——局域网设置，把此页面的所有“勾”都去掉。不保证能用，可以试试看。

**Comment by CheeseGolem** [comment]
朋友那边这样操作可以解决，但是重启之后选项又还原了，具体原因我还没查，但我这边原本就没有勾上这些选项

**Comment by Alvin9999** [comment]
是不是用过lantern软件？lantern好像会默认修改ie代理。你检查下你的浏览器（非ie）不能上网的时候，它的代理是怎样的？

**Comment by CheeseGolem** [comment]
没用过lantern，然后火狐这边是系统代理，chrome我是有用谷歌访问助手这个插件，所以代理是插件控制的，开机的时候这个插件也找不到服务器

**Comment by Alvin9999** [comment]
噢，这样啊，可以这样试试看。当不想用浏览器翻墙时，可以把浏览器设置成直连模式，这样就不会走代理了
