### ISSUE TITLE
今天突然上不到了··········

### ISSUE THREAD

**Issue by huwenjie123** [Alvin9999/new-pac#244]
[Errno 10051] 向一个无法连接的网络尝试了一个套接字操作
是什么意思？？？

**Comment by Alvin9999** [comment]
你用的应该是ipv6版，提示的信息表明你的电脑系统没有成功开启ipv6

**Comment by huwenjie123** [comment]
我平时也是这样上的，，，
为什么会这样，，，
有地址下载最新的吗？

**Comment by huwenjie123** [comment]
推荐一个现在可以翻墙的？？
谢谢

**Comment by Alvin9999** [comment]
软件下载及更新地址：https://github.com/Alvin9999/new-pac/wiki

这是ipv6开启最新方法：https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95  

你可以先按照ipv6最新开启方法试着把电脑系统开启ipv6，里面有验证电脑是否真的开启成功的方法。如果你已经按照最新的方法都尝试过了，还是不能将自己的电脑成功开启ipv6，那很可能说明你那里的ipv6被干扰或封锁的比较厉害，那么只能换其它类型的软件，比如SSR版、GoProxy Quic版、SkyZip版等。因为不同的地区，宽带类型不同，网络环境封锁强度也不同，具体哪款软件适合你那里的网络环境，需要你自己来尝试。
