### ISSUE TITLE
数字安全手册无法下载

### ISSUE THREAD

**Issue by will0306** [Alvin9999/new-pac#247]
我在你的分享的网盘页面上点击download,但是一直跳转当前页，无法下载，就算我保存到我自己的网盘，下载的文件就只有15KB，是损坏的文件，能否共享一份资料给我，谢谢

**Comment by Alvin9999** [comment]
你好，已增加两个网盘下载地址：https://github.com/Alvin9999/new-pac/wiki/%E6%95%B0%E5%AD%97%E5%AE%89%E5%85%A8%E6%89%8B%E5%86%8C

**Comment by will0306** [comment]
多谢，我下载试试
