### ISSUE TITLE
请教线路中转如何实现？

### ISSUE THREAD

**Issue by rrwater** [Alvin9999/new-pac#254]
移动，联通，电信的线路连接vps时常会出问题，一般不是同时出现，有什么办法中转一下，例如移动的国际出口有问题，在本地转到联通的线路上再出国？

**Comment by rrwater** [comment]
找到方法了，但是手机使用4G时不知如何设置代理。
http://www.hostloc.com/thread-312012-1-1.html

**Comment by Alvin9999** [comment]
这个我也不是很懂哦，只能多在网上搜搜看

**Comment by rrwater** [comment]
谢谢！
