### ISSUE TITLE
家庭网ipv6无网络访问权限是不是意味着GoAgent ipv6无望

### ISSUE THREAD

**Issue by ATMacid** [Alvin9999/new-pac#255]
同时开启ipv6.bat没有永久路由

**Comment by Alvin9999** [comment]
不太清楚，你可以试试最新的开启ipv6开启方法中的其它方法来尝试看看。地址：https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95

如果尝试了所有的方法还是不行，也不用太灰心，因为我分享的软件挺多的，只有GoAgent ipv6和GoProxy ipv6才用到ipv6，其它软件都不用ipv6就可以使用。当然，由于大陆各个地区封锁策略会有不同，所以具体哪款软件适合你那里的网络环境，还得由你来测试才行。
