### ISSUE TITLE
搭建SSR，Android能用Win10连不上，日志如下。该怎么解决呢

### ISSUE THREAD

**Issue by wuyong1992** [Alvin9999/new-pac#257]
[2018-01-12 10:03:03] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadPACCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by Alvin9999** [comment]
手机能连，说明是你的MAC设置的问题，当然也不排除是不同的宽带类型造成的，比如你手机是移动网络，但是你的电脑是电信，那么可能电信的封锁策略不同。这种情况的话，你可以试着改变端口、密码、加密方式、协议和混淆来试试看。

**Comment by Alvin9999** [comment]
如果设置了协议和混淆，那么电脑要用SSR客户端，因为SS客户端没有协议和混淆选项。
