### ISSUE TITLE
mac上怎么使用ssr分享的ipv6账号，有ssr客户端

### ISSUE THREAD

**Issue by whyour** [Alvin9999/new-pac#258]
如题，谢谢 @Alvin9999

**Comment by Alvin9999** [comment]
使用ipv6账号，需要将自己的电脑系统成功开启ipv6才能使用。ipv6开启参考方法：https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95
