### ISSUE TITLE
很感谢这个项目

### ISSUE THREAD

**Issue by theratlesnake** [Alvin9999/new-pac#26]
看得起Alvin9999是个好人，因为基本上推荐FLG的都是有信仰的人，感谢你，也感谢所以为FQ作出贡献的所有人，感谢你们。@Alvin9999 请问你有twitter吗？

**Comment by Alvin9999** [comment]
谢谢你的夸奖。
不玩twitter哦！

**Comment by theratlesnake** [comment]
@Alvin9999 真不好意思哈，打错了那么多字，紧跟您的脚步。

**Comment by theratlesnake** [comment]
@Alvin9999 您好，请问您分享的ss账号，为什么没有混淆协议的？不太懂这个，但是听说加入混淆可以全速？

**Comment by Alvin9999** [comment]
有些ss账号是直接转过来的，原先就没有混淆协议。我自建的ss服务器参考的是网络是一键安装脚本，也没有混淆协议的。

至于你说的加入混淆可以全速。我网上搜了下，有人用混淆，速度确实提升了，而有的就不行。我想这可能是不同的网络环境造成的。

我分享ss账号的初衷是考虑苹果用户的翻墙问题，因为我分享的软件主要是针对windows电脑和安卓手机。混淆协议目前不想研究，也许以后会考虑一下。

**Comment by theratlesnake** [comment]
好的，谢谢哈，请问下，那些VPS一脚脚本是您自己做的吗？

**Comment by Alvin9999** [comment]
不是哦，是网友分享的，亲测可用

**Comment by theratlesnake** [comment]
@Alvin9999  好的，谢谢

**Comment by thinkerchan** [comment]
好人一生平安
