### ISSUE TITLE
最近的新版本Chrome浏览器不能登陆是为什么，，不能登陆很多东西不能同步有点小麻烦

### ISSUE THREAD

**Issue by ttxhxz** [Alvin9999/new-pac#260]
Chrome63_64bit_GP_ipv6_2017.12.26就是浏览器右上角的登陆按钮。。登陆以后回车按确定，登录框就消失了。点击右上角又要登陆、。。。就无限循环。。。网页里面的谷歌搜索YouTube都可以通用，就是浏览器的不能登陆。。就很怪

**Comment by ttxhxz** [comment]
win10专业版最新的系统。。不过之前也是用win10   9月10月那个时候的浏览器都能登录的。也能同步

**Comment by Alvin9999** [comment]
你试试其它网站能不能正常登录？还是只是YouTube登录不了？

**Comment by ttxhxz** [comment]
就是网页上的都能登
![2](https://user-images.githubusercontent.com/24288387/35091978-0550ed58-fc79-11e7-9355-ac096b896a7e.png)
录谷歌账号。就是浏览器右上角那个谷歌账号不能同步

**Comment by ttxhxz** [comment]
浏览器的谷歌账号不能登陆就不能同步。。。。。然后就很麻烦

**Comment by Alvin9999** [comment]
浏览器高级设置里面的cookie不要设置为保存到退出后，如果还不行的话，试试GoAgent ipv6版。你的问题的具体原因我也不是很清楚。

**Comment by ttxhxz** [comment]
浏览器默认的cookie就是没有设置为保存到退出后，就说白了就是浏览器本身的登陆登录不了，，网页能登陆。。。感觉怪怪的，别人的GoProxy可以登陆浏览器的账号吗？

**Comment by Alvin9999** [comment]
刚试了确实登录不了，可能是这次的63高内便携版不完善的原因，但具体是哪里的原因目前我也不清楚。如果老版本你能用，可以用老版本。

**Comment by ttxhxz** [comment]
好的，谢谢了

**Comment by hellomm2018** [comment]
我也弄了半天 不能同步。怎么降级到老版本？

**Comment by Alvin9999** [comment]
@hellomm2018  你用你曾经下载过的62内核压缩包，把它再解压出来就可以用，解压后使用前按照使用说明文档把ip这些都更新了。
