### ISSUE TITLE
您的连接不是私密连接怎么解决

### ISSUE THREAD

**Issue by xiaoxiaobai123** [Alvin9999/new-pac#262]
![default](https://user-images.githubusercontent.com/12913212/35129406-72f15190-fcf6-11e7-8f37-821948c17cf1.png)

版本 63.0.3239.108（正式版本） （32 位）
GreenChrome 6.3.9

十分感谢！

**Comment by Alvin9999** [comment]
具体用哪款软件？使用说明文档最上面有软件的类型

**Comment by xiaoxiaobai123** [comment]
@Alvin9999   高内核GoProxy ipv6版（32位） 已经开了ipv6 了。

**Comment by Alvin9999** [comment]
如果只是YouTube、facebook、twitter等https网站打开是这样，按照使用说明文档导入证书再试试看，方法在文档内容偏后面。

**Comment by xiaoxiaobai123** [comment]
@Alvin9999   感谢，重新操作后，可以正常访问了！

**Comment by Alvin9999** [comment]
OK
