### ISSUE TITLE
ios8有那个ss客户端是可以随意切换线路的？

### ISSUE THREAD

**Issue by quan901** [Alvin9999/new-pac#263]
求推荐

**Comment by Alvin9999** [comment]
不太明白你说的意思。随意切换线路指的是什么？线路不是自己设置的吗

**Comment by quan901** [comment]
我现在用的是cydia里面的shadowsocket，里面不能保存线路的信息，
一旦切换了其他路线要重新填写，
求ios8可保存线路信息的工具

**Comment by Alvin9999** [comment]
这可能是该软件对ios8系统兼容性不好导致的。试试：openwingy、superwingy、bestwingy、wingy+、greatwingy

**Comment by quan901** [comment]
楼上推荐的貌似都是ios9以上的，但是我找到了一个越狱软件skia，可惜不支持二维码扫描

**Comment by Alvin9999** [comment]
只能凑合用了，确实很难找。

**Comment by jjandnn** [comment]
shadowrocket，不是socket。小火箭，网上有2.1.11版的ipa文件，ios8没有问题啊。你用pp、兔兔或者爱思都可以直接安装啊，用的是这些平台的开发者证书。其次有surge的1.2.6。都可以啊。不存在不能保存节点。

**Comment by jjandnn** [comment]
差点看错，ios8上网找shadowsocks 0.3.2-3，可以去逗比那里下。另外，不存在你写的那个socket，只有rocket，小火箭。

**Comment by quan901** [comment]
好，谢谢你！另外请问ios是不是不支持ssr？

**Comment by jjandnn** [comment]
ssr在9以后的支持比较理想。现在11，基本完美。

**Comment by jjandnn** [comment]
8肯定是没发支持R的，只能ss。ssr底线是9。我刚看了日区、美区。已经全9以上了。

**Comment by quan901** [comment]
感谢各位解答

**Comment by no-name2017** [comment]
@jjandnn  大佬，请问有ios8 的免费ss客户端推荐吗
