### ISSUE TITLE
SSR服务器这几天是不是被封了（2018.01.22）？

### ISSUE THREAD

**Issue by ekingling** [Alvin9999/new-pac#264]
2018.01.22：之前一直用的好好的SSR账号这两天突然怎么也连不上了，非自建但都是网上找了很久用了大半年一直都有效的，有固定账号的也有每天动态更新的都不行，是不是坊间传说的GFW开始封杀SSR服务器了？

**Comment by Alvin9999** [comment]
可能只是个别现象。我公开分享的多台服务器，一直表现不错，就前几天有2台服务器ip被屏蔽了，然后换了下ip就可以了。当时改变了加密方式，曾经被屏蔽的两台服务器加密方式为chacha20-ietf，之后换成了aes-256-cfb运行至今。所以我判断还好，其它论坛也没有普遍反映被封。

**Comment by share301** [comment]
1.19更新的ssr pornhub.com和xvideo.com都打不开了，SSL错误

**Comment by Alvin9999** [comment]
你好，这种类型的网站已屏蔽。

**Comment by he1226** [comment]
今天SSR好像都用不了了

**Comment by Alvin9999** [comment]
@he1226  你用的是我分享的吗？我分享的账号运行状况良好，此时此刻很多人在使用，没有问题。如果你用的是SSR版，按照使用说明更新一下ip，可能是你很久没更新了的缘故，如果你更新了还是用不了，那估计是你的问题，需要自己排除下，实在不行的话，就换其它类型的软件。

**Comment by divefoolr** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by jjandnn** [comment]
两会期间，望所有人低调。24号大规模封杀，大家都有目共睹。眼下仍处于高封杀段。不要认为自己技术过硬，会一点反向代理、流量伪装之类的，就封不了你。技术上，想封你，请你茶，查你表，消灭你，分分钟的事，都太简单了。关键是它想不想，愿不愿意花精力搞你。它想，就算你是顶级hack猿，一样over。很多朋友以为官方不知道你FQ，那是你没去过XXX部门，去了你就知道了，在线的一个不拉，密密麻麻。人工作人员坐在设备前，看都不看，玩自己手机，因为没上级交代任务，就懒得理你。

**Comment by birdofprey** [comment]
@jjandnn 其实都是工作嘛，为了混口饭吃，就像朝鲜那些站岗的士兵，鬼知道他们心里想些什么。再看看那些天天批评美帝的爱国者们，一有事都往美国跑。王立军出事了干嘛不往俄罗斯使馆跑呢。
