### ISSUE TITLE
大佬，请问您提供的免费账号是哪家的？Vultr吗？

### ISSUE THREAD

**Issue by Jason-Fly** [Alvin9999/new-pac#266]

**Comment by Alvin9999** [comment]
vultr每月有流量限制，不适合作为公共免费分享的服务器，我选了3家不同的不限制流量的vps服务商。你看中了哪个或哪几个ip？

**Comment by divefoolr** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by wangxiusen** [comment]
我用的这个 https://billing.anynode.net/aff.php?aff=260

**Comment by Alvin9999** [comment]
罗马尼亚和芝加哥的服务器是两家小众服务器，但是小商家不稳定，经营不好的话容易跑路，罗马尼亚的商家的官网已经打不开了，估计是经营不善，所以下个月这两家的服务器到期后就弃用了。选vps商家最好选大品牌的。
旧金山的服务器是digitalocean商家的，和vultr一样是大品牌，跑路的可能性几乎为0，也是按小时候计费。地址：https://m.do.co/c/01092ba28bfa
