### ISSUE TITLE
教程里的VPS是KVM框架，能改用OPEN框架的VPS吗

### ISSUE THREAD

**Issue by ilongdao** [Alvin9999/new-pac#267]
我发现一个资费很便宜的VPS，但框架是OPEN的，能按照教程配下来吗？
网站地址https://www.alpharacks.com/holiday

**Comment by ilongdao** [comment]
还有教主你似乎有个QQ群，能方便告诉我一下群号吗

**Comment by Alvin9999** [comment]
非KVM框架的vps也可以搭建ss/ssr账号，但是没法使用bbr加速教程，所以速度上不出意外的话会慢很多。

没有QQ群。

**Comment by happy1234367** [comment]
openvz水分略多啊....
