### ISSUE TITLE
关于自建SS无法使用的问题

### ISSUE THREAD

**Issue by LikeYears** [Alvin9999/new-pac#268]
今天发现用了几个月的SS无效了，刚开始以为是IP被封了。重新搭建几次和更换节点以后依旧无效，无意中发现不使用一键部署的谷歌BBR加速后就可以使用了。烦请核实下是不是有这个情况，谢谢！

**Comment by Alvin9999** [comment]
你好，在不使用bbr加速的前提下，经过测试发现，账号可以使用。你说的问题没法复现，可能是个别现象。
采用的账号配置信息如下，供君参考：
端口：333
加密方式：aes-256-cfb
协议：auth_sha1_v4 （兼容原版）
混淆：plain

**Comment by LikeYears** [comment]
感谢回复。目前不使用bbr加速的情况下可以正常使用，延迟大概为2400ms

**Comment by divefoolr** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by Alvin9999** [comment]
建议部署bbr加速，多个步骤可以提高速度。
