### ISSUE TITLE
大佬，推荐一下用什么加密，协议，混淆

### ISSUE THREAD

**Issue by Rehtt** [Alvin9999/new-pac#269]
我的服务器两个ip前两天被封了，我曾经用的是aes-256-cfb，origin，tls 1.2_ticket_auth组合
端口443

**Comment by Alvin9999** [comment]
混淆不要使用tls开头的，目前看tls开头的容易被针对，混淆推荐用plain，即不混淆；加密方式用aes-256-cfb，不推荐用chacha20；协议不推荐用origin，其它的还好。

**Comment by Rehtt** [comment]
好的，学习了，谢谢你的回答

**Comment by Alvin9999** [comment]
嗯，不客气
