### ISSUE TITLE
谷歌账号的登陆问题

### ISSUE THREAD

**Issue by jacknnnbauer** [Alvin9999/new-pac#27]
网页端的谷歌账户可以登录，但是浏览器的谷歌账户无法登陆，输入密码后确定总是提示DNS解析错误。
因为我想同步以前的一些账户密码，插件，搜索引擎等等。毕竟换了有点不方便。

**Comment by Alvin9999** [comment]
请问你用的什么版本呢

**Comment by theratlesnake** [comment]
支持一下

**Comment by jacknnnbauer** [comment]
GoAgent版

**Comment by Alvin9999** [comment]
多试几次，如果还不行的话，可以试试GoProxy版。这两款版本为了达到比较好的翻墙效果，同时又能适应国内大多数地区的网络环境，所以软件内置的google ip很多，但随之带来的登录问题，目前还没有找到更好的方法来解决

**Comment by theratlesnake** [comment]
@Alvin9999 请问下你有使用过vpn gate吗

**Comment by Alvin9999** [comment]
@theratlesnake  曾经试用过，当然不好用。

你运行一下GoAgent版里面的ip更新文件再试试看，我刚刚做了一下改动

**Comment by jacknnnbauer** [comment]
@Alvin9999 谢谢，多试几次后可以登录了。希望可以一直保持稳定。

**Comment by theratlesnake** [comment]
@Alvin9999  博主，还有两个翻墙软件也不错，赛风3和无界浏览，速度还可以，可以加上去

**Comment by theratlesnake** [comment]
@Alvin9999  当然自由门做后备用不错，那么多年了就它一直坚挺能上，虽然慢了一些

**Comment by Alvin9999** [comment]
嗯嗯，谢谢你的建议，会加上去的

**Comment by Sak1tama** [comment]
@theratlesnake 你怎么也在这里，哈哈

**Comment by theratlesnake** [comment]
@Sak1tama  哈哈，我来这，是给这个项目的主人提供免费ss账号，让他添加维护的，很热心的一个管理者

**Comment by weinierlai** [comment]
@theratlesnake 建议所有ss服务器参照 http://www.bawagon.com/ddos-deflate/ 打上防ddos补丁 另外，日本樱花主机现在还免费，有空可以弄多几个ss

**Comment by theratlesnake** [comment]
@weinierlai 我用樱花，看youtube才200Kbps不到的速度，最低画质都卡，安装了Kcptun，总是上一会就断，有人说是UDP干扰严重，老哥，有好的办法吗？另外，在樱花上好像用不了BBR加速

**Comment by Sak1tama** [comment]
@theratlesnake 那个一键安装脚本应该支持最新的 aes-256-gcm 加密方式，你不加混淆，不加kcp，换个加密方式试试 我注册不了樱花，没法解释太多

**Comment by Sak1tama** [comment]
@theratlesnake 那个一键安装脚本应该支持最新的 aes-256-gcm 加密方式，你换个加密方式 还有这个  http://www.bawagon.com/net_speeder/

**Comment by theratlesnake** [comment]
@Sak1tama 换个加密方式就能解决了么？那udp干扰这个呢？感觉应该是udp受干扰才掉线啊，net_speeder还是finalspeed ？

**Comment by Sak1tama** [comment]
@theratlesnake 用finalspeed tcp 试试 net_speeder好像用不了了

**Comment by Sak1tama** [comment]
@Alvin9999 强烈建议在vps教程第四步写上防ddos插件安装运行方法

**Comment by theratlesnake** [comment]
我在找锐速的版本，好像都没支持ubuntu4.8内核的

**Comment by theratlesnake** [comment]
什么第四步教程？

**Comment by Sak1tama** [comment]
@theratlesnake ubuntu不适合做服务器，就像win 7不适合一样。服务器最好用centos，所以找不到很正常。

**Comment by theratlesnake** [comment]
不是这个问题，是锐速的问题，另外，fs用不了，我已经试过了

**Comment by Sak1tama** [comment]
@theratlesnake 其实你可以自己改锐速的脚本适合ubuntu4.8，不然就没办法咯
