### ISSUE TITLE
Adrive网盘下载速度过慢如何解决？

### ISSUE THREAD

**Issue by C-Xavier** [Alvin9999/new-pac#275]
您好，我从网盘中下载文件需要十多个小时，请问怎么才能解决？

P.S.手机挂代理后下载速度很快，但是解压时提示文件损坏。

**Comment by Alvin9999** [comment]
你好，这个很好解决的。因为同一款软件，至少有2个以上的下载地址，所以你可以换其它下载地址的。

Adrive网盘大陆有的地区下载快，有的地区下载慢。手机用Adrive网盘下载地址下载文件时，提示下载成功了，其实并没有下载成功，这应该是Adrive网盘兼容性做的不好，忽略了支持手机下载。
