### ISSUE TITLE
请问这是怎么了，提示"error": "dial tcp6 [2a00:1450:400a:2::8]:443: connectex: 向一个无法连接的网络尝试了一个套接字操作。"

### ISSUE THREAD

**Issue by houhouwei** [Alvin9999/new-pac#276]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2a00:1450:400a:2::8]:443: connectex: 向一个无法连接的网络尝试了一个套接字操作。"
}

上不了了，，变成这样

**Comment by Alvin9999** [comment]
提示表明你的电脑没有成功开启ipv6，我分享的GoAgent ipv6版和GoProxy ipv6版，这两款版本使用前需要按照使用说明文档将电脑开启ipv6，不然用不了。你可以按照使用说明文档或者 [最新ipv6开启方法](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95)来将自己的电脑开启ipv6。

如果ipv6无法开启成功，可以用其它类型的软件，其它类型的软件不需要开启ipv6。

**Comment by Alvin9999** [comment]
这个问题有代表性，所以把这个帖子加精了。。。

**Comment by houhouwei** [comment]
这样是吗。。重装了系统，我就点了一键开启ipv6，这个没设置

**Comment by houhouwei** [comment]
哈哈，一不小心就加精了，受宠若惊

**Comment by houhouwei** [comment]
开启之后还是不行，是不是路由器也要开启？

**Comment by houhouwei** [comment]
我把ipv6改成自动获取就行了。。。

**Comment by Alvin9999** [comment]
OK，能用就好。这可能跟每个人的电脑系统或环境有关，有的系统设置成固定的才行。

**Comment by liuujuu** [comment]
win10的ipv6都是自动开启的吧

**Comment by Alvin9999** [comment]
@liuujuu  你的是吗？有的win10好像不行

**Comment by liuujuu** [comment]
互联网设置那里ipv6的前面的勾选上了呀
