### ISSUE TITLE
发现访问xys.org无法打开txt，以及xys.textx.net无法载入，提示1个资源未加载

### ISSUE THREAD

**Issue by birdest** [Alvin9999/new-pac#277]
使用的是Chrome53_gop_ipv6_v2017.10.26
教育网,访问twitter正常

**Comment by Alvin9999** [comment]
把浏览器代理切换成全局代理再打开，如图：
![default](https://user-images.githubusercontent.com/12132898/36028238-32f17086-0dd9-11e8-9c80-80bdb8a9495d.PNG)

**Comment by houhouwei** [comment]
请问你能上汤不热吗？

**Comment by birdest** [comment]
谢谢！我很奇怪那天为什么没成功。。我记得尝试过的
