### ISSUE TITLE
阿里云ECS上面可以安装ss服务器吗？

### ISSUE THREAD

**Issue by confidence68** [Alvin9999/new-pac#278]
阿里云ECS上面可以安装ss服务器吗？会不会被屏蔽掉？

**Comment by Alvin9999** [comment]
有被屏蔽的风险存在。

**Comment by jjandnn** [comment]
可以，但不建议。首先你装的线路选择，一定要注意。其次流量特征在每次搞运动的时候，国内这几家一定是先接受匹配的。呵呵。如果ss，你用ecs连个手，回头停了。找家好服务商，自己玩的才安心。
