### ISSUE TITLE
非常感谢！请教一些关于网速的问题。

### ISSUE THREAD

**Issue by lodagoss** [Alvin9999/new-pac#279]
Alvin9999你好，特别感谢分享科学上网心得。我最终使用的vultr自建ssr服务器，有一些问题想请教一下：

1、我挑选了很多节点，然后用cmd输入ping -t -n 20测试延迟，发现响应速度都在200-300ms之间，最终选择了丢包率最低的西雅图节点。请问这个速度是正常的吗？这种测速方式是恰当的吗？有更好的测速方法吗？
2、我按照说明选择了最便宜的5美元每月的最低配置，但我看配置也影响带宽，请问这个对速度没有影响的吗？
3、还有哪些方法可以提升科学上网速度？
4、vultr上server type——application中有OpenVPN选项，这是不是就是已经设置好了的？——自己已经试过了，不能连手机，而且不知道为什么我这连接不上。。。
5、有没有必要设置防火墙？

另外，分享一下我在操作中遇到的问题。我用你的第一个链接下载了xshell5，提示找不到mfc110.dll，排查了很久问题最终发现需要在根目录运行update更新到最新版本。

再次感谢，么么哒！

**Comment by redapple0204** [comment]
有钱用香港的吧

**Comment by jjandnn** [comment]
1-vultr美国的线路200-300很正常，并不糟糕。测速大同小异，最简单的是站长工具，呵呵。测试方式不决定你的速度。
2-你是设置ssr，5美元的配置绰绰有余，很多小伙伴以为把自己的小鸡升配，掏钱就会飞快。我想告诉小伙伴们，no，不是。决定你速度的核心是服务商的带宽，线路。如果不是线路决定，那外面的隧道商还开公司做服务干嘛呢！so，ssr，5美元ok。你会发现，如果，你不做生意，就是自己玩，那简直就是浪费。
3-ssr干完，加速是必须的，比如bbr。我推荐bbr魔改。
4-openvpn，哈哈，你已经用了ssr，请和用不着的技术告别吧。就像将来你抛弃v2ray后，发现更牛的方式时，眼前这些名词虽然还会出现，但只是谈资。如果你要实现openvpn的隧道功能，那就sstap或 Proxifier。请明白一件事情，我说某种技术过时，是针对普通用户的使用目的，你只是为了fq，那就没必要openvpn。因为他的特征虽然比起以前的两个协议可以自定义，但，也已经over。
5-防火墙，你装系统，开机，ok，防火墙就启动了。现在的服务商都直接启动。linux是自带的，即iptables。干啥用？端口管理。so，请把ssh端口默认22换一个。换的那一天，你就可以看到自己已经被攻击多少次了。一般来说，2个月5w次暴力破解很合理。你不是买独立主机，你是买云机，啥意思？压根没有你那机。打你，就是打你的端口。获取其中的信息，数据。

你写的有关xshell5。作为ssh管理软件，商用是要收费的，非商用不用。如果你不是要用很多功能，就是建个小站、甚至就ssr，那这款软件对你来说没啥大用处，因为putty+winscp戳戳有余。
最后，哈哈，虽然遗憾，但还是要告诉你一句话，在我之前的二楼的那句回答叫真理。这是所有fq的人多年后唯一的共识。为什么？因为路近呗。
很多小伙伴本能的以为香港回归，所以，不能香港，得美国才能看到全世界，服务商也必须是美国的。这是因为你不了解基本技术常识。你用阿里的国区以外机子一样翻不是吗？你用阿玛逊中国的机子，线路在里边，一样死。
速度香港平均20-30，美国平均140-400，韩国55-90，日本55-120。
这就是合理。

**Comment by Alvin9999** [comment]
1.ping值低的不一定速度就快，楼上也说了，速度除了和ping有关以为，还和服务器带宽、服务器线路、你的宽带线路有关。最好的办法是把账号搭建并进行了bbr加速，手动测试账号的速度，这样最直观。

2.如果当前服务器位置搭建的账号速度不满意，那就换服务器位置

3.bbr加速或锐速加速，但锐速加速需要换内核，不适合新手，如果自己想试试可以网上搜索教程，我觉得两个差不多

4.不是。

5.没有必要设置防火墙。

**Comment by lodagoss** [comment]
感谢大佬们的解答，么么哒！
