### ISSUE TITLE
扩展丢失怎么办？

### ISSUE THREAD

**Issue by Jason4774** [Alvin9999/new-pac#28]
你好，我自己也配置绿色的浏览器，但是遇到自己配置的谷歌在别人的电脑上使用，很多人都会出现扩展程序一个都没有加载的情况，需要重新覆盖安装crx文件一次，很麻烦，所以请问 你知道怎么解决吗？谢谢、

**Comment by Alvin9999** [comment]
如果你用的是谷歌浏览器36以上的版本，这是没法制作便携版的，也就是如果你用的谷歌浏览器版本较高，那么换台电脑后就没法使用扩展；原因是谷歌官方有一种验证机制。这也是为什么我用36版本的谷歌浏览器，然后内置内核升级压缩包的原因。

解决办法：用36或以下版本的谷歌浏览器来配置。

**Comment by Jason4774** [comment]
谢谢你的回复，就是我自己电脑上没问题，但是我分享给别人使用的时候就有些人会丢失扩展，有些还是不会，我找了很多地方都没办法，试过只有覆盖安装扩展才能解决，覆盖安装扩展后还是能读取配置里面扩展的那些设置文件，只是覆盖安装扩展的话比较麻烦，但是又比较喜欢用新的。
另外想问一些问题，就是安装第三方扩展的问题，有一些第三方的只是有时候不能启用，这种可以通过adm策略来解决，但是有些第三方的好像是从52开始会损坏，所以这种我只能通过加载解压后的扩展文件夹来解决，但是这种方法会导致每次打开浏览器会提示让我停用加载解压的那些第三方扩展。很多网上的老方法感觉还是不行，不知道你有什么方法吗？关于这个第三方扩展。
谢谢你。

**Comment by Alvin9999** [comment]
如果是分享给别人使用的话，可以分享我发布的浏览器，很方便的，解压后即可使用。

我对第三方扩展不是很了解，帮不了你。

**Comment by Jason4774** [comment]
谢谢，请问在什么地方可以下载老版本的浏览器离线安装包呢?
另外问一下你升级内核那个【是否是必须先打开一次低版本的浏览器】，然后再来强制关闭这个浏览器并升级新的浏览器，我想如果不打开低版本的浏览器直接升级内核的话是不是没有用呢？因为我想如果直接升级浏览器内核的话相当于没有低版本浏览器什么事，和原来自己直接打包最新版浏览器一样呢？请问是不是呢？

你的浏览器很好用，我用的是耍下的补丁，功能还挺多的，mychrome的话我用过，但是功能少些，然后有些更新地址不能用了，甲壳虫很久没更新了，然后我自己也配置了浏览器，过一会我给你发一个我的试试，我是结合了网上很多浏览器里面的我觉得有用的东西，包括你浏览器里面的pac，不知道你是否知道耍下的更新器，给你发个我刚上传的视频先。https://www.youtube.com/watch?v=tyL1C9Nt8DI

再次谢谢你。我弄好那个内核升级后给你发个我配置的，用耍下的更新器还是可以升级内核，挺方便的。

**Comment by Jason4774** [comment]
mychrome的话支持xp，耍下的补丁最新版的不支持xp，所以这两个工具都还是挺好用的。反正配置都可以通用。

然后我还发现内核升级的时候如果是升级到低版本，比如49，那么stylish样式会丢失，只有自己备份恢复。

**Comment by Jason4774** [comment]
关于那个内核升级，那个一键启动bat是升级内核的时候用还是平时启动都用它，平时启用应该是用mychrome吧？那么那个bat文件的作用是？里面的参数加在mychrome里面还是一样，所以不知道这个bat文件有什么用呢？

**Comment by Jason4774** [comment]
遇到一些问题，你能帮忙一下吗？我的qq:970852638.

**Comment by Alvin9999** [comment]
你好，请按照文件夹里面的《Chrome内核升级方法.rtf》升级内核即可，步骤很详细的。如果你没有按照步骤来操作造成一些错误的话，可以重新解压再操作。

至于你说的用第三方软件来升级内核，目前并没有这个打算，我觉得现在的方法挺好的，XP系统和win7或以上系统都可以直接用《Chrome内核升级方法.rtf》升级内核，而且软件里面内置了不同系统的升级包。而且，根据之前别人的反馈，目前如果升级到54或以上版本，扩展会丢失，所以目前完整版里面最高内核为53版本，个人认为足够用了。

**Comment by Jason4774** [comment]
谢谢回复，我自己想把我自己的配置加进去，也就是user  data  文件夹，但其他的东西用你的，结果有点问题，可能配置是我最新版浏览器里面的，所以不行，不知道怎么解决呢？

发自我的 iPhone

在 2017年1月20日，07:40，自由上网 <notifications@github.com> 写道：

你好，请按照文件夹里面的《Chrome内核升级方法.rtf》升级内核即可，步骤很详细的。如果你没有按照步骤来操作造成一些错误的话，可以重新解压再操作。

至于你说的用第三方软件来升级内核，目前并没有这个打算，我觉得现在的方法挺好的，XP系统和win7或以上系统都可以直接用《Chrome内核升级方法.rtf》升级内核，而且软件里面内置了不同系统的升级包。而且，根据之前别人的反馈，目前如果升级到54或以上版本，扩展会丢失，所以目前完整版里面最高内核为53版本，个人认为足够用了。

**Comment by Alvin9999** [comment]
你用的浏览器内核是多少版本

**Comment by Jason4774** [comment]
版本 55.0.2883.87

**Comment by Jason4774** [comment]
你能帮忙一下吗？我的qq:970852638.

**Comment by Alvin9999** [comment]
太高了！你用53再试试看，不好意思，我加qq的

**Comment by Alvin9999** [comment]
根据之前别人的反馈和我自己的测试，如果升级到54或以上版本，扩展会丢失

**Comment by Jason4774** [comment]
不是，我现在是55.然后降级用过49，35.36.53.我想可能我现在user data里面的某些东西比较新，所以低版本不太适用，所以不知道怎么解决。昨天有人说修改chrome.dll可以，但是找不到帖子了。

**Comment by Jason4774** [comment]
我55降级到49,53都没问题，降级到36就丢失扩展，然后说我什么个人资料比较新，一直弹出这种提示，

**Comment by Jason4774** [comment]
我的想法就是现在要丢扩展，但是想按你的那种分享出去开始是36版本，然后别人手动更新内核就不会丢失扩展了。但是现在我降级到36的话扩展都丢失了，而且还会弹出个人资料比较新的那种提示，但是接着升级内核还是有扩展。但是我自己没有测试环境。因为我看你36里面的扩展都是在的。

**Comment by Jason4774** [comment]
https://pan.baidu.com/s/1geKxKX1
这个是我的，你能帮忙看看吗？

**Comment by Alvin9999** [comment]
今天我很忙，空了帮你看看，到时候给你反馈

**Comment by Jason4774** [comment]
好的，谢谢

**Comment by Alvin9999** [comment]
我试了你的软件，扩展在的，可以翻墙

**Comment by Jason4774** [comment]
恩。就是之前还是有一少部分人说会丢失，本身他这个shuax补丁好像里面修改了什么有解决扩展丢失的方法，但是可能也是随着版本的更新，所以还是有一部分人会丢失，所以我现在自己打包了所有的扩展，覆盖安装，虽然麻烦，但是还是能读取一些扩展的设置。

**Comment by Jason4774** [comment]
我里面封装了你的Pac.对了，你的那个备用pac不能用，是在维护吗？还是说以后都不要那个pac了？

**Comment by Alvin9999** [comment]
曾经有两个备用pac，你说的应该是早期的那个pac吧，是有一个早期的pac不维护了

**Comment by Jason4774** [comment]
我这个浏览器是前两天看了你最新更新的，然后用了你所有的pac。里面有一个备用，https://git.oschina.net//kebi2014/pac/raw/master/pac3，这个好像不能用了。

**Comment by Jason4774** [comment]
我这个浏览器结合了网上各种软件，还是比较全吧，有什么好的建议或好的扩展脚本样式推荐吗？

**Comment by Jason4774** [comment]
自动判断是否需要代理用的是meow。

**Comment by Alvin9999** [comment]
你说的那个pac，我这里可以用的。

说实话，目前没有更好的建议。

你很细心，给你点个赞。

**Comment by Jason4774** [comment]
那可能我当时有点问题，我回头加上

**Comment by Jason4774** [comment]
对了，你的pac对于google.com有点问题，经常403.

**Comment by Alvin9999** [comment]
没有
