### ISSUE TITLE
SSR延迟测试有数据却连接不上怎么回事？

### ISSUE THREAD

**Issue by ekingling** [Alvin9999/new-pac#280]
SSR用某个账号能顺利翻墙，同时测试了另一个账号延迟有显示数据，但连接之后却翻不了墙了，测试该账号延迟也没有了数据，这是怎么回事？测试延迟不是出现null、timeout等提示才表示用不了吗？

**Comment by Alvin9999** [comment]
测试延迟即ping 服务器ip，只能表明该ip是否被墙，不能表明ssr账号是否可用。

**Comment by Alvin9999** [comment]
比如，一个服务器还没有开始搭建账号，如果该服务器ip没有被墙，此时你测试其延迟，是有数据的。

**Comment by ekingling** [comment]
哦，学习了~
