### ISSUE TITLE
ssr 账号昨晚开始好像用不了？

### ISSUE THREAD

**Issue by Josephineduh** [Alvin9999/new-pac#281]

**Comment by Josephineduh** [comment]
所有东西都根据最近的账号更新填对了，网络也没有问题，就是上不了

**Comment by 308901951** [comment]
确实，到现在也还是不行

**Comment by jjandnn** [comment]
兄弟，不是昨晚，是前天下午开始的，GFW杀。主动诱探，全灭。我死掉两台，身边兄弟的，亚洲系统的，挂一大批。防火墙明显升级了。自己去ping一下ip，十有八九是国内全部不通，国外流畅无比。这次比1.24还牛。

**Comment by jjandnn** [comment]
换vps，换ip。没有其他方法，至少暂时还没想出来更高级的应付ip端封锁的方法，别指望换个brook、v2ray、或者反向伪装解决，那些是用来安慰小伙伴们的，没实际作用。等待质变，就像当年ss登场时的那种。在此之前，稍安勿躁，累一点，手动clone吧。

**Comment by Josephineduh** [comment]
现在开始搭建ss/ssr服务器的话被封的可能性大吗

**Comment by bjnews** [comment]
原以为干掉鲁炜能出现些积极的变化，挺好的改邪归正的时机，还有这么大一只的替罪羊。。。看来还是幼稚了，低估了某党的无耻与恐惧。我一直说GF墙的存在就是明晃晃狠抽某党N个自信的老脸。

**Comment by 308901951** [comment]
不是大规模封的ssr,用的其他的ssr可以

**Comment by 308901951** [comment]
正常有人性的人都知道土共什么货色，多说无益

**Comment by Alvin9999** [comment]
免费的第一个旧金山节点国内大多数地方都没有被屏蔽，应该可以用的。其它节点等我空了再换ip。自己搭建服务器不用担心被屏蔽，因为vultr可以随意删除和开通服务器，新服务器就是新ip。

**Comment by Josephineduh** [comment]
好的谢谢
