### ISSUE TITLE
我的GOOGLE NEXUS 6P 一直无法下载系统更新包，请教解决办法！

### ISSUE THREAD

**Issue by anlexN** [Alvin9999/new-pac#283]

**Comment by Alvin9999** [comment]
这个问题我也不知道喔，你可以网上搜搜看

**Comment by cuiyuzhong** [comment]
8.1的ota么？据说是手机翻墙不行。需要路由器，或者pc翻墙，手机在热点下面就可以了。

**Comment by anlexN** [comment]
@cuiyuzhong 对! 按照你说的方法，真的成功了。但是我想问这是因为什么呢？您路由器，PC分别怎么翻墙？

**Comment by cuiyuzhong** [comment]
我有个newifi路由器刷的padavan，有ss。
电脑也是用的ssr客户端。我之前搜这个问题的时候，介绍的是个windows下面的ssr软件，有个选项是允许局域网访问，然后安卓手机的wifi代理设置成那台电脑就可以了。
不过我没试，家里windows电脑都落灰了……就用newifi翻墙升了。

**Comment by anlexN** [comment]
我的是HIWIFI极路由，您能不能帮我找一下我这个路由器的翻墙教程？您微信多少，我加你。

**Comment by cuiyuzhong** [comment]
这个是之前找的那个解决的帖子： http://jiyouhui.it168.com/thread-471891-1-1.html
刷路由器的话，我是照着：http://www.right.com.cn/forum/thread-161324-1-1.html 和 http://www.right.com.cn/forum/thread-161906-1-1.html 弄的。
不刷机的话，不太清楚，好久没用过极路由了，印象里好像官方插件里没有ss，可能得去极路由论坛找找。
