### ISSUE TITLE
问一下大佬怎么建立多端口 并且可以查看每个端口流量

### ISSUE THREAD

**Issue by Marrg** [Alvin9999/new-pac#285]
想问一下 怎么才能建立多端口 而且可以查看每个端口的流量 谢谢了!!!!

**Comment by Alvin9999** [comment]
如果想实现支持每个用户(端口)不同的加密方式/协议/混淆等，并且管理流量使用，可以参考多用户配置脚本：wget -N --no-check-certificate https://softs.fun/Bash/ssrmu.sh && chmod +x ssrmu.sh && bash ssrmu.sh 备用脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssrmu.sh && chmod +x ssrmu.sh && bash ssrmu.sh 安装后管理命令为：bash ssrmu.sh

注意：这个多用户配置脚本和教程内容的脚本无法共存！要想用这个脚本，把之前的脚本卸载，输入管理命令bash ssr.sh ，选择3，卸载ShadowsocksR即可卸载原脚本。

**Comment by Marrg** [comment]
谢谢 谢谢
