### ISSUE TITLE
如何用ss玩外服游戏呢

### ISSUE THREAD

**Issue by Marrg** [Alvin9999/new-pac#286]
如题 能用ss 玩外服 而且每个连接端口都可以玩 类似于vpn吧 怎么做呢

**Comment by jjandnn** [comment]
用sstap的客户端，其他不用动，最简单，直接udp真全局。sstap不会用或设置，去看一下逗比根据地toyo的教程，网上也很多。

**Comment by Alvin9999** [comment]
sstap配置教程：https://www.jianshu.com/p/519e68b74646

**Comment by Marrg** [comment]
哇谢谢大佬  谢谢

**Comment by Marrg** [comment]
sstap连接后，由路由管理添加用户ip，那么添加了ip的用户连接ss/ssr，就可以直接玩外服游戏了吗 ?ss/ssr上是不是还要选什么代理模式呢?  还是说也要启动sstap ?

**Comment by Marrg** [comment]
。

**Comment by Alvin9999** [comment]
没有用过，可以自己来测试，一路思路不行的话，就换另外一种思路

**Comment by Marrg** [comment]
好的谢谢

**Comment by jjandnn** [comment]
@Marrg 解决了没？sstap，设置和ssr的其他软件没区别，它主要是指定全局所有流量走socks，这样，你整台机器就进入了类似vpn的隧道。链接了，就直接玩，因为应用内部的流量被指定了通路，ss的全局是原本所有调用浏览器的流量走socks。代理模式就是全局-内置规则。在规则上注意，自己可以设定屏蔽掉迅雷，当然也可以不设定，sstap是我用过的最好最稳定的真全局客户端。简单说，我用它不是打游戏的，主要用于跨区跨服消费注册，所以，就这点，你就知道它是干嘛的。很多兄弟买了别人账号，线路，然后去上netflix、跨区ps4，结果失败，以为是供应商线路毛病，不是，就是客户端问题，是流量没有走代理。对面的服务器一下子就把你秒了。一般来说，现在的v2ray，ssr，小火箭，土豆丝，surge，brook都可以满足日常，但是你要跨区游戏，那就得模拟vpn。

**Comment by nbrnred** [comment]
SSR有时能用，有时不能用，更新也不一定能用，总之断断续续不怎么稳定，不过比IPV6 Go版还是稳定好用很多。
