### ISSUE TITLE
昨天半夜突然连接不上了

### ISSUE THREAD

**Issue by jackxavierman** [Alvin9999/new-pac#287]
用了半年很稳定 昨天半夜开始突然连不上
手机显示可以正常连接vpn但是没有网络，Xshell链接不上服务器也ping不通，vutrl官方的终端可以连接上可以ping通，求解。。

**Comment by jackxavierman** [comment]
用vutrl重新申请ip Xshell还是连接不上

**Comment by jackxavierman** [comment]
Xshell提示信息
Connecting to 45.xx.xx.xx:22...
Could not connect to '45.xx.xx.xx' (port 22): Connection failed.

Type `help' to learn how to use Xshell prompt.

**Comment by jackxavierman** [comment]
15个端口全部连接不上

**Comment by Alvin9999** [comment]
手机上的vpn图标不能作为判定依据，如果随便填数据，手机上还是会显示vpn图标，但是上不了国外网站。根据你的描述，应该是你的vps ip被墙了，你可以重新开心的服务器，开通新服务器后等待5分钟，再用xshell去连接vps，如果同一个位置，你开了3个以上的服务器还是不行的话，那就换其它位置的服务器，直到开到没有被墙的ip。

**Comment by jackxavierman** [comment]
原来用了半年那个是NYC的ip，刚才又换了一个东京的ip，还是连接不上xshell，都没办法部署。。但是我用vrtul自带的noVNC部署了一下，部署成功了 但还是链接不上。

**Comment by jackxavierman** [comment]
换了四个地区的不同ip了，xshell全都连不上。。好绝望

**Comment by Alvin9999** [comment]
你排除一下是ip被墙了，还是你的xshell的问题。用电脑的运行，输入cmd，弹出黑色对话框，输入：
ping 123.123.123.123   （把ip换成你的vps ip）
或者你里面开几个新的服务器，把ip发出来，我看一下。

**Comment by Alvin9999** [comment]
我刚试了一下，开了2台服务器，1台ip被墙，另外1台是好的，说明能开到好的ip的概率还挺大的。

**Comment by Alvin9999** [comment]
只要ip没有被墙，用xshell就能连上。如果ip没有被墙，用xshell还是连不上的话，估计是电脑或者xshell软件的问题。你好好排查下。

**Comment by jackxavierman** [comment]
谢谢大神，经过一天的努力，终于好了。原因就是以前那台vps被墙了，可能是我运气太好，连着开了四五个新的vps还都是被墙的，以至于我以为是我xshell的问题，排查了一下xshell并没有问题，所以又碰运气开了两台，最后一台chicago的可以用了，但是我系统选择的是7不是6，不知道以后会不会有一些影响，总之可以用了。
再次谢谢大神一天的帮助。

**Comment by Alvin9999** [comment]
不客气哈

**Comment by qrzbing** [comment]
表示我的也是。。感觉最近又严了很多啊

**Comment by Alvin9999** [comment]
@qrzbing  因为最近要开会，且决定要修改宪法。

**Comment by moxixuan** [comment]
哈哈，不能说决定啦，中共只是“建议”，跟不能说钦点一个道理。。。

**Comment by jjandnn** [comment]
@jackxavierman 楼上49大说的是最近的正解，我补充一下，大伙儿90%的人出问题在东京、香港、新加坡。请注意，阿里也好，gcp也好，linode和搬瓦工不用说了，至于vutrl就是灾难，他们家近期都换不出了，我最高纪录是，整整换了一天，没换到一个不被ban的。年30大屠杀那天，我被干掉4台，昨晚一台。封的是ip段，ip段，ip段，一锅粥里有一个流量特征明显，其余全部爆，一刀切。给大伙儿说个简单可容易忽略的常识，独立ip对于运营商来说是固定量，是珍贵的。也就是说，死一个，少一个，哪怕他财大气粗如gcp，也解决不了客观问题。所以，敏感期，你换亚洲主力区，他们换给你被ban的ip，概率太大了。为了保证工作正常，建议，近期，不要亚洲换亚洲，本机房换本机房，备用gcp北美和aws的北美免费。否则，太耽误事情了。讲个小技巧，当你在流行的运营商这里换ip，实例一开，发现ip段同前面被干的一个段，别犹豫，别浪费时间，直接移除，再来，不要clone，镜像一遍，最少也要20分钟啊，等你putty，xshell了，半小时没了。另，就我常年被封的经验来讲，时间一过，ip就又恢复正常了，不是特别紧急要用，就等几天，尤其是服务商如果是你认识的，自己的兄弟公司，给人一点体谅（呵呵，不是的话，没商量，哈哈）。

**Comment by Alvin9999** [comment]
@jjandnn 亚洲的地区vps用的人多，被墙的ip也多，建议选择非亚洲地区的。延迟高一点，但是配合加速还是可以的。

**Comment by jjandnn** [comment]
@Alvin9999 哈哈哈，英法意德荷我都有用过，唯独没想到非洲这茬，感谢提示，去试试，有意思的想法。
