### ISSUE TITLE
怎么最近服务器不好开了，而且速度慢了很多!

### ISSUE THREAD

**Issue by Marrg** [Alvin9999/new-pac#288]
前几天开的才100多延迟 这几天开的300-400，卡的很，bbr加速也开了，怎么会突然这么卡啊，而且 试了很多服务器，好像只有新加坡的能用啊，其他几个国家的x shell 根本连接不上，怎么解决呀。

**Comment by Marrg** [comment]
而且看了bbr加速还是卡

**Comment by Marrg** [comment]
服务器也不好开，好多都连接不了

**Comment by Alvin9999** [comment]
一般晚上高峰期的速度会比白天慢，晚上是翻墙高峰期。多试试吧，创建服务器成本很低，你把vultr15个地区的服务器位置都试试看，要每个都开到可用ip，然后进行测试。还有，影响速度的因素有很多，比如你的宽带类型，相同的服务器位置搭建的ss/ssr账号，使用移动、电信、联通的速度会不同，这是由于宽带运营商的国际出口带宽和线路不同导致的。

**Comment by Alvin9999** [comment]
近期服务器和以前相比是不好开。昨天我开了4台，2台是可用ip，2台是被墙ip。

**Comment by Marrg** [comment]
好的谢谢
