### ISSUE TITLE
感谢开发者

### ISSUE THREAD

**Issue by ghost** [Alvin9999/new-pac#29]
我是@YANZHONGJIAN，通过翻墙调查来到这里的。有帮助谢谢

**Comment by 18833801750** [comment]
Σ( ° △ °|||)︴我最讨厌被墙了

**Comment by 18833801750** [comment]
Twitter上的石斑鱼大爷，多谢分享。

**Comment by Alvin9999** [comment]
不客气！我也很讨厌被墙

请问你说的哦“翻墙调查”是什么，可以给你地址么

**Comment by 18833801750** [comment]
Twitter 上 石斑鱼大爷头像下边的链接

欢迎使用 https://t.co/LebEsKvN5K 大杀器

本站所有服务完全免费，不限制网络速度和流量

请遵守服务条款，不要公开节点信息，不要滥用服务

欢迎经常关注这里，至少每周来一次，以获取最新信息

自由上网 <notifications@github.com>编写：

**Comment by 18833801750** [comment]
SSR 不稳定配置好后用不几分钟就掉线，鱼大爷给的IP人数过多？🐒去Google查找了下gfw.press大杀器根据关键字找到了这里

**Comment by 18833801750** [comment]
http://gfw.press/ 

自由上网 <notifications@github.com>编写：

**Comment by Alvin9999** [comment]
原因如此，明白了

**Comment by theratlesnake** [comment]
@Alvin9999  祝您新年快乐，感谢您的努力付出，也祝楼主和各大有良知的网友们新年快乐，同时祝愿GFW早日崩塌，方校长早日被病魔带走！

**Comment by 18833801750** [comment]
thank you.  新年快乐˒˒📢₍₍🐔₎₎🎉

theratlesnake <notifications@github.com>编写：

**Comment by Alvin9999** [comment]
新年快乐
