### ISSUE TITLE
google可以打开，但是搜索出不来，请问怎么处理？

### ISSUE THREAD

**Issue by isoliyang** [Alvin9999/new-pac#290]
无法访问此网站
ipv6.google.com 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by Alvin9999** [comment]
你好，请告知你用的软件具体类型。我分享的软件有很多。。。

**Comment by isoliyang** [comment]
Chrome63_64bit_GP_ipv6_2017.12.26.7z

**Comment by isoliyang** [comment]
ipv6替换为www可以了，多谢大神！
