### ISSUE TITLE
从昨天晚上开始，ipv6大量黄字，无可用IP，更新了新版本还是不行

### ISSUE THREAD

**Issue by kaikaisnow** [Alvin9999/new-pac#292]

**Comment by kaikaisnow** [comment]
是谷歌版本，上传不了图片

**Comment by Alvin9999** [comment]
首先检测一下电脑系统是否成功开启了ipv6，使用说明（必看）文档有提到

**Comment by kaikaisnow** [comment]
已经开启了，用了好久的ipv6，就是这两天谷歌版本用着用着突然就大量黄字，今天晚上一点也没有可用IP了，是不是我登陆的地址被列入黑名单了。现在改用火狐了。

**Comment by Alvin9999** [comment]
你的问题是火狐ipv6版能用，谷歌ipv6版不能用，对吗？

**Comment by kaikaisnow** [comment]
Chrome53_goa_ipv6_v2018.3.3，Chrome64_64bit_GA_ipv6_2018.3.3，这两个版本 你试一下

**Comment by kaikaisnow** [comment]
是的

**Comment by Alvin9999** [comment]
测试没问题。谷歌ipv6版和火狐ipv6版配置信息、翻墙方式一模一样，只是浏览器类型不一样，所以你的问题有点奇怪哦。如果你的谷歌ipv6版用不了，理论上火狐ipv6版也应该用不了才对。你试试谷歌GoProxy ipv6版看看

**Comment by kaikaisnow** [comment]
昨天晚上我用谷歌下载了一些比赛视频，是不是我因为产生了大量流量？我换了谷歌的版本，刚开始能用，过一会就又不行了。所以我现在干脆先用火狐吧。不知道过段时间会不会好。

**Comment by Alvin9999** [comment]
不太清楚。你有没有用国产杀毒软件？

**Comment by kaikaisnow** [comment]
今天火狐也都黄字了，是不是得重新设置一下ipv6了？

**Comment by kaikaisnow** [comment]
用了ipv6好几个月，一直都挺好的。

**Comment by kaikaisnow** [comment]
我家用的电信，会不会和这个有关系？

**Comment by Alvin9999** [comment]
只能说有可能，影响网络的因素有很多。你可以按照最新的ipv6开启方法https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95，更换一下开启ipv6.bat脚本里面的teredo服务器地址，默认ipv6服务器为teredo.remlab.net

**Comment by hedaiwei** [comment]
您好，我的也是前两天碰到的这个原因，突然一堆黄字，没有可用的ipv6，更新了ip地址也没有用，就是一直找不到可用的ip，不知道是为什么

**Comment by Alvin9999** [comment]
@hedaiwei  按照上面同样的方法试试更换teredo服务器地址。原因可能是你所在地区对ipv6通道受到了干扰。

**Comment by kaikaisnow** [comment]
@Alvin9999 谢谢 更换了 就好了
