### ISSUE TITLE
登录论坛没反应

### ISSUE THREAD

**Issue by hun200** [Alvin9999/new-pac#295]
谷歌浏览器低内核GoProxy ipv6版 和高内核都登录论坛没反应，就是输入论坛的用户名和密码，确定以后没反应，不管是什么论坛

**Comment by Alvin9999** [comment]
都是国外论坛吗？有可能是论坛对谷歌ip作了限制。

**Comment by jacknnnbauer** [comment]
老哥，你的网址挂了。有新地址吗？

**Comment by asmosn** [comment]
终于复活了，植树节愉快！

**Comment by moxixuan** [comment]
之前发生了啥？登不上了？

**Comment by rave666666** [comment]
有些网站提示证书无效！如deviantart.com，patreon.com等

**Comment by Alvin9999** [comment]
@rave666666  
测试没有问题。如图：
![default](https://user-images.githubusercontent.com/12132898/37346767-38dd3232-270b-11e8-8667-af2796084430.PNG)

你用的什么版本呢?

**Comment by rave666666** [comment]
用的是Chrome64_32bit_GP_ipv6_2018.3.3版本
提示GoProxy证书无效

**Comment by rave666666** [comment]
@Alvin9999

**Comment by Alvin9999** [comment]
@rave666666 把浏览器切换成全局代理看看
