### ISSUE TITLE
自己搜Ip的教程失效了，请问新的方法是什么呢？可以更新一下教程吗？谢谢。

### ISSUE THREAD

**Issue by Jason4774** [Alvin9999/new-pac#296]
自己搜Ip的教程失效了，请问新的方法是什么呢？可以更新一下教程吗？谢谢。

**Comment by Alvin9999** [comment]
哪款软件？

**Comment by xugaohui** [comment]
@Jason4774 搜ip最好的软件目前是这个:https://github.com/Kisesy/gscan_quic
只需要ipv4就好了,然后再配合goproxy r1651版开启quic,播放视频开几个窗口都用 1080完全没问题.只是用它下载直链视频文件时快时慢.下载小文件也一样.

**Comment by caofengzi** [comment]
goproxy本來就不能下載超過32m的大文件。
