### ISSUE TITLE
群主！！新版本SS，怎么看不了直播视频youtube呢？

### ISSUE THREAD

**Issue by yy0535** [Alvin9999/new-pac#297]
群主！！新版本SS，怎么看不了直播视频youtube呢？新版本SS能看视频线路真的太少了，有时很卡

**Comment by Alvin9999** [comment]
所有的直播视频都看不了吗？至于速度，还有提升的空间，会逐步寻求一个平衡点。

**Comment by yy0535** [comment]
群主，只能看东森直播视频，其他视频都看不了，群主你试试，其实，我最想看的是cctv直播
