### ISSUE TITLE
群主，不知道为啥免费账号都不能用了 ShadowsocksX-NG1.3.9

### ISSUE THREAD

**Issue by phpmatt** [Alvin9999/new-pac#299]

**Comment by Alvin9999** [comment]
因为刚刚更新了一下，你再试试看

**Comment by phpmatt** [comment]
用的服务器4，ip可以ping通，就是打不开网站 Twitter YouTube

**Comment by Alvin9999** [comment]
可能是服务器4在你所在的地区不太好用的缘故，你可以换另外的服务器

**Comment by phpmatt** [comment]
谢谢，试了都不能用，010地区。。

**Comment by Alvin9999** [comment]
从服务器运行状况看，表现良好。你是之前能用，就今晚不能用吗？ 账号信息检查一下是否填写正确

**Comment by phpmatt** [comment]
之前能用的，参数也正确，从过完年就不能用了

**Comment by phpmatt** [comment]
搞定了，原来是我本机一个服务占用了PAC监听端口，多谢！
