### ISSUE TITLE
台湾的网站上不去

### ISSUE THREAD

**Issue by marlenxmai** [Alvin9999/new-pac#3]
我有海淘的需求 
我发现台湾的网站不容易上去 需要刷新好几次才出来
有的直接是就打不开
请问是什么问题
我主要想要上这个网站
http://www.kingstone.com.tw/

**Comment by Alvin9999** [comment]
你好，谢谢你的反馈。这个网站没有被墙，用普通浏览器就能打开。或者你可以用PAC版或蓝灯新版，我试了可以。

**Comment by marlenxmai** [comment]
我用的最新版本的 GoAgent 上不去 
很多台湾的网站也用不了
这个网址是有被墙的
我手机如果用翻墙软件才能打开
我试一下其他的版本看看
我这边的天朝国内啊 会不会是这原因个

**Comment by Alvin9999** [comment]
应该是不同的地区网络封锁不同，所以造成了这种情况。有些地区能打开，有些地区打不开。
