### ISSUE TITLE
关于wiki的GoAgent的问题

### ISSUE THREAD

**Issue by tianmuabc** [Alvin9999/new-pac#30]
由于换了新电脑，安装刚下载的最新版的GoAgent版，按照教程一步步安装，本来可以翻墙，在mychrome上登录谷歌账号后就无法翻墙了，这是什么原因，安装了n遍。。。

**Comment by Alvin9999** [comment]
你好，我分享的GoAgent版不用安装，下载压缩包后解压缩，然后打开一键启动程序“chrome+.exe“即可。如果你是win7及以上系统，第一次打开时右键chrome+.exe，选择“以管理员身份运行”

**Comment by tianmuabc** [comment]
首先感谢你的软件！
我也是那样做的，然后就直接可以翻墙，打开YouTube也可以看，接着关了chrome+.exe，然后双击打开mychrome，然后登陆原来那台电脑的谷歌账号同步所有数据，然后立马就不能翻墙了，今早又试了只同步书签，结果能打开谷歌应用商店，却用不了搜索了，这是什么原因，问题想来想去就出在同步设置上，该怎么做？

**Comment by tianmuabc** [comment]
实在不行加下QQ，帮我远程操作下下。。我qq1500286836

**Comment by Alvin9999** [comment]
不好意思，我不加qq的。我明白你的意思了，你是想同步自己原先谷歌账号的数据。说实话，我不清楚是否能做到，因为我分享的是36版本的便携版浏览器，你可以先尝试着按照内核升级使用说明升级一下53内核（如果你是xp系统，升级到49内核），然后再登录你自己的账号看看是否能同步以及翻墙。

另外，我自己也有普通的谷歌浏览器，我翻墙时就用翻墙谷歌浏览器，不翻墙时就用普通的谷歌浏览器，我是这样的使用习惯，供你参考。

**Comment by tianmuabc** [comment]
还是不行，现在只能未登录用，同步就会翻不了墙，只同步书签能打开商店，搜索却用不了，这是什么原因

**Comment by Alvin9999** [comment]
我也不知道。建议你分开使用翻墙和普通浏览器。如果你觉得不方便，可以把翻墙浏览器的一键启动程序弄个快捷方式，然后把这个快捷方式弄到桌面上去。
