### ISSUE TITLE
GoAgentIPV6版本没有goodIp

### ISSUE THREAD

**Issue by hedaiwei** [Alvin9999/new-pac#300]
您好，请问最近发现goagent的ipv6版在开启后一直没有goodIP，导致上不了网，请问这个有解决办法吗，多谢。我的IPV6是可以成功开启的，但是就是没有办法找到goodip，更新之类的办法都没用，原先一直好好的，前几天突然就这样了，不知道为什么

**Comment by Alvin9999** [comment]
有可能是一键启动默认的teredo服务器在你所在的网络环境不稳定的原因，你可以按照使用说明文档，手动更换一键启动里面的teredo服务器地址，文档里面有很多备用的地址。

**Comment by xugaohui** [comment]
@Alvin9999 请保持继续更新GoProxy Quic版,它在线看视频最快最稳定,只是用它下载油管视频文件就不怎么样..

**Comment by Alvin9999** [comment]
@xugaohui  谢谢反馈。

**Comment by nbrnred** [comment]
ipv6不稳定，不是用不了多久，就是直接用不了，经常反复如此。

**Comment by Alvin9999** [comment]
@nbrnred  试试换开启ipv6.bat里面的teredo服务器，使用说明里面有具体方法

**Comment by nbrnred** [comment]
换过，都试了的，.bat修改两处服务器地址，都是要么用不了，要么用不了多久忽然就用不了了，过会或者过段时间又能用了，改好的一堆 .bat   teredo服务器地址，工具Ping和手动全改好的一堆都放那里，那个ping的延迟低点那个 .bat,服务设置自动重启，再重启，重新开启或关闭再开启微软IPV6工具等都反复试过，都是一样要么用不了，要么用一会就用不了了，挨个换也没用。WIN7.WIN8,WIN10都是如此，就差XP没试过了。估计和服务项和注册表有关。.bat自动修改的注册表可能那里有不足的地方。

**Comment by Alvin9999** [comment]
@nbrnred  
ipv6DNS 有两组:2001:4860:4860::8888 2001:4860:4860::8844  和 2620:0:ccc::22620:0:ccd::2
你可以换一组ipv6 DNS试试看。
之后，再试试这两个teredo服务器：win10.ipv6.microsoft.com 和 win1710.ipv6.microsoft.com （新增的）

因为影响翻墙的因素有很多，除了墙，各个地区封锁策略也会不一样，比如新疆连百度网盘都打不开。还有宽带运营商也有可能作限制。如果实在用不了ipv6版的话，可以换其它类型的软件。

**Comment by nbrnred** [comment]
IPV6DNS设置了四组，服务器.bat也设置了很多，不是用不了，是用不了多久，一会就无效，有时候要用XX-Net，如果XX-Net连上这个就能连上，有时候这个连上了，XX-Net才能连上，和换.bat服务器地址不一定有关系，意思是没换别的.bat地址如果这个和XX-Net任意一个先用不了，如果有一个在不换服务器的情况下IPV6连上了，另一个就能连上。用不了多久都。
