### ISSUE TITLE
怎么设置翻墙过去的IP 成为某个国家的IP 地址

### ISSUE THREAD

**Issue by Jamesowens11** [Alvin9999/new-pac#301]
我现在用的是 Chrome53_goa_ipv6_v2018.3.3 在电脑上翻墙的。

我这边怎么能够确定翻过去是哪个国家的 IP 呢， 我能设置成我想要的国家的IP 吗？

感谢了

**Comment by Alvin9999** [comment]
你好，不能，因为ipv6版用的是谷歌服务器，出口ip全是美国的。如果你对ip国家有特殊需求，建议按照自建ss服务器教程来搭建自己的账号。项目的右侧有教程。
