### ISSUE TITLE
按照教程私自架设vpn服务器会触犯天朝法律吗

### ISSUE THREAD

**Issue by lilixin** [Alvin9999/new-pac#302]
胆子比较小。听同事说。好像私自架设vpn服务器会触犯天朝法律啊，是真的吗

**Comment by Alvin9999** [comment]
ss不是vpn。上网是公民的基本权利。翻墙不建议用国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家等，这些软件与墙有合作关系。

**Comment by lilixin** [comment]
好的。非常感谢
