### ISSUE TITLE
按照教程买了服务器,试了好多次 一直上不去啊...分别试了newyork和miami两个服务器,,还是不行啊...

### ISSUE THREAD

**Issue by mengzhongtian** [Alvin9999/new-pac#305]

**Comment by mengzhongtian** [comment]
咋整啊...是这个ip地址被封了?

**Comment by Alvin9999** [comment]
你可以重新开服务器，或者换其它位置的服务器，再尝试。ping不通说明你开到的是一个被墙的ip！由于纽约和迈阿密有2.5美元的服务器，所以国内购买的人多，而这些人大多数是用来做翻墙用的，当ip被墙后，这些人会把服务器删掉，删掉后的ip并不会消失，会被随机分配到下一个开这个服务器位置的人手里，所以需要多多尝试，尤其是近期封锁加重的背景下。

**Comment by no-name2017** [comment]
@Alvin9999 话说，纽约和迈阿密的速度看youtube怎么样？

**Comment by no-name2017** [comment]
现在还有新注册赠送的活动吗？

**Comment by Alvin9999** [comment]
有的，刚看了，活动图片还在

**Comment by no-name2017** [comment]
其实我注册过了，不过一直没使用过，现在想用你的链接来注册，好像双方都有奖励？这样可以的吗？

**Comment by Alvin9999** [comment]
@no-name2017  要想参与活动，一定要满足条件：仅限新注册用户，老用户不行，充值方式是paypal或信用卡，支付宝支付不能参与本次活动，而且paypal和信用卡在vultr上从未支付过。满足条件并充值成功后，你的账号应该会多25美元的奖励，有效期1年。
