### ISSUE TITLE
打开网页提示下面这些要怎么办呢？

### ISSUE THREAD

**Issue by yizhidouzai** [Alvin9999/new-pac#306]
用GoProxy ipv6版打开youtube，facebook之类的网站直接显示这个了，怎么办呢
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2a00:1450:400e:808::200a]:443: connectex: A socket operation was attempted to an unreachable host."
}

**Comment by Alvin9999** [comment]
请按照使用说明将电脑开启ipv6

**Comment by yizhidouzai** [comment]
ipv6是开启状态的，大概用来一个礼拜后突然变成这样的，之前都是正常的

**Comment by Alvin9999** [comment]
可能是teredo服务器不稳定的原因造成的，按照使用说明手动更换开启ipv6.bat脚本里面的teredo服务器地址，然后重新运行开启ipv6脚本，至于哪个teredo服务器地址好用，需要自己来测试比较。
