### ISSUE TITLE
请问一下搭建的ss手机端总是提示ssl handshake timed out如何解决

### ISSUE THREAD

**Issue by Airmop** [Alvin9999/new-pac#307]
pc端可以正常使用，就是用Vultr的服务器，求问。

**Comment by Airmop** [comment]
有的时候还会提示connection closed by peer

**Comment by Alvin9999** [comment]
电脑能用，说明账号没有问题。如果你的vps配置了协议和混淆，但是你的手机选择的是SS客户端，那么SS客户端是没有填写协议和混淆的地方的。因此，你配置帐号的时候可以将协议和混淆设置成兼容原版，或者你的手机选择SSR客户端。

**Comment by Airmop** [comment]
我手机的客户端就是用的ssr，但还是不行，会不会是服务器配置的问题

**Comment by Alvin9999** [comment]
如果你手机和电脑都是用的wife，即网络环境完全相同，只是客户端不同，账号也是一样的，这就有点奇怪了。如果你确定账号信息没有填错，那么可以试着更改服务器配置的端口、加密方式、协议、混淆等参数。

**Comment by Airmop** [comment]
哇好神奇，我换了个端口竟然可以了。。。谢谢啦

**Comment by Airmop** [comment]
然后又出现相同问题了。。。

**Comment by Alvin9999** [comment]
把端口改成8080或443看看

**Comment by Airmop** [comment]
先谢谢大神～～～现在还有个问题就是手机用校园网认证的网络ssr无法连接，总是超时，不知道是什么问题。。。谢谢大神的耐心解答

**Comment by Alvin9999** [comment]
可能是校园网封禁了一些端口造成的。你试试80端口，这个是所有网站的默认端口。

**Comment by maianne** [comment]
请问后来是改端口解决的吗。我这边突然也遇到了着这样的情况。ios和安卓都上不去，电脑端可以。

**Comment by oceanlvr** [comment]
请问您解决了吗？我也出现相同问题。
在pc上的ssr都是可以使用的。但是安卓端不行 @Airmop

**Comment by xuexiaokang** [comment]
SSRR安卓端兼容性差造成的，目前无解，用SS安卓端一点问题都没

**Comment by LKorint** [comment]
我用的v2ray  出现这种问题我把centos的防火墙关了就行了，试过多次有效

**Comment by flybird027** [comment]
防火墙的问题，服务器检查下http和https规则 设置为允许ssr的端口或者干脆全部允许，应该就可以了
