### ISSUE TITLE
为什么vray的速度比ss快很多

### ISSUE THREAD

**Issue by brainwashing** [Alvin9999/new-pac#308]
好像原理差不多啊

**Comment by nbrnred** [comment]
vray使用没反应，更新ip_Update后使用也没反应。

**Comment by brainwashing** [comment]
今天下午好像就失效了

**Comment by Alvin9999** [comment]
这要看怎么对比，如果是用我分享的SSR版和v2ray版来对比的话，不是很准，因为SSR版对每个人做了速度限制，而2ray版没有做限制，因为目前没有找到更好的方法来进行v2ray速度限制。

之所以要进行速度限制，一是服务器带宽有限，有限制的话可以尽量避免有的人非常快，而有的人很慢，资源分配相对平均。另外，速度太快，对服务器的内存、cpu等消耗也会相应增加，一旦超出服务器的承受能力，就会宕机，需要手动启动服务器才能恢复，今天就是很好的例子，使用的人数很多。

现已恢复，同时升级了服务器cpu、内存等配置，更新一下配置信息即可同步。

**Comment by nbrnred** [comment]
vray又用不了了。

**Comment by brainwashing** [comment]
不知道怎么搭建vray 我的digital用ss搭建总是被墙 我都放弃了

**Comment by brainwashing** [comment]
用这个自己搭建了一个

**Comment by brainwashing** [comment]
速度不错

**Comment by Alvin9999** [comment]
@nbrnred 服务器运行状况良好，更新一下ip试试，刚发布v2ray版的配置文件，由于服务器配置较低，使用人数太多，所以服务器经常宕机，新配置大幅度升级了服务器配置。

@brainwashing  恭喜你，近期也会出一个自建v2ray的教程。

**Comment by nbrnred** [comment]
v2ray能用了，看了帖子说更新IP，更新就用不了了。GP_quic看视频还可以，看网页有的网页显示不全。

**Comment by nbrnred** [comment]
v2ray速度变慢了。

**Comment by Alvin9999** [comment]
@nbrnred  服务器带宽资源有限，同时使用的人数多的话，速度会变慢。

**Comment by nbrnred** [comment]
v2ray太慢了，看网页都慢，没法用。GP_quic有的网页格式显示不全，SS没这样的情况，就是有时候不能用。

**Comment by Alvin9999** [comment]
@nbrnred  国内各个地区封锁策略不同，使用效果会有差别，有的人反馈v2ray和Quic版很好用。
