### ISSUE TITLE
GoAgent版和GoProxy版均无法打开tumblr

### ISSUE THREAD

**Issue by LouisTomlinsun** [Alvin9999/new-pac#31]
www.tumblr.com 我墙外的主要蹲点啊~ 请问大大~ 
这个浏览器真的是我用过最好的了 感谢大大！

**Comment by Alvin9999** [comment]
按照使用说明切换到全局代理

**Comment by Sak1tama** [comment]
@LouisTomlinsun 试试这个 https://github.com/weinierlai/note/blob/master/data-3.md
