### ISSUE TITLE
看abematv必须用日本线路，有什么办法看啊！

### ISSUE THREAD

**Issue by 1343712786** [Alvin9999/new-pac#310]

**Comment by Alvin9999** [comment]
可以通过[自建ss/ssr服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) 搭建一个日本位置的ss/ssr账号
