### ISSUE TITLE
unreachable network

### ISSUE THREAD

**Issue by wengxk** [Alvin9999/new-pac#311]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2a00:1450:4006:804::200d]:443: connectex: A socket operation was attempted to an unreachable network."
}
谁了解么

**Comment by Alvin9999** [comment]
关于ipv6版：如果你的电脑系统运行开启ipv6.bat文件无法成功开启ipv6，或者开启ipv6后不稳定，浏览器提示“dial tcp6 [2a00:1450:400e:808::200a]:443: connectex: A socket operation was attempted to an unreachable host"，多半是开启ipv6.bat文件默认的teredo服务器在你所在地区被封的原因造成的，可以按照使用说明文档或最新的ipv6开启方法手动替换开启ipv6.bat文件里面的teredo服务器地址，再重新运行它。
