### ISSUE TITLE
GoProxy是不是IPv4都不能用了

### ISSUE THREAD

**Issue by dlsyaim** [Alvin9999/new-pac#312]
GoProxy是不是IPv4都不能用了

**Comment by caofengzi** [comment]
tls協議的基本上都不行了，quic協議可以用。

**Comment by xugaohui** [comment]
ipv4开启quic就可以,速度十分好.GoProxy下载文件有问题.最终版是r1651

**Comment by Alvin9999** [comment]
GoProxy下载有两种方法，一种是配合专门的下载工具，比如IDM，将IDM代理设置HTTP 127.0.0.1和8087；第二种方法是用火狐浏览器的youtube下载工具。曾经用谷歌浏览器和火狐浏览器做过对比测试，发现超过32M的文件，火狐可以，但谷歌浏览器下载会出错，原因不明。

**Comment by caofengzi** [comment]
用chrome還是不能下載超過32m以上的大文件，火狐沒有試過，最近新版火狐無論怎麼弄也無法導入goproxy證書。

**Comment by Alvin9999** [comment]
@caofengzi  把新版火狐里面的以前GoAgent和GoProxy删掉，再试试看

**Comment by caofengzi** [comment]
@Alvin9999 剛纔又試著導入證書，goagent可以導入，gop還是不可以，應該是證書名稱的原因，goa證書是ca.crt爾gop1651版本已經變成prom.crt了，而且啟動程序和密鑰都已經變為以
![2018-03-25_174100](https://user-images.githubusercontent.com/13650252/37873673-2077863c-3054-11e8-80e9-fa39180a2c43.png)
prom開頭了。

**Comment by Alvin9999** [comment]
@caofengzi  原本如此。如果gop1651确实导入不进去，而自己又想用新版火狐，那么可以试试低版本的gop

**Comment by caofengzi** [comment]
@Alvin9999 不用了，另外還有一個發現，最後版本1651已經不會在系統證書管理生成證書了。
