### ISSUE TITLE
疑问；搭建好后；真是奇怪；mac可以用；ios 试过了N个 客户端都不能用！why ?

### ISSUE THREAD

**Issue by wanminny** [Alvin9999/new-pac#314]
疑问；搭建好后；真是奇怪；mac可以用；ios 试过了N个 客户端都不能用！why ?
 应该不会对终端有影响啊！

**Comment by wanminny** [comment]
SSR，Ss 的客户端都试过；vultr 。

**Comment by Alvin9999** [comment]
是很奇怪，你试试把ssr服务端的协议和混淆设置成origin和plain，然后ios在用ss客户端试试看

**Comment by YiFengTang94** [comment]
我也遇到这个问题，按楼上的方法试了也不行，ios用的代理客户端是potatos lite

**Comment by YiFengTang94** [comment]
刚尝试后通过了，是我在potatos lite里没有把连接和智能路由同时打开，跟ssr还是ss，协议以及混淆都没关系的
