### ISSUE TITLE
谷歌浏览器64高内核GoProxy ipv6版 今天翻不了了！（附详细截图）

### ISSUE THREAD

**Issue by Gerrard373** [Alvin9999/new-pac#316]
翻墙后，可以打开墙外网站，但网站每篇文章链接点开后却是如下提示：

{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2607:f8b0:4007:80a::2004]:443: i/o timeout"
}

![64 1](https://user-images.githubusercontent.com/18229005/38067783-9bc9def4-3340-11e8-88ce-f83ef8129c79.png)

![64 2](https://user-images.githubusercontent.com/18229005/38067787-a0aad392-3340-11e8-984f-db3d51eb39aa.png)

![64 3](https://user-images.githubusercontent.com/18229005/38067795-a3ad18e8-3340-11e8-925e-76ffb71153b6.png)

![64 4](https://user-images.githubusercontent.com/18229005/38067805-ae24a7f0-3340-11e8-9a8a-ae11bd08e60e.png)

![64 5](https://user-images.githubusercontent.com/18229005/38069237-dcbb1ebc-3347-11e8-9f05-c025afa217da.png)

**Comment by Alvin9999** [comment]
从你提供的详细的截图看，你的ipv6是已开启状态，你的ipv6 ip已更新到最新的，但你用GoProxy IPV6版不稳定，表现为有的网站和链接打不开。推测是你的teredo服务器通道在你所在地区不稳定的原因造成的，你可以手动修改“开启ipv6.bat”脚本里面默认的teredo服务器地址，然后重新运行“开启ipv6.bat”脚本。参考[最新开启ipv6方法](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95)

**Comment by Alvin9999** [comment]
截图很详细，加精。

**Comment by liu987** [comment]
和楼主一样，我这里也用不了了，估计用的人太多被侦测到了。

**Comment by liu987** [comment]
更换teredo服务器也没用

**Comment by Alvin9999** [comment]
如果所有的teredo服务器地址都试了还是不行的话，应该就是teredo通道被严重干扰，那么为了自己能够翻墙上网，建议换其它类型的软件，比如QUIC版、V2RAY版、SSR版等。

**Comment by Alvin9999** [comment]
从国内各个地区反馈情况看，目前ipv6版不能用的人数比较少，这会跟各个地区封锁强度或策略不同有关。

**Comment by kaikaisnow** [comment]
@Alvin9999 我这一直能用，今天晚上回家就不能上了

**Comment by fly9520** [comment]
我这里从3月底开始陆陆续续很多网站开不了，有时候有的网站白天开不了，到了晚上能开，到现在彻底所有的IPV6都死了，最新版本4.2更新里的11备用地址全试了都打不开无法连接，目前用WJ和赛风版本先顶住，还是好想用回GP的IPV6版本啊，看油管1080P轻轻松松

**Comment by hipskil** [comment]
我这里也是这样，昨晚刚打开GP还能用，只能用了一两秒，立刻打不开网页了，就像是被墙住了一样，打开网页的状态和贴主一样，Chrome的错误提示也是："error": "dial tcp6 [2457:b4b5:2017:63a::1003]:443: i/o timeout"，GoProxy的good_adress=1，更换各teredo服务器无效，netsh int ipv6 show teredo显示teredo是正常的，打开IPv6测试页也显示正常。希望A大能更新GP版本，感觉GP版很好用，谢A大付出的努力。 @Alvin9999

**Comment by hipskil** [comment]
最新发现，家里两个网，一个移动，一个电信，用电信GP就用不了，无论teredo服务器怎么改都没有用，被墙得厉害，打开Chrome就提示："error": "dial tcp6 [2457:b4b5:2017:63a::1003]:443: i/o timeout"，good_address为0，换了移动的网络，瞬间流畅。如果想用电信的网，A大有没有解决的方法，家里电信的网速快一点。 @Alvin9999

**Comment by Alvin9999** [comment]
如果所有的teredo服务器都尝试过了，还是不行的话，推测是google ipv6已被全部封锁。

**Comment by hipskil** [comment]
OK 多谢A大
