### ISSUE TITLE
谷歌内核无法升级，似乎是我电脑缺少什么软件打开。

### ISSUE THREAD

**Issue by 247365550** [Alvin9999/new-pac#317]

**Comment by 247365550** [comment]
![qq 20180406120536](https://user-images.githubusercontent.com/36228881/38403038-0194b4e0-3993-11e8-8898-d9d013cdd26f.png)

**Comment by 247365550** [comment]
求大神解答一下

**Comment by Alvin9999** [comment]
我看你把帖子关了，是自己解决了吗

**Comment by 247365550** [comment]
很绝望

**Comment by Alvin9999** [comment]
把你不能升级的报错提示截图发上来一下

**Comment by Alvin9999** [comment]
顺便问下，你的电脑是XP系统吗

**Comment by 247365550** [comment]
![qq 20180406120536](https://user-images.githubusercontent.com/36228881/38409589-8c260ade-39b4-11e8-85b0-b45e4d23754e.png)
就这个VBS的文件 我电脑选择的是网页打开  WIN8,1系统

**Comment by 247365550** [comment]
用网页打开来 就是下载  下载出来的 还是这个文件
![qq 20180406160824](https://user-images.githubusercontent.com/36228881/38409655-cd6ab576-39b4-11e8-9ae7-1c8f27a60663.png)

**Comment by Alvin9999** [comment]
1.右击“以管理员权限运行”
2.不行的话右击，点属性，在兼容性选项卡中选择以兼容模式运行，模式可以选XP

win10系统可以用高内核版，不用自己升级浏览器内核，低内核版主要是给XP用户使用的
