### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Josephineduh** [Alvin9999/new-pac#319]
我的路由器上国内的网站可以上，但是看国外的油管推特谷歌什么的一直显示未发送数据，刷新还是不行，ssr账号都没有问题。手机开流量来上也没有问题，想问下有什么解决方法吗

**Comment by Alvin9999** [comment]
你是通过下面这个方法配置的路由器吗？

路由器也可以配置ss/ssr账号，详见openwrt-ssr项目地址：https://github.com/ywb94/openwrt-ssr

**Comment by Josephineduh** [comment]
应该不是，前几个小时一切都好好的，没有出现上述问题

**Comment by Josephineduh** [comment]
好吧现在解决了，谢谢

**Comment by Alvin9999** [comment]
选PAC模式看看
