### ISSUE TITLE
goagent

### ISSUE THREAD

**Issue by hyunbb** [Alvin9999/new-pac#32]
博主你好！
我是用GoAgent的，最近我用GoAgent跟goproxy都是一样可以上网的 但是后来不小心删除了火狐 然后导致现在GoAgent不能上反而goproxy可以上 我没有使用一键翻墙 因为我要下载YouTube的视频。重新安装了也还是不行

**Comment by hyunbb** [comment]
错误的代码：ERROR -  ssl.wrap_socket(connection=<socket at 0x2cdef50 fileno =616 sock=127.0.0.1:8087 peer=127.0.0.1:4256>) failed: (-1, 'Unexpected EOF')

**Comment by Alvin9999** [comment]
重新解压再试试看，我分享的一键翻墙火狐浏览器可以下载YouTube视频的，好像在使用小技巧里面

**Comment by hyunbb** [comment]
解压好几次了 也下载以前的旧版本了 还是不行 只能用goproxy翻 GoAgent就翻不出去 但是用GoAgent翻墙不去推特去国内的网站倒是可以 goproxy的ip好像有点不行了 现在用起来好卡。

**Comment by Alvin9999** [comment]
下周我更新一下ip，过年期间太忙了

**Comment by Alvin9999** [comment]
下周我更新一下ip，过年期间太忙了

**Comment by Sak1tama** [comment]
@hyunbb 下载ytb视频用 www.clipconverter.cc 解析ytb视频地址，然后直接用IDM下载就可以了，不需要goproxy

**Comment by hyunbb** [comment]
不不不 我火狐安装了一个插件 下载视频挺快的，但是就是要靠速度 那个idm我也试过了 没有火狐的插件好
