### ISSUE TITLE
【请问】如果升级软件，必须全部重下浏览器？？？？？？

### ISSUE THREAD

**Issue by kapans** [Alvin9999/new-pac#320]
有没可能只更新代理那部分软件
不重下整个浏览器啊？
好麻烦哦

谢谢

**Comment by kapans** [comment]
就是说，我想用自己的浏览器，可能么？

**Comment by AnyWAT** [comment]
貌似有可能：按目录下的说明来升级代理。倒是浏览器的升级 ChromeUpdater.exe 已失效，自己可更新到 GreenChrome6.5.7.zip 及 ChromeUpdateSharp_v2.4.5.0.zip 解决
