### ISSUE TITLE
你好，我已经有GoProxy了，但是如何配置呢？

### ISSUE THREAD

**Issue by EliteOtaku** [Alvin9999/new-pac#322]
版本号1623
已经配置好app ID等步骤，可以翻墙，但是最近发现youtube非常慢，有没有办法解决？

**Comment by caofengzi** [comment]
慢是網絡問題與goproxy無關，ip的問題。

**Comment by Alvin9999** [comment]
最近ipv6被干扰的厉害，即使能用也很慢。相对而言，Quic要快些，如果你配置的是ipv6，可以参考GoProxy  Quix版来配置。

**Comment by EliteOtaku** [comment]
我看了一下，你发布的quic版goproxy，可以更新ipv6的地址，但是我运行更新程序ip_1后，发现似乎没有更新上来。

--2018-04-08 22:07:58--  https://raw.githubusercontent.com/Alvin9999/pac2/master/ipv6/gae.user.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 97788 (95K) [text/plain]
Saving to: 'gae.user.json'

100%[======================================>] 97,788       436KB/s   in 0.2s

2018-04-08 22:07:59 (436 KB/s) - 'gae.user.json' saved [97788/97788]

系统找不到指定的文件。
系统找不到指定的文件。
系统找不到指定的路径。
已复制         0 个文件。

已更新完成最新可用IPv6 ip,请按任意键退出,并重启程序.

----------------
我的打算是把更新下来的ipv6地址复制到自己用的goproxy的gae.user.json中，然后看看是否能恢复youtube的速度，另外请教一下，如果正确配置goproxy呢？因为很难找到教程。

**Comment by EliteOtaku** [comment]
果然，死马当作活马医，用这土办法搞定了，运行goproxy时，留意到GAE模式为quic，打开youtube发现视频速度完全恢复了，嗖嗖的！
