### ISSUE TITLE
goagent配和Chrome使用，打开google时经常出现Error

### ISSUE THREAD

**Issue by zhixing2017** [Alvin9999/new-pac#323]
如题：
goagent配和Chrome使用，打开google时经常出现Error，打开facebook和youtube却没有问题，不知道是什么原因。

我用SS的时候，可以打开google，但是不能用google scholar，出现Error。

有人知道是什么原因吗？

**Comment by Alvin9999** [comment]
不太清楚。你试试全局代理。

**Comment by zhixing2017** [comment]
有时能打开，有时就像是被封锁一样，不能打开，过会就又好了。

最近封的很严吗？

用gogo tester查找的20个ip，很快就会不能用，有什么找ip的好方法吗？

**Comment by Alvin9999** [comment]
你是用的google ipv4还是google ipv6？

**Comment by zhixing2017** [comment]
ipv4

**Comment by Alvin9999** [comment]
目前国内几乎99%地区都无法使用google ipv4，所以搜出来的ip放进软件中会用不了。

**Comment by zhixing2017** [comment]
有时能用，速度也还行，但是有的时候就不行了，不知道为什么
