### ISSUE TITLE
请教一个问题，谢谢

### ISSUE THREAD

**Issue by xiawuliangdianban** [Alvin9999/new-pac#325]
首先十分感谢版主提供的软件，我用的是高内核GoProxy ipv6版，默认的teredo服务器下可以打开ipv6不过速度比较慢，ping 默认teredo服务器280ms，测试有一个服务器延迟为7ms,但是按照文件内说明更换服务器，自动更换，手动更换都试了，可就是不能开启ipv6,  重启电脑，更换谷歌dns,都试了 ，都不行，win7 64位系统， 但手动更换为默认teredo服务器还能正常开启ipv6,请问有神马办法吗？谢谢。

**Comment by Alvin9999** [comment]
没有办法。这跟最近teredo服务器以及google ipv6被严重干扰有关，所以速度很慢。
