### ISSUE TITLE
这个新方法可能有效？

### ISSUE THREAD

**Issue by happy1234367** [Alvin9999/new-pac#326]
![image](https://user-images.githubusercontent.com/25525577/38597940-e7f54ae2-3d8c-11e8-8816-79e3038e4678.png)
plus.google.com/113984721138789488972/posts/1iEh7PpdZBn
本人水平有限，gae绑域名那步不会弄。请问版主见过这种方法吗？从图片上看前景好像还可以？？

**Comment by happy1234367** [comment]
#325

**Comment by Alvin9999** [comment]
谢谢这些大侠的推荐。由于翻墙浏览器内置了4千个appid，所以不能批量弄，太花费时间了，以后弄的话也只是出个教程，让个人来使用。

**Comment by caofengzi** [comment]
這個方法只是適用與個人
