### ISSUE TITLE
服务器类型是哪个

### ISSUE THREAD

**Issue by Franklincon** [Alvin9999/new-pac#328]
请问你的服务器是哪个，我自己建的服务器linux连不上。

**Comment by Franklincon** [comment]
我的安卓和windows可以正常使用但是linux连不上。。

**Comment by Alvin9999** [comment]
那说明账号没有问题，可能是你的linux系统没有配置好。
参考：[Linux客户端一键安装配置使用脚本(使用方法见注释)](https://github.com/the0demiurge/CharlesScripts/blob/master/charles/bin/ssr) 或者采用图形界面的[linux ssr客户端](https://github.com/erguotou520/electron-ssr/releases)

如果上面推荐的方法不行，建议用google搜索linux配置ss/ssr账号的方法。

**Comment by Franklincon** [comment]
已经解决了  是自己配置的问题，谢谢老哥了，抱拳了！！
