### ISSUE TITLE
v2ray一键安装脚本

### ISSUE THREAD

**Issue by Jason-Fly** [Alvin9999/new-pac#329]
在网上看到一个挺人性化的脚本。
https://233blog.com/post/16/

**Comment by Alvin9999** [comment]
谢谢分享

**Comment by ufo1024k** [comment]
@Alvin9999   可否给v2ray 加上v2rayn 方便管理 谢谢

**Comment by Alvin9999** [comment]
@ufo1024k  你可以去v2ray项目开发提问https://github.com/v2ray/v2ray-core
