### ISSUE TITLE
博主 能否做一个基于360极速的GoAgent版啊？

### ISSUE THREAD

**Issue by G8045** [Alvin9999/new-pac#33]
谷歌 跟火狐浏览器 真的不好用啊 
360极速 比较符合国人使用习惯 
大神能否考虑下？

**Comment by nxtreaming** [comment]
禁止使用/支持360的任何产品
如果不明白原因，请自行Google.

**Comment by G8045** [comment]
360做了什么伤天害理的事吗？求大佬科普！

**Comment by nxtreaming** [comment]
360 大股东之一之国安， 国安是干什么的，自己去查一下吧

**Comment by Alvin9999** [comment]
其实，随着时间的延长，人们的习惯会慢慢改变的的。我觉得谷歌浏览器很不错哦。

**Comment by caofengzi** [comment]
說chrome不好用的人是因為沒有完全弄明白。

**Comment by theratlesnake** [comment]
@G8045 可怕，居然还有人说chrome不好用的，另外，360浏览器有各种后门，会监控你的电脑数据，所以还是早点抛弃吧，不然什么私隐都没了。

**Comment by 349205055** [comment]
360浏览器安装插件，和谷歌浏览器一样翻墙，就是把谷歌的那个插件复制过来用就行了。
![default](https://user-images.githubusercontent.com/30136196/29003051-18c5dda8-7ae2-11e7-8465-a6f276f6ebec.PNG)

**Comment by gyj1109** [comment]
360系列应该算是GFW忠实的守护者，如果发现有翻墙行为会忠实地上传到GFW服务器，15分钟内保证被封。翻墙请远离360系列

**Comment by FUXIAOZHIYAN** [comment]
相对而言，我还是喜欢firefox。。。在移动端chrome做的很烂
