### ISSUE TITLE
请问使用过这些工具，设置了ipv6，怎么恢复以前的设定呢，好像打不开局域网内搭建的网站了

### ISSUE THREAD

**Issue by Qingyunruooyu** [Alvin9999/new-pac#330]
不知道为什么，我们在局域网搭建了桌面云，然后我们小组内用过翻墙的电脑都连不进去，不知道应该怎么恢复使用翻墙工具前的状态。谢谢大大🌝

**Comment by Alvin9999** [comment]
试试关闭之前的ipv6 DNS设置的内容，然后运行关闭ipv6脚本，最好重启电脑。

鉴于你们这种网络环境，为了方便，不推荐用ipv6翻墙工具，可以尝试其它的工具，比如v2ray版、GoProxy Quic版、SSR版等

**Comment by nbrnred** [comment]
不久前用了更新的，一键配置ipv6脚本，ipv6可以正常持续使用了，但用了发布的PAC-ipv6版后，ipv6就不能正常使用了，重设置后也不能正常持续使用ipv6。

**Comment by Alvin9999** [comment]
可以换不同的teredo服务器试试看，PAC-ipv6和GoAgent ipv6版、GoProxy ipv6版的一键配置ipv6脚本是一模一样的。也不排除刚好你那里ipv6被干扰。

**Comment by nbrnred** [comment]
重做系统后就可以用了，和服务器没关系，都换了的，不可能不能用了就不换服务器试，是PAC-ipv6的问题。

**Comment by Alvin9999** [comment]
PAC-ipv6版，从后台看CPU、内存以及带宽的消耗，表明有不少人在使用，应该没有问题
