### ISSUE TITLE
QUIC频繁出现这几个错误

### ISSUE THREAD

**Issue by happy1234367** [Alvin9999/new-pac#331]
版主您好，东北电信使用quic最近出现了以下几种不稳定的情况。打开youtube主页时遇到的尤其多，无法正常显示。

**Comment by happy1234367** [comment]
W0414 08:43:35.682997    7432 handler.go:152] &gae.QuicBody{Stream:(*quic.stream)(0x1395c4d0), Transport:(*h2quic.RoundTripper)(0x133cc080), MultiDialer:(*helpers.MultiDialer)(0x133fe070)}.OnError(write tcp 127.0.0.1:8087->127.0.0.1:2105: wsasend: An established connection was aborted by the software in your host machine.) called.

**Comment by happy1234367** [comment]
E0414 08:46:15.425012    7432 handler.go:96] 127.0.0.1:2212 Filter RoundTrip *gae.Filter error: PeerGoingAway:

**Comment by happy1234367** [comment]
W0413 20:24:58.776807    7432 gae.go:552] 127.0.0.1:1199 "GAE DIRECT GET https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=latin,latin-ext HTTP/1.1" error: *net.OpError(read udp: closing session in order to recreate it with a new version)

**Comment by happy1234367** [comment]
APPID使用了我自己的gp最新版本，换成您配置的appid问题依旧。没有在quic翻*时同时扫ip，没有国产**软件。

**Comment by happy1234367** [comment]
# #326 
## 上面这个，一个朋友前几天试过，可以长时间流畅观看1440p30帧的视频。版主有兴趣写个教程吗：）

skyzip最近速度可以，但有所下降。

五***界最近速度也不错，有时候突然断线几天连不上。

ipv6还可以用，但是好几次发现访问5界浏览的时候teredo会突然不正常，持续两分钟左右，十分有规律，

使用dnscrypt后问题解决，访问任何“敏*感”网站teredo都没有出问题。

pac-ipv6速度不是太理想，但是可用，十分感谢版主想出了这样一个好方法！！

**Comment by Alvin9999** [comment]
你好，十分感谢你的反馈。

**Comment by Alvin9999** [comment]
GoProxy Qui版的开发者已不再进行维护，所以目前出现问题的话，我也没办法，可以刷新一下网页或者更新一下ip来尝试着解决。

**Comment by Alvin9999** [comment]
v2ray版速度应该还可以，采用的是独立服务器，使用前把ip更新到最新。

你说的那个教程，比较复杂，目前没时间弄。你有兴趣的话可以自己按照那个帖子的说明去研究下。

**Comment by nbrnred** [comment]
v2ray就才开始发出那天还可以，荡机，更改设置后一直都不好用，速度太慢，可能是独立服务器分配的资源太少，后面就基本没用，偶尔试下，速度一直不理想，完全不如刚发出来那天的速度，一点也不流畅，很缓慢。

**Comment by Alvin9999** [comment]
@nbrnred  你家的带宽是什么类型？移动、联通、电信？

**Comment by nbrnred** [comment]
v2更新后1080都可以流畅了。

**Comment by nbrnred** [comment]
gp_quic 中的 _cn : IP容易让网页显示不全，干扰了 h 的IP.

**Comment by Alvin9999** [comment]
@nbrnred  十分感谢，已去掉google_cn ip
