### ISSUE TITLE
在GoProxy里如果自己检测到可用IP怎么添加呢？

### ISSUE THREAD

**Issue by ufo1024k** [Alvin9999/new-pac#333]
自己这里可以检测到一些IP想添加到GoProxy里，怎么操作呢？

**Comment by caofengzi** [comment]
打開gae.jso配置文件找到這一段，把［］裏面的網址刪除然後添加ip，添加格式是這樣的，需要注意所有符號必須用英文的.
![2018-04-18_084900](https://user-images.githubusercontent.com/13650252/38906327-a2d7c4e2-42e8-11e8-9122-55fd92bde154.jpg)

		"google_hk": [
			"mail.google.com",
			"mail.l.google.com",
			"maps.l.google.com",
			"scholar.google.com",
			"scholar.google.com.hk",
---------------------------------
		"google_hk": [
			"000.111.222.333",
                        "xx.xxx.xx.x",
