### ISSUE TITLE
ubuntu可否有代理的方法

### ISSUE THREAD

**Issue by xu378947986** [Alvin9999/new-pac#334]
我的系统是ubuntu（linux），有时要上github下载东西或者外网下载东西速度很慢，想说楼主有没有linux代理的方法，Windows用ipv6方法还不错，关键是linux（工作需要）  另外想说Ubuntu有没有类似goagent这种可更新ip的东西

**Comment by Turing2333** [comment]
这个ssr-helper的教程亲测可用

https://github.com/Turing2333/Detailed-tutorial-on-the-building-and-usage-of-SSR/blob/master/Instructions/Clients%20manual%20for%20each%20platform/Linux%20SSR相关说明.txt

**Comment by Alvin9999** [comment]
@Turing2333 谢谢分享哈
