### ISSUE TITLE
pc端配置好ssr后，使用时报错，连接不到代理服务器(win10自带的了浏览器，代理也设置了的)，这是为什么？

### ISSUE THREAD

**Issue by coderjzf** [Alvin9999/new-pac#336]
安卓手机可以使用ssr,但是pc端使用时报错，连接不到代理服务器，这是为什么？

**Comment by Alvin9999** [comment]
安卓能用，说明账号没问题。你检查下PC段的账号是否有细小的地方填写错误，浏览器代理是设置HTTP代理127.0.0.1和1080
