### ISSUE TITLE
为啥汤不热和pin登录不进去

### ISSUE THREAD

**Issue by Sizzmi** [Alvin9999/new-pac#337]

**Comment by Alvin9999** [comment]
用的哪款软件呢？

**Comment by Sizzmi** [comment]
你好我用的是Chrome66_64bit_GP_ipv6_2018.4.23

**Comment by Alvin9999** [comment]
试试切换成全局代理
![1111](https://user-images.githubusercontent.com/12132898/39972055-d7dff41a-5739-11e8-84b0-58a48e593d16.PNG)
