### ISSUE TITLE
请问YouTube下载总是提示未找到文件，已试用多个版本

### ISSUE THREAD

**Issue by sun199933** [Alvin9999/new-pac#338]
观看正常，只有下载时，总是提示下载失败，未找到文件。用Chrome53WJ_v2018.4.29，下载一半会中断。用在线下载，也是提示下载失败，谢谢

**Comment by caofengzi** [comment]
未找到文件是代理不支持下載超過32m的大文件，你可以複雜視頻地址然後打開這個鏈接粘貼鏈接選擇格式下載。https://www.onlinevideoconverter.com/zh

**Comment by sun199933** [comment]
抱歉，这么久回复，谢谢
