### ISSUE TITLE
动态网、大纪元都是轮子控制的网站，麻烦撤掉

### ISSUE THREAD

**Issue by kingtami** [Alvin9999/new-pac#339]
动态网、大纪元都是轮子控制的网站，麻烦撤掉
动态网、大纪元都是轮子控制的网站，麻烦撤掉
动态网、大纪元都是轮子控制的网站，麻烦撤掉
轮子的，不解释，别拿来误导大家，谢谢。

**Comment by Alvin9999** [comment]
有时间请静下心来了解一下真相哦。在国内媒体是被控制的，“轮子”是有信仰的好人。
