### ISSUE TITLE
用mychrome升级后所有插件都不见了

### ISSUE THREAD

**Issue by trymeandy** [Alvin9999/new-pac#34]
无论是goAgent还是GOP版本，用mychrome升级后所有插件都不见了。
所有能否请楼主先更新上传一下已经更新过的版本？
我怀疑是36版本过旧的缘故。
谢谢

**Comment by Alvin9999** [comment]
你好，请严格按照文件夹里面的《Chrome内核升级方法》来升级浏览器内核。

为什么我不直接升级后再上传？
因为从36以上版本开始，谷歌官方开启了验证，也就是说如果我升级内核再打包分享出来，换一个人（或电脑）就没法使用以前的插件，因为官方验证非本人。所以我才分享的是36版本的压缩包。
你按照内核升级说明即可，再试试。
