### ISSUE TITLE
提供的免费ss/ssr服务已经不能使用了

### ISSUE THREAD

**Issue by yyr03gy** [Alvin9999/new-pac#340]

**Comment by chat491231702** [comment]
很久没更新了

**Comment by xhanglizhu** [comment]
免费账号5月13最后一次更新，现在无法使用了，查资料都不用了，着急，在线等。

**Comment by 6914491** [comment]
你好 服务器什么时候恢复  谢谢

2018-05-23 16:12 GMT+08:00 Editplus <notifications@github.com>:

**Comment by Alvin9999** [comment]
正在解决

**Comment by Alvin9999** [comment]
已更新

**Comment by bjnews** [comment]
@Alvin9999 多谢晒👍

**Comment by 6914491** [comment]
谢谢 辛苦

2018-05-23 21:27 GMT+08:00 bjnews <notifications@github.com>:

**Comment by bjnews** [comment]
好像又抽了😟

**Comment by nbrnred** [comment]
更新还4.28的日期？

**Comment by AndyLeecs** [comment]
请问现在免费账号可以使用吗？好像又不能用了

**Comment by Alvin9999** [comment]
@AndyLeecs 从使用人数看，没有问题。你试试其他账号，一共有3个。

**Comment by cclylycc** [comment]
可以试试基微云加速 https://yun.gvhouse.com

**Comment by xhanglizhu** [comment]
BWG大面积被封。有其他路径吗？
