### ISSUE TITLE
https://hello.the-youtube.win/不能打开，

### ISSUE THREAD

**Issue by jinyumarine** [Alvin9999/new-pac#341]
https://hello.the-youtube.win/不能打开，链接无效

**Comment by Alvin9999** [comment]
你好，请用电脑打开

**Comment by xfmniao** [comment]
2018-05-30 7:20 GMT+09:00 自由上网 <notifications@github.com>:

**Comment by xfmniao** [comment]
我从Gmail的回复里中发了附件上来看看(⊙o⊙)…

**Comment by Alvin9999** [comment]
@ekingling 什么打开？

**Comment by Alvin9999** [comment]
@ekingling 什么打不开？

**Comment by ekingling** [comment]
@Alvin9999 https://hello.the-youtube.win/这个网址电脑端打不开啊

**Comment by Alvin9999** [comment]
@ekingling 已向开发者反馈

**Comment by Alvin9999** [comment]
新地址https://nogfw.the-youtube.win

**Comment by gfw-breaker** [comment]
@jinyumarine @xfmniao @ekingling  
前段时间GFW封锁升级了，好几台服务器被封。多谢大家及时反馈。
之前的 Web代理被封了，因此另外新建了 [https://node1.free-ss.win/](https://node1.free-ss.win/)

**Comment by xfmniao** [comment]
邪恶中共，又拿着国库里的钱去非洲大撒币。
