### ISSUE TITLE
意见

### ISSUE THREAD

**Issue by jdfq** [Alvin9999/new-pac#346]
quic版已经不能使用，可以先下架。
既然翻墙软件都不稳定，即使做便携版，也应该集合起来，一次下载，不应该每种都要下载一次浏览器。

**Comment by caofengzi** [comment]
quic可以用，還是自己搜索ip比較好。

**Comment by Alvin9999** [comment]
@caofengzi 很多人反馈Quic不能用了。请问你的能用吗？

**Comment by caofengzi** [comment]
@Alvin9999 可以用，而且還是17/10月份掃的ip呢，不可用應該是各個地方的網絡運營商的原因，就像有的地方tls協議ip可以用有的地方卻不能用。

**Comment by Alvin9999** [comment]
@caofengzi 喔，那估计是的

**Comment by caofengzi** [comment]
@Alvin9999 俺這裡從昨天晚上開始quic協議ip4已經很少很少了，重新掃描也基本上沒有了。

**Comment by bannedbook** [comment]
@jdfq   https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

这边是集合起来的
