### ISSUE TITLE
这个问题是网络问题 还是系统版本问题呢 因为别人的window7是可以用的 我用的是win10

### ISSUE THREAD

**Issue by zengpengkindle** [Alvin9999/new-pac#347]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2001:ee0:3203:7::11]:443: connectex: A socket operation was attempted to an unreachable network."
}

**Comment by caofengzi** [comment]
系統防火牆關閉試試。

**Comment by Alvin9999** [comment]
是用的Quic版吧？

**Comment by zengpengkindle** [comment]
是的

**Comment by caofengzi** [comment]
是ip6隧道問題吧？俺現在用的就是gop的ip6。

**Comment by zengpengkindle** [comment]
我配置了下ip6 可以了 但是感觉没以前那么稳定了

**Comment by caofengzi** [comment]
能用就行了，ip6本來就不怎麼穩定。

**Comment by caofengzi** [comment]
壓縮包裡面應該有修改隧道的批處理吧。

**Comment by zengpengkindle** [comment]
@Sizzmi  博主的的文档里有详细说明 https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95

**Comment by Sizzmi** [comment]
@zengpengkindle  @caofengzi  状态都是offline试了11个了都是不行，说明是不是我的这个已经用不了了。

**Comment by caofengzi** [comment]
@Sizzmi 你可以找一個掃描ip的工具和ip段文件，然後自己搜索試試找到的ip能否使用。

**Comment by nbrnred** [comment]
Quic最近无法用了？是否该更新IP了。

**Comment by caofengzi** [comment]
俺這裡從昨天晚上開始quic協議ip4已經很少很少了，重新掃描基本上沒有了。

**Comment by Alvin9999** [comment]
@nbrnred 换其它类型的软件吧，这次干扰与ip无关。

**Comment by caofengzi** [comment]
@Alvin9999 今天重新掃描了quic協議ip4，4個小時找到了100個左右。

**Comment by Alvin9999** [comment]
@caofengzi  能否提供一下这100个ip？造福更多的网友

**Comment by Alvin9999** [comment]
@caofengzi 我估计Quic版时日不多了，能多用会就让大家都用会吧

**Comment by caofengzi** [comment]
還是自己用kisesy開發的那個工具掃描更好，先試試這些，如果長時間搜索應該會有更多。這是俺用的ip庫。
[iprange_quic.zip](https://github.com/Alvin9999/new-pac/files/2125214/iprange_quic.zip)


"223.25.255.229", "180.210.155.228", "103.229.45.197", "163.47.157.132", "103.197.248.228", "103.68.116.133", "163.47.157.133", "103.230.4.198", "103.68.116.132", "103.15.246.101", "103.230.4.196", "180.211.173.229", "103.54.38.197", "180.211.173.228", "103.197.248.229", "103.54.38.196", "27.147.199.4", "220.158.234.4", "59.152.108.165", "59.152.108.164", "58.145.190.6", "58.145.190.4", "58.145.190.7", "103.229.45.196", "27.147.198.4", "58.145.190.5", "27.147.198.5", "180.210.155.229",

**Comment by Alvin9999** [comment]
@caofengzi 谢谢大兄弟分享

**Comment by caofengzi** [comment]
@Alvin9999 其實使用的人更應該自力更生，google的ip庫很好找到，找到ip庫然後用kisesy開發那個搜索工具自己搜索豈不更好，這樣能夠減輕你的負擔。

**Comment by Alvin9999** [comment]
@caofengzi  根据网友反馈，还是不能用。

搜Quic ip教程在issue之前分享过，没有专门弄wiki。

**Comment by caofengzi** [comment]
@Alvin9999 現在可以肯定各個地方的網絡運營商屏蔽策略不一樣，上面的ip俺這裡可以用。
