### ISSUE TITLE
除了google 搜索不了，其他都行的

### ISSUE THREAD

**Issue by Jamesowens11** [Alvin9999/new-pac#348]
您们好，

请教一下，

我用的是 Chrome53_gop_ipv6_v2018.4.6  ， Facebook  等等都可以用的，但是就是google 搜索时候出现这样的问题， 提示这样的： 403. That’s an error.

Your client does not have permission to get URL /search?newwindow=1&source=hp&ei=NGkoW9LjCYGA8gWm9qRY&q=nbv&oq=nbv&gs_l=psy-ab.3..0l3j0i10k1j0l3j0i10k1j0l2.3510.3613.0.4477.3.2.0.0.0.0.455.455.4-1.1.0....0...1.1.64.psy-ab..2.1.453....0.L0bsAW_Kh3M from this server. That’s all we know.

请问这怎么解决呢？

感谢了

**Comment by Alvin9999** [comment]
试试这个网站https://www.google.com.hk/

**Comment by Jamesowens11** [comment]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2001:b032:8100::10]:443: i/o timeout"
}

**Comment by Jamesowens11** [comment]
你好，

出现这样的提示呢， 请问有什么办法吗？

**Comment by Alvin9999** [comment]
@Jamesowens11 没有成功开启ipv6，可以按照使用说明更换teredo服务器地址，然后再试试看。
