### ISSUE TITLE
请教关于Chrome53_gop_ipv6_v2018.4.6 出现错误问题

### ISSUE THREAD

**Issue by Jamesowens11** [Alvin9999/new-pac#349]
您好，

我下载了 Chrome53_gop_ipv6_v2018.4.6，  装在不同的电脑，其中有两台不能用，提示是这样的： {
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2001:8002:e52:e001::10]:443: connectex: A socket operation was attempted to an unreachable network."
}

那两台不能用的电脑也都关了杀毒软件了，防火墙也没有问题的。

麻烦你了，谢谢了

**Comment by caofengzi** [comment]
換一個ip6隧道地址試試看。

**Comment by Jamesowens11** [comment]
你好，换了IP6 隧道也不行的

**Comment by Jamesowens11** [comment]
请问还有什么办法吗？

**Comment by caofengzi** [comment]
系統是10嗎？你可以在不能用的電腦上ping一下ip看看能否聯通，如果能聯通應該還是系統的原因。

**Comment by Jamesowens11** [comment]
系统是W7 的，以前能用的，但是有一次用时候， 忘了关杀毒软件了，从那时以后就不能用了

**Comment by caofengzi** [comment]
檢查一下系統防火牆，看看是不是曾經被殺毒程序設置阻止了。

**Comment by Jamesowens11** [comment]
你好，也不是防火墙的问题呢， 我配置ip6 时候， 到了查看隧道时， 只是出现了三行字呢， 正常的不只三行字的，我觉得是什么阻止了，还有别的办公吗？  谢谢了

**Comment by caofengzi** [comment]
除了殺毒軟件系統防火牆還能有啥能阻止呢？另外系統uac會不會阻止？把uac關閉看看。
