### ISSUE TITLE
置顶的谷歌浏览器66高内核版这2天不行了

### ISSUE THREAD

**Issue by ydssnjtv** [Alvin9999/new-pac#350]
猛更新了ip也没辙
一个good ip也没
换用ssr，龟速啊。。。。

**Comment by Alvin9999** [comment]
不同地区的封锁强度和策略不同，会造成软件的使用效果不同。如果某一款软件不好用，建议多试试其它类型的软件，选择一款与自己网络最搭的。

**Comment by ydssnjtv** [comment]
感谢A大大的回复，昨夜折腾出来了，原来是IPV6问题，之前IPV6都ok的，结果就没往上面想，
试了一下，现在只有第10个IPV6服务器能通了，
不知道是不是因为电信动了手脚

**Comment by Alvin9999** [comment]
有可能哦
