### ISSUE TITLE
Chrome66_64bit_GP_ipv6_2018.4.23 最近连不上代理服务器

### ISSUE THREAD

**Issue by liaowuyin** [Alvin9999/new-pac#352]
新解压的包，配置完ipv6后，依旧打不开代理服务器。

 C:\Users\zlc>   ping -6 ipv6.test-ipv6.com

正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
来自 2001:470:1:18::4:230 的回复: 时间=3403ms
来自 2001:470:1:18::4:230 的回复: 时间=170ms
来自 2001:470:1:18::4:230 的回复: 时间=169ms
来自 2001:470:1:18::4:230 的回复: 时间=168ms

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 168ms，最长 = 3403ms，平均 = 977ms

**Comment by Alvin9999** [comment]
请按照使用说明更换其它teredo服务器，如果所有的都尝试还是不行的话，表明你的网络不适合用ipv6版。那么，建议换其它类型的非ipv6软件。
