### ISSUE TITLE
Vultr新建服务器总是用一两个星期就开始丢包

### ISSUE THREAD

**Issue by Rorspike** [Alvin9999/new-pac#353]
Alvin你好，我按照你的自建ss服务器教程使用Vultr服务器有一段时间了，有个问题一直困扰我，每次新建一个服务器刚开始几天是很流畅的，ping起来也几乎不丢包，但是一两个星期之后就一定会开始延迟增大并开始丢包，使用起来也很卡，试过reboot服务器但无效。请问是被GFW检测到了的原因吗，还是因为我哪里没设置好，我一直是用plain的混淆协议，其它都是默认的设置。

**Comment by Alvin9999** [comment]
可以尝试更换协议、混淆、加密方式、端口
