### ISSUE TITLE
我更改端口后服务器 无法登陆了

### ISSUE THREAD

**Issue by shanjava** [Alvin9999/new-pac#355]

**Comment by Alvin9999** [comment]
是不是更好被墙了？可以重新开一台新的服务器

**Comment by shanjava** [comment]
v2ray 这种方式我换了4台服务器 都不行  重启后连接不上 ip ping 不通   。后来换了ssr   可以用了。Windows SSR客户端下载下来我不会安装  我从csdn 下载了一个，求安装说明。


------------------------------------------------------------------
发件人：自由上网 <notifications@github.com>
发送时间：2018年7月4日(星期三) 20:46
收件人：Alvin9999/new-pac <new-pac@noreply.github.com>
抄　送：shanjava <shan_java@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [Alvin9999/new-pac] 我更改端口后服务器 无法登陆了 (#355)

是不是更好被墙了？可以重新开一台新的服务器

**Comment by Alvin9999** [comment]
SSR客户端不用安装，打开就能使用。

第一次电脑系统使用SSR/SS客户端时，如果提示你需要安装NET Framework 4.0，网上搜一下这个东西，安装一下即可。NET Framework 4.0是SSR/SS的运行库，没有这个SSR/SS客户端无法正常运行。有的电脑系统可能会自带NET Framework 4.0。
