### ISSUE TITLE
【最新方法】已经实现

### ISSUE THREAD

**Issue by happy1234367** [Alvin9999/new-pac#356]
https://github.com/XX-net/XX-Net/issues/11064
0个IP，却能流畅播放1440p@30视频

**Comment by happy1234367** [comment]
![image](https://user-images.githubusercontent.com/25525577/42410086-df745344-8216-11e8-96d1-d27454b537fb.png)
@Alvin9999

**Comment by Alvin9999** [comment]
收到了。我分享的软件appid太多，且来自于不同的账号，所以这种方法不适合制作公共版，只能作为教程，让自己来操作。

**Comment by YunXuyun** [comment]
@happy1234367 @Alvin9999 教程为什么删掉了，有备份吗？请问现在这办法还行得通吗？我想抽空试试看能不能让我的goproxy复活。

**Comment by Alvin9999** [comment]
@YunXuyun 我还没有写教程，你可以按照一楼的地址去找。

**Comment by Alvin9999** [comment]
哦哦
