### ISSUE TITLE
Follow the tutorial and go where my problem is?

### ISSUE THREAD

**Issue by ruoru** [Alvin9999/new-pac#357]
按照教程走了一遍，客户端连接上了也没有反应，现在还是翻不了墙，也不知道问题在哪里。

**Comment by Alvin9999** [comment]
自己搭建的SSR吗？

**Comment by ruoru** [comment]
是的是的大佬 ==

**Comment by Alvin9999** [comment]
1、端口不要以0开头，密码不要有太特殊的符号
2、浏览器代理设置对了没有？
3、账号信息是否填写正确?

**Comment by ruoru** [comment]
@Alvin9999 

1. 均符合要求
2. 浏览器没有设置代理
3. 账号信息是对的

另外，关于第二点，我是用的 shadowSocket 客户端，扫描的服务器返回的二维码扫描有问题，shadowSocket 已经配置账户信息

**Comment by Alvin9999** [comment]
浏览器要设置代理才行，除非你是系统自动代理

**Comment by ruoru** [comment]
系统代理怎么设置呢 因为我不仅仅是浏览器需要翻墙 我有一些人软件也需要翻墙

**Comment by ruoru** [comment]
感谢这个 issue 一直开着 我前几天才发现我的 chrome 设置了代理无法翻墙，所以可能是我 chrome 问题，并非 ssr 问题。
