### ISSUE TITLE
新增谷歌镜像请求

### ISSUE THREAD

**Issue by zenuo** [Alvin9999/new-pac#358]
本人的谷歌镜像站点，https://176.122.157.73:5000，源代码https://github.com/zenuo/gogo，希望可供各位使用

**Comment by Alvin9999** [comment]
你好，你的谷歌镜像界面和原生的差距有点大哦

**Comment by zenuo** [comment]
非原版，原理是提取原版网站的结果，结果和原版一样；具有网络流量耗费小和简洁的特点😂

自由上网 <notifications@github.com>于2018年7月9日 周一下午7:43写道：

**Comment by Alvin9999** [comment]
已收录，十分感谢。

**Comment by zenuo** [comment]
举手之劳，🤝

自由上网 <notifications@github.com>于2018年7月10日 周二上午5:51写道：

**Comment by abchb99** [comment]
在手机浏览器上使用颜色不正常，搜索出来的内容由于颜色的原因看不见。

**Comment by Alvin9999** [comment]
@zenuo  请优化一下哈

**Comment by zenuo** [comment]
@abchb99 可以发一下截图吗？谢谢。

**Comment by abchb99** [comment]
![screenshot_2018-07-13-22-13-29-262_com mmbox xbrowser](https://user-images.githubusercontent.com/16471155/42696367-7a2f046c-86a7-11e8-9a7c-839b5ced636e.png)
就是这样，用的X浏览器。

**Comment by abchb99** [comment]
现在显示正常，多谢。

**Comment by zenuo** [comment]
@abchb99 好的´ ▽ ` )ﾉ

@Alvin9999 已经优化哈_(:з」∠)_
