### ISSUE TITLE
GoAgent ipv6上推特视频都播放不了，

### ISSUE THREAD

**Issue by 1343712786** [Alvin9999/new-pac#359]
- 

-

**Comment by Alvin9999** [comment]
试试GoProxy ipv6版呢

**Comment by nbrnred** [comment]
最近ipv6 GP和GO速度都很慢，是不是IP不行了该更新下了？服务器也不是很稳定要经常换来换去才能用。

**Comment by Alvin9999** [comment]
遇到干扰了，ipv6通道，从反馈看不同的地区封锁强度不同

**Comment by nbrnred** [comment]
还是GPQ使用方便，虽然不能下载大文件，但使用起来很方便，ipv6版使用很繁琐，持续性也不强。
