### ISSUE TITLE
用ubuntu添加vps的问题

### ISSUE THREAD

**Issue by birdest** [Alvin9999/new-pac#361]
对一个新服务器输入
ssh root@149.28.20.213

弹出
The authenticity of host '149.28.20.213 (149.28.20.213)' can't be established.
RSA key fingerprint is SHA256:frL19lKf+36WDIE7YEgT3I5juh5qCUDoxmHKVbGbpRc.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '149.28.20.213' (RSA) to the list of known hosts.

之后如果删除了该服务器操作一个新服务器（地址改变），会出现警告，并且无法连接
qc@qc-VPCEA35EC:~$ ssh root@149.28.20.213
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:frL19lKf+36WDIE7YEgT3I5juh5qCUDoxmHKVbGbpRc.
Please contact your system administrator.
Add correct host key in /home/qc/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/qc/.ssh/known_hosts:1
  remove with:
  ssh-keygen -f "/home/qc/.ssh/known_hosts" -R "149.28.20.213"
RSA host key for 149.28.20.213 has changed and you have requested strict checking.
Host key verification failed.

于是我rm了/home/qc/.ssh/known_hosts，又会出现第一个场景，这个问题怎么解决

**Comment by birdest** [comment]
其实我已经设置好了，就是以后要设新服务器ubuntu又得删除老的地址，这个应该怎么解决呢

**Comment by Alvin9999** [comment]
我不会，等大佬来解答
