### ISSUE TITLE
什么时候能把 tutlr 的 ipv6 给消灭了呢

### ISSUE THREAD

**Issue by TaylorBoy** [Alvin9999/new-pac#362]
所有的 2.5 套餐都变成 ipv6 了，是不是可以让 ipv4 连到 ipv6 的 vps 上，然后让 ipv6 的 vps 兼容访问 ipv4/ipv6 的网站，这岂不是完美 =.=，会不会异想天开了我 ......

**Comment by Alvin9999** [comment]
试试这个ipv6开启方法：https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95
