### ISSUE TITLE
操你妈，盗老子文章，狗比

### ISSUE THREAD

**Issue by iamsdk** [Alvin9999/new-pac#364]
https://juejin.im/user/5a4f60d0f265da3e261bc5fd/posts
老子这才是正版

**Comment by wangchaowei** [comment]
@iamsdk 你是逗比吗，你文章是2018年02月26日，这个教程几年前就有了，你个傻B

**Comment by fws407296762** [comment]
为了流量，居然还有骂人引起好奇心，然后吸引别人去购买，我擦...牛逼，有想法，这也算是一个拉流量得方式了

**Comment by bearchess** [comment]
惊了 git上还有这种。。

**Comment by Alvin9999** [comment]
额。。。
