### ISSUE TITLE
vps 问题

### ISSUE THREAD

**Issue by Terrobladediao** [Alvin9999/new-pac#366]
从周三开始连续4天，每天新注册一个服务器，分到ip之后用来当vps，但是第二天这个ip就直接被封禁了，之后又注册了3了也是这样。（每次不管是部署还是使用的时候都未开启任何杀毒软件） 请问这是当地运营商策略问题还是我被盯上了？ 害怕 求一下解答 感谢

**Comment by Alvin9999** [comment]
你用的vps是哪家的？用的哪个位置的服务器？搭建的是ssr吗? 账号的加密方式、协议等这些信息配置的什么 呢？我帮你分析下

**Comment by Terrobladediao** [comment]
vultr 的5美元套餐NJ seattle Silicon 都部署过 用的是ssrmu的脚本  因为自己也是初学shell 仅修改了脚本的配置环节，让自己可以一键配置多个内部账号使用xftp传送到远程vultr主机，部署完成后自己测试时也是正常 
加密aes-256-cfb 协议 auth-sha-v4 混淆plain和tls1.2都用过  
请问这其中哪一环会存在漏洞呢

**Comment by Alvin9999** [comment]
那试试不手动修改呢

**Comment by xiaokachen** [comment]
确实，前几天我也是几乎一天就被封，用shadowrocket  ping不通，但是在cmd里面能ping 的通，这两天好了，暂时还没有被封，有没有更好的方法能够最大减少被封的几率

**Comment by Terrobladediao** [comment]
前天尝试了直接从服务器下载的ssrmu，今天还是被墙。而且也是可以ping通但是不管是ssr还是ssh登陆都不行了

**Comment by Alvin9999** [comment]
如果ip能ping通，但xshell连接不同，这个是不正常的。可以把xshell卸载了，然后重新安装后再连接。
