### ISSUE TITLE
服务器端ping google.com正常，但我的电脑连不上

### ISSUE THREAD

**Issue by birdest** [Alvin9999/new-pac#369]
除google外一切正常，包括google mail和youtube。
google页面显示
无法访问此网站
www.google.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED

大概有什么可能性呢
今天下午之前都是正常的
--
同一wifi下的其他设备可以连到google。
没有动过任何设置。直接输ip地址也连接不了。
难道google由于某种原因屏蔽我了？

用edge试了下，提示是
无法安全地连接到此页面
这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。
尝试此操作:
返回到前一页

**Comment by Alvin9999** [comment]
证书问题？你试试打开google.com.hk

**Comment by birdest** [comment]
@Alvin9999 对的，hk是可以的。
