### ISSUE TITLE
goagent挂了

### ISSUE THREAD

**Issue by PvCDp** [Alvin9999/new-pac#37]
今天ip全部失效，没办法访问了，gogo还可以，虽然速度慢，但是还是可以访问谷歌。

**Comment by Alvin9999** [comment]
GoAgent版可以正常使用，如图：
![111](https://cloud.githubusercontent.com/assets/12132898/23112940/7229623a-f76f-11e6-99b3-0f60fa53a160.PNG)

你可以这样做：先排除杀毒软件和防火墙的干扰，把这俩都退出或关闭，然后重新解压，更新ip到最新的，再试试看

**Comment by PvCDp** [comment]
还是不行，估计我是这边的问题。

**Comment by Alvin9999** [comment]
试试GoProxy版

**Comment by PvCDp** [comment]
@Alvin9999 用你最近更新的同一批ip使用goagent完全不能上网，用goproxy就可以，显示有20个左右的good_addrs,估计goagent以后可能不能正常使用了。多谢博主！

**Comment by Alvin9999** [comment]
@PvCDp  你隔一段时间再测试一下。是有点奇怪。
