### ISSUE TITLE
关于自建ssr服务器的问题

### ISSUE THREAD

**Issue by zhdzaq** [Alvin9999/new-pac#371]
是不是重新建一个服务器，然后部署以后，Xshell里的所有东西以及谷歌加速就都得重新设置，是这个意思吗？因为只有晚上在家才上网，白天如果不删除的话它也消费啊

**Comment by Alvin9999** [comment]
是的，都要重新设置。

虽然白天你没用，但是这部分资源你是占用了的，别人无法使用这部分资源，所以对于vultr来说要收费。

**Comment by zhdzaq** [comment]
明白，感谢
