### ISSUE TITLE
能否更新v2ray的linux教程

### ISSUE THREAD

**Issue by birdest** [Alvin9999/new-pac#373]
想用ubuntu配置v2ray,下载了最新版3.35放进/usr/lib。按照配置服务端教程过完（bbr加速服务那里没有完成，因为选完4.18内核服务器似乎就爆了，之后再也联不上了），scp下载了config.json放进了v2ray的地址，运行后浏览器使用127.0.0.1:1080代理，然后悲剧的是
V2Ray v3.35 (die Commanderin) 20180809
A unified platform for anti-censorship.
2018/08/17 00:58:13 [Warning] Core: V2Ray v3.35 started
2018/08/17 01:00:01 [Info] [2176655797] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown Socks version: 71
2018/08/17 01:00:01 tcp:127.0.0.1:35734 rejected  Proxy|Socks: unknown Socks version: 71
2018/08/17 01:00:01 [Info] [3960243575] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown Socks version: 71
2018/08/17 01:00:01 tcp:127.0.0.1:35736 rejected  Proxy|Socks: unknown Socks version: 71
2018/08/17 01:00:01 [Info] [2361110940] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown Socks version: 71
2018/08/17 01:00:01 tcp:127.0.0.1:35738 rejected  Proxy|Socks: unknown Socks version: 71
。。。
根本联不上啊
由于没有给linux版的教程，不知哪里出了问题

**Comment by Alvin9999** [comment]
如果服务器连不上，那么v2ray是用不了的。建议重新开个新的服务器，可以先部署bbr，再部署v2ray脚本。

**Comment by birdest** [comment]
我肯定换个服务器再测试的阿。。
另外运行ssr脚本时，backspace会变成！？，也就是无法退格。是脚本本身的问题么？

**Comment by Alvin9999** [comment]
可以复制。如果不行，只能关闭连接，重新再连哦。

**Comment by birdest** [comment]
之后没再试v2ray
爆机应该是系统版本太低的问题，也就是说按教程走应该是无法配置bbr的==
Backspace的问题查了下找到一个解释的网页https://blog.csdn.net/chenggong2dm/article/details/8290306
今天vultr似乎被墙了。就上来看下。
