### ISSUE TITLE
搭建ssr连接后  浏览器无法访问任何网站

### ISSUE THREAD

**Issue by myallz** [Alvin9999/new-pac#375]
能帮忙解决一下吗？

**Comment by birdest** [comment]
浏览器无法访问任何网页应该是填了代理端口但是相应的软件没开或无效。把浏览器改成不使用代理就可以正常上网了==其他你和版主慢慢沟通吧。

**Comment by Alvin9999** [comment]
同上，建议把问题描述清楚点，也可以截图的。
