### ISSUE TITLE
新版macOS无法使用 10.13.6

### ISSUE THREAD

**Issue by hiblacker** [Alvin9999/new-pac#378]
家里iMac和手机都可以正常使用没问题，MacBook为10.13.6，怎么也连不上，让同事下了一个ssr。同样的配置，他的是10.13.5，就可以正常使用没问题。困扰我一周了，满脑瓜问号，求大神解答。

**Comment by hiblacker** [comment]
我参照。自建SS/SSR服务器教程   这篇文章搭建的ssr服务

**Comment by Alvin9999** [comment]
有没有可能是防火墙的问题呢

**Comment by hiblacker** [comment]
@Alvin9999   我看了，防火墙关闭了的

**Comment by hiblacker** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/22385375/44858571-e2885680-aca4-11e8-9f84-ee1ee972d1c0.png">

**Comment by hiblacker** [comment]
@Alvin9999 老大救救啊。 没有谷歌的日子好难受

**Comment by hiblacker** [comment]
找到一个解决办法。更新xcode   我的是新电脑。 还没安装过。。。  正在尝试。。。

**Comment by hiblacker** [comment]
@Alvin9999 还是不行，老大能给指条明路吗？我甚至把系统语言换回了中文。。。还是不行。
<img width="652" alt="image" src="https://user-images.githubusercontent.com/22385375/44894336-d098c900-ad21-11e8-95a6-b25f1af4d35b.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/22385375/44894381-0938a280-ad22-11e8-8501-8f1487687676.png">

**Comment by Alvin9999** [comment]
我也没用过MAC，不知道咋个解决哦，你这个应该是系统的问题，因为其它设备可以用。对不对？
