### ISSUE TITLE
关于hackforums

### ISSUE THREAD

**Issue by Skyline23** [Alvin9999/new-pac#38]
一进去就提示IP被ban,有没有什么办法解决？

**Comment by Alvin9999** [comment]
网上搜索结果：这个是服务器的问题，他可能防火墙或者是访问安全设置那里设置了只对特定的人开放，或者是打开后有一个安全验证的如果错误就被拒绝的机制！总之就是网站已经对你拒绝访问！

目前没有解决办法，你也可以自己网上搜搜看。

**Comment by Skyline23** [comment]
好吧,谢谢啦xD
