### ISSUE TITLE
作者大大这种情况怎么办

### ISSUE THREAD

**Issue by Cg110778** [Alvin9999/new-pac#383]
Broadcast message from root@vultr.guest
	(/dev/pts/0) at 10:17 ...

The system is going down for reboot NOW!
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(cg) at 10:17:40.

Type `help' to learn how to use Xshell prompt.

**Comment by Alvin9999** [comment]
重启服务器后，需要几分钟才能手动去连接，就像你的电脑重启后一样，需要等待一点时间。

**Comment by Cg110778** [comment]
好的非常感谢
