### ISSUE TITLE
IPV6问题

### ISSUE THREAD

**Issue by sdyy86** [Alvin9999/new-pac#384]
这些IPV6的版本我的都不太好用，网页打开非常慢，没有之前的QUIC版本网速——怎么办啊

**Comment by Alvin9999** [comment]
Quic版已失效。如果ipv6两款版本都尝试了且teredo服务器也都试过了，那么就换其它类型的软件。

**Comment by anesliu** [comment]
原生ipv6无压力

**Comment by sdyy86** [comment]
啥是原生IPV6啊，求教！！

**Comment by anesliu** [comment]
@sdyy86 就是宽带运营商提供的ipv6
