### ISSUE TITLE
提问：打不开那些网站！

### ISSUE THREAD

**Issue by XmJwit** [Alvin9999/new-pac#387]
萌新提问：-_-}}：
Linux SSR 使用方法二 https://github.com/Turing2333/Detailed-tutorial-on-the-building-and-usage-of-SSR/blob/master/Instructions/Clients%20manual%20for%20each%20platform/Linux%20SSR%E7%9B%B8%E5%85%B3%E8%AF%B4%E6%98%8E.txt
可以正常上网，不过那些网站打不开，ping不通。
系统是ubuntu 16.04
相应选项填好后，回车出现：

2018-09-15 16:51:38 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2018-09-15 16:51:38 ERROR    daemon.py:155 not running
IPv6 support
Success!

而后我ssr delay，回车：
? Please select group 666
test route  打码
✔ delay:82ms

再ssr local
ssr local
[ { type: 'input',
    name: 'workers',
    message: 'What workers will be?',
    default: 1 },
  { type: 'input',
    name: 'timeout',
    message: 'What timeout will be?',
    default: 300 },
  { type: 'input',
    name: 'local_port',
    message: 'What local_port will be?',
    default: 1080 },
  { type: 'input',
    name: 'local_address',
    message: 'What local_address will be?',
    default: '127.0.0.1' } ]
? What workers will be? 1
? What timeout will be? 300
? What local_port will be? 1080
? What local_address will be? 127.0.0.1
{ workers: 1,
  timeout: 300,
  local_port: 1080,
  local_address: '127.0.0.1' }
求大佬指教！

**Comment by Alvin9999** [comment]
我对linux系统部署不了解，教程是转载别人的，所以需要自行摸索哦。如果某个脚本部署后不行，可以换其它的部署脚本。另外，建议用3.5美元或以上的服务器，2.5美元的服务器只提供ipv6支持。

**Comment by XmJwit** [comment]
> 我对linux系统部署不了解，教程是转载别人的，所以需要自行摸索哦。如果某个脚本部署后不行，可以换其它的部署脚本。另外，建议用3.5美元或以上的服务器，2.5美元的服务器只提供ipv6支持。

昨天折腾了一下午，终于搞好了，搭配electron-ssr和SwitchyOmega可以用了

**Comment by XmJwit** [comment]
顺便发个图，嘻嘻
![gayhub](https://user-images.githubusercontent.com/36185379/45592184-29f72e00-b999-11e8-8db6-53c238af5c85.png)

**Comment by Alvin9999** [comment]
恭喜恭喜啊
