### ISSUE TITLE
goa点击IP更新后不能用了

### ISSUE THREAD

**Issue by PvCDp** [Alvin9999/new-pac#39]
![default](https://cloud.githubusercontent.com/assets/13728892/23288044/0a4862d2-fa7c-11e6-8d51-15b8b14df78e.jpg)

**Comment by PvCDp** [comment]
出现文件格式错误，请博主看看是什么情况，不点ip更新程序可以正常使用。

**Comment by caofengzi** [comment]
360給你修改了吧。

**Comment by PvCDp** [comment]
没有用360，只用了360浏览器，杀毒软件是金山毒霸

**Comment by PvCDp** [comment]
与杀毒软件没有关系，我还用avast也是如此，不能点击ip自动更新，点击了就出现图片那样，不能上网。

**Comment by Alvin9999** [comment]
把杀毒软件退出来，然后重新解压再运行ip更新文件，ip更新文件有两个，都可以试试看的

**Comment by PvCDp** [comment]
退出杀毒软件可以更新了，多谢，不过新更新的ip不如之前1月2号那批好用。

**Comment by caofengzi** [comment]
能夠使用就不需要更新，這也是開發者說明文檔裡面提示的，幹嘛不用原版chrome而是用一樣內核的360呢？俺下載完了就把goagent提取出來了，另外為什麼使用goagent代理在githup發不了回覆呢？

**Comment by PvCDp** [comment]
用goa,gop都不能在这里留言，我以为是我这边问题，看来都不行。

**Comment by PvCDp** [comment]
@caofengzi 确实不能回复，不知怎么回事。我现在用两个浏览器，360用打开国内网站，谷歌用来打开国外的，这样速度都不受影响。
