### ISSUE TITLE
今天服务不可用

### ISSUE THREAD

**Issue by chat491231702** [Alvin9999/new-pac#391]

**Comment by Alvin9999** [comment]
你问的是两个免费ss/ssr账号吧，可以用另外一个试试。38.141.44.98 服务器出现故障，修复需要时间。

**Comment by nbrnred** [comment]
自从谷歌要搞中国版的谷歌后，iPV6看YouTube就非常大慢，谷歌的GAE和YouTube不都是谷歌的吗，怎么最近看YouTube那么慢现在速度和以前完全不是一个级别。

**Comment by nbrnred** [comment]
自从谷歌要搞中国版的谷歌后，iPV6看YouTube就非常的慢，谷歌的GAE和YouTube不都是谷歌的吗，怎么最近看YouTube那么慢现在速度和以前完全不是一个级别。
