### ISSUE TITLE
遇到了一些问题

### ISSUE THREAD

**Issue by CKRYOU** [Alvin9999/new-pac#393]
大大你好，在教程的部署管理脚本那里，一套流程之后出现了unzip安装失败的情况
接着用备用脚本后又说下载失败
卡在这部实在没办法了，希望可以得到解决。

![41635](https://user-images.githubusercontent.com/43326232/45602737-a64f4700-ba55-11e8-8569-75f71853877b.png)
![6666](https://user-images.githubusercontent.com/43326232/45602738-a9e2ce00-ba55-11e8-8b49-09ff67efda5c.png)

**Comment by Alvin9999** [comment]
你是怎么复制脚本的呢

**Comment by CKRYOU** [comment]
今天晚些时候又试了几次，已经搭建成功了！

**Comment by Alvin9999** [comment]
好的，恭喜恭喜
