### ISSUE TITLE
ss免费账号不可用 大佬

### ISSUE THREAD

**Issue by kris0325** [Alvin9999/new-pac#394]
这两个账号都不可用了，  大佬 能跟新下吗 ？ 
103.114.161.158 
38.144.44.98

![Uploading image.png…]()

**Comment by Alvin9999** [comment]
103应该可以用，从服务器资源消耗看，有不少人在使用。

38服务器故障，带修复。

**Comment by Alvin9999** [comment]
两个账号已更新
