### ISSUE TITLE
搭建完ssr账号谷歌学术还是上不去...

### ISSUE THREAD

**Issue by Ellen9616** [Alvin9999/new-pac#395]
https://scholar.google.com/和http://scholar.google.com/两个都显示流量异常......
【We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.
】换了服务器也会这样,这种要怎么解决啊？

**Comment by Alvin9999** [comment]
可能是这个ip段有很多人在使用，所以导致了谷歌学术判定为机器人（流量异常）。这个问题不好解决，可以用我分享的谷歌镜像地址应急用。[谷歌镜像地址](https://github.com/Alvin9999/new-pac/wiki/%E8%B0%B7%E6%AD%8C%E9%95%9C%E5%83%8F)

**Comment by Ellen9616** [comment]
好的谢谢大佬！！

**Comment by gfw-breaker** [comment]
@Ellen9616 可能你运气不好，恰好遇到的几个IP都有这种问题。可以尝试换一个区域部署VPS。
