### ISSUE TITLE
有没有交流群啊？或者微信群什么的？

### ISSUE THREAD

**Issue by wang1231** [Alvin9999/new-pac#397]
有没有交流群啊？或者微信群什么的？

**Comment by Alvin9999** [comment]
没有哦

**Comment by dadidzf** [comment]
@Alvin9999 非常感谢，可以建一个微信交流群哦，另外可以在上面加一个微信或支付宝打赏码，让我们支持一下

PS：我个人之前在阿里云买过服务器，搭建过ss，后来被封了，最近一直用你共享的，感觉挺好，因为我只是偶尔看看Google 和 facebook了，你那个经常更新，网速也不慢，所以都懒得自己再去买服务器搭建了。。。

**Comment by xfmniao** [comment]
用微信？你在國內嗎？如果是這不找死嗎

**Comment by xfmniao** [comment]
微信是間諜軟件能用它聊天這不是 Game Over 嗎

**Comment by xfmniao** [comment]
共產黨忠誠的警察天天監控微信。

**Comment by Alvin9999** [comment]
楼上说的对。

**Comment by dadidzf** [comment]
有道理

**Comment by gfw-breaker** [comment]
用Issue交流足诶。暴露自己的微信、支付宝甚至PayPal无异于举报自己。另外，随着技术的发展，当前安全的工具可能以后也不安全，所以连Telegram也不要用。

**Comment by qianyiliushang** [comment]
可以搞个telegram
