### ISSUE TITLE
自从谷歌要搞中国版的谷歌后，iPV6看YouTube就非常的慢，谷歌的GAE和YouTube不都是谷歌的吗，怎么最近看YouTube那么慢，现在速度和以前完全不是一个级别。

### ISSUE THREAD

**Issue by nbrnred** [Alvin9999/new-pac#398]
_Originally posted by @nbrnred in https://github.com/Alvin9999/new-pac/issues/391#issuecomment-422809667_

**Comment by Alvin9999** [comment]
影响翻墙速度的因素有很多,也不排除是你那里ipv6被干扰而导致的。可以试试切换不同的teredo服务器。

**Comment by nbrnred** [comment]
能连上的服务器速度都一样慢。换别的方式看YouTube很快，和网速没关系，是谷歌GAE对YouTube的速度搞了鬼。

**Comment by nbrnred** [comment]
能连上的IPV6服务器速度都一样慢。换别的方式看YouTube很快，和网速没关系，是谷歌GAE对YouTube的速度搞了鬼。
