### ISSUE TITLE
免费Shadowsocks账号 “复制技术” 挺熟练啊，没少干吧？

### ISSUE THREAD

**Issue by ToyoDAdoubi** [Alvin9999/new-pac#40]
本来看你也是免费Shadowsocks分享的，我就把你网站刮到我的页面上了。
[Shadowsocks免费账号分享](https://doub.io/sszhfx)
结果很多在我网站分享免费Shadowsocks账号的人发现他们的账号被“复制”到你这里来了，也没有著名源链接和分享者，好多人跟我举报你。
哎，我也无话可说了，有人在建设，有人在破坏，希望一些人不要只会复制粘贴，而不知道什么叫做尊重！
很多分享者因为这类问题导致被滥用，都取消了分享。
如果这个issues被某人直接关闭或者完全无视，那么正好说明了某人心虚 :)

**Comment by tulipearl** [comment]
围观，分享别人的东西好歹注明一下来源吧？做人的基本道理都不懂么？

**Comment by viewer12** [comment]
防不胜防

**Comment by brookrchu** [comment]
从doub.io上来的，围观此issues。

**Comment by Alvin9999** [comment]
你好，十分抱歉！因为我想的是既然是公开分享出来的，所以就图方便直接复制黏贴过来了。我分享的账号出了自建外，全来自于互联网和网友的贡献。

我最大的问题应该是没有注明来源，缺少版权意识。你提到滥用一词，所以为了你的网站的分享者的利益，我会立马删掉这些账号。

对不起，给你们带来的困扰深感抱歉。今后我从互联网上搜集免费账号会留意版权问题以及表达尊重之意。

**Comment by ToyoDAdoubi** [comment]
@Alvin9999 既然你意识到了问题，那我也不追究了。
