### ISSUE TITLE
大佬能不能再分享一下之前那个开启Ivp6的脚本，不是配置那个。纯开启

### ISSUE THREAD

**Issue by Explore911** [Alvin9999/new-pac#400]
谢谢

**Comment by Explore911** [comment]
就是一个批处理文件

**Comment by Explore911** [comment]
@echo off 
netsh interface isatap set state default 
netsh interface teredo set state default 
netsh interface teredo set state server=[teredo.remlab.net ]
netsh interface ipv6 set teredo enterpriseclient

好像这个也许。。。

**Comment by AnyWAT** [comment]
管理权限运行CMD
纯关闭：netsh int ipv6 set teredo disable
纯开启：netsh int ipv6 set teredo enterpriseclient
https://github.com/Alvin9999/new-pac/issues/401#issuecomment-425071858

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases XX-Net 目录内的批处理 disable_ipv6.bat enable_ipv6.bat

**Comment by AnyWAT** [comment]
貌似Win10从某版本开始。。。https://github.com/XX-net/XX-Net/issues/11511#issuecomment-425631370
