### ISSUE TITLE
（求助）用了一会ipv6就关了怎么回事

### ISSUE THREAD

**Issue by Aricttt** [Alvin9999/new-pac#401]
我翻墙用了一会之后，谷歌突然就进不去，显示是这样的，和没打开ipv6是一样的
![qq 20180925191059](https://user-images.githubusercontent.com/43572491/46010890-c38bb180-c0f6-11e8-814d-11c0a5222651.png)

然后我就又去照着开启ipv6的方法做了一遍，重启电脑后可以用了，用了一会又不行了。我用edge打开ipv6测试，结果是这样的

![qq 20180925191322](https://user-images.githubusercontent.com/43572491/46011022-2b41fc80-c0f7-11e8-9916-998220644ddc.png)
这是被自动关闭了吗？咋回事啊，我电脑重装系统zhiqia之前都没有这个毛病

求助

**Comment by Alvin9999** [comment]
那个提示是你没有成功开启ipv6导致的。可以按照使用说明更换其它的teredo服务器，然后再试试看。如果所有的teredo服务器都尝试了，还是不行的话，说明目前你的网络环境或系统不适合用ipv6版，建议换其它类型的软件。

**Comment by AnyWAT** [comment]
（开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
