### ISSUE TITLE
下载不了shadowsockR

### ISSUE THREAD

**Issue by zhangxixi0904** [Alvin9999/new-pac#406]
您好，我按照教程部署vultr，但是github的ssr.sh脚本下载不了，我就在本地下载完之后，再通过vim创建一份文件把ssr.sh的内容复制进去，但是安装的过程中还是需要在github中下载shadowsockR，显然下载失败，请问应该怎么办？

[信息] 开始下载/安装 ShadowsocksR文件...
--2018-10-14 14:47:41--  https://codeload.github.com/ToyoDAdoubi/shadowsocksr/zip/manyuser/shadowsocksr-manyuser.zip
Resolving codeload.github.com... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com|192.30.253.121|:443... failed: Network is unreachable.
Connecting to codeload.github.com|192.30.253.120|:443... failed: Network is unreachable.
[错误] ShadowsocksR服务端 压缩包 下载失败 !

另外建立的服务器为什么ping不通任何网址？

**Comment by Alvin9999** [comment]
用另外一个脚本看看。提醒一下，vultr要买3.5美元的套餐，2.5美元的套餐的服务器只提供ipv6

**Comment by zhengziheng** [comment]
我也是第二步最后下载这个文件 提示404 然后用第三部的脚本安装之后，没有部署成功

**Comment by zhangxixi0904** [comment]
> 我也是第二步最后下载这个文件 提示404 然后用第三部的脚本安装之后，没有部署成功

我换成3.5美元的ipv4之后的确就可以了。。

**Comment by zhengziheng** [comment]
我是用的 3.5美元的ipv4 问题是https://codeload.github.com/ToyoDAdoubi/shadowsocksr/zip/manyuser/shadowsocksr-manyuser.zip
这个地址是404就没法下载了

**Comment by zhangxixi0904** [comment]
> 我是用的 3.5美元的ipv4 问题是https://codeload.github.com/ToyoDAdoubi/shadowsocksr/zip/manyuser/shadowsocksr-manyuser.zip
> 这个地址是404就没法下载了
> 
> 而且 刚才ping了google 是能通的

似乎就是这个地址挂了，我也上不去，不过我当时部署的时候没有遇到这个问题，我也不太清楚了

**Comment by momomojing** [comment]
有大兄弟解决了嘛

**Comment by momomojing** [comment]
> 是的，我到作者主页看了，他删除了几个部署的脚本

有解决方案了没

**Comment by zhangxixi0904** [comment]
现在的教程里不是：
yum -y install wget
wget -N --no-check-certificate https://raw.githubusercontent.com/Alvin9999/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh
吗？ 我好像还是可以重新部署啊 @zhengziheng @momomojing

**Comment by zhangxixi0904** [comment]
我看了一下，好像是@ToyoDAdoubi的仓库里面已经没有了那个目录“https://codeload.github.com/ToyoDAdoubi/shadowsocksr”，好在他有一个备份！！我把服务器中下载下来的那份ssr.sh修改成备份地址就可以了
把606行、612行、613行的shadowsocksr改成shadowsocksrBackup @zhengziheng @momomojing

**Comment by Alvin9999** [comment]
最新脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh
