### ISSUE TITLE
Xshell 6和SSR这两个怎么弄开机自动启动

### ISSUE THREAD

**Issue by HASEEMEIZU** [Alvin9999/new-pac#408]
Xshell 6和SSR这两个怎么弄开机自动启动，每次开机都要打开这两个后才能上到网，怎么设置这两个开机启动

**Comment by Alvin9999** [comment]
SSR是客户端，每次使用必须打开它。
xshell只是一个连接服务器的工具，部署好服务器后以后不用打开它。

**Comment by Alvin9999** [comment]
将软件设置为开机启动，可以网上搜一下自己电脑系统对应的方法。

**Comment by AnyWAT** [comment]
@Alvin9999 自动切换规则列表网址信息时间上相差近3年😂 2015年11月17日与 2018年9月22日
https://raw.githubusercontent.com/bfwlist/web/master/a.txt
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by Alvin9999** [comment]
@AnyWAT 额，有没有好的建议哦？

**Comment by AnyWAT** [comment]
建议：
1、SwitchyOmega 内
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 替换 https://raw.githubusercontent.com/bfwlist/web/master/a.txt
2、浏览器的升级 ChromeUpdater.exe 已失效，更新到 GreenChrome6.5.7.zip 及 ChromeUpdateSharp_v2.4.5.0.zip 解决

**Comment by xfmniao** [comment]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]
"SSR"="\"C:\\××××××\\×××××\\××××\\××××.exe\""


AnyWAT <notifications@github.com> 于2018年10月27日周六 上午8:50写道：

**Comment by AnyWAT** [comment]
楼上对楼主说：（注册表）怎么设置开机启动 😂

**Comment by xfmniao** [comment]
微软都把GITHUB收购了。我就用WIN了 joy

**Comment by xfmniao** [comment]
Please view this email in an HTML compatible email client.
