### ISSUE TITLE
这个是什么问题

### ISSUE THREAD

**Issue by dibaiqigai** [Alvin9999/new-pac#409]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp6 [2001:b032:a501::c]:443: connectex: A socket operation was attempted to an unreachable network."
}

**Comment by dibaiqigai** [comment]
@Alvin9999

**Comment by Alvin9999** [comment]
这是你的电脑系统没有成功开启ipv6导致的，你可以按照使用说明更换teredo服务器试试，如果所有的teredo服务器都尝试了，还是不能开启ipv6的话，说明你的电脑系统和网络环境目前开启不了ipv6，那么ipv6版就用不了了，此时为了翻墙，建议你更换其它类型的软件。比如，v2ray版、ssr版、skyzip版、wujie版等。

**Comment by wang3stone** [comment]
@Alvin9999  请问我的goproxy出了什么问题？
------------------------------------------------------
GoProxy Version    : r1624 (go/62e20ef36a windows/amd64)
GoProxy Profile    : PHP
Listen Address     : 127.0.0.1:8080
Enabled Filters    : stripssl|autoproxy,php|
Pac Server         : http://127.0.0.1:8080/proxy.pac
PHP Servers         : https://highspeedtrain.herokuapp.com/index.go
------------------------------------------------------
I1031 23:21:47.230520   16840 stripssl.go:151] 127.0.0.1:50383 "STRIP CONNECT www.googleapis.com:443 HTTP/1.1" - -
I1031 23:21:47.237501   16840 stripssl.go:151] 127.0.0.1:50384 "STRIP CONNECT mtalk.google.com:5228 HTTP/1.1" - -
I1031 23:21:47.339228   16840 stripssl.go:151] 127.0.0.1:50385 "STRIP CONNECT www.googleapis.com:443 HTTP/1.1" - -
I1031 23:21:47.691287   16840 stripssl.go:151] 127.0.0.1:50386 "STRIP CONNECT accounts.google.com:443 HTTP/1.1" - -
I1031 23:21:47.965553   16840 stripssl.go:151] 127.0.0.1:50388 "STRIP CONNECT www.google.com:443 HTTP/1.1" - -
I1031 23:21:48.007441   16840 stripssl.go:151] 127.0.0.1:50389 "STRIP CONNECT www.google.com:443 HTTP/1.1" - -

**Comment by Alvin9999** [comment]
你用的herokuapp来部署的？

**Comment by wang3stone** [comment]
> 你用的herokuapp来部署的？

是的

**Comment by Alvin9999** [comment]
我对这个东西不了解哦
