### ISSUE TITLE
Virus is detacted in new pack.

### ISSUE THREAD

**Issue by xyang5987** [Alvin9999/new-pac#410]
Chrome69_32bit_GP_ipv6_2018.9.8.7z Failed - Virus detected
http://45.32.141.248:8082/files/e55fb094-2a38-434a-8d9e-58d540c67f7e/Chrome69_32bit_GP_ipv6_2018.9.8.7z

**Comment by Alvin9999** [comment]
没有毒的，杀毒软件误删了哦

**Comment by Alvin9999** [comment]
翻墙时最好不要用国产杀毒软件

**Comment by xyang5987** [comment]
我的系统里没有大陆的杀毒软件的，是win 10自带的defender测到的。

**Comment by xyang5987** [comment]
现在用的去年回国前装的翻墙软件Chrome62_64bit_FG_2017.10.22，中途也有defender的警告一次。
