### ISSUE TITLE
osx下用shell进行远程连接错误

### ISSUE THREAD

**Issue by Ellen9616** [Alvin9999/new-pac#412]
root@207.246.92.72's password: 
Last failed login: Sun Oct 28 16:04:40 CST 2018 from 201.16.249.209 on ssh:notty
There were 115 failed login attempts since the last successful login.
Last login: Sun Oct 28 15:58:05 2018 from 61.183.112.245
[root@vultr ~]# 

确定IP和密码都没有出错，但是就是一直显示连接失败，另一台win7系统的电脑通过xshell连接没有出现问题

**Comment by Alvin9999** [comment]
那是系统的问题？你用苹果系统的话，换个连接工具看看呢。如果你有两台电脑，只要能把账号部署成功，然后两台电脑都可以用这个账号的。

**Comment by Ellen9616** [comment]
换了shadowsocksX后成功连上了，感谢大佬
