### ISSUE TITLE
搭建的v2ray服务端无法下载config.json配置文件

### ISSUE THREAD

**Issue by jojolfy** [Alvin9999/new-pac#413]
如题，我用的是google云，直接在浏览器里打开的ssh，配置完成后配置文件被保存到了root文件夹，导致无法下载，本人小白，求指导，谢谢

**Comment by Alvin9999** [comment]
浏览器连接不行的，脚本不支持下载。

**Comment by jojolfy** [comment]
> 浏览器连接不行的，脚本不支持下载。

那为啥我之前搭建的SSR可以下载
