### ISSUE TITLE
您好 一直提示 ShadowsocksR 启动失败

### ISSUE THREAD

**Issue by hermitcrabcai** [Alvin9999/new-pac#415]
反复试了很多次  卸载安装 是6的系统  一直提示 失败 
![image](https://user-images.githubusercontent.com/26593656/48050518-13bd5f80-e1dd-11e8-8dba-a37691cc739a.png) 求解答

**Comment by hermitcrabcai** [comment]
![image](https://user-images.githubusercontent.com/26593656/48052941-50408980-e1e4-11e8-8534-d3610727c6e1.png)
查看日志如下

**Comment by hermitcrabcai** [comment]
自己已经搭建成功了 但是一直 使用不了 无法上网 尝试了日本和芝加哥的服务器

**Comment by Alvin9999** [comment]
你的浏览器有没有设置对应的代理呢

**Comment by hermitcrabcai** [comment]
> 你的浏览器有没有设置对应的代理呢

你说的 浏览器使用代理是指？我本地已经开启了代理 浏览器可以访问

**Comment by Alvin9999** [comment]
你看看这个呢
![default](https://user-images.githubusercontent.com/12132898/48414315-52c35600-e785-11e8-89dc-58d4f4511c1e.PNG)

**Comment by Alvin9999** [comment]
@AnyWAT  是http协议

**Comment by AnyWAT** [comment]
😂记忆中 SS、SSR 是Socks5:1080 例证：
https://www.flyzy2005.com/tech/switchyomega-proxy-server/ 
https://ssr.tools/150

**Comment by Alvin9999** [comment]
@AnyWAT 哦哦，这样啊，学习了哦

**Comment by AnyWAT** [comment]
😂至少SS是支持一端口2协议的 https://github.com/shadowsocks/shadowsocks-windows/issues/2073#issuecomment-439621687

**Comment by You00** [comment]
@Alvin9999  @AnyWAT 
电脑上连接上了可以用正常使用，但是手机连接上了还是翻不了，手机用的是Potatso Lite，大佬们知道是什么情况吗？

**Comment by Alvin9999** [comment]
@You00 原因是不同运营商封锁不同导致的。可以试试换参数，比如端口、加密方式等，看看行不行吧
