### ISSUE TITLE
密码拒绝？

### ISSUE THREAD

**Issue by jacknnnbauer** [Alvin9999/new-pac#417]
![default](https://user-images.githubusercontent.com/19789020/48618756-4af9f080-e9d5-11e8-9130-abbce094ab8d.PNG)
这个ssh服务器老是拒绝我输入的密码怎么办？
它也能自动调出来，但是总是反复拒绝密码

**Comment by Alvin9999** [comment]
你的vps选择的是什么系统呢

**Comment by jacknnnbauer** [comment]
> 你的vps选择的是什么系统呢

问题找到了。我的用户名一直没填写root，所以一直拒绝。现在搭建好了。现在我怎么保持xshell一直连接服务器？我点ctrl+z，没有反应。大脑端我要一直开着命令行，怎么才能缩小到消息提醒框里？

**Comment by Alvin9999** [comment]
部署好后，xshell可以关闭，xshell只是你需要对你的服务器做什么的时候才要打开它，仅仅是一个部署工具。
