### ISSUE TITLE
创建SSR 的时候 下载404了

### ISSUE THREAD

**Issue by momomojing** [Alvin9999/new-pac#419]
[信息] 开始下载/安装 ShadowsocksR文件...
--2018-11-20 10:55:40--  https://github.com/ToyoDAdoubi/shadowsocksr/archive/manyuser.zip
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-20 10:55:41 ERROR 404: Not Found.

**Comment by Alvin9999** [comment]
试试wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh
