### ISSUE TITLE
感謝開發維護者

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#42]
這裡的pac文件支持安卓系統嗎？

**Comment by Alvin9999** [comment]
应该可以，你试试看

**Comment by caofengzi** [comment]
@Alvin9999 謝謝回覆，俺是4.4.4版本不支持在wian裡面導入pac，只能使用代理機器人軟件，但是機器人軟件提示這是不受支持的pac格式文件。

**Comment by Alvin9999** [comment]
bug，用全局代理试试；手机导入pac文件不太懂，你可以网上查查看

**Comment by caofengzi** [comment]
謝謝開發者，感覺開發者應該是法輪大法的弟子吧？全局代理也是同樣提示。

You can't perform that action at this time.

**Comment by Alvin9999** [comment]
嗯，我会尽力的

**Comment by caofengzi** [comment]
國內很多人都誤會法輪大法了。

**Comment by Alvin9999** [comment]
你用GoProxy版试试看，我刚用这个试了，可以

**Comment by caofengzi** [comment]
gop沒有問題，俺也在用。

**Comment by theratlesnake** [comment]
一起让国内更多人上网，让更多人了解真相。
