### ISSUE TITLE
搭建ssr服务器的时候出问题(下载/安装 ShadowsocksR 404了) -- 临时解决

### ISSUE THREAD

**Issue by xiayuanyin** [Alvin9999/new-pac#420]
[信息] 开始下载/安装 ShadowsocksR文件...
--2018-11-20 10:40:31--  https://github.com/ToyoDAdoubi/shadowsocksr/archive/manyuser.zip
Resolving github.com (github.com)... 192.30.255.113, 192.30.255.112
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-20 10:40:31 ERROR 404: Not Found.

[错误] ShadowsocksR服务端 压缩包 下载失败 !

**Comment by Terrific5454** [comment]
我刚才重新搭建的时候也碰到这个问题了，之前的VPS刚刚被封。。。

**Comment by xiayuanyin** [comment]
我尝试了一下直接给之前装过ssr的系统备份了一下，然后还原到新机器上，成功能用了！！！
备份命令：
`cd /
tar pczf bak.tgz 
--exclude=/bak.tgz 
--exclude=/cdrom 
--exclude=/dev 
--exclude=/lost+found 
--exclude=/media 
--exclude=/mnt 
--exclude=/proc 
--exclude=/run 
--exclude=/sys 
--exclude=/tmp /`

还原系统：
`tar pxzf bak.tgz -C /`

**Comment by Alvin9999** [comment]
最新脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh

**Comment by Terrific5454** [comment]
> 最新脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh

谢谢了

**Comment by longshilin** [comment]
> 最新脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh

thanks!
