### ISSUE TITLE
多用户

### ISSUE THREAD

**Issue by Bingosty** [Alvin9999/new-pac#422]
脚本怎么设置多用户?

**Comment by Tryking** [comment]
> 如果你想把搭建的账号给多人使用，不用额外设置端口，因为一个账号（端口）就可以多人使用。
> 
> 如果想实现支持每个用户(端口)不同的加密方式/协议/混淆等，并且管理流量使用，可以参考多用户配置脚本：wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssrmu.sh && chmod +x ssrmu.sh && bash ssrmu.sh 安装后管理命令为：bash ssrmu.sh

关键是咋配置啊，里面的配置看不太懂，有好多参数不知道咋填@Alvin9999  多谢大佬

**Comment by Bingosty** [comment]
> > 如果你想把搭建的账号给多人使用，不用额外设置端口，因为一个账号（端口）就可以多人使用。
> > 如果想实现支持每个用户（端口）不同的加密方式/协议/混淆等，并且管理流量使用，可以参考多用户配置脚本：wget -N --no-check-certificate [https：//raw.githubusercontent。 com / ToyoDAdoubi / doubi / master / ssrmu.sh](https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssrmu.sh) && chmod + x ssrmu.sh && bash ssrmu.sh安装后管理命令为：bash ssrmu.sh
> 
> 关键是咋配置啊，里面的配置看不太懂，有好多参数不知道咋填@ Alvin9999 多谢大佬

里面的每一步都是有提示的，该默认的默认，仔细看看每一步的说明就o了

**Comment by Tryking** [comment]
@Bingosty  已解决，多谢，不该自作聪明改东西的
