### ISSUE TITLE
[错误] ShadowsocksR服务端 解压失败 !

### ISSUE THREAD

**Issue by TheoJiang** [Alvin9999/new-pac#423]
100%[======================================================================================================================================================================================================================>] 2,133,116   1.59M/s   in 1.3s    

Last-modified header missing -- time-stamps turned off.
2018-11-21 01:15:11 (1.59 MB/s) - “manyuser.zip” saved [2133116/2133116]

Archive:  manyuser.zip
c4507b7af1fe20a5a6adbb5e3b5a86da9d3a35e8
replace shadowsocksr-backup-manyuser/.travis.yml? [y]es, [n]o, [A]ll, [N]one, [r]ename: N
[错误] ShadowsocksR服务端 解压失败 !

===================================================

搞了半天。我没办法了。=。=
请教下遇到这种问题怎么办？

**Comment by Alvin9999** [comment]
**CentOS6/Debian6/Ubuntu14 ShadowsocksR一键部署管理脚本（2018.11.21更新）：**

**脚本一（2018.11.20更新）**

***

yum -y install wget

wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh

***

**备用脚本二（2018.11.21更新）**

**如果上面的脚本暂时用不了，可以用下面的备用脚本，备用脚本没有单独做图文教程，自己摸索下就会了。备用脚本卸载命令：./shadowsocksR.sh uninstall**

***

yum -y install wget

wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh

chmod +x shadowsocksR.sh

./shadowsocksR.sh 2>&1 | tee shadowsocksR.log

***
