### ISSUE TITLE
装完BBR之后就无法连通服务器了

### ISSUE THREAD

**Issue by Terrific5454** [Alvin9999/new-pac#425]
连续测试了两台机器，都跑完bbr的安装脚本重启之后就连不上了（Connection failed）

**Comment by Alvin9999** [comment]
试试先安装bbr再部署SS/SSR脚本

**Comment by jacknnnbauer** [comment]
我也遇到同样状况。从v2ray脚本部署后bbr加速就被墙了，

**Comment by jacknnnbauer** [comment]
![image](https://user-images.githubusercontent.com/19789020/48903965-ee487b00-ee97-11e8-925e-b49c451cc386.png)
我先部署后，也同样被服务器拒绝了，然后这个ip就直接ping不上了。。

**Comment by Alvin9999** [comment]
@jacknnnbauer 你用的哪个地区的服务器呢

**Comment by jacknnnbauer** [comment]
@Alvin9999 我用的是日本和新加坡的。
