### ISSUE TITLE
ipv6 pac 

### ISSUE THREAD

**Issue by yang330960** [Alvin9999/new-pac#427]
这几天ipv6 pac模式用不了了

**Comment by xiawuliangdianban** [comment]
是的，我的是昨天不能用的，最新版里边没有了pac,估计放弃了

**Comment by Alvin9999** [comment]
@yang330960 @xiawuliangdianban 刚才修复了下，再试试看pac-ipv6版呢？

**Comment by yang330960** [comment]
@Alvin9999 pac-ipv6版本还是不行

**Comment by Alvin9999** [comment]
@yang330960 被封锁了
