### ISSUE TITLE
開發者應該更新一下goagent的證書了

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#43]
chrome58.0.3030-dve以後版本提示不是安全鏈接，是證書問題。

**Comment by vkings1** [comment]
How to use  that? They have one in the mobile app.

**Comment by Alvin9999** [comment]
![qq 20170310220432](https://cloud.githubusercontent.com/assets/12132898/23798017/976560fe-05dd-11e7-9134-5f7886fac580.png)
奇怪呀，有效期是2026年呢。不排除是目前的高版本内核不适合GoAgent，可能需要一定的时间等待谷歌官方支持。或者你有什么解决办法吗？

**Comment by caofengzi** [comment]
xx也有這個情況，但是xx可以修改一個cert-util.py文件，把這行代碼的cert.add_extensions([OpenSSL.crypto.X509Extension(b'subjectAltName', True, ', '.join('DNS: %s' % x for x in sans))])
        cert.sign(key, CertUtil.ca_digest)“#“號註釋掉刪除ca.crt和證書文件夾重新生成就解決了58.0.3030.0以後版本不是安全鏈接的問題了，俺不明白代碼希望你能夠解決。

**Comment by Alvin9999** [comment]
你把Agent文件夹里面的CA.crt证书剪切或者删除，然后再重启GoAgent试试看

**Comment by caofengzi** [comment]
已經實驗過了還是不行，你可以看看xx-net的cert-util.py文件，這行代碼在252行。

**Comment by Alvin9999** [comment]
用Notepad++打开Agent文件夹里面的proxylib.py，在275行取消“cert.add_extensions。。。。”前面的# ，然后再删除CA.crt和certs文件夹，之后重启GoAgent
![222](https://cloud.githubusercontent.com/assets/12132898/23819603/42ad282e-0643-11e7-9222-73cc13801473.PNG)

**Comment by caofengzi** [comment]
由於俺不明白每個py文件的意思所以找了好久都沒有找到。謝謝

**Comment by Alvin9999** [comment]
原来如此，了解了

**Comment by theratlesnake** [comment]
@Alvin9999 我重新找回了几年前下载的goagnetV3.2.3，想复活，但是把在xx上传过的appid添加上去后，再添加xx导出的ip，发现打开google会报错405，有时是404，请问博主有办法解决吗?

**Comment by theratlesnake** [comment]
@Alvin9999 确实是ip的问题，已经解决了，非常感谢，另外请问一下，添加ciphers='DES-CBC3-SHA' 这个有什么用呢？好像添加了，速度会变慢。不过适合goagent的ip可能是会慢好多。

**Comment by Alvin9999** [comment]
修改后可以支持gws ip 和gvs ip，修改前只能支持gws ip

**Comment by Alvin9999** [comment]
如果你觉得速度变慢与修改配置有关，而自己又有足够的gws ip，那么你可以不用修改配置

**Comment by theratlesnake** [comment]
@Alvin9999 你好，我的原本是没有【ciphers】这个参数的，手动加上去后，发现使用GVS的ip也是上不了哦，gws的可以，但是太太太太慢了，而且gws的ip也很不多，请问是哪里的问题？

**Comment by Alvin9999** [comment]
@theratlesnake 你用搜索功能搜一下，可能是你的GoAgent的那个参数没有在1808和1810行

**Comment by theratlesnake** [comment]
@Alvin9999 你好，又有问题要请教你啦，我想问下，为什么我的goagent可以翻墙了，但是我发现youtube可以播放，但是显示不了评论，去twitter上试，发现显示推文，搜索之类的一切正常，但是回帖，发帖都不正常，提示我没有“没有赋予推文内容”，，请问下，你知道是哪里出问题了吗？在没升级Chrome为58之前，这个问题就存在了。而且用goagent登录github，也是回复不了帖子的，很奇怪的问题。

**Comment by Alvin9999** [comment]
@theratlesnake  goagent的问题，网上就有类似的问题，没法解决，至少目前是这样

**Comment by Alvin9999** [comment]
@theratlesnake  goagent的原开发者不维护它了

**Comment by theratlesnake** [comment]
@Alvin9999  恩，感謝解答！不過能用就已經很滿足了。謝謝你哈！
