### ISSUE TITLE
执行脚本安装BBR失败

### ISSUE THREAD

**Issue by SimonZYC** [Alvin9999/new-pac#438]
大家好，请问在安装BBR时是否遇到错误：
No package kernel-ml available
No package kernel-ml-devel available

**Comment by boiio** [comment]
我刚发这个问题妈耶，赶快去把我自己的给关了。

**Comment by ycshan** [comment]
遇到同样问题，无法加速，不晓得bbr加速还有没有用

**Comment by Alvin9999** [comment]
试试锐速加速脚本：
yum -y install wget
wget -N --no-check-certificate https://github.com/91yun/serverspeeder/raw/master/serverspeeder.sh && bash serverspeeder.sh

**Comment by Alvin9999** [comment]
我研究下什么问题，估计是vultr的centos系统更新了，导致系统内核对bbr不兼容，锐速应该可以的

**Comment by ycshan** [comment]
VPS用CentOS 7，尝试配置BBR后再配置SSR，也可以正常连接，速度也很快。

**Comment by Alvin9999** [comment]
@ycshan 谢谢反馈
