### ISSUE TITLE
谷歌BBR安装失败

### ISSUE THREAD

**Issue by boiio** [Alvin9999/new-pac#439]
之前一直可以用，这次上个ip被ban后重新建却安装不上了
错误信息如下：
No package kernel-ml available.
No package kernel-ml-devel available.
Error: Nothing to do
Error: Install latest kernel failed, please check it.
这意思是vultr的centos更新了还是bbr脚本更新了？

**Comment by Alvin9999** [comment]
我还没研究，估计是vultr的centos系统更新了，试试锐速加速：
yum -y install wget
wget -N --no-check-certificate https://github.com/91yun/serverspeeder/raw/master/serverspeeder.sh && bash serverspeeder.sh
