### ISSUE TITLE
咨询与求助！！

### ISSUE THREAD

**Issue by tomybluesky** [Alvin9999/new-pac#44]
Alvin9999墙友，無論在哪裡下載shadowsocks的任何版本，俺的安卓4.0.4三星i9100g均無法安裝，出現解析包出錯，不知道啥原因？！！請問有沒有替代shadowsocks的好用的類似工具呀,謝謝！

**Comment by caofengzi** [comment]
解析包錯誤是你的系統版本低，不支持shadowsocks了。

**Comment by Alvin9999** [comment]
@tomybluesky  网上搜了一下没有类似的安卓ss软件，所以爱莫能助。你可以按照楼上的方法试着更新一下系统版本。

**Comment by tomybluesky** [comment]
嗯，好的，待會兒去更新系統看看，謝謝你們的回复！！
