### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by zhangle0403** [Alvin9999/new-pac#445]
你好， 
目前使用高内核GoProxy ipv6版 （2018年9月8日升级浏览器版本至69），本人win10 64位OS，最近这几天频繁碰到错误 502 Bad Gateway
This Host header is not served from this network address. Due to an infrastructure change, this request cannot be processed.

请问如何解决，谢谢！

**Comment by AnyWAT** [comment]
😥与此同命 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448628695

**Comment by zhangle0403** [comment]
是的 我这边也是从昨晚22点开始 是不是国内防火墙又增加新设备了 哎。。

**Comment by Alvin9999** [comment]
可以暂时换用其它版本，这个问题有待观察

**Comment by AnyWAT** [comment]
WuJie （U模式）👍

**Comment by Alvin9999** [comment]
@AnyWAT 谢谢给大家提醒。除了无界以外，v2ray版和SSR版应该都可以使用的。

**Comment by AnyWAT** [comment]
v2ray版没试，My独立的SS/SSR也不行了😭

**Comment by FrankRx41** [comment]
我也是同樣的問題，能訪問google，能查gmail，但是除了google以外的網頁｢包括github，baidu｣都沒有辦法訪問

**Comment by Alvin9999** [comment]
@AnyWAT  GoAgent和GoProxy怎么修改才能使用呢？有没有建议？

**Comment by AnyWAT** [comment]
GoAgent 即 XX-Net ？
更新了 https://github.com/XX-net/XX-Net/releases/tag/3.13.1 但软件默认的总 IP数100貌似太小，300/500或许好些（貌似总共不到500了😂）
前者仍不太稳定，GoProxy 没试，或许导入 IP有救？https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138

**Comment by zhangle0403** [comment]
v2ray版今天试了可以的

@AnyWAT  WuJie （U模式）是啥意思？指的是GoProxy的一种模式么

**Comment by Alvin9999** [comment]
@AnyWAT  经过测试，GoAgent更新ip后，除了google无法使用外，其它大多数网站都可以打开。但GoProxy更新ip后还是无法使用，可能还需要修改某些文件。感谢你的建议哟。

**Comment by Alvin9999** [comment]
@zhangle0403  WuJie是我分享的另外一款软件。

**Comment by youstrong** [comment]
E1220 19:40:17.009561   18844 handler.go:96] 127.0.0.1:53237 Filter RoundTrip *gae.Filter error: http: invalid Read on closed Body
跟lz同样的问题，报上面的错误

**Comment by AnyWAT** [comment]
> 除了google无法使用外

貌似正常呢，https://github.com/Alvin9999/new-pac/issues/445#issuecomment-448964009 有增改

**Comment by AKB48kojima** [comment]
为什么用了xx net启用IPV6,Wu Jie就不能用 了啊？

**Comment by AnyWAT** [comment]
不会呀，或许是 xx net 启用了系统代理？

**Comment by zhangle0403** [comment]
v2ray版从今晚11点多开始也用不了了

**Comment by zhangle0403** [comment]
闹心了 下周软件的那个国外网盘也无法访问了

**Comment by AnyWAT** [comment]
3.13.1版XX-Net 貌似基本正常了😂

**Comment by Alvin9999** [comment]
@caofengzi 你知不知道GoProxy怎么修改配置呢？目前GoAgent换了最新的ipv6还可以凑合使用，但GoProxy无法使用，可能需要对某些文件进行修改才行。

**Comment by Alvin9999** [comment]
@zhangle0403 v2ray版已修复，可能是用的人太多负载太大造成的。

**Comment by caofengzi** [comment]
@Alvin9999 好像是需要在gae.user.json里面开启ip6才能用。

**Comment by AnyWAT** [comment]
> GoProxy无法使用，可能需要对某些文件进行修改才行。

貌似 @masktao 最近搞定了 https://github.com/XX-net/XX-Net/issues/11768

**Comment by caofengzi** [comment]
> > GoProxy无法使用，可能需要对某些文件进行修改才行。
> 
> 貌似 @masktao 最近搞定了 [XX-net/XX-Net#11759 (comment)](https://github.com/XX-net/XX-Net/issues/11759#issuecomment-448876768) [XX-net/XX-Net#11768](https://github.com/XX-net/XX-Net/issues/11768)

@masktao在gitter上面是说了，但是没有弄明白说的新旧ip是指什么，是ip4还是ip6。

**Comment by AnyWAT** [comment]
W1223 11:26:05.559067    1964 rootca.go:175] Verify RootCA("GoProxy") error: x509: certificate has expired or is not yet valid, try import to system root
E1223 11:26:05.583615    1964 rootca.go:177] Remove Old RootCA("GoProxy") error: Access is denied.
E1223 11:26:05.591620    1964 rootca.go:180] Import RootCA("GoProxy") error: Access is denied.
E1223 11:26:05.592620    1964 rootca.go:188] *storage.FileStore.Delete("cache/ecc") error: remove F:\GoProxy\cache\ecc: The directory is not empty.

**Comment by Alvin9999** [comment]
@AnyWAT 你把certs文件夹和CA.crt删掉，然后重新运行软件就会自动生成最新的证书了，你试试看呢

**Comment by AnyWAT** [comment]
GoProxy，删除目录 F:\GoProxy\cache\ecc，重新管理权限运行软件也无效

**Comment by Alvin9999** [comment]
@AnyWAT 还是提示证书问题吗？其它信息配置没有哦？比如开启ipv6，填写appid，放上ipv6 ip等

**Comment by AnyWAT** [comment]
在22时 DEAD Time 出现以前正常的 GoProxy，貌似证书可新生成，还可扫描出 good ip，但代理报错（与XX-Net 一样）：502 Bad Gateway
This HTTP request has a Host header that is not covered by the TLS certificate used. Due to an infrastructure change, this request cannot be processed.

**Comment by caofengzi** [comment]
如果运营商已经开通原生ip6还是干脆用“猫”直连或者买一个支持ip6的家用路由器。

**Comment by AnyWAT** [comment]
> 3.13.1版XX-Net 貌似基本正常了😂

试试：https://github.com/XX-net/XX-Net/issues/11892

**Comment by HEISEXIAOZHAI** [comment]
> 你好，
> 目前使用高内核GoProxy ipv6版（2018年9月8日升级浏览器版本至69），本人win10 64位操作系统，最近这几天频繁碰到错误502 Bad Gateway 
> 此主机标题不是由此提供的网络地址。由于基础架构更改，无法处理此请求。
> 
> 请问如何解决，谢谢！
更改DNS服务器地址为自动获得，可以访问YouTube，但是不能访问谷歌，想要访问谷歌就使用教程里的DNS服务器地址：在上面一行复制黏贴 2001:4860:4860::8888 下面一行复制黏贴 2001:4860:4860::8844 ，但是只能访问关于谷歌的地址，以前没有设置DNS服务器也能访问谷歌和Youtube，但是近端时间要设置DNS服务器才能访问谷歌网站，没搞懂是怎么回事

**Comment by AnyWAT** [comment]
> 
> 
> > 3.13.1版XX-Net 貌似基本正常了😂
> 
> 试试：[XX-net/XX-Net#11892](https://github.com/XX-net/XX-Net/issues/11892)

试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。

**Comment by AnyWAT** [comment]
Teredo 隧道：XX-net/XX-Net#12455 或
原生：XX-net/XX-Net#12477
