### ISSUE TITLE
GoAgent ipv6跟GoProxy ipv6都用不了！！！

### ISSUE THREAD

**Issue by GaranYeon** [Alvin9999/new-pac#446]
GoAgent ipv6跟GoProxy ipv6这两天为什么都不能用？
晚上更新到最新版本还是不行，要不就404，要不就502 Bad Gateway，
good_addrs=140
请问这个梗咋破？

**Comment by Alvin9999** [comment]
GoAgent ipv6更新一下ip看看，GoProxy ipv6还在研究中

**Comment by Alvin9999** [comment]
如果实在用不了，可以暂时换用其它类型的软件

**Comment by GaranYeon** [comment]
> 如果实在用不了，可以暂时换用其它类型的软件

ip更新都试过了，仍无解。
请问还有哪些可用？

**Comment by Alvin9999** [comment]
@GaranYeon 可以尝试v2ray版、SSR版，使用前按照说明更新一下ip。其它可以尝试的软件有无界版、skyzip版等

**Comment by GaranYeon** [comment]
好的，我试试其他的。感谢！
________________________________
发件人: 自由上网 <notifications@github.com>
发送时间: 2018年12月23日 1:40
收件人: Alvin9999/new-pac
抄送: GaranYeon; Mention
主题: Re: [Alvin9999/new-pac] GoAgent ipv6跟GoProxy ipv6都用不了！！！ (#446)


@GaranYeon<https://github.com/GaranYeon> 可以尝试v2ray版、SSR版，使用前按照说明更新一下ip。其它可以尝试的软件有无界版、skyzip版等

―

**Comment by YL-Li** [comment]
@Alvin9999 大佬，现在goproxy用什么部署appid，旧的不能用，以前在其他讨论区见过你头像

**Comment by AnyWAT** [comment]
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043
