### ISSUE TITLE
V2ray用不了了？

### ISSUE THREAD

**Issue by stella1314** [Alvin9999/new-pac#447]
如题

**Comment by Alvin9999** [comment]
已修复。

**Comment by stella1314** [comment]
感谢，感谢

**Comment by stella1314** [comment]
博主，好像本站提供的V2ray又用不起了

**Comment by CheneyHen** [comment]
v2r和ss之类好像最近都被算计了，没想到博主这还有新大陆，哈哈

**Comment by Alvin9999** [comment]
@stella1314 重启了下服务器，你再试试看呢。最近使用的人数很多，及时设置了自动重启都不行。

**Comment by huhufu** [comment]
> @stella1314 重启了下服务器，你再试试看呢。最近使用的人数很多，即使设置了自动重启都不行。

今天从上午开始，现在还是不行呢

**Comment by zhangle0403** [comment]
现在又不行了 是服务器负载过重 还是这条通路又被围堵了

**Comment by Alvin9999** [comment]
@huhufu @zhangle0403  已更换加密方式，运行下ip更新文件

**Comment by stella1314** [comment]
> @huhufu @zhangle0403 已更换加密方式，运行下ip更新文件

谢谢，刚刚试了下可以了
