### ISSUE TITLE
google调整的问题

### ISSUE THREAD

**Issue by asdfasdfko001** [Alvin9999/new-pac#448]
google调整的问题，与代理软件无关，看google以后还怎么调整了，毕竟gae服务已经给国人免费用十几年了，即使以后gae不能用了还是要感谢google，因为很多人都是从goagent开始知道有gfw的。

_Originally posted by @caofengzi in https://github.com/Alvin9999/new-pac/issues/446#issuecomment-449603826_

**Comment by Alvin9999** [comment]
google确实做出了贡献

**Comment by asdfasdfko001** [comment]
搜集完了中国用户数据，还是说下片太多。

**Comment by caofengzi** [comment]
有国会干预很难进入了。
