### ISSUE TITLE
亲，为啥都用不了了，什么都搭建好了就是用不了

### ISSUE THREAD

**Issue by Cg110778** [Alvin9999/new-pac#449]
如题

**Comment by xugaohui** [comment]
VPN Gate  PenguinProxy 都可以,不用搭建吧.

**Comment by Alvin9999** [comment]
你是自己搭建的ss/ssr账号吗？如果是，可以把协议和混淆设置成origin和plain

**Comment by IamZY** [comment]
应该可以吧

**Comment by WSCZou** [comment]
我也是每一步都是按照教程来且都成功了，但就是上不了。

**Comment by Alvin9999** [comment]
@WSCZou 账号信息是怎么配置的呢？比如端口、加密方式、协议和混淆

**Comment by WSCZou** [comment]
@Alvin9999 突然可以了，谢谢了

**Comment by osxn** [comment]
同样的问题，免费的ssr能用，于是协议、加密方式和混淆设置的和免费的一样，但自己搭建的就是用不了。服务器能Ping通。

**Comment by Alvin9999** [comment]
@osxn 请问你现在自己搭建的账号可以用吗
