### ISSUE TITLE
不能上nordstrom购物网站

### ISSUE THREAD

**Issue by allrainer** [Alvin9999/new-pac#45]
版主你好！你的软件Goagent和Goproxy很好用，只是http://shop.nordstrom.com/这个购物网站上不去，能否解决下，谢谢了！

Access Denied

You don't have permission to access "http://shop.nordstrom.com/" on this server.
Reference #18.1536d817.1489814806.1f3e5dc8

**Comment by Alvin9999** [comment]
请用全局代理打开。方法是：地址栏右侧有个圆形按钮，点击一下选择“全局代理”即可
![default](https://cloud.githubusercontent.com/assets/12132898/24071361/d4ece860-0c0a-11e7-9d22-011b16f94591.PNG)

**Comment by allrainer** [comment]
谢谢！
