### ISSUE TITLE
无界18.06    Chrome 69.0.3497.81  下载视频浏览器就卡死无法响应 

### ISSUE THREAD

**Issue by zlx9423** [Alvin9999/new-pac#452]
视频什么的都可以看  就是下载视频浏览器就卡死无法响应 怎么解决   求助大神们！！

**Comment by Alvin9999** [comment]
重启电脑，不要打开其它软件，只打开无界版，然后下载看看呢

**Comment by AnyWAT** [comment]
> 浏览器就卡死无法响应 

貌似卡在：代理扩展图标上有附加数字——未加载资源，等待手动添加。。。
无界版代理扩展情景模式除了无界（浏览器内全局）代理，有（可自添加任意切换规则的）无界自动切换？使用后者好过前者。。。貌似任何一种代理XX，均用（可自添加任意切换规则的）XX自动切换为佳

**Comment by zlx9423** [comment]
![360 16630501849581](https://user-images.githubusercontent.com/37044586/50841890-9c54a980-13a0-11e9-8feb-b32bdecc701b.png)
![360 1658111995137119](https://user-images.githubusercontent.com/37044586/50841895-9d85d680-13a0-11e9-8430-e760f478a05a.png)

**Comment by zlx9423** [comment]
代理我都没改过

**Comment by AnyWAT** [comment]
用浏览器代理扩展，无界不要使用默认的系统（全局）代理
![image](https://user-images.githubusercontent.com/37962734/50842490-c064ba80-13a1-11e9-9700-6b7e60d878a1.png)

**Comment by AnyWAT** [comment]
> 代理我都没改过

如果没有自动切换，得改——自己创建

**Comment by AnyWAT** [comment]
> Chrome 69.0.3497.81

https://shuax.com/portfolio/greenchrome/ 更新下。。。
即可随时手动更新  Chrome 71.0.3578.98

**Comment by Alvin9999** [comment]
@AnyWAT 计划等chrome72出来了一起更新一下浏览器

**Comment by Alvin9999** [comment]
@zlx9423  浏览器自带的YouTube插件可以下载哟，你是下载的某个网站的视频还是借助网站来下载YouTube视频呢

**Comment by AnyWAT** [comment]
> 计划等chrome72出来了一起更新一下浏览器

主要同时更新到：GreenChrome6.6.4  Chrome更新器v2.4.5.0

**Comment by zlx9423** [comment]
@AnyWAT   这个增强是放在这个目录下吗？
![360 16400224345938](https://user-images.githubusercontent.com/37044586/51188081-3031f280-1918-11e9-98b0-eff985ac7497.png)

**Comment by zlx9423** [comment]
@Alvin9999  借助网站来下载YouTube及其他网站视频、还有音乐什么的

**Comment by zlx9423** [comment]
@Alvin9999  情景也新设置了规则也更新了 还是一样    _(¦3」∠)_
![360 1659100988128104](https://user-images.githubusercontent.com/37044586/51189168-712b0680-191a-11e9-91e8-e8390c6396ab.png)
![360 16411202108117130](https://user-images.githubusercontent.com/37044586/51189169-712b0680-191a-11e9-9b21-36a6c371a7fa.png)

**Comment by AnyWAT** [comment]
免费 https://chrome.google.com/webstore/detail/idm-integration-extension/beobjkkhmebdklhjedacliojimbibppm 结合 WuJie 即可下载 YouTube

**Comment by AnyWAT** [comment]
> @AnyWAT 这个增强是放在这个目录下吗？

对的，不是已更新到最新版 71.0.3578.98？文件夹 69.0.3497.81 可删除了
