### ISSUE TITLE
ip被封

### ISSUE THREAD

**Issue by glancecopper** [Alvin9999/new-pac#453]
自建ssr用了半年多，从去年年底开始使用ip疯狂被封，我用的一般是洛杉矶和硅谷两个地方的。这30天以来换了3.4个地址。就在刚才上线又被封了，我开了6个地址最后才找到了个完好的。我想问下这正常吗。

**Comment by lbp0200** [comment]
不正常

**Comment by Alvin9999** [comment]
我分享的免费账号一直都是正常的。你说下你设置账号的端口、加密方式、协议和混淆呢，我帮你分析下。

**Comment by glancecopper** [comment]
chacha20-ietf  和 auth_sha1_v4 混淆plain

**Comment by glancecopper** [comment]
> 我分享的免费账号一直都是正常的。你说下你设置账号的端口、加密方式、协议和混淆呢，我帮你分析下。
chacha20-ietf 和auth_sha1_v4 混淆plain

**Comment by Alvin9999** [comment]
@glancecopper  加密方式改为AES-256-CFB，协议该为origin，然后再用一段时间

**Comment by glancecopper** [comment]
> @glancecopper 加密方式改为AES-256-CFB，协议该为origin，然后再用一段时间

好的，我再试一段时间

**Comment by TianTianUp1024** [comment]
ip被墙，ssh连不上可以ping通。
加密方式改为AES-256-CFB，协议该为origin。使用流量较大 100+G。

**Comment by pi408637535** [comment]
我用vultr买的洛杉矶的服务器。centos系统。2018年都正常，就是最近2019一到，这台服务器要不就是上午ssh连接不上去，要不就是下午ssh连接不上去。ssr当然也是这个样子，我想问这个样子是属于ip被封了，还是vultr服务不行

**Comment by TianTianUp1024** [comment]
> 我用vultr买的洛杉矶的服务器。centos系统。2018年都正常，就是最近2019一到，这台服务器要不就是上午ssh连接不上去，要不就是下午ssh连接不上去。ssr当然也是这个样子，我想问这个样子是属于ip被封了，还是vultr服务不行

遇到类似的情况，墙长高了求大腿抱

**Comment by pi408637535** [comment]
我再补充下，我最近拿朋友电脑去vultr申请主机，然后朋友机器能正常翻墙。但是只要我机器尝试去翻墙，我机器正常浏览5分钟左右，朋友买的机器就无法无法翻墙了。我尝试了三次，三个都是这种情况。我想问，这可能是什么原因造成。

**Comment by Willib** [comment]
> 我再补充下，我最近拿朋友电脑去vultr申请主机，然后朋友机器能正常翻墙。但是只要我机器尝试去翻墙，我机器正常浏览5分钟左右，朋友买的机器就无法无法翻墙了。我尝试了三次，三个都是这种情况。我想问，这可能是什么原因造成。

还有这操作额。。

**Comment by Alvin9999** [comment]
@pi408637535 可能是丢包导致的，你试试换其它地区看看，避开热门区域，热门区域包括日本东京、洛杉矶
