### ISSUE TITLE
无界浏览器怎么设置成自动代理，不需要代理的网站不走代理

### ISSUE THREAD

**Issue by 1343712786** [Alvin9999/new-pac#454]

**Comment by AnyWAT** [comment]
https://github.com/Alvin9999/new-pac/issues/452#issuecomment-452342966  从此往下。。。

**Comment by 1343712786** [comment]
@AnyWAT 具体怎么做？不懂啊

**Comment by AnyWAT** [comment]
已有无界代理或如下（名字不同而已，协议、端口相同即可）
![image](https://user-images.githubusercontent.com/37962734/51085658-756aee80-1777-11e9-97b2-ec0d06e8a26c.png)
左下角：新建情景模式——自动切换模式，如下（或用无界代理替换 WuJie）
规则列表网址：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
![image](https://user-images.githubusercontent.com/37962734/51085722-4f921980-1778-11e9-81ef-ff2930423d9a.png)

**Comment by AnyWAT** [comment]
> @AnyWAT 具体怎么做？不懂啊

其它有代理服务器的亦可如法炮制：貌似任何一种代理XX，均用（可自添加任意切换规则的）XX自动切换为佳
