### ISSUE TITLE
（自己按教程配置完的）ss/ssr的二维码链接粘贴到浏览器没有二维码了

### ISSUE THREAD

**Issue by TianTianUp1024** [Alvin9999/new-pac#455]
![image](https://user-images.githubusercontent.com/23043061/51133763-c90d3300-1870-11e9-9537-1fddaee9303c.png)

**Comment by TianTianUp1024** [comment]
![image](https://user-images.githubusercontent.com/23043061/51133748-be529e00-1870-11e9-93bb-8c4824a51f6f.png)

**Comment by Alvin9999** [comment]
二维码域名已失效。可以手动输入账号信息到客户端。
