### ISSUE TITLE
关于BBR加速

### ISSUE THREAD

**Issue by anzi2018** [Alvin9999/new-pac#456]
vultr BBR加速在日本服务器无法使用，但日本节点速度比较快，移动宽带都能达到1.4MB左右的下载速度，网络延迟在100左右，所以不用BBR加速速度也不错。美国洛杉矶移动宽带延迟都在200以上，可以使用BBR，下载速度在500KB左右

**Comment by anzi2018** [comment]
经测试要先安装BBR，再安装SSR，如果已经安装了SSR可以使用命令卸载后重新安装。速度确实提升不少，4K都不是问题。还是就是reboot重启命令后SSR无法使用

**Comment by Alvin9999** [comment]
谢谢反馈

**Comment by Alvin9999** [comment]
先安装bbr再安装ssr，重启后也不能用吗？

**Comment by anzi2018** [comment]
这个没试，因为已经弄好了，不想再折腾
