### ISSUE TITLE
ssr安卓版连上后检查网络连接提示“no address associated with hostname"

### ISSUE THREAD

**Issue by youstrong** [Alvin9999/new-pac#457]
手机是xiaomi5x，配置了一个pc上可用的服务器，在”配置文件“列表里测试延迟也正常，连接后也显示“ssr已激活vpn”，但点击“检查网络连接”后报错，提示：unable to resolve www.google.com，no address associated with hostname"。
有哪位大佬知道怎么弄吗，还请不吝赐教啊

**Comment by Alvin9999** [comment]
不点击检查网络连接，可否正常上外网？
