### ISSUE TITLE
mac连接vps一致报Operation timed out

### ISSUE THREAD

**Issue by KAKAROTS** [Alvin9999/new-pac#458]

**Comment by Alvin9999** [comment]
ip能ping通，如果ping不通就是ip被墙了，那么可以重新开一台新服务器

**Comment by KAKAROTS** [comment]
能够ping通，并且查看端口是开放的

**Comment by KAKAROTS** [comment]
我在终端输入ssh root@ip回车后就等待了一会，然后报operation time out

**Comment by Alvin9999** [comment]
噢，换个地区的vps试试看呢

**Comment by KAKAROTS** [comment]
试过了，没有用

发自我的 iPhone

**Comment by KAKAROTS** [comment]
ssh: connect to host ip port 22: Operation timed out 一直都是这个错

**Comment by anzi2018** [comment]
https://blog.csdn.net/zyzseven/article/details/81664149

看看这个是否可以解决

**Comment by DoublePg** [comment]
我的mac也是超时，半年前用mac连接很正常，现在换了很多地区的服务器，都显示超时。

**Comment by Alvin9999** [comment]
@DoublePg 是连接vps服务器都连不上吗

**Comment by Alvin9999** [comment]
@KAKAROTS 现在好了没有呢？如果不行，可以尝试用双系统或者windows虚拟机系统来搭建

**Comment by KAKAROTS** [comment]
没有好，试过好几个都这样，要不断开新vps的偶尔碰到好的才可以

**Comment by KAKAROTS** [comment]
没有好，要不断开新的vps去试才行，现在的vps都没有centos6了吗

发自我的 iPhone

**Comment by Alvin9999** [comment]
应该有的哦，选择系统的时候点一下有下拉选项
