### ISSUE TITLE
为什么日本和新加坡地区的服务器经常连接不上

### ISSUE THREAD

**Issue by KAKAROTS** [Alvin9999/new-pac#459]

**Comment by anzi2018** [comment]
别用reboot命令重启，某些地区CentOS Linux 7 系统reboot命令重启后SSR就失效了，还有就是加速器，同样某些地区安装完加速就失效，要先安装加速再装SSR。至于CentOS Linux 6会不会就不清楚了

**Comment by pi408637535** [comment]
ip被墙是什么现象？我这用了8个月在洛杉矶的服务器。最近就突然连接不上了首先服务器连接不上，就算晚上连接上了但是也不无正常翻墙

**Comment by WangZhonglei** [comment]
我买的洛杉矶的，听说日本的最快。博主分享的账号速度变慢了，您买的这个vps是不是也有流量限制啊？

**Comment by Alvin9999** [comment]
@WangZhonglei 我分享的免费账号用的人有点多，并且我限制了单线程速度，这是速度不快的主要原因。
