### ISSUE TITLE
pac1至pac5 好像都一样？

### ISSUE THREAD

**Issue by plus888** [Alvin9999/new-pac#46]
代理是一样的？

**Comment by Alvin9999** [comment]
可以这么说，PAC1～PAC5只是ip顺序不同。本来有想过删掉一些重复的，但是考虑到有人可能有人在用其中一个，就没有这么做了。另外一个原因就是穷，购买服务器是需要成本的。我尽量选价格低质量好的服务器。

**Comment by plus888** [comment]
谢谢

在 2017年3月21日 下午3:05，自由上网 <notifications@github.com>写道：

**Comment by caofengzi** [comment]
@Alvin9999 你做的已經很好了，有多少人能夠自己出資購買服務然後免費提供給其他人使用呢？看看那些做ss的，但是咱們也不否定那些收費做ss的人，這就是學佛人與普通人的區別。

**Comment by yangchandle** [comment]
非常感谢你做的付出

**Comment by Alvin9999** [comment]
@yangchandle  不客气
