### ISSUE TITLE
求大神帮忙 关于无法使用链接的问题

### ISSUE THREAD

**Issue by 743316391** [Alvin9999/new-pac#461]
您好， 4月份的时候通过您的教程 成功搭建，近期链接不是很稳定，想更换服务器，但是向原来搭建的方式一样操作，但是无法链接，更加无法使用，用手机端链接显示 
unable to resolve host“www.google.com” NO address associated with hostname。
也切换了协议 加密方式 端口 包括服务器 都是不行几乎是100%出现这个问题 具体问题怎么解决求大神指教。

**Comment by Alvin9999** [comment]
协议和混淆设置成origin和plain
