### ISSUE TITLE
vps能ping通，但是端口不通

### ISSUE THREAD

**Issue by YoungTakhin** [Alvin9999/new-pac#462]
系统是CentOS 7，刚搭建完SSR以后可以正常使用，但一两天以后就无法连接，测试了一下vps可以ping通，端口也确定是开的，但是从国内扫描vps端口全是关闭的，包括22端口，求大神告知为什么会出现这种情况？是端口被墙了吗？出现这种情况该怎么解决？

**Comment by YoungTakhin** [comment]
我用的端口号443，加密chacha20，协议auth_sha1_v4，混淆tls1.2_ticket_fastauth

**Comment by YoungTakhin** [comment]
这半年以来一直被这种情况困扰，每次出现这种情况我都只能换地址恢复快照，请问一下这正常吗？

**Comment by Alvin9999** [comment]
协议和混淆可以换成origin和plain。换了后如果还不行，再把端口和加密方式改变。最后还可以换centos6系统。

**Comment by YoungTakhin** [comment]
大神，还是不可以，我直接系统换成了CentOS6，协议和混淆换成了origin和plain，还是这种情况，求解

**Comment by lbp0200** [comment]
telnet ip 22，没反应，就是被封了，不管能不能ping通，防火墙现在升级了。

**Comment by YoungTakhin** [comment]
是的，就连22端口也封，那要怎么解决呢，封的太频繁了

**Comment by Alvin9999** [comment]
现在可以了吗

**Comment by YoungTakhin** [comment]
之前又封了几个，换IP以后也是第二天就用不成了，然后再换。最后换的这次用了几天，暂时还没出现问题

**Comment by Alvin9999** [comment]
你一般是用哪个地区的服务器呢

**Comment by YoungTakhin** [comment]
用的Vultr的服务器，位置不固定，但亚洲地区的服务器都是第二天被封；欧洲美洲多数是2、3天被封，但我之前换过一个英国的服务器用了几个月，这是最长的一次。另外欧美地区的服务器比亚洲速度慢一点。目前这次用的迈阿密的，到现在差不多一个星期了

**Comment by Alvin9999** [comment]
好的，谢谢反馈。一般来说，东京和洛杉矶的服务器由于用的人很多，造成像这种热门区域的服务器ip容易被屏蔽。

**Comment by YoungTakhin** [comment]
不用谢，大神，以后有问题还需请教您。另外，我的情况是不是IP被屏蔽，而是IP能ping，端口被屏蔽，半年以来都是如此。

**Comment by wukong0503** [comment]
> 不用谢，大神，以后有问题还需请教您。另外，我的情况是不是IP被屏蔽，而是IP能ping，端口被屏蔽，半年以来都是如此。

用的脚本一还是脚本二 大兄弟

**Comment by YoungTakhin** [comment]
脚本一

**Comment by Alvin9999** [comment]
@YoungTakhin 有网友反馈用5位数的端口解决了这个问题，你也可以试试看

**Comment by YoungTakhin** [comment]
好的多谢大神，再被封就试试五位端口
