### ISSUE TITLE
别的浏览器都可以 谷歌就error filed 尝试reset也不行

### ISSUE THREAD

**Issue by simcatSL** [Alvin9999/new-pac#463]
所有网页都提示 网址为XXX的可能暂时无法连接，或者它已永久性的移动到了新网址
ERR_FAILED  求教这是什么情况 重启几次才能好 很奇怪。。。netsh winsock reset也尝试过了不行

**Comment by simcatSL** [comment]
![Uploading a1962a87e950352a3368a3e55e43fbf2b3118bbc.jpg…]()

**Comment by Alvin9999** [comment]
图片看不了，不知道你遇到的是什么问题，你用的是ipv6版吗

**Comment by simcatSL** [comment]
用的是ipv6版，
![a1962a87e950352a3368a3e55e43fbf2b3118bbc](https://user-images.githubusercontent.com/20704815/53003263-90610a80-3469-11e9-9fa6-2e05e5d92082.jpg)

**Comment by simcatSL** [comment]
每次开机用浏览器都会出现 必须重启数次才可以打开网页  任何网页都显示这个

**Comment by simcatSL** [comment]
已经升级到最新版本了还是不行

**Comment by AnyWAT** [comment]
> 用的是ipv6版，

XX-Net 隧道优于原生，且隧道与原生只能二选一：用此禁彼

**Comment by Alvin9999** [comment]
建议换用v2ray版、SSR版、wujie版等
