### ISSUE TITLE
vps能连接，ping得通，昨天突然不能用了，关闭了防火墙没用

### ISSUE THREAD

**Issue by wqh0109663** [Alvin9999/new-pac#465]
如题

**Comment by wqh0109663** [comment]
centos6

**Comment by Alvin9999** [comment]
换下端口、加密方式、协议和混淆，然后再试试看呢

**Comment by wqh0109663** [comment]
我试过换端口 但是没什么用 其他的两种 因为我用的是兼容模式 就没换 最后无奈只能换了一台服务器

**Comment by wukong0503** [comment]
> 我试过换端口 但是没什么用 其他的两种 因为我用的是兼容模式 就没换 最后无奈只能换了一台服务器

换了哪里的服务器，我换了好几个咋都不行喃

**Comment by wqh0109663** [comment]
Londona啊 @wukong0503  而且以前的是5刀一个月的，最多就用到20G，现在这个换成了3.5刀的

**Comment by moxiaoyizui** [comment]
换成了5位数端口 origin+plain  好使了。 不知道是哪个生效了

**Comment by wqh0109663** [comment]
我就是你这种啊 突然不能用了 @moxiaoyizui

**Comment by FaceShawn** [comment]
> 换成了5位数端口 origin+plain 好使了。 不知道是哪个生效了

同换五位数端口解决了

**Comment by Alvin9999** [comment]
好的，谢谢大家反馈，这样给其他人也能作为参考
