### ISSUE TITLE
自建的VPN这2天突然不能用了，然后重装发现报错

### ISSUE THREAD

**Issue by hechuanhua** [Alvin9999/new-pac#466]
![4ba72dc1-9c9f-40fb-9299-4e9c48151adf](https://user-images.githubusercontent.com/8540940/52421936-03948380-2b30-11e9-9f47-65757c977e9e.png)

咋回事

**Comment by zihui745** [comment]
这两天我发现自建的SSR也用不了了，ip ping得通 22端口号可以扫描到，但就是翻不了，换了几个ip试了试发现也不行了，是不是墙又变高了

**Comment by Willib** [comment]
我的也是，这几天用不了了，新建的服务没有搭建ssr之前可以ping通，部署了之后再ping就ping不通了，囧…

**Comment by lbp0200** [comment]
代码没有了

**Comment by zihui745** [comment]
我解决了，卸载之后重新换个ss脚本就好了，我的步骤是这样的（前提是我的ip和端口没被墙）
1.输入bash ssr.sh 然后选3卸载脚本
2.输入
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev.sh
chmod +x shadowsocks-libev.sh
./shadowsocks-libev.sh 2>&1 | tee shadowsocks-libev.log
根据提示安装（输入密码，输入端口号，输入加密方式）
3.执行
etc/init.d/shadowsocks restart
重启一下服务确保开启

**Comment by Alvin9999** [comment]
先用脚本二来部署，脚本一的某个文件不在了导致下载失败，修复需要时间

**Comment by Alvin9999** [comment]
@Willib 是不是安装bbr加速后导致的，如果是可以先安装bbr加速，再安装ssr脚本

**Comment by Alvin9999** [comment]
把脚本一卸载了，重新安装即可，已修复

**Comment by Willib** [comment]
@Alvin9999 我觉得应该是今年以来墙更高了，这几天已经换了很多个ip了，用不了多久就被封，刚开始以为是ssr被特别关注了，然后换到了v2ray还是被封，最后换了个延迟高些的美国vps，目前用着虽然慢了些，但是暂时还没被封

**Comment by hechuanhua** [comment]
> 把脚本一卸载了，重新安装即可，已修复

卸载了用脚本一的还是安装不了，用脚本二没有脚本一方便，貌似每次所有的参数每次都要重新一个一个设置，而且不知道为什么就是用不了，我的是阿里云香港的服务器，不知道是不是被封了，我开其他的端口去测试能打开，就是SSR连接不上，搞不清是什么原因

**Comment by hechuanhua** [comment]
![qq 20190213152642](https://user-images.githubusercontent.com/8540940/52694214-e8000180-2fa3-11e9-9420-54e32a13ff4c.png)
这个是因为IP被封了吗？？？？导致拒绝连接？？

**Comment by zihui745** [comment]
@hechuanhua 脚本一是可以用的，我昨天才用谷歌云重新搭了个，用的就是脚本一

**Comment by hechuanhua** [comment]
> @hechuanhua 脚本一是可以用的，我昨天才用谷歌云重新搭了个，用的就是脚本一

我的不行，就是图片上面的报错

**Comment by hechuanhua** [comment]
我的问题解决了，没有用你这里的脚本，直接是  pip install shadowsocks，然后就可以了
