### ISSUE TITLE
IPv6部署失败，Network is unreachable

### ISSUE THREAD

**Issue by lvoicc** [Alvin9999/new-pac#467]
使用IPv6服务器安装会出现failed: Network is unreachable。IPv4一切正常，请问这是什么原因呀

**Comment by lvoicc** [comment]
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.204.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.204.133|:443... failed: Network is unreachable.

**Comment by Alvin9999** [comment]
你的电脑成功开启了ipv6才行，如果开启不了，那么无法使用ipv6 ip，只能使用ipv4 ip

**Comment by lvoicc** [comment]
您好，我电脑能Ping通vultr，反向也可以，只是一键部署程序无法连接，有没有IPv6的部署程序链接，或者有什么方法能载入呀？
