### ISSUE TITLE
ssr安装完成后，ssh就断掉

### ISSUE THREAD

**Issue by Shawnten49** [Alvin9999/new-pac#468]
ssh断掉后，就再也链接不上了。只有把系统还原后，ssh才可以连接上了。试过N次，都是这样的。
（当然，google等也一直登陆不了。。。）
CentOS 6 x64的系统

**Comment by Alvin9999** [comment]
是安装了bbr加速后才这样的吗

**Comment by Shawnten49** [comment]
没有，就只是安装了ssr就这样了。 单独安装bbr也是正常的。

**Comment by Shawnten49** [comment]
我在网上找了好多的安装ssr教程，基本上都是和你的类似的，一安装成功后，ssh就链接不上了。不过最后还是找到一个可用的版本（链接：http://www.lyz1234.com//site/vultrcn/246/info/2018/300.html），不知道和你这个有多大的区别。

**Comment by Alvin9999** [comment]
我看了，和我分享的脚本二几乎是一样的

**Comment by Shawnten49** [comment]
脚本二我也试过了一次的，当时也是一样的问题，就没有继续尝试了，主要就是用的脚本一。（等我搭建的再次不可用的时候，我去试一试吧）

**Comment by Xiongziwen** [comment]
我和你情况相同。后来我选协议origin，混淆插件plain，就OK了。
