### ISSUE TITLE
翻墙突然失效

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#470]
一直好好的，昨天开始突然不行了，更换了协议和和混淆也还是不行
北京联通  
硅谷节点 
origin
plain 
端口 8090
用的脚本一 + 锐速加速

新开的一个洛杉矶节点也不行

**Comment by V-zhangyunxiang** [comment]
Mac 和 Windows 都不行，Mac 是 SSX，Widnows 是 SSR

**Comment by Alvin9999** [comment]
试试更改一下端口呢，5位数的端口，或者用特殊端口，比如443、80等

**Comment by V-zhangyunxiang** [comment]
@Alvin9999 还是不行

**Comment by Alvin9999** [comment]
换一下服务器地区

**Comment by V-zhangyunxiang** [comment]
@Alvin9999 没管它今天早上又好了。。

**Comment by V-zhangyunxiang** [comment]
@Alvin9999 目前发现一个现象，白天正常，一到晚上就 GG 了

**Comment by Alvin9999** [comment]
如果是这样，那推测是不同时间段封锁强度不一样

**Comment by ghost2113** [comment]
我用的新加披的  也不能用了  昨天重新部署了一个日本 就连上了1分钟，就ping不通了  妈蛋

**Comment by V-zhangyunxiang** [comment]
同一个 SSR 账号，Windows 能翻墙，Mac 翻不了，是什么原因呢 @Alvin9999

**Comment by hiblacker** [comment]
同样的问题  换了很多服务器  偶尔能连上  但只能用一会就失效

**Comment by Alvin9999** [comment]
@V-zhangyunxiang @hiblacker 这个问题有的人会遇到，但有的人就没问题，目前不知道具体原因。可以尝试改变端口、协议、密码、服务器位置等来试试看

**Comment by V-zhangyunxiang** [comment]
发现只要设置 Sockets5  代理 连接 telegram 后，SSR就断了，是为什么呢

**Comment by Alvin9999** [comment]
@V-zhangyunxiang Telegram是网页版还是软件呢

**Comment by Norcy** [comment]
我换协议没有用，换个端口就正常了。仅供参考

**Comment by V-zhangyunxiang** [comment]
oneVPS 有考虑出一个教程吗 @Alvin9999

**Comment by Alvin9999** [comment]
@V-zhangyunxiang   如果是vps的话，搭建方法应该是一样的哦
