### ISSUE TITLE
刚搭的ssr手机能用电脑不能用

### ISSUE THREAD

**Issue by aishangkaoniangao** [Alvin9999/new-pac#471]
协议：auth_sha1_v4
混淆：plain

**Comment by Alvin9999** [comment]
试试更改一下端口呢，5位数的端口，或者用特殊端口，比如443、80等，协议可以换成origin

**Comment by SingleTigger** [comment]
> 试试更改一下端口呢，5位数的端口，或者用特殊端口，比如443、80等，协议可以换成origin

还是不行呢

**Comment by aishangkaoniangao** [comment]
> 试试更改一下端口呢，5位数的端口，或者用特殊端口，比如443、80等，协议可以换成origin

试过了不行。
家里的windows可以，mac不行和操作系统有关系？

**Comment by Alvin9999** [comment]
楼上两位把系统的防火墙或者杀毒软件关了再试试看呢

**Comment by QiWang-SJTU** [comment]
怎么解决呀？

**Comment by ghost2113** [comment]
昨天手机和电脑都可以翻过去，今天早上发现电脑SSTap连接成功，但是翻不过去了

**Comment by aishangkaoniangao** [comment]
> 楼上两位把系统的防火墙或者杀毒软件关了再试试看呢

防火墙是关了的，没有杀毒软件

**Comment by QiWang-SJTU** [comment]
> > 楼上两位把系统的防火墙或者杀毒软件关了再试试看呢
> 
> 防火墙是关了的，没有杀毒软件

今天早上突然可以了，啥都没动，真玄学
