### ISSUE TITLE
查下个人征信下载安装了人行的密码控件，结果ssr FQ不起作用了，求解？

### ISSUE THREAD

**Issue by renshaopeng** [Alvin9999/new-pac#472]
查下个人征信下载安装了人行的密码控件，开着ssr，弹窗提示检测到使用代理，将使用兼容模式，刷新网页即可，然后就见了鬼的用不了了，卸载了控件也没用啊

**Comment by Alvin9999** [comment]
应该是这个控件影响了。你看下浏览器代理设置对了没有？

**Comment by renshaopeng** [comment]
设置了的，不起作用

**Comment by renshaopeng** [comment]
> 应该是这个控件影响了。你看下浏览器代理设置对了没有？

并没有更换服务器，只是重新设置了ssr的配置，问题已解决，谢谢
