### ISSUE TITLE
亲，两个脚本好像都不能用了啊

### ISSUE THREAD

**Issue by Cg110778** [Alvin9999/new-pac#473]

**Comment by Alvin9999** [comment]
哪两个脚本呢？顺便可以把不能用的画面截图一下

**Comment by Cg110778** [comment]
咦我记得我用邮箱回复了啊，怎么没有啊，不好意思呀，就是在服务器上面建立ssr的那两个脚本，不过现在没事啦，我改用ss了，谢谢亲

**Comment by Cg110778** [comment]
> 哪两个脚本呢？顺便可以把不能用的画面截图一下

咦我记得我用邮箱回复了啊，怎么没有啊，不好意思呀，就是在服务器上面建立ssr的那两个脚本，不过现在没事啦，我改用ss了，谢谢亲

**Comment by Alvin9999** [comment]
OK
