### ISSUE TITLE
完全按照教程搭建  但是就是用不了SSR

### ISSUE THREAD

**Issue by majiajun1** [Alvin9999/new-pac#475]
如题  一旦打开SSR  网都上不了了

**Comment by majiajun1** [comment]
连接17  延迟一百多     但就是没有任何网速

**Comment by Alvin9999** [comment]
试试把端口设置为5位数，协议和混淆设置为origin和plain

**Comment by SingleTigger** [comment]
> 试试把端口设置为5位数，协议和混淆设置为origin和plain



> 试试把端口设置为5位数，协议和混淆设置为origin和plain

不行，手机是完全OK的，就是电脑不行

**Comment by CheganX** [comment]
> 如题 一旦打开SSR 网都上不了了

服务器的防火墙没关吧

**Comment by Alvin9999** [comment]
@SingleTigger
电脑把防火墙和杀毒软件关了再试试看

**Comment by majiajun1** [comment]
@Alvin9999   端口和协议都改过了  还是不行

**Comment by Alvin9999** [comment]
@majiajun1 试下特殊端口443、80等，如果还是不行，可以尝试其它地区的服务器。
