### ISSUE TITLE
vultr最近的服务器都ping不通啊

### ISSUE THREAD

**Issue by bumblebeehub** [Alvin9999/new-pac#476]
是我的问题吗？前两天是断断续续还偶尔能连上，今天试了日本，新加坡和西雅图的连ping都ping不通

**Comment by Alvin9999** [comment]
如果ping不通的话，就是ip被墙了。你需要开新服务器才行，多开几个，最好避开日本、洛杉矶、新加坡等热门地区，热门地区的服务器容易被墙。

**Comment by hockor** [comment]
哎，从日本到美国到悉尼，跨越3个大洲都没一个能连上的

**Comment by bumblebeehub** [comment]
> 哎，从日本到美国到悉尼，跨越3个大洲都没一个能连上的

我开了个法国的，除了时不时地断开，已经坚挺地工作好几天了

**Comment by zhangxixi0904** [comment]
我都ping都通，但是就是连不上，已经连续开了六七个，眼见着终于有一个连上去了，五分钟后竟然又连不上了。。。。

**Comment by hockor** [comment]
> 我都ping都通，但是就是连不上，已经连续开了六七个，眼见着终于有一个连上去了，五分钟后竟然又连不上了。。。。

我最后选了个悉尼的，延迟 250ms 左右，勉强能用。。
