### ISSUE TITLE
ssr的ping非常高

### ISSUE THREAD

**Issue by glancecopper** [Alvin9999/new-pac#477]

**Comment by glancecopper** [comment]
连接的加州vps ping再600+到了晚上基本1000+
我的dns如果自动获取根本翻不了墙，我改成谷歌的才行，有人知道问题出在哪里吗
aes-256-cfb  origin  plian

**Comment by Alvin9999** [comment]
ping一般与自己的带宽类型与服务器位置有关，建议换服务器位置。
