### ISSUE TITLE
你好，使用SSR断开后，断网

### ISSUE THREAD

**Issue by edcee99** [Alvin9999/new-pac#478]
你好，按照教程搭建后能使用，谢谢！但是遇到一个问题就是每次用完断开SSR之后路由器的WIFI就不能联网了，需要重启路由器才能正常使用。我在网上搜了一下说修改internet 选项里的局域网都取笑勾选，但是我基本上是手机用SSR跟电脑没关系，所以想求助解决方法 以前没自己搭服务器用那些免费VPN的时候用完断开不会出现这种问题

**Comment by Alvin9999** [comment]
是手机用ssr客户端后wife就断开了吗？

**Comment by edcee99** [comment]
> 是手机用SSR客户端后妻子就断开了吗？

是的不过已经解决了 我原本是按照教程用的auth_sha1_v4协议，后来换成origin就好了，还有一个问题就是3.5美元的服务器怎么没看到

**Comment by Alvin9999** [comment]
![default](https://user-images.githubusercontent.com/12132898/53294337-cf9faa80-381f-11e9-90e9-f8d730471145.PNG)

刚看了，vultr官网首页还有3.5美元的服务器介绍，但账号里面购买时没有了，不知道是会取消还是暂时断货。需要观察一段时间才知道。以前购买过的3.5美元服务器还能用。

**Comment by Alvin9999** [comment]
![1](https://user-images.githubusercontent.com/12132898/53373924-cfbfb780-3991-11e9-8f58-0e762ce7da52.PNG)
![2](https://user-images.githubusercontent.com/12132898/53373926-cfbfb780-3991-11e9-9c30-05af74f72bec.PNG)

美国亚特兰大有3.5美元的服务器可以选择

**Comment by edcee99** [comment]
不好意思我昨天没看到没有及时回复，刚刚我去看了还能买已经更换了，谢谢！
