### ISSUE TITLE
内核更新问题

### ISSUE THREAD

**Issue by kolidat** [Alvin9999/new-pac#48]
1. 用mychrome更新插件，不用作者提供的53版本离线升级包，用在线升级包更新到56或58，其他严格按照说明更新，更新后变成了普通的chrome，goagent等插件全部都不在了。是否不支持53以上的内核？
2. 另外，chrome的flash插件中只有PPAPI，播放音乐时会严重爆音，网上搜索的解决方法是换NPAPI，但此包里没有，下载gcswf32.dll后放入chrome.dll同级目录后，在chrome://plugins/里还是看不到，请问作者怎么解决？非常感谢

**Comment by caofengzi** [comment]
到這裡下載離線安裝包然後選擇離線更新就不會報錯了。http://chromium.woolyss.com/#latest-best-releases

**Comment by kolidat** [comment]
@caofengzi 下载哪个呢，那么多版本（sync,portable...,zip)和压缩包，·昨天下载几个都不行，还是更新了就变成普通的chrome了

**Comment by kolidat** [comment]
已测试，升级到53版本以后就不行了

**Comment by caofengzi** [comment]
@kolidat 點擊installer下載，不要選擇zip壓縮包。
