### ISSUE TITLE
怎么判断自己的服务器是否被封了

### ISSUE THREAD

**Issue by KAKAROTS** [Alvin9999/new-pac#481]
怎么判断自己的服务器是否被封了

**Comment by AnyWAT** [comment]
或许？https://github.com/shadowsocks/shadowsocks-windows/issues/2245#issuecomment-468513703

**Comment by KAKAROTS** [comment]
我查了端口以及ip都显示是开放的，但是用代理一直连不上

**Comment by Alvin9999** [comment]
是搭建的ss/ssr服务器吗？如果是，可以尝试换5位数的端口、协议和混淆推荐origin和plain。

**Comment by hwanpenn** [comment]
最新消息 wget: 无法解析主机地址 “raw.githubusercontent.com” 应该是被干掉了

**Comment by KAKAROTS** [comment]
换了端口和协议，确实有用
