### ISSUE TITLE
服务器能ping通但是ssr连不上

### ISSUE THREAD

**Issue by yizi-wang** [Alvin9999/new-pac#486]
最近好几个vultr服务都有这个问题，研究了一下发现是被tcp阻断了，不知道Alvin对KCPTUN有了解吗？

**Comment by Alvin9999** [comment]
没有研究过，你呢

**Comment by tylercross** [comment]
我的也是，vps配置好之后可以用，但是最近几天ssr连不上，PING的通，重新配置也无效，换其他电脑也连不上

**Comment by Alvin9999** [comment]
@tylercross 端口换5位数，协议和混淆设置成origin和plain看看呢

**Comment by Ghjsw** [comment]
> OK,解决了

怎么解决的?   我的端口五位数   协议跟混淆都换乘了origin和plain  也都没有效果

**Comment by tylercross** [comment]
我换了五位端口号就好了，协议跟混淆是orgin 和 plain。

发件人：D-sky <notifications@github.com>
发送日期：2019-03-14 09:35:34
收件人：Alvin9999/new-pac <new-pac@noreply.github.com>
抄送人：tylercross <fanwenjin@tju.edu.cn>,Mention <mention@noreply.github.com>
主题：Re: [Alvin9999/new-pac] 服务器能ping通但是ssr连不上 (#486)
OK,解决了
怎么解决的? 我的端口五位数 协议跟混淆都换乘了origin和plain 也都没有效果
