### ISSUE TITLE
最近很多vps都被墙了

### ISSUE THREAD

**Issue by KAKAROTS** [Alvin9999/new-pac#487]

**Comment by Alvin9999** [comment]
换下地区看看呢

**Comment by wyfSunflower** [comment]
@Alvin9999 你好 请问现在有适合ubuntu的教程么？我以前用的lantern能用比较慢，但是最近是彻底不能用了，任何时间都连不上，多谢啊

**Comment by xwtxwy** [comment]
我用的这个 http://yunsu.aicaibai.com/share.html?channel=kdl16
 可以的你试试吧

**Comment by wyfSunflower** [comment]
没有Linux版本的，我用的Ubuntu16.04

**Comment by Alvin9999** [comment]
@wyfSunflower 试试用ssr账号的方法，[地址](https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95)
