### ISSUE TITLE
不用搭建ss，安卓手机怎么翻？

### ISSUE THREAD

**Issue by kalelsun** [Alvin9999/new-pac#492]

**Comment by lbp0200** [comment]
https://choucuoqiong.blogspot.com/p/ssr.html

**Comment by xwtxwy** [comment]
这个啊http://yunsu.aicaibai.com/share.html?channel=kdl16 一键翻的 狠简单的

**Comment by AnyWAT** [comment]
https://apkpure.com/cn/search?q=%E6%97%A0%E7%95%8C%E6%89%8B%E6%9C%BA%E7%89%88 尚可
