### ISSUE TITLE
请问FDM的代理设置如何填写能够实现翻墙下载？

### ISSUE THREAD

**Issue by bajisama** [Alvin9999/new-pac#493]
Free Download Manager一个下载软件，貌似得填代理才能下墙外的东西，应该如何设置呢？

**Comment by AnyWAT** [comment]
得看所使用的代理是啥？如代理启用了系统全局代理，则默认的“系统代理”，不用再手工填写；否则手动设置，一般是：http 地址127.0.0.1 端口1080（视代理的端口，可能是其它）

**Comment by AnyWAT** [comment]
谢谢，从本贴知晓了貌似比 IDM、iDM 还爽的 FDM
![image](https://user-images.githubusercontent.com/37962734/54573785-a04c1a00-4a28-11e9-87d8-da21bfee8ddb.png)

**Comment by lantex** [comment]
我直接使用此作为代理，似乎并不立刻生效，包括暂停、取消后重新下载等。用proxifier引路是可以的，不太清楚怎么回事。
