### ISSUE TITLE
如何解锁netflix节点

### ISSUE THREAD

**Issue by jacknnnbauer** [Alvin9999/new-pac#494]
通过教程，已经翻墙。但是想看Netflix视频。
试用所谓解锁了Netflix的节点。但是没有一次成功看王飞视频。
所以想问如何解锁看Netflix视频？

**Comment by Alvin9999** [comment]
这个不太懂哦

**Comment by xwtxwy** [comment]
我用的这个还可以翻过去 http://yunsu.aicaibai.com/share.html?channel=kdl16可以试试
