### ISSUE TITLE
mac 链接不上了现在

### ISSUE THREAD

**Issue by diyxiaoshitou** [Alvin9999/new-pac#498]
2019年3月18的，mac 链接不上了现在，这么回事

**Comment by Alvin9999** [comment]
从服务器资源消耗看，账号没有问题。你是之前能用，突然不能用了吗？

**Comment by diyxiaoshitou** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    是的，之前一直能用，最近用不了了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2535477634
                            
                    
                        
                            
                                    2535477634@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年03月25日 15:46，自由上网<notifications@github.com> 写道： 


从服务器资源消耗看，账号没有问题。你是之前能用，突然不能用了吗？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Alvin9999** [comment]
今天会更新一下，到时候可以再试试看

**Comment by diyxiaoshitou** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2535477634
                            
                    
                        
                            
                                    2535477634@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年03月26日 09:25，自由上网<notifications@github.com> 写道： 


今天会更新一下，到时候可以再试试看



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AnyWAT** [comment]
😱楼主的贴怎么总是大片的空白？

**Comment by diyxiaoshitou** [comment]
我去，刚发现，用客户端发的，这么会出现这么多空白，不过现在vpn还是用不了

**Comment by Alvin9999** [comment]
已更新，可以试试看

**Comment by diyxiaoshitou** [comment]
![image](https://user-images.githubusercontent.com/17715122/55015615-23243480-5028-11e9-8680-665b954247b1.png)
还是不行，给这个版本有关系吗？

**Comment by diyxiaoshitou** [comment]
谢谢可以了，是版本的问题
