### ISSUE TITLE
LZ大大能提供ios的V2ray软件就好了

### ISSUE THREAD

**Issue by luck-cheng** [Alvin9999/new-pac#499]

**Comment by Alvin9999** [comment]
可以试试看 [v2ray ios客户端下载地址](https://itunes.apple.com/cn/app/kitsunebi/id1275446921?mt=8)

**Comment by luck-cheng** [comment]
> 可以试试看 [v2ray ios客户端下载地址](https://itunes.apple.com/cn/app/kitsunebi/id1275446921?mt=8)

这种方式就是需要国外的appleId对吧，头大

**Comment by cynen** [comment]
> > 可以试试看 [v2ray ios客户端下载地址](https://itunes.apple.com/cn/app/kitsunebi/id1275446921?mt=8)
> 
> 这种方式就是需要国外的appleId对吧，头大

其实并不需要国外appleID...
你在app store中,将自己账户的ID的国家调成美国或者其他国家即可...

**Comment by Alvin9999** [comment]
@cynen 更改国家的时候，还是需要填一些信息才行，相当于重新注册了

**Comment by Alvin9999** [comment]
@cynen 层主，棒棒哒！

**Comment by Alvin9999** [comment]
@cynen 最后一步是不是必须要完善信息才能下载？
