### ISSUE TITLE
goproxy版的作者更新了么？

### ISSUE THREAD

**Issue by blackross19945** [Alvin9999/new-pac#5]
goproxy版的作者更新了么？麻烦看一下，谢谢

**Comment by Alvin9999** [comment]
请问目前的能用不？是否有问题？

**Comment by blackross19945** [comment]
你发的几个版本都出现大量黄字，就这几天，更新ip也没用，不知道是不是就我自己这样

**Comment by Alvin9999** [comment]
我这里很好的,目前只有你反应这个问题.根据经验,国产杀毒软件会起干扰作用,比如360. 
我建议你把杀毒软件退了,再试试看

**Comment by blackross19945** [comment]
什么都没开还是那样，以前一直用的好好的，就这几天，我再想想办法吧，毕竟只有我这样，可能是我自己的原因，谢谢你的耐心回答。

**Comment by Alvin9999** [comment]
重新解压，把杀软和防火墙关了试试。不行的话，下载goproxy pac综合版，刚刚更新的。

**Comment by Alvin9999** [comment]
可以把黄色的字样的图截一下给我吗？我想知道是什么问题

**Comment by blackross19945** [comment]
今天重新下了个goproxy版的没问题了，可能是这几天我的网络波动之类的吧我也不是太懂
