### ISSUE TITLE
如果下次更新，是不是我本地更新一下iP就可以了？如果需要更新chrome版本，可以自己下吗？

### ISSUE THREAD

**Issue by Explore911** [Alvin9999/new-pac#50]
![image](https://cloud.githubusercontent.com/assets/26666077/24319854/6454373a-1163-11e7-95ac-1386d852886f.png)

我试过自己下安装包【59的】，失败了
遇到怎么样的更新才需要重新下载更新压缩文件？
本地的插件应用设置文件会被覆盖吗？

**Comment by Explore911** [comment]
开发者选择53版本是不是因为再升级会出现错误？

**Comment by caofengzi** [comment]
到這個網站下載離線安裝包，然後按照作者的說明首先啟動瀏覽器，然後在啟動my更新vbs，更新程序啟動以後選擇從離線安裝包更新，然後選擇已經下載的chrome離線包更新腳本就會自動提取更新文件，更新完成會彈出關閉瀏覽器點擊關閉，等到更新腳本提示更新完成關閉更新腳本然後重新啟動瀏覽器。
http://chromium.woolyss.com/#latest-best-releases

**Comment by Alvin9999** [comment]
@Explore911  
如果只是appid、ip的更新或者云端配置的更新，这些可以通过运行ip更新文件来解决；但是设计到一些具体的其它文件的修改或替换等，这些没法通过ip更新文件来解决，需要下载新版。

如果你升级内核失败，请降低内核版本，这个需要自己来测试了，53版本是我经过测试后觉得比较稳定的版本

**Comment by Explore911** [comment]
https://api.shuax.com/tools/getchrome


测试结果：Stable 稳定版 64位    版本：57.0.2987.110可用，暂时无其他异常
                   Canary 金丝雀 64位  版本：59.0.3051.3有异常，暂时无法正常使用 



@Alvin9999 如果涉及到具体文件的更新可以在升级的时候说明一下吗？【感谢】
Browser文件夹应该不会有改动吧

**Comment by Alvin9999** [comment]
@Explore911  通常更新时都会有说明；Browser文件夹一般不会有改动。

**Comment by caofengzi** [comment]
win32位離線更新金絲雀版沒有問題。

**Comment by shakesnake** [comment]
@Alvin9999 请问goagent-always-available那个里面的ip能不能覆盖这里的,那个好像更新频率更高?

**Comment by Alvin9999** [comment]
@shakesnake  goagent-always-available的gws ip文件只是单纯的ip，不含其它配置信息，没法直接用于GoAgent版，当然你可以自己手动复制来替换ip。

我更新的ip源于整合goagent-always-available的ip和自己搜集的众多ip段而搜到的ip，含有gws ip和gvs ip。
