### ISSUE TITLE
vultr上东京的服务器都被墙了吗？

### ISSUE THREAD

**Issue by tristrem** [Alvin9999/new-pac#500]
怎么换新服务器都没用，ip一直不变都ping不通。 其他地区的要么用不了，要么速度很慢。哎,,,

**Comment by Alvin9999** [comment]
东京属于热门地区，用的人很多，所以开到被墙的概率十分大。

**Comment by Alvin9999** [comment]
如果你有耐心，可以尝试开20个东京试试看。如果还是不行，那可以换其它地区的。
