### ISSUE TITLE
手机可以使用，电脑不能使用

### ISSUE THREAD

**Issue by jevinpi** [Alvin9999/new-pac#501]
4G能正常使用，电脑可以ping通，但是shell连不上，ssr也用不了，哪位大佬碰到过帮忙解答下？

**Comment by Alvin9999** [comment]
你在xshell里面新建这个服务器看看呢

**Comment by jevinpi** [comment]
> 你在xshell里面新建这个服务器看看呢

我用电脑连手机热点，xshell可以链接，连WiFi就不能，会存在ssr屏蔽ip的情况吗？

**Comment by Alvin9999** [comment]
如果是你自己的服务器应该就不会
