### ISSUE TITLE
写了一个批量创建账号的脚本，有兴趣的老哥可以用一下

### ISSUE THREAD

**Issue by YeYoot** [Alvin9999/new-pac#503]
写了一个批量创建账号的脚本，有兴趣的老哥可以用一下：
https://github.com/YeYoot/batch_create_account

**Comment by Alvin9999** [comment]
厉害

**Comment by Alvin9999** [comment]
请问除了v2ray、SSR等我分享的翻墙工具以外，楼主还知不知道其它的好用翻墙工具，我想增加一键翻墙工具，让大家有更多的翻墙选择。

**Comment by YeYoot** [comment]
> 请问除了v2ray、SSR等我分享的翻墙工具以外，楼主还知不知道其它的好用翻墙工具，我想增加一键翻墙工具，让大家有更多的翻墙选择。

支持你啊老哥，我是一直用的你的脚本...没怎么用过别的，坐等你的好消息~

**Comment by Alvin9999** [comment]
[自建Brook服务器教程 ](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by Alvin9999** [comment]
最近发布的，有兴趣的话可以尝试，根据反馈速度很不错

**Comment by YeYoot** [comment]
> [自建Brook服务器教程 ](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

老哥稳

**Comment by aitazhixin** [comment]
https://github.com/Alvin9999/new-pac/issues/503#issuecomment-483891154
brook服务器destroy后再新建，还需要重新部署脚本吗？

**Comment by Alvin9999** [comment]
@aitazhixin 需要的，服务器destroy后相当于信息被清空了，重新开服务器后就是全新的服务器，所以需要重新部署。

**Comment by aitazhixin** [comment]
https://github.com/Alvin9999/new-pac/issues/503#issuecomment-488878608
vultr可以实现自动部署吗？服务新建后，自动执行那个脚本。

**Comment by Alvin9999** [comment]
@aitazhixin  不行哟
