### ISSUE TITLE
chrome不能用google搜索

### ISSUE THREAD

**Issue by edisonchoi** [Alvin9999/new-pac#506]
经常会出现“隐私设置错误””您的连接不是私密连接“

1. 我用其它浏览器没有问题，所以应该不是服务器问题
2. 用百度去搜索google，点开进行搜索没有问题，但是直接在导航栏或右键直接搜索则会出现问题

错误详情：
NET::ERR_CERT_COMMON_NAME_INVALID 
Subject: baidu.com  
Issuer: GlobalSign Organization Validation CA - SHA256 - G2

能否帮忙看看呢？谢谢~

**Comment by Alvin9999** [comment]
用的什么翻墙方式呢？自建的服务器吗？

**Comment by edisonchoi** [comment]
对呀，就Vultr搭的CentOS 6系统，锐速加速
 加密 : aes-256-ctr
 协议: auth_aes128_sha1
 混淆: tls1.2_ticket_auth_compatible

我猜是不是混淆或者加密设置让chrome觉得不安全还是咋地，感谢解答

**Comment by Alvin9999** [comment]
可以设置为不混淆，即把混淆设置成plain，然后再试试看
