### ISSUE TITLE
影响代理的速度有哪些？

### ISSUE THREAD

**Issue by KAKAROTS** [Alvin9999/new-pac#507]

**Comment by Alvin9999** [comment]
宽带类型、所在地区被封锁强度、服务器位置、丢包率、翻墙方式

**Comment by KAKAROTS** [comment]
那可以通过什么手段提高ssr的速度吗 @Alvin9999

**Comment by Alvin9999** [comment]
比如换服务器位置、bbr/锐速加速等。最近发布了[自建brook服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) ，你也可以试试看的
