### ISSUE TITLE
请问怎么设置才能支持奈飞？

### ISSUE THREAD

**Issue by lhbzyz** [Alvin9999/new-pac#508]
在vultr上自架VPS服务器可登录奈飞，但一进入播放界面就会被奈飞提升不能使用代理。现在我转用nordvpn勉强可以登录和观看，就是nordvpn自带的混淆服务器非常不稳定，经常会被禁掉。请问有什么办法可以让我用现在vultr上自架VPS服务器正常使用奈飞？

**Comment by Alvin9999** [comment]
搭建的ss/ssr、v2ray还是brook？

**Comment by lhbzyz** [comment]
SSR

> 搭建的SS / SSR，v2ray还是小溪？

SSR
