### ISSUE TITLE
小火箭使用节点连不上

### ISSUE THREAD

**Issue by accfcx** [Alvin9999/new-pac#509]
目前有3个人说小火箭不能用，节点没问题。不知道这是怎么回事，求解

**Comment by Alvin9999** [comment]
如果确定不是账号的问题，那么可能是小火箭的问题，可以尝试换其它客户端软件。

**Comment by jen-yenpin** [comment]
小火箭确实用不了, 以前没有这种问题

**Comment by tomybluesky** [comment]
不是小火箭的问题，用其他的账号可以，应该是这两个账号的问题吧@Alvin9999

**Comment by RPCheung** [comment]
节点在其他客户端可用 但小火箭就是用不了

**Comment by Alvin9999** [comment]
@RPCheung 那就是软件的原因喽
