### ISSUE TITLE
作者能夠升級goa的aes嗎？

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#51]
作者能否把goagent的AES-CBC-SHA 升级到 AES-CBC-SHA256嗎？

**Comment by Alvin9999** [comment]
这个是干什么用的？

**Comment by caofengzi** [comment]
這是ssl加密算法吧，俺在goproxy討論區看到有人提的goagent的ssl問題，社長說得升級aes-cbc-sha256但是社長說他不在維護goa了，所以就到這裡問問你能否升級這個。

**Comment by Alvin9999** [comment]
没有找到goa的AES-CBC-SHA，所以没法弄哦
