### ISSUE TITLE
突然间电脑无法翻墙了

### ISSUE THREAD

**Issue by Ellen9616** [Alvin9999/new-pac#511]
手机试了一下可以打得开google，mac safari和chrome都无法打开，在五分钟前还是能翻墙上google schoolar和推的……

**Comment by Alvin9999** [comment]
是自建的服务器还是用的免费账号呢？

**Comment by Ellen9616** [comment]
自建的

**Comment by Alvin9999** [comment]
端口换成5位数，协议和混淆设置成origin和plain，然后再试试看。

**Comment by Ellen9616** [comment]
已经是五位数端口和origin+plain混淆了，断断续续能用一会又间歇性不能上一会😂这种是什么情况啊

**Comment by Alvin9999** [comment]
你用的哪个地区的服务器呢

**Comment by Ellen9616** [comment]
美国新泽西的

**Comment by Alvin9999** [comment]
可以考虑换其它的试试看

**Comment by YiFengTang94** [comment]
我也是一样的情况，cent6 SSR 锐速加速，换了五位数端口和加密协议混淆协议还是不行。地区尝试了新加坡和美国纽约的

> 可以考虑换其它的试试看

**Comment by Alvin9999** [comment]
@YiFengTang94  可以考虑再换下其它非热门地区。如果还是不行的话，也可以尝试部署v2ray或brook。
