### ISSUE TITLE
大佬可不可以出付费服务啊？

### ISSUE THREAD

**Issue by huanghy0424** [Alvin9999/new-pac#512]
相信还是有很多人愿意承担一定的费用的，这样也可以帮助大佬提高服务质量啊。

**Comment by luvvien** [comment]
你可以自己搭一个啊，很简单的，有那种一键安装脚本，熟练了几十秒就能搭一个。[小白一键搭建ss服务](https://vien.tech/article/122)

**Comment by jacknnnbauer** [comment]
我搭建过，后来找人合租。不同地区的网速都不一样。有的人试一下就可以连接，有的人试了就很慢。所以。。。

**Comment by Alvin9999** [comment]
谢谢楼主的建议和关心。应该不会做付费服务的，因为当初做这个项目的初衷就是提供永久免费的翻墙软件和免费ss/ssr账号，给大家提供一个了解墙外世界的机会，这个初心会一直坚持下去的。至于速度这块，随着使用人数越来越多的时候，带宽资源分配下来每个人不会多，尤其是晚上，那么速度就不快了。鉴于这种情况，近期在考虑使用独立服务器，这样带宽更大，负载能力也会增强。对速度要求比较高的朋友，建议自己根据教程来搭建服务器，一是可以学习一门技能，二是速度这块因为是一个人使用，那么肯定会更快的。
