### ISSUE TITLE
服务器被封

### ISSUE THREAD

**Issue by hibluesea** [Alvin9999/new-pac#514]
自建的服务器最近发现容易被封，感觉墙加高了，求助
配置是参考免费账号设置的，表现为刚连接上就开始丢包，一会就ping不通了。
但如果不连接几分钟后又可以ping通了。有时候更换端口可以使用一段时间，但IP或者端口还是容易被封，是不是ss的流量被精准识别了？但使用楼主提供的免费账号一直正常，使用自建的很容易被封(服务器为日本)，另外感觉电信网比移动网更容易封，又没朋友遇到类似情况？是不是应该考虑换项目中其他技术方案？比如V2ray 或者 Brook

**Comment by Alvin9999** [comment]
日本服务器属于热门地区，ip段使用人数多，很容易整个ip段被封，单个ip也是这样。你可以换其它地区的vps再来尝试ss/ssr，当然你也可以换brook或v2ray，尝试一下总是好的。

**Comment by hibluesea** [comment]
可能和我使用的网络环境有关，好在被封只是暂时的，不影响其他网络下使用。看来封禁策略是玄学
