### ISSUE TITLE
ubuntu18.04

### ISSUE THREAD

**Issue by onceone** [Alvin9999/new-pac#515]
你好，下载了.tar.gz文件，但是里面没有configure问价呀，请问如何安装啊，谢谢了

**Comment by Alvin9999** [comment]
你好，你说的是什么呢

**Comment by onceone** [comment]
下载了ubuntu对应的文件，是tar.gz格式的。百度了如何安装，先解压，再进入解压后的目录，在中终端中，运行./configure，但是不行呀（小白一个，谢谢了）

**Comment by Alvin9999** [comment]
是哪一篇教程呢

**Comment by onceone** [comment]
百度经验《ubuntu18.04如何安装tar.gz》

**Comment by Alvin9999** [comment]
这个不行的话，可以用google搜下其它的方法，我对ubuntu系统不是很了解哦

**Comment by onceone** [comment]
嗯嗯，好的。谢谢了。
