### ISSUE TITLE
学自建brook服务器教程，失败

### ISSUE THREAD

**Issue by TianTianUp1024** [Alvin9999/new-pac#517]
谷歌BBR加速后重启服务器 连接不上 试了4台机器刚好都不行
换了锐速后重启服务器 可以连接回服务器
但是跟着教程，版本号 同步时间 防火墙也关了，改完了还是不能翻墙
导入分享连接 -> 保存配置 -> 启动。
打开 YouTube 试了无反应。
有基友成功的吗 ~

**Comment by TianTianUp1024** [comment]
。。。没试过全局模式，刚才点了一下就可以了。

**Comment by TianTianUp1024** [comment]
感谢开源

**Comment by Alvin9999** [comment]
PAC确实失效了的

**Comment by smilelight** [comment]
> PAC确实失效了的

@Alvin9999 2020.4.7了，Windows好像还是提示PAC错误吧？

**Comment by smilelight** [comment]
提示如下错误：![UTOOLS1586271815814.png](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/UTOOLS1586271815814.png)

**Comment by Alvin9999** [comment]
@smilelight 是的
