### ISSUE TITLE
我在Vultr上使用的新加坡5$速度很慢

### ISSUE THREAD

**Issue by MengWuZiChan** [Alvin9999/new-pac#518]
我的服务器在使用时速度很慢，想请问有没有什么解决方案，听说PAC可以改善网速，但我没有找到这种网址。
求教。

**Comment by MengWuZiChan** [comment]
我在iphone上使用ShaWingy和ScanWingy时节点显示超时，这又是什么原因呢？

**Comment by Alvin9999** [comment]
可以试试其它地区的vps，因为速度与很多因素有关，比如你家的带宽类型、服务器位置等

**Comment by Alvin9999** [comment]
PAC只是一个方便有的网址走代理，有的网址不走代理，实际上不会改善网速。

**Comment by greediness** [comment]
洛杉矶的还挺快的，你可以试试

**Comment by AnyWAT** [comment]
适用代理端口1080 的
1、白名单（推荐使用可自添加切换规则的 auto white 情景模式而不是 whitepac）https://github.com/MatcherAny/whitelist.pac
2、黑名单 A、https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac
B、https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac
