### ISSUE TITLE
ubuntu19.04安装deb客户端输入账号不能翻墙

### ISSUE THREAD

**Issue by zxh451200** [Alvin9999/new-pac#519]

**Comment by Alvin9999** [comment]
用的免费ss账号还是自己搭建的呢？

**Comment by zxh451200** [comment]
免费啊  window都可以 翻墙了 就是虚拟机中的ubuntu不行   是不是还要再ubuntu设置里把代理设置成自动嗯  谢谢

**Comment by Alvin9999** [comment]
我对ubuntu没怎么研究过，你可以参考下这个[Linux系统翻墙方法](https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95)
