### ISSUE TITLE
求教我用的官方最后一版goagent-3.0不能上尤土碧的问题

### ISSUE THREAD

**Issue by ximenlangzige** [Alvin9999/new-pac#52]
首先感谢作者不辞辛苦为我们提供这样一个方便快捷的出墙软件，本人一直也有使用！我用的是XP系统， 之前有一个自己使用自己的APPID的阿根廷 有一天更新系统补丁后不能使用了，出现了goagent系统缓冲区空间不足或队列已满的提示，自己没法解决后来还原系统好了！ 不知怎么后来其它的网站都可以打开 仅仅尤土碧打开是完全的乱码！取消油猴脚本与关于尤土碧的所有扩展问题依旧！于是我去看看一下https://console.cloud.google.com这里 胡乱捣鼓了一下还是没用，也不记得是因为我捣鼓了才出现的乱码还是出现乱码打不开尤土碧才捣鼓的了！现在就是上不了尤土碧！我把作者你的两个配置文件proxy.ini和proxy.user.ini是能够正常的！换句话说就是用作者你的阿根廷是可以正常打开的，就用我自己的APPID就是这种情况！所以请教一下有什么办法能够解决！ 谢谢！

**Comment by caofengzi** [comment]
可以使用排除法，就是每次在proxy.user.ini裡面添加1個你自己的appid然後訪問youtude。

**Comment by ximenlangzige** [comment]
昨天测试了一下XX-NET 用自己的APPID配置后是可以上尤土碧的！是不是可以判定为APPID的网页设置没问题？只是现在用阿根廷3.23版无法上传服务，之前我都是用GOOTEST 自己搜IP,然后排除掉非GA的IP直接右键选定应用就可以自动写入一个proxy.user.ini直接能用！里面就单纯的两组IP! 虽然很多好的IP依然尤土碧乱码！不过按照你的方法我对我的proxy.user.ini的内容作了修改添加了APPID段跟按照作者的】proxy.user.ini[profile]添加了里面的内容现在可以上尤土碧了！ 我现在很纳闷为什么以前就不用写这么多东西在proxy.user.ini里面！有过我么猜错的话是我后来把原先的proxy.ini换为官网那版单单添加APPID不行？有点蒙圈!大神给普及一下吧！

**Comment by ximenlangzige** [comment]
`这是正式版proxy.ini带的那段[profile]
dl-ssl.google.com = withgae
dl.google.com = withgae
play.google.com = withgae
wenda.google.com.hk = withgae
clients.google.com = withgae,noforcehttps
.clients.google.com = withgae,noforcehttps
clients1.google.com = withgae,noforcehttps
translate.google.com = withgae,noforcehttps
mtalk.google.com = direct
talk.google.com = google_talk
talk.l.google.com = google_talk
talkx.l.google.com = google_talk
.google.cn = google_cn
.appspot.com = google_hk,crlf
.google.com = google_hk,forcehttps,fakehttps
.google.com.hk = google_hk,forcehttps,fakehttps
.commondatastorage.googleapis.com = withgae
.googleapis.com = google_hk,forcehttps,fakehttps
.googleusercontent.com = google_hk,forcehttps,fakehttps
.googletagservices.com = google_hk,forcehttps,fakehttps
.googletagmanager.com = google_hk,forcehttps,fakehttps
.google-analytics.com = google_cn,forcehttps,fakehttps
.gstatic.com = google_hk,forcehttps,fakehttps
.ggpht.com = google_hk,forcehttps,fakehttps
.googlegroups.com = google_hk,forcehttps,fakehttps
.googlecode.com = google_hk,forcehttps,fakehttps
.youtube.com = forcehttps,fakehttps
.android.com = google_hk
tools.android.com = withgae
www.dropbox.com = withgae
.dropbox.com:443 = direct
.box.com:443 = direct
.copy.com:443 = direct
https?://www\.google\.com/(?:imgres|url)\?.*url=([^&]+) = $1
https?://www\.google\.com\.hk/(?:imgres|url)\?.*url=([^&]+) = $1
https?://www\.google\.com\.hk/search\?(.+) = https://www.google.com/ncr#$1
; https?://www\.example\.com/.+\.html = file:///C:/README.txt
; https?://www\.google\.com(\.[a-z]{2})?/($|(search|url|gen_204)\?|(complete|images)/) = google_cn
; https?://www\.youtube\.com/watch = google_hk
; .c.youtube.com =
; .youtube.com = google_hk
; .googlevideo.com =`
我把作者这版的proxy.user.ini的这段替换到proxy.ini里面是不是就可以不用在proxy.user.ini里写了！

**Comment by Alvin9999** [comment]
@ximenlangzige  可以试试看哦。推测是youtube没有走直连造成的。这个“.youtube.com = google_hk ”很重要。

**Comment by ximenlangzige** [comment]
@Alvin9999是可以了谢谢！ 我替换你的这段可以上了！就是前面说的那些比如上传什么的都不用了吗？这个原版自带的这段有什么问题吗？
