### ISSUE TITLE
赠送的50美元有效期一个月

### ISSUE THREAD

**Issue by zanwen** [Alvin9999/new-pac#521]
这是个大坑啊，不知道我当时看教程的时候是不是楼主没提到这一点，但我现在才发现，如果你只是用来搭建一个小型的SSR，那赠送的50美元基本上打水漂了

**Comment by Alvin9999** [comment]
嗯嗯，是的，不好意思，当时没有提到这一点，后来才在教程里面提到了vultr赠送的50美元有效期1个月这点。

**Comment by Alvin9999** [comment]
确实很可惜

**Comment by cynen** [comment]
那这个50美金,能用来干嘛啊

**Comment by Alvin9999** [comment]
@cynen 免费用一个月，可以开更高套餐的服务器。

**Comment by aitazhixin** [comment]
怎么申请服务才有这50呢？

**Comment by Alvin9999** [comment]
@aitazhixin 必须是新的账号才行，老账号不行，全新的邮箱、全新的支付账号

**Comment by aitazhixin** [comment]
https://github.com/Alvin9999/new-pac/issues/521#issuecomment-488878725
绝对全新，好像在blling里看到有50了，这个建brook服务可用吗？

**Comment by Alvin9999** [comment]
@aitazhixin 可以用的

**Comment by cynen** [comment]
> @cynen 免费用一个月，可以开更高套餐的服务器。

我感觉作用不大,但是不知道能不能卡到月底,再开一个

**Comment by Alvin9999** [comment]
@cynen 嗯。虽然作用不大，但能省点费用也不错。
