### ISSUE TITLE
安装 SSR 时提供的备用脚本，怎么去修改端口，密码等等呀

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#522]

**Comment by V-zhangyunxiang** [comment]
bash ssr.sh 没用呀

**Comment by Alvin9999** [comment]
备用脚本如果要修改端口，只能重新复制整个代码再安装一遍，备用脚本没有第一个脚本方便。如果嫌麻烦，可以把备用脚本卸载了，然后安装第一个脚本。

**Comment by cynen** [comment]
ssh ./ssr.sh

**Comment by V-zhangyunxiang** [comment]
> ssh ./ssr.sh

你这个没有用

**Comment by cynen** [comment]
bash 开头，打错了


 
---原始邮件---
发件人: "YunXiang Zhang"<notifications@github.com>
发送时间: 2019年5月2日(星期四) 下午2:02
收件人: "Alvin9999/new-pac"<new-pac@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"cynen"<cynen@foxmail.com>;
主题: Re: [Alvin9999/new-pac] 安装 SSR 时提供的备用脚本，怎么去修改端口，密码等等呀 (#522)


 
ssh ./ssr.sh
  
你这个没有用

**Comment by V-zhangyunxiang** [comment]
> bash 开头，打错了
bash 开头的第一个脚本有效，备用脚本没有效果

**Comment by Alvin9999** [comment]
@V-zhangyunxiang 是的
