### ISSUE TITLE
用的ssr 最近又翻不出去了····

### ISSUE THREAD

**Issue by glancecopper** [Alvin9999/new-pac#523]
没有该任何设置，上谷歌就突然显示"客户端和服务器不支持一般 SSL 协议版本或加密套件“
用edge上谷歌也是"因为该站点使用过期的或不安全的 TLS 安全设置"     
 不知道为什么，我的ip并没有被封，origin+plain的问题吗，真是有点无解。 tsl 1.0到 1.2的设置都在啊，有谁遇到过这个情况，国内网址没这问题。

**Comment by Alvin9999** [comment]
除了google以为的其它网站有问题没？比如youtube？

**Comment by glancecopper** [comment]
> 除了google以为的其它网站有问题没？比如youtube？

不止YouTube，twitch之类也这样，前一天晚上还能上，一起来就这样了我也是一脸懵逼·····

**Comment by Alvin9999** [comment]
换下端口试试

**Comment by WangZhonglei** [comment]
俩都不能用，谷歌上不去

**Comment by Alvin9999** [comment]
@WangZhonglei 免费的2个账号没有问题。

**Comment by WangZhonglei** [comment]
嗯

**Comment by Alvin9999** [comment]
@WangZhonglei 你的意思是自己搭建的2个都不能用吗?如果是可以试试换下5位数端口，协议和混淆设置为origin和plain，如果还不行，可以考虑换服务器位置。

**Comment by WangZhonglei** [comment]
@Alvin9999 没有，偶尔看看新闻，需求不大，用的分享的账号，下午那个密码忘改了，没连上

**Comment by gbbh** [comment]
我现在自建的和试用账号都不能翻，连ssr那个测试都不能通过，前两天开始的，现在一直这样

**Comment by Alvin9999** [comment]
更新了免费ss账号和ssr版配置信息，可以试试看
