### ISSUE TITLE
5.1期间免费共享一个vpn

### ISSUE THREAD

**Issue by cynen** [Alvin9999/new-pac#524]
共享自己搭建的SSR 服务器. 由于开启BBR加速后,实际效果不理想,所以没有进行加速. 
只有一个简单的 SSR

IP: 207.148.72.205 
端口: 8388
密码:654321
加密:  aes-256-cfb

5.1-5.4号共享,以后会关闭.

**Comment by Alvin9999** [comment]
谢谢楼主分享。时间到了，我就关闭这个了哦。
