### ISSUE TITLE
哈哈好简单

### ISSUE THREAD

**Issue by lufengleo** [Alvin9999/new-pac#525]
感谢教程，一遍成功，后面在试着设置限速限流

**Comment by Alvin9999** [comment]
恭喜哦

**Comment by lufengleo** [comment]
可不可以写一篇怎么部署多端口、限流量、限设备数和限速的详细文章

**Comment by Alvin9999** [comment]
常见问题里面有一条，可以尝试下

**Comment by YeYoot** [comment]
> 可不可以写一篇怎么部署多端口、限流量、限设备数和限速的详细文章

https://github.com/YeYoot/batch_create_account
批量创建账号的脚本你可能用的着哦
