### ISSUE TITLE
iPhone使用Shadowsocks翻墙（无需美区AppleID）

### ISSUE THREAD

**Issue by gfw-breaker** [Alvin9999/new-pac#526]
刚才写了 [iPhone使用Shadowsocks翻墙](https://github.com/gfw-breaker/guides/wiki/iPhone%E4%BD%BF%E7%94%A8Shadowsocks%E7%BF%BB%E5%A2%99)，适用于没有美区AppleID的网友，可以作为你的教程的补充，望采纳。

**Comment by Alvin9999** [comment]
我看了这个只适合没有协议和混淆的账号，但如果是ssr账号就没法用了。有没有ssr客户端的文件？如果有就最好了。

**Comment by gfw-breaker** [comment]
支持 SSR的，点击混淆选项有另一个页面填这些信息。

**Comment by Alvin9999** [comment]
嗯，看到了，有混淆但没有协议。稍后会把这个加在教程里面。
