### ISSUE TITLE
请问brook和ssr可以同时部署吗会冲突吗以及tracert问题

### ISSUE THREAD

**Issue by admiral-graf-spee** [Alvin9999/new-pac#527]
十分感谢版主的分享，您正在做的事给了我很大帮助，也一定会帮助到更多的人。您的工作是有价值的。
如题，请问brook和ssr在服务器可以同时部署吗，会冲突吗
我自己在vultr建的日本vps貌似访问其他网站都ok，但是不知为什么上不了p站？
另外想问下这个问题版主有什么看法：我用**另一个**加密代理软件的代理ip地址无论怎么查都是乌克兰，但是我总怀疑它在用日本的服务器。果然，我用tracert命令有以下结果：
`1     *        *        *     请求超时。
  2     *        *        *     请求超时。
  3     9 ms     8 ms     9 ms  LAPTOP-4412C9V4 [本地ip,马赛克]
  4     1 ms     1 ms    <1 毫秒 LAPTOP-4412C9V4 [本地ip,马赛克]
  5    11 ms     4 ms     *     LAPTOP-4412C9V4 [10.18.1.1]
  6     4 ms     4 ms     4 ms  10.0.68.1
  7     *        *        *     请求超时。
  8   544 ms    11 ms     5 ms  10.7.77.1
  9     *        *        *     请求超时。
 10     *        *        5 ms  10.0.92.5
 11     9 ms     *        4 ms  202.106.42.149
 12     2 ms     3 ms     2 ms  202.106.35.185
 13     3 ms     4 ms     5 ms  61.51.169.69
 14     9 ms     7 ms     7 ms  125.33.186.1
 15    31 ms    32 ms    30 ms  219.158.6.170
 16    29 ms    28 ms    69 ms  219.158.19.82
 17    27 ms    30 ms    31 ms  219.158.19.85
 18    54 ms    56 ms    55 ms  219.158.102.202
 19    55 ms    55 ms    54 ms  210.130.133.9
 20    57 ms    57 ms    60 ms  tky008bb01.IIJ.Net [58.138.104.37]
 21    57 ms    57 ms    57 ms  tky009bb01.IIJ.Net [58.138.88.38]
 22    57 ms    55 ms    55 ms  tky009ip58.IIJ.Net [58.138.112.234]
 23    55 ms    56 ms    55 ms  210.138.133.150
 24    58 ms    65 ms    59 ms  202.143.80.18
 25    57 ms    56 ms    59 ms  115.30.15.58
 26    65 ms    60 ms    60 ms  5.183.176.206`
截图：
![QQ截图20190504214851](https://user-images.githubusercontent.com/50203025/57180031-f5e46500-6eb6-11e9-8c86-2f8e1d21e011.png)
这个结果显示，数据包从中国联通主干网出去后（我是联通inode）直接进到了日本 东京Internet Initiative Japan公司，一直到25跳（倒数第二个ip）都是日本ip，但是最后一个ip突变成乌克兰。
这是否意味着代理软件使用了某种欺骗技术？
或者说，我到底在用哪里的代理服务器链接外网？
这个代理软件似乎是我用过的所有FQ技术里突破能力最强的（几乎没有无法访问的网站），速度也很快。相比之下，我自己在vultr建的日本vps不知为什么上不了p站
我很好奇它是否使用了更高级的技术

**Comment by Alvin9999** [comment]
1、brook和ssr不知道是否可以同时部署，你可以尝试下。
2、可能是p站对代理ip有限制。
3、你说的这个先跳到日本，最后到乌克兰。这个应该是vps的ip本身就是乌克兰，中途在日本进行了中转导致的，以最后的位置为准。
4、顺便问下，你说的这个代理软件叫什么名字呢？很好奇。

**Comment by admiral-graf-spee** [comment]
感谢。
1、好的。我感觉brook也挺好用的（先去给brook项目加一颗星），但并不清楚基于什么协议。以后尝试自建。
2、我谷歌了一下，p站好像是专门ban了vultr的某些ip= = 真的想上p站就用其他工具吧。

> vultr打不开p站是因为p站将一些vultr的ip给封了，所以你自然用代理也上不去的，你需要做的就是修改以下vultr的ip就行了，因为p站虽然封了一些vultr的ip，但是没有全部封禁，所以你只需要换到可用的ip就行

3、好的明白。这个问题可以和4、联系起来。我用国外网站查了一下这个乌克兰ip的whois（国内根本查不到啊）:
![QQ截图20190504233020](https://user-images.githubusercontent.com/50203025/57181549-e1f52f00-6ec7-11e9-99d3-2001dd37ff9b.png)
好像……信息量有点大，我很难解析其中的信息。
4、就是小白加速的黄金会员。这个公司只有一个静态主页，查不到任何关于它的身世背景，而且客户端的集成度很高，从所用本地端口1881看应该不是socks协议？（不确定）
更正一下，它的**延迟还是比我的vultr vps高的**。（只不过是访问所有网页都不怎么卡，给我一种延迟很低的错觉。所以这大概也从侧面证明了服务器更可能在乌克兰）同样一个优酷的4k画质视频《两位Youtuber的故事》，用vultr 日本vps搭建的ssr观看4k清晰度1倍速会卡住，观看1080p1倍速能正常观看但是2倍速会卡住；用xb黄金会员则1080p1倍速经常卡主，且每次加载白条更少，这方面和brook（免费版）的表现是差不多的。是不是由于大家都在用，所以带宽不够了，有这个原因
5、另外就是不理解锐速、bbr加速的原理，它们做到了什么，是如何做到的？希望您能赐教

**Comment by Alvin9999** [comment]
锐速、bbr加速的原理分析可以参考这个[锐速与BBR的原理简单解析](https://www.zhujiboke.com/2017/08/673.html)

免费的版本带宽是一定的，用的人多的话，速度会有一定的影响。

**Comment by Zreo4** [comment]
小白vpn?
