### ISSUE TITLE
浏览器的代理设置为（http）127.0.0.1和1080即可

### ISSUE THREAD

**Issue by hadeschx** [Alvin9999/new-pac#529]
请问这个要怎么设置，google和火狐游览器

**Comment by AnyWAT** [comment]
1、IE 或系统设置（成系统全局代理）
![图片](https://user-images.githubusercontent.com/37962734/57242824-1eab5c80-7067-11e9-90d2-217c7b0b1a46.png)

2、扩展设置 https://github.com/FelisCatus/SwitchyOmega 情景模式名称随意
![图片](https://user-images.githubusercontent.com/37962734/57242608-857c4600-7066-11e9-8db8-27f8fc93aaa3.png)

**Comment by hadeschx** [comment]
Win10按你第二张图设置了还是没用啊，手机里可以用的

**Comment by hadeschx** [comment]
不知道哪里出错了

**Comment by AnyWAT** [comment]
> 不知道哪里出错了

网络不同，手机能用但Win10不能用，并非代理设置问题。如 https://github.com/shadowsocks/shadowsocks-windows/issues/2338#issuecomment-489433200

**Comment by Alvin9999** [comment]
楼主现在弄好了没有呢？

**Comment by Jachinhuang** [comment]
你好啊，我和你遇到了一样的情况，刚刚解决。方法如下：
1.可以尝试用手机本地代理。链接：https://github.com/shadowsocks/shadowsocks-android/issues/1374
2.先把pc的杀毒软件给退了（我没退，但是我重新删除ssr重新部署的时候杀毒软件被强制关闭了，我用的是avast.），重新配置ssr就行。如果还不行的话，尝试：设置->网络和Internet->代理->手动设置代理  检查端口是否为1080.如果不是的话先退掉ssr,把端口改回1080，然后在启动ssr。
3.可参考https://github.com/shadowsocks/shadowsocks-windows/issues/1749
