### ISSUE TITLE
有個問題請教作者

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#53]
在Agent文件夾裡面的G.ip.txt文件起啥作用？

**Comment by Alvin9999** [comment]
没有作用，可以删掉。
曾经把它和GoGotest（搜ip软件）放在一起，方便用户自己搜ip，但后来此ip段已经搜不出ip来了，删掉GoGotest时忘把它一起删了。

**Comment by caofengzi** [comment]
@Alvin9999 這個proxy.user.ini_backup需要修改成和proxy.user.ini一樣的配置嗎？

**Comment by Alvin9999** [comment]
不用。在更新ip时，它只是起一个桥梁的作用，真正软件的运行是靠proxy.user.ini文件。

**Comment by Jason4774** [comment]
@Alvin9999 你好，请问你现在更新高质量ip是用的什么软件或者脚本呢？

**Comment by Alvin9999** [comment]
@Jason4774  自己搜的，然后更新到云端。你是想知道搜ip的软件吗？我用的是MFF再改版，参考帖子： https://github.com/phuslu/goproxy/issues/654

**Comment by Jason4774** [comment]
谢谢，昨天看了这个软件，但是没有用呢。我再重新看看。谢谢你。我主要是想知道你更新ip的方法。

**Comment by Jason4774** [comment]
@Alvin9999 你好，请问你可以出一个你更新高质量Ip的教程方便大家吗？这样大家可以自己找，然后同时也可以贡献到你这里。谢谢

**Comment by Alvin9999** [comment]
@Jason4774  这个不是三言两语说的清楚的，最近有点忙，等我空了再考虑写教程的事

**Comment by caofengzi** [comment]
使用mff很簡單，主要是ip段現在難找，有兩個國外的找ip的網址好像被dns汙染了，俺更換了幾次dns使用代理下載的ip地址鏈接然後用ding程序查找那個國家的ip段都是被汙染過的。

**Comment by Alvin9999** [comment]
这是xx-net的ip段，你可以用这个搜索https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/ip_range.txt

**Comment by Jason4774** [comment]
谢谢。你最近这次更新了什么啊。看不出来。

**Comment by Alvin9999** [comment]
GoProxy版更新了ip

**Comment by Jason4774** [comment]
谢谢新的教程
