### ISSUE TITLE
点击国外云盘下载无反应

### ISSUE THREAD

**Issue by crazyiiiiii** [Alvin9999/new-pac#530]
无法下载文件，是链接失效了吗?

**Comment by AnyWAT** [comment]
貌似更大的可能不是自己的代理不够劲？

**Comment by Alvin9999** [comment]
现在可以了。有可能是同一段时间连接数太多导致短暂下载不了。你再试试看呢，如果是翻墙浏览器，有2个下载地址，都可以试试看。

**Comment by crazyiiiiii** [comment]
> 现在可以了。有可能是同一段时间连接数太多导致短暂下载不了。你再试试看呢，如果是翻墙浏览器，有2个下载地址，都可以试试看。

已解决，谢谢回复。

**Comment by pysl** [comment]
又打不开咯...

**Comment by Alvin9999** [comment]
增加了trojan版的国内云盘下载，陆陆续续都会增加其它版本的
