### ISSUE TITLE
IP一开始连得上但是在XShell部署过程中就会突然断开连接然后连不上是什么情况呢 小白一个 求助。

### ISSUE THREAD

**Issue by sasayaki1** [Alvin9999/new-pac#532]
Connecting to 207.148.95.249:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Connection closed by foreign host.

Disconnected from remote host(新建会话 (2)) at 10:55:04.

Type `help' to learn how to use Xshell prompt.

以前正常时前三行出来以后就能输入用户名密码了 现在要么是跳不出来用户名密码就连接失败了，要么是用户名密码输入完以后部署到一半自动断开连接然后就连不上了。 
  Installing : foomatic-4.0.4-5.el6_7.x86_64                                                                          81/107 
  Installing : mesa-private-llvm-3.6.2-1.el6.x86_64 [############################################################# ]  82/107
Connection closed by foreign host.

Disconnected from remote host(新建会话 (2)) at 10:43:18.

Type `help' to learn how to use Xshell prompt.

试了好几个ip都是这样的情况，请问有什么解决办法吗

**Comment by Alvin9999** [comment]
用的哪个地区的vps呢？

**Comment by Alvin9999** [comment]
把杀毒软件和防火墙退出来，再用xshell来链接，试试看

**Comment by sasayaki1** [comment]
日本 法国 英国都试过了，都是这种情况。杀毒软件和防火墙也退了没用。@Alvin9999

**Comment by Alvin9999** [comment]
是部署bbr还是ssr脚本的时候出现的？

**Comment by sasayaki1** [comment]
> 是部署bbr还是ssr脚本的时候出现的？

都有出现 还有时候是连ip的时候就出现这种情况。

**Comment by Alvin9999** [comment]
你ping一下ip，是不是丢包严重？

**Comment by Alvin9999** [comment]
你可以尝试美国的服务器，比如达拉斯、西雅图等，然后在xshell里面新建。

**Comment by sasayaki1** [comment]
> 你ping一下ip，是不是丢包严重？

    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 216ms，最长 = 217ms，平均 = 216ms

**Comment by sasayaki1** [comment]
> 你可以尝试美国的服务器，比如达拉斯、西雅图等，然后在xshell里面新建。

试了下西雅图的 也是丢包 有时候百分之25 有时候50

**Comment by Alvin9999** [comment]
在xshell里面尝试，你是第一次部署吗？

**Comment by sasayaki1** [comment]
> 在xshell里面尝试，你是第一次部署吗？

不是 按你的教程部署过很多次了 就这两天出现了这种问题

**Comment by Alvin9999** [comment]
目前还没有其他反应遇到这种问题，你可以换个时间段，重启下电脑，再部署看看。你的xshell没有升级吧？

**Comment by sasayaki1** [comment]
> 在xshell里面尝试，你是第一次部署吗？

试了下西雅图的目前没出现那种情况。

**Comment by sasayaki1** [comment]
> 目前还没有其他反应遇到这种问题，你可以换个时间段，重启下电脑，再部署看看。你的xshell没有升级吧？

没升级

**Comment by Alvin9999** [comment]
OK

**Comment by sasayaki1** [comment]
> OK

谢谢啦

**Comment by cynen** [comment]
我之前也有遇到过这种情况，你看看，时候是服务器的防火墙没有关闭？ 
关闭系统自带的防火墙，vultr控制界面，在firewall里面添加你要打开的端口。 
这个断开连接，很大原因就是系统本身的防火墙搞的鬼。 

查看防火墙状态： 
`systemctl status firewalld`
 -- 会提示防火墙状态。 

关闭操作系统防火墙： 
`systemctl stop firewalld
`
永久关闭防火墙：
`systemctl disable firewalld`

**还需要在vultr里面打开对应的端口。**
