### ISSUE TITLE
请问为什么打不开这个网址呢?t66y.com

### ISSUE THREAD

**Issue by ifengliu** [Alvin9999/new-pac#533]
错误日志
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by Alvin9999** [comment]
因为免费账号vps屏蔽了成人网站。
