### ISSUE TITLE
流量用不完,还不如发给大家啦

### ISSUE THREAD

**Issue by cynen** [Alvin9999/new-pac#535]
IP: 207.148.72.205
port:8380/8381 【2端口都可以】
密码: 666666/777777 【密码和上面的端口对应】
加密:aes-256-cfb
协议:origin
混淆:plain

其次，做免流服务器一直失败，哪位大佬搞过免流？分享一下经验呗。我免流做了2次。。。不小心把我流量卡的2G流量给用完了。。。感觉被免流坑了
┭┮﹏┭┮

**Comment by cynen** [comment]
流量还有500G，不出意外，我会开放到月底。

**Comment by ifengliu** [comment]
使用后,谷歌打不开...

**Comment by 2165998** [comment]
能用！！！

**Comment by cynen** [comment]
> 使用后,谷歌打不开...

是不是没配置好? 检查配置试一下

**Comment by cynen** [comment]
你们太狠了...大周五的,我居然打不开google...你们要不要这样?

**Comment by wx0322** [comment]
感谢。只是为了查资料用。

**Comment by cynen** [comment]
> 感谢。只是为了查资料用。

其实，还可以用来干点别的，O(∩_∩)O哈哈~

**Comment by jinyumarine** [comment]
@cynen 貌似不能用

**Comment by gMan1990** [comment]
我觉得公开的最好加上限速。。不然下载看视频一下就耍没了。

**Comment by cynen** [comment]
> @cynen 貌似不能用

过期了...

**Comment by cynen** [comment]
> 我觉得公开的最好加上限速。。不然下载看视频一下就耍没了。

我是在乎那500G流量的人吗? 我现在是在找网速快点的VPN,O(∩_∩)O哈哈~ 开玩笑的.月底过了,500G还没用到100G.哎...又给vutrl公司赚大发了
