### ISSUE TITLE
脚本二安装后如何查看账号信息

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#536]
如题

**Comment by V-zhangyunxiang** [comment]
目前是通过 vim 编辑模式 vi /etc/shadowsocks.json 查看，很麻烦

**Comment by Alvin9999** [comment]
cat /etc/shadowsocks.json
脚本二没有脚本一方便，建议用脚本一

**Comment by Alvin9999** [comment]
脚本二每次要修改配置时都要重新输入部署ssr代码，相当于重新部署一遍，而脚本一就要方便多了

**Comment by V-zhangyunxiang** [comment]
> 脚本二每次要修改配置时都要重新输入部署ssr代码，相当于重新部署一遍，而脚本一就要方便多了
因为脚本一不支持 centOS 7，无法使用 bbr plus ，所以用的脚本二，不过用 Linux 命令行还是好查看以及修改的。

**Comment by Alvin9999** [comment]
脚本一应该是可以在centos7用的，如果下次再尝试，把vps防火墙关了

**Comment by V-zhangyunxiang** [comment]
> 脚本一应该是可以在centos7用的，如果下次再尝试，把vps防火墙关了

好的，感谢
