### ISSUE TITLE
ssr可以连接外网但是过一段时间后就连接不上需要把ssr进程关掉然后重开才能继续用一段时间然后重复这个过程，请问这是怎么回事怎么解决？

### ISSUE THREAD

**Issue by kinkdom** [Alvin9999/new-pac#539]

**Comment by Alvin9999** [comment]
有可能是杀毒软件或者防火墙干扰，可以关闭这些再试试看

**Comment by kinkdom** [comment]
> 有可能是杀毒软件或者防火墙干扰，可以关闭这些再试试看

应该不是，我没有开任何杀毒软件而且防火墙也设置了不对ssr干涉

**Comment by Alvin9999** [comment]
现在好了吗？

**Comment by zhuxianzhiniko** [comment]
> 现在好了吗？

一样的情况，SS,和SSR，混淆都试过了。地址是 广东深圳企业中国电信。(公司)

手机电信4G，和家里网络（中国电信）都是可以上。

感觉是企业电信的做了一些识别？随机性丢包？

> 现在好了吗？

**Comment by kinkdom** [comment]
> > 现在好了吗？
> 
> 一样的情况，SS,和SSR，混淆都试过了。地址是 广东深圳企业中国电信。(公司)
> 
> 手机电信4G，和家里网络（中国电信）都是可以上。
> 
> 感觉是企业电信的做了一些识别？随机性丢包？

我本地没有做任何操作，服务端也没有去改过什么然后它就自己好了。这几天一直用着很稳定所以还是不清楚之前到底是什么问题
