### ISSUE TITLE
Trojan的配置文件更新

### ISSUE THREAD

**Issue by gxpgc** [Alvin9999/new-pac#543]
请问Trojan的config.json文件怎么更新？能有一个更新的bat文件就好了，谢谢你们的服务！

**Comment by Alvin9999** [comment]
Trojan版如果未来需要更新，会采取发新版文件来更新的方式。之所以没有整合bat文件，是因为Trojan版有点特别，需要ctr证书文件，仅仅更新config.json文件是无法使用的。
