### ISSUE TITLE
小飞机测速有网络连接,但是打不开google;请问该如何解决呢?

### ISSUE THREAD

**Issue by WanderZY** [Alvin9999/new-pac#544]
<img width="595" alt="屏幕快照 2019-05-27 下午5 36 48" src="https://user-images.githubusercontent.com/44358718/58411080-182c6580-80a6-11e9-9b31-035dbbc578a5.png">

**Comment by Alvin9999** [comment]
是只有google打不开吗？其它网站呢？

**Comment by WanderZY** [comment]
准确的讲是被墙的都访问不了,现在服务器直接fail了
![image](https://user-images.githubusercontent.com/44358718/58445649-0394af80-8130-11e9-998d-91a5f1e2ce84.png)

**Comment by Alvin9999** [comment]
如果ip可以ping通，那说明ip没有被墙。可以尝试修改端口为5位数，协议和混淆分别设置为origin和plain，然后再试试看

**Comment by sylartp** [comment]
@Alvin9999  您好，我现在问题是可以ping通，端口Telnet也可以，就是访问不了谷歌相关墙外网站

**Comment by Alvin9999** [comment]
@sylartp 请问你是自建的还是用的我分享的免费的账号呢

**Comment by sylartp** [comment]
@Alvin9999 自建的，vultr上面弄了个亚特兰大的服务器

**Comment by Alvin9999** [comment]
@sylartp  端口设置为5位数，协议和混淆设置成origin和plain，然后再试试看

**Comment by sylartp** [comment]
@Alvin9999 没事了，我用了你的免费的ss账号然后在GCP上开了个新加坡的可以科学上网了 ^ _ ^ 谢谢~
