### ISSUE TITLE
2019.06.01为啥所有VPN都不能使用了

### ISSUE THREAD

**Issue by EpicWang** [Alvin9999/new-pac#547]
RT,有人知道原因吗，国内有什么事情发生吗，还是贸易战的原因？

**Comment by AnyWAT** [comment]
> 2019.06.01

😱试试：
年号-30
日期+03

**Comment by YeYoot** [comment]
昨天挂了一个服务器，重新开了一个，今天又挂了！

**Comment by Hanseltu** [comment]
看来不是我一个人挂掉了，，，我还在找原因。。。

**Comment by xfgithub** [comment]
我这边也挂了，新建一个也不能用，啥情况啊，有解决的人吗？

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477

**Comment by xfgithub** [comment]
> ✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。[XX-net/XX-Net#12477](https://github.com/XX-net/XX-Net/issues/12477)

兄弟 你的可以用吗？

**Comment by Admgan** [comment]
这几天是特殊时期，听别人说好像是每年这个时候防火墙会对网络进行重新加固，大概到5号之后就慢慢会好了，不是你自己的软件或者节点的问题，都出现这样的情况了，别急。

**Comment by AnyWAT** [comment]
> 兄弟 你的可以用吗？

原生没感觉有异样，隧道或许较以往差了点儿。https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839

**Comment by pi408637535** [comment]
我的也给干倒了

**Comment by Hanseltu** [comment]
可能是因为six-4

**Comment by pi408637535** [comment]
@Hanseltu 什么是six-4

**Comment by AnyWAT** [comment]
2楼

**Comment by yuyujulin** [comment]
难怪呢

**Comment by imxiny** [comment]
难受的一批

**Comment by xfgithub** [comment]
有知道需要啥时候才能正常使用的吗？在线等，急急急

**Comment by imxiny** [comment]
> 有知道需要啥时候才能正常使用的吗？在线等，急急急

6号就差不多了

**Comment by xfgithub** [comment]
https://github.com/Alvin9999/new-pac/issues/547#issuecomment-498014995
具体原因是啥，没听懂啊，six-4

**Comment by TALanaya** [comment]
同61两个vps架的ssr都翻不了，儿童节严打吗哈哈哈

**Comment by imxiny** [comment]
> [#547 (comment)](https://github.com/Alvin9999/new-pac/issues/547#issuecomment-498014995)
> 具体原因是啥，没听懂啊，six-4

1989.6.4

**Comment by Admgan** [comment]
> [#547 (comment)](https://github.com/Alvin9999/new-pac/issues/547#issuecomment-498014995)
> 具体原因是啥，没听懂啊，six-4

你去翻翻前面的，看懂就看，看不懂就不用知道了，话题太敏感

**Comment by Hanseltu** [comment]
chrome浏览器插件 setupvpn可用，但是只能局域使用，只能将就一下了

**Comment by Tommycm** [comment]
> chrome浏览器插件 setupvpn可用，但是只能局域使用，只能将就一下了

这个插件看视频一堆广告，而且速度不快，有每天有流量限制，看会视频就不行了

**Comment by xfgithub** [comment]
Setupvpn插件安装不了啊！一直报错 程序包无效啊，有解吗各位

**Comment by wqh0109663** [comment]
> 昨天挂了一个服务器，重新开了一个，今天又挂了！

跟你一样

**Comment by AnyWAT** [comment]
chrome 扩展 skyZIP™ Proxy 可用（在线安装需代理？）：https://chrome.google.com/webstore/detail/skyzip-proxy/hbgknjagaclofapkgkeapamhmglnbphi

**Comment by RoastEgg** [comment]
跟大家一样。。挂了。。

**Comment by Alvin9999** [comment]
ss/ssr暂时用不了的，可以下载我分享的trojan版和brook版翻墙浏览器。

**Comment by rickeyliao** [comment]
6.1 儿童不宜 ...six-4不懂的，证明你很年轻。

**Comment by gbbh** [comment]
自建和试用的都挂掉了，再等等看

**Comment by nanjixing** [comment]
@Alvin9999能分享一份吗现在下不了啊

**Comment by zoukun120** [comment]
我也挂了，难受

**Comment by zoukun120** [comment]
> > 2019.06.01
> 
> 😱试试：
> 年号-30
> 月份不变
> 日期+03

什么意思？

**Comment by zoukun120** [comment]
你们这几天都是怎么翻墙的？

**Comment by Ellen9616** [comment]
6.1就挂了然后新开了一个还没撑过两天又挂 无语😓

**Comment by 774471872** [comment]
> RT，有人知道原因吗，国内有什么事情发生吗，还是贸易战的原因？
89年6月4号天安门闹学潮，今年是30周年，你不知道？

**Comment by forever8938** [comment]
github都被墙了

**Comment by AeneasZhu** [comment]
> > 2019.06.01
> 
> 😱试试：
> 年号-30
> 月份不变
> 日期+03

唉，国殇日

**Comment by GaranYeon** [comment]
brook昨晚还能用，今天就用不了

**Comment by WangZhonglei** [comment]
还能不能快乐的看片了

**Comment by 774471872** [comment]
我刚才进了外网，只搜了中国俩字，然后头条就是“64天安门大屠杀”，等等舆论，大家还是最近不要进外网了，有些人会被这些舆论洗脑，发一些乱七八糟的话，做一些傻了吧唧的事。

**Comment by AeneasZhu** [comment]
> 64天安门大屠杀

一个国家要是真的自信，就要直面她的历史，不管是光荣还是屈辱，就像德国、法国那样。一个国家不敢面对自己的过去，恰恰是她极度自卑的体现。中国什么时候真正自信起来，就是敢于直面自己历史，直面自己国民的时候。

我没经历那个时期，但我对那个时候的国人抱有敬意，他们真正影响改变了当时的世界。他们吹响了东欧剧变的号角，打破了笼罩在整个半球的铁幕。

**Comment by Emeryout19** [comment]
Tiananmen Square Massacre
![Tankman_new_longshot_StuartFranklin](https://user-images.githubusercontent.com/32247328/58876279-2579cd80-8700-11e9-9a4a-705514c6ecb4.jpg)

**Comment by pi408637535** [comment]
6.5了，还没恢复....

**Comment by 774471872** [comment]
> 6.5了，还没恢复....

还早着呢，最少得到6月15号以后

**Comment by 774471872** [comment]
> Tiananmen Square Massacre
> ![Tankman_new_longshot_StuartFranklin](https://user-images.githubusercontent.com/32247328/58876279-2579cd80-8700-11e9-9a4a-705514c6ecb4.jpg)
> ![61657163_10155866794356065_6397055686596886528_n](https://user-images.githubusercontent.com/32247328/58876986-3297bc00-8702-11e9-90ac-bfddb949f5bc.jpg)

发这些干啥？根本不关我们的事，你知道事情真相吗？你是6 4参与者吗？显然你不是，所以不要听风就是雨，人一辈子就短短几十年，自己活得潇洒就行了，管那么多别人的破事干啥？

**Comment by Emeryout19** [comment]
> 
> 发这些干啥？根本不关我们的事，你知道事情真相吗？你是6 4参与者吗？显然你不是，所以不要听风就是雨，人一辈子就短短几十年，自己活得潇洒就行了，管那么多别人的破事干啥？

"自己活得潇洒就行了" 問題是問題太多根本沒有安全感沒法治我今天活得潇洒明天就失聯了,不"管那么多别人的破事"不行啊.

我信不信64根本無所謂,"人一辈子就短短几十年",但我也得考慮家人孩子啊,不是每個人都像5毛一樣的孤兒光棍啊.

**Comment by 774471872** [comment]
> > 发这些干啥？根本不关我们的事，你知道事情真相吗？你是6 4参与者吗？显然你不是，所以不要听风就是雨，人一辈子就短短几十年，自己活得潇洒就行了，管那么多别人的破事干啥？
> 
> "自己活得潇洒就行了" 問題是問題太多根本沒有安全感沒法治我今天活得潇洒明天就失聯了,不"管那么多别人的破事"不行啊.
> 
> 我信不信64根本無所謂,"人一辈子就短短几十年",但我也得考慮家人孩子啊,不是每個人都像5毛一樣的孤兒光棍啊.
你有啥不安全的，我活了二十多年，毕业在上海混了3年，然后杭州又混了2年，也没感觉到什么不安全，再说了你认为你使劲宣传这些历史就能安全，你这么干只会引起动乱，不会带来和平，你想让这种历史重演？

**Comment by Emeryout19** [comment]
> > 6.5了，还没恢复....
> 
> 还早着呢，最少得到6月15号以后

首先麻煩説下你的消息來源,你是自己做夢夢到的的呢還是有gfw的内部情報?

"也没感觉到什么不安全"這只是你個人的主觀感受,卻不能否定各種無視人權不遵守程序濫抓人抓了人不讓見家人律師的客觀事實以及封殺人民言論自由利用國家機器製造恐怖維護一黨之私利的邪惡行徑.
何況5毛狗的主觀感受本就異於常人,住在監獄裏吃屎照樣感覺安全又幸福.你的辯解毫無說服力.

再说我貼了2張圖就"会引起动乱",你說的安全原來這麽脆弱不堪啊.那我告訴你我一直在訓練特種部隊準備直接去中南海實施斬首行動,你不得嚇到失禁啊.
暴政才是動亂之源,終結暴政才會"带来和平".历史當然不會重演,貪官暴君們會被清算,人民必拿回應有的權利.

**Comment by wqh0109663** [comment]
可以用了说一声

**Comment by josyonchen** [comment]
my lantern client not used.from 6.1 so what's happening?

**Comment by iamwalt** [comment]
> 
> 
> > 64天安门大屠杀
> 
> 一个国家要是真的自信，就要直面她的历史，不管是光荣还是屈辱，就像德国、法国那样。一个国家不敢面对自己的过去，恰恰是她极度自卑的体现。中国什么时候真正自信起来，就是敢于直面自己历史，直面自己国民的时候。
> 
> 我没经历那个时期，但我对那个时候的国人抱有敬意，他们真正影响改变了当时的世界。他们吹响了东欧剧变的号角，打破了笼罩在整个半球的铁幕。

从整个教育体系到政治体系都没有做好打舆论战的准备。或者更深层说是进入别人的规则里战斗还是自己设主场的问题。老邓定了基调韬光养晦，估计没到具备订立规则的实力水平时候，舆论战打不起来。

**Comment by EpicWang** [comment]
各位：
1. 我提这个issue时真的没想到时这样的原因
2. 之后我自己买服务器自己架了一个梯子，这几天都正常使用
3. 最好不要讨论这么敏感的问题
