### ISSUE TITLE
电脑上的账号可以翻,同一个账号手机却不行

### ISSUE THREAD

**Issue by gally16** [Alvin9999/new-pac#548]
电脑上的账号可以翻,同一个账号手机却不行
手机是连WiFi的=.=

**Comment by Admgan** [comment]
不会吧    用的什么账号  SSR？还是SS还是其他的

**Comment by jinyumarine** [comment]
现在基本上抽风状态，基本上连接不上

**Comment by xfgithub** [comment]
我连ip都ping不通，死绝了

**Comment by Alvin9999** [comment]
应该是手机网络和电脑网络运营商不同造成封锁的缘故，可以尝试换下5位数的端口，协议和混淆设置成origin和plain，然后再试试看。

ss/ssr暂时用不了的，可以下载我分享的trojan版和brook版翻墙浏览器。

**Comment by gally16** [comment]
> 应该是手机网络和电脑网络运营商不同造成封锁的缘故，可以尝试换下5位数的端口，协议和混淆设置成origin和plain，然后再试试看。
> 
> ss/ssr暂时用不了的，可以下载我分享的trojan版和brook版翻墙浏览器。

手机是连WiFi的，网络就是当年的网络。就是你分享的免费账号，是5位数的端口哦

**Comment by jinyumarine** [comment]
我正好相反，同wifi下，手机正常SS，PC端翻不了

**Comment by Willib** [comment]
我的也好奇怪，今天发现原来的ip被封了，就重新开了一个，配置好后，电脑上修改了下配置就连接上了，但是在手机端iOS 修改或者新增加节点试了下都不行，网是用的移动流量，小火箭是APP store上美国账户下载的。。晕死。。 = =

**Comment by jinyumarine** [comment]
@Willib 我的手机正常，PC用不了
