### ISSUE TITLE
这个自建v2ray我在第二步被卡住了

### ISSUE THREAD

**Issue by theendtimes** [Alvin9999/new-pac#553]
如题，第一步很顺利的完成，但是到了第二步时在打上脚本那里卡住，无法输入v2ray配置。net更新到最新4.7.2，系统是win7，第一次建v2ray，能请你帮助我一下吗？

**Comment by theendtimes** [comment]
https://github.com/Alvin9999/new-pac/wiki/自建v2ray服务器教程，我是学着这个帖子来的，不知道什么原因，复制了脚本粘贴后，链接就自己中断

**Comment by Alvin9999** [comment]
可以截图看看吗

**Comment by theendtimes** [comment]
你好，使用ss就能正常了。v2ray之前是使用Xshell6安装，所以安装异常。但是后来使用Xshell5也用不了v2ray，不知道为什么，流程正常，链接后也显示链接上，但是无法上youtube和大纪元

**Comment by Alvin9999** [comment]
之前是其它网站都可以上吗？
