### ISSUE TITLE
2个chrome

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#555]
我的电脑本来就安装了chrome  刚刚安装的Trojan版 里面也有一个，  会有冲突吗 ，怎么解决？另外安装包里有一个chrome升级器  需要升级chrome吗？目前正常使用

**Comment by AnyWAT** [comment]
貌似（原有）安装版与后安装（严格来说，非安装乃绿色解压）版不会冲突，“目前正常使用”。😂当然升级了好（不然软件自身为毛要升级？）

**Comment by Alvin9999** [comment]
一键翻墙浏览器是便携版，不用安装，解压后打开使用，所以不会和自己安装的chrom冲突。

不升级也能用。
