### ISSUE TITLE
Chrome69_64bit_Brook_2019.4.18.7z被Windows报毒了...

### ISSUE THREAD

**Issue by Emeryout19** [Alvin9999/new-pac#556]
![Untitled](https://user-images.githubusercontent.com/32247328/58922818-37468980-876f-11e9-8593-39bf9e9a4cd8.png)

**Comment by Alvin9999** [comment]
误报，一般新型软件，尤其是小众翻墙软件，都容易被误报，软件没有问题的

**Comment by Emeryout19** [comment]
感謝大佬回復
