### ISSUE TITLE
浏览器升级

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#557]
安装包有个chrome升级器 ，有用吗？有没试过的小伙伴

**Comment by liao6964799** [comment]
> 安装包有个铬升级器，有用吗？有没试过的小伙伴

我自己刚刚试了一下 那个升级器不能一键升级  ，查询获得的地址也是无效的！ 没法更新

**Comment by AnyWAT** [comment]
https://github.com/Alvin9999/new-pac/issues/555#issuecomment-498886395
https://github.com/Alvin9999/new-pac/issues/320#issuecomment-428168541
https://github.com/Alvin9999/new-pac/issues/408#issuecomment-432916739

**Comment by AnyWAT** [comment]
原来是😭2个chrome #555 楼主

**Comment by liao6964799** [comment]
> 原来是😭2个铬[＃555](https://github.com/Alvin9999/new-pac/issues/555)楼主

是  哈哈

**Comment by liao6964799** [comment]
> > 原来是😭2个铬[＃555](https://github.com/Alvin9999/new-pac/issues/555)楼主
> 
> 是哈哈

那个更新器是要提供压缩包升级吗？  可以不可以把最新的chrome文件夹压缩 然后给它升级？

**Comment by liao6964799** [comment]
> 原来是😭2个铬[＃555](https://github.com/Alvin9999/new-pac/issues/555)楼主

那个更新器需要压缩包升级？ 把最新chrome文件夹压缩给它升级行不行？

**Comment by AnyWAT** [comment]
不太明白你说的，
运行 ChromeUpdateSharp.exe 。。。

**Comment by liao6964799** [comment]
> 不太明白你说的，
> 运行ChromeUpdateSharp.exe ...

那个更新器是要选择压缩包然后解压升级，我自己有安装最新版的谷歌浏览器，我把它的文件夹打成压缩包然后拿到升级器里升级  ，靠谱吗？

**Comment by AnyWAT** [comment]
没试过。。。
如能从安装版整出 Chrome-bin 文件夹，包含 75.0.3770.80 文件夹及 chrome.exe、chrome_proxy.exe 的话，倒是行？

**Comment by liao6964799** [comment]
> 没试过... 
> 如能从安装版整出Chrome-bin文件夹，其下包含新版75.0.3770.80文件夹及chrome.exe，chrome_proxy.exe的话，倒是行？

不纠结了 ，这个升级还是留给作者吧，竟然他最新给的下载安装包都是69版的，应该是有目的的。

**Comment by Alvin9999** [comment]
嗯嗯，升级这个会考虑的。
