### ISSUE TITLE
今天更新的服务器，ping都ping不通

### ISSUE THREAD

**Issue by loverto** [Alvin9999/new-pac#559]
正在 Ping 38.141.44.51 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

38.141.44.51 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by sasayaku** [comment]
已阵亡
![TIM截图20190605163722](https://user-images.githubusercontent.com/7899927/58942556-8cef5600-87b0-11e9-868f-2a8076812ea8.png)

**Comment by loverto** [comment]
这几天毕的真快

**Comment by liao6964799** [comment]
> 这几天毕的真快

你用的是什么版本

**Comment by YeYoot** [comment]
新开服务器1小时内就gg

**Comment by arifranken** [comment]
不知为啥Xndroid一直能用，不过只能浏览器翻墙，Googleplay这些都不了。。。

**Comment by lvdream** [comment]
昨天搬瓦工刚刚换了一个IP，2个小时就阵亡了，我的60大洋

**Comment by firebirdwu** [comment]
我今天刚换的iP,还没用一个小时就又阵亡了

**Comment by mourinholiu** [comment]
什么时候才恢复正常啊！！！

**Comment by Alvin9999** [comment]
又更新了一下，对速度进行了大幅度限制

**Comment by NovaHe** [comment]
最近是什么时期？

**Comment by Alvin9999** [comment]
几个小时前
