### ISSUE TITLE
您好，问一下有安卓能用的上IG，脸书的翻墙app吗？

### ISSUE THREAD

**Issue by maidiweide** [Alvin9999/new-pac#56]
之前一直用蓝灯，现在不好用了，想来问一下安卓手机有能用来上IG，脸书的翻墙app吗？

**Comment by caofengzi** [comment]
到這裡下載安卓版ssr，然後添加樓主提供的免費ss帳號。https://github.com/breakwa11

**Comment by maidiweide** [comment]
万分感谢！
