### ISSUE TITLE
锐速不支持Ubuntu吗

### ISSUE THREAD

**Issue by marud1024** [Alvin9999/new-pac#560]
操作系统：Ubuntu 
发行版本：18.04 
内核版本：4.15.0-1032-aws 
位数：x64 
锐速版本：3.10.61.0

**Comment by Alvin9999** [comment]
应该是可以的，你直接用第二步

**Comment by marud1024** [comment]
Last-modified header missing -- time-stamps turned off.
2019-06-10 06:50:33 (145 MB/s) - ‘serverspeeder-all.sh’ saved [10095/10095]

Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
=================================================
操作系统：Ubuntu 
发行版本：18.04 
内核版本：4.15.0-1032-aws 
位数：x64 
锐速版本：3.10.61.0 
=================================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96179  100 96179    0     0   208k      0 --:--:-- --:--:-- --:--:--  207k


锐速暂不支持该内核，程序退出.自动安装判断比较严格，你可以到http://www.91yun.org/serverspeeder91yun手动下载安装文件尝试不同版本

**Comment by Alvin9999** [comment]
应该是你的系统版本太高的缘故。如果要用ubuntu，可以尝试14版本的。如果对系统没什么要求，可以换centos系统。

**Comment by marud1024** [comment]
哦 好吧 谢谢老哥
