### ISSUE TITLE
最新的ip又被墙了

### ISSUE THREAD

**Issue by SLin0218** [Alvin9999/new-pac#562]
刚才还在弄google云, ssh 还没通, 
会更新新的IP吗

**Comment by BloCamLimb** [comment]
今天更新的ip也ping不通

**Comment by loverto** [comment]
是的，被墙了

**Comment by Asphyxia-m** [comment]
嘤嘤嘤

**Comment by moxixuan** [comment]
ai

**Comment by weipan1993** [comment]
我还以为，被运营商监管了。原理被墙了。

**Comment by Jay-Chuang** [comment]
还是被 Q-I-A-N-G 了

**Comment by 1106035348** [comment]
早上还用了

**Comment by Alvin9999** [comment]
刚又更新了一下，可以试试看

**Comment by wqh0109663** [comment]
连挂三台。。。

**Comment by pi408637535** [comment]
这以后想出去是不是只能走出国这条路了。想看的课程也看不了，难受啊

**Comment by AnyWAT** [comment]
> 想看的课程也看不了，难受啊

如网络已有 IPv6，近些天也无异常的简单操作。。。https://github.com/XX-Net/XX-net/issues/12477

**Comment by StoicLD** [comment]
连续弄了6台服务器都没ping通，难道都被墙了吗......

**Comment by lixiansky** [comment]
分享一个： 125.71.3.114  8888   nutgeek   rc4-md5   origin   plain

**Comment by wqh0109663** [comment]
> 分享一个： 125.71.3.114 8888 nutgeek rc4-md5 origin plain
四川的ip ？？？

**Comment by lixiansky** [comment]
> > 分享一个： 125.71.3.114 8888 nutgeek rc4-md5 origin plain
> > 四川的ip ？？？

能上就可以了~~~

**Comment by SLin0218** [comment]
外币信用卡, 可以注册 google 云 吗, 免费一年

**Comment by bylucky** [comment]
v2ray 也被墙吗？

**Comment by moxixuan** [comment]
> 
> 
> v2ray 也被墙吗？

可以上的，是不是你公司墙了？

**Comment by AnyWAT** [comment]
@stonytjd https://github.com/XX-net/XX-Net/issues/12587
> @AnyWAT comment怎么删了？有新办法？

https://github.com/XX-net/XX-Net/issues/12599

https://github.com/XX-net/XX-Net/issues/12455 https://github.com/XX-net/XX-Net/issues/12477

被强权。。。点开原贴顶楼用户名所在行最后的向下三角，即可见各版。。。

**Comment by AnyWAT** [comment]
@squallyang520 https://github.com/XX-net/XX-Net/issues/12610 直连光猫原生 IPv6 下即时，导入 IP 为主（ https://github.com/XX-net/XX-Net/issues/12477 ），也能自扫描出一点 IPv4：

![image](https://user-images.githubusercontent.com/37962734/60404557-98317800-9bdc-11e9-918e-da3441806df9.png)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12636 此刻原生仍正常，Teredo 隧道正常但扫描不到 IP，与原生一样可导入 IP：调小甚至关闭扫描、IP模式为自动或仅 IPv4（IPv6几乎无效了），IP来自 gscan_quic，见 https://github.com/XX-net/XX-Net/issues/12477

![image](https://user-images.githubusercontent.com/37962734/61261720-4892a500-a7b5-11e9-8e84-5c66cd972dfc.png)

**Comment by AnyWAT** [comment]
@Andywang089 https://github.com/XX-net/XX-Net/issues/12642 同为移动光纤，光猫直接电脑，用原生（见上楼）

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12690 
原生 IPv6 https://github.com/XX-net/XX-Net/issues/12477 点开“三角”看鄙人的最终版

![image](https://user-images.githubusercontent.com/37962734/63634529-5677f780-c68a-11e9-9f00-746ababa3c76.png)

![image](https://user-images.githubusercontent.com/37962734/63634546-8fb06780-c68a-11e9-9aaa-a9fc4991ce39.png)

![image](https://user-images.githubusercontent.com/37962734/63634556-b2428080-c68a-11e9-89d9-acae533328e0.png)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12690 https://github.com/XX-net/XX-Net/issues/12700 解决😱
