### ISSUE TITLE
trojan.exe 被avast报风险

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#563]
误报吧？ 直接拉入白名单吗？

**Comment by liao6964799** [comment]
@Alvin9999 
![批注 2019-06-06 211842](https://user-images.githubusercontent.com/35887374/59035823-af609c80-88a0-11e9-912e-dd7476fdce04.jpg)

**Comment by Alvin9999** [comment]
是的，加入白名单即可
