### ISSUE TITLE
您知道嘛叫小众VPS?

### ISSUE THREAD

**Issue by canalist** [Alvin9999/new-pac#564]
六四前，发了个帖子问版主，请教小众VPS。担心突然被封，嗖地一声拔掉无情。

转念一想，这种愚蠢的问题也好意思问版主？想来想去，还是“大众当中的小众 ”吧。大厂，其中少有问津者，又买一个。

惭愧，两个都没封。六四去矣，却看众网友纷纷诉苦，不免兔死狐悲，又寻思“真正的小众”，买了个大家不太可能买的——贵且不说，窄带，服务极差。

这种VPS服务商咋不去死呢？咋就活着呢？我叉他爹！

然而，悲剧就这么存在着，自有中国人养着。呜呼国人，怒其不争又有何用？我们真地一点办法都没有。

**Comment by Alvin9999** [comment]
对未来要有信心哦！多多帮助身边的朋友翻出去呼吸新鲜的空气、了解真相，当谎言包不住的时候自然就是黎明的到来。而且，现在国际上很多国家做的事，也在帮助中国人民。

**Comment by canalist** [comment]
@Alvin9999 版主您好！一直在盼您回帖。您帮助中国人翻墙，我敬您如佛祖。我不会止于独善其身，一定帮助亲朋好友。谢谢！

**Comment by cynen** [comment]
首先申明: 本人目前并非GCD员, 群众一枚,翻墙时间也不短,主要在youtube混迹.
说句真心话,墙外的新闻不一定香. 

大纪元,九评 之类的,都是某功在后台支撑,胡言乱语,抹黑造谣. 不小心还发现,美国政府居然赞助某功办网站!!. 

从此对某功深恶痛绝. 以前还比较客观看待.

尽自己观点,不喜勿喷.谢谢.

**Comment by Alvin9999** [comment]
@cynen  兼听则明吧，长期受大陆宣传的影响，很难获得真相的。你说的某功并不是像你说的那样。
