### ISSUE TITLE
v2ray客户端配置文件config.json 导入 V2rayX客户端时软件崩溃

### ISSUE THREAD

**Issue by hibluesea** [Alvin9999/new-pac#567]
ss 喜欢抽风，在某些网络下使用经常被封。想尝试一下v2ray, 按照楼主提供的教程服务端安装完成后配置客户端的时候遇到问题。客户端配置文件是按照程序导出到本地的，导入到v2rayX软件中时先是提示：
 tag direct is reserved, please use another one!  再advance 中删除该tag 后点击OK保存配置结果软件闪退。命令行信息如下，麻烦楼主看看可能是什么原因，不胜感激

/Applications/V2RayX.app/Contents/MacOS/V2RayX
2019-06-06 18:52:12.413 V2RayX[1220:68764] pac file is switched to pac.js
[INFO] GCDWebServer started on port 8070 and reachable at http://172.30.0.50:8070/
2019-06-06 18:52:12.422 V2RayX[1220:68764] 0, -1
2019-06-06 18:52:12.428 V2RayX[1220:68768] /Users/XXXX/Library/Application Support/V2RayX/cenmrev.v2rayx.v2ray-core.plist: No such file or directory
2019-06-06 18:52:12.431 V2RayX[1220:68764] updatePacMenuList
2019-06-06 18:52:12.492 V2RayX[1220:68768] V2Ray core unloaded.
objc[1220]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff94502cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10e19bcd8). One of the two will be used. Which one is undefined.
2019-06-06 18:54:19.025 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:19.671 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:19.879 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:20.929 V2RayX[1220:68764] do nothing
2019-06-06 18:54:35.744 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:36.143 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:36.335 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:54:36.519 V2RayX[1220:68764] -[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fff91215dd0
2019-06-06 18:56:15.318 V2RayX[1220:68764] 0, -1
2019-06-06 18:56:15.318 V2RayX[1220:68764] updatePacMenuList
2019-06-06 18:56:15.319 V2RayX[1220:77883] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object (
{
domainStrategy = AsIs;
name = "all_to_main";
rules = (
{
outboundTag = main;
port = "0-65535";
type = field;
}
);
},
{
domainStrategy = IPIfNonMatch;
name = "bypasscn_private_apple";
rules = (
{
domain = (
localhost,
"domain:me.com",
"domain:lookup-api.apple.com",
"domain:icloud-content.com",
"domain:icloud.com",
"domain:cdn-apple.com",
"domain:apple-cloudkit.com",
"domain:apple.com",
"domain:apple.co",
"domain:aaplimg.com",
"domain:guzzoni.apple.com",
"geosite:cn"
);
outboundTag = direct;
type = field;
},
{
ip = (
"geoip:private",
"geoip:cn"
);
outboundTag = direct;
type = field;
},
{
outboundTag = main;
port = "0-65535";
type = field;
}
);
},
{
domainStrategy = AsIs;
name = "all_to_direct";
rules = (
{
outboundTag = direct;
port = "0-65535";
type = field;
}
);
},
{
domainStrategy = IPIfNonMatch;
name = "some rule set";
rules = (
{
domain = "";
ip = (
"0.0.0.0/8",
"10.0.0.0/8",
"100.64.0.0/10",
"127.0.0.0/8",
"169.254.0.0/16",
"172.16.0.0/12",
"192.0.0.0/24",
"192.0.2.0/24",
"192.168.0.0/16",
"198.18.0.0/15",
"198.51.100.0/24",
"203.0.113.0/24",
"::1/128",
"fc00::/7",
"fe80::/10"
);
outboundTag = direct;
port = "";
type = field;
},
{
outboundTag = main;
port = "0-65535";
type = field;
}
);
}
) for key routingRuleSets'
*** First throw call stack:
(
0 CoreFoundation 0x00007fff3709465b __exceptionPreprocess + 171
1 libobjc.A.dylib 0x00007fff5e320c76 objc_exception_throw + 48
2 CoreFoundation 0x00007fff3712617d +[NSException raise:format:] + 205
3 CoreFoundation 0x00007fff36fd0caa _CFPrefsValidateValueForKey + 266
4 CoreFoundation 0x00007fff3704724d -[CFPrefsPlistSource sendMessageSettingValue:forKey:] + 573
5 CoreFoundation 0x00007fff37179feb -[CFPrefsPlistSource alreadylocked_setValues:forKeys:count:from:] + 491
6 CoreFoundation 0x00007fff37106e5b -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:from:] + 219
7 CoreFoundation 0x00007fff3710708a -[CFPrefsSource setValues:forKeys:count:from:] + 26
8 CoreFoundation 0x00007fff371494ff -[CFPrefsSearchListSource alreadylocked_setValues:forKeys:count:from:] + 623
9 CoreFoundation 0x00007fff37106e5b -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:from:] + 219
10 CoreFoundation 0x00007fff3710708a -[CFPrefsSource setValues:forKeys:count:from:] + 26
11 CoreFoundation 0x00007fff371070cf -[CFPrefsSource setValue:forKey:from:] + 63
12 CoreFoundation 0x00007fff3714b629 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 297
13 CoreFoundation 0x00007fff3714b495 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 341
14 CoreFoundation 0x00007fff371713d0 -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:] + 96
15 CoreFoundation 0x00007fff3701a6c5 _CFPreferencesSetAppValueWithContainer + 117
16 Foundation 0x00007fff3911d6b2 -[NSUserDefaults(NSUserDefaults) setObject:forKey:] + 55
17 V2RayX 0x00000001099d600f __29-[AppDelegate saveConfigInfo]_block_invoke + 1185
18 libdispatch.dylib 0x00007fff5ef085fa _dispatch_call_block_and_release + 12
19 libdispatch.dylib 0x00007fff5ef00db8 _dispatch_client_callout + 8
20 libdispatch.dylib 0x00007fff5ef15217 _dispatch_queue_serial_drain + 635
21 libdispatch.dylib 0x00007fff5ef08166 _dispatch_queue_invoke + 373
22 libdispatch.dylib 0x00007fff5ef15f0d _dispatch_root_queue_drain_deferred_wlh + 332
23 libdispatch.dylib 0x00007fff5ef19d21 _dispatch_workloop_worker_thread + 880
24 libsystem_pthread.dylib 0x00007fff5f251fd2 _pthread_wqthread + 980
25 libsystem_pthread.dylib 0x00007fff5f251be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1] 1220 abort 
/Applications/V2RayX.app/Contents/MacOS/V2RayX

**Comment by Alvin9999** [comment]
不用v2rayX客户端，就用原先的v2ray客户端能不能用？

**Comment by hibluesea** [comment]
没找到v2rayX客户端配置文件位置，不过试了下手动输入，总共就5项：ip，端口，uuid,加密方式，传输方式,填一下不复杂。加密方式和传输方式服务端和客户端不完全一致，选2边都能找到的，我选的chacha20(瞎查的说这个比较省电), 传输方式选的mKCP，客户端选的KCP, 测试可用，速度也流畅(也可能是心理作用)，感谢楼主。 另外系统使用的是centos6，网上找了说明 https://blog.mzihen.com/archives/v2ray-on-centos-6-x/，手动添加系统服务就行。这样一台centos6同时跑ss和v2ray，功能正常，有空再试试brook。就差ios版的v2ray客户端，好像还没发现有免费版的，只能去美区花钱买了

**Comment by Alvin9999** [comment]
OK

**Comment by mrdulin** [comment]
同样的问题

**Comment by Alvin9999** [comment]
配置文件config.json 要导入到v2ray客户端，而不是v2rayX
