### ISSUE TITLE
V2RAY教程中的两个加速现在似乎都有问题？

### ISSUE THREAD

**Issue by wjf008** [Alvin9999/new-pac#569]
试图用脚本搭建V2RAY服务器。
使用加速方案1 BBR加速之后，到RESTART服务器那一步，无论用RESTART命令还是在VULTR中RESTART，都会导致该云服务器无法PING到，必须在VULTR中选择“Server Reintall”才能再次PING到。
而使用方案2锐速，则提示：
操作系统：Debian 
发行版本：8 
内核版本：3.16.0-8-amd64 
位数：x64 
锐速版本：3.10.61.0 
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96179  100 96179    0     0  78452      0  0:00:01  0:00:01 --:--:-- 78513

锐速暂不支持该内核，程序退出.自动安装判断比较严格，你可以到http://www.91yun.org/serverspeeder91yun手动下载安装文件尝试不同版本

所以现在两种加速在VULTR的DEBIAN类服务器上都无法使用。该怎么办？

**Comment by Alvin9999** [comment]
可以用centos7系统，这个系统既可以部署ssr，也可以部署v2ray，建议用锐速。
