### ISSUE TITLE
樓主應該在增加一個便攜版

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#57]
樓主應該看看能否用海大這個項目在做個便攜版，這個東西也是基於goa修改的，網頁訪問速度媲美gop比goa快，下載速度與goa媲美比gop快，下載速度俺這裡聯通是1.5-3m。其實ss免費資源還是有限的，最好的方法還是免費的google云服務，可惜很多人太懶惰不想自己去申請google appid。https://github.com/SeaHOH/GotoX/issues

**Comment by Alvin9999** [comment]
嗯，今天研究下

**Comment by Alvin9999** [comment]
你知道在哪里下载吗？

**Comment by caofengzi** [comment]
下面哪個網址。

**Comment by Alvin9999** [comment]
我按照该项目作者提供的使用说明没有配置成功。如果你有成功经验，空了的时候希望你帮忙一下，说下你的经验

**Comment by caofengzi** [comment]
你說的沒有配置成功只是程序沒有成功還是和瀏覽器捆綁沒有成功？如果還像你那幾個集成調用瀏覽器的沒有成功俺無法幫助，因為俺不懂編程，俺猜測應該是用啟動程序然後調用瀏覽器沒有成功吧？你可以和作者交流交流。

**Comment by Alvin9999** [comment]
是程序没有成功，还没有到调用浏览器那一步呢

**Comment by caofengzi** [comment]
這個東西配置和goa差不多，可以把自己的配置放到Config.user.ini裡面，按照俺這個截圖就可以。
![fireshot screen capture 117 - gotox_config_ini at master seahoh_gotox - github_com_seahoh_gotox_blob_master_config_config_ini](https://cloud.githubusercontent.com/assets/13650252/25457891/6f1ac25e-2b0a-11e7-8a66-96d0d26f0038.png)

**Comment by Alvin9999** [comment]
python文件夹你放入了什么，是从官网上下载的python，还是直接用的原版GoAgent里面的内容，如果是后者，具体涉及了哪些文件，要不要重新命名？

前面两种方法我都试了，没法正常运行。

**Comment by caofengzi** [comment]
俺猜測你是下載的源代碼吧？你可以下載作者已經編輯好的程序試試，你無法運行是沒有python的運行庫文件。

**Comment by Alvin9999** [comment]
嗯，之前下载的是源代码，刚下载了正式版，但有点问题，已向作者提问。
