### ISSUE TITLE
翻墙成功后个别网站无法访问，你们有遇到吗

### ISSUE THREAD

**Issue by loverto** [Alvin9999/new-pac#570]
比如这个网站
www.tonymacx86.com

**Comment by AnyWAT** [comment]
正常，貌似没有代理是万能的
![image](https://user-images.githubusercontent.com/37962734/59166278-879c5d80-8b5a-11e9-9896-7a9419414e73.png)

**Comment by loverto** [comment]
那可能是我dns的问题喽？

**Comment by AnyWAT** [comment]
也许，dnscrypt-proxy 路过

**Comment by loverto** [comment]
我手机也无法访问，

**Comment by Alvin9999** [comment]
有的是网站自身屏蔽了某些代理方式

**Comment by loverto** [comment]
怎么确认呢，我现在用的是ssr这种方式

**Comment by Alvin9999** [comment]
如果ssr本身没有问题，那就推测是网站的限制

**Comment by AnyWAT** [comment]
如用了浏览器代理扩展，其图标上有附加数字：未加载资源，手动添加到走代理或直连。。。

**Comment by loverto** [comment]
嗯，我现在用trojan这种方式同样有这个问题，有点无语，这个网站之前访问时没问题的
