### ISSUE TITLE
希望这个项目能一直坚持下去

### ISSUE THREAD

**Issue by AeneasZhu** [Alvin9999/new-pac#572]
今年墙的高度前所未有的增高了，doub.io被抓，用了多年的XX-NET半死不活，大批SSR、SS机场主跑路，自建VPS也不安全了，在国殇日30周年期间，也就只有这个项目依旧坚挺。真心希望这个项目能一直坚持下去。

**Comment by Alvin9999** [comment]
会的

**Comment by lixiansky** [comment]
大部分的都被击沉了~~~

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477

**Comment by AeneasZhu** [comment]
> ✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。[XX-net/XX-Net#12477](https://github.com/XX-net/XX-Net/issues/12477)

可否在油管上发布一个视频？按照上面的操作经常连XX-NET都打不开

**Comment by AnyWAT** [comment]
> 连XX-NET都打不开

控制页 http://127.0.0.1:8085/?module=gae_proxy&menu=status 打不开？

**Comment by AeneasZhu** [comment]
> > 连XX-NET都打不开
> 
> 控制页 http://127.0.0.1:8085/?module=gae_proxy&menu=status 打不开？

隧道的话可以打开，但现在只能在校园网苟活。按照你的方法启动原生以后，控制台就打不开了

**Comment by AnyWAT** [comment]
校园网，没经历。或许原生貌似不适用？

**Comment by AeneasZhu** [comment]
> 校园网，没经历。或许原生模式不适用？

4G和家庭网我也按照你的方法尝试了，还是遇到各种谜之不能打开控制台的情况。离开校园网，隧道都失效了

**Comment by AnyWAT** [comment]
控制页打不开：
1、修改过某些文件，但格式有问题，木有进程 pythonw.exe 或
2、端口被占用。。。

**Comment by AeneasZhu** [comment]
> 控制页打不开：
> 1、修改过某些文件，但格式有问题，木有进程 pythonw.exe 或
> 2、端口被占用。。。

我刚刚又试了一次，避免出现无法挽回的损失我在win10沙盒上测试，做到https://github.com/XX-net/XX-Net/issues/12477上面的第四步（感觉后面几步不是关键），出现如下情况（截图上传不了）
1. IPV6状态：Fail
2. 有效IPV6共有400之多，接近总IP数量（470左右），有效IPv4则20多个
3. 依旧无法连接

**Comment by AnyWAT** [comment]
> 出现无法挽回的损失

对解压即运行的绿色软件，能有神马？

> 在win10沙盒上测试

 没经历，无建议。。。

**Comment by AeneasZhu** [comment]
> > 避免出现无法挽回的损失
> 
> 对解压即运行的绿色软件，能有神马？
> 
> > 在win10沙盒上测试
> 
> 没经历，无建议，不参合。。。

我只是不想在自己常用的XX-NET上测试，之前改原生的时候总是出现打不开的情况，又要重新配置，很麻烦。我做不到原生-隧道随意切换这么熟练。

**Comment by AnyWAT** [comment]
> 之前改原生的时候总是出现打不开的情况，又要重新配置

如果说的是 http://127.0.0.1:8085/?module=gae_proxy&menu=config，其在 data\gae_proxy\config.json 文件内，备份后即保险。
如果说的是 http://127.0.0.1:8085/?module=gae_proxy&menu=deploy，那就大错特错了：无此需求！

**Comment by AeneasZhu** [comment]
> 控制页打不开：
> 1、修改过某些文件，但格式有问题，木有进程 pythonw.exe 或
> 2、端口被占用。。。

好吧，我大概是知道怎么回事了。可能是我周围的网络环境不支持ipv6，所以只能通过隧道。
用你的方法测试了一下，ipv6状态还是fail，有效ipv6从400+下降稳定在336，但依然可以正常访问

**Comment by AnyWAT** [comment]
> 我（周围）的网络环境不支持ipv6

自己电脑有无 IPv6 应很清楚。。。

**Comment by AeneasZhu** [comment]
> > 我（周围）的网络环境不支持ipv6
> 
> 自己电脑有无原生 IPv6 应很清楚。。。

我以为校园网和4G就是原生的。。。。。。今天特意测试了才知道。。。不是原生

**Comment by AeneasZhu** [comment]
> > 我（周围）的网络环境不支持ipv6
> 
> 自己电脑有无原生 IPv6 应很清楚。。。
> 
> ![image](https://user-images.githubusercontent.com/37962734/59194357-5acc6280-8bbb-11e9-8a3c-cafeb2e4c882.png)

在哪看的？

**Comment by AeneasZhu** [comment]
> > 我（周围）的网络环境不支持ipv6
> 
> 自己电脑有无原生 IPv6 应很清楚。。。

![image](https://user-images.githubusercontent.com/44701446/59194766-a8959a80-8bbc-11e9-98b1-d52101a78be7.png)

总后成了这个状态，4G非校园网，能正常访问外网，速度尚可，时常会断一下

**Comment by AnyWAT** [comment]
> 在哪看的？

右键 Win10 托盘图标——网络——”打开。。。设置“——更改适配器选项——左键双击”所用的网络“图标

**Comment by AeneasZhu** [comment]
> > 我（周围）的网络环境不支持ipv6
> 
> 自己电脑有无原生 IPv6 应很清楚。。。
> 

总之还是感谢**AnyWAT **大神指导，让我的XX-NET继续苟延残喘一阵子。

**Comment by AnyWAT** [comment]
> 总后成了这个状态，4G非校园网，能正常访问外网，速度尚可，时常会断一下

貌似是禁止扫描、导入 IP后的临时效果，与 #12455 所述：能自扫描出、导入 IP（不太）有效的结果相距甚远。。。

**Comment by AeneasZhu** [comment]
> > 总后成了这个状态，4G非校园网，能正常访问外网，速度尚可，时常会断一下
> 
> 貌似是禁止扫描、导入 IP后（原生的做法）的临时效果，与 [XX-net/XX-Net#12455](https://github.com/XX-net/XX-Net/issues/12455) 所述：能自扫描出、导入 IP（不太）有效的结果相距甚远。。。

还有什么好办法呢？隧道情况下

**Comment by AnyWAT** [comment]
> 还有什么好办法呢？隧道情况下

 XX-net/XX-Net#12455

**Comment by AeneasZhu** [comment]
> > 还有什么好办法呢？隧道情况下
> 
> 对比、做到 [XX-net/XX-Net#12455](https://github.com/XX-net/XX-Net/issues/12455) 。。。足矣（往往有人并没做全，你说的方法不行呢😥）

用你的方法后非校园网比原来稳健不少，虽然还是有一些问题，但至少能用的下去，看个油管啥的还凑合。校园网比原来更加稳定，速度也更快些
