### ISSUE TITLE
cannot resolve remote server hostname free9999.tk: No such host is known

### ISSUE THREAD

**Issue by Emeryout19** [Alvin9999/new-pac#573]
cannot resolve remote server hostname free9999.tk: No such host is known

is server ok?

**Comment by Alvin9999** [comment]
服务器没什么问题，域名出了问题导致无法正常解析，会尽快解决。

**Comment by Alvin9999** [comment]
服务器没什么问题，域名出了问题导致无法正常解析，会尽快解决。

**Comment by Emeryout19** [comment]
> 服务器没什么问题，域名出了问题导致无法正常解析，会尽快解决。

thanks a lot^_^

**Comment by Alvin9999** [comment]
已发布trojan新版

**Comment by Emeryout19** [comment]
> 已发布trojan新版

nicely done^_^

**Comment by Bruceherring-create** [comment]
> 服务器没什么问题，域名出了问题导致无法正常解析，会尽快解决
the same situation happed in my win10 host  and i download the latest version of trojan, but it does't work

**Comment by Bruceherring-create** [comment]
how to fix that problem

**Comment by Alvin9999** [comment]
@Bruceherring-create 域名要正常添加服务器ip，就不会出现在换个问题了
