### ISSUE TITLE
trojan程序打开后显示 不知道这样的主机 请问是怎么回事？

### ISSUE THREAD

**Issue by fulinyan** [Alvin9999/new-pac#574]

**Comment by Alvin9999** [comment]
域名出问题了，已发布trojan新版

**Comment by fulinyan** [comment]
十分感谢！

**Comment by liao6964799** [comment]
> 域名出问题了，已发布木马新版

新版也有问题啊
![image](https://user-images.githubusercontent.com/35887374/59194648-4dfc3e80-8bbc-11e9-8240-817d77971ec6.png)
直接卡死了
