### ISSUE TITLE
请问服务器IP可以ping通，但是ssh连不上是什么原因啊？

### ISSUE THREAD

**Issue by Ruananx** [Alvin9999/new-pac#575]
如题

**Comment by asker517** [comment]
我这儿ping都ping不通...真操蛋

**Comment by zhangjiuding** [comment]
tcp层级阻断

**Comment by Alvin9999** [comment]
用xshell新建看看

**Comment by asker517** [comment]
@Alvin9999 现在vultr上买的vps为啥都ping不通...

**Comment by floor-cheetah** [comment]
现在vultr的vps都用不了吗

**Comment by Alvin9999** [comment]
@asker517 @floor-cheetah  前几天封的厉害，可以多试试其它不同地区，避开热门区域，比如日本、洛杉矶，多开几个

**Comment by asker517** [comment]
@Alvin9999 非常感谢 大神有木有推荐区域..墙真是烦人..简直没法儿搞开发了

**Comment by asker517** [comment]
@Alvin9999 有没有购买账号渠道 试了好多个都不行..真是受够了

**Comment by Alvin9999** [comment]
没有付费的，可以先用[免费ss/ssr账号](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)

**Comment by AnyWAT** [comment]
> 真是受够了

✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477
