### ISSUE TITLE
现在怎么ip又ping不通了？又有啥情况啊？

### ISSUE THREAD

**Issue by xfgithub** [Alvin9999/new-pac#577]

**Comment by Alvin9999** [comment]
什么ip？我分享的免费账号还是你自己搭建的服务器呢？

**Comment by xiaogu-space** [comment]
是这个免费账号吗
![image](https://user-images.githubusercontent.com/8435230/59494953-dd596880-8ec0-11e9-9ee4-f15866c49149.png)，不能yon用了

**Comment by Alvin9999** [comment]
@xiaogu-space 刚刚更新了一下
