### ISSUE TITLE
大家这两天怎么穿越的?

### ISSUE THREAD

**Issue by WanderZY** [Alvin9999/new-pac#579]
最近IP被蔷了各位大佬现在是怎么玩的?能否分享一波?

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477

**Comment by Alvin9999** [comment]
可以用我分享的免费ss/ssr账号，或者[一键翻墙浏览器](https://github.com/Alvin9999/new-pac/wiki) ，有trojan版、v2ray版、brook版等

**Comment by lewis615** [comment]
试试这个 暂时能用下
撸油管、刷INS、访推特，完美支持高清1080P视频，无任何流量限制 ,真正免费的加速器 https://www.ck66.live/redirect?code=R4JBYRR
