### ISSUE TITLE
vultr的ip地址还有救嘛

### ISSUE THREAD

**Issue by Hc7Hs** [Alvin9999/new-pac#580]
感觉换了好多，没一个能ping通的

**Comment by Alvin9999** [comment]
避开热门区域，比如东京、洛杉矶。先开新的，再删旧的。如果先删后开，那么同一区域开出的还是上一个vps的ip。

**Comment by Hc7Hs** [comment]
> 避开热门区域，比如东京、洛杉矶。先开新的，再删旧的。如果先删后开，那么同一区域开出的还是上一个vps的ip。

我试的新加坡的结点。我也发现了如果先destroy的话新部署的服务器会是一样的ip。然而换了5，6个不同的新加坡IP都ping不通。绝望

**Comment by Alvin9999** [comment]
不要执著于某一个地区的vps，可以尝试不同区域的vps

**Comment by Alvin9999** [comment]
当封锁厉害的时候，某个区域5-6个开不到可用ip属于正常现象，所以要尝试不同区域的vps。

**Comment by lzg217** [comment]
我用新泽西的，便宜，速度也还可以

**Comment by cynen** [comment]
我要是告诉你，我周末测试了接近 $2 的测试vps服务器,都链接不通,我估计你们是不会相信的了.
┭┮﹏┭┮

**Comment by cynen** [comment]
一共 $10 的资金,被我试成了 $7.98 ,我也是无语了

**Comment by Hc7Hs** [comment]
> 我要是告诉你，我周末测试了接近 $2 的测试vps服务器,都链接不通,我估计你们是不会相信的了.
> ┭┮﹏┭┮

换网站吧

**Comment by asker517** [comment]
@cynen 同样遭遇的表示信了...坑死了..没一个能通

**Comment by Alvin9999** [comment]
有的人可以很顺利的开到可用ip，有的人就不行，很可能是各个地区封锁强度不同导致的。如果实在开不了可用ip，可以换其它的，最好是能够免费换ip的，至于其它服务商可以自行网上搜索

**Comment by xfgithub** [comment]
我这边也一样，IP完全ping不通，为毛啊？有知道的人吗 ？

**Comment by yuebanyidiudiu** [comment]
开了10多个，ping通了3，4个，都是300ms左右，丢包率还挺高的

**Comment by yuebanyidiudiu** [comment]
终于明白，充10刀送50刀,那50刀就是给人试的。

**Comment by yuebanyidiudiu** [comment]
> 一共 $10 的资金,被我试成了 $7.98 ,我也是无语了

vultr充10送50，只不过50刀有一个月的使用时间限制。

**Comment by jiechud** [comment]
ip 完全 ping 不通啊
