### ISSUE TITLE
解救VPS

### ISSUE THREAD

**Issue by cynen** [Alvin9999/new-pac#583]
我发现大家都在用vultr....然后我的$10 关测试现在只剩下$7.05了....问题是我还没有测试到一个可用的ip...你就说气不气? 

果断换网站 . 
virmach.com  ，论便宜，其他都是渣啊.... 
我买了一个 $2.5/m 的,加个促销码: LEB30 打骨(7)折 . 实际是$1.75 可以接受.   当然还有 $1.25/m的机器.

**Comment by Alvin9999** [comment]
有的人可以很顺利的开到可用ip，有的人就不行，很可能是各个地区封锁强度不同导致的。如果实在开不了可用ip，可以换其它的，最好是能够免费换ip的
