### ISSUE TITLE
群主，我用你的SSR翻墙翻不了，我的线路是"越南“打不开网页

### ISSUE THREAD

**Issue by yy0535** [Alvin9999/new-pac#585]
群主，我用你的SSR翻墙翻不了，我的线路是越南打youtube打不开，非常的慢,请问，就这一个线路吗？？看到请回复,打扰你啦

**Comment by jacknnnbauer** [comment]
如果是chrome浏览器的话需要 switchyomegra这个插件。

**Comment by Alvin9999** [comment]
账号填写要正确哦，浏览器代理设置对没有？

**Comment by Alvin9999** [comment]
实在用不了，可以用我分享的一键翻墙浏览器，有trojan版、brook版、v2ray版等

**Comment by Alvin9999** [comment]
增加了一个账号
