### ISSUE TITLE
Trojan版

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#588]
Trojan版使用chrome一段时间后会提示版本太旧的红色图标，然后看YouTube的视频网速会慢慢降到100左右，视频就卡住了。。。重启后提示的红色图标消失，网速又会好点😂

**Comment by Alvin9999** [comment]
其它版本有类似的现象吗

**Comment by liao6964799** [comment]
> 其它版本有类似的现象吗
目前我只用过这个版本

**Comment by Alvin9999** [comment]
记录一下频次
你具体用的是哪款trojan版，压缩包名称是什么？

**Comment by liao6964799** [comment]
> 一下记录次频
> 你具体用的的英文哪款木马版，压缩包名称是什么？

最新版的 64位 目前有2次这种情况 我下次截图给你

**Comment by liao6964799** [comment]
> 一下记录次频
> 你具体用的的英文哪款木马版，压缩包名称是什么？

压缩包名称Chrome69_64bit_trojan_2019.6.10.7z，文件大小109.3M。

**Comment by Alvin9999** [comment]
好的

**Comment by Alvin9999** [comment]
最近trojan版表现怎么样？可能是用的人比较多的缘故，时间久了服务器缓存比较大，所以最近加入了每天定时重启服务器1次，以达到及时清理缓存的目的。这样，效果应该会更好点。

**Comment by liao6964799** [comment]
> 最近trojan版表现怎么样？可能是用的人比较多的缘故，时间久了服务器缓存比较大，所以最近加入了每天定时重启服务器1次，以达到及时清理缓存的目的。这样，效果应该会更好点。

我刚刚用了一下，确实速度又上来了，3500 ，可能是这个原因吧，我就说我用的好好的，突然就没速度了，另外那个提示版本太旧的红色图标出现后确实有问题啊，我的鼠标竟然失灵了一会儿！

**Comment by Alvin9999** [comment]
@liao6964799  好的，知道了

**Comment by Alvin9999** [comment]
帮忙测试下新版-[75高内核SSR版](http://108.61.224.82/lib1/Chrome75_64bit_SSR_2019.6.22.7z) 浏览器内核升级到了75。主要测试能否成功翻墙以及浏览器扩展、书签、标签是否存在。

**Comment by liao6964799** [comment]
@Alvin9999 哦

**Comment by liao6964799** [comment]
@Alvin9999  给我下载连接啊

**Comment by Alvin9999** [comment]
点击上方的蓝色字体即可下载

**Comment by liao6964799** [comment]
@Alvin9999 
呵呵 原来点击那个就是下载，我已经下了

**Comment by Alvin9999** [comment]
多多测试下，打开/关闭次数最好3次以上，如果没什么问题，近期就可以升级所有版本的内核了。

**Comment by liao6964799** [comment]
@Alvin9999 
测试了 ，没有问题，开关4次，其他感觉没差别，不过速度还是慢啊
![image](https://user-images.githubusercontent.com/35887374/59961701-ede78f80-950d-11e9-9503-72ad0281e088.png)

**Comment by liao6964799** [comment]
@Alvin9999 
一键退出，也会退出自己装的chrome

**Comment by Alvin9999** [comment]
谢谢你测试和反馈。

由于之前ssr版受干扰比较厉害，加上使用人数很多，单日消耗流量很大，ip容易被封，因此对ssr服务器速度进行了限速。刚刚对速度进行了提升，大概提升了50%左右。

一键退出是关闭电脑的进程，所以会关闭所有打开的chrome，手动关闭就不会存在这个问题。

**Comment by Alvin9999** [comment]
其它版本都已升级内核至75

**Comment by liao6964799** [comment]
@Alvin9999 
我刚刚测试了，ssr稳定在1200-1800，
trojan 速度很快，4000-10000 ，但是偶尔突然会掉下来，特别是晚上，1000左右。

**Comment by Alvin9999** [comment]
晚上是翻墙高峰期，且用的人多，速度会降，正常。

**Comment by liao6964799** [comment]
@Alvin9999  Trojan版 登陆YouTube之后一直提示同步失败，不知道什么原因
![image](https://user-images.githubusercontent.com/35887374/60080255-1b2c7b80-9762-11e9-878e-a64348224ce0.png)

**Comment by liao6964799** [comment]
使用ssr 退出后 正常登陆
![image](https://user-images.githubusercontent.com/35887374/60080975-79a62980-9763-11e9-9a62-e56ea1303502.png)
