### ISSUE TITLE
服务器可以登但是ssr用不了

### ISSUE THREAD

**Issue by baidaren** [Alvin9999/new-pac#589]
服务器可以登但是ssr用不了，卸载重装也不可以，这是为什么呢？

**Comment by Alvin9999** [comment]
如果你能用我分享的免费ss/ssr账号的话，你的电脑及网络环境没什么问题，那么就是你设置的账号有问题。你可以把端口设置为5位数，协议和混淆设置成origin和plain，密码不要有特殊符号，端口不要以0开头。

**Comment by yuebanyidiudiu** [comment]
我也是，我能ping通服务器，服务器能ping通fb，用的ShadowsocksX-NG-R8的客户端，测速也能通，但是无法科学上网。

**Comment by Alvin9999** [comment]
@yuebanyidiudiu 至少说明你的服务器没有被墙，是正常的。你可以从账号着手，可以看下2楼我的建议。

**Comment by baidaren** [comment]
> 如果你能用我分享的免费ss/ssr账号的话，你的电脑及网络环境没什么问题，那么就是你设置的账号有问题。你可以把端口设置为5位数，协议和混淆设置成origin和plain，密码不要有特殊符号，端口不要以0开头。

我照你说的试了还是不行，只能又开了个服务器

**Comment by Alvin9999** [comment]
@baidaren 我分享的免费ss/ssr账号你能用吗？

**Comment by yuebanyidiudiu** [comment]
好方，我用你的方法试过了，还是不得行。
你分享的免费账号，我朋友的客户端一下就OK，但是在我电脑上还是不好使。
在我电脑上，速度都是有的
<img width="607" alt="QQ20190621-142945@2x" src="https://user-images.githubusercontent.com/7090699/59902543-15b4f580-9431-11e9-9aa5-d2d1ff9070de.png">
客户端有个http代理设置，改1080也不好使
<img width="210" alt="QQ20190621-143325@2x" src="https://user-images.githubusercontent.com/7090699/59902779-ba373780-9431-11e9-909b-4092cf29a06e.png">

**Comment by baidaren** [comment]
> @baidaren 我分享的免费ss/ssr账号你能用吗？

可以用的，我自己又装了另一个服务器也是可以用的，就是不知道那台是怎么回事

**Comment by yuebanyidiudiu** [comment]
> > @baidaren 我分享的免费ss/ssr账号你能用吗？
> 
> 可以用的，我自己又装了另一个服务器也是可以用的，就是不知道那台是怎么回事

你的客户端也是博主分享的那个连接下载的么

**Comment by baidaren** [comment]
> > > @baidaren 我分享的免费ss/ssr账号你能用吗？
> > 
> > 
> > 可以用的，我自己又装了另一个服务器也是可以用的，就是不知道那台是怎么回事
> 
> 你的客户端也是博主分享的那个连接下载的么

是的

**Comment by Alvin9999** [comment]
@yuebanyidiudiu 你朋友能用，但是你不能用，推测是你的电脑问题。如果你电脑有杀毒软件或安全卫士等，可以关闭再试试看

**Comment by yuebanyidiudiu** [comment]
@Alvin9999 请问下，这个ss的账号是可以自己设置的么，脚本里面貌似直接输入的密码
<img width="369" alt="QQ20190621-175907@2x" src="https://user-images.githubusercontent.com/7090699/59915070-58d19180-944e-11e9-8cac-9d011b5c511e.png">

**Comment by Alvin9999** [comment]
@yuebanyidiudiu  默认的就是括号里面的，按下回车键就可以，可以不用输入，如果不用默认的就自己输入想要设置的就可以啦

**Comment by yuebanyidiudiu** [comment]
换了个客户端，用的outline，就可以用了。
