### ISSUE TITLE
WARNING - [Apr 28 02:00:10] install root certificate failed, Please run as administrator/root/sudo

### ISSUE THREAD

**Issue by juligalo** [Alvin9999/new-pac#59]
电脑是win10 pro，使用goagent完整版且完全按照说明操作，结果黑框内出现标题所示黄字，请问老哥怎么解决啊？

**Comment by Alvin9999** [comment]
这句话的意思是“安装根证书失败，请以管理员身份运行/根/ ”

先退出杀毒软件，然后根据使用说明导入一下证书，最后右键chrome+.exe选择“以管理员身份运行”

**Comment by juligalo** [comment]
可是我并没有装杀软，系统自带的windows defender也关了，也根据说明导入了证书，还是老样子啊。。。我再重装一下试试

**Comment by Alvin9999** [comment]
嗯。如果尝试了多次还不行的话，可以换其它版本的软件，比如GoProxy版

**Comment by juligalo** [comment]
相同的方法在另一台笔记本上使用完全没问题，真是奇了怪了。那一台系统是win10企业版，我这台用不了的是win10专业版，难道和系统有关系？搞不明白...

**Comment by juligalo** [comment]
GoProxy也是同样的问题

**Comment by Alvin9999** [comment]
有可能哦，如果是同样的网络环境那多半是系统的原因

**Comment by juligalo** [comment]
并不是同样的网络，能正常使用的电脑是公司的，电信网络；不能用的是我家里的电脑，移动网络...

**Comment by Alvin9999** [comment]
如果你想知道是否是网络的原因，需要把你家里的电脑拿到公司去试试看，如果能行，说明是网络的原因而非系统的原因；如果还是不行，那就是系统的原因。

如果你不想测试，你再试试我分享的其它软件，PAC版和GoGo翻墙软件

**Comment by caofengzi** [comment]
可以試試手動能否導入證書。
