### ISSUE TITLE
这两天我用Trojan版速度突然一直不好

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#590]
![image](https://user-images.githubusercontent.com/35887374/59895378-f3ae7980-9416-11e9-9858-ba3d87592431.png)
这两天速度一直都是200-300 看YouTube ，你们都好吗？

**Comment by liao6964799** [comment]
![image](https://user-images.githubusercontent.com/35887374/59895474-56a01080-9417-11e9-90c9-5f1db64684d6.png)

**Comment by Alvin9999** [comment]
有没有用杀毒软件或者安全卫士？

**Comment by Alvin9999** [comment]
杀毒软件、安全卫士、防火墙可以关闭，然后再测试下速度。如果还是慢，说明你目前所在地的网络环境不适合用trojan版，那么建议换其它类型的软件。

**Comment by liao6964799** [comment]
> 杀毒软件，安全卫士，防火墙可以关闭，然后再测试下速度。如果还是慢，说明你目前所在地的网络环境不适合用木马版，那么建议换其它类型的软件。

用的win10再带防火墙和avast 没有安全卫士，使用有七八天了，就是这两天不行了

**Comment by liao6964799** [comment]
@Alvin9999  在敏感时期比较能抗的，推荐一下！

**Comment by Alvin9999** [comment]
国内各个地区封锁强度不一定相同，多备用几款软件吧，比如brook版、v2ray版、SSR版、wujie版、freegate版等

**Comment by liao6964799** [comment]
@Alvin9999  刚刚试了brook版根本连不上谷歌，ip更新成功 了也没用，准备试一下ssr，另外我的ie flash插件异常你能帮我解决吗？在工具加载里启用那个flash插件没用，重置ie没用，重装ie也没用，我真是醉了，
![image](https://user-images.githubusercontent.com/35887374/59919493-24fc6900-945a-11e9-86de-94f9089d89a0.png)

**Comment by liao6964799** [comment]
ssr版也不是很好啊
![image](https://user-images.githubusercontent.com/35887374/59919994-a0aae580-945b-11e9-93db-f2f265e2fa27.png)

**Comment by Alvin9999** [comment]
把防火墙和杀毒软件关了，再尝试下brook版

**Comment by liao6964799** [comment]
> 把防火墙和杀毒软件关了，再尝试下brook版

试过了 ，不行，速度都没有。
Trojan版这两天我这里速度只有300，现在在用ssr，速度在500-1200

**Comment by Alvin9999** [comment]
噢！v2ray版也可以尝试下

**Comment by liao6964799** [comment]
> 噢！v2ray版也可以尝试下
Trojan版到了晚上速度就会降下来，这是使用十几天的感受。
ssr表现稳定，任何时候都是那个速度，但是不快吧。
再次说明  那个 提示版本太旧的 红色图标  对使用有影响的。

**Comment by Alvin9999** [comment]
@liao6964799 好的，谢谢反馈，我已知道。

**Comment by AnyWAT** [comment]
> 在工具加载里启用那个flash插件没用，重置ie没用，重装ie也没用

国内版？非国内版：
FlashPlayer最新版离线安装程序。运行时如自动联网到国内版网址，取消，开启系统代理（或断网后？）再运行即可。
http://fpdownload.macromedia.com/pub/flashplayer/latest/help/install_flash_player.exe
http://fpdownload.macromedia.com/pub/flashplayer/latest/help/install_flash_player_ppapi.exe

**Comment by liao6964799** [comment]
@AnyWAT  
嗯，国内版，我是win10 64 家庭中文版的，说是flash是与系统集成在一起的，直接下载安装可以吗 ？
另外是这两个都要下载吗？

**Comment by liao6964799** [comment]
都要安装？

**Comment by AnyWAT** [comment]
> 直接下载安装可以吗 ？

> FlashPlayer最新版离线安装程序。
。。。。。。

> 都要安装？

貌似后者作用于FireFox

**Comment by liao6964799** [comment]
@AnyWAT  必须要联网才能安装，另外没有跳转什么网页，就是直接安装完成了，这是国际版吗？

**Comment by liao6964799** [comment]
@AnyWAT 
你的ie可以看爱奇艺的视频吗？我刚刚试了一下优酷可以看。。。。

**Comment by AnyWAT** [comment]
> 这是国际版吗？

> 国内版？非国内版：

> 你的ie可以看爱奇艺的视频吗？

> PS：系统市场内的爱奇艺或许没网页版的。。。

**Comment by zhang1122244** [comment]
我也是这两天trojan的速度突然不好了，同个VPS的ssr速度还行，trojan就很差。楼主解决了吗

**Comment by Alvin9999** [comment]
@zhang1122244  没有，trojan这段时间都比较差，这多半是被网络封锁干扰的原因

**Comment by zhang1122244** [comment]
那我就放心了，我刚在香港的GCP又搭建了一个trojan一样的问题，速度很慢。而且youtube可以打开，google不能打开，会提示安全问题google拒绝访问，你有遇到吗？

**Comment by Alvin9999** [comment]
@zhang1122244 没有
