### ISSUE TITLE
神韵晚会哪里看？

### ISSUE THREAD

**Issue by efynn** [Alvin9999/new-pac#591]
请问神韵晚会哪里可以看，链接给的只有30s

**Comment by Alvin9999** [comment]
神韵晚会目前只能在大陆地区以外现场观看，每年的上半年会进行全球巡演且每年都是全新的节目。也就是要出国才能看。如果你感兴趣，可以看这个官网的一些其它视频，比如演员、音乐等的介绍，[地址](http://zh-cn.shenyun.com/videos/latest-videos/#/latest-videos)

**Comment by efynn** [comment]
好哒，抛去别的成分不说，舞蹈还是挺好看的:)

**Comment by Alvin9999** [comment]
每年的大年三十和十五，新唐人会面向大陆地区免费播放神韵晚会，通过自由门和无界软件就能观看。
