### ISSUE TITLE
flash插件异常

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#592]
@Alvin9999 
笔记本 win10的 不知什么时候flash异常用不了了，插件是启动的，可是看网页直播一直提示没有启动，我重装了ie没用，我现在用html5看直播有杂音，难受呀。

**Comment by Alvin9999** [comment]
你是普通浏览器还是翻墙浏览器呢

**Comment by liao6964799** [comment]
用edge和你的chrome有这问题，我自己下载的chrome没问题
现在trojan有点问题，连接很慢

**Comment by liao6964799** [comment]
速度下降好多，是限制了吗？ 只有500
![image](https://user-images.githubusercontent.com/35887374/59972081-285b3600-95bb-11e9-8280-7cfec7bd9256.png)

**Comment by AnyWAT** [comment]
> 用edge和你的chrome有这问题，我自己下载的chrome没问题

系统有更新 flash player，或许会更新到国内版。Chrome 可手动更新：chrome://components/ Adobe Flash Player - 版本： 32.0.0.207

**Comment by Alvin9999** [comment]
@liao6964799 trojan版没有做限速处理。

**Comment by Alvin9999** [comment]
这是其它网友的反馈，trojan版速度不错，7000kbps
![1111](https://user-images.githubusercontent.com/12132898/59985660-5c8b3100-9665-11e9-8af0-48a03234da1c.PNG)

**Comment by liao6964799** [comment]
@Alvin9999  今天早上速度正常了，可能网络原因吧，服务器缓存要及时清理哈
