### ISSUE TITLE
trojan [ERROR] SSL handshake failed with www.free9999.net:443: certificate verify failed

### ISSUE THREAD

**Issue by Emeryout19** [Alvin9999/new-pac#595]
![Untitled](https://user-images.githubusercontent.com/32247328/60358661-4be20e80-9a09-11e9-9136-ad1ab0868bea.png)
![Untitled](https://user-images.githubusercontent.com/32247328/60358799-b85d0d80-9a09-11e9-8752-0f26eff1aaf0.png)
剛才好好的,突然就不行了...

**Comment by liao6964799** [comment]
是的 现在一直连不上

**Comment by Alvin9999** [comment]
trojan版已更新

**Comment by Emeryout19** [comment]
謝謝更新 在用goflyway
