### ISSUE TITLE
为什么我的没有显示额外ID

### ISSUE THREAD

**Issue by s19996** [Alvin9999/new-pac#596]
![PNQK`~I%(D(~LJA )CJF688](https://user-images.githubusercontent.com/52347484/60382681-50560800-9a99-11e9-8cdc-4b25a04eeb09.png)

**Comment by Alvin9999** [comment]
不影响使用，你用原版v2ray客户端即可

**Comment by s19996** [comment]
> 不影响使用，你用原版v2ray客户端即可

我是在K2P里面设置，需要额外ID的

**Comment by Alvin9999** [comment]
这个脚本没有额外ID，如果你换客户端，那么只能在网上寻找其它有额外ID的脚本。
