### ISSUE TITLE
Trojan'是要更新了吗 连接不上

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#597]
@Alvin9999

**Comment by Alvin9999** [comment]
已发布新版

**Comment by liao6964799** [comment]
添加了ip更新，以后也和ssr一样更新方便啦 @Alvin9999

**Comment by Alvin9999** [comment]
嗯嗯，是的哟

**Comment by briancblog** [comment]
@Alvin9999  https://github.com/trojan-gfw/trojan/issues/114
**请问你的 Trojan 这个问题解决了吗？**

我也曾经报告了类似的问题 https://github.com/trojan-gfw/trojan/issues/113，但是被作者关闭了

我这边的 Trojan 确实非常不稳定，有时候非常非常的慢，也是需要 10-20 秒才能打开一个网页，相反 shadowsocks 就很快，只是 Trojan 比 shadowsocks 的抗干扰能力强很多。

我找了好久，但是找不出原因所在。

非常感谢！

**Comment by liao6964799** [comment]
有没有360啥的，腾讯管家。。。我用的没问题，偶尔速度会慢点可能是人多吧 @briancblog

**Comment by Alvin9999** [comment]
@briancblog  你用最新的安装看看。

@liao6964799  他是自己搭建trojan服务器。

**Comment by briancblog** [comment]
@liao6964799 @Alvin9999 
非常感谢你们的回复!
我是自己搭建的 Trojan 服务器，ss 我也是一直自己搭建服务器

没有 360 这样的软件，我明白这些软件的本质

我已经是最新版的 1.12.3 版本了。

你们的速度和 shadowsocks 是一样的速度吗？
**请问如何发 gitHub 私信呢？**

**Comment by Alvin9999** [comment]
@briancblog  issue发不了私信吧，你可以用邮箱和我私自交流kebi2014@gmail.com
