### ISSUE TITLE
vultr vps ssr 电信网络问题

### ISSUE THREAD

**Issue by WIll-Xu35** [Alvin9999/new-pac#598]
请问电信的网使用vultr ssr是不是效果很差

我配置了5台vultr vps，包括japan，singapore，la。但是在公司和家里的电信网络使用的时候，一直出现连不上的情况（包括ssh都连不上，但是可以ping通），偶尔能连上。但是笔记本连移动4g随时都可以使用。请问这有什么解决办法吗？还是说必须换isp或者换带cn2 gia的vps？

谢谢！

**Comment by Alvin9999** [comment]
你可以把端口换为5位数，协议和混淆设置成orgin和plain，然后再试试看。另外，日本、新加坡、洛杉矶属于热门区域，热门区域用的人多，也可以尝试其它非热门区域，非热门区域配置bbr或锐速加速，看视频也会很快。

**Comment by WIll-Xu35** [comment]
@Alvin9999 好的，我尝试一下。之前测试的时候我的协议和混淆都设置成了origin和plain，并且已经配置了bbr。不知道bbr和锐速加速哪个比较好呢？

我选择一下别的位置然后端口更改一下试试。

谢谢！

**Comment by WIll-Xu35** [comment]
@Alvin9999 我尝试将日本的vps端口调整成5位数之后，感觉并没有明显的提升。并且在电信网络下仍然存在一定时间无法使用，并且ssh time out的情况。切换移动4g网络后立即恢复正常使用。

我也尝试使用达拉斯和西雅图的vps，但是开出的ip地址均无法使用外网tcp，所以目前不知道使用别的区域是否能解决问题。我猜测是否是国内电信的网络导致ssr的使用出现不稳定的情况？不知道是否有别的人有遇到过类似的情况？

谢谢！

**Comment by Alvin9999** [comment]
1、基本可以判断是的！国内不同地区封锁强度还不一样，也不能说所有的电信用户都存在这个问题，但目前你自己测试的情况表明，是带宽的原因。
2、你开出的ip是被墙的，如果你要测试，需要不断尝试才行。有的人刚开就能开出好的ip，有的人得不断的尝试才能开出没有被墙的ip。

**Comment by Alvin9999** [comment]
你也可以换不同的翻墙工具，比如搭建v2ray、brook看看，这两种我都有发布教程，也许不同的翻墙工具可以解决你目前遇到的问题，我觉得你可以尝试下。

[自建v2ray服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （很详细，适合新手）

[自建brook服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （很详细，适合新手）

**Comment by WIll-Xu35** [comment]
@Alvin9999 非常感谢！
