### ISSUE TITLE
无法使用ssr问题

### ISSUE THREAD

**Issue by willnotlazy** [Alvin9999/new-pac#599]
你好，我创建的vps服务器，在自己电脑上是ping不通的，在他人电脑上是可以ping通的，并且在其它电脑上搭建好的ssr服务，在自己电脑上是无法使用的，其它小伙伴却是可以使用，之前ssr在自己电脑上用的好好的，突然就这样了，电脑除了win10自带的防火墙和杀毒软件就没有其它的安全软件了，尝试过将端口改为5位、选择非热门地区、更改连接客户端等方式，在自己电脑上均无法使用，其他人电脑可以正常使用，这种现象今年过年的时候就出现了，现在使用v2ray也出现ip在自己电脑上ping不通的情况，被这种情况困扰了很久，可以排除一下原因，给一些建议吗，谢谢大佬了！

**Comment by Alvin9999** [comment]
是有点怪。
1、你把电脑自带的防火墙和杀毒软件也关闭，再试试看。
2、你家里的网络宽带和其它小伙伴是一样的吗？
3、你用自己的手机分别用4g网络和wife能不能使用自建的ssr账号？

**Comment by willnotlazy** [comment]
1.我朋友和我一样使用的系统自带的杀毒软件等， 但是使用ssr没问题
2.一样的
3.4g和wife也不能使用
就很奇怪，要疯了

**Comment by Alvin9999** [comment]
你先不管别人用没用自带的杀毒软件，你现在遇到了问题，需要你自己先排除你自身的杀毒软件和防火墙有没有影响

**Comment by Alvin9999** [comment]
你也测试下我分享的这两个[免费ssr账号](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7) 是否可用，用电脑和手机都测试下。

**Comment by Alvin9999** [comment]
vps服务器可以关闭防火墙，试试看。
相关命令如下：

查看防火墙状态命令：firewall-cmd --state

停止firewall命令：systemctl stop firewalld.service

禁止firewall开机启动命令：systemctl disable firewalld.service

**Comment by willnotlazy** [comment]
好的，等晚些时候我试一下吧，谢谢了
