### ISSUE TITLE
楼主，为什么总是提示用户密码登录？

### ISSUE THREAD

**Issue by sandyplus** [Alvin9999/new-pac#60]
用pac的时候，一直提示登录账号和密码，这是怎么回事？
以前没有出现过的。。

**Comment by Alvin9999** [comment]
如果你用的最新版的电脑PAC版就不存在这个问题，因为已经内置了账号和密码。之所以启用账号验证机制，是因为发现最近服务器被大量的SQ扫描器占用宽带。如果你用的手机端的话，可以手动输入
帐号：root
密码：pac.itzmx.com

**Comment by Jason4774** [comment]
有时候浏览器里面明明设置好了密码，但是有些pac有些时候还是会提示输入密码？这个知道怎么解决吗？谢谢

**Comment by Jason4774** [comment]
@Alvin9999

**Comment by Alvin9999** [comment]
当浏览器刚启动时，浏览器还没有完全加载出来密码，那么会提示。如果密码变化了，那么也会提示。
