### ISSUE TITLE
使用公司网络经常链接不上

### ISSUE THREAD

**Issue by woyaohaohaoxuexi** [Alvin9999/new-pac#600]
你好，我根据教程自己配置的 SSR 服务器，现在有个问题在公司里面经常链接不上。再家里面可以链接。试过切换代理方式，刚更改可以连上，过一会就链接不上了。大佬帮忙分析一下

**Comment by Alvin9999** [comment]
这有很多种可能。
1、公司网络或电脑的限制。比如公司内部网络防火墙限制上外网。
2、不同网络运营商的限制。如果你家里的宽带和公司不一样，那么有可能是宽带类型不同，限制不同造成。

**Comment by woyaohaohaoxuexi** [comment]
1、我在公司使用的是个人电脑，使用谷歌访问助手可以链接。
2、请问下大佬，ssr 的工作方式是不是在本地启动一个服务，然后拦截请求通过127.0.0.1:1080 转发。能不能修改本地服务的地址和端口呢

**Comment by woyaohaohaoxuexi** [comment]
@Alvin9999 我设置 SwitchyOmega 代理为 socks5 模式，打开页面的时候，一直提示  您的连接不是私密连接。没办法打开页面

**Comment by Alvin9999** [comment]
不能修改本地服务的地址和端口，固定的。

**Comment by woyaohaohaoxuexi** [comment]
@Alvin9999  😭我把本地的端口改了，不知道原来设置的是什么了，大佬怎么办。要不要重新装

**Comment by woyaohaohaoxuexi** [comment]
大佬，我 ssr 客户端 本地配置有问题，请问下如何重置或者彻底删除重新下载

**Comment by Alvin9999** [comment]
这个页面的中部有下载地址：https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
