### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#603]
![image](https://user-images.githubusercontent.com/35887374/62003682-4f260280-b14d-11e9-9173-2ad18db25a5e.png)
今天一整天的trojan速度有问题啊

**Comment by Alvin9999** [comment]
![22222](https://user-images.githubusercontent.com/12132898/62015584-6ad9e900-b1df-11e9-82d4-9aa2c01c662e.PNG)
网友截图。

**Comment by liao6964799** [comment]
@Alvin9999 嗯 正常了

**Comment by liao6964799** [comment]
刚刚试了一下又不正常了
![image](https://user-images.githubusercontent.com/35887374/62029143-7e537700-b214-11e9-8e78-63bd8ce9a984.png)

**Comment by Alvin9999** [comment]
有可能是你那里网络波动或封锁波动造成的
