### ISSUE TITLE
android 添加ssr订阅失败？？？

### ISSUE THREAD

**Issue by kugouasd** [Alvin9999/new-pac#604]
为什么 我安卓无法添加ssr订阅地址呀？？

**Comment by Alvin9999** [comment]
哪个订阅地址？

**Comment by kugouasd** [comment]
https://www.ssrtool.com/tool/free_ssr 
添加订阅列表之后，还是显示的默认的订阅地址
![image](https://user-images.githubusercontent.com/32253434/62208475-902a4b00-b3c9-11e9-8d07-082aeb00d78d.png)
![image](https://user-images.githubusercontent.com/32253434/62208479-928ca500-b3c9-11e9-8e08-63e4c86bdbb7.png)

**Comment by Alvin9999** [comment]
重启下手机再试试看。如果还是不行，那我也没办法，因为原来的安卓的ssr开发项目已经停止维护了。

**Comment by Alvin9999** [comment]
可以试着去这里提问https://github.com/shadowsocksr-backup/shadowsocksr-android/issues

**Comment by kugouasd** [comment]
好的，谢谢
