### ISSUE TITLE
请问可以更新一下Brook的配置吗

### ISSUE THREAD

**Issue by momo3030** [Alvin9999/new-pac#606]
北方联通，Brook大概从4天前开始无法使用

**Comment by Emeryout19** [comment]
我家的北方联通是正常的

**Comment by Alvin9999** [comment]
@momo3030 如果关闭了杀毒软件、安全卫士和防火墙以后，Brook版还是无法使用的话，建议换其它软件。

**Comment by Alvin9999** [comment]
从服务器资源消耗看，有很多人正在使用brook版。

**Comment by momo3030** [comment]
@Alvin9999 可以连接至Brook服务器，但是浏览器无法打开网页
检查了一下端口占用和SwitchyOmega的设定，没发现问题😓
其他的软件倒是可以正常使用

**Comment by Alvin9999** [comment]
@momo3030 重新解压再试试看呢

**Comment by momo3030** [comment]
@Alvin9999 不行😓
