### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#608]
提示： 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。这是网络封锁造成的吗？还是服务器不稳定啊？ @Alvin9999

**Comment by GaranYeon** [comment]
作者好像很久没更新了，是不是被喝茶了？

**Comment by GaranYeon** [comment]
作者好像很久没更新了，是不是被喝茶了？@Alvin9999

**Comment by Alvin9999** [comment]
待修复。除了trojan版，其它版本都是正常的，可以换用其它版本。一般来说，只要软件是正常的就不会更新。

**Comment by FremdSprach** [comment]
Trojan version is the best.

**Comment by Alvin9999** [comment]
trojan版会尽快修复。原因是有人使用trojan版下载BT电影（侵权），从而导致服务器被封。

**Comment by Alvin9999** [comment]
已修复。

**Comment by liao6964799** [comment]
> 木马版会尽快修复。原因是有人使用木马版下载BT电影（侵权），从而导致服务器被封。

只看YouTube
