### ISSUE TITLE
征求：你希望下次版本的浏览器背景色是什么颜色？

### ISSUE THREAD

**Issue by Alvin9999** [Alvin9999/new-pac#612]
![背景色](https://user-images.githubusercontent.com/12132898/63732340-610ed880-c8a6-11e9-875b-fcb4d419eccc.png)

白色？蓝色？黑色？灰色？其它颜色？

**Comment by liao6964799** [comment]
这背景颜色可以自己调啊！

**Comment by Alvin9999** [comment]
还是有些人不知道

**Comment by sleeplesslibray** [comment]
随便┐(‘～`；)┌辛苦了 ------------------ 原始邮件 ------------------
发件人: "自由上网"<notifications@github.com>
发送时间: 2019年8月27日(星期二) 下午5:35
收件人: "Alvin9999/new-pac"<new-pac@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Alvin9999/new-pac] 征求：你希望下次版本的浏览器背景色是什么颜色？ (#612)



还是有些人不知道
 
&mdash;

**Comment by Emeryout19** [comment]
淺灰/淺藍/淺黃?
雖然我不用附帶的瀏覽器...
