### ISSUE TITLE
chrome版本问题

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#616]
![image](https://user-images.githubusercontent.com/35887374/64572380-a4cf0b00-d399-11e9-9a15-8c10224c9ae0.png)

又出现了这个提示 ，Trojan

**Comment by Alvin9999** [comment]
不会影响翻墙。目前官方稳定版是76，翻墙版本是75，所以准备再等等，计划77、78的时候再更新。

浏览器版本不想更新太频繁。
