### ISSUE TITLE
号不能用了,现在图片也不显示了

### ISSUE THREAD

**Issue by WangZhonglei** [Alvin9999/new-pac#620]
是不是github也要被审查了? 早上看新闻,说审查法轮功相关的内容

**Comment by Alvin9999** [comment]
已更新

**Comment by WangZhonglei** [comment]
> 已更新

谢谢, 能上了, 习惯了看新闻, 没了这种自由, 突然空虚了

**Comment by hei0323** [comment]
是不是有开始封傻了？备用ss啊网址https冒号//free-ss点site/

**Comment by hei0323** [comment]
标记下https大大的冒号//www.呦涂笔点com/watch?v=ZgH7E_QD1lY
