### ISSUE TITLE
是不是因为临近十一，封锁力度加重了？

### ISSUE THREAD

**Issue by Wakagixsx** [Alvin9999/new-pac#625]
新开的服务器没用几天就被墙了...

**Comment by wqh0109663** [comment]
今天是9 18 刚好今天0点左右 谷歌不能用了 至于是不是十一 可能有影响吧

**Comment by wangcongyi** [comment]
其他的付费 VPN 也是一样，到处在找新梯子...

**Comment by Alvin9999** [comment]
是的。
刚云端更新了v2ray版配置信息，目前Trojan版、v2ray版、goflyway版、ssr版都可以用，使用前记得按照说明更新一下ip，这样才能同步到最新的云端配置。

**Comment by EpicWang** [comment]
是的，我也刚换的IP，又被封了。求解决办法

**Comment by zhangle0403** [comment]
肯定有关系 各种平台的梯子都断了很多

**Comment by chenm1xuexi** [comment]
> 是的，我也刚换的IP，又被封了。求解决办法

你刚搭的在最后一步，有没有出现安装shadowsocketr的时候无法连接到指定的ip + 端口地址的情况

**Comment by WangZhonglei** [comment]
就是十一来临,听人说各个部门都在找绩效呢

**Comment by KAKAROTS** [comment]
自己搭的服务器,怎么更新ip? @Alvin9999

**Comment by Alvin9999** [comment]
@KAKAROTS 如果用的vultr的服务器，重新开新的服务器，删掉老服务器。

**Comment by wqh0109663** [comment]
可以开新的？ 不会被封了吗

**Comment by KAKAROTS** [comment]
不是vultr的服务器,怎么解决,我已经开过好几个服务器试过了 @Alvin9999

**Comment by Alvin9999** [comment]
@wqh0109663 vultr不怕被封ip，因为可以几乎零成本换新服务器

**Comment by Alvin9999** [comment]
@KAKAROTS 最近封锁确实加重了。可以考虑搭建v2ray或者brook。

**Comment by oudafei** [comment]
vultr建一个封一个

**Comment by zwkcoding** [comment]
看到大家都这样，我就不说什么了，默默等待

**Comment by mrdulin** [comment]
我曰，已经严重影响工作了

**Comment by jersonal** [comment]
> @KAKAROTS 最近封锁确实加重了。可以考虑搭建v2ray或者brook。



> @KAKAROTS 最近封锁确实加重了。可以考虑搭建v2ray或者brook。

v2ray 和 brook 有ios版本的软件吗，我用国外apple id 查到很多brook软件，不知道是哪个。

**Comment by Alvin9999** [comment]
@jersonal v2ray有iOS版，名字叫Kitsunebi

**Comment by FreeSlaver** [comment]
真的没撒折腾的必要，都是一路折腾过来的人。
还是用别人的机场把，便宜稳定，撒事都不用操心，<a href="https://user.by.ltd/aff.php?aff=17672">bywave</a>。
你那折腾的几个小时玩会游戏，刷会视频，学习下，它不香吗？
这个机场我18年末用到现在，当初有个套餐是80块钱250gb流量，包终生。
后面遇到3次还是几次故障，只要时间够久都会赔偿，有一次好像是赔偿了100多g。
我就白嫖到了现在，当时冲了100块，现在还有35块余额了。
专业的事情还是交给专业的人干把。
