### ISSUE TITLE
谷歌浏览器Brook版 好像无法使用

### ISSUE THREAD

**Issue by GaranYeon** [Alvin9999/new-pac#629]
如题，更新了IP也无法使用

**Comment by neozhu** [comment]
好像所有的vpn，ssr都无法使用，我花钱买的也不行了，国庆节要到了，开始全面实施封锁了，看来以后翻墙要花更多的钱了。

**Comment by neozhu** [comment]
估计是长城防火墙实施了白名单策略，一切没有备案的国外IP都会被禁止访问。这下翻墙是无望了

**Comment by bajisama** [comment]
> 估计是长城防火墙实施了白名单策略，一切没有备案的国外IP都会被禁止访问。这下翻墙是无望了

别胡扯了，前几个月六四的时候就跟现在一样，风头过了该翻还是翻，他们平时就知道有一堆人在翻墙，人家根本懒得管你，除非是这种敏感时期。你当全面封锁不花钱哪？

**Comment by Alvin9999** [comment]
brook ip很快被墙了，所以brook版要观望一下才会更新。可以换其它类型的软件，比如trojan版、v2ray版、goflyway版。

**Comment by neozhu** [comment]
> brook ip很快被墙了，所以brook版要观望一下才会更新。可以换其它类型的软件，比如trojan版、v2ray版、goflyway版。

肯定直接封锁IP了，现在我这边是所有的代理都不能用了

**Comment by Alvin9999** [comment]
@neozhu 从服务器资源消耗，我分享的trojan版、v2ray版、goflyway版目前是正常的，有很多人在使用。你可以试试看。使用前记得按照说明更新一下ip。

**Comment by neozhu** [comment]
> @neozhu 从服务器资源消耗看，我分享的trojan版、v2ray版、goflyway版目前是正常的，有很多人在使用。你可以试试看。使用前记得按照说明更新一下ip。

我都下了都不行

**Comment by Alvin9999** [comment]
@neozhu 如果你更新ip后还是无法使用，请关闭防火墙、杀毒软件、安全卫士，删掉文件夹，重新解压后再更新ip。

**Comment by neozhu** [comment]
> @neozhu 如果你更新ip后还是无法使用，请关闭防火墙、杀毒软件、安全卫士，删掉文件夹，重新解压后再更新ip。

没有找到哪里有最新的IP地址

**Comment by Alvin9999** [comment]
@neozhu 使用说明（必看）文档里面有一键更新ip配置信息的方法。

**Comment by Alvin9999** [comment]
![333](https://user-images.githubusercontent.com/12132898/65209496-e878f180-daca-11e9-853e-d744ce367e1f.PNG)

**Comment by neozhu** [comment]
请联系 +86 18094270297




在 2019-09-19 10:48:54，"自由上网" <notifications@github.com> 写道：
