### ISSUE TITLE
好久能够把自动获取谷歌IP教程出来啊

### ISSUE THREAD

**Issue by xiebinhqy** [Alvin9999/new-pac#63]
好久能够把自动获取谷歌IP教程出来啊？这样的话，也减少你对这个的维护。。。。

**Comment by Alvin9999** [comment]
已经出来了

**Comment by caofengzi** [comment]
gae ip也就那些了可以自己搜索。以前能夠使用din查找，現在那兩個網站已經被gfw汙染了俺反覆din都是那幾段被汙染的ip。

**Comment by Alvin9999** [comment]
@caofengzi  要不要我给你一些网络上搜集的ip段？

**Comment by caofengzi** [comment]
@Alvin9999 可以啊那樣就非常感謝了。發郵箱吧ip在這裡分享總是感覺不妥。
ziyouminzu617@gmail.com

**Comment by Jason4774** [comment]
![20170710_113545](https://user-images.githubusercontent.com/19594338/28002038-ee717df2-6563-11e7-98ab-35947e786ba8.png)

你好这个ip段你可以分享出来并更新吗？这样大家也可以直接自己用工具如mff扫描，也可以分享一些扫描软件，授人以鱼不如授人以渔。当然只是建议。谢谢。

**Comment by Jason4774** [comment]
![20170710_113545](https://user-images.githubusercontent.com/19594338/28002038-ee717df2-6563-11e7-98ab-35947e786ba8.png)

你好这个ip段你可以分享出来并更新吗？这样大家也可以直接自己用工具如mff扫描，也可以分享一些扫描软件，授人以鱼不如授人以渔。当然只是建议。谢谢。
