### ISSUE TITLE
为什么不把goflyway拆出来

### ISSUE THREAD

**Issue by bbfxier** [Alvin9999/new-pac#635]
把代理软件拆出来，自己可以选择浏览器版本，为什么要弄成集成的呢，自己设置下代理也很简单啊

**Comment by smartnikocj** [comment]
可以拆哦。你在本地浏览器设置下也可以用。

**Comment by bbfxier** [comment]
@smartnikocj 我自己拆开了，用最新版的chrome加goflyway特别爽

**Comment by Alvin9999** [comment]
这个项目一开始就是制作的一键翻墙浏览器
