### ISSUE TITLE
免费账号是不是又挂了

### ISSUE THREAD

**Issue by ChenSiWu** [Alvin9999/new-pac#637]
![9E271A61-7CEC-4C5F-B48B-C2DE5DC5AB0A](https://user-images.githubusercontent.com/12423395/65291017-343ba180-db84-11e9-82bc-752891f8e7a9.png)

**Comment by xihadandan** [comment]
是的！连不上了

**Comment by Alvin9999** [comment]
从服务器资源消耗看，部分人可用。

**Comment by Alvin9999** [comment]
在想办法解决这种容易被封的情况

**Comment by ChenSiWu** [comment]
最近封了好严格，https://vultr.com 的建的服务器都连接不上

**Comment by tanjuntao** [comment]
> 在想办法解决这种容易被封的情况

9/20 19:30免费账号用不了不知道是什么原因。

**Comment by JasonStatham616** [comment]
> > 在想办法解决这种容易被封的情况
> 
> 9/20 19:30免费账号用不了不知道是什么原因。

别说9月20了，9月18就连不上了。

**Comment by Alvin9999** [comment]
试试22日的
