### ISSUE TITLE
Goflyway err_emplty_response 错误

### ISSUE THREAD

**Issue by dilless** [Alvin9999/new-pac#652]
ping测试正常，但使用代理访问网站就会出现ERR_EMPTY_RESPONSE错误。

**Comment by Alvin9999** [comment]
是Goflyway版还是免费Goflyway账号？

**Comment by dilless** [comment]
> 是Goflyway版还是免费Goflyway账号？

是Goflyway客户端+免费账号

**Comment by Alvin9999** [comment]
现在应该可以了吧

**Comment by dilless** [comment]
> 现在应该可以了吧

OK了！THX
