### ISSUE TITLE
v2ray提示“unrecgnized service”，但又提示“服务启动成功”，实际上是启动失败的

### ISSUE THREAD

**Issue by oahnaLiew** [Alvin9999/new-pac#655]
v2ray的脚本，启动服务后，提示“unrecgnized service”，然后又提示“服务启动成功”。
实际上应该是启动失败，无法连接。

**Comment by keirh360** [comment]
同样的情况

**Comment by Alvin9999** [comment]
配置参数是什么？有的参数要有域名才行。

**Comment by weiLanhao** [comment]
> 配置参数是什么？有的参数要有域名才行。

忘了。放弃这个方案了。之前用了别人的脚本，搭起来了也是秒封，就别再祸害人家Vultr的IP了。。。之后用了JustMySocks，效果拔群，简单省事，也不用担心封IP。。。你要不推广一下这个试试。。。
