### ISSUE TITLE
Mac下使用goflyway出现invalid response错误

### ISSUE THREAD

**Issue by hellobiek** [Alvin9999/new-pac#657]
在mac下使用goflyway。出现以下错误

Date: Wed, 25 Sep 2019 20:28:25 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=dc430b5bd7b48aee6191e0fa6fbed0bed1569443305; expires=Thu, 24-Sep-20 20:28:25 GMT; path=/; domain=.lidtsiligud.net; HttpOnly
Cache-Control: max-age=6
Expires: Wed, 25 Sep 2019 20:28:31 GMT
X-Frame-Options: SAMEORIGIN
Server: cloudflare
CF-RAY: 51bfbe967b936e36-SJC

**Comment by hellobiek** [comment]
启动方式为：./goflyway -up="www.free6666.com:8880" -k="dongtaiwang.com" -l=":8100"

**Comment by Alvin9999** [comment]
goflyway.exe -up="cf://服务器地址:端口" -k="密码"

**Comment by ObserverZQ** [comment]
> goflyway.exe -up="cf://服务器地址:端口" -k="密码"

这样在mac下不行啊，显示command not found: goflyway.exe

**Comment by dilless** [comment]
> > goflyway.exe -up="cf://服务器地址:端口" -k="密码"
> 
> 这样在mac下不行啊，显示command not found: goflyway.exe

MAC 哪来EXE 哥哥^-^

**Comment by Alvin9999** [comment]
我的错。参考下window这个命令：goflyway.exe -up="cf://服务器地址:端口" -k="密码"
我没有MAC，解压后看看是哪个程序，修改下

**Comment by jinwyp** [comment]
./goflyway -up="cf://www.free6666.com:8880" -k="dongtaiwang.com" -l=":8100"

**Comment by hellobiek** [comment]
谢谢！
