### ISSUE TITLE
我觉得免费ssr服务器配置有问题

### ISSUE THREAD

**Issue by 308901951** [Alvin9999/new-pac#667]
[https://lncn.org](https://lncn.org) 
这个网站提供的ssr服务器至少3天左右都正常，在我有限的测试中发现youtube,美国之音访问不了，网站前几天有明说推特youtube是封锁的，但是今天推特能访问，youtube还是不行，所以质疑服务器配置有问题

**Comment by Alvin9999** [comment]
主要还是外部大环境封锁加重导致的。不过，可以参考这个配置试试看，他用的2位数的端口，加密方式rc4，另外，youtube禁止了那么服务器访问流量不大，也许是这个原因。
