### ISSUE TITLE
电信 Trojan 疑似被封

### ISSUE THREAD

**Issue by Fun10165** [Alvin9999/new-pac#677]
大约从1小时前开始所有经过Trojan代理的连接均显示
0 bytes received, 517 bytes sent, lasted for 30+ seconds

**Comment by Alvin9999** [comment]
现在呢

**Comment by birdofprey** [comment]
运营商都开始大量封国外IP了

**Comment by Fun10165** [comment]
现在好了，早就应该关闭这个issue了
