### ISSUE TITLE
最新版的brook貌似还是链不上

### ISSUE THREAD

**Issue by GaranYeon** [Alvin9999/new-pac#679]
如题
广东电信

**Comment by Alvin9999** [comment]
可以换其它翻墙软件

**Comment by Alvin9999** [comment]
少数人可以用brook版。推测各个地区封锁强度不一样导致的。

**Comment by Emeryout19** [comment]
完美
![Untitled](https://user-images.githubusercontent.com/32247328/66349637-e7c9d180-e98b-11e9-9bc6-4ce51311fe62.png)

**Comment by Alvin9999** [comment]
@Emeryout19 是自建搭建的brook还是用的我分享的？

**Comment by Emeryout19** [comment]
> @Emeryout19 是自己搭建的brook还是用的我分享的？

你給的啊 謝謝大佬

**Comment by GaranYeon** [comment]
> 完美
> ![无标题](https://user-images.githubusercontent.com/32247328/66349637-e7c9d180-e98b-11e9-9bc6-4ce51311fe62.png)

是不是大佬偏心？

**Comment by Emeryout19** [comment]
@GaranYeon 命令行啓動試試
`brook_windows_amd64.exe client -l 127.0.0.1:2080 -i 127.0.0.1 -s 216.176.190.13:23456  -p ntdtv.com  --http`

**Comment by GaranYeon** [comment]
> @GaranYeon控制台启动试试
> `brook_windows_amd64.exe client -l 127.0.0.1:2080 -i 127.0.0.1 -s 216.176.190.13:23456 -p ntdtv.com --http`

能够具体点说吗？我比较笨

**Comment by GaranYeon** [comment]
> @GaranYeon控制台启动试试
> `brook_windows_amd64.exe client -l 127.0.0.1:2080 -i 127.0.0.1 -s 216.176.190.13:23456 -p ntdtv.com --http`

能够具体点说怎么操作吗？？我比较笨

**Comment by Emeryout19** [comment]
那我还是推荐换用Goflyway版和Trojan版吧,就按教程来,保持更新最新的配置文件,不难的.
brook最近更新比较频繁.

**Comment by GaranYeon** [comment]
> 那我还是推荐换用Goflyway版和Trojan版吧，就按教程来，保持更新的最新配置文件，不难的。
> 布鲁克最近更新比较优先。

或者能否发个链接我学习下

**Comment by Alvin9999** [comment]
@GaranYeon @Emeryout19 问题的关键是，有的人能用brook版，有的人不能用。跟单独使用brook没有关系。

**Comment by Alvin9999** [comment]
今天更新了一下brook，可以试试看

**Comment by GaranYeon** [comment]
感谢老铁无私奉献！
________________________________
发件人: 自由上网 <notifications@github.com>
发送时间: 2019年10月28日 3:37
收件人: Alvin9999/new-pac <new-pac@noreply.github.com>
抄送: GaranYeon <garan1980@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [Alvin9999/new-pac] 最新版的brook貌似还是链不上 (#679)


今天更新了一下brook，可以试试看

―
