### ISSUE TITLE
梯子小白求教-哪种梯子最好用

### ISSUE THREAD

**Issue by jun58** [Alvin9999/new-pac#682]
如题，现阶段哪种梯子最好用

1. ss/ssr
2.v2ray
3.brook

纯小白，望大佬指教

**Comment by jun58** [comment]
接上篇，三种方式都是需要买vps服务器，那最根本的就是服务器ip被强了那就都失效了，所以就变成了，哪种方式配置或者说更换服务器更方便快捷。
另：
现考虑**$3.5**或者**$5**的配置，有没有大概支持几台设备登陆而不卡，毕竟对于那些配置信息不是很敏感，要是能量化一下就好了

**Comment by Alvin9999** [comment]
ip被墙后都没有办法，需要重新开新的服务器。作为初学者，建议选择第1种。

**Comment by Alvin9999** [comment]
服务器配置越高，同时支持的人数越多，至于具体的数值，这个没有办法量化。一般来说，几十个人没有问题。

**Comment by jun58** [comment]
那你发布的免费ss账号的服务器是什么配置的，大约多少人在用

**Comment by Alvin9999** [comment]
4CPU，16G内存，500人
