### ISSUE TITLE
可以ping通vps服务器，但是xshell连不上，怎么办？

### ISSUE THREAD

**Issue by dskl1** [Alvin9999/new-pac#685]

**Comment by Alvin9999** [comment]
是新开的服务器？vps系统是什么？

**Comment by Alvin9999** [comment]
有没有弹出让你输入用户名和密码的界面

**Comment by dskl1** [comment]
是新开的，系统是Debian 8，显示Connection established.但是不弹出输入界面

**Comment by Alvin9999** [comment]
你是想搭建ss还是v2ray还是brook？

**Comment by dskl1** [comment]
v2ray

**Comment by Alvin9999** [comment]
可以重新开服务器换系统，比如centos7

**Comment by dskl1** [comment]
我试了centos7，还是一样问题

**Comment by Alvin9999** [comment]
可能是电脑防火墙的干扰。把自己电脑的防火墙关闭试试

**Comment by dskl1** [comment]
防火墙一直是关着的，之前连vps都是可以的，但昨天被封了ip，今天换了新的ip，就都连不上了

**Comment by Alvin9999** [comment]
哦! 把xshell卸载，重新安装看看

**Comment by dskl1** [comment]
试了，能连接，但是不弹出输入用户名密码

**Comment by dskl1** [comment]
![image](https://user-images.githubusercontent.com/49867691/66626238-0c42d980-ec2a-11e9-9a3f-3a75e4a56d31.png)

**Comment by Alvin9999** [comment]
现在好了吗

**Comment by dskl1** [comment]
我刚试了一下，突然可以了，谢谢
