### ISSUE TITLE
使用Goflyway,报错（之前用的好的，突然出现）

### ISSUE THREAD

**Issue by CodorMonkey** [Alvin9999/new-pac#688]
Microsoft Windows [版本 10.0.18362.418]
(c) 2019 Microsoft Corporation。保留所有权利。

D:\tool\Goflyway>echo off
goflyway.exe -up="cf://www.free6666.com:8880" -k="dongtaiwang.com" -l=":1080" -web-port="8101" -lv=err -g -U=http 
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0

**Comment by Alvin9999** [comment]
账号没问题。有很多人再使用。
可能是防火墙干扰，你把防火墙关闭再试试看，杀毒软件如果有的话也关闭。

**Comment by CodorMonkey** [comment]
都试过了，还是报这个错误；
怀疑是前几天win10更新引起的

**Comment by Alvin9999** [comment]
已经解决了吗

**Comment by CodorMonkey** [comment]
> 已经解决了吗

解决了，经过数次win10更新，又可以用了 amazing...

**Comment by Alvin9999** [comment]
> > 已经解决了吗
> 
> 解决了，经过数次win10更新，又可以用了 amazing...

好的，恭喜你，确实不容易
