### ISSUE TITLE
请问如何处理python命令缺失

### ISSUE THREAD

**Issue by whynotjinx** [Alvin9999/new-pac#689]
目前正在尝试搭建服务器，使用的v2ray的教程，设置过程中出现如下错误：
/usr/local/bin/v2ray: line 100: python: command not found
/usr/local/bin/v2ray: line 101: python: command not found
其他设置也均出现类似错误信息，请教如何修复

**Comment by whynotjinx** [comment]
另外使用ssr的教程时无法启动ssr的错误也相对类似，猜测是同一种问题，日志档案如下：
nohup: failed to run command 'python': No such file or directory
刚开始接触，不知道问题是否得当

**Comment by Alvin9999** [comment]
vps服务器系统选择的是什么呢？不要选择centos8哦

**Comment by whynotjinx** [comment]
> vps服务器系统选择的是什么呢？不要选择centos8哦

嗯确实是centos8的问题，这个解决了谢谢

但是有个新问题，现在服务器搭好了我可以使用（在国外，IP确实已经变更且服务器产生数据）但是我国内的朋友却无法使用，同时只有一个人在尝试连接，请问这个要怎么解决

**Comment by whynotjinx** [comment]
{
  "dns": {
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "66.42.43.74",
            "port": 19068,
            "users": [
              {
                "alterId": 64,
                "id": "8c3b56dc-ed63-11e9-8b18-5600025c5a36",
                "level": 8,
                "security": "chacha20-poly1305"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "kcpsettings": {
          "congestion": false,
          "downlinkCapacity": 100,
          "header": {
            "type": "utp"
          },
          "mtu": 1350,
          "readBufferSize": 1,
          "tti": 50,
          "uplinkCapacity": 12,
          "writeBufferSize": 1
        },
        "network": "kcp",
        "security": ""
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  },
  "stats": {}
}

**Comment by Alvin9999** [comment]
可能是端口被封了，换端口看看

**Comment by whynotjinx** [comment]
是被封了，solved
