### ISSUE TITLE
Goflyway 免费账号版 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by dilless** [Alvin9999/new-pac#691]
Goflyway 免费账号版
今天出现 
ERR_EMPTY_RESPONSE 错误
谢谢！

**Comment by Alvin9999** [comment]
1、有没有用14日更新的账号？
2、防火墙和杀毒软件有没有关闭？

**Comment by dilless** [comment]
> 1、有没有用14日更新的账号？
> 2、防火墙和杀毒软件有没有关闭？

已修复，谢谢
