### ISSUE TITLE
Brook自建:为什么联通宽带上一会就断连，必须重启路由器后才能上，但每次重启后只能坚持几十分钟。我手机联通4G连接brook一直都能上的。

### ISSUE THREAD

**Issue by GoetheXX** [Alvin9999/new-pac#694]
为什么联通宽带上一会就断连，必须重启路由器后才能上，但每次重启后只能坚持几十分钟。(重启路由器的话马上能连上，不重启路由器的话等10分钟左右也能连上)
我手机联通4G连接brook一直都能上的。

Brook自建:
服务器：最新版brook
电脑和手机：最新版brook客户端

**Comment by Alvin9999** [comment]
把电脑防火墙关闭试试
