### ISSUE TITLE
youtube问题请教

### ISSUE THREAD

**Issue by senzhanggz** [Alvin9999/new-pac#7]
youtube登录后无法浏览，首页变成了只剩左上角的youtube标志，视频页面也一样，但是有视频的声音。请教如何解决，goproxy和goagent两个版本都是这个问题，请问是插件的问题吗？

**Comment by Alvin9999** [comment]
我用goproxy登陆帐号后是正常的。目前只有你一个人反应这个情况，应该不是普遍存在的，建议你重新解压，再试试看

**Comment by AdrainZhou** [comment]
我也是 只要登陆Youtube账号就只有左上角的youtube标志，不登账号就可以用

**Comment by Alvin9999** [comment]
@AdrainZhou  用的什么版本？

**Comment by Ahorror** [comment]
为什么视频下到一半就自己停了？

**Comment by Alvin9999** [comment]
你用的哪款软件呢？有可能是你那里的偶尔网络不稳定造成的，遇到这种情况，重新点击下载再看看
