### ISSUE TITLE
請在做一個gop-chrome版本

### ISSUE THREAD

**Issue by caofengzi** [Alvin9999/new-pac#71]
請在做一個goproxy-windows-64位版本的。

**Comment by Alvin9999** [comment]
目前没有这个打算。64位系统可以用32位的软件，且我增加了自动更新goproxy的方法，只要按照方法运行相应的软件就会自动更新64位的goproxy，这样可以减少我维护软件的精力。

**Comment by caofengzi** [comment]
今天訪問youtude出現這個提示請處理一下。We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

**Comment by Alvin9999** [comment]
@caofengzi 正在想办法解决此问题
