### ISSUE TITLE
用不了啊////

### ISSUE THREAD

**Issue by cutedCha** [Alvin9999/new-pac#711]

**Comment by Alvin9999** [comment]
您好，我分享的软件有很多，不知道您说的是哪一款，如果是trojan版，刚已更新。其它版本，比如goflyway版、brook版、ssr版、v2ray版都是正常的。也建议您多备用几款软件，以备不时之需。

购买服务器的钱都是自己的生活费。 

看了您的标题，建议您如果能够翻墙出去，多多了解真相，对您有好处。

**Comment by cutedCha** [comment]
😓我一直以为是李轮子掏钱给你们 自掏腰包挺辛苦的。。。  虽然政治观念不同 但你们加油吧

**Comment by Alvin9999** [comment]
真相与政治无关。叫人退党为了让人远离共产邪恶，“君子不立于危墙之下”。

**Comment by cutedCha** [comment]
不过李轮子我实在喜欢不来。。。。  无意中伤你的信仰 鄙人不信任何宗教 也不喜欢某组织 。
我认为甭管来生前世的活好这辈子才是最重要的。
希望pro主能够有自己的判断能力 。
李轮子说信他得病摸一下就好了 在我看来特别扯.

**Comment by Alvin9999** [comment]
你可以不信，但也要尊重别人的信仰，“真善忍”是教人修心向善的。

**Comment by cutedCha** [comment]
加油

**Comment by Alvin9999** [comment]
好的，祝您一切顺利。

**Comment by Seansun1314** [comment]
有宗教信仰可以，在中国不会禁止你，但是你们胡编乱造颠倒黑白就过分了吧？恶意抹黑他人就过分了吧？！在墙外好好待着吧！

**Comment by Alvin9999** [comment]
@Seansun1314 对人权的迫害没看见吗？不管是历史还是今天，这样的事情仍然在大规模发生。
