### ISSUE TITLE
反华经费不够了吗啊？都不能用了亲！

### ISSUE THREAD

**Issue by lifeneedspassion** [Alvin9999/new-pac#726]

**Comment by Alvin9999** [comment]
Goflyway版、Trojan版、v2ray版、SSR版、brook版、lightsocks版都是正常的，除非你那里封锁特别严重。如果你更新ip后还是无法使用，请关闭防火墙、杀毒软件、安全卫士，删掉文件夹，重新解压后再更新ip。更新ip时，如果ip-1文件无法成功更新ip的话，请运行ip-2来更新ip。
