### ISSUE TITLE
不能使用youtube搜索功能

### ISSUE THREAD

**Issue by kaikaisnow** [Alvin9999/new-pac#73]
打开youtube  显示

We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

**Comment by chengchneg** [comment]
同样的烦恼

**Comment by belinda4869** [comment]
一样的，直接的视频页面地址可以打开，但是up主的页面和个人主页的时候都是上面那样显示的。。。麻烦请给解决一下吧=w=

**Comment by chengchneg** [comment]
拜托！拜托！急啊！晚上还要看郭文贵报平安呢！！狂抓中！！！

**Comment by caofengzi** [comment]
![2017-06-13_202845](https://user-images.githubusercontent.com/13650252/27082001-b1d6ad20-5075-11e7-90a2-401f081ac7e7.png)

**Comment by jacknnnbauer** [comment]
出现同样的问题，如下字段：“... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.”。请求解决。

**Comment by Alvin9999** [comment]
楼上的所有用户可以按照使用说明运行ip更新文件，再试试看。

@caofengzi 你分享的方法我试了，打开YouTube是乱码。

**Comment by caofengzi** [comment]
@Alvin9999 俺就是這樣解決的沒有亂碼問題42行最後一段修改為withgae就解決了。

**Comment by chengchneg** [comment]
俺不懂，这个文件在哪儿？

**Comment by Alvin9999** [comment]
最新解决方法：下载完整版，先按照内核升级方法升级浏览器内核，然后运行ip更新文件。

**Comment by caofengzi** [comment]
@chengchneg 這個設置在porxy.user.ini配置文件裡面。

**Comment by chengchneg** [comment]
Alvin9999 试了还是不行

**Comment by Alvin9999** [comment]
@chengchneg  两款软件都试了没？

**Comment by panmaki** [comment]
goa和gop我都试过了，还是不行啊。希望能解决啊

**Comment by Alvin9999** [comment]
@panmaki  奇怪嘛，有的网友已经反馈可以用GoAgent版了？我想问，你是xp系统吗？内核升级成功没？现在是只有YouTube网站打不开，其它网站正常？

**Comment by chengchneg** [comment]
Alvin9999谢谢！行了。我从新下载的完整版Chrome53_goa_v2017.4.23

**Comment by panmaki** [comment]
Alvin9999  是XP系统，已经升级内核和更新IP了，YouTube网站还是不能打开啊吗，其他网站能正常打开

**Comment by caofengzi** [comment]
gop版在gae.user.json配置文件裡面修改。按照圖片修改。
![2017-06-14_161014](https://user-images.githubusercontent.com/13650252/27121650-c1184e24-511a-11e7-874c-3512d03294eb.png)

**Comment by Alvin9999** [comment]
@panmaki  因为XP系统只能升级到49内核，而win7及以上系统可以升级到53及以上版本，所以我推测49内核目前用GAE服务还是没法打开YouTube。鉴于此，给你两个建议：一是换电脑系统为win7，二是换其它版本，比如PAC版或GOGO翻墙软件等。

**Comment by Alvin9999** [comment]
@caofengzi  嗯，目前GoProxy版的云端配置已经是这样了

**Comment by chengchneg** [comment]
@Alvin9999 又不行了

**Comment by panmaki** [comment]
@Alvin9999 谢谢，已经改用PAC版，能打开youtube网站了，也希望GoAgent版能够更完善

**Comment by chengchneg** [comment]
listen]
ip = 127.0.0.1
port = 8087
username =
password =
visible = 0
debuginfo = 0



[iplist]
google_cn = www.google.cn|www.g.cn
google_hk = www.google.com|mail.google.com|www.google.com.hk|www.google.com.tw|www.l.google.com|www2.l.google.com|www3.l.google.com|www4.l.google.com|www5.l.google.com|mail.l.google.com|googleapis.l.google.com|googlecode.l.googleusercontent.com|maps.l.google.com|code.l.google.com|cert-test.sandbox.google.com
google_talk = talk.google.com|talk.l.google.com|talkx.l.google.com

[profile]
.c.docs.google.com = withgae
.c.pack.google.com = withgae
.c.bigcache.googleapis.com = withgae
dl-ssl.google.com = withgae
dl.google.com = google_cn
play.google.com = withgae
wenda.google.com.hk = withgae
clients.google.com = withgae,noforcehttps
.clients.google.com = withgae,noforcehttps
clients1.google.com = withgae,noforcehttps
translate.google.com = withgae,noforcehttps
mtalk.google.com = direct
talk.google.com = google_talk
talk.l.google.com = google_talk
talkx.l.google.com = google_talk
.google.cn = google_cn
.appspot.com = google_hk,crlf
.google.com = google_hk,forcehttps,fakehttps
.google.com.hk = google_hk,forcehttps,fakehttps
.commondatastorage.googleapis.com = withgae
.googleapis.com = google_hk,forcehttps,fakehttps
.googleusercontent.com = google_hk,forcehttps,fakehttps
.googletagservices.com = google_hk,forcehttps,fakehttps
.googletagmanager.com = google_hk,forcehttps,fakehttps
.google-analytics.com = google_cn,forcehttps,fakehttps
.gstatic.com = google_hk,forcehttps,fakehttps
.ggpht.com = google_hk,forcehttps,fakehttps
.googlegroups.com = google_hk,forcehttps,fakehttps
.googlecode.com = google_hk,forcehttps,fakehttps
.youtube.com = forcehttps,fakehttps
.android.com = google_hk,noforcehttps,fakehttps
tools.android.com = withgae
www.dropbox.com = withgae
.dropbox.com:443 = direct
.box.com:443 = direct
.copy.com:443 = direct
https?://www\.google\.com/(?:imgres|url)\?.*url=([^&]+) = $1
https?://www\.google\.com\.hk/(?:imgres|url)\?.*url=([^&]+) = $1
https?://www\.google\.com\.hk/search\?(.+) = https://www.google.com/ncr#$1
; https?://www\.example\.com/.+\.html = file:///C:/README.txt
; https?://www\.google\.com(\.[a-z]{2})?/($|(search|url|gen_204)\?|(complete|images)/) = google_cn
; https?://www\.youtube\.com/watch = google_hk
; .c.youtube.com =
; .youtube.com = google_hk
; .googlevideo.com =

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
admode = 1
adblock = https://easylist-downloads.adblockplus.org/easylistchina.txt
gfwlist = https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt
expired = 86400

[php]
enable = 0
password = 123456
crlf = 0
validate = 0
keepalive = 0
listen = 127.0.0.1:8088
fetchserver = http://.com/
hosts =

[vps]
enable = 0
listen = 127.0.0.1:8088
fetchserver = https://username:123456@vpsserver.com/

[proxy]
enable = 0
autodetect = 1
host = 10.64.1.63
port = 8080
username =
password =

[autorange]
hosts = *.c.youtube.com|*.atm.youku.com|*.googlevideo.com|*av.vimeo.com|smile-*.nicovideo.jp|video.*.fbcdn.net|s*.last.fm|x*.last.fm|*.x.xvideos.com|*.edgecastcdn.net|*.d.rncdn3.com|cdn*.public.tube8.com|videos.flv*.redtubefiles.com|cdn*.public.extremetube.phncdn.com|cdn*.video.pornhub.phncdn.com|*.mms.vlog.xuite.net|vs*.thisav.com|archive.rthk.hk|video*.modimovie.com|*.c.docs.google.com
endswith = .f4v|.flv|.hlv|.m4v|.mp4|.mp3|.ogg|.avi|.dmg|.iso
noendswith = .xml|.json|.html|.php|.py|.js|.css|.jpg|.jpeg|.png|.gif|.ico|.webp
threads = 3
maxsize = 1572864
waitsize = 524288
bufsize = 8192

[dns]
enable = 0
listen = 127.0.0.1:53
servers = 209.244.0.3|209.244.0.4|199.91.73.222|178.79.131.110|8.8.8.8|8.8.4.4|208.67.222.222|208.67.220.220|168.95.1.1|168.95.192.1|223.5.5.5|223.6.6.6|114.114.114.114|114.114.115.115|2001:4860:4860::8888|2001:4860:4860::8844|2001:470:20::2
blacklist = 0.0.0.0|2.1.1.2|28.13.216.0|4.36.66.178|4.193.80.0|8.7.198.45|8.105.84.0|12.87.133.0|14.102.249.18|16.63.155.0|20.139.56.0|23.89.5.60|24.51.184.0|37.61.54.158|46.20.126.252|46.38.24.209|46.82.174.68|49.2.123.56|54.76.135.1|59.24.3.173|61.54.28.6|64.33.88.161|64.33.99.47|64.66.163.251|65.104.202.252|65.160.219.113|66.45.252.237|66.206.11.194|72.14.205.99|72.14.205.104|74.117.57.138|74.125.31.113|74.125.39.102|74.125.39.113|74.125.127.102|74.125.130.47|74.125.155.102|77.4.7.92|78.16.49.15|89.31.55.106|93.46.8.89|113.11.194.190|118.5.49.6|122.218.101.190|123.50.49.171|123.126.249.238|125.230.148.48|127.0.0.1|127.0.0.2|128.121.126.139|159.106.121.75|169.132.13.103|173.201.216.6|188.5.4.96|189.163.17.5|192.67.198.6|197.4.4.12|202.106.1.2|202.181.7.85|203.98.7.65|203.161.230.171|203.199.57.81|207.12.88.98|208.56.31.43|208.109.138.55|209.36.73.33|209.85.229.138|209.145.54.50|209.220.30.174|210.242.125.20|211.5.133.18|211.8.69.27|211.94.66.147|213.169.251.35|213.186.33.5|216.139.213.144|216.221.188.182|216.234.179.13|221.8.69.27|243.185.187.3|243.185.187.30|243.185.187.39|249.129.46.48|253.157.14.165|255.255.255.255|1.1.1.1|183.207.229.|183.207.232.
tcpover = .youtube.com|.ytimg.com|.googlevideo.com

[useragent]
enable = 0
string = Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3

[fetchmax]
local =
server =

[love]
enable = 1
tip = \u8bf7\u5173\u6ce8\u5317\u4eac\u5931\u5b66\u513f\u7ae5~~

**Comment by Alvin9999** [comment]
刚刚做了一款59内核的GoAgent版，省去了手动升级内核的步骤，麻烦大家测试一下这款新版的使用效果。软件名称Chrome59_GA_2017.6.14.7z  （win7及以上系统才能使用，xp系统不能）

下载地址：http://pan.stnts.com/s/4A5L64v

**Comment by Alvin9999** [comment]
使用方法：下载后解压，然后运行“一键启动.bat”

**Comment by Alvin9999** [comment]
为了能够实现便携版的功能，即解压后翻墙插件及扩展不会丢失，59内核的GoAgent版又做了一次修改，新下载地址：http://pan.stnts.com/s/YBEesLb

目前该版本属于测试阶段，效果好才会正式发布

**Comment by chengchneg** [comment]
@Alvin9999  都试过了，每次换了新版本都可以打开youtube，但退出后就又打不开了。
显示
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

**Comment by Alvin9999** [comment]
@chengchneg  建议你使用PAC版

**Comment by caofengzi** [comment]
可以肯定已經不是goa的問題了，因為俺現在用的還是作者的老版本。

**Comment by Alvin9999** [comment]
@caofengzi  嗯，升级内核至53或以上，同时修改goa即可正常访问YouTube，很多网友反馈正常了。谢谢你的方法。

**Comment by Jason4774** [comment]
你好，请问是什么修改让他扩展不丢失呢？
![20170710_113315](https://user-images.githubusercontent.com/19594338/28001988-9d69a0a6-6563-11e7-8a4e-931ac0117030.png)

**Comment by Alvin9999** [comment]
@Jason4774  没有修改。win7及以上系统使用就可以了。

**Comment by sky8964** [comment]
# 无需翻墙可以直接播放郭文贵视频音频
【追求民主宪政】
https://github.com/sky8964/home/wiki

在右边导航的“郭文贵视频与音频” 栏目 进入
郭文贵视频、音频、文字版

请推广此网站，传播文贵视频、音频，谢谢。
