### ISSUE TITLE
GoQuiet + SSR 教程可以出一个吗

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#733]
如题

**Comment by Alvin9999** [comment]
GoQuiet是混淆插件？

**Comment by V-zhangyunxiang** [comment]
> GoQuiet是混淆插件？

对，混淆插件，能伪装成正常流量，被封的几率很小，类似插件很多，相当于外面套了一层壳

**Comment by Alvin9999** [comment]
[Windows客户端教程](https://github.com/cbeuw/GoQuiet/wiki/Windows%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%95%99%E7%A8%8B)
[GoQuiet折腾记](https://syuez.com/blog/GoQuiet%E6%8A%98%E8%85%BE%E8%AE%B0.html)
[Shadowsocks+GoQuiet setup guide](https://www.youtube.com/watch?v=V9clEjav6zY)

最近没时间研究，你可以参考下上面的教程。
