### ISSUE TITLE
轮子万岁

### ISSUE THREAD

**Issue by bbfxier** [Alvin9999/new-pac#738]
好用的免费翻墙软件都是轮子做的

**Comment by Alvin9999** [comment]
有条件可以多多帮助身边的朋友

**Comment by AnyWAT** [comment]
【转】实际上Github表达与中国合作意愿可能是最近最差消息之一。一旦达成合作，微软会不吝出卖用户和源码给支那政府。凡涉及翻墙工具源码托管、镜像的用户只要人在墙内，都有被捕的危险，这将是一场人道主义灾难。
