### ISSUE TITLE
vimeo.com无法打开，求助，如何解决

### ISSUE THREAD

**Issue by linhai1985** [Alvin9999/new-pac#74]
vimeo.com无法打开，求助，如何解决？youtube什么的都能够打开，就是vimeo打不开

**Comment by Alvin9999** [comment]
请问你用的哪款软件？我分享的软件类型有点多

**Comment by linhai1985** [comment]
我使用的是GoProxy版

**Comment by Alvin9999** [comment]
该网站屏蔽了谷歌ip，GoProxy版和GoAgent版用的是谷歌服务器和谷歌ip，所以没法打开这个网站。如果你很想玩这个网站，可以用PAC版

**Comment by linhai1985** [comment]
好的，非常感谢
