### ISSUE TITLE
PAC用不了了

### ISSUE THREAD

**Issue by sandyplus** [Alvin9999/new-pac#76]
试了下pac和pac5，都用不了了。
我想知道是我的问题，还是这个pac的问题？
你们可以用吗？

**Comment by Alvin9999** [comment]
可以用。你是手机用吗？

**Comment by sandyplus** [comment]
不是手机，是电脑。之前用得好好的，突然用不了了。可能被运营商拦截了。。。

**Comment by Alvin9999** [comment]
用我分享的PAC版试试看https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88

如果不行，还可以选择其它软件https://github.com/Alvin9999/new-pac/wiki

**Comment by sandyplus** [comment]
我是mac系统，有mac的吗？

**Comment by Alvin9999** [comment]
苹果电脑可以用SS客户端，这是详细教程：https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by he1226** [comment]
你好以后能不能出低内核版本的，就出32版本或者49版本的，新版本的浏览器把一些功能去掉了，上有土鳖很难用，没有超级拖拽

**Comment by Alvin9999** [comment]
@he1226 低内核版本的仍然有啊，名字叫53低内核版，主程序是36内核，可以根据自己需求手动升级53或49内核。

**Comment by Alvin9999** [comment]
PAC低内核版本下载地址：https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88

**Comment by he1226** [comment]
你好我用goa和gop打开YouTube都是乱码
你看下面
IQT�~(���F����#d�{L]�SY\��n�̌�6� 6���2������_�g:�{.�͎�7Ȣ��(l)��e�-���`��{k��[�m�~���5/ �i)����[��R��d9{���_����؃�LP ��K��`����0���Z->S����K(աPՍ�wblHG)�!���7l�R������n�����Z>�{�qd���fu]Gf����f�| ��l|����[r�O�[�����$MD�7�'4U�M�{�8Nb�Is��Y-!!���(,�z� F9�\�D�d�2��V�Apݟxc�9?;��/�T�y�Ϗ��siUV�{��!z 
在2017年07月8日 19:49，自由上网<notifications@github.com> 写道：

PAC低内核版本下载地址：https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88

**Comment by Alvin9999** [comment]
@he1226  请看公告。

2017年6月14日公告：谷歌浏览器53低内核GoAgent版和GoProxy版无法上YouTube的解决方法如下：

如果你的电脑是win7及以上系统，下载完整版，先按照内核升级方法升级浏览器内核至53版本，然后运行ip更新文件，两者缺一不可。其次，你还可以用刚发布的谷歌浏览器59高内核版。

如果你的电脑是xp系统，因为XP系统最高只能用谷歌浏览器49内核，根据反馈和测试，目前用GoAgent版和GoProxy版升级到49内核后不能成功打开YouTube。鉴于此，有两个建议：一、换电脑系统为win7或以上系统，这样软件的使用范围会很大；二、如果不换系统的话，可以换其它版本的软件，比如低内核的谷歌浏览器PAC版或Lantern版或GoGo翻墙软件等，又或者火狐浏览器。
