### ISSUE TITLE
这几天什么情况，自建服务器又又又又又被墙了。

### ISSUE THREAD

**Issue by EpicWang** [Alvin9999/new-pac#770]
搬瓦工买的，国庆被墙了一次，换了2个IP，但是国庆完了全部解封了；这次又有什么特殊事件吗，怎么又被墙了？

**Comment by Alvin9999** [comment]
封锁加重。武汉肺炎。

**Comment by 774471872** [comment]
没错，外媒全是黑中国武汉肺炎的，所以封锁加重了

**Comment by Alvin9999** [comment]
@774471872  国内一直在掩盖武汉肺炎真相。到目前为止没有一家国内电视台在全程报道武汉肺炎，为什么？老百姓有权利知道事实真相啊。如果12月份当8名医生披露出肺炎的时候，警察不去抓他们，不当作“谣言”处理，而第一时间公布出来，相信肺炎不会像现在这么严重。可见，信息封锁对这次事件的影响有多大。

**Comment by 774471872** [comment]
> @774471872 国内一直在掩盖武汉肺炎真相。到目前为止没有一家国内电视台在全程报道武汉肺炎，为什么？老百姓有权利知道事实真相啊。如果12月份当8名医生披露出肺炎的时候，警察不去抓他们，不当作“谣言”处理，而第一时间公布出来，相信肺炎不会像现在这么严重。可见，信息封锁对这次事件的影响有多大。

疫情严重主要还是湖北地方政府问题导致，但疫情情况也不是像哪些老外说的那么可怕，什么几百万人感染，武汉出现丧尸，军队枪杀感染者，全扯淡，太离谱了

**Comment by gao409115900** [comment]
刚建的服务器不能用



在 2020-02-04 16:06:57，"774471872" <notifications@github.com> 写道：

@774471872 国内一直在掩盖武汉肺炎真相。到目前为止没有一家国内电视台在全程报道武汉肺炎，为什么？老百姓有权利知道事实真相啊。如果12月份当8名医生披露出肺炎的时候，警察不去抓他们，不当作“谣言”处理，而第一时间公布出来，相信肺炎不会像现在这么严重。可见，信息封锁对这次事件的影响有多大。

疫情严重主要还是湖北地方政府问题导致，但疫情情况也不是像哪些老外说的那么可怕，什么几百万人感染，武汉出现丧尸，军队枪杀感染者，全扯淡，太离谱了

**Comment by 774471872** [comment]
> 刚建的服务器不能用 在 2020-02-04 16:06:57，"774471872" <notifications@github.com> 写道： @774471872 国内一直在掩盖武汉肺炎真相。到目前为止没有一家国内电视台在全程报道武汉肺炎，为什么？老百姓有权利知道事实真相啊。如果12月份当8名医生披露出肺炎的时候，警察不去抓他们，不当作“谣言”处理，而第一时间公布出来，相信肺炎不会像现在这么严重。可见，信息封锁对这次事件的影响有多大。 疫情严重主要还是湖北地方政府问题导致，但疫情情况也不是像哪些老外说的那么可怕，什么几百万人感染，武汉出现丧尸，军队枪杀感染者，全扯淡，太离谱了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可能是巧合，多建几个试试，也许能用几分钟

**Comment by gao409115900** [comment]
测试IP没有被墙，但是现在PING不通了



在 2020-02-04 16:21:04，"774471872" <notifications@github.com> 写道：

刚建的服务器不能用 在 2020-02-04 16:06:57，"774471872" notifications@github.com 写道： @774471872 国内一直在掩盖武汉肺炎真相。到目前为止没有一家国内电视台在全程报道武汉肺炎，为什么？老百姓有权利知道事实真相啊。如果12月份当8名医生披露出肺炎的时候，警察不去抓他们，不当作“谣言”处理，而第一时间公布出来，相信肺炎不会像现在这么严重。可见，信息封锁对这次事件的影响有多大。 疫情严重主要还是湖北地方政府问题导致，但疫情情况也不是像哪些老外说的那么可怕，什么几百万人感染，武汉出现丧尸，军队枪杀感染者，全扯淡，太离谱了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可能是巧合，多建几个试试，也许能用几分钟

**Comment by 1228857713** [comment]
> 离谱

老百姓知道真相有什么用，只会造成恐慌。

**Comment by 774471872** [comment]
是的

**Comment by Alvin9999** [comment]
@gao409115900 如果ip没有被墙，那多半是端口被封了，优先换端口试试。

**Comment by Alvin9999** [comment]
@1228857713 在重大公共安全事件面前，时间就是生命！早知道，早处理，早自我隔离！信息的封锁，会造成多接触，进而造成疫情的蔓延！请站在老百姓生命安全的角度来思考问题。

**Comment by 774471872** [comment]
老百姓不添乱就好了，我们这边很多从武汉回来的也不到医院检查也不自我隔离，到处窜，上面调查来了，他们家人还隐瞒

**Comment by LostKe** [comment]
换了几个端口后直接把ip封了，换ip也一样 o(╯□╰)o

**Comment by Alvin9999** [comment]
@LostKe 如果SSR实在不稳定，可以换v2ray、Brook、Trojan，教程都有的。

**Comment by bsharkl** [comment]
已有两台服务器阵亡，而且不是封端口，是封IP。

**Comment by patentonk** [comment]
@1228857713 
中共把你当成傻逼，你有资格知道真相？

**Comment by Iamyourbaba** [comment]
去tmd的gcd

**Comment by bsharkl** [comment]
不用急着跟换IP，一个月内会解封。
![](http://img.bai-long.cn/img/Snipaste_2020-02-08_22-29-17.png)

**Comment by techbirds** [comment]
+1

**Comment by 774471872** [comment]
估计是第二个14天，封锁又加重了

**Comment by Alvin9999** [comment]
@techbirds @774471872  推荐加密方式rc4

**Comment by lyw6024** [comment]
"我家火着的这么大，都快烧没了，你在这儿看了半天了怎么也不告诉我一声啊"
“我怕你造成恐慌”...

**Comment by bsharkl** [comment]
全面弃用SS SSR吧，最后的堡垒trojan v2ray。

**Comment by bsharkl** [comment]
全面弃用SS SSR吧，最后的堡垒trojan v2ray。
![](http://img.bai-long.cn/img/20200219010727.jpg)

**Comment by 774471872** [comment]
这么看来是不能用了

**Comment by techbirds** [comment]
> @techbirds @774471872 推荐加密方式rc4

试了，只有 rc5-md5。一样。用不了几秒就被封。

**Comment by ghsgz** [comment]
> 
> 
> @1228857713 在重大公共安全事件面前，时间就是生命！早知道，早处理，早自我隔离！信息的封锁，会造成多接触，进而造成疫情的蔓延！请站在老百姓生命安全的角度来思考问题。

重点是官员的迟钝和不作为, 而不是信息的封锁. 信息已然这么开放, 欧美依然开发爆发. 你说的是另一回事罢了.

**Comment by Alvin9999** [comment]
@ghsgz 共产党隐瞒疫情，不仅害老百姓没有心理和实际的预防措施，大量染病。隐瞒疫情信息还欺骗了很多国家。最终的源头是共产党。

**Comment by ghsgz** [comment]
> @ghsgz 共产党隐瞒疫情，不仅害中国老百姓没有心理和实际的预防措施，大量染病。隐瞒疫情信息还欺骗了很多国家，导致瘟疫的全球爆发。最终的祸乱源头是共产党。

中国有没有向世界告知covid19的详细信息，你心里有数。欧美对covid19的无知和傲慢使得当地个别病毒携带者迅速转染给其他公民，政府为了经济依旧不紧不慢的下达防治措施，视欧美公民的生命于不顾。总体来说，每一个爆发点不过都是**当地政府的迟钝和不作为**导致的后果罢了。既然你们是恨国党，在国外好好生活不就完了，喜欢你们理念的人自然回去国外和你们开party的，祝你们安全。😊

**Comment by ghsgz** [comment]
> 
> 
> @ghsgz 共产党隐瞒疫情，不仅害中国老百姓没有心理和实际的预防措施，大量染病。隐瞒疫情信息还欺骗了很多国家，导致瘟疫的全球爆发。最终的祸乱源头是共产党。

傻冒只能删issue自哀了
