### ISSUE TITLE
https证书没有申请成果，本次安装失败

### ISSUE THREAD

**Issue by sophiepeithos** [Alvin9999/new-pac#776]
这个报错是什么原因呢，要买ssl证书？

**Comment by Alvin9999** [comment]
搭建的trojan？

**Comment by sophiepeithos** [comment]
按照你的教程执行的

**Comment by Alvin9999** [comment]
关于申请证书没有成果的处理

可能的原因1：

一些原因导致使用nginx申请证书时出错，要么防火墙端口没开放，要么nginx未正常。建议用最纯净的系统安装。

可能的原因2:

出现这个问题最可能的原因之一是你的同一个域名多次申请证书，导致let’s encrypt官方的限制，同一域名每周最多5次申请。

![](https://www.atrandys.com/wp-content/uploads/2019/10/clipboard.png)

如果你的同一个域名申请了很多此证书，这个处理方法可能有用：更换二级域名，例如原来使用的域名是www.abc.com或abc.com或xyz.abc.com，那么现在你添加一个二级域名解析例如xxx.abc.com，安装时使用这个域名即可。

**Comment by sophiepeithos** [comment]
我就namecheap上买了一个域名，没买证书，需要买是吧？

**Comment by Alvin9999** [comment]
不用买证书

**Comment by Alvin9999** [comment]
证书是申请的

**Comment by sophiepeithos** [comment]
证书的申请是教程里的脚本自动搞定的？

**Comment by Alvin9999** [comment]
是的

**Comment by Alvin9999** [comment]
你可以再尝试下，不行的话可以用二级域名

**Comment by sophiepeithos** [comment]
trojan现在确实能让gfw完全无法识别吗？

**Comment by Alvin9999** [comment]
网络上反馈效果还不错，但这个还需要时间来检验，各个地方封锁强度会不一样

**Comment by cmlzgc** [comment]
我的Trojan已经被封了，重新申请也出现了这个情况。准备再试一次。

**Comment by yanzi1225627** [comment]
如果有这个报错：`It is recommended to install socat first`,可以通过如下命令解决：
```
apt-get update && apt-get install curl -y && apt-get install cron -y && apt-get install socat -y
```
安好socat就可以正常申请证书了。

**Comment by qqktr** [comment]
您好。我的vps也出现了这样的问题。本机同时还跑着个wordpress所以不敢去重装。但是不管域名换成什么依然还是显示没有申请结果
