### ISSUE TITLE
shadowsocks 服务器端接收不到请求

### ISSUE THREAD

**Issue by WIll-Xu35** [Alvin9999/new-pac#779]
使用搬瓦工，centos7，ssr和bbr加速，协议origin混淆plain。

之前因为ip被封，换了ip之后发现仍然无法使用。

更换端口后可以使用一段时间，然后又无法使用了（3台设备都无法使用，ip没有被墙，端口也确认打开，客户端ip端口等信息肯定正确）。于是重装vps，仍然无法使用。

查看服务器上的日志，发现根本没有接收到请求。

请问有没有碰到同样问题的？有没有解决办法呢？

**Comment by Alvin9999** [comment]
ip没有被墙的话，多半是端口被封了。最近封锁强度确实增强了，也可以考虑换其它代理工具，比如v2ray、trojan等。

**Comment by WIll-Xu35** [comment]
@Alvin9999 感谢回复，但是我端口扫描发现端口是开启的，不知道到底是什么原因

**Comment by Alvin9999** [comment]
换v2ray、brook、trojan
