### ISSUE TITLE
GoAgent版、GoProxy版出现了问题

### ISSUE THREAD

**Issue by brainwashing** [Alvin9999/new-pac#78]
我按照‘必看’操作了 跟随chrome启动的程序好像还是提示证书导入错误 请以管理员身份运行 
出错后打开YouTube是这样的界面
![20170616214639](https://user-images.githubusercontent.com/29288641/27229412-22fe9b24-52de-11e7-8644-7154da6b5bf3.png)

**Comment by candy2107** [comment]
您好!
请安装 user agent switcher 
然后切换到安卓版
目前 m.youtube.com 正常
