### ISSUE TITLE
请问有什么免翻墙就可以下载youtube视频的网站吗

### ISSUE THREAD

**Issue by scut-salmon** [Alvin9999/new-pac#782]
请问有什么免翻墙就可以下载youtube视频的网站吗

**Comment by Alvin9999** [comment]
没有，不可能。因为不管怎么弄，youtube这个网站是被墙的。

**Comment by Alvin9999** [comment]
如果是别人做的一些youtube的镜像网站，这个可以，但很难找。而且，如果是搭建这种镜像网站，对服务器的流量消耗会非常大。

**Comment by scut-salmon** [comment]
https://bitdownloader.com/en1/youtube-video-downloader-free-v1我之前一直是用这个网站下载视频的，都挺正常，是因为我以前默认开了vpn的原因吗（最近vpn用不了了）

**Comment by Alvin9999** [comment]
是的。
你可以用我分享的翻墙软件来下载youtube视频哦，那么多，9款软件了，都是免费的。

**Comment by Alvin9999** [comment]
如果不想用一键翻墙浏览器，你还可以用ssr、v2ray、goflyway账号，[项目地址](https://github.com/Alvin9999/new-pac/wiki)

**Comment by scut-salmon** [comment]
谢谢，这些网站果然是翻墙才能下载

**Comment by ccsone** [comment]
@scut-salmon 你好 在吗   想问下    advancedEast 把主干网络VGG16 换成resnet50 的问题，我的qq：805677020 谢谢
