### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by pgz123** [Alvin9999/new-pac#784]
xx活了

**Comment by Alvin9999** [comment]
ipv4 还是ipv6？

**Comment by AnyWAT** [comment]
> xx活了

本来就没S。隧道（ipv6）或原生（ipv4）一直可用。

**Comment by Alvin9999** [comment]
@AnyWAT 大佬，好久不见

**Comment by Alvin9999** [comment]
@AnyWAT 中途GoProxy ipv6有各种问题，所以就放弃了。现在对这个又感兴趣了。你能帮忙把xx-net的一些优化整合到GoProxy，从而复活GoProxy吗？

**Comment by AnyWAT** [comment]
没那本事😭GoProxy 已弃用

**Comment by Alvin9999** [comment]
没事，我慢慢研究下

**Comment by pgz123** [comment]
x大又做了优化， @Alvin9999 你研究研究。

**Comment by Alvin9999** [comment]
@pgz123  OK，谢谢提醒哟

**Comment by pgz123** [comment]
谢谢你，为大家做了这么多。
