### ISSUE TITLE
有木有ipv6的呀？

### ISSUE THREAD

**Issue by StephenAnboer** [Alvin9999/new-pac#79]
好人一生平安，有木有ipv6的呀？

**Comment by Alvin9999** [comment]
已增加IPV6节点https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by Alvin9999** [comment]
我以为把vps服务器的ipv6地址直接弄过来就可以用呢，结果发现不行。给你推荐一个其它网站吧，里面有别人分享的ipv6 ss账号 
网站地址：https://doub.bid/sszhfx/   密码：doub.io
