### ISSUE TITLE
早上的端口已不能使用了

### ISSUE THREAD

**Issue by Bourbon404** [Alvin9999/new-pac#794]

**Comment by MuYunyun** [comment]
我这边新起一个端口 5 分钟就 gg.

**Comment by Alvin9999** [comment]
最近端口被封的厉害，已更新

**Comment by Alvin9999** [comment]
> 我这边新起一个端口 5 分钟就 gg.

试试RC-4这个加密方式

**Comment by newborn2010** [comment]
昨晚突然所有的JJ一齐挂了，不光端口，ip也有被封的。鸡蛋都放一个篮子里不行啊，看来要学习新的把式了

**Comment by Alvin9999** [comment]
v2ray、brook、trojan都可以考虑的
ssr账号的加密方式推荐用rc4
