### ISSUE TITLE
火狐浏览器

### ISSUE THREAD

**Issue by zhongshuiyuan** [Alvin9999/new-pac#796]
你好，火狐浏览器为什么没有高内核版的？有些网站低版本的火狐浏览器访问不了了！

**Comment by Alvin9999** [comment]
因为XP系统支持的火狐浏览器的最后一个版本是52，所以为了照顾XP系统用户，之前没有考虑升级火狐浏览器内核。另外一个原因是不太好制作火狐浏览器高内核版。

有空会再研究下。

**Comment by Alvin9999** [comment]
目前可以用谷歌浏览器高内核版来使用

**Comment by zhongshuiyuan** [comment]
高版本系统目前基本都只有64位，可以不考虑32位

**Comment by bannedbook** [comment]
火狐，是可以自行升级的，想用高版本的。当火狐提示升级时自行升级即可。

**Comment by bannedbook** [comment]
关于32位、64位，
64位系统是可以运行32位程序的，32位系统无法运行64位程序
所以弄一个32位的就可以了

**Comment by zhongshuiyuan** [comment]
我试过自动升级，但失败了

**Comment by bannedbook** [comment]
https://support.mozilla.org/zh-CN/kb/%E8%BD%AF%E4%BB%B6%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5

**Comment by zhongshuiyuan** [comment]
谢谢大佬，升级上去了，直接下载个绿色版的，替换以下就可以了
