### ISSUE TITLE
如何不用软件自带的chrome翻墙？

### ISSUE THREAD

**Issue by rommel123** [Alvin9999/new-pac#8]
我不想用软件里的chrome浏览器，想用自己的浏览器配合软件进行翻墙，请问下这个如何设置呢？

**Comment by senzhanggz** [comment]
每个浏览器都有代理设置的吧，把SwitchyOmega插件里的设置照搬到其他浏览器的代理设置就应该OK了吧。另外现在好多浏览器都支持像CHROME这种扩展插件了，像我的QQ浏览器上面也有SwitchyOmega。

**Comment by rommel123** [comment]
我是电脑小白，能麻烦您说详细点吗

**Comment by rommel123** [comment]
@senzhanggz

**Comment by 349205055** [comment]
360浏览器安装插件，和谷歌浏览器一样翻墙，就是把谷歌的那个插件复制过来用就行了。
![default](https://user-images.githubusercontent.com/30136196/29003051-18c5dda8-7ae2-11e7-8465-a6f276f6ebec.PNG)
