### ISSUE TITLE
V2ray免费的账号用不了了。。。。

### ISSUE THREAD

**Issue by xxdbd** [Alvin9999/new-pac#802]

**Comment by Alvin9999** [comment]
最新的账号服务正常。你检查下是否用的最新的账号以及帐号信息是否填写正确。

**Comment by xxdbd** [comment]
![image](https://user-images.githubusercontent.com/44439592/74702947-9e956280-5246-11ea-87d7-25efba223c96.png)
我在测试服务器真连接延迟时说连接超时，Tcping 和ping都能通，在浏览器用不了，之前都能用

**Comment by xxdbd** [comment]
请问一下这个怎么解决

**Comment by Alvin9999** [comment]
确定账号没有填写错吗，刚刚检测了下，服务是正常的。

**Comment by xxdbd** [comment]
我想问一下我圈到的部分是干什么用的，填写账号信息的时候没用到

**Comment by xxdbd** [comment]
![image](https://user-images.githubusercontent.com/44439592/74704549-b91e0a80-524b-11ea-9312-c2fc6cc3fa82.png)
我想问一下这部分是干什么用的，填账号信息这部分没用到

**Comment by Alvin9999** [comment]
v2rayN客户端复制那个vmess地址可以直接导入账号信息

**Comment by Alvin9999** [comment]
防火墙和杀毒软件关闭试试看呢

**Comment by xxdbd** [comment]
![image](https://user-images.githubusercontent.com/44439592/74704934-12d30480-524d-11ea-9163-0174eddd29ca.png)
连上了，是代理的端口出问题了，你教程里说的1080端口连不上，用v2ray客户端下面显示的端口连上了

**Comment by xxdbd** [comment]
![image](https://user-images.githubusercontent.com/44439592/74705128-c2a87200-524d-11ea-86f4-1883a4c48709.png)

我用这个端口就连上了

**Comment by Alvin9999** [comment]
教程是自建服务器，默认的1080端口。而我分享的账号把客户端端口改成了10808。

**Comment by Alvin9999** [comment]
能用了就好。

**Comment by xxdbd** [comment]
谢谢
