### ISSUE TITLE
国家信息安全中心提醒您：关闭杀毒软件的行为有可能被非法劫持！

### ISSUE THREAD

**Issue by longfly04** [Alvin9999/new-pac#806]
追求自由本没有错，是人类天性，但是把追求自由的灵魂和暴力、反动、极端主义以及邪教绑定起来，是人类历史的退步。
恶意丑化和渲染历史，并不是真正的历史，一个真正对社会有用的人，也不会在这些低级无聊的新闻、舆论、资讯中迷失。
历史会选择真理，就像几千年的文化沉淀，糟粕终究会被时间洗刷干净。

**Comment by Alvin9999** [comment]
![9999](https://user-images.githubusercontent.com/12132898/74703760-2da37a00-5249-11ea-9ea0-62b6cf0743c5.png)
