### ISSUE TITLE
解压出错

### ISSUE THREAD

**Issue by 00001liufei** [Alvin9999/new-pac#809]
下载尝试了一下所有的压缩包，解压出现两种错误：1、无法作为压缩包打开文件；2、数据错误。
解压软件用的是7z-1902。
请问如何解决？

**Comment by Alvin9999** [comment]
谢谢反馈，新版本已经拿掉了，可以重新刷新页面下载上一个版本的，问题还在研究中

**Comment by momo3030** [comment]
@Alvin9999 前几天下载64位skyzip版的时候也遇到解压出错的问题，chrome.exe所在文件夹内的4个文件损坏，用的是7z解压。32位版本可以正常使用

**Comment by Alvin9999** [comment]
@momo3030 好的，谢谢反馈。64位skyzip会重新上传。64位其它软件正常么？

**Comment by momo3030** [comment]
@Alvin9999 2月12日发布的版本全部正常

**Comment by Alvin9999** [comment]
@momo3030 刚刚发布了新版

**Comment by momo3030** [comment]
@Alvin9999 可以正常使用，感谢更新

**Comment by Alobe007** [comment]
可以解压了。一切正常。非常感谢。

**Comment by Alvin9999** [comment]
@momo3030 @Alobe007 好的

**Comment by Alvin9999** [comment]
@momo3030 @Alobe007 方便的话，帮我测试下现在网盘下载文件的速度怎么样

**Comment by Alvin9999** [comment]
现在测试一下，晚上再测试一下。晚上是高峰期。
