### ISSUE TITLE
18号更新的两个免费账号是不是不能用了？

### ISSUE THREAD

**Issue by shanzemin** [Alvin9999/new-pac#811]
我下载了最新的ssr客户端，好像无法访问谷歌？

**Comment by Alvin9999** [comment]
2个服务都是正常的哦，你看下账号信息填写正确没有

**Comment by tuuzhang** [comment]
表示还能用，就是速度很慢

**Comment by Alvin9999** [comment]
> 表示还能用，就是速度很慢

最近封锁很严重，尤其ss账号被干扰的厉害，断流很厉害。有空也可以尝试其它的翻墙方式，比如v2ray、brook等

**Comment by zleiwang** [comment]
能用，翻出去了，又上不去百度了，感觉还是ss客户端多一些，还是留一个ss账号好

**Comment by shanzemin** [comment]
> 2个服务都是正常的哦，你看下账号信息填写正确没有

谢谢，可能是我操作问题
