### ISSUE TITLE
ipone 客户端 potatso lite

### ISSUE THREAD

**Issue by xrkffgg** [Alvin9999/new-pac#817]
加密选项没有 rc-4 
是不是因为我的版本不是最新的，还有没有其他能 APP 有rc-4 的加密方式呢

**Comment by Alvin9999** [comment]
用shadowrocket，有离线[安装ipa文件教程](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6)
