### ISSUE TITLE
全新版已发布

### ISSUE THREAD

**Issue by Alvin9999** [Alvin9999/new-pac#819]
相比较之前要下载多款软件，现在只需要下载一款就相当于下载了8款软件，理论上应该是会更方便点。了解下大家实际的使用效果和体验。

**Comment by neunundneunzig** [comment]
任务栏总会留一个bat的窗口在
多任务工作的时候比较不方便

另外对于想用自己自定义了插件chrome的话
用SwitchyOmega不确定是要切换在哪个项目上
系统代理？
之前有一个白名单的pac https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac 貌似可用

**Comment by GaranYeon** [comment]
Brook连不上，新旧都一样。

**Comment by Alvin9999** [comment]
@neunundneunzig 全新版不适合SwitchyOmega

**Comment by Alvin9999** [comment]
@GaranYeon brook目前的方式极容易被封，在研究新的加密协议

**Comment by neunundneunzig** [comment]
而且之前的工具可以检测延迟看是不是挂了
现在没这个选项，不知道究竟是速度比较慢还是根本连接超时了

**Comment by GaranYeon** [comment]
@Alvin9999  能否把几个软件的启动文件整合成一个，打开后用数字选择其中想打开的软件。
然后IP默认每次打开自动更新。谢谢！

**Comment by neunundneunzig** [comment]
还有个问题，就是固定到任务栏的chrome图标如果在开启软件后点击
chrome就会在新的task里打开而不是在固定在任务栏中的chrom图标上打开
导致每次都会出现两个chrome图标
很烦

**Comment by Alvin9999** [comment]
@neunundneunzig 没明白

**Comment by AnyWAT** [comment]
貌似：任务栏的chrome图标仅仅是启动chrome的（图标），它没有管理已打开或即将打开的任何chrome窗口。
