### ISSUE TITLE
youtube 不能传视频 谁能教教我

### ISSUE THREAD

**Issue by fiyin-cc** [Alvin9999/new-pac#82]
一上传就显示An error has occurred while sending data over the network. Please check your network connection and try uploading again.  要么就是没有速度 已经更新了浏览器，网速也正常，不知道怎么回事啊

**Comment by Alvin9999** [comment]
用的哪款软件

**Comment by fiyin-cc** [comment]
Chrome59_GA_2017.6.27 这个版本

**Comment by Alvin9999** [comment]
运行一下ip更新文件，然后再试试看，如果不行的话，说明这款软件不适合上传youtube视频，那么可以换其它类型的软件，比如GoProxy版，PAC版等。
