### ISSUE TITLE
SSR最近免费账号 还是登陆不进去

### ISSUE THREAD

**Issue by ChenSiWu** [Alvin9999/new-pac#823]
不知道是不是我配置的不对。还是被限制了。

**Comment by Alvin9999** [comment]
第二个试了没

**Comment by ChenSiWu** [comment]
目前2个都试过了。好像都不行。顺便问下。你说的RC4加密 就是 rc4-md5加密吧，工具里只有这个一个rc4

**Comment by Alvin9999** [comment]
不是。RC4和RC4-md4是2种不同的加密方式。SS客户端没有，你要用SSR客户端，页面上有下载地址，可以进行下载。

**Comment by ChenSiWu** [comment]
好的，谢谢
