### ISSUE TITLE
为什么不能改进你们的专业软件？

### ISSUE THREAD

**Issue by jdfq** [Alvin9999/new-pac#83]
ss IP、配置等经常变化，手动获取不方便。你们的无界、自由门就不能改进吗？现在还比不上这临时的ss。

**Comment by Alvin9999** [comment]
由于使用人数很多，SS需要不定期更换端口或密码，以保证服务器质量和账号速度。

无界和自由门不是这个项目开发的，如果你有建议，可以去动态网或者无界网反馈。

如果你想稳定流畅的翻墙上网，且对看视频速度要求较高，建议你用[一键翻墙浏览器](https://github.com/Alvin9999/new-pac/wiki)。
