### ISSUE TITLE
刚买的 IP 用了不到一天端口被封

### ISSUE THREAD

**Issue by V-zhangyunxiang** [Alvin9999/new-pac#832]
我昨天刚买的 VPS，搭好 SSR 用了一天，今天用手机连 SSR 不到 5 分钟，端口就被封了(IP 能 ping 通)，之前也出现过这种情况

是手机 SSR 什么地方配置有问题吗？为什么会封的那么快？

**Comment by Alvin9999** [comment]
最近封锁严重，端口被封了，你先换下端口，然后加密方式设置为rc4，协议和混淆设置成origin和plain

**Comment by V-zhangyunxiang** [comment]
> 最近封锁严重，端口被封了，你先换下端口，然后加密方式设置为rc4，协议和混淆设置成origin和plain

原本就是 origin、plain；刚才我把加密换成 rc4，端口换成了 22 还是不行，用 22 是因为试了很多只有 22 是开启的

**Comment by Alvin9999** [comment]
把vps防火墙关闭，端口就全部开放了

**Comment by Alvin9999** [comment]
查看防火墙状态命令：firewall-cmd --state

停止firewall命令：systemctl stop firewalld.service

禁止firewall开机启动命令：systemctl disable firewalld.service

**Comment by V-zhangyunxiang** [comment]
> 查看防火墙状态命令：firewall-cmd --state
> 
> 停止firewall命令：systemctl stop firewalld.service
> 
> 禁止firewall开机启动命令：systemctl disable firewalld.service

firewall-cmd --state

**Comment by V-zhangyunxiang** [comment]
换了一个端口突然好了
