### ISSUE TITLE
套CDN无法使用

### ISSUE THREAD

**Issue by WIll-Xu35** [Alvin9999/new-pac#839]
现在使用的是v2ray的ws+tls，能正常使用但还是怕被封。

尝试套cdn，但是没有成功。在godaddy上面已经把域名的dns服务器改成cloudfare了。但是cloudfare里一旦把子域名的dns only变成proxy就没法使用了，请问这是为什么呢？

还是说cdn一定要搭配nginx这种web服务一起用？

谢谢！

**Comment by Alvin9999** [comment]
是的，要用nginx来转发数据。你用我教程最后面那个高阶篇中的脚本来搭建

**Comment by WIll-Xu35** [comment]
这个脚本会自动给域名来申请并且配置证书是吗？

然后套用cdn的话会更有效的对抗封锁是吗？如果只用ws+tls是不是风险也相对比较高？

非常感谢

**Comment by Alvin9999** [comment]
是的，脚本自动申请证书并续签，很方便。ws tls都是数据加密，安全。套cdn后会更能保护ip。

**Comment by WIll-Xu35** [comment]
了解了，谢谢！
