### ISSUE TITLE
goproxy的github网站怎么没有内容了？

### ISSUE THREAD

**Issue by Jason4774** [Alvin9999/new-pac#84]
1.goproxy的github网站怎么没有内容了？请问你知道怎么回事吗？
2.请问我用goproxy设置成0.0.0.0:8087然后共享给手机上网，但是却用不了，请问怎么goproxy共享给手机上网呢？

**Comment by Alvin9999** [comment]
[主页](https://github.com/phuslu/goproxy/tree/master)

**Comment by Alvin9999** [comment]
第二个问题我不会。

**Comment by Jason4774** [comment]
![20170707_194504](https://user-images.githubusercontent.com/19594338/27956555-f69214ce-634c-11e7-8689-5c86e5e52375.png)
我的意思是不提供下载了，你新版在哪里下载

**Comment by Alvin9999** [comment]
![1](https://user-images.githubusercontent.com/12132898/27956829-1661738e-634e-11e7-8958-2f237ee24bdb.PNG)
这里下载的，如图

**Comment by Jason4774** [comment]
谢谢你的回复。
