### ISSUE TITLE
减少封杀的一个方法

### ISSUE THREAD

**Issue by ninibay** [Alvin9999/new-pac#840]
目前来看，git上的SSR代理IP三五天就会被封杀，而且速度奇慢，为此我想了个新方法，但未经验证，如果可以建议你们尝试一下，就是在国内找一个主机当SSR Client单独连接国外SSR Server，国内翻墙用户连接SSR Client，这样应该能减少被封杀的可能性。如下图
![新方法](https://user-images.githubusercontent.com/30041343/76611148-080e4580-6555-11ea-9dbd-cb1385ac1e09.png)

**Comment by Alvin9999** [comment]
有心了。根据反馈，ssr确实慢，因为被干扰的严重。建议换用v2ray，速度要快很多。

**Comment by Alvin9999** [comment]
你说的这个方法，国内主机ip被封了也一样的。

**Comment by Alvin9999** [comment]
用户连接主机的数据还好，但是主机连接国外用ssr也是一样的，和之前区别不大。

**Comment by ninibay** [comment]
单个IP点对点过防火墙应该还好，我之前自建自己访问，很长时间都没被封。
还有就是可以用日本等非英语国家IP，被审查的可能性小，因为语言不通用不会审查那么严

**Comment by hubsocks** [comment]
@ninibay 你说的方法很多人在用了.由于本机外网没直接连境外vps供应商,被封几率小,但是公开用国内ip做前置代理,危险.自己用就另论了.
