### ISSUE TITLE
vultr的新加坡和日本两个地区的不能用

### ISSUE THREAD

**Issue by daaaaaaaaaaa** [Alvin9999/new-pac#845]
都是centOS6，后来部署了法兰克福的centOS7才行

**Comment by Alvin9999** [comment]
搭建的什么？ss、v2ray，还是其它的？

**Comment by daaaaaaaaaaa** [comment]
> 搭建的什么？ss、v2ray，还是其它的？

SS

**Comment by daaaaaaaaaaa** [comment]
> 搭建的什么？ss、v2ray，还是其它的？

XSHELL连不上，也PING不通

**Comment by Alvin9999** [comment]
那是因为ip被墙了，你开到的是一个被墙的ip

**Comment by daaaaaaaaaaa** [comment]
> 那是因为ip被墙了，你开到的是一个被墙的ip

连续三四个都是？

**Comment by Alvin9999** [comment]
是的，当封锁很墙的时候，会有这种情况发生。

**Comment by chen510260x** [comment]
ss最近很不稳，V2RAY虽然还行，也难免被封。
昨天开了V2RAY，速度还不错，但今天中午就被封了，XSHELL完全连不上。我中午另外新开了，现在还行，都不知道后面会不会有问题

**Comment by daaaaaaaaaaa** [comment]
最近咋回事

**Comment by Donguapi** [comment]
我开了10个日本vps，只有2个能用，而且都会丢包25%-50%。

**Comment by Alvin9999** [comment]
@Donguapi 亚洲的vps用的很多。可以选择美国西海岸的服务器。

**Comment by Alvin9999** [comment]
@chen510260x  ss推荐用rc4加密方式，协议和混淆选择origin和plain。

**Comment by daaaaaaaaaaa** [comment]
> @Donguapi 亚洲的vps用的很多。可以选择美国西海岸的服务器。

用过西雅图的，感觉速度比较慢

**Comment by zxh95320** [comment]
我用的ssr，有时候能ping通，有时候不行。

**Comment by MiaoWu-T** [comment]
墙现在检查有搭建ss和ssr脚本的服务器直接墙，但是仍能ping通 建议用v2ray了现在 而且东京和新加坡的服务器之间搭梯的人太多了，大多数IP都被ban了，能连上的也不稳定，丢包率很高
