### ISSUE TITLE
wiki里文昭谈古论今那个频道不要推荐了，就一垃圾，为了黑中国而黑中国

### ISSUE THREAD

**Issue by lzm1988** [Alvin9999/new-pac#847]
wiki里文昭谈古论今那个频道不要推荐了，就一垃圾，为了黑中国而黑中国

**Comment by onepow** [comment]
夏虫不可语冰， 井蛙不可说海

lzm1988 <notifications@github.com> 于2020年3月22日周日 下午11:42写道：
