### ISSUE TITLE
你好，请问Chrome看不了youtube视频是什么情况

### ISSUE THREAD

**Issue by nickcarter8317** [Alvin9999/new-pac#85]
就Chrome看不了，火狐可以看，我PAC，GAE，SS，都试过了，youtube均打不开
想对的，使用任何工具火狐都非常流畅。
我去贴吧看了看，很多人都有这问题，说是关闭QUIC，我关闭了，但没用。
试过几个SS，都是这副样子，我没辙了。是不是CHROME最近动了什么手脚呢？
![qq 20170707181115](https://user-images.githubusercontent.com/13479039/27953959-5e37568c-6340-11e7-845f-5c56a92a3332.jpg)

**Comment by nickcarter8317** [comment]
不好意思，发完贴，去微博搜索了一下，说是油管开始打击adblock类似的软件了，我把adblock和adblock plus都关了，结果视频就能打开了。

**Comment by Alvin9999** [comment]
好的，知道了
