### ISSUE TITLE
SSR客户端链接不了脚本

### ISSUE THREAD

**Issue by lovelyzzc** [Alvin9999/new-pac#862]
我的服务器能用xshell链接，打开ssr脚本查看连接信息，没有任何链接。试过重新安装服务器，重新安装脚本，ssr客户端也重新下载了，但是还是没有用，我觉得是客户端的哪里出现了问题，而且我是在使用过程中突然断开了链接，然后怎么都不能用了.有没有大佬帮帮忙呀

**Comment by happy1234367** [comment]
要是自己用，既然研究ssr的时间都有了，不如安装trojan效果好

**Comment by lovelyzzc** [comment]
刚刚接触，不是很了解，谢谢提醒

**Comment by Alvin9999** [comment]
可能是端口被封了，换下端口。另外加密方式推荐RC4，协议和混淆设置为origin和plain。
