### ISSUE TITLE
#goflyway trojan v2ray都不能用了

### ISSUE THREAD

**Issue by mygithubyc** [Alvin9999/new-pac#865]

**Comment by Alvin9999** [comment]
有没有更新ip？

**Comment by Alvin9999** [comment]
goflyway1和2 brook2可用

**Comment by Alvin9999** [comment]
v2ray1和2都是正常的

**Comment by Alvin9999** [comment]
trojan1和2 brook1已修复

**Comment by Alvin9999** [comment]
都已正常

**Comment by zhaoruihao** [comment]
我这边昨天brook还可以用，其他的用不了，今日所有的都用不了，更新ip失败

**Comment by Alvin9999** [comment]
@jackandma 要用最新的AllNew全新版

**Comment by mygithubyc** [comment]
今天早上可以了，昨天晚上不行，thanks!

**Comment by mygithubyc** [comment]
> 有没有更新ip？

今天早上可以了，昨天晚上不行，thanks!

**Comment by jackandma** [comment]
@Alvin9999 用的是3月4号发布的AllNew全新版，所有的ip更新都失败

**Comment by Alvin9999** [comment]
@jackandma  ip更新失败的截图发一下看看呢

**Comment by jackandma** [comment]
[image: 1.png]
[image: 2.png]
[image: 3.png]
[image: 4.png]
[image: 5.png]
[image: 6.png]
[image: 7.png]
[image: 8.png]
[image: 9.png]
[image: 10.png]
[image: 11.png]
[image: 12.png]
[image: 13.png]
[image: 14.png]

自由上网 <notifications@github.com> 于2020年4月5日周日 下午9:33写道：

**Comment by Alvin9999** [comment]
@jackandma 看不到图片哦

**Comment by jackandma** [comment]
我重新发了个邮件发到您 notifications@github.com 邮箱了

自由上网 <notifications@github.com> 于2020年4月5日周日 下午10:06写道：

**Comment by Alvin9999** [comment]
@jackandma  发到kebi2014@gmail.com

**Comment by jackandma** [comment]
您好，我又给这个kebi2014@gmail.com邮箱也发了一份

自由上网 <notifications@github.com> 于2020年4月5日周日 下午10:06写道：
