### ISSUE TITLE
ssr端口几分钟就被封

### ISSUE THREAD

**Issue by RoastEgg** [Alvin9999/new-pac#867]
![image](https://user-images.githubusercontent.com/11443423/78748384-81efee00-799e-11ea-9400-aea0a484c9a2.png)

配置如图

**Comment by Alvin9999** [comment]
端口换5位数看看

**Comment by Litangren** [comment]
参见此文https://github.com/Alvin9999/new-pac/issues/856

**Comment by Litangren** [comment]
www.vultr.com的服务器太慢太慢。。。。ping丢包很严重。试过日本、新加坡、悉尼、美国、欧洲.....
