### ISSUE TITLE
请教一下pac的来源

### ISSUE THREAD

**Issue by IRISlMaple** [Alvin9999/new-pac#87]
是自己架构的吗，最近速度好一些的pac全部挂完了，寻思着能不能自己动手丰衣足食。特来请教！
感谢！

**Comment by Alvin9999** [comment]
对，PAC是自己搭建的。挂完了不至于，因为每天看到都有流量产生，也就是使用人数还有。不过，自己学习一下搭建方法还是好的。参考教程：https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAPAC%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B

**Comment by IRISlMaple** [comment]
@Alvin9999 Thank you very much~!
