### ISSUE TITLE
32Bit的4.9版Allnew里，Trojan用的是64bit版本

### ISSUE THREAD

**Issue by Alobe007** [Alvin9999/new-pac#870]
在32bit Win7上运行不了。

**Comment by Alvin9999** [comment]
不对哦，trojan应该是windows版，目前没分32和64位。你是怎么看出来trojan是64位呢？

其他人也是这个情况么？

**Comment by Alobe007** [comment]
> 不对哦，trojan应该是windows版，目前没分32和64位。你是怎么看出来trojan是64位呢？
> 
> 其他人也是这个情况么？

运行时显示：此文件的版本与正在运行的Windows版本不兼容。请检查计算机的系统信息以了解需要x86（32位）还是x64（64位）版本的程序，然后联系软件发布者。

**Comment by Alvin9999** [comment]
32位回退了trojan版本，你可以重新下载，然后再试试看

**Comment by Alobe007** [comment]
> 32位回退了trojan版本，你可以重新下载，然后再试试看

现在可以了。非常感谢。
