### ISSUE TITLE
今天晚上怎么所有工具全都慢得要命？

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#873]
youtube、ins图片半天不显示，视频卡着半天没反应 ，trojan、brook、lightsocks、v2ray全都如此。是服务器带宽不够？还是传输被墙干扰了？

**Comment by qdhfqdhf** [comment]
刚才用的v2ray，刚一打开速度秒开。结果几分钟之后就time out了，再不能用了！到底是被服务器限制带宽了？还是流量被墙给嗅探了？

**Comment by Alvin9999** [comment]
可能是用的人太多的缘故吧。除了SSR，没有进行限速。一般来说，晚上是上网高峰期，白天会好很多。当然，各个地区封锁强度不同，使用效果也会有差别。

**Comment by cckkrr** [comment]
为什么图片无法显示，可是是能上的

**Comment by AnyWAT** [comment]
XX-Net 也是，至少图片加载、显示很慢，或许与某日志 mtalk.google.com（unknown 0，正常貌似是1）相关？
