### ISSUE TITLE
AllNew版本怎样配合idm下载？

### ISSUE THREAD

**Issue by xianggithubli** [Alvin9999/new-pac#877]
AllNew版本怎样配合idm下载？

**Comment by Litangren** [comment]
Goflyway 127.0.0.1:8100 
XX-Net 127.0.0.1:8087
trojan socks5://127.0.0.1:1080
Brook socks5://127.0.0.1:2080
Lightsocks socks5://127.0.0.1:7448
DAZE 127.0.0.1:3080
SSR 127.0.0.1:1080
v2ray socks5://127.0.0.1:10808
SSROT socks5://127.0.0.1:1080

**Comment by xianggithubli** [comment]
![idm01](https://user-images.githubusercontent.com/14290317/79677822-baf25300-8227-11ea-91f6-63f19eea3c26.png)
![idm02](https://user-images.githubusercontent.com/14290317/79677829-c34a8e00-8227-11ea-9812-a5e15844a373.png)
brook这样设置吗 ,下载不了呢？
