### ISSUE TITLE
可以做成一个综合版吗？

### ISSUE THREAD

**Issue by Jason4774** [Alvin9999/new-pac#88]
这些软件只是代理的软件不一样，但是都是谷歌或者火狐，可以火狐或者谷歌都做成一个版本吗？然后代理工具自己来修改，这样只需要写一个切换代理的教程就好了，不然分成很多版本，每次下载后更新都要下载很多。

**Comment by Alvin9999** [comment]
有的会冲突，曾经试过。我觉得目前这种方式挺好的。

一般来说，自己选一种适合自己的就可以了，那么每次专门更新一款即可，最多其它的也就备用一两款。

**Comment by Jason4774** [comment]
不会啊。什么会冲突，我就是集合了很多软件，你以前也下载过我的看过，真的这样更新就很简单，你只需要更新软件比如goproxy的版本，然后更新gae.user.json就好， 因为我觉得现在你这里做的有点多了就感觉有点乱。下载多个版本的话里面的谷歌浏览器又都是一样的，就觉得比较麻烦。

**Comment by Alvin9999** [comment]
谢谢你的建议，我考虑下。

**Comment by Jason4774** [comment]
谢谢，然后我在其他issue里面问你可以分享一下你的ip段吗？并进行随时更新，这样可以自己来搜索。因为你的ip段还是很有用。

**Comment by candy2107** [comment]
@Jason4774 
其实这个ip段来源于 goagent-always-available ，你找这个项目就行了
issues里面不要把ip贴出来，以免被封

**Comment by Jason4774** [comment]
@Alvin9999 @candy2107 好的，确实ip用的人多了，谷歌这些网站都会让输入验证码之类的 。

**Comment by Alvin9999** [comment]
我分享的搜ip教程里面已经有50多万的ip段，现在够用了，没必要更新，以后需要的时候再更新。

**Comment by Jason4774** [comment]
恩。对了，mff那个帖子里面下面k大又更新了一次mff，你可以更新一下。

**Comment by Alvin9999** [comment]
@Jason4774  最后一个版本会搜到不是谷歌证书的ip，不适合新手使用。

**Comment by Jason4774** [comment]
@Alvin9999 请问lantern那一版好像多数时候不能用啊？

**Comment by Alvin9999** [comment]
是不是最新版？

**Comment by Alvin9999** [comment]
你用我分享的浏览器打开看看

**Comment by Jason4774** [comment]
就是

**Comment by Alvin9999** [comment]
有没有用国产杀毒软件？

**Comment by Jason4774** [comment]
稍等

**Comment by Jason4774** [comment]
没有， 我裸奔

**Comment by Alvin9999** [comment]
你看能不能把我的版本让你朋友测试一下，人多点好，这样我就知道这个版本效果如何，便于之后的更新

**Comment by Jason4774** [comment]
恩。我刚试了可以，只是我之前用的时候很不稳定，很多时候用不了。

**Comment by Jason4774** [comment]
对了可以问下你这2.2.5是在哪里找的吗？和我之前用的那个2.2.5好像也一样，我是用k主任的补丁打了之后去弹窗的，然后我自己也是和你一样的方法去开机自启和修改系统代理，就是通过修改那个文件全部为false。

**Comment by Alvin9999** [comment]
根据我自己的测试和别人用，目前的版本效果不错，已经今非昔比了，但能持续用多久还是未知的。如果未来哪天不好用了，希望你能帮忙提醒一下我

**Comment by Alvin9999** [comment]
也是网上找的，应该是同一个吧。之前确实不好用，但最近发现效果不错，所以重新启用了。

**Comment by Alvin9999** [comment]
本来lantern版我是暂停更新的

**Comment by Alvin9999** [comment]
@Jason4774   请在你的说明里加上，“首选GoAgent和GoProxy”，因为这两款用的是谷歌服务器，谷歌服务器抗压强，不用担心使用人数多的问题。但如果是PAC或GoGo或萤火虫或Lantern，这些翻墙方式，只要人数使用过多，在开发者不增加服务器的基础上，必然会造成速度变慢且会对vps服务器造成压力。所以，能用GoAgent和GoProxy最好，其它方式为备选。

我曾经将GoProxy和PAC版合并，推测是因为使用GoProxy版的人数有一部分采用了PAC代理方式，结果造成PAC几乎全部失效，过了一段时间才缓过劲来，后来我就取消了这种合并方式。

**Comment by Jason4774** [comment]
所以pac你是怕用的人太多了吗？确实之前我用的时候有时候也会失效

**Comment by Jason4774** [comment]
如果pac你怕失效的话你可以把其他的软件合并到一起，到时候我给你发一个我的版本，就是全部集成到一起的，也没有影响，

**Comment by Jason4774** [comment]
1
45.76.197.251:25
2
47.88.223.222:25
3
47.88.172.54:25
4
45.32.56.64:25
45.77.22.158:25
5
pac1.nagro.net:25
这个是你pac的服务器地址，其实我更喜欢这种http代理，配合meow/cow或者代理规则表，比pac里面的规则表好多了。

**Comment by Alvin9999** [comment]
目前不考虑制作综合版

**Comment by Jason4774** [comment]
请问Chrome+.exe这个文件是怎么弄的啊？

**Comment by Alvin9999** [comment]
@Jason4774  这个我也不会，是别人制作的。顺便问下，你那里有其它好用的其它lantern吗？想做一个备用。

**Comment by Alvin9999** [comment]
@Jason4774   我想制作一个与SS相关的便携版浏览器，请问你会吗？我希望达到的效果是，不打开SS客户端，但能够直接用浏览器翻，也就是把ss客户端以及ss账号信息内置在浏览器里面。以前网上有一款chromegae的浏览器，就是用的这种方式，我曾发邮件希望作者教一下，但作者不愿意。
