### ISSUE TITLE
此次疫情还是体现出社会主义制度的优越性的

### ISSUE THREAD

**Issue by zhtyyx** [Alvin9999/new-pac#880]
支持社会主义

**Comment by Alvin9999** [comment]
共产党隐瞒疫情，不仅造成武汉人民在无知的情况被大量染病失去生命，还造成疫情扩散到全球。十分邪恶！

**Comment by AnyWAT** [comment]
全是铁证据！谁在隐瞒真相？ - https://mp.weixin.qq.com/s/b4Il8Tqr9lhrwY5_Gm5ZEg

**Comment by zhtyyx** [comment]
我一向以为程序员至少是理性客观，明辨是非的，看来诸位不是这样，也就没什么好说的了

**Comment by Alvin9999** [comment]
如果你能翻墙，还是建议你多多了解客观真实的资讯，多了解真相吧。

**Comment by Alvin9999** [comment]
[首部探究中共病毒疫情真相的紀錄片](https://www.youtube.com/watch?v=3bXWGxhd7ic) （英文版）

[首部探究中共病毒疫情真相的紀錄片](https://www.youtube.com/watch?v=EIOPHnWFE40) （中文字幕版）

**Comment by Alvin9999** [comment]
百度贴吧-哈尔滨  总关注数146万，目前帖子被删的差不多了，昨天还有3页，今天只剩2页，全是吧主发的贴子。如今哈尔滨疫情爆发的厉害，还在管控言论，老百姓得不到真实的资讯！大陆正在营造一种假象！

![哈尔滨1](https://user-images.githubusercontent.com/12132898/80163907-282c2c80-860a-11ea-8f64-bf71dab8e667.PNG)
![哈尔滨2](https://user-images.githubusercontent.com/12132898/80163909-28c4c300-860a-11ea-9295-6fbd976ce6ec.PNG)

**Comment by AnyWAT** [comment]
> 大陆正在营造一种假象！

😂一直一直。。。

**Comment by AnyWAT** [comment]
楼下保安员说：‘如果我是方方，我会把日记留言区所有辱骂的信息也結集，附在日记后面一同出版。我甚至觉得，后者更有文物价值。’
😂故无需删除他人任何言论？

**Comment by yoy-aww** [comment]
我就想问问, @Alvin9999  这个狗B, 现在还觉得 首部探究中共病毒疫情真相的紀錄片 （英文版） 是正确的吗?
贱人自有东方收
