### ISSUE TITLE
Who is tue true virus?

### ISSUE THREAD

**Issue by danxinzhujian** [Alvin9999/new-pac#882]
。

**Comment by Emeryout19** [comment]
粉蛆记得天亮后去给党国殉葬哦，为期不远啦：）

**Comment by Alvin9999** [comment]
[首部探究中共病毒疫情真相的紀錄片](https://www.youtube.com/watch?v=3bXWGxhd7ic) （英文版）

[首部探究中共病毒疫情真相的紀錄片](https://www.youtube.com/watch?v=EIOPHnWFE40) （中文字幕版） [备用地址](https://www.ntdtv.com/gb/2020/04/11/a102821093.html)

**Comment by danxinzhujian** [comment]
Alvin9999就是病毒

**Comment by Alvin9999** [comment]
希望您多多了解真相，在非常时期，真相能保命。

**Comment by danxinzhujian** [comment]
你认为中国不好，别在中国待了，去你的美帝啊。看看感染病毒你的精神祖国给不给你治

**Comment by Alvin9999** [comment]
@danxinzhujian  中共与中国以及中华民族是三个不同的概念。我爱中国、爱中国人民，中国人很善良、勤劳，也很辛苦。

**Comment by danxinzhujian** [comment]
你认为的中国是什么？台湾吗？中国共产党真正做到了为人民服务，面对灾难力挽狂澜，这不是事实吗？你看看美国已经死了多少人。反倒是台湾第一时间禁止往大陆出口口罩，这样的地方领导也配领导中华民族？看看台湾已经什么样子了，认为大陆人吃不起茶叶蛋吃不起榨菜，对美国日本就是跪舔

**Comment by tianxinyueming** [comment]
我感觉做这种事请真的没有任何意义，这就跟你租房子一样，如果你觉得房子不舒服，你再换一家租就好了，现在中国也没有强制中国人不能移民，如果觉得中国的制度不适合你，你完全可以移民到美国，加拿大等国家，在那里好好工作生活，当一个遵纪守法的好公民，在那里能够是你的身体和精神都是愉悦的，这无论从哪方面来说对你来说都是最好的，我认为你在国内对你精神上是一种折磨，这是很痛苦的。所以我给你的建议是：Emigrate now and have a happy life，而不是像网上的黑粉一样黑生养自己的地方。

**Comment by danxinzhujian** [comment]
你的美爹给你钱了，让你祸害真正的祖国

**Comment by Alvin9999** [comment]
百度贴吧-哈尔滨  总关注数146万，目前帖子被删的差不多了，昨天还有3页，今天只剩2页，全是吧主发的贴子。如今哈尔滨疫情爆发的厉害，还在管控言论，老百姓得不到真实的资讯！大陆正在营造一种假象！

![哈尔滨1](https://user-images.githubusercontent.com/12132898/80163907-282c2c80-860a-11ea-8f64-bf71dab8e667.PNG)
![哈尔滨2](https://user-images.githubusercontent.com/12132898/80163909-28c4c300-860a-11ea-9295-6fbd976ce6ec.PNG)

**Comment by AnyWAT** [comment]
> 大陆正在营造一种假象！

😂一直一直。。。

**Comment by AnyWAT** [comment]
楼下保安员说：‘如果我是方方，我会把日记留言区所有辱骂的信息也結集，附在日记后面一同出版。我甚至觉得，后者更有文物价值。’
😂故无需删除他人任何言论？
