### ISSUE TITLE
由贵单位管理

### ISSUE THREAD

**Issue by liao6964799** [Alvin9999/new-pac#883]
浏览器设置里出现  由贵单位管理  这个正常吗？

**Comment by Alvin9999** [comment]
试试这个https://www.daniao.org/4609.html

**Comment by liao6964799** [comment]
好奇怪 我自己的chrome没有 但是软件里的chrome里有，而且按照那个网址的方法 ，我的注册表不存在那个键值，这。。。

**Comment by Alvin9999** [comment]
是有点奇怪，测试没有这个，可能是你电脑环境导致的，你删掉文件夹，重新解压看看呢
