### ISSUE TITLE
想咨询一下GoAgent如何配置其他下载youtube的软件~

### ISSUE THREAD

**Issue by hyunbb** [Alvin9999/new-pac#89]

**Comment by Alvin9999** [comment]
将下载youtube的软件的代理设置成127.0.0.1 8087

**Comment by hyunbb** [comment]
[http://wx1.sinaimg.cn/large/703b581fly1fhieetn0dwj20dq066q39.jpg](url) 不行 经常出现这个错误。

**Comment by Alvin9999** [comment]
推荐几个可以直接下载youtube视频的网站：

http://www.clipconverter.cc/
http://zh.keepvid.com/
https://savemedia.com/

**方法：用翻墙浏览器打开，然后把你想下载的视频的地址放上去就可以了**

**Comment by IRISlMaple** [comment]
把goagent设置成系统代理，用youtube-dl下就好了。不设置的话也可以直接在youtube-dl命令行设置代理下载。

**Comment by caofengzi** [comment]
chrome和火狐都有y2b視頻的下載腳本，安裝使用腳本下載不需要任何設置，只需要安裝一個腳本管理擴展程序即可，goa的下載速度還是不錯的。
