### ISSUE TITLE
ss突然不能用了求助

### ISSUE THREAD

**Issue by HClCH** [Alvin9999/new-pac#90]
chrome用着用着就突然没有数据传输了，刷新页面出现ERR_EMPTY_RESPONSE，经测试hosts和dns正常，请问是哪里的问题呢

**Comment by Alvin9999** [comment]
你用的我分享的哪个服务器 呢？

**Comment by candy2107** [comment]
你是不是用移动的网络？
刚用手机的移动数据试试，居然连不上任何的ss或ssr服务器
也许是移动封锁了非 80/443 端口的数据
换成联通宽带一切正常

**Comment by candy2107** [comment]
你是不是用移动的网络？
刚用手机的移动数据试试，居然连不上任何的ss或ssr服务器
也许是移动封锁了非 80/443 端口的数据
换成联通宽带一切正常

**Comment by Alvin9999** [comment]
服务器1，2，3失效，请更换其它的服务器

**Comment by Alvin9999** [comment]
之前公开出来的账号可能被屏蔽或者被别人DDOS，造成服务器没法使用。刚刚替换了ip，已更新。
