### ISSUE TITLE
goflyway的免费账户返回invalid websocket错误

### ISSUE THREAD

**Issue by yyr03gy** [Alvin9999/new-pac#907]
使用当前tr12.free5555.xyz，tr13.free5555.xyz两个免费账户都不能科学上网，返回如下借误：
2020-06-04 10:41:32.603 CST,client.go:394, ERROR ,"Dial failed: invalid websocket response from www.google.com:443: HTTP/1.1 521 Origin Down
Date: Thu, 04 Jun 2020 02:41:32 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d9ccc4c2dffe47a4dab2bfc84ff4b6f5f1591238492; expires=Sat, 04-Jul-20 02:41:32 GMT; path=/; domain=.free5555.xyz; HttpOnly; SameSite=Lax
Cache-Control: no-store, no-cache
cf-request-id: 031ecd99550000e7e1ec89a200000001
Server: cloudflare
CF-RAY: 59de4ba22ff9e7e1-LAX

"

**Comment by Alvin9999** [comment]
已更新

**Comment by yyr03gy** [comment]
实测可以了
