### ISSUE TITLE
分享的ssr免费账号用的哪个机房？

### ISSUE THREAD

**Issue by wufan-bit** [Alvin9999/new-pac#909]
我买的vultur机房几乎全都不能用，不是连不上就是谷歌学术被ban，想问下免费的账号是哪里的机房

**Comment by Alvin9999** [comment]
谷歌学术对翻墙方式要求很高，可以尝试搭建v2ray

**Comment by Alvin9999** [comment]
免费ss入帐号可以访问谷歌学术？

**Comment by Alvin9999** [comment]
https://oneprovider.com/
