### ISSUE TITLE
ssr是不是用不了了

### ISSUE THREAD

**Issue by zgd716** [Alvin9999/new-pac#911]
大佬,弱弱问一句:ssr那个账号(162.245.239.68)是不是用不了了,多谢大佬的分享

**Comment by fuckGFW2015** [comment]
对

**Comment by Alvin9999** [comment]
端口被封，已更新

**Comment by zgd716** [comment]
> 对

大佬更新的1001 端口,你能用吗?我这边怎么还是不能用

**Comment by zgd716** [comment]
> 端口被封，已更新

大佬,辛苦

**Comment by Alvin9999** [comment]
密码也变了

**Comment by zgd716** [comment]
> 密码也变了

账号：162.245.239.68

端口：1001

密码： dongtaiwang.com

加密方式：RC4

协议：origin

混淆：plain



大佬,我就是用的您这一套,我的是ubuntu系统,我再试试,多谢大佬
