### ISSUE TITLE
自己搭建的v2ray不超过半小时端口就被封了

### ISSUE THREAD

**Issue by jersonal** [Alvin9999/new-pac#914]
自己搭建了v2ray，用着很流畅，但是不超过半个小时就玩不了了，更换端口又可以用半小时，有时候甚至ip也特别容易被封，各位老铁有什么好的推荐吗？我是104.168.xxx.xxx的IP。没有TLS，因为没有域名。传输方式：mKCP 伪装 BT下载流量，用其他的传输方式也一样。加密方式用过none和其他。

**Comment by bannedbook** [comment]
上 ws+TLS

**Comment by 5m17h** [comment]
mKCP 秒封，相当于在警察局值班室门口拉客

**Comment by jersonal** [comment]
> mKCP 秒封，相当于在警察局值班室门口拉客

我自己搭建了，ws + TLS 至今半年了没有被封

**Comment by 0neday** [comment]
试试[ trojan-gfw](https://github.com/trojan-gfw/trojan)，选 vultr 日本或美国西海岸节点
