### ISSUE TITLE
别玩虚的，提供账号密码就行

### ISSUE THREAD

**Issue by skyformat99** [Alvin9999/new-pac#919]
简单点；
查询点学术资料而已，别玩虚的

**Comment by Emeryout19** [comment]
討飯的跑來裝大爺,人家有求你用嗎

**Comment by skyformat99** [comment]
> 討飯的跑來裝大爺,人家有求你用嗎

你奶奶个熊，还玩繁体，臭不要脸的湾湾。鄙视

**Comment by jersonal** [comment]
> 简单点；
> 查询点学术资料而已，别玩虚的



> > 討飯的跑來裝大爺,人家有求你用嗎
> 
> 你奶奶个熊，还玩繁体，臭不要脸的湾湾。鄙视

你别出来丢大陆的脸了，大陆没你这么穷，出来讨账号

**Comment by skyformat99** [comment]
> > 简单点；
> > 查询点学术资料而已，别玩虚的
> 
> > > 討飯的跑來裝大爺,人家有求你用嗎
> > 
> > 
> > 你奶奶个熊，还玩繁体，臭不要脸的湾湾。鄙视
> 
> 你别出来丢大陆的脸了，大陆没你这么穷，出来讨账号

套你老母。你马哥拔插，吃力的榨菜去吧，傻逼湾湾儿

**Comment by jersonal** [comment]
> > > 简单点；
> > > 查询点学术资料而已，别玩虚的
> > 
> > 
> > > > 討飯的跑來裝大爺,人家有求你用嗎
> > > 
> > > 
> > > 你奶奶个熊，还玩繁体，臭不要脸的湾湾。鄙视
> > 
> > 
> > 你别出来丢大陆的脸了，大陆没你这么穷，出来讨账号
> 
> 套你老母。你马哥拔插，吃力的榨菜去吧，傻逼湾湾儿

@Alvin9999 瞧一瞧，这个人真的恶心
