### ISSUE TITLE
北京电信，貌似已全部阵亡

### ISSUE THREAD

**Issue by LokiSpark** [Alvin9999/new-pac#921]
rt，golfway，brook，Trojan，都不行了，更新了up也不行

**Comment by LokiSpark** [comment]
更新了下防火墙，ok了

**Comment by Alvin9999** [comment]
有的人的win10系统默认的防火墙会起干扰作用

**Comment by 466034505** [comment]
> rt，golfway，brook，Trojan，都不行了，更新了up也不行

用二爷翻墙
