### ISSUE TITLE
树莓派的ssr客户端？

### ISSUE THREAD

**Issue by 123ABCDF11345** [Alvin9999/new-pac#922]
求一个树莓派的ssr客户端，32位官方系统的

**Comment by Alvin9999** [comment]
https://github.com/shadowsocksr-backup/shadowsocksr/releases

**Comment by 123ABCDF11345** [comment]
好像只有服务器端的有Linux版，而且架构还不一样...我这边是arm架构的

**Comment by 123ABCDF11345** [comment]
Closed，because of long time without answering
