### ISSUE TITLE
ss方式无法上网 今天凌晨可以 中午就不行了

### ISSUE THREAD

**Issue by zhangtuo1999** [Alvin9999/new-pac#925]
今天凌晨购买了Just My Socks账户（500G/mo），凌晨使用ss科学上网时网速很快YouTube视频1080p无卡顿。中午起床之后发现无法正常科学上网。

**Comment by zhangtuo1999** [comment]
已成功解决，换了个服务器就可以了

**Comment by Alvin9999** [comment]
好
