### ISSUE TITLE
每次失效就需要重新下载包含浏览器的压缩包，文件太大，能否简化该过程？

### ISSUE THREAD

**Issue by yezhigangzju** [Alvin9999/new-pac#929]
我每次失效就需要重新下载包含浏览器的压缩包，文件太大，请问能否简化该过程？比如建立一个分支，我们用户fetch一下，即可知道修改过的内容，然后替换本地即可。或者其他方式，反正其实每次需要下载整个包含浏览器的文件，实在太慢了，有时候还下载不了。

**Comment by Alvin9999** [comment]
集合版里面的工具都自带ip更新程序，一般来说更新ip即可，除非有一些大的变动才会发布新版。

**Comment by Alvin9999** [comment]
有2个网盘下载地址，可以用普通浏览器下载，如果速度慢也可以换用翻墙浏览器来下载

**Comment by yezhigangzju** [comment]
好的，感谢解答！
