### ISSUE TITLE
教程网页打不开

### ISSUE THREAD

**Issue by ttwwxk** [Alvin9999/new-pac#93]
http://www.ishouyou.cn/news/jiaocheng/1608.html

**Comment by Alvin9999** [comment]
该网站被屏蔽且原来的教程不好用，待我更新一下。

**Comment by Alvin9999** [comment]
教程已更新：https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAPAC%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B
