### ISSUE TITLE
ssr bt下载链接太多会导致服务器cpu占用高到死机么

### ISSUE THREAD

**Issue by Qiuchi0918** [Alvin9999/new-pac#934]
如题，我跟着教程走的ssr和加速的流程，挂着它bt下载一段时间后有几率服务器会死机。我试了试用cpulimit把占用最高的那个给限制到80然而还是会卡死，求问大佬这个怎么解决？需要限制连接数么还是什么？
![image](https://user-images.githubusercontent.com/64412747/87883714-c0845280-ca3b-11ea-95ed-9c98f92aa163.jpg)
![image](https://user-images.githubusercontent.com/64412747/87883707-ac405580-ca3b-11ea-8bf0-b54fd4aed479.jpg)

**Comment by Alvin9999** [comment]
crontab -e
* * * * * /etc/init.d/ssr start

试试看

**Comment by jap33** [comment]
bt直接用就可以了，各种代理都直接封bt的。

**Comment by Qiuchi0918** [comment]
> crontab -e
> ***** /etc/init.d/ssr start
> 
> 试试看

额是我没表达清楚。。我是在windows上用ssr下载bt，然后vps死机了，我现在怀疑是不是被攻击。。放了几个小时它自己也会死

**Comment by Qiuchi0918** [comment]
> bt直接用就可以了，各种代理都直接封bt的。

运营商网太烂不挂连得人太少速度不行。。

**Comment by Alvin9999** [comment]
你看下不开服务的时候，后台CPU一直是100%吗

**Comment by Qiuchi0918** [comment]
> 你看下不开服务的时候，后台CPU一直是100%吗

不确定，开服务有时也没事，两天内上传下载了100多g，不确定什么时候就会突然死掉

那我不开服务放一天试试

**Comment by Qiuchi0918** [comment]
到目前没有再死机
