### ISSUE TITLE
感谢发布者分享免费账号！终于可以科学上网了

### ISSUE THREAD

**Issue by 11612206** [Alvin9999/new-pac#936]
如题，本人词比较穷，真的十分感谢发布者分享免费账号让我科学上网。给大家一些参考：华北，edge，ssr两个账号均可用。真心希望发布者以后能动态更新免费账号信息，不胜感激！

**Comment by Alvin9999** [comment]
会长期更新下去的。如果好用，可以分享给自己的好朋友，帮助他们了解外面的世界。

**Comment by haitaoss** [comment]
我想问问作者有速度稳定或者自建的机场嘛，想花钱买一个速度快又稳定一点的，因为使用需求比较大😊

**Comment by Alvin9999** [comment]
@haitaoss  可以考虑[justmysocks](https://github.com/Alvin9999/new-pac/wiki/Just-My-Socks) ，当然也可以自己搭建[ss教程教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by haitaoss** [comment]
> @haitaoss 可以考虑[justmysocks](https://github.com/Alvin9999/new-pac/wiki/Just-My-Socks) ，当然也可以自己搭建，参考[自建ss服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

谢谢回复，一个人用自建有点不划算，还是买别人的比较方便。

**Comment by 0neday** [comment]
如果条件允许，可以试试自己自建。vps厂商vultr，有一个 充10$ 送 50$ 的活动，可以试试看，活动地址[https://www.vultr.com/promo/try50/](https://www.vultr.com/promo/try50/?ref=7538023)

**Comment by 774471872** [comment]
最近的一键复制链接挺好的，感谢！
