### ISSUE TITLE
7.28 00:17 貌似挂了

### ISSUE THREAD

**Issue by kiki1027** [Alvin9999/new-pac#938]
如上

**Comment by Alvin9999** [comment]
什么工具挂了？

**Comment by kiki1027** [comment]
> 什么工具挂了？

shadowsocks

**Comment by Alvin9999** [comment]
用的什么帐号？ssr ss帐号？3个ssr帐号 1个ss帐号都不能用？

**Comment by kiki1027** [comment]
> 用的什么帐号？ssr ss帐号？3个ssr帐号 1个ss帐号都不能用？

大概是我设备的问题，同一个账号手机端可以访问成功，pad上失败了

感谢回复，可以关闭issue了🤘🏻

**Comment by Alvin9999** [comment]
好的
