### ISSUE TITLE
国内移动网络用户反馈专用贴

### ISSUE THREAD

**Issue by Alvin9999** [Alvin9999/new-pac#942]
移动宽带使用软件如果遇到问题或者速度很慢，可以进行反馈。

同时，十分欢迎大家反馈不同工具的速度。

**Comment by root1005214** [comment]
移动宽带下无法代理
<img width="835" alt="截屏2020-09-26 上午11 02 05" src="https://user-images.githubusercontent.com/21187208/94328816-3a126100-ffe8-11ea-83a6-1c615ce3a2c5.png">
<img width="627" alt="截屏2020-09-26 上午11 04 12" src="https://user-images.githubusercontent.com/21187208/94328828-4ac2d700-ffe8-11ea-8f77-e857416d493b.png">

**Comment by root1005214** [comment]
macOS 
<img width="835" alt="截屏2020-09-26 上午11 02 05" src="https://user-images.githubusercontent.com/21187208/94329127-b8700280-ffea-11ea-8ac7-f522acdcdf8b.png">
goflyway  移动宽带无法代理。

**Comment by Alvin9999** [comment]
> macOS
> <img alt="截屏2020-09-26 上午11 02 05" width="835" src="https://user-images.githubusercontent.com/21187208/94329127-b8700280-ffea-11ea-8ac7-f522acdcdf8b.png">
> goflyway 移动宽带无法代理。

3个账号都不能用吗

**Comment by root1005214** [comment]
是的，都不可以，以前发布的一些账号也都不可以用，
但在电信宽带下，都可以正常访问。
<img width="627" alt="截屏2020-09-26 上午11 04 12" src="https://user-images.githubusercontent.com/21187208/94335299-35ac6f00-000d-11eb-936a-7d438869c895.png">

**Comment by Alvin9999** [comment]
噢！那这种情况的话，还不好解决。建议更换工具，比如使用v2ray

**Comment by LunaticTian** [comment]
移动针对pac模式还有很多图片挂了，比如github上的图片...
