### ISSUE TITLE
有些网站会跳转到nginx

### ISSUE THREAD

**Issue by neunundneunzig** [Alvin9999/new-pac#947]
会出现Welcome to nginx!页面
刷新后无法正常载入

dial tcp 127.0.0.1:80: connect: connection refused

**Comment by Alvin9999** [comment]
什么网站？

**Comment by neunundneunzig** [comment]
urbandictionary.com

**Comment by Alvin9999** [comment]
已修复，可以再试试看

**Comment by mesutozil1088** [comment]
还是会显示这样的

> This site can’t provide a secure connection
urbandictionary.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

如果要屏蔽黄色网站的话
是不是可以手动添加几个大站就行了，不然会误封，或者高峰时段直接限流量就好了

**Comment by Alvin9999** [comment]
> 还是会显示这样的
> 
> > This site can’t provide a secure connection
> > urbandictionary.com sent an invalid response.
> > Try running Windows Network Diagnostics.
> > ERR_SSL_PROTOCOL_ERROR
> 
> 如果要屏蔽黄色网站的话
> 是不是可以手动添加几个大站就行了，不然会误封，或者高峰时段直接限流量就好了

你用的什么工具？

**Comment by mesutozil1088** [comment]
用的brook会显示这样

换成goflyway会变成

> This site can’t be reached
The webpage at https://www.urbandictionary.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKS_CONNECTION_FAILED

或者是网站自己的问题，不知道了。。

**Comment by mesutozil1088** [comment]
换naiveproxy就可以打开网站了

**Comment by Alvin9999** [comment]
> 换naiveproxy就可以打开网站了

OK
