### ISSUE TITLE
请问能不能使用之前国家的IP？

### ISSUE THREAD

**Issue by xxx1320** [Alvin9999/new-pac#948]
现在更新的是日本的ip，很多网站无法上
之前乌克兰 俄罗斯的都可以

**Comment by Alvin9999** [comment]
第三个是俄罗斯ip

**Comment by xxx1320** [comment]
第三个是指？
我用的Chrome83_64bit_AllNew_2020.7.7里的SSR

**Comment by Alvin9999** [comment]
ip1和ip2都尝试了吗

**Comment by Alvin9999** [comment]
ip2是俄罗斯的ip

**Comment by xxx1320** [comment]
有了
昨天刷1 2都日本的
现在是乌克兰了 但是还是有网站不像之前那样能打开

**Comment by Alvin9999** [comment]
什么网站？

**Comment by xxx1320** [comment]
某几个瑟情网站：spankbang，xvideos等等
这两天变日本ip之前还能开
但是这不是头次出现这问题
更早前也是这几个网站不能开，不知道后来为什么又都行了

**Comment by Alvin9999** [comment]
跟ip的位置无关。屏蔽了黄色网站。
