### ISSUE TITLE
Lantern视频看不了

### ISSUE THREAD

**Issue by yy0535** [Alvin9999/new-pac#95]
Lantern视频看不了看不了720和1080，请帮助

**Comment by Alvin9999** [comment]
你的意思是Lantern可以看视频，只是看不了超清视频吗？

因为各个地区封锁的强度不同且宽带类型不同,所以会造成使用速度不一样 。有的地区很快，有的地区一般，有的很慢。

我分享的软件类型很多，可以自己测试看看哪款最适合自己的网络。理论上，为了节省服务器流量，便于大家都能使用，不建议看1080p视频。

**Comment by 349205055** [comment]
网速慢，就看不了呗
