### ISSUE TITLE
勿用所提供工具登录facebook！

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#951]
我的账号被封了，现在要求手机验证码。原因不明但是高度怀疑是所用工具IP乱跳触发了fb的反广告机制。而惨的是我用的大陆+86手机号收不到验证码，已经两天了，fb要求每24小时只能请求一次验证码发送，估计账号是回不来了！

**Comment by Alvin9999** [comment]
如果ip被封了或者速度很慢，是会换ip的。

**Comment by Alvin9999** [comment]
如果是要固定ip的话，建议自己搭建翻墙服务器。

**Comment by Alvin9999** [comment]
网上有一些国外手机号收验证码的网站，可以试试看
