### ISSUE TITLE
安装锐速

### ISSUE THREAD

**Issue by chen510260x** [Alvin9999/new-pac#956]
安装锐速，到了选择锐速版本号的时候，提示没取到锐速版本，怎么回事

**Comment by Alvin9999** [comment]
再试一次看看。有没有操作第一步，更换内核？

**Comment by chen510260x** [comment]
@Alvin9999 第一步更换内核已经做了，到第二步就出现那个提示了

**Comment by Alvin9999** [comment]
我刚更新了加速脚本和教程，可以用最新的
