### ISSUE TITLE
安卓 SSR客户端下载及更新地址网页404

### ISSUE THREAD

**Issue by ttwwxk** [Alvin9999/new-pac#96]
安卓 SSR客户端下载及更新地址网页404了，

**Comment by kobeking** [comment]
@ttwwxk ssr项目停更了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus ONEPLUS A3000 发送_

**Comment by candy2107** [comment]
[download](https://github.com/shadowsocksr-backup/shadowsocksr-android)

**Comment by candy2107** [comment]
(download link](https://github.com/shadowsocksr-backup/shadowsocksr-android/releases]

**Comment by candy2107** [comment]
(download link)[https://github.com/shadowsocksr-backup/shadowsocksr-android/releases]

**Comment by candy2107** [comment]
(download-link)[https://github.com/shadowsocksr-backup/shadowsocksr-android/releases]

**Comment by candy2107** [comment]
[download-link](https://github.com/shadowsocksr-backup/shadowsocksr-android/releases)
