### ISSUE TITLE
trojan电脑端正常手机端不正常

### ISSUE THREAD

**Issue by ChrisAtticus** [Alvin9999/new-pac#967]
我这边手机端正常，可是电脑端连接不上，请问该怎么解决呢，时间是正常的。以前可以用，现在就不行了

**Comment by Alvin9999** [comment]
自己搭建的trojan帐号吗

**Comment by Alvin9999** [comment]
可能是被系统防火墙、杀毒软件干扰了，可以关闭它们再试试看

**Comment by ChrisAtticus** [comment]
> 可能是被系统防火墙、杀毒软件干扰了，可以关闭它们再试试看

火绒和防火墙均已经关闭,但仍然连接不上

**Comment by Alvin9999** [comment]
http://port.ping.pe/
打开这个网址，输入ip:端口号 ，冒号为英文状态下输入，然后截图一下结果，如果下面为红色，那么就说明端口被封了，如果都是绿色，那么说明服务是正常的，就是其它原因

**Comment by jap33** [comment]
![捕获](https://user-images.githubusercontent.com/15140842/91746930-04987480-ebf0-11ea-823a-7b095a563810.PNG)
这样是不是封了，v2 ip2。

**Comment by Alvin9999** [comment]
@jap33  是的，这种显示表明端口在国内不通，被封了，正在更新。

**Comment by Alvin9999** [comment]
v2ray ip2已更新

**Comment by jap33** [comment]
v2ray ip2已更新
还是不行，

**Comment by Alvin9999** [comment]
端口被封的有点快，又更新了下，可以再试试看

**Comment by jap33** [comment]
可以了，

**Comment by Alvin9999** [comment]
OK。有问题欢迎反馈哈，维护的东西有点多，不一定能及时发现。
