### ISSUE TITLE
Goflyway，vray都不能用了

### ISSUE THREAD

**Issue by aboutqx** [Alvin9999/new-pac#970]
几个ip都试了

**Comment by Alvin9999** [comment]
4个ip都尝试了吗？goflyway第一次打开网页的时候要多等待一下

**Comment by Alvin9999** [comment]
封锁有加重的趋势。刚刚对不能用的v2ray ip配置更新了一下，可以试试看。如果都不能用，可以试试软件中其它的工具。

**Comment by aboutqx** [comment]
。。。昨天vray可以的，现在试了下都不行了。

**Comment by aboutqx** [comment]
Vray可以了，用url可以了，应该是参数没填对，但是昨天可以啊，很奇怪

**Comment by aboutqx** [comment]
看了下，导入的tr24那个服务器，底层传输需要填tls

**Comment by Alvin9999** [comment]
嗯,已修改

**Comment by Alvin9999** [comment]
goflyway试试带ip那个
