### ISSUE TITLE
我没找到生成config文件的选项，是压根就没有这个选项吗？

### ISSUE THREAD

**Issue by bayzhen** [Alvin9999/new-pac#972]

**Comment by Alvin9999** [comment]
新脚本没有这个选项，输入v2ray url可以生成vmess链接，可以快速导入到v2rayN客户端里面，如果你用的是v2ray官方客户端，建议换成v2rayN客户端。[使用方法](https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%90%84%E5%B9%B3%E5%8F%B0%E5%9B%BE%E6%96%87%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B)

**Comment by Alvin9999** [comment]
旧脚本可以直接下载config文件，访问这个老地址：https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B/aa5a85752369a0b2e7f9d2e2d6a1b3ea836f1328

**Comment by Alvin9999** [comment]
![v2ray-001](https://user-images.githubusercontent.com/12132898/92144465-52f48000-ee49-11ea-8357-8dc1309508fa.PNG)

新脚本安装成功后，输入v2ray进入管理页面可下载config文件

**Comment by Alvin9999** [comment]
更新了脚本，并增加了一个脚本[新教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)
