### ISSUE TITLE
用了linux客户端怎么连接不上呢？

### ISSUE THREAD

**Issue by LiveLys** [Alvin9999/new-pac#975]
![image](https://user-images.githubusercontent.com/21288914/92302174-90b5ed80-ef9c-11ea-8e59-959ac2351629.png)
是配置错了吗？换了好几个帐号都不行

**Comment by Alvin9999** [comment]
加密方式为RC4，不是RC4-MD5

**Comment by Alvin9999** [comment]
你需要用linux ssr客户端

**Comment by LiveLys** [comment]
> 你需要用linux ssr客户端
这个不是linux ssr客户端吗？能不能给个下载链接？我当时下载的时候提示我就是Linux客户端，另外，加密里面我就找到一个rc4-md5。。

**Comment by Alvin9999** [comment]
加密方式还有哪些？有没有aes-256-gcm 截图看一下

**Comment by Alvin9999** [comment]
等会我增加2个ss帐号

**Comment by LiveLys** [comment]
![image](https://user-images.githubusercontent.com/21288914/92302843-053f5b00-efa2-11ea-9e42-23955cecac1e.png)
大概是这个样，还有就是帐号中，给了帐号密码，但是这个工具只有一个 填写密码的地方，怎么弄？

**Comment by Alvin9999** [comment]
密码就填帐号中的密码就可以了

**Comment by Alvin9999** [comment]
已增加ss帐号

**Comment by Alvin9999** [comment]
可以试试看

**Comment by Alvin9999** [comment]
本地服务器类型选择HTTP，不是socks

**Comment by LiveLys** [comment]
测试了一下，显示可以正常连接，但是google,youtube都无法打开。。。

**Comment by Alvin9999** [comment]
截图看看你设置的信息

**Comment by Alvin9999** [comment]
截图看看你设置的信息

**Comment by LiveLys** [comment]
![image](https://user-images.githubusercontent.com/21288914/92308694-36378400-efd2-11ea-8505-7462a91c01b7.png)
![image](https://user-images.githubusercontent.com/21288914/92308699-45b6cd00-efd2-11ea-9267-4d833ecab54e.png)
麻烦看下

**Comment by Alvin9999** [comment]
密码是多少

**Comment by LiveLys** [comment]
123abc

**Comment by Alvin9999** [comment]
密码填写不完整

**Comment by Alvin9999** [comment]
ntdtv.com 123abc

**Comment by LiveLys** [comment]
@Alvin9999 还是不行，密码直接复制你的，然后 还是无法上网

**Comment by Alvin9999** [comment]
再截图看一下,保留密码明文显示,我对linux不是特别熟悉,浏览器代理设置了吗

**Comment by Alvin9999** [comment]
试试socks5 127.0.0.1 1080

**Comment by Alvin9999** [comment]
参考:https://shadowsockshelp.github.io/Shadowsocks/linux.html

**Comment by Alvin9999** [comment]
可以了吗

**Comment by bailinkai** [comment]
https://my.vultr.com/
我创建的实例，为什么没有显示都快两个小时了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alvin9999/new-pac"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 中午1:47
收件人:&nbsp;"Alvin9999/new-pac"<new-pac@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Alvin9999/new-pac] 用了linux客户端怎么连接不上呢？ (#975)





 
可以了吗

**Comment by Alvin9999** [comment]
截图看看

**Comment by LiveLys** [comment]
@Alvin9999 不好意思一直不行

**Comment by Alvin9999** [comment]
> @Alvin9999 不好意思一直不行

截图再看看
