### ISSUE TITLE
trojan-go闪退

### ISSUE THREAD

**Issue by qdhfqdhf** [Alvin9999/new-pac#978]
命令提示符下运行有如下提示
![ddsadas](https://user-images.githubusercontent.com/47769695/93036503-a600db00-f672-11ea-9dbb-3f829fa17d9a.png)
前不久win10刚刚升级到2004。

**Comment by Alvin9999** [comment]
关闭win10防火墙后试试看

**Comment by qdhfqdhf** [comment]
> 关闭win10防火墙后试试看

没有用。关防火墙、防火墙加白名单都不行。

**Comment by Alvin9999** [comment]
可以下载最新版。trojan运行库安装没有？

**Comment by qdhfqdhf** [comment]
> 可以下载最新版。trojan运行库安装没有？

全都没用。已经是最版的了。

**Comment by Alvin9999** [comment]
ip1和ip2都尝试了吗

**Comment by jap33** [comment]
ip1和ip2都尝试了吗 
都挂啦

**Comment by Alvin9999** [comment]
> ip1和ip2都尝试了吗
> 都挂啦

已修复

**Comment by qdhfqdhf** [comment]
现在的类似问题也出在naiveproxy，也是闪退，命令提示符运行提示
[0916/194009.757:INFO:naive_proxy_bin.cc(455)] Proxying via https://tr10.freedom104.xyz
[0916/194009.761:ERROR:tcp_socket_win.cc(352)] bind() returned an error: 以一种访问权限不允许的方式做了一个访问套接字的 尝试。 (0x271D)
[0916/194009.764:ERROR:naive_proxy_bin.cc(583)] Failed to listen: -10
brook也是闪退，运行提示
listen tcp 127.0.0.1:2080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
查了一下这几个错误的原因有可能是端口被封了，无解。

**Comment by Alvin9999** [comment]
> 现在的类似问题也出在naiveproxy，也是闪退，命令提示符运行提示
> [0916/194009.757:INFO:naive_proxy_bin.cc(455)] Proxying via https://tr10.freedom104.xyz
> [0916/194009.761:ERROR:tcp_socket_win.cc(352)] bind() returned an error: 以一种访问权限不允许的方式做了一个访问套接字的 尝试。 (0x271D)
> [0916/194009.764:ERROR:naive_proxy_bin.cc(583)] Failed to listen: -10
> brook也是闪退，运行提示
> listen tcp 127.0.0.1:2080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
> 查了一下这几个错误的原因有可能是端口被封了，无解。

从你的信息看，ip沒有更新成功

**Comment by jap33** [comment]
trojan ip1挂啦

**Comment by Alvin9999** [comment]
> trojan ip1挂啦

已修复
