### ISSUE TITLE
蓝灯版和pac版都不能用了

### ISSUE THREAD

**Issue by l8277239** [Alvin9999/new-pac#98]
前两天刚下载蓝灯版速度挺快的 现在速度只有十几k是不是被限制了 还有pac版速度也不行了 只剩pac2的线路而且非常慢 请问能修复吗 不行的话就算了 毕竟是免费的  也感谢作者无私奉献 注意身体哦 听说it人员很累的

**Comment by Alvin9999** [comment]
蓝灯版为网上破解版，有可能是地区不同所以使用效果不同。按照官方的说法，每月流量超过500M后会被限速到20kb/s。这个破解版有的人反馈还行，有的人反馈不行，可能跟地区不同所造成的破解效果不同的缘故吧。

PAC版请使用最新版本，增加了PAC代理地址。且刚刚修复了PAC1，由于使用人数有点多，为了更好的分配资源，PAC服务器会进行一定的限速，但一般看普通清晰度的视频没问题。

除了上面的版本以外，你还可以试试其它版本。考虑到不同地区使用效果会不同，所以我分享的软件类型很多。大致选择顺序是GoAgent，GoProxy，SS，PAC，Lantern，GoGo，萤火虫。

**Comment by l8277239** [comment]
@Alvin9999 谢谢作者百忙之中能回答我的问题 我试过好多破解版的蓝灯结果都是一样 使用多了会限制速度 可能是破解不完整 另外文件夹当中有一个蓝灯一键配置的软件 我双击了提示说退出浏览器和代理按回车键继续 我照做了 然后窗口下面提示找不到目标就马上自动关闭了 这个算是起作用了吗 我试过好多次都没有作用 如果顺利的话是不是会恢复速度呢

**Comment by Alvin9999** [comment]
如果你使用蓝灯一段时间速度都还没有恢复，那说明你那里的网络环境或地区不适合用蓝灯破解版。鉴于这种情况，可以考虑更新其它版本。

**Comment by l8277239** [comment]
@Alvin9999  找到原因了 果然是没有破解完整 如果速度明显变慢了那说明被官方限制了 改下mac地址就可以恢复高速了 另外现在又有个严重的问题 不知道是不是我按到保留设置的原因 前天弹出一个保留设置和恢复设置的选项我点保留设置 后来就老是提示连接不上代理服务器 必须重启浏览器才可以上 然后又上不了十分钟 请问这个怎么修复啊 我把浏览器文件夹全删了重新下载还是这个问题

**Comment by Alvin9999** [comment]
点保留设置没问题。
你的问题有可能是杀毒软件在干扰。如果lantern程序被误删了也就上不了网了。你具体用的哪款蓝灯版？
