### ISSUE TITLE
免费账号全部挂了

### ISSUE THREAD

**Issue by jinyumarine** [Alvin9999/new-pac#981]
全挂了

**Comment by Alvin9999** [comment]
刚刚调整了下，再试试看

**Comment by jinyumarine** [comment]
> 刚刚调整了下，再试试看

不能用，接收没网
另外SS账号也一样

**Comment by Alvin9999** [comment]
服务正常，很多人再用。可以排除一下防火墙和杀毒软件的干扰。

**Comment by jinyumarine** [comment]
> 服务正常，很多人再用。可以排除一下防火墙和杀毒软件的干扰。

手机，原来一切都正常的，早上开始不能用，不管是数据还是WiFi

**Comment by Alvin9999** [comment]
帐号界面截图看一下

**Comment by jinyumarine** [comment]
> 帐号界面截图看一下

![Screenshot_2020-09-19-11-33-54-919_in zhaoj shadowsocksrr](https://user-images.githubusercontent.com/31756681/93658202-11c8b680-fa6c-11ea-94b7-c89cac1ae743.jpg)

**Comment by jinyumarine** [comment]
> 帐号界面截图看一下

![Screenshot_2020-09-19-11-33-54-919_in zhaoj shadowsocksrr](https://user-images.githubusercontent.com/31756681/93658221-3a50b080-fa6c-11ea-8178-f94be1d63d38.jpg)

**Comment by Alvin9999** [comment]
看不到，黑屏

**Comment by jinyumarine** [comment]
> 帐号界面截图看一下

另外开启SSR后，连这个网站都打不开，只能停了SSR
关键所有账号都没下行网速，为0

**Comment by jinyumarine** [comment]
> 看不到，黑屏

截图不了，我还以为我手机深色模式原因，换正常模式还是截黑屏

**Comment by Alvin9999** [comment]
帐号信息是否填写正确了？密码中有一个空格

**Comment by Alvin9999** [comment]
这个问题并不普遍。目前服务是正常的，和平时没有什么区别。可以找找其它原因，比如手机设置，或者重启下手机看看。

**Comment by jinyumarine** [comment]
> 这个问题并不普遍。目前服务是正常的，和平时没有什么区别。可以找找其它原因，比如手机设置，或者重启下手机看看。

用了无数方法，就差恢复出厂设置了，还是无解，唉

**Comment by Alvin9999** [comment]
电脑能用吗

**Comment by Alvin9999** [comment]
如果ss/ssr帐号实在用不了，可以换v2ray或goflyway

**Comment by Alvin9999** [comment]
@jinyumarine 如果有新进展可以留言
