### ISSUE TITLE
谷歌高内核Astar版 ipad 能使用吗？

### ISSUE THREAD

**Issue by yDan** [Alvin9999/new-pac#982]
谷歌高内核Astar版 ipad 能使用吗？

**Comment by Alvin9999** [comment]
不行哦
可以用离线安装shadowrocket来使用ss/ssr帐号

**Comment by yDan** [comment]
那苹果电脑MAC能使用吗？

**Comment by Alvin9999** [comment]
不能，只适用于windows系统

**Comment by Alvin9999** [comment]
苹果Mac可以用v2ray

**Comment by yDan** [comment]
Astar 那个谷歌插件好像要准备收费了是不是？

**Comment by yDan** [comment]
Astar 那个谷歌插件好像要准备收费了是不是？

**Comment by Alvin9999** [comment]
不知道哦,不是我开发的

**Comment by Alvin9999** [comment]
有这种可能

**Comment by yDan** [comment]
还有没有像这样快速的谷歌插件啊？

**Comment by Alvin9999** [comment]
> 还有没有像这样快速的谷歌插件啊？

没有。这个插件你收到了什么收费提示么？

**Comment by yDan** [comment]
因为我看到插件的官网已经有保费计划了。估计要准备收费了

**Comment by Alvin9999** [comment]
> 因为我看到插件的官网已经有保费计划了。估计要准备收费了

这样啊，那估计就是了。也许到时候会有免费节点，速度快的节点收费。

**Comment by Alvin9999** [comment]
![捕获](https://user-images.githubusercontent.com/12132898/94336920-36e39900-0019-11eb-86b6-88a5de558879.PNG)

**Comment by Alvin9999** [comment]
看到了
