### ISSUE TITLE
谷歌浏览器集合版要怎么删除呢？

### ISSUE THREAD

**Issue by AmoubLee** [Alvin9999/new-pac#983]

**Comment by AmoubLee** [comment]
安装了之后连不上网了，是把文件删除就可以了吗

**Comment by Alvin9999** [comment]
谷歌浏览器集合版没有安装一说 , 因为是便携版 ,打开后使用.当然,如果不想用,可以删掉文件.

**Comment by Alvin9999** [comment]
便携版不是安装文件,上不了网可能是其它原因.

**Comment by Alvin9999** [comment]
可以这样排查一下,打开ie浏览器-internet选项-连接-局域网设置,看看"为LAN使用代理服务器”前面有没有勾，如果有，去掉它。
如果没有，可以重启下电脑看看。

**Comment by AmoubLee** [comment]
谢谢大佬，还有一个问题就是：只有集合版的谷歌浏览器能出去？其他谷歌浏览器或者其他浏览器能不能fanqiang，我看ssr里面账号已经登录，能否用其他浏览器进行科学上网？还是只能用下的这个谷歌浏览器进行科学上网

**Comment by Alvin9999** [comment]
如果想便捷的上网，用这个集合版就可以了。如果想用其它浏览器上网，需要设置浏览器的代理。这个你需要自己学一下。

**Comment by AmoubLee** [comment]
我用proxy switchyomega设置好了，但是只能使用你开发好的那个版本，我用其他浏览器就不能科学上网或者只能用我之前弄好的pac脚本，只能打开Google搜索，不能像你做好的那样能打开所有网站

**Comment by Alvin9999** [comment]
按理说，代理设置好了应该就可以，如果帐号是一样的话。
