### ISSUE TITLE
免费账号信息访问不了推特

### ISSUE THREAD

**Issue by MuYunyun** [Alvin9999/new-pac#987]
感谢楼主大大提供免费账号。最近一个星期没法访问了 https://www.twitter.com/, 有什么解决方法吗?

**Comment by Alvin9999** [comment]
用的哪个账号，截图看看

**Comment by syhufo** [comment]
v2ray帐号正常,可以试试

**Comment by MuYunyun** [comment]
![image](https://user-images.githubusercontent.com/19354791/95275966-82e5d780-087c-11eb-8143-e074850823a0.png)

试了这几个好像 fq 都挂了, 代理状态如下:

![image](https://user-images.githubusercontent.com/19354791/95276056-b9235700-087c-11eb-859d-480fef538f64.png)

**Comment by Alvin9999** [comment]
你用的账号已经失效了，请查看最新账号。

**Comment by MuYunyun** [comment]
试了这几个, 还是上不了 :smile:

德国 | 89.163.245.185 | 23456 | dongtaiwang.com 666nice | RC4 | origin | plain | 220kb/s
莫斯科 | 85.117.235.151 | 12345 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s
洛杉矶1 | 195.123.240.241 | 8888 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s
洛杉矶2 | 67.21.68.252 | 23456 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s

**Comment by Alvin9999** [comment]
> 试了这几个, 还是上不了 😄
> 
> 德国 | 89.163.245.185 | 23456 | dongtaiwang.com 666nice | RC4 | origin | plain | 220kb/s
> 莫斯科 | 85.117.235.151 | 12345 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s
> 洛杉矶1 | 195.123.240.241 | 8888 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s
> 洛杉矶2 | 67.21.68.252 | 23456 | ntdtv.com 123abc | RC4 | origin | plain | 220kb/s

看看你的密码是怎么设置的

**Comment by MuYunyun** [comment]
ss://cmM0OmRvbmd0YWl3YW5nLmNvbSA2NjZuaWNlQDg5LjE2My4yNDUuMTg1OjIzNDU2
ss://cmM0OgludGR0di5jb20gMTIzYWJjQDg1LjExNy4yMzUuMTUxOjEyMzQ1
ss://cmM0Om50ZHR2LmNvbSAxMjNhYmNAMTk1LjEyMy4yNDAuMjQxOjg4ODg
ss://cmM0Om50ZHR2LmNvbSAxMjNhYmNANjcuMjEuNjguMjUyOjIzNDU2

这是我的设置

**Comment by Alvin9999** [comment]
推测你是ss客户端，但你用的是ssr帐号，所以用不了，如果要用ss帐号，可以用最后那2个帐号，那2个帐号才是ss帐号

**Comment by MuYunyun** [comment]
我用的是 ssr 客户端, 之前用免费账号都是可以访问 twitter 的, 最近一个星期不行, 我再看看吧。

**Comment by Alvin9999** [comment]
> 我用的是 ssr 客户端, 之前用免费账号都是可以访问 twitter 的, 最近一个星期不行, 我再看看吧。

好。实在不行可以换v2ray

**Comment by Alvin9999** [comment]
也可以试试这个新增的ssr帐号
加利福尼亚：107.148.240.162  端口：12345 密码： dongtaiwang.com 123abc  加密方式：aes-256-cfb 协议：origin 混淆：plain

**Comment by MuYunyun** [comment]
> 也可以试试这个新增的ssr帐号
> 加利福尼亚：107.148.240.162 端口：12345 密码： dongtaiwang.com 123abc 加密方式：aes-256-cfb 协议：origin 混淆：plain

试了也不行, 我去下载 v2ray 了😭

**Comment by Alvin9999** [comment]
> > 也可以试试这个新增的ssr帐号
> > 加利福尼亚：107.148.240.162 端口：12345 密码： dongtaiwang.com 123abc 加密方式：aes-256-cfb 协议：origin 混淆：plain
> 
> 试了也不行, 我去下载 v2ray 了😭

系统防火墙关闭也试试看

**Comment by MuYunyun** [comment]
感谢楼主, 账号没问题, 是 chrome 插件导致的。

**Comment by Alvin9999** [comment]
> 感谢楼主, 账号没问题, 是 chrome 插件导致的。

OK
