### ISSUE TITLE
关于PAC问题

### ISSUE THREAD

**Issue by feidizai** [Alvin9999/new-pac#99]
请问能更新下自建PAC的教程吗，还有自建的PAC最近无法上网，能出个如何自建和隐蔽代码的教程吗，就像PAC1和PAC2一样，服务器的代码是隐藏的，请问这个是什么方法做到的

**Comment by Alvin9999** [comment]
把需要隐藏的内容用这个转换一下格式即可
网址：https://javascriptobfuscator.com/Javascript-Obfuscator.aspx

**Comment by feidizai** [comment]
非常感谢

**Comment by Alvin9999** [comment]
请问你自建的PAC服务器还能用，最近我发现PAC这种代理方式不太好用了，不知道你有没有遇到过这种情况？
