### ISSUE TITLE
轮子？

### ISSUE THREAD

**Issue by JikQ** [Alvin9999/new-pac#993]
推荐的频道啥狗屁玩意儿，你也是轮子？？？

**Comment by Alvin9999** [comment]
建议您多多了解真相。

**Comment by JikQ** [comment]
> 建议您多多了解真相。

以为我没看过吗？都讲的什么烂玩意儿，偷换概念，主观臆想，模糊猜测，没有事实根据的事情讲了几年了吧。也就只能自我高潮，带轮子一起遁入环境了，哈哈哈哈。
