### ISSUE TITLE
连接通但是无法访问网站

### ISSUE THREAD

**Issue by JinLuhuan** [Alvin9999/new-pac#994]
连接畅通 但是无法访问网站
<img width="586" alt="WX20201019-154919@2x" src="https://user-images.githubusercontent.com/59244967/96416832-1e832a80-1223-11eb-8544-d2978502c5f5.png">

以下是ssr配置
<img width="209" alt="WeChat30adfeda9b153961ad2c14b45f253b3d" src="https://user-images.githubusercontent.com/59244967/96416898-365aae80-1223-11eb-9b49-4f81d7afd991.png">
![1603093821657](https://user-images.githubusercontent.com/59244967/96416910-3a86cc00-1223-11eb-850d-910848f17c85.jpg)

系统代理是软件自动设置：
<img width="592" alt="WeChat139ba6b6b9f24c049d9df0acba95a7de" src="https://user-images.githubusercontent.com/59244967/96416992-57230400-1223-11eb-880e-0b53edd812da.png">

浏览器代理使用的是系统代理：
<img width="187" alt="WeChat6e4ef07962f699a9df045c28e11f36be" src="https://user-images.githubusercontent.com/59244967/96417062-6f931e80-1223-11eb-9bdd-6e13368f1f48.png">

存在的问题是我的pac文件不能访问
访问 http://127.0.0.1:8090/proxy.pac
Status Code: 400 Invalid header received from client

**Comment by Alvin9999** [comment]
帐号密码填写对没有呢？

**Comment by Alvin9999** [comment]
提醒一下，帐号密码中有一个空格。如果帐号信息填写正确，可以重新尝试下前面2个帐号，即西雅图和德国帐号。
