### ISSUE TITLE
兄弟们，哪个工具速度快点啊

### ISSUE THREAD

**Issue by badongdyc** [Alvin9999/new-pac#996]
最近用goflyway感觉好慢啊，哪个工具速度快点啊，坐标成都

**Comment by Alvin9999** [comment]
不同地区使用效果不一定都一样，可以自己尝试下

**Comment by Alvin9999** [comment]
提醒一下，Golfyway有4个ip，ip1 ip2 ip3 ip4，如果没有都试过，可以都试试看

**Comment by badongdyc** [comment]
Goflyway有4个ip?我怎么只有一个啊，难道更新了？

**Comment by Alvin9999** [comment]
嗯，很久了吧，看来你不怎么关注官网哦

**Comment by badongdyc** [comment]
官网是这个吗https://tr1.freeair888.club/，只要能用我一般不会来，只有出问题我我才来看看😂

**Comment by Alvin9999** [comment]
没事，下载最新版即可

**Comment by Alvin9999** [comment]
你发的那个网址和github会同步更新

**Comment by badongdyc** [comment]
好的，谢谢，我多试几个
