### ISSUE TITLE
关于快速启动的cmd

### ISSUE THREAD

**Issue by cangjieBlue** [Alvin9999/new-pac#997]
命令
`%1 start "" mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c %~s0 ::","","runas",1)(window.close)&&exit`
这种获取权限的方法似乎在某些win10下，会因为空格字符的原因失效；
`%1 mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c "^&chr(34)^&"%~0"^&chr(34)^&" ::","%cd%","runas",1)(window.close)&&exit`
替换成这种就可以运行了

**Comment by Alvin9999** [comment]
谢谢分享

**Comment by Alvin9999** [comment]
好像不行噢，这种情况发生时，直接启动chrome快捷方式也不行，貌似不是这个问题。
